### ISSUE TITLE
Plotting phase diagrams for more than 4 elements

### ISSUE THREAD

**Issue by Leila1234** [materialsproject/pymatgen#1000]
Hello, 
I would like to plot the phase diagram of a metal composition with more than 4 elements but now it's possible just for 1-4 elements. It says: `ValueError: Only 1-4 components supported!`
Would you please guide me if there is any possibility to solve the problem?

**Comment by shyuep** [comment]
There is no way to plot a phase diagram in more than 4 terminals in 3D space.
