### ISSUE TITLE
Standalone function for d_hkl to define size of structures

### ISSUE THREAD

**Issue by richardtran415** [materialsproject/pymatgen#1002]
Is there a stand alone function that returns d_hkl given a structure and a Miller index? I know the class XRDPattern() has something that gets d_hkl, but I don't that can be used outside the class right? This would be useful for things like if we wanted a standard nlayer of atoms of slab thickness or gb thickness thats not defined by length scale where the number atoms would vary across different systems (e.g. a 10 Angstrom slab/gb of Cs would only have n layer of atoms while the same size slab/gb for Fe would have a larger number of layer of atoms.

**Comment by shyuep** [comment]
Don't think there is right now. By all means implement it in the Slab class.

**Comment by mkhorton** [comment]
A function to go from three PeriodicSites to output a (h,k,l) tuple would be nice to have too.

**Comment by richardtran415** [comment]
@mkhorton  Just to clarify, do you mean something that would generate a plane with any 3 PeriodicSites and then return the hkl of that plane?

**Comment by mkhorton** [comment]
@richardtran415 yes, that's exactly what I meant -- to my knowledge this isn't in pymatgen currently?

**Comment by richardtran415** [comment]
@shyuep 
Actually I think a function for getting d_hkl might be more at home as a method of the Lattice class, its not standalone, but at least its accessible outside xrd.py, but I agree the function to describe slab thickness in terms of nlayers should be part of class Slab().

**Comment by shyuep** [comment]
that's fine. Implement then.
