### ISSUE TITLE
BoltzTrap2

### ISSUE THREAD

**Issue by shyamd** [materialsproject/pymatgen#1003]
## Summary
It looks like Madsen group has released a new major version upgrade of BoltzTrap that is written in python/cython/C++ : https://arxiv.org/abs/1712.07946

The current BoltzTrap module is very hairy. It would be good to get it rewritten to wrap the new BoltzTrap2 module and in the process improve the code quality and documentation.

**Comment by shyuep** [comment]
No objections. Are you volunteering to do the rewrite?

**Comment by shyamd** [comment]
Nope. Should probably be some of the thermoelectrics people since they will be using the new code anyways and will need the secondary analysis currently implemented in our boltztrap module.

**Comment by shyuep** [comment]
@computron can I ask you to suggest who is the best candidate to do this (not asking your esteemed self to do it)? It does not have to be someone from your group.

**Comment by fraricci** [comment]
I had a look at the new implementation of Boltztrap and I find it could be great to interface pymatgen with it, both solving different problems and having a much smoother boltztrap module.
I think I could spend sometime on it.
One thing that could be limiting is that bzt2 is only python3.
This means that the user will be forced to upgrade to use the boltztrap.
Probably not a big deal because it is just matter of time, as also pymatgen will 
stop supporting py2 soon (right?)

**Comment by shyuep** [comment]
pmg already abandoned Py2 support from 2018. New code does not have to support Py2.

Thank you in advance for volunteering to implement. I am sure it would be a good help to the research community.

**Comment by fraricci** [comment]
Update:
I've been working on a new module to interface pymatgen and BoltzTraP2.
I pushed a first version in my fork:
[boltztrap2](https://github.com/fraricci/pymatgen/tree/boltztrap2)

In the example folder, you can find a ipynb:
[How to use Boltztra2 interface](https://github.com/fraricci/pymatgen/blob/boltztrap2/examples/How%20to%20use%20Boltztra2%20interface.ipynb)
that explain roughly how it works.
There, PbTe case has been considered and the results shown are comparable 
with results from BZT1.

The module is still under development, no documentation is provided, so
for the moment I won't do any pull request to the master.

If someone (thinking about @computron, @albalu, @hautierg,... ) want to 
have a look and have comments, it would be great.

**Comment by computron** [comment]
From our side I think @albalu and @ardunn should take a look, they will likely be the most heavy users (Alireza in short term, Alex in long term)

**Comment by fraricci** [comment]
FYI: the development of BoltzTraP2 is now on gitlab
https://gitlab.com/sousaw/BoltzTraP2

**Comment by ziechys** [comment]
Hi @fraricci 
thanks for the new BoltzTrap2 interface. 
Do you plan to implement a read/load function for Boltztrap2 calculations? 
So you load the .btj and can run your Plotter than? This would avoid a subsequent boltztrap run for each plot. 
Or did you implement it and I just do not find it.

**Comment by fraricci** [comment]
Hi @ziechys , boltztrap2 has already such function. 
I have to see if it's better to implement it in a different way or the native one is good enough. 
It's an important function so I'll put it higher in the todo list.
Thanks.

**Comment by shyamd** [comment]
@fraricci 
Is it JSON? If not, it might still be usefull to have something that is JSON or atleast BSON compliant.

**Comment by shyamd** [comment]
Taken care of in #1307
