### ISSUE TITLE
Algorithm to convert Miller index to Somorjai microfacet/step notation for surfaces

### ISSUE THREAD

**Issue by richardtran415** [materialsproject/pymatgen#1009]
The microfacet/step notation for Miller indices is a convention used to define the step and terraces of higher Miller index surfaces based on low Miller index surfaces. E.g. the (331) facet of an fcc crystal can be defined by the (111) facet.
For fcc system, an exmaple would be:
(hkl) = (n+1, n+1, n-1) 
Microfacet notation: n_n(111) + 1_1(11-1)
Step notation: (n+1)(111)x(111)

This can be useful in catalytic studies where steps play an important role in surface energy and can also be used in studies involving modelling surface energy or work function relative to the values of low miller index facets.

However Somorjai has only developed this for cubic systems, it make take a little bit of further investigation to generalize this beyond cubic systems....
 
See:
Van Hove, M. A., & Somorjai, G. A. (1980). A new microfacet notation for high-Miller-index surfaces of cubic materials with terrace, step and kink structures. Surface Science, 92(2-3), 489–518. https://doi.org/10.1016/0039-6028(80)90219-8

**Comment by shyuep** [comment]
I would say this is not of the highest priority unless you have a clear idea of the generalization approach.
