### ISSUE TITLE
miller_index.py in util folder

### ISSUE THREAD

**Issue by richardtran415** [materialsproject/pymatgen#1025]
For organization, I would suggest a python module in the utils folder for containing functions and classes related to Miller indices. Functions such as get_symmetrically_distinct_miller_indices in the surface.py module can be moved here along with other related functions such as a function to get_symmerically_equivalent_miller_indices, miller_index_from_sites, convert from hkl to hkil for hexagonal systems, parse to a latex format (e.g. (1,-2,3) would be ($1 \bar{2} 3$)), etc.

**Comment by shyuep** [comment]
No. Miller indices are not a util package thing. It is specific to planes in crystals. Leave it in surface.py.

**Comment by richardtran415** [comment]
OK
