### ISSUE TITLE
Vasprun.from_dict() error 

### ISSUE THREAD

**Issue by mamachra** [materialsproject/pymatgen#1047]
When trying to create a Vasprun object from Vasprun.from_dict(d), the following error happens:

TypeError: __init__() got an unexpected keyword argument 'vasp_version'

This deserves a fix for users that need Vasprun object to be in a dict format for later uses.

**Comment by shyuep** [comment]
No one uses the from_dict for Vasprun as far as I know. Under what circumstances would you want to do this?

**Comment by skasamatsu** [comment]
Hi. I came across this problem as well. My use case was for saving very long MD trajectories where vasp is run several times in series. I would feed the Vaspruns into the DiffusionAnalyzer in series to monitor the mean square displacement after each vasp run, and do another subsequent vasp MD run if the MSD doesn't seem to be equilibrated enough.

**Comment by shyuep** [comment]
You need to be more specific on what is the exact error you seen. The DiffusionAnalyzer for MD calculations do not use from_dict at all.

**Comment by skasamatsu** [comment]
Sorry for being unclear. That was just explaining why I would want to save a Vasprun as_dict for later use with from_dict. The code snippet and error are as follows:

`from pymatgen.io.vasp import Vasprun
from pymatgen import MontyEncoder,MontyDecoder
import json

myvasprun = Vasprun("vasprun.xml",parse_dos=False,parse_eigen=False,ionic_step_skip=5)

with open('vasprun.json','w') as f:
    json.dump(myvasprun, cls=MontyEncoder, fp=f)

with open("vasprun.json","r") as f:
    vasprun = json.load(f, cls=MontyDecoder)`

and the error:
`Traceback (most recent call last):
  File "vasprun_json.py", line 11, in <module>
    vasprun = json.load(f, cls=MontyDecoder)
  File "/home/k0306/k030600/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/k0306/k030600/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/home/k0306/k030600/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/monty/json.py", line 228, in decode
    return self.process_decoded(d)
  File "/home/k0306/k030600/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/monty/json.py", line 210, in process_decoded
    return cls_.from_dict(data)
  File "/home/k0306/k030600/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/monty/json.py", line 105, in from_dict
    return cls(**decoded)
TypeError: __init__() got an unexpected keyword argument 'vasp_version'`
