### ISSUE TITLE
In pymatgen, is it possible to partially substitute atoms?

### ISSUE THREAD

**Issue by joniserra** [materialsproject/pymatgen#1053]
What I would like to do is the following:
 For a given POSCAR file I would like to select some atoms and substitute them partially. I know I can remove them partially with PartialRemoveSitesTransformation module in pymatgen.transformations.site_transformations. You provide a list of positions and a fraction to be removed and the program returns a list of electrostatically most stables vacancy configurations. I would like to know if there is any posibility of doing the same but instead of removing atoms substituing them with another atom.
Thanks in advanced
Jon

**Comment by shyuep** [comment]
Github issues should only be used for reporting problems. For help, pls post on the Google groups.

Look at the examples. For example: http://pymatgen.org/_static/Ordering%20Disordered%20Structures.html
