### ISSUE TITLE
Several issues with EnumlibAdaptor

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/pymatgen#1063]
## System

* Pymatgen version: affects several versions, using 2018.3.13
* Python version: 3.6
* OS version: macOS 10.13.3

## Summary

* [This line](https://github.com/materialsproject/pymatgen/blob/f9d984d25b550ff04e534a4a67f18a52799dee68/pymatgen/command_line/enumlib_caller.py#L227) causes a crash in a small percentage of disordered structures (~5%), where it tries to pop from an empty list
* When `check_ordered_symmetry` is True, some site properties are not propagated correctly in the enumerated structure. This leads to exceptions elsewhere in pymatgen, e.g. anywhere a new structure object is initialized from the enumerated structure, as the site property key is only present on some sites of the enumerated structure
* [This line](https://github.com/materialsproject/pymatgen/blob/f9d984d25b550ff04e534a4a67f18a52799dee68/pymatgen/command_line/enumlib_caller.py#L245) seems like it doesn't do anything
* [This test](https://github.com/materialsproject/pymatgen/blob/f9d984d25b550ff04e534a4a67f18a52799dee68/pymatgen/command_line/tests/test_enumlib_caller.py#L94) expects to return 10, but reliably returns 16 for me and for a colleague too. This may be related to `check_ordered_symmetry`, but I'm not sure. I'm also not sure why the CI hasn't caught this.

* I'm still investigating this, if I find a good minimal example or a fix I'll post it here.

**Comment by shyuep** [comment]
1. I don't actually quite understand the situation where the first error will occur. If the ordered sites list is empty, then the disordered symmetry should be equal to the full symmetry. I can put in a break, but I am confused when such an issue would occur.
2. Also not clear why this will occur. The sites are not modified as far as I can tell....
3. Removed.
4. What version of enumlib are you running? My machine, which is running latest enumlib, returns 10.

I addressed 1 and 3. See https://github.com/materialsproject/pymatgen/commit/a73c0967b42c67450d800693094c9fdba681f240

**Comment by mkhorton** [comment]
For 4., I re-compiled using the latest version from their repo to double check it wasn't an issue with a fault installation. Previously, I was using 1.0.8.

**Comment by shyuep** [comment]
@mkhorton can you do a structure matcher of the 16 structures you get to check if any of them are similar?

**Comment by mkhorton** [comment]
Will do ... perhaps that part could actually be an spglib issue, will try reinstalling that too.

**Comment by mkhorton** [comment]
Ok, StructureMatcher reports 7 to be equivalent, which accounts for the discrepancy. I've attached all 16: [enumlib_structures.txt](https://github.com/materialsproject/pymatgen/files/1813154/enumlib_structures.txt)

My understanding is that EnumerateStructureTransformation filters out equivalent structures, so this issue would probably not be encountered in production unless someone uses EnumlibAdaptor directly.

**Comment by mkhorton** [comment]
Ok, here are two examples for the other issues.

Missing site props:   -- here, after enumeration,

**Comment by mkhorton** [comment]
Ok, I have a fix for 1. and a partial fix for 2., PR pending. Still no idea on the 16 vs 10.

**Comment by shyuep** [comment]
I already fixed 1?

**Comment by mkhorton** [comment]
Your fix stopped the crash, but didn't stop the underlying reason for why the list was becoming empty to start with.

**Comment by mkhorton** [comment]
1 is now fully fixed.

Regarding 2, the missing site properties issue is simply because any sites that go through enumblib lose their site properties in the round trip. There's no easy way to solve this, so I'm leaving it for now.

2 was only an issue because it was leading to a secondary bug where a Structure was initalized and the `len(species)` != `len(site_properties)` ... I lost the original bug so haven't been able to track down where this was happening exactly, I think somewhere in `get_primitive_structure()`. Will keep an eye on that one.

**Comment by mkhorton** [comment]
Closing, also noting in case others find this that the newer enumlib is much better and more stable, but should be compiled from source (the version on conda is out of date).
