### ISSUE TITLE
Qchem needs to be refactored.

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#1066]
pymatgen.io.qchem_io should be refactored to pymatgen.io.qchem to be consistent with all the other io packages.

I do not want to undertake this task because if I do it, it may break code on MP end of things. 

@mkhorton @montoyjh ? I know Xiaohui is the original author. I am not sure who took over his duties.

**Comment by mkhorton** [comment]
I don't use Qchem, but I'll ask the people that do. This shouldn't be a problem though.

**Comment by wood-b** [comment]
@shyuep we (myself, @samblau, @shyamd) can refactor the new qchem io to pymatgen.io.qchem. We didn't do that from the start because of the old qchem.py file (which we are still not ready to completely phase out).

**Comment by montoyjh** [comment]
@samblau and @wood-b have been working on this I believe.

**Comment by samblau** [comment]
FYI, just about to submit a pull request that includes the refactor. I'm ready to submit similar pull requests for Custodian and then Atomate as well.

**Comment by samblau** [comment]
This can now be closed
