### ISSUE TITLE
Neutron diffraction pattern calculator

### ISSUE THREAD

**Issue by resnant** [materialsproject/pymatgen#1070]
Hi, now I research magnetic materials using neutron beam.
I am writing a program to calculate the neutron diffraction pattern based on pymatgen.analysis.diffraction.xrd, for the case of nuclear scattering.
I will prepare the code according to the contribution guidelines, so please consider merge it.
Do you have an interest?

**Comment by shyuep** [comment]
Hi, yes we are very interested. Pls submit a pull request when you are ready, and thank you in advance for your contributions!

**Comment by mkhorton** [comment]
Hi @resnant, if it's helpful at all, note we have magnetic symmetry groups in pymatgen, available at pymatgen.symmetry.maggroups

**Comment by resnant** [comment]
Thank you @mkhorton, I'll check it.

**Comment by resnant** [comment]
Hi. The work was almost finished, and I'm preparing the unit test.
However, when I set a Debye-Waller B factor, I encountered intensity mismatch with other software and textbook. I'll recheck this.

By the way, should I fill the credit? (i.e., copyright, version, maintainer, etc.)

**Comment by shyuep** [comment]
Yes pls provide the credit information. If you have a publication you would like users to cite, pls provide it as well. We will make sure to acknowledge this contribution in the documentation as well

**Comment by resnant** [comment]
Ok, I will fill and update the credit.
Since my code to calculate neutron diffraction pattern is a slight modification of pymatgen.analysis.diffraction.xrd, may I fill the \_\_copyright__ as "Copyright 2018, The Materials Project"?
[https://github.com/resnant/pymatgen/blob/00ae1075000b7dc7bcf23b1791fa52403d96540d/pymatgen/analysis/diffraction/neutron.py](https://github.com/resnant/pymatgen/blob/00ae1075000b7dc7bcf23b1791fa52403d96540d/pymatgen/analysis/diffraction/neutron.py)

The publication is not published yet, I will contact you later.
