### ISSUE TITLE
LocalStructOrderParas ->  LocalStructOrderParams (with an 'm')

### ISSUE THREAD

**Issue by computron** [materialsproject/pymatgen#1081]
@nisse3000 to have better consistency in naming, ditch the "paras" and move to "params"

This refactor should be maybe 30 seconds of work with PyCharm, or even a simple find/replace across files

**Comment by nisse3000** [comment]
Addressed in PR #1083. Can be closed once the tests ran successfully.

**Comment by nisse3000** [comment]
@computron, can be closed.

**Comment by computron** [comment]
Thanks!
