### ISSUE TITLE
_get_image() in pymatgen.analysis.local_env doesn't give correct image

### ISSUE THREAD

**Issue by computron** [materialsproject/pymatgen#1103]
## System

* Pymatgen version:  master

## Summary

* pymatgen.analysis.local_env.NearNeighbors#_get_image doesn't give the correct image
* Looks like @mkhorton did an initial implementation and @nisse3000 made the most recent changes to it

## Example code

```python
    mpr = MPRester()
    s = mpr.get_structure_by_material_id("mp-685291")

    cnn = MinimumDistanceNN(tol=0.5)
    nn = cnn.get_nn_info(s, 71)
    for x in nn:
        if x["site"].specie.symbol == "Al":
            print(x["site"], s[71].distance(x["site"], x["image"]))  # gives the WRONG distance for Al - way too far!!
            print(x["site"], s[71].distance(x["site"], [0, 0, 0]))  # gives the CORRECT distance for Al - this is the right image!
```

## Error message

none

## Suggested solution (if any)

haven't looked at the code

## Files (if any)

none

**Comment by mkhorton** [comment]
There was some discussion on this on the PR Nils made for the most recent
change to get_image too. If you encounter further issues I’ll go back and
take another look.

**Comment by computron** [comment]
From what I can tell, the neighbors returned by VoronoiNN, MinimumDistanceNN, and perhaps all NN algorithms give back a Site objects that have the correct cartesian coordinates but the wrong image (e.g., fractional coordinates that don't correctly represent the image they are in). But, I don't have much time to debug. Just the code example above, here modified a bit to show the Cartesian distance at the end and how it is in agreement with a "hacked" image but not the reported image:

```python
from pymatgen import MPRester
from pymatgen.analysis.local_env import MinimumDistanceNN
import numpy as np

mpr = MPRester()
s = mpr.get_structure_by_material_id("mp-685291")

cnn = MinimumDistanceNN(tol=0.5)
nn = cnn.get_nn_info(s, 71)
for x in nn:
    if x["site"].specie.symbol == "Al":
        print(x["site"], s[71].distance(x["site"], x["image"]))  # gives 15.85  - WRONG!
        print(x["site"], s[71].distance(x["site"], [0, 0, 0]))  # gives 1.96 - RIGHT!
        print(x["site"], np.linalg.norm(x["site"].coords - s[71].coords)) # gives 1.96 - RIGHT!
```

As far as I can tell the root of the image problem is the fractional coords of the site

**Comment by mkhorton** [comment]
Yeah, it’s definitely further down the callstack. I’ll track it down when
I’m back in work next week — I think it’s either an issue with frac coords
on 0 or 1, or there’s a rounding of small numbers happening somewhere
that’s resulting in numbers being rounded the ‘wrong’ way. In any case,
there are alternative ways to get the image given that the Cartesian coords
are correct, so hopefully should be an easy fix. Thanks for the detailed
bug report.

**Comment by shyuep** [comment]
Seems like this issue has been defunct for many years. Closing.... Feel free to reopen if still valid.
