### ISSUE TITLE
return values for undefined numbers

### ISSUE THREAD

**Issue by computron** [materialsproject/pymatgen#1106]
## Summary

* pymatgen sometimes returns float("inf") if a value is not found - just search for float("inf") or look specifically at the code for electronegativity below

```
    @property
    def X(self):
        if "X" in self._data:
            return self._data["X"]
        else:
            warnings.warn("No electronegativity for %s. Setting to infinity. "
                          "This has no physical meaning, and is mainly done to "
                          "avoid errors caused by the code expecting a float."
                          % self.symbol)
            return float("inf")
```

* **I would suggest to return float("nan") instead**
* With float("inf") you can design functions and perform computations without knowing that you are doing anything wrong. e.g. a function like 1/electronegativity will return zero for unknown electronegativity, whereas it should really throw an error or return another invalid value like NaN. Otherwise, there is no way to really detect that 1/electronegativity did anything wrong - you get a perfectly ordinary float (zero) at the end.
* Note that my suggestion is in-line with what libraries like pandas does

**Comment by shyuep** [comment]
While I in principle do not have objections to this, NaN has other problems. For example, float("NaN") > 0 and float("NaN") < 0 both return False. If you do `sorted([float("NaN"), 0, 1, -1, 2])`, that effectively returns `[nan, -1, 0, 1, 2]`. That means that all elements with no electronegativity will effectively appear as though it is the most electropositive.

**Comment by computron** [comment]
I think NaN will just stay in the same place as it was initially in the list when sorted, so it wouldn't show up as either most or least electronegative unless it started in that list position

So elements with no electronegativity, when sorting, will just stay in the same place. But TBH I don't see that as a big issue. I'm more concerned with people designing mathematical functions that depend on electronegativity difference (or doing data mining with that) and the potential for infinity to be seen as a "computable" float.

As an example I am currently writing a NearNeighbor algorithm that might want to weight bonds with higher electronegativity difference more strongly - so something like a bond strength score that looks like (X1 - X2). However if I wasn't more careful in reading the docs or testing against ALL elements (like He, Ne, etc) then I could easily end up with pathological cases where the bond strength scores are infinity and I'm not sure why the NN algorithm is failing and perhaps just bonding everything to He / Ne / etc.

**Comment by shyuep** [comment]
I can see the issue with the inf. But I also see the problem with using NaN. For example, there is now completely no predictability in sorting formulas. I can easily get LiHeN as well as HeLiN and LiNHe. Granted the ones with no electronegativities tend not to be compound formers, but it is an issue. For instance, HArF exist. There are a few He compounds at low temperatures.

**Comment by computron** [comment]
Ah now I understand why you want to be able to sort electronegativities and also why you chose +inf

Ok up to you. I think the two solutions are to just leave as-is, or if people want an explicit sort order to NaN (as in pretty formula) to have more complex code that gives a custom sort key, e.g.

```
sorted(my_list, key=lambda x: x if not math.isnan(x) else float("inf"))
```

This is admittedly ugly but explicit that you are intentionally putting undefined electronegativities at the end.

Feel free to close ...

**Comment by shyuep** [comment]
Ok, I have a solution that addresses both problems. We cab use Nan, but we modify the Element '__lt__' method to treat NaN as effectively infinity in the sort order. Will this address your needs? If so, pls implement with tests.

**Comment by shyuep** [comment]
I implemented and fixed this. Just pull the latest changes.

**Comment by computron** [comment]
Great, thanks!
