### ISSUE TITLE
Alternate algo to reduce structure on the axb plane.

### ISSUE THREAD

**Issue by CifLord** [materialsproject/pymatgen#1118]
Part of the SlabGenerator class. We want to build a slab from the most reduced oriented unit cell as possible in order to reduce computational cost and maintain kpoint density of the ouc and slab. The current method of doing this (sift through all possible structures with the c direction constrained) using get_primitive_structure() works but because it iterates through a large number of possible reduced structures, it isn't fast enough. Since we only care about reducing the axb plane in our oriented unit cell, a simpler solution would be to just define the primitive basis vectors parallel to the hkl plane while maintaining the c vector and build a new oriented unit cell based on our new basis vectors.

Algo:
-Select a site as an origin.
-Find all equivalent sites to this site.
-Choose the two closest sites sitting on the same axb as our defined origin.
-The origin and the two sites define our a' and b' (making sure our a' and b' are not parallel of course).
-c'=c
-Build the new structure with the lattice defined by a', b', c' and the sites are inside a', b' and c'.

**Comment by shyuep** [comment]
Seems like this issue has been defunct for many years. Closing.... Feel free to reopen if still valid and someone wants to take it on.
