### ISSUE TITLE
Feature request: bond order of covalent bonds

### ISSUE THREAD

**Issue by liwt31** [materialsproject/pymatgen#1126]
Function `is_bonded` in `bonds.py` is able to find if 2 sites are bonded according to bond length data stored. It's great. I think it's natural to automatically judge the bond order between the 2 sites, and `is_bonded` can return an int bond order instead of a bool. Further, why not make `bond_order` a member variable of the `CovalentBond` class and set it when initializing a `CovalentBond` object?

I can submit a pull request if the community think the feature is reasonable.

**Comment by shyuep** [comment]
Yes, this feature would be great. Thank you in advance and please submit a pull request (with unittests) when you are ready.

**Comment by mkhorton** [comment]
Note that you can now also get bond orders from `pymatgen.analysis.local_env.OpenBabelNN` also where bond orders are returned as neighbor weights.
