### ISSUE TITLE
How to plot the bandstructure of the hybrid functional?

### ISSUE THREAD

**Issue by tiandijunhao** [materialsproject/pymatgen#1144]
I want to plot the band-structure of the HSE06,and the output file was calculated by vasp.

**Comment by shyuep** [comment]
Pls see matgenb.materialsvirtuallab.org for examples. Plotting hybrid and non-hybrid bandstructures is no different. Also, pls use the Google groups for questions. The Github Issues is meant for reporting bugs and feature requests. Thanks.
