### ISSUE TITLE
Any plan for Dash/Zeal documentation?

### ISSUE THREAD

**Issue by specter119** [materialsproject/pymatgen#1147]
I think pymatgen is big enough to have a documentation for [Dash](https://kapeli.com/dash)/[Zeal](https://zealdocs.org/). I tried [doc2dash](https://github.com/hynek/doc2dash) on pymatgen but it didn't work.

**Comment by dwinston** [comment]
The following worked for me:
```
conda create -n doc2dash_pmg python=3.6
conda activate doc2dash_pmg
# include optional dependencies to make those docs too
pip install "pymatgen[provenance]"
pip install doc2dash
pip install invoke
cd <local_git_checkout_of_pymatgen>
# make docs for a particular version of pymatgen
git checkout v2018.5.3
# Use tasks.py in the pymatgen repo for a custom Sphinx-doc-building procedure.
invoke make-doc
# "-af" adds the docset to your installed Dash and overwrites if already built
doc2dash docs -n "pymatgen 2018.5.3" -i docs/_images/pymatgen.png -u https://pymatgen.org/ -af
```
You can grab my Dash docset for pymatgen 2018.5.3 [here](https://www.dropbox.com/s/2ll18eyelmq4922/pymatgen%202018.5.3.docset.tar.gz?dl=0) (need to `tar zxf` it).

**Comment by shyuep** [comment]
I will add this to the invoke task and add a link to the docs for the always updated copy.

**Comment by specter119** [comment]
@dwinston Thanks! @shyuep I think it's better to push it to [Dash-User-Contributions](https://github.com/Kapeli/Dash-User-Contributions) as a native supported dash documentation at your convenience.

**Comment by shyuep** [comment]
I have put the docs on pymatgen.org. See new section on offline docs.

I am reluctant to do Dash-User-Contributions for now. The problem is that it is an extra step for me to submit there, and I do not really want to take the trouble to satisfy all the requirements.

**Comment by specter119** [comment]
@shyuep thanks! This will also be great help. What's more I have 2 more suggestions.
- the link of `.tar.gz` can't add as an feed of zeal, I'm wander if changing to `.tar` will help.
- the context column on left of page seems duplicate with the software, is there anyway, we can export the html without the context column?

**Comment by shyuep** [comment]
Just to add that I have already added this to the User Contributed Docsets. You can now directly install it in Dash. The context column is also fixed.

**Comment by specter119** [comment]
@shyuep Thanks in advance, I'm using it.
