### ISSUE TITLE
add a "weight" attribute to the KPoint class

### ISSUE THREAD

**Issue by computron** [materialsproject/pymatgen#1148]
When accessing the kpoints of a calculation, it's sometimes helpful to know the weights of each k-point. For example, we currently want the k-point weights in order to compute branch point energies.

Right now, we pull the band structure and regenerate the weights again using SpacegroupAnalyzer. But it would be better if the band structure had the kpoint weights embedded in it. This would be accomplished by:

- Adding a ``weight`` attribute to the ``KPoint`` class
- Parsing and including that weight when grabbing entries from Materials Project via MPRester

**Comment by shyuep** [comment]
Supported.
