### ISSUE TITLE
Cannot use pmg command in macOS

### ISSUE THREAD

**Issue by protik77** [materialsproject/pymatgen#1149]
## System

* Pymatgen version: 2018.5.3
* Python version: 2.7.10
* OS version: macOS 10.13.4 (17E202)

## Summary

Trying to setup POTCARs using `pmg`. The `pmg` command fails in general.

## Example code

```python
➜  pmg                           
/Users/protik/pmg/lib/python2.7/site-packages/pymatgen/__init__.py:87: UserWarning: 
Pymatgen will drop Py2k support from v2019.1.1. Pls consult the documentation
at https://www.pymatgen.org for more details.
  at https://www.pymatgen.org for more details.""")
Traceback (most recent call last):
  File "/Users/protik/pmg/bin/pmg", line 7, in <module>
    from pymatgen.cli.pmg import main
  File "/Users/protik/pmg/lib/python2.7/site-packages/pymatgen/cli/pmg.py", line 19, in <module>
    from pymatgen.cli.pmg_plot import plot
  File "/Users/protik/pmg/lib/python2.7/site-packages/pymatgen/cli/pmg_plot.py", line 13, in <module>
    from pymatgen.analysis.diffraction.xrd import XRDCalculator
  File "/Users/protik/pmg/lib/python2.7/site-packages/pymatgen/analysis/diffraction/xrd.py", line 15, in <module>
    from .core import DiffractionPattern, DiffractionPatternCalculator, \
  File "/Users/protik/pmg/lib/python2.7/site-packages/pymatgen/analysis/diffraction/core.py", line 50, in <module>
    class DiffractionPatternCalculator(abc.ABC):
AttributeError: 'module' object has no attribute 'ABC'
```

**Comment by dwinston** [comment]
The "quick fix" for you here is to use Python 3. This error was not caught earlier because tests are no longer being run for pymatgen using Python 2. @shyuep I'm not sure what is your preferred way to patch this for py2 compatibility in the meantime, so I'm just leaving this comment rather than submitting a PR to fix.

**Comment by shyuep** [comment]
Yes, it would be better to just move to python 3. In 2019, we are dropping Python 2 supprot for good in line with the other packages. An alternative is to roll back to earlier versions of pmg (v2017.*) that is compatible with Python 2.
