### ISSUE TITLE
some bugs found in electronic_structure.boltztrap

### ISSUE THREAD

**Issue by flower0226** [materialsproject/pymatgen#1156]
When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.

## System

* Pymatgen version: <2018.4.20>
* Python version: <3.5>
* OS version: <linux-x86_64> 
* Boltztrap version:<1.2.5>

## Summary

1. cannot correctly read the doping_levels in parse_outputtrans

2. electronic_structure.plotter.BoltztrapPlotter
    all the np.sort must be change into sorted

3. electronic_structure.plotter.BoltztrapPlotter.plot_carriers
   must be _carrier_conc rather than carrier_conc

## Suggested solution (if any)

1. i dont know how to solve it elegantly, the result from my outputtrans is like below
  =================== INPUT VARIABLES ======================
  4  Bandstyle: GENE
  5 Set fermi:   0
  6 Debug:  0
  7 FermiE:  0.4639. step size: 0.0005 Ecut: 0.4000. # val. e:   96.000
  8 Run type: CALC
  9 Fourier expansion factor:  5
 10 Calc type: BOLTZ
 11 Fermi level range: (Ry)  0.1500
 12 Max temperature: (K)  800.0 Temp step: (K) 50.0
 13 Range around Ef where bands are given individual output (Ry) -1.0000
 14 HISTO used for calculation of DOS
 15    10 doping levels will be used
 16  Doping levels to be output for, in carriers / cm^3:
 17  0.100E+18 0.100E+19 0.100E+20 0.100E+21 0.100E+22-0.100E+18
 18 -0.100E+19-0.100E+20-0.100E+21-0.100E+22
=========================================================
2. `2940         tlist = np.sort(cond['n'].keys())`
must to be changed into 
   `2940         tlist = sorted(cond['n'].keys())`

3. `3417         abs(self._bz.carrier_conc[temp] / (self._bz.vol * 1e-24)),`
must to be changed into 
   `3417         abs(self._bz._carrier_conc[temp] / (self._bz.vol * 1e-24)),`

**Comment by fraricci** [comment]
Thanks for reporting it, I will take care of that as soon as possible.

**Comment by flower0226** [comment]
thanks a lot!
and there is still one thing to fix
while using the electronic_structure.plotter.BoltztrapPlotter module
if anything about mu, like plot_seebeck_mu, plot_conductivity_mu
the mu_steps didnt minus the e-fermi
and it should be minus 
thanks a lot again!
