### ISSUE TITLE
support querying anonymous formula by string in addition to dict, e.g. "AB2C4"

### ISSUE THREAD

**Issue by rwoodsrobinson** [materialsproject/pymatgen#1167]
feature suggestion

**Comment by dwinston** [comment]
If you are referring to a Materials Project database field accessible via e.g. `MPRester.query`, this is available as [`formula_anonymous`](https://github.com/materialsproject/mapidoc/blob/3bea594cdfd0e8186cc535414fd1cbe13a86e4b3/materials/formula_anonymous/README.md). For example:

```python
from pymatgen import MPRester

mpr = MPRester()
mpr.query({"formula_anonymous": "AB2C4"}, ["material_id", "pretty_formula"])[:5]
```
Output:
> [{'material_id': 'mp-764906', 'pretty_formula': 'LiV2O4'},
 {'material_id': 'mp-675252', 'pretty_formula': 'Yb2MnS4'},
 {'material_id': 'mp-974038', 'pretty_formula': 'Ni2W4C'},
 {'material_id': 'mp-675143', 'pretty_formula': 'Eu(GdS2)2'},
 {'material_id': 'mp-7831', 'pretty_formula': 'MgIn2O4'}]
