### ISSUE TITLE
GLIBC error when import pymatgen

### ISSUE THREAD

**Issue by gVallverdu** [materialsproject/pymatgen#1172]
Hello

I have recently installed anaconda and pymatgen in our lab server and I got an error about GLIBC when I try to import pymatgen. It seems there is something wrong with gcc and cython. Do you know how can I fix this ?

## System

* Python version: Python 3.6.4 Anaconda
* Pymatgen version: 2018.6.11
* OS version: Scientific Linux release 6.9 (Carbon) x86_64

## Example code

```
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymatgen as mg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages/pymatgen/__init__.py", line 54, in <module>
    from pymatgen.core import *
  File "/opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages/pymatgen/core/__init__.py", line 9, in <module>
    from .structure import Structure, IStructure, Molecule, IMolecule
  File "/opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages/pymatgen/core/structure.py", line 30, in <module>
    from pymatgen.core.lattice import Lattice
  File "/opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages/pymatgen/core/lattice.py", line 16, in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
  File "/opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages/pymatgen/util/coord.py", line 11, in <module>
    from . import coord_cython as cuc
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages/pymatgen/util/coord_cython.cpython-36m-x86_64-linux-gnu.so)
>>> 
```

Looking at `/lib64/libc.so.6` it is a sym link to `libc-2.12.so`. Thus I guess the lib version is too old ?

**Comment by yw-fang** [comment]
Hi, Germain, I also encountered this import error of pymatgen-2018.6.27 that was installed by anaconda with python3 (same error with python2).
I solved this problem by using

> pip install --user pymatgen

If you still have the problem, you may consider to update your GLIBC (if you are the admin), or [weaken the version dependencies](http://www.lightofdawn.org/wiki/wiki.cgi/NewAppsOnOldGlibc) so that pymatgen can work with the old libc-2.12.so. 

I hope this may help you.

**Comment by gVallverdu** [comment]
Hi
I am not the admin. We installed anaconda in our local cluster and I got that erreur after installing pymatgen.
I tried to install pymatgen using pip but I got the same error with GLIBC.
How can I weaken the dependencies ?
Thanks

**Comment by yw-fang** [comment]
@gVallverdu 
Hi again,

Just a kind reminder: before executing pip install, did you use 'conda uninstall pymatgen‘? This is quite important. I found GLIBC error still exists if I don't use 'conda uninstall pymatgen'.

As for the  method of 'weaken the version dependencies', actually I have provided the link in last reply, please see http://www.lightofdawn.org/wiki/wiki.cgi/NewAppsOnOldGlibc

I know  one of my friends used the workaround described in the abovewebpage to remove the GLIBC error. However, I didn't try it by myself, hence I cannot provide you more information here.

Bests
Fang

**Comment by gVallverdu** [comment]
Hello
Yes, I did first remove pymatgen. But I wonder if the glibc error comes from pymatgen or its dependencies because pip installs only pymatgen (I guess the dependencies were installed with conda previously).

I will follow the trick of your link. Thanks

```
gvallver@pyrene <~>
--> conda uninstall pymatgen
Solving environment: failed

PackagesNotFoundError: The following packages are missing from the target environment:
  - pymatgen



gvallver@pyrene <~>
--> pip install pymatgen
Collecting pymatgen
Requirement already satisfied: numpy>=1.14.3 in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages (from pymatgen)
Requirement already satisfied: tabulate in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages/tabulate-0.8.2-py3.6.egg (from pymatgen)
Requirement already satisfied: scipy>=1.0.1 in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages (from pymatgen)
Requirement already satisfied: ruamel.yaml>=0.15.6 in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages (from pymatgen)
Requirement already satisfied: palettable>=2.1.1 in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages/palettable-3.1.0-py3.6.egg (from pymatgen)
Requirement already satisfied: pandas in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages (from pymatgen)
Requirement already satisfied: requests in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages (from pymatgen)
Requirement already satisfied: pydispatcher>=2.0.5 in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages/PyDispatcher-2.0.5-py3.6.egg (from pymatgen)
Requirement already satisfied: sympy in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages (from pymatgen)
Requirement already satisfied: six in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages (from pymatgen)
Requirement already satisfied: matplotlib>=1.5 in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages (from pymatgen)
Requirement already satisfied: spglib>=1.9.9.44 in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages (from pymatgen)
Requirement already satisfied: monty>=0.9.6 in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages (from pymatgen)
Requirement already satisfied: python-dateutil>=2 in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages (from pandas->pymatgen)
Requirement already satisfied: pytz>=2011k in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages (from pandas->pymatgen)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages (from requests->pymatgen)
Requirement already satisfied: idna<2.7,>=2.5 in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages (from requests->pymatgen)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages (from requests->pymatgen)
Requirement already satisfied: certifi>=2017.4.17 in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages (from requests->pymatgen)
Requirement already satisfied: cycler>=0.10 in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages (from matplotlib>=1.5->pymatgen)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages (from matplotlib>=1.5->pymatgen)
Installing collected packages: pymatgen
Successfully installed pymatgen-2018.6.27
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

gvallver@pyrene <~>
--> python
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pymatgen
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages/pymatgen/__init__.py", line 56, in <module>
    from .ext.matproj import MPRester
  File "/opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages/pymatgen/ext/matproj.py", line 27, in <module>
    from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
  File "/opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages/pymatgen/symmetry/analyzer.py", line 19, in <module>
    import spglib
  File "/opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages/spglib/__init__.py", line 35, in <module>
    from .spglib import (get_version,
  File "/opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages/spglib/spglib.py", line 35, in <module>
    from . import _spglib as spg
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages/spglib/_spglib.cpython-36m-x86_64-linux-gnu.so)
>>> 

```

**Comment by yw-fang** [comment]
Hi, Germain, could you try '**pip install --user pymatgen**' as mentioned in my first response? Adding '--user' is used for installing pymatgen  in the home directory without requiring any special privileges. 

In addition, you can use this command to find the information of dependency:

> readelf -s /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages/spglib/_spglib.cpython-36m-x86_64-linux-gnu.so|grep GLIBC_2.14

You will find some information like this:

88: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND memcpy@GLIBC_2.14 (4)
801: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND memcpy@@GLIBC_2.14

Furthermore, you can run the following command to print more information about the address of GLIBC_2.14:

> readelf -V /opt/cluster/contrib/apps/anaconda/3/lib/python3.6/site-packages/spglib/_spglib.cpython-36m-x86_64-linux-gnu.so

**Comment by weixie4** [comment]
Just compile glibc 2.14 yourself in your home directory and add the compiled lib to your LD_LIBRARY_PATH. See:
https://stackoverflow.com/questions/35616650/how-to-upgrade-glibc-from-version-2-12-to-2-14-on-centos

Pymatgen will then work with Python 3.x. 

Warning: I found that Anaconda's conda executable crashes with Segmentation Fault error this way. To circumvent it, just reset your LD_LIBRARY_PATH to use the system default Glibc.

**Comment by bencomer** [comment]
hey, I had this error on our cluster and solved it by installing an earlier version of `spglib`. The first way I found to fix it was to just use pip to install `pymatgen` then downgrade the version of `spglib`. Commands below:

`pip install pymatgen; pip install spglib==1.9.8`

**Comment by janosh** [comment]
Closing this as outdated.
