### ISSUE TITLE
Pymatgen produces structure with duplicated atoms from CIF file

### ISSUE THREAD

**Issue by hjjvandam** [materialsproject/pymatgen#1179]
## System

* Pymatgen version: 2018.6.11
* Python version: 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
* OS version: Red Hat Linux 2.6.32-220.el6.x86_64 

## Summary

* Reading a CIF file for In2Se3 from the ICSD produces a structure with 2 atoms in the same position.
* This problem arose after switching to Python 3.6.5 (with Python 2.7 I did not see this problem)
* The CIF-file, a small Python script demonstrating the problem, and the output I get are attached in
[pymatgen_in2se3_test.zip](https://github.com/materialsproject/pymatgen/files/2120649/pymatgen_in2se3_test.zip)

## Potential solution

I am perfectly happy if pymatgen detects and removes duplicated atoms before returning the structure to me.

**Comment by shyuep** [comment]
there is a method to remove duplicate atoms in Structure.

**Comment by mkhorton** [comment]
I'm not sure if it's related to your problem, but the crystal doesn't look quite right to me... the symmetry operations in the CIF file reads:

```
loop_
_symmetry_equiv_pos_site_id
_symmetry_equiv_pos_as_xyz
1 'x-y, x, z'
2 'y, -x+y, z'
3 '-x, -y, z+1/2'
4 '-x+y, -x, z+1/3'
5 '-y, x-y, z+2/3'
6 'x, y, z'
```

while I think it should read 

```
loop_
_symmetry_equiv_pos_site_id
_symmetry_equiv_pos_as_xyz
1 'x-y, x, z+5/6'
2 'y, -x+y, z+1/6'
3 '-x, -y, z+1/2'
4 '-x+y, -x, z+1/3'
5 '-y, x-y, z+2/3'
6 'x, y, z'
```

If you make this change, you no longer get duplicated atomic positions in the output.

**Comment by hjjvandam** [comment]
Thank you Matthew,

I will have a look at this. I did find it odd that there would be duplicate atoms if all I do is read the CIF file. However, if the CIF file incorrectly describes the symmetry equivalent positions then I suppose anything can happen.

Thank you very much,

     Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov
Brookhaven National Laboratory

**Comment by hjjvandam** [comment]
Matthew,

Thank you for looking into this. I have reported your findings to ICSD and they have confirmed that there is an error in their CIF:

You are right. That is an mistake in ICSD. Somehow the translational part for two symmetries is missing. The suggestions of your colleague is correct. We will have to check, where the translational part got lost and correct this. For your case you can just add the two translational parts (+1/6 and +5/6 in the cif file and it will work correctly).

I am sorry for the inconvenience.

Best regards,

Stephan Rühl

And as you can see they are looking to fix this problem (“your colleague” means you, as I did credit you by name for this discovery as I really didn’t do anything). I thought, you’d might like to know that your contribution is helping drive some changes.

Best wishes,

    Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov
Brookhaven National Laboratory

**Comment by mkhorton** [comment]
Happy to hear this got resolved :)

**Comment by kra268** [comment]
A slightly different issue led me to this page. Sometimes, CIF files will have duplicate atoms especially if you open it in VESTA and convert it to .vasp file or POSCAR file. This is likely due to VESTA reading the file in P1 symmetry always. If you want to remove these duplicate/overlapping atoms from the structure, here's the code: 
`from pymatgen.core.structure import Structure`
`structure = Structure.from_file(r'path/to/POSCAR')`
`structure = structure.merge_sites(mode='delete')`
`structure = structure.sort()`
`structure.to(filename='your_file_name', fmt='cif')`

Note, this is not the same as removing disorder. But it's a good place to start.
