### ISSUE TITLE
Transformations module issue

### ISSUE THREAD

**Issue by 91bsjun** [materialsproject/pymatgen#1189]
When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.

## System

* Pymatgen version: latest version
* Python version: 3.6
* OS version: CentOS

## Summary

* Attribute error in strandard_transformations

## Example code

```
enum = OrderDisorderedStructureTransformation(symmetrized_structures=True)
enumerated = enum.apply_transformation(prim_cell, 100)
```

## Error message

```
Traceback (most recent call last):
  File "enumerate_structure.py", line 53, in <module>
    enumerated = enum.apply_transformation(prim_cell, 100)
  File "/home/shared/anaconda3/envs/CCpy/lib/python3.6/site-packages/pymatgen/transformations/standard_transformations.py", line 488, in apply_transformation
    sym_equiv = structure.find_equivalent_sites(ex)
AttributeError: 'Structure' object has no attribute 'find_equivalent_sites'
```

## Suggested solution (if any)

* The error may comes from wrong path after you upgrade Structure modules

## Files (if any)

* If input files are needed to reproduce the error, please provide 
either links (e.g., Dropbox or GDrive) for large files or simply paste
the file below for small files.

```
<contents of file 1>
```

**Comment by shyuep** [comment]
I am not sure what you are supplying as prim cell. Please provide a more detailed example code. Basically I cannot reproduce the error, and there is an actual unittest which passes on that particular method.

**Comment by shyuep** [comment]
This should be correct. But the input structure, prim_cell, should be a SymmetrizedStructure. You can get that from the spacegroup analyzer code. E.g.,

analyzer.get_symmetrized_structure()

**Comment by shyuep** [comment]
Also, I should note that the OrderDisorder transformation by default already detects symmetry. The Symmetrized structure option should only be used if you already pre-determined the symmetry of the structure. In most instances, you should not use that.
