### ISSUE TITLE
CIF importing results in incorrect length assignment

### ISSUE THREAD

**Issue by tawe141** [materialsproject/pymatgen#1198]
https://github.com/numat/RASPA2/blob/master/structures/mofs/cif/MIL-47.cif

Importing the above MIL-47.cif results in lattice lengths different from what is listed in the cif file. Why is this? 

```
In [2]: mof = CifParser("MIL-47.cif")

In [3]: struct = mof.get_structures()[0]

In [4]: struct.lattice.a
Out[4]: 6.8179

In [5]: struct.lattice.b
Out[5]: 13.939

In [6]: struct.lattice.c
Out[6]: 16.143
```

CIF file: 

```
_cell_length_a    6.8179
_cell_length_b    16.143
_cell_length_c    13.939
```

I must be missing something obvious here. What is it?

**Comment by shyuep** [comment]
The default behavior is to reduce the cell to a primitive cell, which can result in swapping of crystal axes. To turn off this behavior, pls use `Structure.from_file("MIL-47.cif")` or set `primitive=False` in the `get_structures` method.
