### ISSUE TITLE
OUTCAR file fails to be loaded by the pymatgen.io.vasp.outputs.Outcar file due to electrostatic potential item in output

### ISSUE THREAD

**Issue by stevetorr** [materialsproject/pymatgen#1199]
This is my first time submitting an issue so I hope that what I've written below is the appropriate level of detail. Thanks for everything you guys do!

## System

* Pymatgen version:  "2018.5.14" (Slightly older version, but I checked the history of the file in question to see if this had been fixed and it didn't look like it)
* Python version: Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
* OS version: Linux (on NERSC)

## Summary

When I tried to parse an OUTCAR file, I got an error in parsing the electrostatic potential part of the output (which states the electrostatic potential at each ion in the system). The offending file is attached.

## Example code

```python
$python
>>>from pymatgen.io.vasp.outputs import Outcar
>>>a=Outcar("OUTCAR")
```

## Error message

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/homes/s/storrisi/.conda/envs/cms/lib/python3.6/site-packages/pymatgen/io/vasp/outputs.py", line 1622, in __init__
    self.read_electrostatic_potential()
  File "/global/homes/s/storrisi/.conda/envs/cms/lib/python3.6/site-packages/pymatgen/io/vasp/outputs.py", line 1749, in read_electrostatic_potential
    pots = self.read_table_pattern(header_pattern, table_pattern, footer_pattern)
  File "/global/homes/s/storrisi/.conda/envs/cms/lib/python3.6/site-packages/pymatgen/io/vasp/outputs.py", line 1726, in read_table_pattern
    retained_data = tables[-1]
IndexError: list index out of range
```

## Suggested solution (if any)
My regular expression expertise is weak so it's unclear...
## Files (if any)

* If input files are needed to reproduce the error, please provide 
either links (e.g., Dropbox or GDrive) for large files or simply paste
the file below for small files.

[OUTCAR.txt](https://github.com/materialsproject/pymatgen/files/2182082/OUTCAR.txt)

**Comment by stevetorr** [comment]
I think I figured out the bug; if the electrostatic potential at an ion is only of order 1 (e.g. -5 instead of -50) then there are going to be two spaces between the ion index and the value, i.e."1  -5" versus "1 -5". (It works fine if there are 0 spaces, too). Hence, there needs to be provision for one **or** two whitespaces in the regular expression parser.

**Comment by stevetorr** [comment]
Update: can be fixed by changing the regular expression for table_pattern in the below snippet:
'''
        header_pattern = r"\(the norm of the test charge is\s+[\.\-\d]+\)"
        table_pattern = r"((?:\s+\d+\s?[\.\-\d]+)+)"
        footer_pattern = r"\s+E-fermi :"

        pots = self.read_table_pattern(header_pattern, table_pattern, footer_pattern)
'''
From
'''
        table_pattern = r"((?:\s+\d+\s?[\.\-\d]+)+)"
'''
To
'''
        table_pattern = r"((?:\s+\d+\s*?[\.\-\d]+)+)"
'''
I'll make a pull request for this later.

**Comment by shyuep** [comment]
I just fixed it.

**Comment by shyuep** [comment]
See latest commit.

**Comment by stevetorr** [comment]
Thank you!
