### ISSUE TITLE
spacegroup error in rhombohedral lattice

### ISSUE THREAD

**Issue by resnant** [materialsproject/pymatgen#1203]
Hello,
I encountered spacegroup issue about rhombohedral lattice as follows.
I read the source code of `pymatgen.symmetry.groups` for a while, but I don't know about what should I do about this.
Do you have any good ideas?
## System

* Pymatgen version: 2018.6.27
* Python version: 3.6.2
* OS version: Ubuntu 16.04.4 LTS

## Summary
Since pymatgen assumes hexagonal lattice notation for rhombohedral lattice,
we can not input crystal structure with rhombohedral lattice notation.

If possible, I'd like to input rhombohedral lattice into pymatgen without lattice conversion to hexagonal.

## Example code

```python
import pymatgen as mg

# Ni3 S2 http://www.crystallography.net/cod/9007640.html?cif=9007640
lattice = mg.Lattice.rhombohedral(4.0718, 89.459)
species = [{'S': 1.0}, {'Ni': 1.0}]
coodinate = [(0.252100, 0.252100, 0.252100), (0.500000, 0.244900, -0.244900)]
structure = mg.Structure.from_spacegroup('R32', lattice, species, coodinate )
```

## Error message
pymatgen interprets space group R32 as R32H and returns value error.
```
ValueError: Supplied lattice with parameters ((4.0717999999999996, 4.0717999999999988, 4.0717999999999996), (89.459000000000017, 89.459000000000017, 89.459000000000017)) is incompatible with supplied spacegroup R32H!
```

**Comment by shyuep** [comment]
Sorry for the late reply. To force rhom setting, set your spacegroup to 'R32:R'. This will result in no errors and the right structure.

**Comment by resnant** [comment]
It works! Thank you.

**Comment by Guancred** [comment]
Hi, I also have the similar error when I constructed the structure based on the groupspace, 
![image](https://github.com/materialsproject/pymatgen/assets/91767936/551d8094-122b-4f49-9f3b-dc52994bdf96)
![image](https://github.com/materialsproject/pymatgen/assets/91767936/34ec1f38-6c2d-4457-be33-a2d322462287)
Could you give me some suggestions?

**Comment by shyuep** [comment]
Your supplied lattice is NOT a rhombohedral lattice. The angles are 90, 125, 90 - that is not rhombohedral. Please review your spacegroup symmetry and lattices and correct accordingly (wikipedia page on spacegroup).
