### ISSUE TITLE
Obtaining what materials-project ids are available

### ISSUE THREAD

**Issue by nilsjohanbjorck** [materialsproject/pymatgen#1211]
Are there any queries for obtaining what materials-project ids ("mp-1234" and so on) are available? I don't really understand the system by which they are assigned...

**Comment by shyuep** [comment]
The method you are looking for is `MPRester.get_materials_ids`. Mids is simply a running number based on time of calculation. There is no system of assignment.

In future, please post questions on the Google groups. Github Issues are meant for reporting issues/bugs/feature requests. Thanks.

**Comment by dwinston** [comment]
Questions regarding Materials Project data in particular should be directed to the [forum](https://discuss.materialsproject.org) linked to at the bottom of every materialsproject.org page. [Your question](https://discuss.materialsproject.org/t/what-is-resource-to-access-and-manage-a-list-of-materials/293) was asked and answere previously.
