### ISSUE TITLE
Band structure checks if HF in order to determine if self-consistent

### ISSUE THREAD

**Issue by ajjackson** [materialsproject/pymatgen#1214]
## System

* Pymatgen version: 2018.5.14
* Python version: 3.6.3
* OS version: Linux Mint 17.3

## Summary

* I am a developer of the `sumo` package which uses pymatgen's Vasp parsers for band stucture plotting
* When attempting to plot self-consistent band structures, the undesired k-points are included in the band structure data unless a hybrid XC functional was used.
* As a result, the band structure parsing in Pymatgen is currently not suitable for meta-GGA calculations:
  - meta-GGA band structures (e.g. SCAN, TB09) require the same workflow as hybrid band structures: a self-consistent calculation with weighted k-points for density convergence and unweighted k-points for the band paths
  - _pymatgen.io.vasp.outputs.Vasprun.get_band_structure_ determines whether a self-consistent band-structure calculation was performed by checking if `LHFCALC = True`.

## Suggested solution

* Instead of checking if a band-structure calculation included Hartree-Fock energy, check whether there is a mixture of weighted and zero-weighted k-points.

**Comment by mkhorton** [comment]
Thanks for the report @ajjackson !
