### ISSUE TITLE
Fail to import pymatgen after master branch install

### ISSUE THREAD

**Issue by skk74** [materialsproject/pymatgen#1223]
When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.

## System

* Pymatgen version: <master>
* Python version: <Only 2.7.* and 3.* supported.>
* OS version: <Ubuntu 16.04> 

## Summary

* 1-2 short bullet points stating the problem.
After running python setup.py install, I attempt to import pymatgen and it seems that pymatgen cannot import the coord_cython module. Is there a dependency that I am missing?

## Example code

```python
# Example code generating error
```

## Error message
----> 1 import pymatgen

/home/sanjeev/pymatgen/pymatgen/__init__.py in <module>()
     54 # Allows from pymatgen import <class> for quick usage.
     55 
---> 56 from pymatgen.core import *
     57 from .electronic_structure.core import Spin, Orbital
     58 from .ext.matproj import MPRester

/home/sanjeev/pymatgen/pymatgen/core/__init__.py in <module>()
      7 from .periodic_table import Element, Specie, DummySpecie
      8 from .composition import Composition
----> 9 from .structure import Structure, IStructure, Molecule, IMolecule
     10 from .lattice import Lattice
     11 from .sites import Site, PeriodicSite

/home/sanjeev/pymatgen/pymatgen/core/structure.py in <module>()
     28 
     29 from pymatgen.core.operations import SymmOp
---> 30 from pymatgen.core.lattice import Lattice
     31 from pymatgen.core.periodic_table import Element, Specie, get_el_sp, DummySpecie
     32 from monty.json import MSONable

/home/sanjeev/pymatgen/pymatgen/core/lattice.py in <module>()
     14 
     15 from monty.json import MSONable
---> 16 from pymatgen.util.coord import pbc_shortest_vectors
     17 from pymatgen.util.num import abs_cap
     18 

/home/sanjeev/pymatgen/pymatgen/util/coord.py in <module>()
      9 import numpy as np
     10 import math
---> 11 from . import coord_cython as cuc
     12 
     13 """

ImportError: cannot import name coord_cython
```
# Error message
```

## Suggested solution (if any)

* If you have a suggestion on how to solve the issue, you may write it
  here.

## Files (if any)

* If input files are needed to reproduce the error, please provide 
either links (e.g., Dropbox or GDrive) for large files or simply paste
the file below for small files.

```
<contents of file 1>
```

**Comment by shyuep** [comment]
Why not use pip install?

**Comment by skk74** [comment]
I would like to use the new part of analysis particularly local_env and it doesn't seem to be available on the pip install version.

**Comment by mkhorton** [comment]
local_env is available on the pip installed version, try `pip install pymatgen --upgrade` ? We recommend using Python 3+ also since Python 2.x support is being dropped, so check what version of pip you're using.

**Comment by xivh** [comment]
I got the same error and fixed it with CC=gcc python setup.py develop.

**Comment by shyuep** [comment]
@xivh I need a more detailed outline of the exact procedure that you did and error message for us to debug. This is an extremely old issue. We have not heard of anyone having this issue in the past four years.

**Comment by xivh** [comment]
I got the same import error as Sanjeev when installing from master and importing pymatgen.io.vasp.inputs from inside the pymatgen directory. Running `CC=gcc python setup.py develop` got rid of the error.

But, I just found out that everything works fine if I leave the directory before importing.
