### ISSUE TITLE
A small number of band structures have doubled k-point labels.

### ISSUE THREAD

**Issue by steicher** [materialsproject/pymatgen#1225]
Hi again Materials Project folks,

Not a major concern, but while we've been running through the electronic structures in the database, we've found that a small number of them have doubled labels for high-symmetry k-points. For example, the k-path will be \Gamma -> X -> X -> \Sigma instead of \Gamma -> X -> \Sigma. 

Structures that have this problem in both the band structure objects downloaded from the API and on the website band structure visualization include: mp-8601, mp-4100, mp-853153, and mp-765720. We are not using the entire group of electronic structure calculations, so there may be more similar band structure label errors.

Thanks!

**Comment by janosh** [comment]
Sorry for the extremely late reply. I can no longer reproduce this (even using the old `MPRester`). Either the issue was fixed in the meantime or I'm not looking in the right place.

```py
for mp_id in ("mp-8601", "mp-4100", "mp-853153", "mp-765720"):
    bandstructure = MPRester().get_bandstructure_by_material_id(mp_id)
    print(f"{bandstructure.branches=}")

>>> bandstructure.branches=[{'start_index': 0, 'end_index': 74, 'name': '\\Gamma-P'},
 {'start_index': 75, 'end_index': 78, 'name': 'P-Z'},
 {'start_index': 79, 'end_index': 164, 'name': 'Z-Q'},
 {'start_index': 165, 'end_index': 239, 'name': 'Q-\\Gamma'},
 {'start_index': 240, 'end_index': 301, 'name': '\\Gamma-F'},
 {'start_index': 302, 'end_index': 345, 'name': 'F-P_1'},
 {'start_index': 346, 'end_index': 349, 'name': 'P_1-Q_1'},
 {'start_index': 350, 'end_index': 409, 'name': 'Q_1-L'},
 {'start_index': 410, 'end_index': 471, 'name': 'L-Z'}]
...
```

Do you have a code snippet to reproduce this?
