### ISSUE TITLE
Unintuitive behavior when saving to .cif related to space groups

### ISSUE THREAD

**Issue by RoberTnf** [materialsproject/pymatgen#1230]
## Summary

* Space group information lost when saving to cif

## Example code
```
import pymatgen as mg
from pymatgen import Lattice, Structure, Molecule

# Set up a cubic structure and write to a CIF.
lattice = mg.Lattice.cubic(4.2)
s1 = mg.Structure(lattice, ["Cs", "Cl"],[[0, 0, 0], [0.5, 0.5, 0.5]])
s1.to(filename="s1.cif")
```

# In the cif file:
```
_symmetry_space_group_name_H-M   'P 1'
```
# It should be
```
_symmetry_space_group_name_H-M   Pm-3m
```
# This works as intended

```python
import pymatgen as mg
from pymatgen import Lattice, Structure, Molecule
from pymatgen.io.cif import CifWriter

# Set up a cubic structure and write to a CIF.
lattice = mg.Lattice.cubic(4.2)
s1 = mg.Structure(lattice, ["Cs", "Cl"],[[0, 0, 0], [0.5, 0.5, 0.5]])
writer = CifWriter(s1, symprec=0.01)
writer.write_file("s1.cif")
```

## Suggested solution 

Maybe `symprec` should be accessible when saving a structure using the method `to`? I'm submitting a PR for it.

**Comment by RoberTnf** [comment]
I see, makes sense. Then what's the purpose of `_symmetry_space_group_name_H-M` in this case? Wouldn't it be better to not write that line, to avoid people trusting it (like I was).

**Comment by mkhorton** [comment]
Yeah, I don't know the answer to that for sure. I can definitely see why this would be confusing; you're not the first person to flag this.

I would say that the purpose of these tags is to tell the software parsing the CIF file what symmetry operations it needs to apply to the list of atomic positions to construct the crystal. This is important to many tools, e.g. visualization tools, etc.

In this sense, supplying P1 is technically correct, it says: "we've supplied *all* the atomic positions, the only symmetry operation you need to apply is the identity." I'm not sure if this is strictly required by the standard or if P1 is assumed by default if symmetry information is not supplied, but in any case I'd expect many third-party tools that parse CIF to break if we didn't include this line.

Perhaps a remedy to this would be to add a human-readable comment to the file, explaining it's been outputted in a P1 setting but also providing the calculated symmetry within the given symmetry tolerance.

**Comment by RoberTnf** [comment]
I see. Maybe even just expanding the docstring, indicating that there are more advanced options would suffice. Now I realize it does says so in the online documentation, so I'm probably the one to blame here!

**Comment by mkhorton** [comment]
Yes, if you wanted to change it I would propose a change here:

https://github.com/materialsproject/pymatgen/blob/0c989cad54ca1ac729aeb173bcbfd35e2faab0cc/pymatgen/io/cif.py#L1309
