### ISSUE TITLE
Why the BandStructure and BandStructureSymmLine classes have different format of ["bands"] in as_dict()

### ISSUE THREAD

**Issue by zhaohuihai** [materialsproject/pymatgen#1242]
Hello, 
I have found the following difference handling the band structure data:

https://github.com/materialsproject/pymatgen/blob/2e03585538072b9e71adaaaa659029f4beaa0a68/pymatgen/electronic_structure/bandstructure.py#L855

https://github.com/materialsproject/pymatgen/blob/2e03585538072b9e71adaaaa659029f4beaa0a68/pymatgen/electronic_structure/bandstructure.py#L551

Could you please explain why they are converted to different format? Thanks.

**Comment by shyuep** [comment]
Seems like this issue has been defunct for many years. Closing.... Feel free to reopen if still valid.
