### ISSUE TITLE
Possible error in strain.Deformation.apply_to_structure

### ISSUE THREAD

**Issue by afonari** [materialsproject/pymatgen#1244]
Possibly related to this commit: https://github.com/materialsproject/pymatgen/commit/2c3a8dc72dddc72c72ed0dd0b417edc29a76a844

In the test_apply_to_structure unit test (https://github.com/materialsproject/pymatgen/blob/master/pymatgen/analysis/elasticity/tests/test_strain.py#L43) lattice is defined as:
```
lattice = Lattice([[3.8401979337, 0.00, 0.00],
                           [1.9200989668, 3.3257101909, 0.00],
                           [0.00, -2.2171384943, 3.1355090603]])
```

The deformation matrix is (from the deformation: self.norm_defo = Deformation.from_index_amount((0, 0), 0.02)):
```
[[ 1.02  0.    0.  ]
 [ 0.    1.    0.  ]
 [ 0.    0.    1.  ]]
```
I expect that only first row of the lattice is modified, however, the lattice in self.assertArrayAlmostEqual is:
```
[[3.9170018886, 0, 0],
[1.958500946136, 3.32571019, 0],
[0, -2.21713849, 3.13550906]]
```

The first element of the second row is modified too (1.9200989668 vs 1.958500946136) what is the reason for that?

**Comment by shyuep** [comment]
@montoyjh

**Comment by montoyjh** [comment]
The cited lattice isn't cubic, the second vector has a nonzero x-component, which is deformed the same way as the first vector.

**Comment by montoyjh** [comment]
Put differently, the deformation gradient is a vector mapping, it's applied to each of the three lattice vectors independently.

**Comment by afonari** [comment]
Sounds good, thanks for the explanation @montoyjh!
