### ISSUE TITLE
Description of method `is_valid` is wrong

### ISSUE THREAD

**Issue by bonfus** [materialsproject/pymatgen#1246]
Line 291 misleadingly states that the default value of tol is 0.01
https://github.com/materialsproject/pymatgen/blob/8cb71acda73b1544a08a087351edf30d68ed18da/pymatgen/core/structure.py#L283-L291

while it is actually defined as `DISTANCE_TOLERANCE=0.5` above.

**Comment by mkhorton** [comment]
Thanks for the report @bonfus! If you spot any other docstring errors you're also welcome to submit a fix directly (GItHub has an integrated text editor which makes this easy to do).
