### ISSUE TITLE
bug in electronic_structure/bandstructure.py

### ISSUE THREAD

**Issue by weixie4** [materialsproject/pymatgen#1258]
## System

* Pymatgen version: 2018.9.1
* Python version: 2.7.14 and 3.6.3
* OS version: CentOS 7.4.1708

## Summary

* On line 251, v is a Python list but called as a Numpy array

## Example code

```python
#!/usr/bin/env python
from pymatgen.io.vasp.outputs import Vasprun
from pymatgen.io.vasp.outputs import BSVasprun
from pymatgen.electronic_structure.plotter import BSDOSPlotter

dosv = Vasprun("dos/vasprun.xml")
dos = dosv.complete_dos

bsv = BSVasprun("bs/vasprun.xml", parse_projected_eigen=True,parse_potcar_file=True)
bs = bsv.get_band_structure(kpoints_filename="KPOINTS",
                            efermi=dos.get_cbm_vbm()[1],
                            line_mode=True)
bsdosp = BSDOSPlotter(bs_projection='elements', dos_projection='orbitals')
plt=bsdosp.get_plot(bs,dos)

```

## Error message

```
 File "/opt/intel/intelpython3/lib/python3.6/site-packages/pymatgen/electronic_structure/plotter.py", line 2177, in get_plot
    not bs.get_projection_on_elements()):
  File "/opt/intel/intelpython3/lib/python3.6/site-packages/pymatgen/electronic_structure/bandstructure.py", line 252, in get_projection_on_elements
    v[i, j, :, k])
TypeError: list indices must be integers or slices, not tuple

```

## Suggested solution (if any)
convert v to a numpy array before calling it. For example adding the following to line 245:
v=np.array(v)

Note this same bug exists not only in function get_projection_on_elements but also at least in function get_projections_on_elements_and_orbitals. Please convert v to a numpy array in all similar functions.

**Comment by shyuep** [comment]
@computron I think this is yours?

**Comment by computron** [comment]
No I think this was all written by Geoffroy, with the last update to that line from you according to "git blame". I really didn't have much to do with writing the band structure classes apart from writing the specific BSDosPlotter and maybe a bugfix here or there

**Comment by computron** [comment]
@weixie4 can you attach the relevant files (vasprun.xml, KPOINTS, POTCAR) so we can debug?

@shyuep I am pretty sure one would get the same error just by calling ``bs.get_projection_on_elements`` without invoking BSDosPlotter at all, but I would need the raw VASP files to confirm

**Comment by weixie4** [comment]
Sorry my Vasprun.xml file for band structure is huge (several GBs) and I confirm it’s not an error in BSDosPlotter function—see my suggested fix to module bandstructure.py

**Comment by shyuep** [comment]
I pushed a more permanent fix.

**Comment by weixie4** [comment]
Thanks @shyuep. I think this bug may be related to issue 1242 https://github.com/materialsproject/pymatgen/issues/1242 because tolist() is called in the end.
