### ISSUE TITLE
MPRester query for band_gap does not return full dict

### ISSUE THREAD

**Issue by rwoodsrobinson** [materialsproject/pymatgen#1261]
## System

* Pymatgen version: master
* Python version: 3

## Summary

* MPRester query output for 'band_gap' is not consistent with mapidoc
* expect a full dictionary of band gap information, but returns only a single band gap value (presumably from search_gap)

## Example code

```python
mpr.query({'material_id': 'mp-555599'}, ['band_gap'])

```

## Expected output

(note: code from mapidoc)

```
[{
    "optimize_structure_gap": {
        "band_gap": 0.013900000000000468, 
        "is_direct": true
    }, 
    "GGA_NSCF_gap": {
        "direct_gap": 0.0, 
        "transition": null, 
        "band_gap": 0.0, 
        "is_direct": false
    }, 
    "search_gap": {
        "direct_gap": 0.0, 
        "transition": null, 
        "band_gap": 0.0, 
        "is_direct": false
    }, 
    "static_gap": {
        "band_gap": 0.02880000000000038, 
        "is_direct": false
    }
}]
```

## Actual output

```
[{'band_gap': 0.0}]

```

**Comment by mkhorton** [comment]
This is an issue with the new builders on emmet, not directly an MPRester issue. Previously gaps from all tasks were included, now only the 'highest-ranked' gap is included:

https://github.com/materialsproject/emmet/blob/master/emmet/vasp/settings/materials_settings.json#L12

**Comment by mkhorton** [comment]
Will raise an issue on emmet to fix this.
