### ISSUE TITLE
missing pymatgen.io version 2018.9.1

### ISSUE THREAD

**Issue by danielsauceda** [materialsproject/pymatgen#1263]
## System

* Pymatgen version: 2018.9.1
* Python version: 3.5, 3.6
* OS version: ubuntu 14.04
* environment: using conda python
* installed via pip

## Summary
* Missing the **io** submodule, i.e pymatgen.io
* I want to interact with vasp. Therefore I must use `import pymatgen.io.vasp.inputs`
* navigating to the site-packages I can **clearly** see `~/anaconda3/envs/py36/lib/python3.6/site-packages/pymatgen/io/vasp/inputs.py` but is not view-able through python

## example code

`
python -c "import pymatgen;print(dir(pymatgen))"
`

### output

> ['ArrayWithUnit', 'Composition', 'DummySpecie', 'Element', 'FloatWithUnit', 'IMolecule', 'IStructure', 'Lattice', 'MPRester', 'MSONable', 'Molecule', 'MontyDecoder', 'MontyEncoder', 'Orbital', 'PeriodicSite', 'SETTINGS', 'SETTINGS_FILE', 'Site', 'Specie', 'Spin', 'Structure', 'SymmOp', 'Unit', '\__author__', '\__builtins__', '\__cached__', '\__doc__', '\__email__', '\__file__', '\__loader__', '\__maintainer__', '\__maintainer_email__', '\__name__', '\__package__', '\__path__', '\__spec__', '\__version__', '_load_pmg_settings', 'analysis', 'bonds', 'composition', 'core', 'electronic_structure', 'entries', 'ext', 'fnmatch', 'get_structure_from_mp', 'lattice', 'loadfn', 'operations', 'os', 'periodic_table', 'sites', 'structure', 'symmetry', 'sys', 'unicode_literals', 'units', 'util', 'warnings', 'yaml']

## any assistance would be greatly appreciated

**Comment by shyuep** [comment]
I don't think there is a bug. Try `python -c "import pymatgen.io.vasp;print(dir(pymatgen.io.vasp))"`

**Comment by shyuep** [comment]
It is probably because io conflicts with a built in python package.
