### ISSUE TITLE
Is there a way that I can get a band structure projected on atom?s

### ISSUE THREAD

**Issue by Shuyangzero** [materialsproject/pymatgen#1267]
I can only get projected on element or orbitals when plotting the band structure. How can I project on atoms ?

**Comment by shyuep** [comment]
@hautierg Can you answer pls.

**Comment by CMUShuyang** [comment]
any updates ?

**Comment by hautierg** [comment]
Viet Anh, could you answer this?

Thanks,

Geoffroy

On 20 Sep 2018, at 15:32, Shuyang Yang <notifications@github.com<mailto:notifications@github.com>> wrote:


any updates ?

**Comment by hautierg** [comment]
BTW, by “atom”, I guess you mean a site?

Geoffroy

On 20 Sep 2018, at 15:47, Geoffroy Hautier <geoffroy.hautier@uclouvain.be<mailto:geoffroy.hautier@uclouvain.be>> wrote:

Viet Anh, could you answer this?

Thanks,

Geoffroy

On 20 Sep 2018, at 15:32, Shuyang Yang <notifications@github.com<mailto:notifications@github.com>> wrote:


any updates ?

**Comment by CMUShuyang** [comment]
Yes,  I want to know how different layers of slab contribute to the band structure (which is local band structure in p4vasp) Thanks so much !

**Comment by anhhv** [comment]
@CMUShuyang In pymatgen/electronic_structure/plotter.py, we supported a method to plot projection for given atoms (as listed in POSCAR 1, 2, 3, or 1+2, 3+4, ...), given orbitals (s, p, d, f or px, py, pz, px+py, and so on) and given branches of the electronic band structure (e. g. \Gamma-X). It's named as "get_projected_plots_dots_patom_pmorb".

P/S: More details about this method are in its docstring. If you get any problem when using this, feel free to contact us.

**Comment by CMUShuyang** [comment]
Thanks so much ! I tried with this method, it can only plot a different band structure with just the selected site. Can I also plot graph like this in pymatgen ?
![picture1](https://user-images.githubusercontent.com/35701741/45903915-4b04b800-bdb9-11e8-8891-c2da50a70bfe.png)

Another question is , is there a same way to plot the partial dos for different site ? Thanks again !

**Comment by anhhv** [comment]
Hi,

I did not completely understand your first question? Do you want to play with color and plot projection of different atoms in one band structure? In plotter.py, there exists a method named "get_elt_projected_plots_color" allowing you to plot projections on maximum there types atoms but you cannot select specific atoms (the projection for each sort of atom is sum over all the same-type atoms).

For projected DOS on specific atoms, I haven't try with this. You can see "class BSDOSPlotter".
