### ISSUE TITLE
Is there a method to parse a formula containing "@" ?

### ISSUE THREAD

**Issue by tamuhey** [materialsproject/pymatgen#1268]
I am searching a parser of chemical formula that can handle [Metallofullerene](https://en.wikipedia.org/wiki/Metallofullerene), whose formula contains "@" symbol.

For example, I tried to handle it with `pymatgen.core.composition.Composition` class, like below
```python
Composition("Dy3N@C80")
```
but this causes an error:
```
CompositionError: @ is an invalid formula!
```

I know I can deal with it by dropping "@" symbol in the formula, but I want to know cool way.

**Comment by mkhorton** [comment]
Hi @tamuhey , this isn't supported right now but you'd be welcome to submit a pull request to add this feature.

You'd want to strip out any '@' symbols present in the formula here:
https://github.com/materialsproject/pymatgen/blob/master/pymatgen/core/composition.py#L468

And then it should work as expected.

**Comment by tamuhey** [comment]
pull request #1269

**Comment by mkhorton** [comment]
Thanks for this @tamuhey !
