### ISSUE TITLE
Make NearNeighbor an abstract base class

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/pymatgen#1273]
A colleague had issues when trying to use analysis.local_env.NearNeighbor directly, which is not possible. This should be an abstract base class.

NearNeighbor could probably also be restructured a little to be friendlier to molecules and disordered structures, and avoid repeating any expensive structure operations (e.g. to avoid the issue with VIRE #1169 where BVAnalyzer is re-run on the whole structure for every single site).

Assigning myself to this for now, but tagging @nisse3000 @espottesmith in case you have any ideas/inputs or want to implement.

**Comment by mkhorton** [comment]
Adding a small note here that MinimumDistanceNN will fail (empty list) if cutoff too small (e.g. very large cells, lots of vacuum), should increase cutoff dynamically; cutoff not relevant to algorithm output as long as it's large enough, it's just for optimization.

**Comment by mkhorton** [comment]
Also adding a note that JmolNN can be refactored to use CutoffDictNN.

**Comment by shyuep** [comment]
Is this done?

**Comment by mkhorton** [comment]
Kind of, the way I want to do this would break backwards compatibility, `NearNeighbour().get_nn_info(struct, n)` would become `NearNeighbour(structure).get_nn_info(n)`. I'm going to do this because I think it's worthwhile, but I want to give people who use it a heads up that this will break some code (I think in matminer in particular).

**Comment by shyuep** [comment]
Implement it with deprecation for old methods. I would also suggest that method naming be as short as possible. E.g., NN.get_nn_info is redundant. Just get_info would do since NN is implied by the fact it is part of the NN class.

**Comment by mkhorton** [comment]
Sure, fine with the rename. Difficult to implement with deprecation warnings without also including a lot of redundant code, but maybe I'll just do that for now.
