### ISSUE TITLE
Pourbaix tests are slow

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#1278]
When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.

## System

* Pymatgen version: "Master"

## Summary

* See output from nose-timer below.
```
[success] 68.23% pymatgen.analysis.tests.test_pourbaix_diagram.PourbaixDiagramTest.test_mpr_pipeline: 33.9371s
[success] 12.18% pymatgen.analysis.tests.test_pourbaix_diagram.PourbaixDiagramTest.test_multicomponent: 6.0564s
[success] 8.52% pymatgen.analysis.tests.test_pourbaix_diagram.PourbaixDiagramTest.test_solid_filter: 4.2371s
[success] 5.51% pymatgen.analysis.tests.test_pourbaix_diagram.PourbaixDiagramTest.test_multielement_parallel: 2.7406s
[success] 3.21% pymatgen.analysis.tests.test_pourbaix_diagram.PourbaixPlotterTest.test_plot_entry_stability: 1.5974s
```

I am not sure why the MPR pipeline test needs to be done by pymatgen. That is a MP thing, not a pymatgen thing. At the very least, it needs to be simplified and made much faster. Similarly for other tests.

**Comment by shyamd** [comment]
rofl @shyuep not following his own issue template :) 
@montoyjh

**Comment by shyuep** [comment]
Erm, I did....
