### ISSUE TITLE
Ferroelectric classes use np.matrix

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#1280]
## System

* Pymatgen version: Master

## Summary

* Currently the polarization module uses np.matrix, which will be deprecated from py3.8 due to the introduction of the matrix multiplication operator (@).
* This leads of excessive deprecation messages.

## Suggested solution (if any)

* Replace all np.matrix with np.array and use np.dot for not. @espottesmith

**Comment by mkhorton** [comment]
Tagging @blondegeek for this issue. This is news to me, but looks like numpy is deprecating np.matrix:

> It is no longer recommended to use this class, even for linear algebra. Instead use regular arrays. The class may be removed in the future.

**Comment by shyuep** [comment]
I really need this to be dealt with soon. The visual noise from this deprecated use of np.matrix is overwhelming. @blondegeek When can we expect a fix?

**Comment by mkhorton** [comment]
I took a quick look at fixing this, diff here:

https://github.com/materialsproject/pymatgen/compare/master...mkhorton:ferroelectric-deprecation-fix

All tests pass except for `test_get_polarization_change_norm()` with:

```
(shapes (3,), (1, 3) mismatch)
 x: array([-5.7944874e-03, -4.4122660e-03,  4.6288752e+01])
 y: array([[-5.7944874e-03, -4.4122660e-03,  4.6288752e+01]])
```

This seems like a trivial fix, but it's not immediately obvious to me where the extra dimension came from.

**Comment by blondegeek** [comment]
Sorry for the delayed reply. I agree with @mkhorton's changes. The difference in shapes is I believe due to the following difference between `np.matrix` and `np.array` during subtraction:

```
a = np.random.randn(1,5)
b = np.random.randn(1,5)
a_m = np.matrix(a)
b_m = np.matrix(b)
print('np.array:\t', (a[0]-b[0]).shape)
print('np.matrix:\t',(a_m[0] - b_m[0]).shape)
>> np.array:	 (5,)
>> np.matrix:	 (1, 5)
```

For backward compatibility with the ferroelectric workflow in atomate, I would recommend a reshape that adds the additional dimension along axis=0. Otherwise, I would change the test to drop the axis=0 dimension.

**Comment by shyuep** [comment]
Ok, can we fix and close this issue?
