### ISSUE TITLE
Longest running tests

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/pymatgen#1292]
[success] 20.10% pymatgen.io.qchem.tests.test_outputs.TestQCOutput.test_all: 153.4455s
[success] 6.81% test_gb.Test_GBGenerator.test_gb_from_parameters: 52.0188s
[success] 3.77% pymatgen.ext.tests.test_matproj.MPResterTest.test_get_pourbaix_entries: 28.8016s
[success] 2.90% test_elastic.DiffFitTest.test_fit: 22.1355s
[success] 2.81% pymatgen.analysis.tests.test_pourbaix_diagram.PourbaixDiagramTest.test_mpr_pipeline: 21.4254s
[success] 2.13% test_elastic.ElasticTensorExpansionTest.test_get_yield_stress: 16.2279s
[success] 2.01% pymatgen.core.tests.test_surface.MillerIndexFinderTests.test_generate_all_slabs: 15.3802s
[success] 2.00% pymatgen.analysis.tests.test_graphs.StructureGraphTest.test_extract_molecules: 15.3037s
[success] 2.00% pymatgen.core.tests.test_surface.SlabTest.test_symmetrization: 15.2751s
[success] 1.97% pymatgen.analysis.defects.tests.test_generators.InterstitialGeneratorTest.test_int_gen: 15.0360s
[success] 1.8

**Comment by shyuep** [comment]
I basically halved the time for tests by using multi-processing. Some of the io bound tests (e.g., getting data from MP / reading from files) are sped up enormously. But I sitll prefer to get total test time down below 10mins. Right now it is 20mins, down from 40mins.

**Comment by mkhorton** [comment]
This is great! I just re-ran nose-timer on my own machine, and found a few hot-spots to address next (including one of my own). Also in discussion with Joey about the Pourbaix tests.
