### ISSUE TITLE
pip version 2018.9.30 is broken

### ISSUE THREAD

**Issue by sandipde** [materialsproject/pymatgen#1296]
**Describe the bug**

upgrading pymatgen to latest version breaks the build. The previous version works okay.

system details: python3.6 with intel  

<ipython-input-2-ad23870f0a12> in <module>()
      1 import numpy as np
----> 2 from pymatgen import Structure

~/.local/lib/python3.6/site-packages/pymatgen/__init__.py in <module>()
     54 # Allows from pymatgen import <class> for quick usage.
     55 
---> 56 from pymatgen.core import *
     57 from .electronic_structure.core import Spin, Orbital
     58 from .ext.matproj import MPRester

~/.local/lib/python3.6/site-packages/pymatgen/core/__init__.py in <module>()
      7 from .periodic_table import Element, Specie, DummySpecie
      8 from .composition import Composition
----> 9 from .structure import Structure, IStructure, Molecule, IMolecule
     10 from .lattice import Lattice
     11 from .sites import Site, PeriodicSite

~/.local/lib/python3.6/site-packages/pymatgen/core/structure.py in <module>()
     28 
     29 from pymatgen.core.operations import SymmOp
---> 30 from pymatgen.core.lattice import Lattice
     31 from pymatgen.core.periodic_table import Element, Specie, get_el_sp, DummySpecie
     32 from monty.json import MSONable

~/.local/lib/python3.6/site-packages/pymatgen/core/lattice.py in <module>()
     14 
     15 from monty.json import MSONable
---> 16 from pymatgen.util.coord import pbc_shortest_vectors
     17 from pymatgen.util.num import abs_cap
     18 

~/.local/lib/python3.6/site-packages/pymatgen/util/coord.py in <module>()
      9 import numpy as np
     10 import math
---> 11 from . import coord_cython as cuc
     12 
     13 """

ImportError: /gpfs/backup/users/home/desa/.local/lib/python3.6/site-packages/pymatgen/util/coord_cython.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __intel_sse2_strchr

**Comment by mkhorton** [comment]
Interesting, thanks for the report. I tested the release and it installs fine on my machine, both with the macOS wheel and direct from source. There is no Linux wheel at present which means your computer has to compile the Cython coord utils itself, so this is likely a compiler issue on your own machine.

If you're using the Intel compilers, are you also using the Intel Python? e.g. see a similar issue here https://stackoverflow.com/questions/49524083/importing-any-module-in-cython-file-gives-undefined-symbol-error

We have recently changed the release process, so it is also possible 2018.9.30 is bad somehow, so I will investigate further to double-check.

**Comment by sandipde** [comment]
Thanks for your response. It might very well be it's something to do with
my system but in order to solve the problem, I carefully installed last few
releases one at a time and the lat at version only causes this issue. So I
think there must be something in the latest release that caused this. See
if you fix it someway, otherwise, I am sure building from source instead of
using pip would solve this problem for me. Just wanted to report as I saw
it was just released 3 days back.

**Comment by mkhorton** [comment]
I'm still not seeing the issue myself, but I'll leave this issue open for a while in case other people have the same problem so we can investigate further.

@shyuep issues with people installing from source and Cython/coord utils seem fairly common, e.g. also see: #1172 #1223 and [here](https://groups.google.com/forum/#!msg/pymatgen/KFS3oIFS-t0/20YCbhN0AwAJ), thoughts on having a pure Python fallback ?

In pymatgen.util.coord we could have something like:

```
try:
    from . import coord_cython as cuc
except ImportError:
    warnings.warn("pymatgen's optimized co-ordinate utils not installed correctly,"
                  "performance of certain operations will be slower than expected.")
    cuc = None
```

and then just update coord.py as appropriate ... it seems like only `coord_list_mapping_pbc` and `pbc_shortest_vectors` need the Cython utils anyway.

In long-term future, we may want to consider something like Cython's [pure Python mode](https://cython.readthedocs.io/en/latest/src/tutorial/pure.html) which would allow us to offer Cython-optimized and pure Python versions of the same functions.

**Comment by arosen93** [comment]
I just want to add that if anyone else comes upon this issue, using the Intel distribution of Python resolved it completely.

**Comment by Develpy** [comment]
Installing via pip is still leading to errors when I try to import the Lattice object from pymatgen.core. I am working on a cluster system.

Traceback (most recent call last):
  File "***/home/***/test/test_pymatgen.py", line 7, in <module>
    from pymatgen.core import Lattice
  File "/home/***/.local/lib/python3.9/site-packages/pymatgen/core/__init__.py", line 21, in <module>
    from .lattice import Lattice  # noqa
  File "/home/***/.local/lib/python3.9/site-packages/pymatgen/core/lattice.py", line 23, in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
  File "/home/***/.local/lib/python3.9/site-packages/pymatgen/util/coord.py", line 17, in <module>
    from . import coord_cython as cuc
ImportError: /home/***/.local/lib/python3.9/site-packages/pymatgen/util/coord_cython.cpython-39-x86_64-linux-gnu.so: undefined symbol: __intel_sse2_strlen

**Comment by shyuep** [comment]
Pls see previous comment. This sounds like there is a mismatch between your system's gcc version and that required by pymatgen. I would suggest you use a conda environment to do the installation first.
