### ISSUE TITLE
get_distance input (jimage) does not take tuple

### ISSUE THREAD

**Issue by hello-underworld** [materialsproject/pymatgen#1306]
In core.structure module, there is a get_distance feature that looks like

def get_distance(i, j, jimage)

to get the distance of site index i and j with lattice translation of jimage. However, when inputted a tuple (say, I do get_distance(0,0,(1,0,0)), it gives me an error that says

"can only concatenate tuple (not "list") to tuple"

I have to do 

jimage=np.array([1,0,0]) 

for this to work properly. Perhaps could consider make it take tuple or list inputs. Thanks.

**Comment by mkhorton** [comment]
Thanks @hello-underworld, this now has been fixed: https://github.com/materialsproject/pymatgen/commit/a1f48c89400405e22ca6fef2befbf8786f07368f

Please also feel welcome to submit a pull request if you encounter any further issues.
