### ISSUE TITLE
pymatgen.vis.structure_chemview bug

### ISSUE THREAD

**Issue by yjzhang97** [materialsproject/pymatgen#1310]
**Describe the bug**
When I run this code in the jupyter notebook, it has a mistake.The prompt message is **A Jupyter widget could not be displayed because the widget state could not be found. This could happen if the kernel storing the widget is no longer available, or if the widget state was not saved in the notebook. You may be able to create the widget by running the appropriate cells.**.What should i do. I think it is a bug because of the chemview .It is too old.
**code**
```
from pymatgen import Structure
import pymatgen.vis.structure_chemview as vis
struct = Structure.from_file("./POSCAR")
mv=vis.quick_view(structure=struct)
mv.ball_and_sticks()
mv
```
The OS is centos 6.My python version is 3.6,but the latest chemview  only support python3.5 .I think it is a reason.

**Comment by mkhorton** [comment]
>  I think it is a bug because of the chemview .It is too old.

I think you're right, we're actively exploring different visualization options for pymatgen, and currently have a new solution in development.

We've had problems getting chemview working in other contexts too, and chemview itself is now officially deprecated, so we should probably deprecate the chemview viewer in pymatgen also.
