### ISSUE TITLE
no "cut off" values in "def get_connections(self)"

### ISSUE THREAD

**Issue by SeoinBack** [materialsproject/pymatgen#1311]
**Describe the bug**

In "pymatgen/analysis/structure_analyzer.py", "get_connections" has no cutoff setup while "class VoronoiConnectivity" has.

    def get_connections(self):
        """
        Returns a list of site pairs that are Voronoi Neighbors, along
        with their real-space distances.
        """
        con = []
        maxconn = self.max_connectivity
        for ii in range(0, maxconn.shape[0]):
            for jj in range(0, maxconn.shape[1]):
                if maxconn[ii][jj] != 0:
                    dist = self.s.get_distance(ii, jj)
                    if dist <= cutoff:                                         ####### added this line  
                        con.append([ii, jj, dist])
        return con

**Comment by shyuep** [comment]
Seems like this issue has been defunct for many years. Closing.... Feel free to reopen if still valid.
