### ISSUE TITLE
Missing test data for EOS analysis

### ISSUE THREAD

**Issue by tlsong** [materialsproject/pymatgen#1314]
Maybe   eta = (volume / v0) ** (1. / 3.) should be change to eta = (v0 / volume) ** (1. / 3.)??
In the code below:
`class BirchMurnaghan(EOSBase):

    def _func(self, volume, params):
        """
        BirchMurnaghan equation from PRB 70, 224107
        """
        e0, b0, b1, v0 = tuple(params)
        eta = (volume / v0) ** (1. / 3.)
        return (e0 +
                9. * b0 * v0 / 16. * (eta ** 2 - 1)**2 *
                (6 + b1 * (eta ** 2 - 1.) - 4. * eta ** 2))`

see 
https://en.wikipedia.org/wiki/Birch%E2%80%93Murnaghan_equation_of_state
and
https://gitlab.com/ase/ase/commit/4a24ac48b76a1abe1575871927ee07790abcddc4
in the 68-70lines

**Comment by mkhorton** [comment]
Thanks @tlsong 

@katherinelatimer2013 is this correct?

**Comment by katherinelatimer2013** [comment]
Yes, I used eta = (v0 / volume) ** (1. / 3.) (the same as what @tlsong has suggested) in the EOS analysis. Not sure at what point this bug arose but it should be changed. Thanks for pointing it out!

**Comment by mkhorton** [comment]
Ok, that's good to know, thank you! I can see there's data in the tests, but it looks like a few test lines are commented out, and as far as I can see there are also no reference outputs for the various EOS equations? In other words, I can fix this bug, but the test output is the same, which seems like an issue.

Do you have some known-good reference EOS values to hand for the "# Si data from Cormac" data that we can add to the tests?

**Comment by mkhorton** [comment]
Also tagging @shyamd here, since I know you were involved with the EOS analysis too

**Comment by katherinelatimer2013** [comment]
My end of the project didn't really involve much code development, so I wasn't too worried about tests at the time. I could dig up some EV curves but don't have Cormac's data.

**Comment by mkhorton** [comment]
Yeah, sorry I just checked the git history -- looks like this is actually mostly Kiran's code. Will merge the fix for now anyway and create an issue for additional test data.

**Comment by shyamd** [comment]
The EOS module was coded up @matk86 copying code from cormac.
@katherinelatimer2013  Can you dig up one of your curves that you computed EOS the params yourself for? I'd give that the highest likelihood of being correct.

**Comment by shyuep** [comment]
Note that I am this close to junking this code. We really shouldn't be allowing substandard code with no tests into pymatgen.

**Comment by mkhorton** [comment]
Started a fix for this https://github.com/materialsproject/pymatgen/commit/6a696ef6f01928a7fbbfdadca594e316992cfcb9 ... will be adding additional Vinet data courtesy of @katherinelatimer2013 also
