### ISSUE TITLE
Error when downloading the data from Material project

### ISSUE THREAD

**Issue by AustinApple** [materialsproject/pymatgen#1325]
**Describe the bug**
I try to access the unit_cell_formula from Material project. In the beginning, it performance normally. However, sometimes, the error pops out
"('REST query returned with error status code 500. Content: b\'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\\n<html><head>\\n<title>500 Internal Server Error</title>\\n</head><body>\\n<h1>Internal Server Error</h1>\\n<p>The server encountered an internal error or\\nmisconfiguration and was unable to complete\\nyour request.</p>\\n<p>Please contact the server administrator,\\n root@localhost and inform them of the time the error occurred,\\nand anything you might have done that may have\\ncaused the error.</p>\\n<p>More information about this error may be available\\nin the server error log.</p>\\n<hr>\\n<address>Apache/2.2.15 (CentOS) Server at www.materialsproject.org Port 443</address>\\n</body></html>\\n\'', 'occurred at index 2512')"

**To Reproduce**
This is my code:
import pandas 
from pymatgen.ext.matproj import MPRester
from pymatgen.core import periodic_table
import numpy as np
import pymatgen as mg
import csv
data = pandas.read_csv("MP_data",index_col=0)[["material_id","point_group"]]

def find_composition(row):
    API_Key='DBNZz5Ltv8q92OPC'
    mp = MPRester(API_Key)
    print(row["material_id"])
    catch_data = mp.query({"material_id":row["material_id"]},["unit_cell_formula"])
    for data in catch_data:
        for element in data["unit_cell_formula"].keys():
            row[element] = data["unit_cell_formula"][element]
    return row

data = data.apply(find_composition, axis=1)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Platform  jupyter notebook
 - pymatgen Version  2018.9.12

**Comment by shyamd** [comment]
Please do not post your API key in public space.

This is not a pymatgen issue. Occasionally the MP website has too many users for our current web servers and this causes this error.
