### ISSUE TITLE
Is there a Enum of materials properties of MP database?

### ISSUE THREAD

**Issue by tamuhey** [materialsproject/pymatgen#1326]
Hi,

I want a python Enum of  materials properties of MP database, like below

```python
class MaterialProperties(Enum):
    anonymous_formula               = "anonymous_formula"
    band_gap                        = "band_gap"
    ...
```

I tried to write a script ([gist](https://gist.github.com/tamuhey/c3c655ce75d979ae144f1aed881c3f6a)).
If you think it useful, please include it to pymatgen package.

**Comment by mkhorton** [comment]
I think the closest to what you're looking for is `MPRester.supported_properties` in `pymatgen.ext.matproj`. You can also check out the [mapidoc](https://github.com/materialsproject/mapidoc) and other Materials Project API documentation.

Please not the Issues page is intended specifically to report bugs, we also have a [Google Group](https://groups.google.com/d/forum/pymatgen) for general questions about pymatgen, or a [community forum](https://discuss.materialsproject.org) for general Materials Project enquiries :)

**Comment by mkhorton** [comment]
Hi @tamuhey, I think I misread your comment initially. We already have something similar to this Enum in  `MPRester.supported_properties` in `pymatgen.ext.matproj`. In general, the list of properties available on Materials Project does change, so I'm not sure that an Enum like this would be useful for us, but thank you for the suggestion. We do maintain the [mapidoc](https://www.github.com/materialsproject/mapidoc) as a list of the currently supported properties in Materials Project.
