### ISSUE TITLE
More transparency with elemental reference energies

### ISSUE THREAD

**Issue by CJBartel** [materialsproject/pymatgen#1339]
I've sometimes found it difficult to figure out what elemental reference energies are used to map total energy to formation energy. This seems like a relatively straightforward feature to add - e.g., when querying the database allow a user to download a dictionary {el1 : mu_el1, el2 : mu_el2} for each chemical formula that is produced in the query. This information could also be put on the page for each entry in the database (mu_el1 = ..., etc.).

This would be of significant utility for users that are interested in calculating their own structures and checking for stability against Materials Project entries. 

It's clear from the Calculations Guide (https://materialsproject.org/docs/calculations) that gases are adjusted, although the values are not so trivial to find. Why not provide these adjusted elemental reference energies right on this page? I eventually found these adjusted energies here - https://github.com/materialsproject/pymatgen/blob/master/pymatgen/entries/MPCompatibility.yaml.

This .yaml suggests that transition metals are also adjusted to account for +U effects, apparently only when in combination with oxygen or fluorine. This is not clear from the documentation and again emphasizes the point that these reference energies should be provided or queryable on a material-specific basis if possible. My interpretation of the documentation is that one could use a dictionary of {element : reference_energy} for obtaining formation energies from total energies but this is not the case as e.g., Co has a different chemical potential in an oxide vs. nitride.

**Comment by shyuep** [comment]
Seems like this issue has been defunct for many years. Closing.... Feel free to reopen if still valid.
