### ISSUE TITLE
Reorganization of SlabGenerator (or make a subclass of SlabTransformations for terminations)

### ISSUE THREAD

**Issue by CifLord** [materialsproject/pymatgen#1340]
There are several methods of generating specific termination in surface.py:

- Simple cleavage: The original algorithm whereby we simply insert a vacuum at a termination to create a slab. This preserves the stoichiometry relative to bulk.

- get_tasker2_slabs(): This is a method built into the Slab object. It enumerates through rearrangements of ions at the surface to obtain non-polar terminations.

- nonstoichiometric_symmetrized_slab(): This is a method built into the SlabGenerator object. After performing simple cleavage, this method will remove atoms at the surface to generate a symmetric slab.

- repair: This is a parameter in get_slabs() (a method of SlabGenerator). It takes a slab created via simple cleavage. Looks for user given bonds (e.g. PO4, PS4) that have been broken nad moves the atom along with the remaining bonds its attached to to the other surface. Useful for for determining terminations of systems that contain such structures. 

As we come up with more ways to generate terminations (or find them in the literature), we may want to better organize these methods. The simple cleavage algorithm which is require to generate a slab in the first place will remain part of the get_slab() method in SlabGenerator. For the other methods, I suggest organizing them as post simple cleavage methods built into SlabGenerator, or perhaps each one can be a subclass of SlabTransformations. The latter will be useful for identifying what kind of termination has been done to the slab, e.g. reconstruction, Tasker 2, non-stoichiometric terminations? Making them into SlabTransformations will also allow ease of combining different termination techniques to generate more terminations. This is important for more complicated systems with more than one element as simple cleavage is not enough to account for all the possible terminations in those systems let alone the most stable.

**Comment by shyamd** [comment]
I agree @richardtran415 .

I think Slab should be part of the core and the methods of generating slabs should be in analysis. SlabGenerator should be a module with one generator for each type of method.

**Comment by shyamd** [comment]
Should note this other set of algorithms for slab generation from Hinuma: https://arxiv.org/pdf/1508.07194.pdf

**Comment by shyuep** [comment]
Seems like this issue has been defunct for many years. Closing.... Feel free to reopen if still valid.

**Comment by DanielYang59** [comment]
Hi @CifLord thanks a lot for the wonderful work on `surface`.

I'm interested in getting my hands on this (maybe in #3691 but perhaps in a separate PR if too much reorganization is expected), and would you have time for some quick comment? That would be deeply appreciated!
