### ISSUE TITLE
Clean up of warnings in test outputs

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/pymatgen#1348]
Need to clean up warnings in test outputs to make test results easier to read.

Three main culprits: CrystalNN ("locate an appropriate radius", "distance cutoffs"), site merging in grain boundary (due to warning in Structure, "Sites with different site property grain_label are merged.so property is set to none"), and also CIF parsing warnings ("Issues encountered while parsing CIF").

**Comment by mkhorton** [comment]
I should note I'm responsible for the CIF warnings -- I wanted to be clear if we were making changes to the CIF file during parsing to fix errors, will have a think about what best to do to suppress these however since we use a lot of CIF files in the tests.

**Comment by shyuep** [comment]
Generally, people should not be using CIF files to do tests. If there are useful structures that are repeatedly being used for testing purposes, it should be hard-coded or dump into a JSON for faster loading. CIF files need to be tested only in the CIF parsing classes.
