### ISSUE TITLE
How do I customize my INCAR ?

### ISSUE THREAD

**Issue by CMUShuyang** [materialsproject/pymatgen#1354]
Hi,

I am wondering if I can customize my INCAR by pymatgen ? For instance, is there a way to automatically write GGA+U 's parameters U and J in INCAR by the elements' order in POSCAR ?  Other tags like MAGMOM and  different values for EDIFF ?  Thanks !

**Comment by shyuep** [comment]
See http://matgenb.materialsvirtuallab.org/2017/04/14/Inputs-and-Analysis-of-VASP-runs.html
