### ISSUE TITLE
A Bug in MPSOCSet with DFT+U

### ISSUE THREAD

**Issue by Shuyangzero** [materialsproject/pymatgen#1356]
Hi,

The MpSOCSet doesn't have the correct format for LDAUU, LDAUJ, LDAUL. 

I specify 'LDAUJ':{'Eu':1}, 'LDAUU':{'Eu':8},'LDAUL':{'Eu':3} in my user_setting for MPSOCSet

But in INCAR, it displays as 
LDAUJ = {'Eu': 1}
LDAUL = {'Eu': 3}
LDAUPRINT = 1
LDAUTYPE = 2
LDAUU = {'Eu': 8}

which doesn't extract the information out of the dictionary.

**Comment by shyamd** [comment]
Please provide some test code that shows this behavior.
