### ISSUE TITLE
Suppression of warnings in CrystalNN

### ISSUE THREAD

**Issue by arosen93** [materialsproject/pymatgen#1361]
**Is your feature request related to a problem? Please describe.**
The warnings are a bit overkill with `CrystalNN` when there are no oxidation states added for the structure. Oxidation states are often not feasible to add for complex materials, but `CrystalNN` is still one of the best NN algorithms implemented in Pymatgen and is useful without ionic radiil. Multiple warning messages for each call to `CrystalNN` in such cases is a bit of a nuisance. Obviously this is a personal opinion, so feel free to close this if you disagree. An example is shown below:

```
...\pymatgen\analysis\local_env.py:3425: UserWarning: CrystalNN: distance cutoffs set but no oxidation states specified on sites! For better results, set the site oxidation states in the structure.
  warnings.warn("CrystalNN: distance cutoffs set but no oxidation "
...\pymatgen\analysis\local_env.py:3238: UserWarning: CrystalNN: cannot locate an appropriate radius, covalent or atomic radii will be used, this can lead to non-optimal results.
  "CrystalNN: cannot locate an appropriate radius, "
```

**Describe the solution you'd like**
An optional input argument to `CrystalNN` of the type `warnings=True`, which can be set to `False` if desired by the user.

**Describe alternatives you've considered**
Of course, the change is minor and I can implement it locally, but it'd be better if it were in the base package.

**Comment by mkhorton** [comment]
Agreed these should be reduced (this is also mentioned in #1348, since the warnings are crowding the test logs)

**Comment by arosen93** [comment]
Ah, I didn't catch the recent issue you opened. Well, glad we're on the same page! For context, I brought this up because I have a few codes I plan to release that use Pymatgen's `CrystalNN`, and having the end-user experience countless warnings because I am purposefully neglecting oxidation states is not the most desirable scenario.

**Comment by mkhorton** [comment]
It’s not ideal, but for your own code you can also do the following:

```
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    CrystalNN()
```

Also I’m sure you’re already aware, but pymatgen does have methods to guess oxidation states, which might also be helpful.

**Comment by arosen93** [comment]
Thanks for the advice! I didn't know you could selectively suppress warnings like that. Very good to know.

With regards to guessing oxidation states, I have never had much success with the automated algorithms currently built into Pymatgen. I study MOFs, so I'm not sure it's the large unit cell, the often complicated electronic structure of the materials, or if the algorithms are mostly meant for nonporous (bulk) materials, but I rarely (if ever) succeed in getting charges assigned to the structures.

**Comment by mkhorton** [comment]
That’s fair, BVAnalyzer doesn’t scale very well to large structures. It’s bond valence parameters are due for an update though, so it could work better in future.

Note that Composition does now also have oxi_state_guesses which literally just tries to find the most probable combination of oxidation states. It’s pretty fast and works fine for larger structures, though I couldn’t say for MOFs. In any case, it’s only a heuristic so may not be appropriate for your application.

**Comment by shyuep** [comment]
@computron I think you need to handle this. See https://circleci.com/gh/materialsproject/pymatgen/8237?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification for an example of the trigger happy nature of CrystalNN warnings. It is rather excessive and basically obscures more important messages. One warning per structure is quite enough....

**Comment by computron** [comment]
wow that is crazy, reminds me of "hit a member found in another star" in VASP

First, I fully agree that what's reported is completely overkill - no warnings at all is better than that craziness. 

I am just confused because I thought the warnings package only warns once and then stops. For example, if I run the following code:

```
from pymatgen import MPRester
from pymatgen.analysis.local_env import CrystalNN

mpr = MPRester()

s1 = mpr.get_structure_by_material_id("mp-149")
s2 = mpr.get_structure_by_material_id("mp-19017")

cnn = CrystalNN()
cnn.get_cn(s1, 0)
cnn.get_cn(s1, 1)

cnn2 = CrystalNN()
cnn2.get_cn(s2, 0)
cnn2.get_cn(s2, 1)
```

which calls CrystalNN 4 times, I only get a single pair of warnings, the same as if I ran only one call on one structure.

Anyone know how why "warnings" is filtering things for that code but not in the unit tests or other code?

**Comment by shyuep** [comment]
I have no idea. Does CrystalNN attempt to run the code with the same structure with different parameters? 

In any case, warnings in regular usage is fine. But if they are not meant to cause test failures, I suggest you wrap them in the warnings.filter approach to suppress them in the test classes. That way we don't get an overwhelming amount of output.

**Comment by computron** [comment]
Even the tests, I only get a single warning (pair) across all CrystalNN tests:

```
Testing started at 2:05 PM ...
/Users/ajain/miniconda3/envs/py3/bin/python "/Applications/PyCharm CE.app/Contents/helpers/pycharm/_jb_unittest_runner.py" --target test_local_env.CrystalNNTest
Launching unittests with arguments python -m unittest test_local_env.CrystalNNTest in /Users/ajain/Documents/code_matgen/pymatgen_repo/pymatgen/analysis/tests
/Users/ajain/Documents/code_matgen/pymatgen_repo/pymatgen/core/periodic_table.py:429: UserWarning: No electronegativity for He. Setting to NaN. This has no physical meaning, and is mainly done to avoid errors caused by the code expecting a float.
  % self.symbol)
/Users/ajain/Documents/code_matgen/pymatgen_repo/pymatgen/analysis/local_env.py:3423: UserWarning: CrystalNN: distance cutoffs set but no oxidation states specified on sites! For better results, set the site oxidation states in the structure.
  warnings.warn("CrystalNN: distance cutoffs set but no oxidation "
/Users/ajain/Documents/code_matgen/pymatgen_repo/pymatgen/analysis/local_env.py:3236: UserWarning: CrystalNN: cannot locate an appropriate radius, covalent or atomic radii will be used, this can lead to non-optimal results.
  "CrystalNN: cannot locate an appropriate radius, "


Ran 8 tests in 4.396s

OK

Process finished with exit code 0
```

So it's easy for me to wrap the tests in warnings.filter(), etc. but I still don't know why CircleCI tests or @arosen93 's code is giving so many warnings - so perhaps this would fix the CircleCI tests, but not @arosen93 's underlying problem.

I would imagine multiprocessing might give a warning per process, but don't know other than that?

**Comment by shyuep** [comment]
For now, just suppress the test warnings. I do think the warnings are useful for general usage. It is just not useful for unittests.

**Comment by arosen93** [comment]
@computron I've rerun my code now, and I only seem to be getting one pair of messages regardless of how many times `CrystalNN` is called. Apologies for the mistake there -- perhaps I forgot to clear old warnings in the log file or something similar. Just wanted to clarify.

**Comment by computron** [comment]
@shyuep Btw it's possible that the following unit test causes problems:

pymatgen.analysis.magnetism.tests.test_analyzer.CollinearMagneticStructureAnalyzerTest

That test calls ``warnings.resetwarnings()`` which will reset all the warning filters. Any test or code run after that might see lots of warnings that is not the default behavior.

In cc9f58332804a487c59e47d74bd04072a3d0e79b I store the previous warnings filters, ignore warnigns, and then in tearing down restore whatever warning filters were there before. I would suggest this for CollinearMagneticStructureAnalyzerTest as well provided that this works

**Comment by mkhorton** [comment]
Hmm, that's my module but I didn't add that line. Maybe it was being too verbose, I'll take a look at it.

**Comment by computron** [comment]
The "git blame" says Hulk ... lol. Note that I'm not 100% sure it's the
culprit, but it might make sense.

**Comment by shyuep** [comment]
It is actually me. Generally, wanrings.restwarnings switch back to default behavior. The idea is that for each test, you want to make no changes to the global system. There are some unittests which actually rely on catching warnings to check correct behavior. So resetwarnings is always in the tearDown stage.

The CrystalNN tests should not rely on the fact that the warnings filter is on some non-default behavior because of a test running somewhere else.

**Comment by computron** [comment]
>> Generally, wanrings.restwarnings switch back to default behavior.

It doesn't though. warnings.simplefilter("default") does that. warnings.resetwarnings removes all filters, which is NOT the default setting

**Comment by shyuep** [comment]
Ok, then. I just pushed a commit to try to fix this. Let's see if it solves the problems.

**Comment by computron** [comment]
(Ok - my commit cc9f583 referenced earlier also has a solution, I think)
