### ISSUE TITLE
`AdsorbateSiteFinder.find_adsorption_sites()` assumes `mvec` is array

### ISSUE THREAD

**Issue by fallleave001** [materialsproject/pymatgen#1368]
in adsorption.py module, the function find_adsorption_sites(...), last line
```
sites = [site + distance * self.mvec for site in sites]
```
seems should change to:
```
sites = [site + distance * np.array(self.mvec) for site in sites]
```

**Comment by janosh** [comment]
Is there a way of instantiating `AdsorbateSiteFinder` where `mvec` isn't already an `np.array`? Didn't find one. If you have one, would be good to add as test case.

Either way doesn't cost much to wrap `self.mvec` in `np.asarray(self.mvec)` and gives peace of mind. 😄 Thanks for the pointer.
