### ISSUE TITLE
Poscar inputs.py 'selective_dynamics' attribute doesn't assign appropriately passed sdynamics tags when printing or writing to file. Error is in line 487 for the inputs.py script. Currently forces selective dynamics tags to all be T. Proposed change:         sd = ["T" if j else "F" for j in self.selective_dynamics[i]] to      [j for j in self.selective_dynamics[i]]

### ISSUE THREAD

**Issue by tboland1** [materialsproject/pymatgen#1376]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sivonxay** [comment]
Hi Tara,

From what I understand, you're providing the selective dynamics as a list of 'T' or 'F' strings (e.g. {['T', 'T', 'T'], ['T', 'F', 'F'],['F', 'F', 'F']]} )

I don't think this is a bug in the code. The selective dynamics that Structure requires is a list of bool (e.g. {'selective_dynamics': [[True, True, True], [True, False, False], [False, False, False]]} )

**Comment by shyuep** [comment]
While it is indeed true that the current code takes booleans, I think we can modify it a little to support strings as well?

**Comment by tboland1** [comment]
Ahh. That would explain a lot. An interesting choice for a flag which I had not thought of. My bad, I missed the bool values in the documentation. It would be nice to have the option to pass a list of strings. It could be me but it seemed more intuitive to just supply a list which would be written to the POSCAR file. 
Thanks for the help & insight! :)
