### ISSUE TITLE
Consider renaming `stress` to `negative_stress` in VASP output parsing

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/pymatgen#1388]
**Describe the bug**

Consider rename the parsed stress from a vasprun.xml/OUTCAR from `stress` to `negative_stress` to more explicitly communicate what is actually being parsed, e.g. consider the following (thanks @montoyjh): 

```
FORCE on cell =-STRESS in cart. coord. units (eV/reduce length):
Direction X Y Z XY YZ ZX
--------------------------------------------------------------------------------------
Alpha Z 0.27 0.27 0.27
Ewald -30.64 -30.64 -30.64 0.00 0.00 0.00
Hartree 93.89 93.89 93.89 0.00 0.00 0.00
E(xc) -27.94 -27.94 -27.94 0.00 0.00 0.00
Local -147.85 -147.85 -147.85 0.00 0.00 0.00
n-local -20.54 -20.54 -20.54 0.00 0.00 0.00
augment 5.55 5.55 5.55 0.00 0.00 0.00
Kinetic 126.50 126.50 126.50 0.00 0.00 0.00
-------------------------------------------------------------------------------------
Total -0.77 -0.77 -0.77 0.00 0.00 0.00
in kB -2.41 -2.41 -2.41 0.00 0.00 0.00
external pressure = -2.41 kB Pullay stress = 0.00 kB
```

We can then also add an explicit `stress` property that creates a `Stress` object on-the-fly with the conventional sense (i.e. not negative), which can then be used for calculation of an elastic tensor etc.

Creating the issue because this change will have consequences elsewhere, e.g. atomate, so want to investigate these other uses before making any changes.

**Comment by shyuep** [comment]
Given no one else has commented, I suggest you proceed and implement the change.

My principle for pymatgen is ask for forgiveness, not permission. If it breaks something elsewhere, we can revert it later.

**Comment by mkhorton** [comment]
Yeah, I'll go ahead and do this -- it will almost certainly break some things in automata and/or our builders however, but should be easy fixes.
