### ISSUE TITLE
Bug in VoronoiConnectivity.

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#1393]
**Describe the bug**
There are failing tests with VoronoiConnectivity with new numpy version.
See https://circleci.com/gh/materialsproject/pymatgen/8309

**Desktop (please complete the following information):**
 - Master

**Comment by computron** [comment]
Why assigned to me? This is Will Richards's method AFAIK?

**Comment by computron** [comment]
Anyway maybe @utf from my team can look into it, and if no solution within an hour, to figure out what to do next

**Comment by shyuep** [comment]
Nvm. I fixed it.
