### ISSUE TITLE
wrong magmom using MPSOCSet

### ISSUE THREAD

**Issue by fraricci** [materialsproject/pymatgen#1397]
Hello,

I noticed that using MPSOCSet on a magnetic previous calculation,
it does not write the proper MAGMOM in the incar.
Example:
in: MPSOCSet.from_prev_calc('.').incar['MAGMOM']
out: [0.6, 0.6, 0.6, 0.6, 0.6]

Although, the returned structure contains the right MAGMOM:
in: MPSOCSet.from_prev_calc('.').structure.site_properties
out: {'magmom': [[0, 0, 0.523],
  [0, 0, -0.004],
  [0, 0, 0.122],
  [0, 0, 0.145],
  [0, 0, 0.068]]}

I also noticed that without specifying the prev_incar, MPSOCSet returns the right MAGMOM.

I think that the flags of the previous incar are used to write the MAGMOM.
This line of code should probably added in  from_prev_calc():
incar.update({'MAGMOM':structure.site_properties['magmom']})

**Comment by mkhorton** [comment]
This line should already be there in MPSOCSet:

https://github.com/materialsproject/pymatgen/blob/master/pymatgen/io/vasp/sets.py#L1053

It's not clear to me why that wouldn't be working just by looking at it. If you can upload your example (or email me it directly), I can investigate further.

**Comment by mkhorton** [comment]
Oh, my mistake. I think I see what's happening.

**Comment by mkhorton** [comment]
@fraricci could you share your example files with me?

**Comment by fraricci** [comment]
Yes, it seems that all the necessary code to get the decorated structure is there. 
But it works partially: it adds the magmom to the structure but the incar does not 
receive this information. I guess the magmom come from the previous incar.
Indeed, when you try:
MPSOCSet(structure,prev_incar=None).incar
the magmom is now correct.
I had a look at all the code and tried something, but I did not find where the bug is.

Solving this problem could be beneficial for the SOC firework in atomate, too.

**Comment by fraricci** [comment]
Any news on this? do you want me to propose a fix?

**Comment by mkhorton** [comment]
Sorry @fraricci, this had completely slipped my mind. If you have a fix then yes that would be great, otherwise I will take another look later.

**Comment by mkhorton** [comment]
@fraricci if you add:

```
        if 'MAGMOM' in incar:
            del incar['magmom']
```

below the lines

```
        vasprun, outcar = get_vasprun_outcar(prev_calc_dir)

        incar = vasprun.incar
```

in `MPSOCSet.from_prev_calc()` does this fix the issue?

**Comment by fraricci** [comment]
@mkhorton yes it works!
Now, it writes the magmom from the previous outcar.
I also checked that it works properly in case magmom 
is passed by the user externally.
Is it better to use: incar.pop('MAGMOM',None) ?
If I understand correctly, the incar() in MPRelax was getting the right
magmom from the structure, but incar['magmom'] was then overwritten by
the previous incar in MPSOCSet.from_prev_calc().

do you take care of push this fix?

Thanks!

I opened a issue in atomate too:
https://github.com/hackingmaterials/atomate/issues/275

**Comment by mkhorton** [comment]
Glad it works! Yes, I can push this. Our current test data is insufficient to catch it however, so I'm just going to find a test case first.

**Comment by mkhorton** [comment]
As for `pop` vs `if...del`, I think that's a matter of taste -- it really makes no difference practically speaking, `pop` has the advantage that it's only one line, but it also returns a value we never use, whereas `if...del` is more explicit about what our intention is but takes the extra line.

And you're correct: both the magmoms were getting added to the structure, *and* the previous INCAR settings were getting picked up. However, since the INCAR already had a magmom tag, the order of precedence when writing the new INCAR is to respect existing tags if present, so then the magmoms from the structure object were never used.

**Comment by mkhorton** [comment]
Ok, I've pushed this fix since it sounds like something that would be useful to have fixed now, however I'm going to leave this issue open since I have concerns about some related logic in MPStaticSet also (which MPSOCSet inherits from) so I want to investigate further.

**Comment by fraricci** [comment]
Thanks, let me know if you need some help for further test/checks.
