### ISSUE TITLE
Abandoning immutability for Site, PeriodicSite, Structure and Molecule

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#1405]
Historically, Site and PeriodicSite are considered immutable, as are IStructure and IMolecule. This is due to bad coding in the early days, which ports over the coding styles of Java to Python due to inexperience of @shyuep at that time.

These impositions are artificial, and indeed, have been violated in common practice. To simplify the code, I propose we abandon immutability for these core objects. Here are the things that need to be done:

1. I have already modified Site and PeriodicSite to allow setting of coordinates, lattice, species, etc. - all while maintaining consistency, using property.setters, with appropriate tests.
2. As a result of (1), many methods in Structure can be considerably simplified. I have done a few of these (e.g., Structure.delete_oxidation_states). This simplification has the added benefit that because we are not creating Site/PeriodicSites all the time, speed is improved by a lot.
3. We can simply a lot of other code as well, e.g., transformations, matchers, etc. By these can be done gradually. 
4. I propose we completely deprecate IStructure and IMolecule, with a view of deleting these in pmg v2020. I do not know of any places where these are used in place of Structure/Molecule. Methods will be ported over where appropriate.

@mkhorton @computron Comments?

**Comment by mkhorton** [comment]
I'm on board with this change.

In general, I like immutable data structures, and think they lend themselves to better code. However, they're only useful if they are used. I think the majority of pymatgen/MP users (and probably devs) have never used or are not aware of IStructure or IMolecule, people assume structures are mutable by default, and code like `structure.copy()` is very common for this reason. I think it makes sense that the design of pymatgen reflects how it's actually used in practice, especially if making them mutable-by-default will make the code a lot simpler, easier to understand and faster.

**Comment by computron** [comment]
IIRC, I think Hulk's original motivation for these was to have a safe object to use as dict keys.

A quick Github search for "pymatgen IStructure" does reveal that there are a lot of code snippets that use IStructure. But, it's not clear which of these snippets actually require IStructures.

For us, the only thing I remember is that we actually use IStructures in matminer as a way to help with caching - although it's not clear to me whether IStructure is needed or simply makes things more safe. I think @utf or Alex Dunn (can't tag him for some reason) could comment more on this.

**Comment by mkhorton** [comment]
> IIRC, I think Hulk's original motivation for these was to have a safe object to use as dict keys.

Always useful to have historical context! I can certainly see cases where having a structure as a dict key might be useful, but in general this seems a little dubious (given that many equivalent structures are not bit-for-bit identical, and I'm not sure how well defined the structure hash is either, so this would be probably be quite slow?). In any case, if this functionality is still required, we could just adopt a frozendict library and use structure.as_dict() as the key -- I don't think this is sufficient motivation either way for whether to keep IStructure around or not. Caching purposes are more compelling, I'm not familiar with how it's used in matminer.

**Comment by shyuep** [comment]
Yes, initially the idea is for IStructure to be hashable and usable as a dict key (or in a set). But given that it is basically near impossible to define structure equality outside the context of StructureMatcher, this is a theoretical, but not practically used feature.

As for caching, I am pretty sure immutability is not required.

Anyway, we can leave it for now. Even with the recent changes, the code has been cleaned up significantly.

**Comment by shyuep** [comment]
Just to give examples of how this change has impacted overall code:

i. Methods such as replace_species, etc. are now unified for both Molecule and Structure, instead of having duplicated methods for both (because originally, new Site/PeriodicSite had to be made). THis also makes it easier to maintain,.
ii. Many of the operations such as translate_sites can be done in place in the site, rather than making new sites.
iii. the pymatgen.core.structure module has lost ~100 lines of code with no loss in functionality.

**Comment by utf** [comment]
> For us, the only thing I remember is that we actually use IStructures in matminer as a way to help with caching - although it's not clear to me whether IStructure is needed or simply makes things more safe.

This is correct. For something to be hashable it has to be immutable, so we always cast to an IStructure for caching in matminer. 

> In any case, if this functionality is still required, we could just adopt a frozendict library and use structure.as_dict() as the key.

This would work for matminer purposes.

**Comment by shyuep** [comment]
The reason why Structure is not hashable is not because it is mutable, but because its `__hash__` is purposely set as None. We can of course just remove that and treat Structure like any other mutable object which always compare unequal and is therefore hashable.

**Comment by utf** [comment]
AFAIK comparing as equal is different to being hashable?

E.g.:

```python
x = [1, 2, 3]

hash(x)
> TypeError: unhashable type: 'list'

x == x
True
```

That said, we can just override the hash method using the frozendict idea that Matt suggested.

**Comment by shyuep** [comment]
They are different. But equal objects must have same hash. From python doc.

```An object is hashable if it has a hash value which never changes during its lifetime ```

The reason why mutable objects are usually not considered hashable is because you would typically use an invariant property as a hash. For IStructure, the hash value is simply derived from the composition. For Structure, composition can change over time. But there is really no problem with making Structure hashable simply by assuming all Structures are different and their hash is simply the default id(). AFAIK, there should be no serious practical consequences given that almost no one uses it as a dict key or expects Structure.__eq__ to mean anything significant. When we need to compare equality of structures, it is almost always with StructureMatcher.
