### ISSUE TITLE
surface.py  and symmetrized slabs / vacuumless slab

### ISSUE THREAD

**Issue by cpashartis** [materialsproject/pymatgen#1408]
1. SlabGenerator.nonstoichiometric_symmetrized_slab will not make a symmetrized surface of a conventional Silicon unit cell in the [1,0,0] direction. It returns a non symmetrized surface.

2. SlabGenerator() with 0 vacuum should return a crystal oriented in the direction of [h,k,l]?

**To Reproduce**

```
from pymatgen.core.surface import SlabGenerator
from pymatgen import Structure
from pymatgen.io.cif import CifWriter
```

Case 1.
```
st = Structure.from_file('Si_mp-149_conventional_standard.cif')
a = SlabGenerator(st, (1,0,0), 10, 15, center_slab=True)
new_st = a.nonstoichiometric_symmetrized_slab(a.get_slab()) # varying tolerance to 1E-1 doesn't help
cif_w = CifWriter(new_st[0])
cif_w.write_file('test.cif')
```
Case 2.
```
st = Structure.from_file('Si_mp-149_conventional_standard.cif')
a = SlabGenerator(st, (1,1,0), 10, 0, center_slab=True, primitive=False) # can also use lll_reduce=True ?
new_st = a.get_slab()
cif_w = CifWriter(new_st)
cif_w.write_file('test.cif')
```
**Expected behavior**
For Case 1, expected a slab to be returned with one less row / plane of original slab. I expect it is being seen as a Laue group and hence returning the original structure. Note that you get the expected behaviour should you choose [1,1,0] direction.

For Case 2, expected an orthorhombic crystal or vacuum-less slab to be created. Instead, a sheared vector is made for one axis. This can also be seen if you add 1 Angstrom of vacuum that a orthorhombic structure should be made.

P.S. I would look into it but I am having issues without some admin commands at my institute with dependencies for install.

Let me know if something I did was wrong, or if you require more information. 

**Version**
2018.9.12

**Comment by shyuep** [comment]
@richardtran415 Pls look into Case 1.

For case 2, what you want is not to give a 0 vacuum. You should just simply get the `oriented_unit_cell` property for each slab, which gives the oriented bulk structure. The slabs generator assumes you actually want a slab structure, and so imposes some minimum space.

As for dependencies, I suggest you use miniconda and create an environment to install everything. That isolates all installs into your own user directory and there should be no requirements for admin privileges. We install pymatgen and its dependencies on supercomputing clusters (which have strict security protocols) all the time.

**Comment by richardtran415** [comment]
@cpashartis 

For Case 1. you should be using a.get_slabs() with the optional parameter "symmetrize" set to True instead of a.get_slab(). The latter is used by the former to generate slab objects but is typically not suppose to be called by the user. 

```
from pymatgen.core.surface import SlabGenerator
from pymatgen import Structure
from pymatgen.io.cif import CifWriter
```
```
st = Structure.from_file('Si_mp-149_conventional_standard.cif')
a = SlabGenerator(st, (1,0,0), 10, 15, center_slab=True)
new_st =  a.get_slabs(symmetrize=True)
```

This returns a list of slabs, but since there is only one termination for a diamond (100) structure, there should only be one slab in the list.

You can check whether or not the slab is symmetric using the following slab method:
```
print(new_st[0].is_symmetric())
>True
```

which just checks if the  slab has inversion symmetry (Laue point group).

**Comment by cpashartis** [comment]
I will check this tomorrow, but then what you are telling me is that public
methods in the class yield different results... that is an issue I would
think no? Also did you try to print out the structure and visualize it?
Because I don't disagree it is Laue point group according to the symmetry
analyzer, *but* it clearly isn't inversion symmetric if you look at it.

Thanks,

Christopher Pashartis

**Comment by cpashartis** [comment]
@richardtran415 The solution you gave me is not symmetric with respect to inversion symmetry. It is symmetric in one axis, not the other. You'll notice one of the atoms on the top surface doesn't have an inversion equivalent on the bottom surface. 

Are our definitions different for symmetry? What am I missing here? Even your own comments designate symmetric as inversion symmetry and remove surfaces until they are equal.

```
from pymatgen.core.surface import SlabGenerator
from pymatgen import Structure
from pymatgen.io.cif import CifWriter

st = Structure.from_file('Si_mp-149_conventional_standard.cif')
a = SlabGenerator(st, (1,0,0), 5, 10, center_slab=True, primitive=False)

c = CifWriter(a.get_slab())
c.write_file('standard.cif')

new_st = a.nonstoichiometric_symmetrized_slab(a.get_slab(),1E-1)
print(new_st[0].is_symmetric())
c = CifWriter(new_st[0])
c.write_file('symmetrized_by_function_call.cif')

a = SlabGenerator(st, (1,0,0), 5, 10, center_slab=True, primitive=False)

symmetrized_slab = a.get_slabs(symmetrize=True)
print(symmetrized_slab[0].is_symmetric())
assert(len(symmetrized_slab)== 1)
c = CifWriter(symmetrized_slab[0])
c.write_file('symmetrized_get_slabs_with_symmetry.cif')
```

All three results are the same (the one with the `symmetry = True` is just a pi/4 rotation). Note, both claim to have `slab_name.is_symmetric() = True`.

P.S. @shyuep you probably shouldn't close the topic unless it is resolved ;).

**Comment by wenhaosun** [comment]
These slabs are clearly symmetric. Valid slabs can have mirror, two told,
four fold, six fold, glide plane or inversion symmetry.
