### ISSUE TITLE
Structure.get_primitive_structure incredibly memory intensive

### ISSUE THREAD

**Issue by utf** [materialsproject/pymatgen#1409]
For certain structures, the `Structure.get_primitive_structure` can be incredibly memory intensive. 

For example, for this structure (https://gist.github.com/utf/3982741b90a4fcb500998433e582d031), calling the function uses 20 GB of memory and takes ~2 min. Admittedly this structure has a very large unit cell (~800 atoms) but this memory usage is impractical.

Using the `SpacegroupAnalyzer.get_primitive_standard_structure` instead takes seconds with minimal memory use.

This is not a hypothetical structure and actually came from the Pearson crystal structure database.

This method is used by the `StructureMatcher.fit` function. When I originally tried to match several Pearson crystal structure database structures to Materials Project structures it crashed my computer due to memory use.

Can we:

a) Change `Structure.get_primitive_structure` to wrap `SpacegroupAnalyzer.get_primitive_standard_structure`.

or

b) Change `StructureMatcher` to instead use `SpacegroupAnalyzer`.

**Comment by shyuep** [comment]
No to (a). I would say you can add an option to select the primitive finder for (b). Structure matching is meant to be symmetry independent. The Structure.get_primitive is also non-symmetry dependent. SpacegroupAnalyzer is symmetry dependent. 

If you are getting structures from a expt database, by all means turn the tolerance down and use spglib to get a primitive version of the structure first. That is how we have always done this. 

Also, ask @computron to buy you a better laptop. :-)
