### ISSUE TITLE
Wulffshape for hexagonal lattice

### ISSUE THREAD

**Issue by dagonzalezfo** [materialsproject/pymatgen#1410]
**Describe the bug**
When I try to construct a Wulff shape for a hexagonal lattice Qhull generates the error
QH6154 Qhull precision error: Initial simplex is flat (facet 1 is coplanar with the interior point

**To Reproduce**
Execute the following commands with python 3.6.7

from pymatgen.core.surface import Lattice
from pymatgen.analysis.wulff import WulffShape

lattice=Lattice.hexagonal(3.838,6.317)

surface_energies={(1, 1, 0): 79.1,
(0, 1, 0): 79.4}

miller_list = surface_energies.keys()
e_surf_list = surface_energies.values()
wulffshape = WulffShape(lattice, miller_list, e_surf_list)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.2 LTS

 - Version : 2018.11.6
**Additional context**

**Comment by shyuep** [comment]
You do not have enough surface energies to generate a closed Wulff shape. Specifically, none of your surfaces contain the (001) direction.
