### ISSUE TITLE
Outcar class reads in elements for ZVAL dictionary non-robustly

### ISSUE THREAD

**Issue by ldwillia** [materialsproject/pymatgen#1411]
Hello,

The Outcar class in pymatgen.io.vasp reads in the atomic species by searching for the name of the POSCAR file in the OUTCAR. This is not required to have anything to do with the atomic species for VASP calculations and can cause errors importing OUTCARs made from POSCARS that were not produced with pymatgen. It may be better to search the OUTCAR for the POTCAR lines and pull the elements from the names of the pseudopotentials directly.

grepped POSCAR lines in OUTCAR example:
POSCAR: [literally any string could be here without changing calculation details]       
POSCAR = [literally any string could be here without changing calculation details]

grepped POTCAR lines in OUTCAR example:
POTCAR:    [pseudo type] [pseudo name #1 - starts with element] [date]                  
POTCAR:    [pseudo type] [pseudo name #2 - starts with element] [date]  
POTCAR:    [pseudo type] [pseudo name #1 - starts with element] [date]                  
POTCAR:    [pseudo type] [pseudo name #2 - starts with element] [date]

**Comment by mkhorton** [comment]
This is not a bad idea, would be interested in implementing the change?

**Comment by ldwillia** [comment]
Not at this time. I expect to be very busy for the next while. Someone else
could almost certainly have it implemented before I would get around to it.

**Comment by sthartman** [comment]
I believe this was fixed by PR #1521 and so the issue can be closed

**Comment by mkhorton** [comment]
Thanks @sthartman
