### ISSUE TITLE
Bug in `CifParser` for files with multiline blocks starting with `data_` prefix

### ISSUE THREAD

**Issue by sphuber** [materialsproject/pymatgen#1415]
**Describe the bug**
A bug in the `CifParser.from_string` method was reported in #1407 which was addressed in [this commit](https://github.com/materialsproject/pymatgen/commit/c34a6c0b69a6654bc6b8e9164341d5b8d6769e18). However, the solution does not actually solve the problem because now the `get_structures` method will fail to parse a valid structure.

**To Reproduce**
```
from pymatgen.cif.io import CifParser
cif = """
data_1526655
_journal_name_full
_space_group_IT_number           227
_symmetry_space_group_name_Hall  'F 4d 2 3 -1d'
_symmetry_space_group_name_H-M   'F d -3 m :1'
_cell_angle_alpha                90
_cell_angle_beta                 90
_cell_angle_gamma                90
_cell_formula_units_Z            8
_cell_length_a                   5.381
_cell_length_b                   5.381
_cell_length_c                   5.381
_cell_volume                     155.808
_iucr_refine_fcf_details
;
data_symmetries
Some arbitrary multiline string
;
loop_
_atom_site_label
_atom_site_type_symbol
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
_atom_site_occupancy
_atom_site_U_iso_or_equiv
Si1 Si 0 0 0 1 0.0
"""
parser = CifParser.from_string(cif)
parser.get_structures()
```

**Expected behavior**
A successfully parsed structure

**Desktop (please complete the following information):**
 - Ubuntu 16.04
 - On [unreleased commit](https://github.com/materialsproject/pymatgen/commit/c34a6c0b69a6654bc6b8e9164341d5b8d6769e18)

**Comment by shyuep** [comment]
I can certainly fix this problem, but as far as I know, this is bad CIF syntax. The ; is used as an indicator of a multiline string. Here, you have ; with `_iucr_refine_fcf_details`, which is not closed until after the data_symmetries loop.

**Comment by sphuber** [comment]
@shyuep you are absolutely right, my mistake. I updated the example to a CIF syntax that should now be correct. Basically the problem lies in the fact that the multiline string contains a line that starts with `data_`. The parsing strategy of `CifParser` will split all blocks on that marker, however, in this case it is not the start of an actual data block but just an ordinary string, which is legal. The fix for #1407 merely "fixes" the `IndexError` being thrown because the `_iucr_refine_fcf_details` tag was without its accompanying value. But the rest of the parsing for structures will still fail because the `data_composition` is unjustly marked as a data block leading to later problems.

**Comment by shyuep** [comment]
This is still incorrect. The data_symmetries have to be provided. Otherwise, the code cannot generate all the symmetrically equivalent positions.

In any case, I am closing this issue until an example can be provided from an actual public source that demonstrates the problem, rather than a hand-written CIF file. I prefer the CIF parsing code to be tested on real world data out there.

**Comment by sphuber** [comment]
I tried to write a representative minimal working example because the real examples I have are pretty big. But [this is a real example from the COD](http://www.crystallography.net/cod/7045976.cif) The COD has multiple CIFs like this that have the same problem and as far as I am aware, these have valid CIF syntax

**Comment by shyuep** [comment]
I downloaded the CIF. I opened it in VESTA, and I see nothing.

**Comment by mkhorton** [comment]
Is data_symmetries in an official CIF dictionary? I understand there are a
few extensions to that also (I think there’s a symmetry CIF dictionary too)

**Comment by sphuber** [comment]
For what it is worth, parsing it with `ase==3.12.0` manages to parse the cell:
```
import ase.io
In [3]: ase.io.read('cif_problem_real.cif')
Out[3]: Atoms(symbols='C144H176F48Fe4N48O16P8', pbc=[True, True, True], cell=[[15.8913, 0.0, 0.0], [9.730614839645167e-16, 15.8913, 0.0], [9.074510317001974e-16, 9.074510317001974e-16, 14.8198]], positions=...)
```
