### ISSUE TITLE
bug in work function plot

### ISSUE THREAD

**Issue by Jshcht** [materialsproject/pymatgen#1416]
**Describe the bug**
if the slab contain any atom with very big frac_z (e.g. z = 0.99 which is supposed to be -0.01 due to the perodicity), the ave_bulk_p will be wrongly calculated because the the frac_z is not a right limitation of the bulk region.

**Expected behavior**
I think during the initiation, any site with such frac_z need to be converted to (frac_z -1) to avoid such thing.

**Screenshots**
the wrong calculation:

![wrong](https://user-images.githubusercontent.com/48586099/54422639-e879ec80-4749-11e9-85ba-a9795e3ef489.jpg)
the right one after change the fra_z to fra_z -1 or just 0:
![only_electrostatic](https://user-images.githubusercontent.com/48586099/54422699-034c6100-474a-11e9-898e-879d13518585.png)

**Comment by shyuep** [comment]
@richardtran415 Pls check and follow-up

**Comment by Jshcht** [comment]
What's more, the model I used is a surface slab model.

**Comment by richardtran415** [comment]
Looking into it
