### ISSUE TITLE
I cant use the rotation function in the structure lib

### ISSUE THREAD

**Issue by jinlhr542** [materialsproject/pymatgen#1418]
![WeChat Image_20190317210246](https://user-images.githubusercontent.com/48645456/54490310-0ab16d00-48f8-11e9-9252-0fd6aeddaecc.png)

Is there something wrong with my codes?

**Comment by shyuep** [comment]
`rotate_sites` is a function that is part of the Structure class, not the structure module.
In your code, use `structure1.rotate_sites`. The indices should be numbers.
Pls post such question at https://pymatgen.discourse.group in future. Github Issues is meant for bug reports and feature requests.
