### ISSUE TITLE
Harmful standardize=True in MPNonSCF/MPStatic.from_prev_calc()

### ISSUE THREAD

**Issue by fraricci** [materialsproject/pymatgen#1424]
MPNonSCF/MPStatic.from_prev_calc(standardize=True) leads to have a CHGCAR from previous calculation and POSCAR with a NEW structure that does not match anymore with
the charge. This brings for example to a band structure completely wrong.

I think that the standardization of a structure should not be allowed in this function.

I got this problem with Ca2Si, but I guess the problem is not related to this particular material.

Note: even if the structure is already a standard primitive in the previous calculation,
sometime applying again the standardization leads to a different structure.

**Comment by shyuep** [comment]
There are reasons why standardization is sometimes necessary.
What I would suggest instead is that if standardize is True, the CHGCAR copy is not allowed and a warning is raised.

**Comment by fraricci** [comment]
Yes, I think a warning is mandatory there.
I am curious to know at least one case where is necessary to standardize at that point.
I usually standardize at the very beginning...

I would change also this notebook:
http://matgenb.materialsvirtuallab.org/2017/04/14/Inputs-and-Analysis-of-VASP-runs.html

in cell 5, a standardize=True appears to get a the input for bands calculation.

**Comment by mkhorton** [comment]
I would actually agree that standardize should be False by default for `from_prev_calc()`, though extra warnings sound sensible.

**Comment by shyuep** [comment]
I am looking at pmg's sets and it seems that it is indeed standardize=False for from_prev_calc. Is there something we need to do here or can we close this issue.

**Comment by fraricci** [comment]
As said, a warning if standardize=True is set would be very useful and, I would not copy the CHGCAR in that case.
I'm still curious to know at least one case where is necessary to standardize at that point.

I would change also this notebook:
http://matgenb.materialsvirtuallab.org/2017/04/14/Inputs-and-Analysis-of-VASP-runs.html
Shall I open an issue in matgenb?

**Comment by shyuep** [comment]
Added the warning and enforced copy_chgcar to be False. Pls modify the notebook in matgenb and submit a PR.
