### ISSUE TITLE
Pymatgen Slabs Not Json Serializable from .as_dict()

### ISSUE THREAD

**Issue by bencomer** [materialsproject/pymatgen#1425]
Currently pymatgen Structure objects are Json serializable from the `.as_dict()` but Slab objects are not Json serializable because the `scale_factor` variable is a numpy array.

This can be easily fixed by modifying the `as_dict` function to return it as a list like this:

        d["scale_factor"] = self.scale_factor.tolist()

and the `from_dict` function to convert it back into a numpy array like this:

            shift=d["shift"], scale_factor=np.array(d["scale_factor"]),

You guys may be able to think of a more elegant solution.

**Comment by shyuep** [comment]
Generally, serialization is done using the MontyEncoder. If you use that, the numpy array is automatically converted to a serializable form.

**Comment by bencomer** [comment]
hmmm, I thought the point of those functions was to just work in serialization. from the [usage](http://pymatgen.org/usage.html) page:

The output from an `as_dict` method is always json/yaml serializable. So if you want to save a structure, you may do the following:

```
with open('structure.json','w') as f:
    json.dump(structure.as_dict(), f)
```

**Comment by shyuep** [comment]
If you look further down the usage page, there is a portion which says:

```python
json.dumps(object, cls=MontyEncoder)
```

We can certainly make the dict completely json serializable. Given that the dict has more uses than simply being dumped into json, it is preferable to use the MontyEncoder to do the serialziation.
