### ISSUE TITLE
Wigner Seitz cells appear too large in difficult cases

### ISSUE THREAD

**Issue by ajjackson** [materialsproject/pymatgen#1430]
**Describe the bug**
The implementation of the Wigner-Seitz cell builder only considers lattice points up to one unit cell away
```python
        for i, j, k in itertools.product([-1, 0, 1], [-1, 0, 1], [-1, 0, 1]):
            list_k_points.append(i * vec1 + j * vec2 + k * vec3)
```
but this does not cover all possible crystal structures, and may lead to the construction of a cell that is too large.

**To Reproduce**
Calculating the distance from the origin to each surface of the WS cell
```
import numpy as np
from scipy.linalg import norm
from pymatgen import lattice
lat = lattice.Lattice.from_lengths_and_angles([5, 5, 3], [22, 90, 90])

def _distance_to_plane(facet):
    # get a vector orthogonal to the plane
    plane_vector = np.cross(facet[1] - facet[0], facet[2] - facet[0])
    # project one of the plane points onto this vector
    distance = abs(facet[0].dot(plane_vector)) / norm(plane_vector)
    return distance

distances = map(_distance_to_plane, lat.get_wigner_seitz_cell())
print(list(distances))
```
which returns:
> [2.5, 1.4999999999999984, 1.2434311765228887, 2.5000000000000004, 1.2434311765228883, 1.4999999999999998]

**Expected behavior**
![lattice_distances](https://user-images.githubusercontent.com/2511383/55157360-169cfa80-5154-11e9-8d73-41ab7a228bc4.png)
Expanding this lattice with the VESTA package we see that the nearest neighbour distance is 2.3171 Å. There should be a Wigner-Seitz cell surface running half-way through this line, giving a minimum distance from the origin to the cell boundary of 2.3171 / 2 = 1.15855

If the WS builder in Pymatgen is to be limited to "sensible" lattice vectors this should probably be mentioned in the docstring? Is there a way to detect problematic angles and raise a warning?

**Notes**
XCrySDen seems to have similar behaviour, here is its attempt at a W-S cell on the same lattice:
![xrysden_ws](https://user-images.githubusercontent.com/2511383/55159414-e015ae80-5158-11e9-96c6-8a26dd94eeab.png)
Clearly an atom-centered primitive cell should not contain any neighbouring atoms.

**Comment by mkhorton** [comment]
Do you have a suggested fix, would considering lattice points up to 2 unit cells away fix the edge cases?

**Comment by ajjackson** [comment]
I don't think it would cover _every_ case. In this example, the highlighted atom pair is three unit cells apart.

![stupid-cell](https://user-images.githubusercontent.com/2511383/56023684-56441480-5d06-11e9-8b2e-cd887f8fcf93.png)

A naive stab at an algorithm would be something like
- get distances from origin to immediate periodic images, note the furthest distance (i.e. unit cell "outer radius") to use as threshold for search
- add a shell of periodic images
- repeat adding shells until a shell only adds points beyond the threshold.

Would need a bit of pen and paper work to confirm if that is actually rigorous. It could certainly get expensive, which is why it would be very useful to have a geometric criterion (e.g. all angles greater than 30 degrees) to use the simpler routine. It does seem like the sort of problem that would have been solved a century ago, but all my textbooks have nice high-symmetry cases and avoid going near these "bad primitives".

I also note that spglib is capable of generating a "standard" primitive cell with a more reasonable set of lattice angles. I'm not the crystallography expert that is needed to determine if that will always work!

**Comment by mkhorton** [comment]
Thanks @ajjacksom, illustration is helpful!

Yes, you could definitely try the reduced cell (Structure.get_reduced_structure). Still, it would be nice to get this fixed.

**Comment by utf** [comment]
Hi Adam!

If I'm following this properly, it seems like this function in pymatgen covers a little bit of what you want: 

https://github.com/materialsproject/pymatgen/blob/6a7a2c3442e0413affda32c3704895e9a5133b72/pymatgen/core/structure.py#L1020-L1048

**Comment by mkhorton** [comment]
Yes, I’m wondering if just getting sites in a sphere of radius (max lattice vector length) during Wigner Seitz construction would fix it?

**Comment by mkhorton** [comment]
Or not even sites, lattice points I should say.

**Comment by ajjackson** [comment]
Funnily enough the reason I was looking at the W-S construction was to get a radius for use with `get_sites_in_sphere`. That does seem like an approach that should work (or maybe with a radius equal to the maximum corner-to-corner distance in the unit cell?) but I'm not entirely confident with this kind of spatial reasoning.

The reduced structure approach could be more efficient. It does require a guarantee that a) the naive 1-cell-shell method always works with reduced structures and b) the rotational orientation does not change (so that the generated W-S cell matches your input lattice).

**Comment by mkhorton** [comment]
@dmrdjenovich has found a nice method for Wigner Seitz construction that is guaranteed to give the correct answer, and nicely side-steps the need to use the SciPy Voronoi too which has some stability issues in edge cases. I'll be working with him to integrate this method into pymatgen, stay tuned...

**Comment by utf** [comment]
@mkhorton  has there been any progress on this?

**Comment by mkhorton** [comment]
Yes ... @dmrdjenovich wrote a method for this but we haven't checked in about it in a while. It still needed a SciPy Voronoi call at the end, so in that sense it's not the cleanest.

**Comment by dmrdjenovich** [comment]
Hello All,

I have implemented an algorithm that finds all 14 Voronoi vectors of a lattice in 3D space (some possibly non strict). This is a well-known algorithm from the lattice mathematical community.

Each Voronoi vector is normal to a plane of the Voronoi envelope, and each plane is offset from the origin by half of a Voronoi vector translation. So together these 14 vectors define the Voronoi envelope. 

pymatgen requires the output of the method to be a list of coordinates where the plane faces intersect. I’ve attempted to use the scipy.voronoi package to find these intersections; however, I’ve really struggled to understand how the package works. As of now that is the reason the code has not been fixed.

If anyone has any expertise on the package or has an alternative solution, I’d be happy to collaborate to finish the solution.

Best,
David

**Comment by shyuep** [comment]
This issue has been outstanding for a number of years. So I am closing it. Feel free to reopen if still valid.
