### ISSUE TITLE
io.phonopy.get_displaced_structures() calls for non-existent method

### ISSUE THREAD

**Issue by JVergnet** [materialsproject/pymatgen#1431]
**Describe the bug**
In the method _pymatgen.io.phonopy.get_displaced_structures()_, 
the call to _phonon.get_displacement_directions()_ raises an error. 

**To Reproduce**
**1**. import pymatgen.io.phonopy as pmg_phonopy
from pymatgen.core import Structure
**2** . s=Structure.from_file(your_structure_directory+"/POSCAR")
**3**. s_list = pmg_phonopy.get_displaced_structures(s,
yaml_fname="structure/phonopy/phonon.yaml")
**4**. See error : 
/usr/local/lib/python3.6/dist-packages/pymatgen/io/phonopy.py in get_displaced_structures(pmg_structure, atom_disp, supercell_matrix, yaml_fname, **kwargs)
    265     if yaml_fname is not None:
    266         displacements = phonon.get_displacements()
--> 267         directions = phonon.get_displacement_directions()
    268         write_disp_yaml(displacements=displacements,
    269                         supercell=phonon.get_supercell(),
    270                         directions=directions, filename=yaml_fname)
AttributeError: 'Phonopy' object has no attribute 'get_displacement_directions'

**Proposed fix**
The method phonon.get_displacement_directions() does not appear to exist anymore. 
Luckily, the method phonopy.file_IO.write_disp_yaml() does not require direction anymore. 
I think it should simply be updated in pmg :  
In pymatgen the call is currently :
[write_disp_yaml(displacements=displacements,                       supercell=phonon.get_supercell(), directions=directions, filename=yaml_fname)](http://pymatgen.org/_modules/pymatgen/io/phonopy.html#get_displaced_structures)
The new syntax is : 
[write_disp_yaml(displacements, supercell, filename='disp.yaml')](https://github.com/atztogo/phonopy/blob/master/phonopy/file_IO.py)

**Screenshots**
bug : 
![image](https://user-images.githubusercontent.com/32762880/55312990-0c863f00-5467-11e9-9b1b-abfb190b9584.png)

phonopy code : 
![image](https://user-images.githubusercontent.com/32762880/55313033-20ca3c00-5467-11e9-9336-18d65385316d.png)

pmg code : 
![image](https://user-images.githubusercontent.com/32762880/55313067-32abdf00-5467-11e9-9ddf-934e9a19e3d1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Mozilla

**Additional context**
Using Jupyter Notebook on Emacs via ein.

**Comment by shyuep** [comment]
@mkhorton Can you look into this one

**Comment by mkhorton** [comment]
I’ll take a look. Phonopy changed a lot of their API recently, broke some workflows in atomate too.

**Comment by mkhorton** [comment]
Yeah, we're pinned to a pre-v2 version of phonopy, I'll update + see what else is broken. Looks like there also isn't a unit test with `yaml_fname` set in `get_displaced_structures` so I'll add one.

**Comment by mkhorton** [comment]
Fixed.
