### ISSUE TITLE
New constructor _BaderAnalysis.from_ACF()_ 

### ISSUE THREAD

**Issue by JVergnet** [materialsproject/pymatgen#1438]
**Is your feature request related to a problem? Please describe.**
In the module _pymatgen.command_line.bader_caller_
I would like to build an instance of _BaderAnalysis_ from an already calculated Bader data so as to avoid repeating the summation each time I study the run without the need to dump a json.
Consequently, I would also need an option in the method _bader_analysis_from_path_ to store the resulting ACF.dat (and CHGCAR_ref and CHGCAR_mag) in a permanent directory (and not a temp_dir which would instead be the default behavior).

**Describe the solution you'd like**
This would imply 
**1)** to have a constructor _BaderAnalysis.from_ACF()_ , relying upon  an isolated ACF_parsing method oustide of the _init_(). 
**2)** to have a flag "results_path" in bader_analysis_from_objects() with a default to None (current behavior with temp_dir) which would indicate the permanent parent directory if any.

**Describe alternatives you've considered**
The alternative of using JSON to dump only the results in the directory is fine but requires a specific workflow which impedes some users to access the very useful methods _get_charge_transfer()_ and _get_oxidation_state_decorated_structure()_ This feature will allow more flexibility at a minimal coding expense.

**Comment by JVergnet** [comment]
Ok :-)

**Comment by shyuep** [comment]
This issue has been outstanding for a number of years. So I am closing it. Feel free to reopen if still valid.
