### ISSUE TITLE
waveder AttributeError: can't set attribute

### ISSUE THREAD

**Issue by amyncarol** [materialsproject/pymatgen#1442]
Unable to use the Waveder class in pymatgen.io.vasp.outputs

Error message below:

```
   4400             cder_data = cder.reshape((nbands, nelect, nk, ispin, 3))
   4401             self.cder_data = cder_data
-> 4402             self.nkpoints = nk
   4403             self.ispin = ispin
   4404             self.nelect = nelect

AttributeError: can't set attribute
```

I think this because nkpoints is a property and cannot be set. 
Change nkpoints to _nkpoints and change the nkpoints method accordingly will probably fix the problem.

**Comment by utf** [comment]
This is also the case for the `nbands` and `nelect` properties.

**Comment by amyncarol** [comment]
I am also a little confused about cder_data. Should it be a complex vector with x,y,z components for each spin? Then it should have 6 float numbers for each (band1, band2, kpoint, spin)? But from the code, we only get 3 float numbers. It should be similar to the data in wavederf, right?

**Comment by utf** [comment]
I was also having this issue, I believe the datatype for the cder should be "complex64". E.g. the data is composed of two 32 bit numbers (real and imaginary component). However, looking at the VASP code, it seems like the exact format of the data will depend on whether the wave function is complex or not. I don't know when the wave function is not complex the code seems like this could happen.

Unfortunately, even setting the dtype of cder to be complex, I couldn't get agreement between the WAVEDER and WAVEDERF file. 

Another thing to note is that `nelect` is incorrectly named. It is not actually the number of electrons. In practice I think it will just be the same as `nbands`.

**Comment by mkhorton** [comment]
Yes, the wave function is not complex if it’s gamma point only.

**Comment by amyncarol** [comment]
Any idea what's the unit of numbers in cder_data?

**Comment by amyncarol** [comment]
Seems to be standard unit J/m, right?

**Comment by shyuep** [comment]
So can someone fix this and submit a PR?

**Comment by mkhorton** [comment]
@knc6, you contributed the WAVEDER class, could you comment on this or would you be willing to submit a fix as appropriate?
