### ISSUE TITLE
”UserWarning:The input structure does not match the expected standard primitive!“

### ISSUE THREAD

**Issue by tlsong** [materialsproject/pymatgen#1448]
Hello, dear developers

When I do the band calculation，it always gives this：
“UserWarning:
The input structure does not match the expected standard primitive! The path can be incorrect. Use at your own risk.”

So，I check it carefully，use these code：
**1. first step:**
`
from pymatgen import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
import numpy as np

structure = Structure.from_file('Si_mp-149_computed.cif')
spg_analy =SpacegroupAnalyzer(structure)
primitive_standard_structure=spg_analy.get_primitive_standard_structure(international_monoclinic=False)
primitive_standard_structure.to(fmt='cif', filename='Si_mp-149_primitive_standard_structure.cif')
print(np.allclose(structure.lattice.matrix,primitive_standard_structure.lattice.matrix))
print(structure.lattice.matrix)
print(primitive_standard_structure.lattice.matrix)
`

**output:**
False
[[3.34889826 0.         1.93348731]
 [1.11629942 3.15737156 1.93348731]
 [0.         0.         3.86697462]]
[[4.39719264e-16 2.73436398e+00 2.73436398e+00]
 [2.73436398e+00 0.00000000e+00 2.73436398e+00]
 [2.73436398e+00 2.73436398e+00 3.34863009e-16]]

**2. second step:**
**use the structure file "Si_mp-149_primitive_standard_structure.cif" from step1.** 
`
from pymatgen import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
import numpy as np

structure = Structure.from_file('Si_mp-149_primitive_standard_structure.cif')
spg_analy =SpacegroupAnalyzer(structure)
primitive_standard_structure=spg_analy.get_primitive_standard_structure(international_monoclinic=False)
print(np.allclose(structure.lattice.matrix,primitive_standard_structure.lattice.matrix))
print(structure.lattice.matrix)
print(primitive_standard_structure.lattice.matrix)
`

**output:**
False
[[3.34889826 0.         1.93348731]
 [1.11629942 3.15737156 1.93348731]
 [0.         0.         3.86697462]]
[[4.39719264e-16 2.73436398e+00 2.73436398e+00]
 [2.73436398e+00 0.00000000e+00 2.73436398e+00]
 [2.73436398e+00 2.73436398e+00 3.34863009e-16]]

**Why does "np.allclose(structure.lattice.matrix,primitive_standard_structure.lattice.matrix)" give "False" in the step 2 ??**
The structure file download from here:
[Si_mp-149_computed.cif](https://materialsproject.org/materials/mp-149/cif?type=computed&download=true)
The pymatgen version is 2019.3.13

Thank you very much！

**Comment by tlsong** [comment]
I really want to know the answer. If my description is not clear, please let me know. Thank you very much

**Comment by shyuep** [comment]
@hautierg Can you help with this?

**Comment by tlsong** [comment]
@shyuep @shyamd 
Thank you very much!

**Comment by tlsong** [comment]
@shyuep @shyamd 

Export the strucutre in POSCAR format, will give true.
**1.**
`
from pymatgen import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
import numpy as np

structure = Structure.from_file('Si_mp-149_computed.cif')
spg_analy =SpacegroupAnalyzer(structure)
primitive_standard_structure=spg_analy.get_primitive_standard_structure(international_monoclinic=False)
primitive_standard_structure.to(fmt="poscar", filename="primitive_standard_structure_POSCAR")
`
**2.**
`
from pymatgen import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
import numpy as np

structure = Structure.from_file('primitive_standard_structure_POSCAR')
spg_analy =SpacegroupAnalyzer(structure)
primitive_standard_structure=spg_analy.get_primitive_standard_structure(international_monoclinic=False)
print(np.allclose(structure.lattice.matrix,primitive_standard_structure.lattice.matrix))
print(structure.lattice.matrix)
print(primitive_standard_structure.lattice.matrix)
`
**output:**
True
[[0.       2.734364 2.734364]
 [2.734364 0.       2.734364]
 [2.734364 2.734364 0.      ]]
[[4.39719268e-16 2.73436400e+00 2.73436400e+00]
 [2.73436400e+00 0.00000000e+00 2.73436400e+00]
 [2.73436400e+00 2.73436400e+00 3.34863012e-16]]

Thank you  very much!

**Comment by shyamd** [comment]
Sounds good. I'm closing this now.
