### ISSUE TITLE
Is it possible to apply biaxial deformation?

### ISSUE THREAD

**Issue by afonari** [materialsproject/pymatgen#1450]
Is it possible to apply biaxial deformation besides shear and non-shear modes defined in the DeformedStructureSet:
```# Generate deformations
        for ind in [(0, 0), (1, 1), (2, 2)]:
            for amount in norm_strains:
                strain = Strain.from_index_amount(ind, amount)
                self.deformations.append(strain.get_deformation_matrix())

        for ind in [(0, 1), (0, 2), (1, 2)]:
            for amount in shear_strains:
                strain = Strain.from_index_amount(ind, amount)
        self.deformations.append(strain.get_deformation_matrix())
```

**Comment by shyuep** [comment]
@mkhorton I think so?

**Comment by shyuep** [comment]
For future reference, pls post queries on https://pymatgen.discourse.group and use Github Issues for only bug reports.

**Comment by mkhorton** [comment]
Hi @afonari, it's possible to apply any arbitrary deformation. You can initialize directly from a `Strain` object:

```
from pymatgen.analysis.elasticity.strain import Strain
strain = Strain(your_biaxial_strain_matrix)
deformation = strain.get_deformation_matrix()
deformed_structure = deformation.apply_to_structure(your_structure)
```

**Comment by afonari** [comment]
Thanks for the reply @mkhorton. What I meant, is it possible to incorporate biaxial strain into the computations of the elastic modulus. Do you maybe have a any examples of biaxial strains?

Thanks.

**Comment by mkhorton** [comment]
Ah, yes, I believe so. You can fit an elastic tensor with any system of independent strains, including biaxial strains:

```
from pymatgen.analysis.elasticity.elastic import ElasticTensor
tensor = ElasticTensor.from_independent_strains(list_of_strains, list_of_stresses)
```

Does that answer your query? If not maybe @montoyjh would like to comment

**Comment by afonari** [comment]
Some example would definitely help with this, thanks.
