### ISSUE TITLE
How to create input files for abinit by using pymatgen?

### ISSUE THREAD

**Issue by pincher-chen** [materialsproject/pymatgen#1462]
Dear developers,

I found pymatgen supports the  input/output  operations for abinit, and tried to use pymatgen to generate the input files. However, little  documents or descriptions for abinit can be found in http://pymatgen.org/. I found it easy to create POSCAR from cif file for vasp:
```
>>> structure = mg.Structure.from_file("CsCl.cif")
>>> structure.to(fmt="poscar")
>>> structure.to(filename="POSCAR")
```
So, does pymatgen have the similar method to create input file for abinit?

Regards.

**Comment by shyuep** [comment]
Please post questions on https://pymatgen.discourse.group . @gmatteo Can you answer this pls? It would be helpful if you write a simple example notebook at https://matgenb.materialsvirtuallab.org for ABINIT io.
