### ISSUE TITLE
Changing the signature of vaspinputset.from_prev() 

### ISSUE THREAD

**Issue by computron** [materialsproject/pymatgen#1464]
Currently, the from_prev() method in the VaspInputSets is a wild west of parameters - i.e., there is no consistency in the signature of from_prev() between different VaspInputSets.

This ends up causing a lot of downstream complexity in atomate. Although the atomate FireTasks can take in a VaspInputSet object to help users control input settings, they usually also mirror the from_prev() parameters to allow users to also control the behavior of the from_prev() method for the VaspInputSet.

The current situation in atomate is unambigously a mess. There are two potential solutions:
i) Atomate uses a single **kwargs style option for updating from_prev() settings in a VASP input set. Thus, at least it would not be mirroring a dozen parameters.
ii) Pymatgen VASP input sets are modified so that *all* parameters (including parameters currently set independently in the from_prev() method) are in the constructor. The method signature of from_prev() is the same for all VaspInputSets, which will be ```my_vaspinputset.from_prev(directory=".")``` - i.e., the only parameter for from_prev is the directory, every other parameter is set in the constructor.

We (atomate discussion team) think (ii) is the much better solution, since it means that once you create an input set, all the rules/flags/etc on the operation of that inputset are determined and can be serialized, etc. e.g., I can serialize my from_prev() settings and not just my "normal" settings. Furthermore, I think this solution is also much cleaner than having atomate create a kwargs-style parameter specifically for passing into the ``from_prev()`` of a vaspinput set.

Thoughts? Is this practical to change?

**Comment by shyuep** [comment]
My view is that there are both use cases. The problem with the suggested Option 2 is that the logic flow is strange. Initialization VaspInputSet requires a Structure, which presumably is being read from a previous calculation in these cases. I would also prefer not to wreak havoc on a lot of people's scripts (including a large fraction of my group). 

I would suggest a Third option that will achieve what you want and is totally backwards compatible.

```python
class VaspInputSet:

    def __init__(structure, ...):
        remains the same.

    def override_from_prev_calc(path="."):
        what you are suggesting in the new from_prev

    @classmethod
    def from_prev_calc(*still the same API and parameters*):
        uses __init__ and override_from_prev_calc to achieve exact same effect as current from_prev_calc
```

For atomate, you should use `__init__` and  `override_from_prev_calc`, which will allow you to standardize the code.

**Comment by computron** [comment]
Two comments:

* The more direct comment is that I don't see how adding override_from_prev_calc helps. Yes, atomate can use this, but then the user has no way to adjust the settings. For example, MPStaticSet.from_prev_calc() currently has a "small_gap_multiply" setting that multiplies k-point meshes for small gap systems. An atomate user might want to adjust this parameter in the workflow. If we just use override_from_prev_calc(), there will be no option to modify small_gap_multiply (unless we move that parameter to the constructor as suggested).

* The more indirect comment is that the fact that VaspInputSet (VIS) requires a structure is also a problem. Often, we want to be able to set up parameters (a VIS object) for a downstream job, but don't yet know exactly what the structure will be. e.g., when writing a workflow like removing Li in the middle, and you don't know what the structure will actually be for the subsequent steps but still need to define a VIS for those runs. Right now we have just two options when trying to set up a VIS in advance of the actual calculation - (i) put in a dummy structure so that we can create the VIS for now (but we need to remember to update it later on, else it will have the wrong structure in it), or (ii) specify the VIS as a String only and only load the full VIS object when the workflow executes. Ideally, the VIS would operate such that the structure is only passed in at the time of creating the input files. Then I could also easily reuse the same VIS for multiple structures.

**Comment by shyuep** [comment]
i. Yes, I mean we move those things to the constructor. I am asking that you do not break from_prev_calc.
ii. We already had extensive debates about whether structure should be part of VIS. It is true that it will require VIS to be constructed for every structure. But the other side of the story is that often structure modification is part of the input file generation. E.g., standardizing a structure to some basis, or setting up some NEB calculations.

**Comment by computron** [comment]
For (i) - I see, but then we will have duplicated parameters in the constructor and in from_prev() - is that OK with you?

**Comment by shyuep** [comment]
We will not have duplicated parameters. Just move the parameters to constructor, remove them from from_prev, and from_prev will simply pass through using *args and **kwargs. That is already the case for other common parameters such as user_incar_settings. We just need to lump these parameters into that.

**Comment by utf** [comment]
I am happy to implement what has been discussed in this thread, however, I think it is not as simple as simply moving the keyword arguments of `from_prev_calc` to `__init__`. This is mainly because `from_prev_calc` needs to have access to the defaults of the keyword arguments before they are passed to through to the constructor.

A solution to this is to define the defaults required by `from_prev_calc` as class variables, which would then be used by both `from_prev_calc` and `__init__`. We would also then need to check whether the keyword argument had separately been based to `from_prev_calc`, which would introduce some boilerplate. E.g.

```python
class VaspInputSet:

    reciprocal_density = 200

    def __init__(structure, reciprocal_density=reciprocal_density, ...):
        # remains the same.

    @classmethod
    def from_prev_calc(prev_calc_dir, **kwargs):
        reciprocal_density = kwargs.get("reciprocal_density", reciprocal_density)
        # do something with reciprocal density.
```

The input set would therefore require a class variable and the ` kwargs.get("reciprocal_density", reciprocal_density)` boilerplate for every variable required by `from_prev_calc`.

If this is acceptable I will implement.

**Comment by shyuep** [comment]
I am confused. If the defaults are the same, if you move them to the constructor, there should be no difference from the defaults being in from_prev? E.g., if the original default reciprocal density is 200, putting that number in the constructor now would still mean that from_prev_calc will use the 200 default.

**Comment by utf** [comment]
In the example I posted, `from_prev_calc` needs to know what the default is before the inputset is constructed, as it will adjust the default value based on the output of the previous calculation. An example from an existing inputset is:

```python
    def from_prev_calc(cls, prev_calc_dir, reciprocal_density=100,
                       small_gap_multiply=None, ... ):

        ...

        # multiply the reciprocal density if needed:
        if small_gap_multiply:
            gap = vasprun.eigenvalue_band_properties[0]
            if gap <= small_gap_multiply[0]:
                reciprocal_density = reciprocal_density * small_gap_multiply[1]

        return cls(reciprocal_density=reciprocal_density, ...)
```

E.g., If the user does not pass `reciprocal_density` or `small_gap_multiply` to `from_prev_calc`, we need to access the defaults defined in the constructor.

**Comment by shyuep** [comment]
@utf No. The idea is that from_prev_calc will now call the constructor AND the new override_from_prev_calc. Obviously, the second call comes after the constructor and therefore would have access to the constructor defaults. We should not be duplicating code in from_prev_calc and override_from_prev_calc.

**Comment by utf** [comment]
I understanding what you are suggesting now.
