### ISSUE TITLE
Delay warning of missing requirements in `io.cif` as a late as possible

### ISSUE THREAD

**Issue by sphuber** [materialsproject/pymatgen#1507]
**Is your feature request related to a problem? Please describe.**
Delay the printing of warnings as late as possible in `io.cif`.
Currently, just importing the module `io.cif` will print the warning if `pybtex` is not installed:
```
try:
    from pybtex.database import BibliographyData, Entry
except ImportError:
    warnings.warn("Please install optional dependency pybtex if you"
                  "want to extract references from CIF files.")
    BibliographyData, Entry = None, None
```
However, the only function requiring it is `get_bibtex_string`.

**Describe the solution you'd like**
Since these warnings are not easy to suppress and show up even when not applicable it would be better to just move this warning to within the `get_bibtex_string` itself. One can simply extend the message of the `requires` decorator

**Comment by shyuep** [comment]
Thanks. I fixed this. But instead of a warning, I simply make it throw an exception. The idea is that if someone is calling get_bibtex_string, they must actually be interested in a result and a runtime error should ensue if pybtex is not installed.

**Comment by sphuber** [comment]
Thanks for the very quick response and action @shyuep :+1:
