### ISSUE TITLE
Obey and fix deprecation warnings

### ISSUE THREAD

**Issue by espenfl** [materialsproject/pymatgen#1511]
**Is your feature request related to a problem? Please describe.**
Please consider to fix all relevant deprecation warnings. One example:

```
pymatgen/core/sites.py:31: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    class Site(collections.Hashable, MSONable):
```

Particularly annoying when running `pytest` and we do not want to ignore warnings.

**Describe the solution you'd like**
Fix these, for instance with six, e.g.

```
if six.PY2:
    from collections import Hashable
else:
    from collections.abc import Hashable
```
etc.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by shyuep** [comment]
As far as I know, this was fixed some time ago. If you believe this not to be true, pls go ahead and implement a fix. As for using six, we already abandoned Py2 support from 2019.

**Comment by espenfl** [comment]
Yes, in fact they should be present since `v2019.3.13`. Sorry for the noise.
