### ISSUE TITLE
BabelMolAdaptor should be able to return all molecules found in a file

### ISSUE THREAD

**Issue by smheidrich** [materialsproject/pymatgen#1512]
**Is your feature request related to a problem? Please describe.**
The way it's currently implemented, ``pymatgen.io.babel.BabelMolAdaptor`` will only ever return the first molecule it finds in a file and discard the rest:
https://github.com/materialsproject/pymatgen/blob/5006e2c92d669a05775fcf67dd9b1f0b972c9636/pymatgen/io/babel.py#L314-L315
It still *loads* all of them though and holds them all in memory simultaneously, so in a way it's the worst of both worlds.

**Describe the solution you'd like**
It would be cool if all molecules found within a file could be accessed.

**Describe alternatives you've considered**
- not implementing this

**Additional context**
There is precedent for this e.g. in [``pymatgen.io.xyz``](https://pymatgen.org/pymatgen.io.xyz.html), which loads and stores everything by default and lets you access either only the last frame via the ``molecule`` property or all frames via ``all_molecules``.

**Comment by mkhorton** [comment]
Tagging @samblau here since he's been working a lot with the OpenBabel adapter.

**Comment by mkhorton** [comment]
@samblau and I were chatting and it looks like the easiest solution would be to add a new keyword argument, `return_all_molecules=False`, that when set to `True` would just return the entire list (we should set it to False by default to maintain backwards compatibility).

@smheidrich would you be willing to implement this with a test and submit a pull request?

**Comment by smheidrich** [comment]
So it should return one instance of ``BabelMolAdaptor`` per molecule? I agree that this would be easiest to implement (as a matter of fact, that's what I've been doing as a workaround :P), although it's not very consistent with other ``io`` modules, which generally have only one filetype-specific object associated with each file (e.g. [``xyz.XYZ``](https://pymatgen.org/pymatgen.io.xyz.html#pymatgen.io.xyz.XYZ), [``cif.CifParser``](https://pymatgen.org/pymatgen.io.cif.html#pymatgen.io.cif.CifParser), [``vasp.outputs.Vasprun``](https://pymatgen.org/pymatgen.io.vasp.outputs.html#pymatgen.io.vasp.outputs.Vasprun)), which can then be used to obtain a list of molecules or structures ([``XYZ.all_molecules``](https://pymatgen.org/pymatgen.io.xyz.html#pymatgen.io.xyz.XYZ.all_molecules), [``CifParser.get_structures``](https://pymatgen.org/pymatgen.io.cif.html#pymatgen.io.cif.CifParser.get_structures), [``Vasprun.structures``](https://pymatgen.org/pymatgen.io.vasp.outputs.html#pymatgen.io.vasp.outputs.Vasprun.structures)). But implementing it in this way would be a bit more work, of course (could be done e.g. introducing ``_obmols`` instead of ``_obmol`` and making all the existing methods work on just ``_obmols[0]`` to maintain backwards-compatibility, then introducing plural versions for working with the full list).

Anyway, if you're set on the one-instance-per-molecule solution, I'm happy to write it up and submit a PR.

**Comment by shyuep** [comment]
Just a note that CIfParser supports multiple structures. For now, I would just suggest the from_file method returns a list of BabelMolAdaptors for each molecule. We should probably rethink the BabelMolAdaptor API.

**Comment by smheidrich** [comment]
>Just a note that CIfParser supports multiple structures.

All the examples I listed do, but what I'm saying is that the API is different from what is proposed here.

>For now, I would just suggest the from_file method returns a list of BabelMolAdaptors for each molecule.

Fair enough, I'll send a PR soon.
