### ISSUE TITLE
Vasprun does not discriminate both Kpoint sets when LVEL flag is set

### ISSUE THREAD

**Issue by JRSuckert** [materialsproject/pymatgen#1513]
**Describe the bug**
When running VASP with the LVEL flag set, two kpoint sets are generated (probably IBZ and FBZ).
The Vasprun class will read both to the same variable overwriting the first that has been read.
Unfortunately, the set that is overwritten is the one associated to the eigenvalue array.
In the vasprun, the structure is somewhat like:
```
<modelling>
  <kpoints>
    ....
  </kpoints>
  <electronvelocities>
    <kpoints>
    ....
    </kpoints>
  </electronvelocities>
</modelling>
```

**To Reproduce**
1. Run vasp with LVEL and LOPTICS flag
2. Initialize Vasprun with resulting vasprun.xml
3. Compare size of eigenvalues in Vasprun().eigenvalues with size of Vasprun.actual_kpoints

**Expected behavior**
Separate kpoint variables, or a list of kpoint sets.

Edit: corrected xml tree

**Comment by shyuep** [comment]
Thanks for reporting this. I have no idea what the LVEL tag does. If this is an issue, I would suggest you perhaps fork the repo and implement a quick fix?

**Comment by JRSuckert** [comment]
The actual purpose of the LVEL flag is also unclear to me, as it is undocumented.

In my particular case, I want to use it as it will write the full set of matrix elements <u|d/dk|u> for (ikpt, nbands, nbands) into the WAVEDER file, which by default is only done for a subset.

I will attempt to fix it.

**Comment by JRSuckert** [comment]
I'm not particularly experienced in parsing xml files, so maybe someone else can give me a hint.
The vasprun is parsed using the iterparse method of the ElementTree so it's not possible to determine the according parent.

A quick fix would be to check if self.kpoints has already been set and then skip later tag matches.
```python
if not hasattr(self, 'kpoints'):
  self.kpoints, self.actual_kpoints, self.actual_kpoints_weights = self._parse_kpoints(elem)
```

Right now it should not break anything, since the kpoint set used for self-consistency is quite far up in the element tree, but I'm not sure how future proof it is, maybe someone else got an idea?
