### ISSUE TITLE
Python 3.6 as hard requirement 

### ISSUE THREAD

**Issue by ajjackson** [materialsproject/pymatgen#1522]
**Describe the bug**
I'm getting CI failures when testing a package that depends on Pymatgen with Python 3.5. It is announced in the README file that only Python 3.6 is supported, but the setup.py refers to older versions and nothing is being enforced for Pip. Please use `python_requires` to prevent Python3.5 users from "upgrading" to a (from their perspective) broken version of Pymatgen.

**To Reproduce**

On a Python 3.5 system:
```
pip install pymatgen
python3 -c "import pymatgen.io.vasp.outputs"
```

**Expected behavior**
I'm not entirely sure what it looks like in practice but a `python_requires` in _setup.py_ should stop Pip from installing incompatible versions. There is a slight gotcha in that this feature has only been around since Pip 9.00.

**Comment by mkhorton** [comment]
Thanks @ajjackson, we’ll correct this.

The Py3.6 notice is quite new, mostly as a result of our own CI and to reduce our maintenance burden, but we’re open to explicitly supporting earlier versions of Py3 if there was a need for it in the community. Do you have any opinions on this?

**Comment by ajjackson** [comment]
3.6 is the most recent version available on most of the systems I have access to. The UCL Sumo users would definitely be ok. I'd be more worried about people doing Fireworks stuff on smaller institutional machines... Python 3.6 has only been out for 3 years, which seems to me the absolute minimum time that's ok to make it a  hard requirement without a lot of pushback.

I would love to start using f-strings in production code though...

**Comment by mkhorton** [comment]
Yes, I'd be lying if I said f-strings weren't a factor :) There's also dataclasses (a back port exists for 3.6 but not 3.5), ordered dicts by default etc. We're also trying to make heavier use of type hints in the core classes, though that's a 3.5 feature so we're fine there.

If you (or anyone else reading this) has significant issues with the 3.6 requirement however please let us know, we're definitely open to formally supporting 3.5 if necessary. To my knowledge there's nothing in pymatgen that shouldn't in principle work in 3.5 currently.

And to clarify, this is for pymatgen specifically, there are no plans to change version requirements for fireworks, monty, etc.

**Comment by mkhorton** [comment]
Closed via https://github.com/materialsproject/pymatgen/commit/ed9396b385e9f5b262eb0289f69630893b7f72c1

**Comment by ajjackson** [comment]
Ok, thanks for clarity.

Just a comment on ordered dicts: as of 3.6 they are an implementation detail of CPython and not guaranteed. Alternative implementations may not be ordered so you should still use OrderedDict wherever it matters (but in CPython it will pass through to the same implementation as _dict_). As of 3.7 it is part of the language spec, so you can assume all dicts are ordered once  going to 3.7 as the minimum supported version.

**Comment by shyuep** [comment]
Just a note that while I am on board for Dataclasses, I am less enamored of the idea of f-strings over say the standard str.format. I can certainly see convenience benefits, but in my opinion, it makes it hard to figure from context what the string actually is if the variable values are defined far away from the actual string.

**Comment by mkhorton** [comment]
f-strings can be directly equivalent to format, I see it as more a syntax choice, e.g.:

```
"Lattice params are {}, {} and {}".format(a, b, c)
```

or

```
"Lattice params are {a}, {b} and {c}".format(a=a, b=b, c=c)
```

vs

```
f"Lattice params are {a}, {b} and {c}"
```

Where a, b and c are defined is an implementation choice, at least in that sense I'm not sure I see why f-strings are any better/worse than .format

**Comment by shyuep** [comment]
The .format forces you to specify at the location of the string what the values of a, b and c are. Of course a, b and c can be defined far away, but the more common application is "{a}".format(a="hello").

**Comment by ajjackson** [comment]
I think it's on the programmer to use both f-strings and format() responsibly. If you're going to define a template and populate it elsewhere then format() is the better tool for the job. But I write a lot of code that looks like @mkhorton 's example and in that case the f-string is easiest to read and has the least potential for surprises.

With format() I have to read more carefully in case of something like
```python
"lattice params are {a}, {b} and {c}".format(a=b, b=c, c=a)
```
