### ISSUE TITLE
get_spd_dos() doesn't work?

### ISSUE THREAD

**Issue by Nokimann** [materialsproject/pymatgen#1530]
**Describe the bug & To Reproduce**
vasprun= Vasprun(path_vasprun, parse_dos=True)
dos = vasprun.complete_dos
dos.get_site_orbital_dos(dos.structure.sites[0],OrbitalType.d)
dos.get_spd_dos()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/noki/anaconda3/envs/procar/lib/python3.7/site-packages/pymatgen/electronic_structure/dos.py", line 745, in get_spd_dos
    add_densities(spd_dos[orbital_type], pdos)
  File "/home/noki/anaconda3/envs/procar/lib/python3.7/site-packages/pymatgen/electronic_structure/dos.py", line 998, in add_densities
    for spin in density1.keys()}
  File "/home/noki/anaconda3/envs/procar/lib/python3.7/site-packages/pymatgen/electronic_structure/dos.py", line 998, in <dictcomp>
    for spin in density1.keys()}
KeyError: <Spin.up: [1>]

(My calculation result contains only Spin.up info.)

There are similar errors when typing

`dos.get_element_dos()`
`dos.get_element_spd_dos(dos.structure.symbol_set[0])`
`dos.get_site_dos(dos.structure.sites[0])`

after executing 

 `dos.get_site_orbital_dos(dos.structure.sites[0],OrbitalType.d)`

But if I re-bulid 
`vasprun= Vasprun(path_vasprun, parse_dos=True)`
`dos = vasprun.complete_dos`
(not from `dos = vasprun.complete_dos`)
It works again.

**Desktop (please complete the following information):**
CentOS 7

**Additional context**
Name / Version / Build / Channel
pymatgen / 2019.7.2 / pypi_0 / pypi

**Comment by Nokimann** [comment]
> **Describe the bug & To Reproduce**
> vasprun = Vasprun(path_vasprun, parse_dos=True)
> dos = vasprun.complete_dos
> dos.get_spd_dos()
> Traceback (most recent call last):
> File "", line 1, in 
> File "/home/noki/anaconda3/envs/procar/lib/python3.7/site-packages/pymatgen/electronic_structure/dos.py", line 745, in get_spd_dos
> add_densities(spd_dos[orbital_type], pdos)
> File "/home/noki/anaconda3/envs/procar/lib/python3.7/site-packages/pymatgen/electronic_structure/dos.py", line 998, in add_densities
> for spin in density1.keys()}
> File "/home/noki/anaconda3/envs/procar/lib/python3.7/site-packages/pymatgen/electronic_structure/dos.py", line 998, in 
> for spin in density1.keys()}
> KeyError: <Spin.up: 1>
> 
> (My calculation result contains only Spin.up info.)
> 
> **Desktop (please complete the following information):**
> CentOS 7
> 
> **Additional context**
> Name / Version / Build / Channel
> pymatgen / 2019.7.2 / pypi_0 / pypi

**Comment by Nokimann** [comment]
I solved, sorry.
When I re-build the above scripts, it works.

**Comment by Nokimann** [comment]
copy.deepcopy works neither. Only after recalling the file, then it works.

**Comment by arosen93** [comment]
@janosh: I think this can be closed. `.get_spd_dos()` is widely used by MP and I've tested it more than probably any function in MP. We can re-open if someone has an issue.
