### ISSUE TITLE
sum_densities(*densities)

### ISSUE THREAD

**Issue by Nokimann** [materialsproject/pymatgen#1531]
**Is your feature request related to a problem? Please describe.**
When I first encountered too simple function `add_densities(density1, density2)`,
I needed to sum multiple a list of density. But there is no feature something like `sum_densities(*densities)`

**Describe the solution you'd like**
I suggest below
```
def sum_densities(*densities):
        if len(densities) == 1:
                return densities[0]
        else:
                density_0 = denstiies[0]
                density_1 = denstieis[1]
                return sum_densities(add_densities(density_0, density_1),
                                     *densities[2:])
```

**Comment by shyuep** [comment]
This can be done using Python's built-in reduce function.
