### ISSUE TITLE
CubicSupercellTransformation and PerturbSitesTransformation not MSONable

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/pymatgen#1536]
@utf @rees-c 

This should be trivially fixable, just make sure the class attribute names match the keyword arg names and that the default values are JSON serializable (e.g. `None` for a default and set `np.Inf` in the body of the init), and then it should "just work." @rees-c you can check this by calling `.as_dict()`, `.from_dict()` etc

**Comment by mkhorton** [comment]
I also realize there's something overlap between `PerturbStructureTransformation` and `PerturbSitesTransformation`; thoughts on merging these?

**Comment by mkhorton** [comment]
Additionally, I just realized that PeturbSitesTransformation is a one-to-many but it doesn't follow the correct format of a one-to-many transformation (see the AbstractTransformation apply_transformation docstring or other one-to-many transformations for an example).

In the long term, I think we could probably clean up the AbstractTransformation base class to make the method signature more consistent between one-to-one and one-to-many transformations, but for now PerturbSites should be fixed to make it consistent with other transformations, else it will not be able to be used e.g. for TransmuterFW in workflows etc.

**Comment by utf** [comment]
@rees-c Can you respond to Matts comments/fix the transformation.

**Comment by rees-c** [comment]
Hey @mkhorton ! Sorry for the late reply - I'm a bit new to Git and my gmail seems to silence my Github notifications. I'll send another pull request with the JSON serialization fixes and the corrected one-to-many format for PerturbSitesTransformation.

I see now that PerturbSitesTransformation can replicate the output of PerturbStructureTransformation. On the flip side, I feel that if a user only needs a single perturbed structure, then reading through a one-to-many transformation with its corresponding variable names could be nonintuitive (i.e. if a user wanted to replicate the output of PerturbStructureTransformation using PerturbSitesTransformation, they would have to set `return_ranked_list=False` in `apply_transformation`, `min_random_distance=None` in the init, and `min_disp` to the desired distance). Do you have any thoughts about what would be the best way to merge the two while maintaining backwards compatibility if we choose to do so?

**Comment by mkhorton** [comment]
No worries, and thanks for the fix.

Regarding merging them, they *should* be merged, but I'm agnostic to the specific method.

The `PerturbStructureTransformation` is basically a wrapper around the `Structure.perturb` method, so one option would be to improve that method to make it more powerful.

I find the current docstring for `PerturbSitesTransformation` a little confusing actually, it's possibly trying to do too much (e.g. if you want multiple structures for multiple displacement distances, why not create multiple transformations to do that? so `max_disp`, `min_disp`, `num_disps` may not be necessary, or at least maybe accept a list of displacements instead and let the user figure out how to do them? It took me a few reads to understand the distinction between `min_disp` and `min_random_distance` which I think is partly why I found it confusing.) Open to ideas on this!

**Comment by shyuep** [comment]
My view: PerturbSitesTransformation should be a one-to-one transformation. If someone wants multiple site perturbations, they can call it multiple times with different displacements. Class design should be for the most common use case, not a strangely powerful use case that is used 0.0001% of the time.

**Comment by mkhorton** [comment]
I agree -- I don't mind it being one-to-many if the "many" are just different random perturbations for the same displacement magnitude. But if the "many" are different random perturbations but also for *different* displacement magnitudes, I think that's just confusing, because you're varying two different variables.

**Comment by rees-c** [comment]
Thanks for the helpful feedback! I agree with all your points - I'll submit a pull request.
