### ISSUE TITLE
Failed to read cifs files

### ISSUE THREAD

**Issue by WSHYY** [materialsproject/pymatgen#1537]
**System**
Python version: 3.5.2
OS version: Windows 10

**Summary**
I download the cif file in AMCSD. And pymatgen failed to read the cif file

I was trying to convert cif to jcpds.

I don't know what is the problem

**Example code**
import pymatgen as mg
from pymatgen import Lattice, Structure
from pymatgen.analysis.diffraction.xrd import XRDCalculator
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

fn_cif = "Ice6.cif"       
fn_jcpds = 'Ice6.jcpds'
comments_jcpds = "Ice6"

material = mg.Structure.from_file(fn_cif)

**Error message**
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-99a894ef35cb> in <module>
----> 1 material = mg.Structure.from_file(fn_cif)

~\Anaconda3\lib\site-packages\pymatgen\core\structure.py in from_file(cls, filename, primitive, sort, merge_tol)
   2092             return cls.from_str(contents, fmt="cif",
   2093                                 primitive=primitive, sort=sort,
-> 2094                                 merge_tol=merge_tol)
   2095         elif fnmatch(fname, "*POSCAR*") or fnmatch(fname, "*CONTCAR*") or fnmatch(fname, "*.vasp"):
   2096             s = cls.from_str(contents, fmt="poscar",

~\Anaconda3\lib\site-packages\pymatgen\core\structure.py in from_str(cls, input_string, fmt, primitive, sort, merge_tol)
   2026         if fmt == "cif":
   2027             parser = CifParser.from_string(input_string)
-> 2028             s = parser.get_structures(primitive=primitive)[0]
   2029         elif fmt == "poscar":
   2030             s = Poscar.from_string(input_string, False,

~\Anaconda3\lib\site-packages\pymatgen\io\cif.py in get_structures(self, primitive)
   1109                 warnings.warn(error)
   1110         if len(structures) == 0:
-> 1111             raise ValueError("Invalid cif file with no structures!")
   1112         return structures
   1113 

ValueError: Invalid cif file with no structures!

**Files**

[Ice6.zip](https://github.com/materialsproject/pymatgen/files/3425151/Ice6.zip)

**Comment by mkhorton** [comment]
I imagine it's failing because it doesn't contain positions of individual atoms, only of water molecules ("Wat"), pymatgen doesn't really know what to do here. We could reasonably put a water molecule on these positions but the orientations would be arbitrary.

**Comment by arosen93** [comment]
@janosh: Can probably close this as being out of scope.
