### ISSUE TITLE
Is there projected band structure on a site?

### ISSUE THREAD

**Issue by Nokimann** [materialsproject/pymatgen#1539]
Only two functions are pooling on elements or elements with orbital? I'm looking for a function working with the projected band structure on a particular site or a group of sites plus OrbitalType.
Also, I couldn't see the function on Orbital: s, px, py, ... (not OrbitalType: s, p, d, f)

In DOS objects, some functions are extracting on a site plus Orbital and OrbitalType.

**Comment by computron** [comment]
The "projections" attribute of the BandStructure object should have the projections:

```
        projections: dict of orbital projections as {spin: ndarray}. The
            indices of the ndarrayare [band_index, kpoint_index, orbital_index,
            ion_index].If the band structure is not spin polarized, we only
            store one data set under Spin.u
```

There doesn't seem to be a convenience method to collect together the data on a single ion_index and orbital_index so you'd have to write your own that is similar to elements / elements with orbital.
