### ISSUE TITLE
Improper pdos for the result from SOC calculation (VASP)

### ISSUE THREAD

**Issue by Nokimann** [materialsproject/pymatgen#1540]
**Describe the bug**
There are four spin numbers in vasprun.xml when we calculate DOS with SOC. They represent 'total, mx, my, and mz' for each OrbitalType. But DOS Object only considers Up and Down as Total and mx (no more than two spin numbers). And, I think Up and Down are not proper namings because they don't come from spin polarization.

**Desktop (please complete the following information):**
CentOS 7
pymatgen / 2019.7.2 / pypi_0 / pypi

**Additional context**

**Comment by utf** [comment]
I'd add this issue is also present with band structure projections. You first have orbital projections and then mx, my, mz spin projections. The spin projection information is not stored for SOC calculations.

**Comment by Nokimann** [comment]
@utf
Did you mean there are sub-class or sub-functions under the object of the orbital projection? Or, I have to construct mx, my, mz spin projections manually?
