### ISSUE TITLE
SpacegroupAnalyzer.get_primitive_standard_structure()'s default symprec value returns a faulty structure for Mg3Sb2

### ISSUE THREAD

**Issue by rees-c** [materialsproject/pymatgen#1543]
**Describe the bug**
When using `SpacegroupAnalyzer.get_primitive_standard_structure()` with the default `symprec=0.01` option on a Mg3Sb2 structure, the structure returned places the Sb atoms on top of the Mg atoms. This issue does not occur when `symprec=0.001` or `symprec=0.1`.

**To Reproduce**
1. Download this file into some directory
[POSCAR-aconvasp_Mg3Sb2.txt](https://github.com/materialsproject/pymatgen/files/3453869/POSCAR-aconvasp_Mg3Sb2.txt)
2. Run the following python code in the same directory:
```python
from pymatgen import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

structure = Structure.from_file('POSCAR-aconvasp_Mg3Sb2.txt')
print('ORIGINAL STRUCTURE')
print(structure)

sga = SpacegroupAnalyzer(structure, symprec=0.01)
structure = sga.get_primitive_standard_structure()
print('NEW STRUCTURE')
print(structure)
```

4. Notice from the printed output that the Sb atoms are placed on top of the Mg atoms in the new structure:
```python
ORIGINAL STRUCTURE
Full Formula (Mg3 Sb2)
Reduced Formula: Mg3Sb2
abc   :   7.280122   4.589982   4.598335
angles:  60.060961  90.000000  90.000000
Sites (5)
  #  SP           a         b         c
---  ----  --------  --------  --------
  0  Mg    0.631749  0.333719  0.332562
  1  Mg    0.368251  0.666281  0.667438
  2  Mg    0         0         0
  3  Sb    0.22557   0.332859  0.332859
  4  Sb    0.77443   0.667141  0.667141
NEW STRUCTURE
Full Formula (Mg3 Sb2)
Reduced Formula: Mg3Sb2
abc   :   4.594160   4.594160   7.280122
angles:  90.000000  90.000000 119.938984
Sites (5)
  #  SP           a         b    c
---  ----  --------  --------  ---
  0  Mg    0.333141  0.666859    0
  1  Mg    0.666859  0.333141    0
  2  Mg    0         0           0
  3  Sb    0.332859  0.667141    0
  4  Sb    0.667141  0.332859    0

```

**Expected behavior**
The original structure is already primitive (it was output from `AFLOW`) so we expected the structure to not change.

**Desktop (please complete the following information):**
 - OS: iOS

**Additional context**
The code was run in PyCharm

**Comment by shyuep** [comment]
Can you report this at https://github.com/atztogo/spglib ? This is basically an issue for spglib to solve.
