### ISSUE TITLE
pymatgen/io/vasp/outputs.py SyntaxError line 4534

### ISSUE THREAD

**Issue by fleischern** [materialsproject/pymatgen#1569]
Installed 2019.7.2 via pip3 and got syntax errors from the WAVEDER and WAVEDERF classes when testing the command line tool. Deleted both classes as I don't see that I need these and it works.

Have python 3.5.0 installed on a cluster runing linux 64 bit CentOS 6.

**Comment by shyuep** [comment]
Ok, I see where the syntax error might be coming from. While I can fix it, I would suggest you move to Py 3.7 and use a newer version of pymatgen. Thanks.
