### ISSUE TITLE
Error when execute pmg analyze .

### ISSUE THREAD

**Issue by lvjian8596** [materialsproject/pymatgen#1578]
**System**
Python version: 3.7.3
OS version: macOS Mojave
monty 1.12.0

**Summary**
I installed the  pymatgen through Conda-based install and in developmental mode as well.

When I was trying the execute "pmg analyze ." in a vasp calculaiton fold.

The following error message appears:

  File "/Users/lvjian/miniconda3/lib/python3.7/site-packages/monty/json.py", line 271, in default
    d = o.as_dict()
AttributeError: 'property' object has no attribute 'as_dict'

...
...

  File "/Users/lvjian/miniconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/lvjian/miniconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
TypeError: Object of type property is not JSON serializable

**Comment by lvjian8596** [comment]
Could any help me to solve this problem?

**Comment by shyuep** [comment]
I just pushed a fix.

**Comment by lvjian8596** [comment]
Thanks for the prompt reply. It works!
