### ISSUE TITLE
pymatgen.io.vasp.outputs.Wavecar fails to read WAVECAR from gamma-only VASP run

### ISSUE THREAD

**Issue by bernstei** [materialsproject/pymatgen#1585]
When reading a WAVECAR that was generated by the gamma-point-only vasp executable, pymatgen.io.vasp.outputs.Wavecar fails with the error:

>   File "/Users/bernstei/Library/Python/3.7/lib/python/site- packages/pymatgen/io/vasp/outputs.py", line 4170, in __init__
    'number of G points {} {}'.format(len(self.Gpoints[ink]), nplane))
ValueError: failed to generate the correct number of G points 891 446

(I added the numbers myself).  The numbers are off by a factor of 2 (+1), suggesting that it's not aware of the "-DNGXhalf -DwNGXhalf" arguments passed for the gamma-only executable, and that's messing up the count.  I don't know if that info is embedded in the WAVECAR, but if not, perhaps it might be necessary to add a "gamma=bool" argument to Wavecar.__init__? The values in the file may well be real rather than complex, as well.

**Comment by shyuep** [comment]
I have no idea whether the gamma info is in the wavecar. But setting that argument seems to be a quick fix for the problem for now. Can you implement and then submit a PR with the requisite unittests pls? Thanks.

**Comment by bernstei** [comment]
> On Sep 10, 2019, at 8:49 AM, Shyue Ping Ong <notifications@github.com> wrote:
> 
> I have no idea whether the gamma info is in the wavecar. But setting that argument seems to be a quick fix for the problem for now. Can you implement and then submit a PR with the requisite unittests pls? Thanks.
> 
> 

I'll see what I can do.

						Noam

____________
||
|U.S. NAVAL|
|_RESEARCH_|
LABORATORY
Noam Bernstein, Ph.D.
Center for Materials Physics and Technology
U.S. Naval Research Laboratory
T +1 202 404 8628  F +1 202 404 7546
https://www.nrl.navy.mil <https://www.nrl.navy.mil/>

**Comment by mkhorton** [comment]
I think there was another issue where this was discussed, I’ll try and find
it...

**Comment by bernstei** [comment]
I've worked out what needs to be done, although it's going to be a while before I would be able to release it.  It required replicating the VASP logic for which plane waves to skip, and then reconstructing the missing complex conjugate coefficients.

**Comment by shyuep** [comment]
Thanks @bernstei. Didn't realize it was so complicated!!!

**Comment by mkhorton** [comment]
Ah, the previous issue I was thinking about was actually in relation to the Waveder class (pasted here for interest https://github.com/materialsproject/pymatgen/issues/1442), which might have similar issues.

**Comment by bernstei** [comment]
From what I can tell, the only way to check is to look for mismatching numbers of plane waves (which is what the current code, and also WaveTrans, do), which isn't exactly feel like good practice, but it does seem to be the only way it can happen.  My current code needs a "gamma" flag, but I suppose one could actually switch to assuming that it's gamma-only if the number of PW doesn't match.

**Comment by mturiansky** [comment]
I wrote the original implementation for pymatgen.io.vasp.outputs.Wavecar based on WaveTrans. There's no flag or any information in the WAVECAR that will tell you whether it's gamma only or a normal one. Putting the option as an input argument is the best option (in my opinion) because this is essentially what you do with VASP (you compile a separate binary for gamma only and the WAVECAR's from gamma only and normal are not cross compatible). Also, this leaves the check for the number of PW's in tact.

Let me know if you have any questions or need any help with adding the gamma-only code.

**Comment by bernstei** [comment]
Thanks. I think I have working code, but can someone point me at an example of a unit test, so I can develop one for this feature?

						thanks,
						Noam

**Comment by mturiansky** [comment]
[here](https://github.com/materialsproject/pymatgen/blob/bcd76b3e5e09983de52eb930799a192ef221db6a/pymatgen/io/vasp/tests/test_outputs.py#L1255-L141) are the unittests that I wrote for the Wavecar class.

**Comment by bernstei** [comment]
> On Sep 11, 2019, at 2:18 PM, Mark Turiansky <notifications@github.com> wrote:
> 
> here <https://github.com/materialsproject/pymatgen/blob/bcd76b3e5e09983de52eb930799a192ef221db6a/pymatgen/io/vasp/tests/test_outputs.py#L1255-L141> are the unittests that I wrote for the Wavecar class.
> 
> 

Thanks.  A couple of related questions.  Does the unit test actually test the contents (PW coefficients and/or values of WF in real space) of the Wavecar object, or just its metadata?  I only see the latter.  Second, where does WAVECAR.N2 come from?  Is that distributed in the pymatgen  git repo, or does the test somehow cause it to be calculated on the fly?

									Noam

**Comment by bernstei** [comment]
> On Sep 11, 2019, at 2:33 PM, Noam Bernstein <noam.bernstein@nrl.navy.mil> wrote:
> 
> Thanks.  A couple of related questions.  Does the unit test actually test the contents (PW coefficients and/or values of WF in real space) of the Wavecar object, or just its metadata?  I only see the latter.

Never mind, I see the relevant tests.

>  Second, where does WAVECAR.N2 come from?  Is that distributed in the pymatgen  git repo, or does the test somehow cause it to be calculated on the fly?

This I still need to understand, to generate a gamma-only run WAVECAR.

							Noam

**Comment by mkhorton** [comment]
Yes, the WAVECAR.N2 lives in the test_files directory: https://github.com/materialsproject/pymatgen/blob/master/test_files/WAVECAR.N2

So the gamma-only WAVECAR would have to be added there also. Since git doesn't really like large files, the smallest sensible representative WAVECAR is definitely preferred.

**Comment by bernstei** [comment]
> On Sep 11, 2019, at 3:00 PM, Matthew Horton <notifications@github.com> wrote:
> 
> Yes, the WAVECAR.N2 lives in the test_files directory: https://github.com/materialsproject/pymatgen/blob/master/test_files/WAVECAR.N2 <https://github.com/materialsproject/pymatgen/blob/master/test_files/WAVECAR.N2>
> So the gamma-only WAVECAR would have to be added there also. Since git doesn't really like large files, the smallest sensible representative WAVECAR is definitely preferred.
> 
> 

I don’t suppose I could get whomever contributed the WAVECAR.N2 file to run a gamma-only calculation with exactly the same parameters and add it?  Then my test could just compare it to the non-gamma-only run.

										Noam

**Comment by shyuep** [comment]
@bernstei You can just run a very small calculation using gamma point only. The calculation does not have to be good. We are only making sure of parsing. E.g., just take the primitive cell of Li and run with gamma point to get WAVECAR. You don't even need to run it on a queue. It will be done in < 1 min.

**Comment by bernstei** [comment]
> On Sep 11, 2019, at 3:23 PM, Shyue Ping Ong <notifications@github.com> wrote:
> @bernstei <https://github.com/bernstei> You can just run a very small calculation using gamma point only. The calculation does not have to be good. We are only making sure of parsing. E.g., just take the primitive cell of Li and run with gamma point to get WAVECAR. You don't even need to run it on a queue. It will be done in < 1 min.
> 

True, but the easiest way to check is to compare to a non-gamma calculation of the same thing, and if I can’t re-use the existing WAVECAR.N2, I’ll have to upload two WAVECARs.  I can do that, but it’s more stuff in your repo.

									Noam

**Comment by bernstei** [comment]
Also, are the any instructions for how to run the unit tests, ideally just the vasp io ones?

						Noam

**Comment by shyuep** [comment]
Committing two small files is fine.
To run unittests, just type pytest test_outputs.py

**Comment by bernstei** [comment]
> On Sep 11, 2019, at 3:33 PM, Shyue Ping Ong <notifications@github.com> wrote:
> 
> Committing two small files is fine.
> To run unittests, just type pytest test_outputs.py
> 
> 
It’s failing with:
> cd pymatgen/io/vasp/tests
> pytest test_outputs.py 

===================================================================================================== ERRORS ======================================================================================================
_____________________________________________________________________________ ERROR collecting pymatgen/io/vasp/tests/test_outputs.py _____________________________________________________________________________
ImportError while importing test module '/Volumes/bernstei/src/work/pymatgen/pymatgen/pymatgen/io/vasp/tests/test_outputs.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../__init__.py:40: in <module>
    from pymatgen.core import *
../../../core/__init__.py:8: in <module>
    from .structure import Structure, IStructure, Molecule, IMolecule
../../../core/structure.py:25: in <module>
    from pymatgen.core.lattice import Lattice
../../../core/lattice.py:22: in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
../../../util/coord.py:9: in <module>
    from . import coord_cython as cuc
E   ImportError: cannot import name 'coord_cython'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I did "setup.py build” in the top level directory, but that didn’t help.  

									Noam

**Comment by shyuep** [comment]
THink you need to run python setup.py develop. Build is not gong to install the compiled cython code.

**Comment by mturiansky** [comment]
As they have said, I just generated the WAVECAR.N2 with horrendously low convergence parameters (ENCUT of 25 eV, 1 kpoint, 10 Angstrom cube cell with a N2 molecule in the center, just a single-shot calculation).

In my unittests, I really just check the metadata. It's not so practical to check the actual wavefunctions and coefficients. The best check in the end is to use the "get_parchg" function and look at the charge density using your favorite viewing software to make sure the charge density looks correct.

**Comment by bernstei** [comment]
Months later, I finally have patches available to make reading gamma-point only wavefunctions possible.  I'd be happy to do a pull request, but do I need some sort of permission first?

**Comment by mkhorton** [comment]
No permission required to open a pull request, thanks very much for taking the time to patch!

**Comment by bernstei** [comment]
OK - I created a pull request, but something's still broken, so please ignore it for now.  I'll try to link it to this issue once it's actually ready.

**Comment by mkhorton** [comment]
Great! You can put “[WIP]” (work in progress) in your PR title and remove it when you feel like it’s ready to merge

**Comment by bernstei** [comment]
OK, I created pull request 1781 [https://github.com/materialsproject/pymatgen/pull/1781], but I haven't quite figured out whether it's ready.  It seems to be failing the travis-ci step, but I see no sign that anything I modified is a problem.
