### ISSUE TITLE
Error report when using module of pymatgen_diffusion.neb.pathfinder 

### ISSUE THREAD

**Issue by ws517037749** [materialsproject/pymatgen#1588]
**Describe the bug**
when I try to use function of FullPathMapper.get_unique_hops_dict() the 'KeyError: 'hop'' appear, but other functions work well.

**Expected behavior**
Fix the bug

**Screenshots**
![image](https://user-images.githubusercontent.com/43861983/64659820-a6d1b200-d40b-11e9-8fdc-02acca3afa59.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Red Hat Enterprise Linux Server release 6.10 (Santiago)]
 - Browser [e.g. Chrome]
 - Version [e.g. 6.10]

**Comment by mkhorton** [comment]
@jmmshn ?

**Comment by jmmshn** [comment]
Sorry, there should have been an example of how to us the FullPathMapper.
I have created a PR to fix this.

**Comment by jmmshn** [comment]
@ws517037749 the following file should have an example.
https://github.com/materialsvirtuallab/pymatgen-diffusion/blob/master/examples/neb_path_mapping.ipynb
The file not rendering on github for me right now but if you download the file it should work.
