### ISSUE TITLE
Inconsistent Structure.get_distance and Lattice.get_distance methods.

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#1592]
Recently, @chc273 implemented a much better distance computation algo that scales linearly with # of atoms Structure.get_neighbors. But some of the other methods seem to still use Lattice.get_points_in_sphere.

I would like to unify all these treatments. Basically port the general concept of get_neighbors to Lattice.get_points_in_sphere and then have all relevant methods just call that. This is reduce code duplication and ensure we have one consistent algo.

@chc273 can do the honors?

**Comment by chc273** [comment]
@shyuep ok
