### ISSUE TITLE
Spin down projection does not work

### ISSUE THREAD

**Issue by nicodemosvarnava** [materialsproject/pymatgen#1600]
**Describe the bug**
When I try to get the projection on elements and orbitals for my bands
the spin down case does not work.
i.e.
Mn_bands = bands.get_projections_on_elements_and_orbitals({"Mn": ["s", "p","d"]})
print(Mn_bands[Spin.down][n_b][n_k]["Mn"]["s"])
I get the error:
KeyError: <Spin.down: -1>
When I replace Spin.down with Spin.up I don't get errors
**To Reproduce**
Mn_bands = bands.get_projections_on_elements_and_orbitals({"Mn": ["s", "p","d"]})
print(Mn_bands[Spin.up][n_b][n_k]["Mn"]["s"])

**Desktop (please complete the following information):**
 - OS: Mac
 - Version [e.g. 10.14.6]

**Comment by shyuep** [comment]
This implies you do not have a spin down DOS. Is your run spin polarized?

**Comment by nicodemosvarnava** [comment]
Shyuep,

The calculation is spin polarized but with spin-orbit coupling 
so the spin up/down channels are not well defined anymore.


Now

**Comment by mkhorton** [comment]
We would need the relevant file to be able to investigate this.

What do you get if you print `print(Mn_bands.keys())`?

**Comment by shyuep** [comment]
Hmmm... yes, that is paradoxical. 

The most helpful thing would be to generalize the DOS and BS objects to support SOC calculations as well as non-SOC>
