### ISSUE TITLE
Adding New Version to Conda

### ISSUE THREAD

**Issue by WardLT** [materialsproject/pymatgen#1602]
**Is your feature request related to a problem? Please describe.**
Yes, the current version of matminer requires a version of pymatgen that is newer than the one on Anaconda. Without the Anaconda version, installing matminer becomes pretty tricky for Windows users. 

**Describe the solution you'd like**
Updating the Anaconda version more frequently. I'm not sure if it would make sense to sync it with the PyPi build, but that would be wonderful.

**Describe alternatives you've considered**
Waiting until the version is updated. What's the release schedule? At least that way I can know when to expect installation problems with matminer users.

**Comment by shyuep** [comment]
If you are using the Matsci channel, try changing to conda-forge.  We are deprecating the matsci channel. That should be the latest version.

**Comment by WardLT** [comment]
Yes, I was using the "matsci" channel. Good to know about it being deprecated, I'll advise people to avoid it

**Comment by shyuep** [comment]
Thanks. I have also updated all docs to note that the conda-forge version is now the official one.
