### ISSUE TITLE
Pymatgen error

### ISSUE THREAD

**Issue by RinuKulkarni** [materialsproject/pymatgen#1604]
Suddenly, pymatgen stopped working with this error. May, I know the reason behind this error
*ImportError: No module named pymatgen.ext.matproj

**Comment by shyuep** [comment]
You will have to give more details than that. It is impossible for us to know what happened based on that one liner description. There is a template for reporting Issues.

**Comment by RinuKulkarni** [comment]
I am trying to use this script to generate the input files for the  
defect physics. Till yesterday, it was working fine but suddenly it's  
showing the following error.

Traceback (most recent call last):
   File "setup2.py", line 4, in <module>
     from pymatgen.ext.matproj import MPRester
ImportError: No module named pymatgen.ext.matproj

I don't understand why it's happening.

your support will be helpful,
Ramya


Quoting Shyue Ping Ong <notifications@github.com>:

**Comment by shyuep** [comment]
It is unclear what script this is. And as far as I know, it should work. I can only conclude that someone uninstalled your pymatgen. Pls reinstall and try again.

**Comment by LBipin** [comment]
I completely installed pymatgen but when I run python program it always shows "module 'pymatgen' has no attribute 'Structure'" error. Since I can see structure.py in anaconda3/lib/python3.8/site-packages/pymatgen/core/structure.py

**Comment by shyuep** [comment]
Pymatgen's structure object is now in pymatgen.core. Do `from pymatgen.core import Structure`.
