### ISSUE TITLE
Custom options in Bader Charge Analysis

### ISSUE THREAD

**Issue by Nokimann** [materialsproject/pymatgen#1609]
I'm not sure Pymatgen deals with other custom options, e.g., -b neargrid | ongrid | weight.
When I check, only parse_atomic_densities=True is available, or I missed.

So can we parse the custom options by the variables, or manually changing the source code?

The double star (** keywords)  at the end of any function or class might hope to this feature.

**Comment by mkhorton** [comment]
Hi @Nokimann, I just noticed this myself recently. I opened a PR to add "vacuum mode" but didn't look at the other options. You'd be welcome to pick this up and add them if you'd like: https://github.com/materialsproject/pymatgen/pull/1597

**Comment by Nokimann** [comment]
@mkhorton Nice notification. So, we have to modify it in our own ways.

**Comment by mkhorton** [comment]
We can leave this issue open, we should add these features to the Bader caller. My point was that you would be welcome to add these features and submit the patch (PR) yourself if it's an urgent concern.
