### ISSUE TITLE
Trouble with linear_add of VolumetricData object

### ISSUE THREAD

**Issue by Nokimann** [materialsproject/pymatgen#1615]
When I tried to use `__add__` or `__sub__` functions of `VolumetricData` object, it raised an error by
```
ValueError("Adding or subtraction operations can only be "
           "performed for volumetric data with the exact "
           "same structure.")
```
In some cases of subtraction from AB system to separated A and B systems in order to see the change of charge density, we need to use something like functions above. But these AB, A, and B are totally different systems (or structure) that conflict with `self.structure != other.structure` conditions.

It would be better to compare the dimension of grid, axis grid or other information.

But if they have different dimensions, I expect that numpy array automatically causes an error.

**Comment by shyuep** [comment]
Thanks for reporting this. I have pushed a fix that raises a warning instead of an error for different structures, but will throw an error if you try to sum spin and non-spin data, or that the dims of the data itself are different (numpy does that).
