### ISSUE TITLE
Symmetrized structure json serialization

### ISSUE THREAD

**Issue by fermionian** [materialsproject/pymatgen#1629]
**Describe the bug**
symmetrized structure cannot be dumped and loaded
Thanks for fixing https://github.com/materialsproject/pymatgen/commit/2131e3e95477995947b43864ef9fda2294b2a6dc

This is a follow-up question.

**To Reproduce**
```
sym = SpacegroupAnalyzer(s).get_symmetrized_structure()
sym.copy() # now works

with open(f't.json', 'w') as f:
    json.dump(sym, f, cls=MontyEncoder)

with open(f't.json') as f:
    sym = json.load(f, cls=MontyDecoder)

```

Still throws

> TypeError: __init__() got an unexpected keyword argument 'charge'

**Comment by shyuep** [comment]
Thanks. This should be fixed.
