### ISSUE TITLE
Poscar doesn't sort structure causing bad POSCARs

### ISSUE THREAD

**Issue by shyamd** [materialsproject/pymatgen#1633]
**Describe the bug**
The `Poscar` class doesn't appear to sort structure and there is no expectation in the standard structure class to sort the sites by elements. The result is more complex classes such as Slab can be generated with atoms grouped together by the original structure. This leads to unwieldy Poscar's that can even be truncated when read in. This also leads to huge POTCARs due to the non-sequential repeat. 

**Expected Behavior**
The issue is due to conflicting prescriptions of order. `Poscar` is written assuming preordered structures. But the current structures are not enforcing order. My intuition is that Poscar should reorder the structure by default to make reasonable input files. This can cause problems for anyone expecting the site indicies to stay the same. This might be mitigated by making this a flag in `Poscar`? The other option is to enforce ordering atoms in `Slab` and any other complex structures. I don't see any problems with this, but this site ordering issue is AFAIK unique to VASP. 

**Example code**
```
from pymatgen.util.testing import PymatgenTest
from pymatgen.core.surface import SlabGenerator
from pymatgen.io.vasp.inputs import Poscar

sio2 = PymatgenTest.get_structure("SiO2")
slabgen = SlabGenerator(sio2,miller_index=(1,1,0),min_slab_size=5,min_vacuum_size=3,in_unit_planes=True)
poscar = Poscar(slabgen.get_slab(0))
print(poscar)
```

Output:
```
Si15 O30
1.0
5.518918 0.000000 0.000000
-0.000000 4.354187 7.541673
0.000000 0.000000 40.222254
Si O Si O Si O Si O Si O
3 6 3 6 3 6 3 6 3 6
direct
0.000010 0.522709 0.119322 Si
0.333344 0.477288 0.065339 Si
0.666677 0.000003 0.065338 Si
0.129333 0.584963 0.071972 O
0.462667 0.160740 0.011695 O
0.796000 0.254296 0.041333 O
0.870690 0.839261 0.071972 O
0.537356 0.745704 0.011695 O
0.204023 0.415036 0.041334 O
0.000010 0.522709 0.244322 Si
0.333344 0.477288 0.190339 Si
0.666677 0.000003 0.190338 Si
0.129333 0.584963 0.196972 O
0.462667 0.160740 0.136695 O
0.796000 0.254296 0.166333 O
0.870690 0.839261 0.196972 O
0.537356 0.745704 0.136695 O
0.204023 0.415036 0.166334 O
0.000010 0.522709 0.369322 Si
0.333344 0.477288 0.315339 Si
0.666677 0.000003 0.315338 Si
0.129333 0.584963 0.321972 O
0.462667 0.160740 0.261695 O
0.796000 0.254296 0.291333 O
0.870690 0.839261 0.321972 O
0.537356 0.745704 0.261695 O
0.204023 0.415036 0.291334 O
0.000010 0.522709 0.494322 Si
0.333344 0.477288 0.440339 Si
0.666677 0.000003 0.440338 Si
0.129333 0.584963 0.446972 O
0.462667 0.160740 0.386695 O
0.796000 0.254296 0.416333 O
0.870690 0.839261 0.446972 O
0.537356 0.745704 0.386695 O
0.204023 0.415036 0.416334 O
0.000010 0.522709 0.619322 Si
0.333344 0.477288 0.565339 Si
0.666677 0.000003 0.565338 Si
0.129333 0.584963 0.571972 O
0.462667 0.160740 0.511695 O
0.796000 0.254296 0.541333 O
0.870690 0.839261 0.571972 O
0.537356 0.745704 0.511695 O
0.204023 0.415036 0.541334 O
```

**Comment by shyuep** [comment]
You are certainly welcome to add an option `sort_structure` to the Poscar class. But the default behavior has to be that the Poscar class simply generates the input *in the order that the user supplies it*. There are a lot of use cases where this is important. E.g., when doing NEB, I need a 1-1 mapping of start and end point positions. In some cases, the so called bad arrange that you show might actually be the desired arrangement, e.g., if I have multiple types of the same species and I need to apply some tricks, e.g., setting different U values for Fe2+ and Fe3+ in Fe3O4. 

The rule is always - the user knows what he is doing. So he should have done the sorting using Structure.get_sorted_structure if that is what he wants.

**Comment by mkhorton** [comment]
If there is a max line length from VASP, we should check for that when writing the POSCAR: if we know it will cause a bug because the full line isn't read by VASP then we should raise an error.

**Comment by shyamd** [comment]
Ok, I see the uses cases. I'll try and add some documentation so that this is clear.
