### ISSUE TITLE
Changing the VoronoiNN default tolerance value

### ISSUE THREAD

**Issue by utf** [materialsproject/pymatgen#1638]
I'm working on a package to benchmark the performance of the NearNeighbor classes in pymatgen by comparing predicted coordination numbers against human determined coordination numbers (taken from the literature).

The performance of VoronoiNN can be tuned through a parameter, `tol`. Voronoi faces that are smaller than `tol` fraction of the largest face are not included in the tessellation. 

In our benchmark, we've been using VoronoiNN with a default `tol` value of 0.5. This gives very close to optimal results as shown by the plot below.

The default value of `tol` in pymatgen is 0, which as you can see is highly unoptimized. Is there any reason for this? If not, would you be against changing the default to 0.4/0.5?

![VoronoiNN-tolerance-tuning](https://user-images.githubusercontent.com/1330638/67055338-94c6eb80-f0fc-11e9-989d-1b82cfb55c7a.png)

*Plot shows benchmark score (lower is better) computed using VoronoiNN with different tolerances.*

**Comment by mkhorton** [comment]
Have you seen this?

https://github.com/materialsproject/pymatgen/blob/b7588712eb6f37ef2ff5cfa47667e2df33e8c11d/pymatgen/analysis/local_env.py#L1001 

I'm on-board with changing the default, I'm not sure why it wasn't done previously. I'm sure you're already aware there are other NNs that rely on Voronoi though and assume a tolerance of 0 that may need to be updated to keep tol=0 in those cases, e.g. see:

https://github.com/materialsproject/pymatgen/blob/b7588712eb6f37ef2ff5cfa47667e2df33e8c11d/pymatgen/analysis/local_env.py#L3335

**Comment by mkhorton** [comment]
The Voronoi tessellation has also been unstable in some cases too. I'm not sure we need so many NN strategies really, but maybe they're useful somewhere. I think Voronoi may be used in some other places too (defects, chemenv?) though I'm not sure if they use the NN class directly.

**Comment by utf** [comment]
Yep, I'm aware of `VoronoiNN_modified`. Although, it has been deprecated for some time now, so perhaps it should just be removed entirely.

That's a good point about other classes that rely on VoronoiNN though, those would have to be updated.

**Comment by mkhorton** [comment]
Yeah let's just remove the modified one, it doesn't have a deprecated date set and it's not used elsewhere so may as well remove it now.

**Comment by mkhorton** [comment]
Closed with https://github.com/materialsproject/pymatgen/commit/e79d2806b2f9696fcc31069d2ccf400b3c371901
