### ISSUE TITLE
an adsorbatesitefinder bug

### ISSUE THREAD

**Issue by finthon** [materialsproject/pymatgen#1643]
**Describe the bug**
i use generate_all_slabs to cleave surface Au with max_index=1, then i found when min_vacuum_size=15, got 5 sites, min_vacuum_size=10, got 4 sites. other parameters fix.

**To Reproduce**
code as shown:
struct = Structure.from_file(r"./bulk_library/Au_POSCAR")
struct = SpacegroupAnalyzer(struct).get_conventional_standard_structure()
slabs = generate_all_slabs(struct, max_index=1, min_slab_size=8.0, min_vacuum_size=15.0)
for n, slabs in enumerate([slab for slab in slabs if slab.miller_index == (1, 1, 1)]):
    slabs_bak = slabs.copy()
    slabs.make_supercell([[3, 0, 0],
                          [0, 3, 0],
                          [0, 0, 1]])
    fig = plt.figure()
    ax = fig.add_subplot(111)
    plot_slab(slabs, ax, adsorption_sites=True)
    asf = AdsorbateSiteFinder(slabs)
    n_site = asf.find_adsorption_sites()
    print(slabs.miller_index)
    print(n_site)
    print(len(n_site['all']))
    plt.savefig(str(n) + '-Au-111.png', img_format='png')

Provide any example files that are needed to reproduce the error, 
especially if the bug pertains to parsing of a file.

**Expected behavior**
generally, there are 4 different sites in Au(111)

**Screenshots**
![0-Au-111](https://user-images.githubusercontent.com/17920490/67372410-6d669780-f5b0-11e9-9140-acf538c06b4d.png)
![0-Au-111-1](https://user-images.githubusercontent.com/17920490/67372411-6dff2e00-f5b0-11e9-8688-846a92815a0c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2019.10.16

**annex:**
[Au_POSCAR.zip](https://github.com/materialsproject/pymatgen/files/3760995/Au_POSCAR.zip)

**Comment by montoyjh** [comment]
Thanks for the detailed bug report.  Will check on this today.

**Comment by mkhorton** [comment]
Tagging @oxana-a and @mhsiron since this bug might affect their work.

**Comment by JosephMontoya-TRI** [comment]
So this only seems to happen when finding adsorption sites on a supercell, I suspect it's not testing all of the translational equivalencies.

**Comment by JosephMontoya-TRI** [comment]
In general, we should encourage the adsorption analysis using the minimal cell (i. e. with `AdsorptionSiteFinder.generate_adsorption_structures` and it's `repeat` kwarg because it'll be more computationally efficient, but I think we can refactor to ensure that it'll work otherwise.

**Comment by JosephMontoya-TRI** [comment]
Just a quick update, I've tried refactoring to use spglib to determine symmetrically equivalent sites of adsorption structures, rather than doing so manually, and the issue persists.

**Comment by MrLonelyZC88** [comment]
Some high-throughput related work may be affected
