### ISSUE TITLE
installation improvement

### ISSUE THREAD

**Issue by danpho** [materialsproject/pymatgen#1662]
**Is your feature request related to a problem? Please describe.**
First, I have to admit that I just start using Python although it is popular. I noticed that my colleagues had similar experience although they have used python for a long while. The configuration is still a headache work.

It looks to take forever to install pymatgen using "conda" because cond always find all kinds of conflicts and looks for incompatible package although I installed a new conda. I had to use pip to install it. However, I could not quickly figure out the environment settings for conda and/or python. So, I am able to "import pymargen", however I could not import structure, etc. sub-modules.

I tried to modified numy*.json for pymatgen. I failed.

**Describe the solution you'd like**
Is that possible to provide a setting program (like bash scripts) which can be used to merge settings/environment for pymatgen into conda's enviroment. So, we can run python scripts like, "from pymatgen import Structure, ...."

**Describe alternatives you've considered**
Provide us a instruction to show how to configure the environment for pymatgen in conda environment.

**Additional context**

**Comment by shyuep** [comment]
It is rare that I have heard anyone complain about ease of installation with conda. As far as I know, after installing miniconda on your system, a series of commands such as

```
conda create -n pmg_env python
conda activate pmg_env
conda install -c conda-forge pymatgen
```

should work just fine and you can subsequently just call python and type `from pymatgen import Structure`. These instructions are pretty clear in the pymatgen.org documentation page itself.

If this does not work, you need to provide context - what is your OS (and version)? What conda version are you using?

**Comment by danpho** [comment]
Dear Shyue Ping Ong,


Thank you so much! Please forgive my ignorance. I simply followed the instruction on the website and only input “conda install -c conda-forge pymatgen”. Thus, it took me forever to install it. In another word, is it possible for beginner to update the instruction on the website. I sincerely appreciate your effort and time.

Following your instruction, I successfully installed pymatgen using conda.


Appreciatively,
Leon

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
