### ISSUE TITLE
involve solid state hydroxide in pourbaix diagram

### ISSUE THREAD

**Issue by yuxin-chang** [materialsproject/pymatgen#1682]
**Describe the bug**
I tried to draw  Fe-H2O pourbaix diagram, using pymatgen.analysis.pourbaix_diagram module. Comparing with the experimental pb diagram (they should match mostly), there should be Fe(OH)2 in the diagram, but the given diagram does not have Fe(OH)2.
**To Reproduce**
`entries = mpr.get_pourbaix_entries(["Fe"])`
`pbx = PourbaixDiagram(entries)`
`plotter = PourbaixPlotter(pbx)`
`plotter.get_pourbaix_plot().show()`
**Expected behavior**
from wikipedia
![image](https://upload.wikimedia.org/wikipedia/commons/8/85/Pourbaix_Diagram_of_Iron.svg)
**Screenshots**
code output:
![untitled](https://user-images.githubusercontent.com/46608307/69491939-0156a800-0e6a-11ea-9bca-da5367381046.png)

**Comment by JosephMontoya-TRI** [comment]
Hi yuxin-chang,

As far as I can tell, this isn't a bug in pymatgen's pourbaix solving/plotting routine, it's an issue with the MP data and corrections for Fe(OH)2.
