### ISSUE TITLE
Procar can not read in PROCAR with SOC effect?

### ISSUE THREAD

**Issue by zrqustc** [materialsproject/pymatgen#1686]
**Describe the bug**
Procar(filename="PROCAR")
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-220-d410e4cba7b4> in <module>
----> 1 Procar(filename="/Users/zhangruiqi/Work//band/PROCAR")

~/.local/lib/python3.6/site-packages/pymatgen/io/vasp/outputs.py in __init__(self, filename)
   3319                             for orb in range(len(headers)):
   3320                                 phase_factors[spin][current_kpoint, current_band,
-> 3321                                                     index, orb] = complex(num_data[2 * orb], num_data[2 * orb + 1])
   3322                         else:
   3323                             # old format of PROCAR (vasp 5.4.1 and before)

IndexError: index 17 is out of bounds for axis 0 with size 17

**Screenshots**

**Desktop (please complete the following information):**
 - OS:Mac,
 - Version [2018.9.30]

**Comment by Cloudiiink** [comment]
I have met the same bug today. I think this bug comes from the judgment statement used to judge the VASP version. In VASP 5.4.1 and before, the `toks` line and `header` line have the same length. 

PROCAR (VASP 5.4.1) look like this
```
band   1 # energy   -6.07967625 # occ.  1.00000000
 
ion      s     py     pz     px    dxy    dyz    dz2    dxz    dx2    tot    <--- header line
  1  0.028  0.000  0.000  0.001  0.000  0.000  0.000  0.000  0.000  0.029    <--- toks line
  2  0.028  0.000  0.000  0.001  0.000  0.000  0.000  0.000  0.000  0.029
```

Pymatgen code pops the `ion` and `tot` in `header`.
```
elif headers is None and ionexpr.match(l):
    headers = l.split()
    headers.pop(0)
    headers.pop(-1)
```
But it only pops the ion number in `toks` line.
```
elif expr.match(l):
    toks = l.split()
    index = int(toks.pop(0)) - 1    # Add toks.pop(-1) after this line
    num_data = np.array([float(t) for t in toks[:len(headers)]])
```
After adding `toks.pop(-1)`, I successfully create a `Procar` instance.

**Comment by shyuep** [comment]
Thanks. Can one of you make the changes in code to handle the PROCARs for different versions of vasp? This should be a simple if-else thing. Then add a example PROCAR and unittests and submit a PR and I will merge. Thanks.
