### ISSUE TITLE
pymatgen.analysis.gb.grain.py generates strange structures with normal=True

### ISSUE THREAD

**Issue by nishiyamat** [materialsproject/pymatgen#1693]
**Describe the bug**
`pymatgen.analysis.gb.grain.gb_from_parameters()` generates a $\Sigma 5 <001>$ tilt boundary of fcc whose top_grain has a large minus deviation in the b-axis when `normal=True`.

**To Reproduce**

Run followings and open the generated file `Cu_GB4.cif`.

```python
from pymatgen import Structure
from pymatgen.analysis.gb.grain import GrainBoundary, GrainBoundaryGenerator

Cu_conv = Structure.from_file("Cu_mp-30_conventional_standard.cif")
GB_Cu_conv = GrainBoundaryGenerator(Cu_conv)

Cu_GB4 = GB_Cu_conv.gb_from_parameters(
    rotation_axis= [0,1,0],
    rotation_angle=36.8698976458,
    expand_times= 4,
    vacuum_thickness= 1.0,
    ab_shift= [0.0,0.0],
    rm_ratio= 0.0,
    plane=[0,0,1],
    normal=True
)

Cu_GB4.to("cif",filename="Cu_GB4.cif")
```

"Cu_mp-30_conventional_standard.cif" is
<https://github.com/materialsproject/pymatgen/blob/master/test_files/grain_boundary/Cu_mp-30_conventional_standard.cif>.

**Screenshots**

![image](https://user-images.githubusercontent.com/49854960/70012497-e39ae880-15b7-11ea-9ed6-3b4c051209eb.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Version 2019.11.11

**Additional context**

The lines 635--639 of pymatgen.analysis.gb.grain.py may cause this anomaly.
```python
        for site in top_grain:
            all_coords.append(site.coords + half_lattice.matrix[2] * (1 + c_adjust) +
!!!                              unit_ab_adjust * np.linalg.norm(half_lattice.matrix[2] * (1 + c_adjust)) +
                              translation_v + ab_shift[0] * whole_matrix_with_vac[0] +
                              ab_shift[1] * whole_matrix_with_vac[1])
```
These lines append `all_coords[400:]` of top_grain with large minus values in the above parameter settings.

I'm not sure about the algorithm to generate these coordinates, so let me know the reference of this part.

**Comment by ucsdlxg** [comment]
The structure generated itself should be correct. Using the periodic boundary condition, you can move the top grain to match with the bottom grain. In other words, the large minus values in direct coordinates can be added up to (0,1) using the periodic boundary condition. The vesta software can do this automatically. Of course, we can add a line code at the final step to make sure all the direct coordinates are within (0, 1). This part is straight forward.

**Comment by nishiyamat** [comment]
Thank you for your reply. I created the above pull request according to your suggestion.
