### ISSUE TITLE
"pymatgen.io.lammps.data" Can't write file

### ISSUE THREAD

**Issue by swanboiled** [materialsproject/pymatgen#1694]
**Describe the bug**
I want to convert a ".cif" file to lammps coordination data but found
"pymatgen.io.lammps.data" Can't write lammps data file with the following error:
"FileNotFoundError: [Errno 2] No such file or directory: '/home/myuser/.conda/envs/pmg/lib/python3.6/site-packages/pymatgen/io/lammps/CoeffsDataType.yaml'"

**To Reproduce**
The cif file I was using:
*************
data_H2CO
_symmetry_space_group_name_H-M   'P 1'
_cell_length_a   2.57520631
_cell_length_b   4.92688007
_cell_length_c   10.72047831
_cell_angle_alpha   90.00000000
_cell_angle_beta   90.00000000
_cell_angle_gamma   90.00000000
_symmetry_Int_Tables_number   1
_chemical_formula_structural   H2CO
_chemical_formula_sum   'H8 C4 O4'
_cell_volume   136.01856262
_cell_formula_units_Z   4
loop_
 _symmetry_equiv_pos_site_id
 _symmetry_equiv_pos_as_xyz
  1  'x, y, z'
loop_
 _atom_site_type_symbol
 _atom_site_label
 _atom_site_symmetry_multiplicity
 _atom_site_fract_x
 _atom_site_fract_y
 _atom_site_fract_z
 _atom_site_occupancy
  H  H0  1  0.613030  0.756578  0.148355  1.0
  H  H1  1  0.973662  0.576934  0.231306  1.0
  H  H2  1  0.386970  0.256578  0.351645  1.0
  H  H3  1  0.026338  0.076934  0.268694  1.0
  H  H4  1  0.113030  0.743422  0.851645  1.0
  H  H5  1  0.473662  0.923066  0.768694  1.0
  H  H6  1  0.886970  0.243422  0.648355  1.0
  H  H7  1  0.526338  0.423066  0.731306  1.0
  C  C8  1  0.194567  0.250018  0.000094  1.0
  C  C9  1  0.805433  0.750018  0.499906  1.0
  C  C10  1  0.694567  0.249982  0.999906  1.0
  C  C11  1  0.305433  0.749982  0.500094  1.0
  O  O12  1  0.972683  0.749006  0.182615  1.0
  O  O13  1  0.027317  0.249006  0.317385  1.0
  O  O14  1  0.472683  0.750994  0.817385  1.0
  O  O15  1  0.527317  0.250994  0.682615  1.0
*************

The code:

************
import pymatgen.core.structure as structure
import pymatgen.io.lammps.data as ld
in_stru = structure.Structure.from_file('mp.cif')
ldata = ld.LammpsData.from_structure(in_stru,atom_style = 'full')
print(ldata.structure)
ldata.write_file('new',distance=6, velocity=8, charge=4)
************

**Expected behavior*
I want to see the lammps file

**Screenshots**

![image](https://user-images.githubusercontent.com/17527300/70052979-71ee8900-160f-11ea-8e0e-a48e77b2eddb.png)

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Version [2019.11.11]

**Comment by shyuep** [comment]
Pls install the 2019.12.3 version. I just fixed this.
