### ISSUE TITLE
scripts directory of pymatgen

### ISSUE THREAD

**Issue by JabinHao** [materialsproject/pymatgen#1697]
**Describe the bug**
I cannot find the scripts directory of pymatgen’s github repo. It seems that in the new version you have built them in the "pmg", but i want to see the code of these scripts such as gen_potcar.py、vasp_example.py .etc. where can i find them

**Comment by mkhorton** [comment]
Hi @JabinHao, the scripts are defined via the `entry_points` of `setup.py`, see https://github.com/materialsproject/pymatgen/blob/c9b3385ad6ff06f0f1b26c4a6509b977b63be6e6/setup.py#L182 

Most of them are defined in `pymatgen.cli.pmg`.

Note that this is not an appropriate use of the Issues page, this is intended for bug reports or feature requests only. If you want help, please post in our [User Forum](https://discuss.matsci.org/c/pymatgen).
