### ISSUE TITLE
Illegal Instruction when importing find_points_in_spheres

### ISSUE THREAD

**Issue by gmfricke** [materialsproject/pymatgen#1703]
An illegal instruction occurs when importing find_points_in_spheres from pymatgen.optimization.neighbors. The code was built with anaconda 5.2.0.

To reproduce:

$ conda create -n test_pymatgen -c conda-forge pymatgen
$ conda  activate test_pymatgen
(test_pymatgen) $ python
Python 3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:54:18) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pymatgen.optimization.neighbors import find_points_in_spheres
Illegal instruction (core dumped)

**Comment by shyuep** [comment]
I am not sure what's the issue with conda installation on Linux. But for linux, perhaps you can just try using `pip install pymatgen`. That usually forces a compile using whatever compiler you have on your system and works fine.

**Comment by gmfricke** [comment]
Thanks for the reply. The illegal instruction does not occur with Clang 9.0.0 and Python 8, but does occur with gcc 7.3.0 and Pyton 3.7.3. The pymatgen versions are both 2019.12.3. 

Python 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:19) 
[Clang 9.0.0 (tags/RELEASE_900/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pymatgen.optimization.neighbors import find_points_in_spheres
>>>

**Comment by shyuep** [comment]
Hmm... Python 3.8 cannot be the issue. We have tested on Python 3.7x and it works. It is probably the c compiler then. Does pip installing solve the problem?

**Comment by gmfricke** [comment]
I tried pip which we use fairly regularly, this is at an HPC center. For example 
pip3 install --user pyramid installs correctly

however
pip3 install --user pymatgen yields,

gcc -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.6m -I/users/mfricke/.local/lib/python3.6/site-packages/numpy/core/include -c pymatgen/optimization/linear_assignment.c -o build/temp.linux-x86_64-3.6/pymatgen/optimization/linear_assignment.o
    pymatgen/optimization/linear_assignment.c:4:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1

**Comment by shyuep** [comment]
As far as  I can tell, the problem is that the header files are missing. I would suggest you do not just type pip3 in the command line. It is probably the system Python (I see Python 3.6, not 3.7 in your output) and pip that is being used.

I suggest you use the gcc from conda itself. And then use pip from within your conda env. ie..,

```
conda create -n test_pymatgen python=3.7
conda activate test_pymatgen
conda install gcc
pip install pymatgen
```

I tested this on a HPC and it works.

**Comment by gmfricke** [comment]
That worked beautifully. Thank you for the help.
