### ISSUE TITLE
PhaseDiagram/PDPlotter may rotate endpoints when elements are not explicitly specified.

### ISSUE THREAD

**Issue by JosephMontoya-TRI** [materialsproject/pymatgen#1721]
**Describe the bug**
PhaseDiagram/PDPlotter may rotate endpoints when elements are not explicitly specified.

**To Reproduce**
1. Make list of entries
2. PhaseDiagram(entries)
3. PhaseDiagram(entries.shuffle())
4. PDPlot both
5. One may be rotated relative to other

**Expected behavior**
Endpoints of PDPlot to be consistent

**Additional context**
Specifically, this cropped up when we were plotting differences between successive iterations of an algorithm which augmented a list of entries on the same plot.  One was rotated, but the endpoints didn't show up.  One can remedy this by supplying an explicit list of elements, but it's a bit surprising that you would need to do so for ordering purposes.

**Comment by shyuep** [comment]
I don’t have a problem with this. I guess the simplest solution is to add a elements = sorted(elements) somewhere. Feel free to implement, with tests, and submit PR.

**Comment by mattmcdermott** [comment]
@JosephMontoya-TRI  just checking, this issue is fixed with your PR from a couple of years ago and can be closed right?

**Comment by JosephMontoya-TRI** [comment]
Yep.
