### ISSUE TITLE
Add new spacegroup names

### ISSUE THREAD

**Issue by arosen93** [materialsproject/pymatgen#1730]
In `pymatgen/symmetry/symm_data.json`, there is the `Cmma` spacegroup (num. 67), but this spacegroup has [been renamed](https://hal.archives-ouvertes.fr/hal-00963925/document) (see top of page 00006-p.26) to `Cmme`, which is not found in the json file. Similarly, there is support for `Ccca` (num. 68), but this spacegroup has been renamed `Ccce`, which is not supported. Interestingly, spacegroup num. 64 is included with its new name of `Cmce`, but its old name of `Cmca` is not included as a possible synonym.

**Comment by shyuep** [comment]
Thanks, I pushed a fix to include all renames of the "e" operation and added tests. Let me know if there are other issues.
