### ISSUE TITLE
 Fail to build python bindings to Zeo++ with Cython

### ISSUE THREAD

**Issue by ws517037749** [materialsproject/pymatgen#1747]
**Describe the bug**
Successful compilation of Zeo++ but fail to build the python bindings , the return error is ''command 'gcc' failed with exit status 1'', I am not sure whether it is the problem for the gcc or something else. I successfully do it only once in a cluster but failed in my Macbook (Macos.10.15.2) and on the other cluster.

**To Reproduce**
mkdir Voro++
mkdir Voro++/voro
cd Voro++/voro
svn checkout --username anonsvn https://code.lbl.gov/svn/voro/trunk  # password is 'anonsvn'
Add -fPIC to the CFLAGS variable in config.mk
mkdir Zeo++
mkdir Zeo++/zeo
cd Zeo++/zeo
svn checkout --username anonsvn https://code.lbl.gov/svn/zeo/trunk  # password is 'anonsvn'
cd trunk
make dylib
make
pip install cython
cd cython_wrapper
python setup_alt.py develop

**Expected behavior**
Clear the python binding problem, actually the compiled binary file could run successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/43861983/73283021-7b840f80-41c0-11ea-9c03-e507ae7e391e.png)

**Desktop (please complete the following information):**
 - OS:   Red Hat 
 - Version:   4.8.5-28

**Additional context**

**Comment by shyuep** [comment]
Pls contact the developers of Zeo++ as we do not maintain that code.
