### ISSUE TITLE
Point cloud from structure

### ISSUE THREAD

**Issue by mm04926412** [materialsproject/pymatgen#1750]
In order to get a raw point cloud from a pymatgen structure I've found I've had to use the as dict method and list comprehensions which is computationally expensive, a quick command to extract a 2d list of every species in the from [x,y,z,element, oxidation,occupancy] or something similar would be invaluable for geometric machine learning on crystal structures.

**Comment by shyuep** [comment]
[[*site.coords, site.specie.symbol, site.specie.oxi_state] for site in structure]

I don’t think there is a need to use the as_dict method.

**Comment by mm04926412** [comment]
I had tried this I believe but I didn't want the 'sites'  for partial occupancies I wanted a raw list of atoms which I struggled to achieve without hacky list comprehensions that took a long time to complete.

Directly calling species broke for partial occupancies and directly calling sites gave inconsistent dtypes.

**Comment by shyuep** [comment]
Perhaps I am unclear what is the output you want. By nature, partial occupancies have an arbitrary number of elements and occupancies.

**Comment by mm04926412** [comment]
Yes, I wanted to expand them out and treat them as independant points, my main issue has been that the neighbour class seems to erase access to the occupancy.

So I'd want to represent the site H0.25O0.75 at x,y,z = 1,2,3 as

[1,2,3,H,0.25]
[1,2,3,O,0.75]

My apologies if doing this with the library is actually trivial the structure module just seems to be fighting me on getting a raw array of species and getting rid of the grouping into a site

**Comment by shyuep** [comment]
I see. This is actually not difficult (and the Neighbor class functions just like a PeriodicSite in most instances).

```python
data = []
for site in structure:
    for el, occu in site.species.items():
        row = list(site.coords)
        row.append(str(el))
        row.append(occu)
    data.append(row)
```
should provide what you need.

For future reference, pls post questions on usage at http://discuss.matsci.org . The Github Issues is meant for bug reports and feature requests. Thanks.

**Comment by mm04926412** [comment]
Ah thank you, I was unaware of the generic items method and was looking in the documentation which led me to believe the information was missing. I'll take note to assume I'm the prolem and head to masci before posting here again then thank you for your time!
