### ISSUE TITLE
visualize multiple molecules

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [materialsproject/pymatgen#1762]
Hello,

I am trying to visualize multiple molecules to get the sense of the whole dataset. First,  I tried [nglview](https://github.com/arose/nglview/issues/864) it works for single-molecule but not work for multiple ones. From this [post](https://github.com/materialsproject/pymatgen/issues/1310) , pymatgen.vis.structure_chemview is also not the right way.

I was wondering would you like to suggest some quick visualization tools that can 1) plot and save a single molecule as a png and 2) plot all many molecules, say 100, into a 10*10 grid very easily?

I am a computer scientist who doesn't know much about chemistry and material science. The two above requirements seem to be very reasonable and I am having a hard time finding an easy way to achieve this. Hopefully, this make sense to you. Thank you very much for your help!

**Comment by shyuep** [comment]
I think your original post already answers the question. I think (1) can be done with nglview and you can make sure all the molecule plots are the same size. (2) Once you have 100 images from (1), you can easily use the Pillow package to stitch images. See https://stackoverflow.com/questions/10657383/stitching-photos-together for an example.

**Comment by Chen-Cai-OSU** [comment]
Sure thing I can do that myself. But this often requires taking care out input/ouput and convert matplotlib figures to images and then stitch images together. Taking care of those things usually takes quite some time and my intention is simply take a look at data before doing any analysis. 

I feels that this is better done in pymatgen instead by users.
