### ISSUE TITLE
MaterialsProjectCompatibility method process_entries fails if symmetry determination of any entry fails

### ISSUE THREAD

**Issue by LuciusV** [materialsproject/pymatgen#1764]
I process a lot of calculated entries collected by BorgQueen and put them in all_entries list. Then when I use 

from pymatgen.entries.compatibility import MaterialsProjectCompatibility
processed_entries = compat.process_entries(all_entries)
I got exception

`/home/youjin/.local/lib64/python3.6/site-packages/pymatgen/symmetry/analyzer.py in get_space_group_symbol(self)
    105             (str): Spacegroup symbol for structure.
    106         """
--> 107         return self._space_group_data["international"]
    108 
    109     def get_space_group_number(self):

TypeError: 'NoneType' object is not subscriptable`

Obviously because symmetry determination in 
`/home/youjin/.local/lib64/python3.6/site-packages/pymatgen/analysis/structure_analyzer.py in sulfide_type(structure)
    620 
    621     finder = SpacegroupAnalyzer(structure, symprec=0.1)
--> 622     symm_structure = finder.get_symmetrized_structure()`
fails.
I suggest changing 
`/home/youjin/.local/lib64/python3.6/site-packages/pymatgen/entries/compatibility.py in process_entry(self, entry)
    438         """
    439         try:
--> 440             corrections = self.get_corrections_dict(entry)
    441         except CompatibilityError:
    442             return None`
to also catch TypeError.

**Comment by shyuep** [comment]
Hmmm interesting. But it is very rare that symmetry detection fails. Typically the worst case scenario is that the structure returns a P1. Failure usually occurs only when you have colliding atoms, in which case the calculation is completely useless....

Do you have an example where this failure occured on a normal structure?

**Comment by LuciusV** [comment]
You are right, this is because of bad structure, it exploded during optimization and also have overlapped atoms like you mentioned. Actually its only one structure in about 30000 entries, so consigering above I don't expect this happen in normal structure now.
