### ISSUE TITLE
visualization 

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [materialsproject/pymatgen#1765]
Hello,

Sorry I have to reopen this issue. https://github.com/materialsproject/pymatgen/issues/1762. It turns out that ngl cannot save visualization of a single molecule in python script. (only support Jupiter notebook) So right now I don't even know how to visualize a single molecule (cif file) in a python script. 

I am not asking for a simple solution to visualize multiple molecules. (I can do this my self by stitching a bunch of png files myself) Would you like to provide a  working example to visualize a cif file?

Thank you very much!

**Comment by wenhaosun** [comment]
Check out StructureVis: https://pymatgen.org/pymatgen.vis.structure_vtk.html
