### ISSUE TITLE
PointGroupAnalyzer gets totally wrong point group

### ISSUE THREAD

**Issue by fxcoudert** [materialsproject/pymatgen#1772]
**Describe the bug**
pymatgen 2020.1.28 fails to identify proper point group with pymatgen.symmetry.analyzer.PointGroupAnalyzer

**To Reproduce**

1. Create a file called `Cluster_H.xyz` with this content: https://gist.github.com/fxcoudert/def477b148e95b8cad61804e26e89271
2. Run the following code:

```
import pymatgen
mol = pymatgen.Molecule.from_file("Cluster_H.xyz")
pg = pymatgen.symmetry.analyzer.PointGroupAnalyzer(mol)
print(pg.get_pointgroup())
```

3. The point group identified is `D1d`, which is wrong.

**Expected behavior**
The point group should be `C3v`, not `D1d`. Changing tolerances will not help, since the symmetry is exactly C3v in this case.

This is a significant mistake, since D1d (which is also C2h with a different choice of orientation) is actually not a subgroup of C3v at all.

**Desktop**
 - OS: macOS 10.15.3
 - Version: pymatgen 2020.1.28

**Comment by fxcoudert** [comment]
Forget about it. The default eigenvalue tolerance is just too low for something like this. I have:

```
DEBUG:pymatgen.symmetry.analyzer:Spherical top molecule detected
DEBUG:pymatgen.symmetry.analyzer:Accidental speherical top!
DEBUG:pymatgen.symmetry.analyzer:Eigenvalues = [0.66670374 0.66659252 0.66670374].
DEBUG:pymatgen.symmetry.analyzer:Rotation symmetries = [(array([-0.16868303, -0.60751073,  0.77619376]), 1)]
DEBUG:pymatgen.symmetry.analyzer:Accidental speherical top!
DEBUG:pymatgen.symmetry.analyzer:Eigenvalues = [0.66670374 0.66659252 0.66670374].
DEBUG:pymatgen.symmetry.analyzer:Rotation symmetries = [(array([-0.16868303, -0.60751073,  0.77619376]), 1), (array([-0.16868303, -0.60751073,  0.77619376]), 1)]
```

which lead me to lower the tolerance:

```
pg = pymatgen.symmetry.analyzer.PointGroupAnalyzer(mol, eigen_tolerance=0.000001)
```

which lead to the correct `C3v` point group.

**Comment by mkhorton** [comment]
Re-opening because we’ve had another issue with this recently where the eigenval tolerance didn’t help. I’ll try to find it to late here.

On investigation, it seemed strange because the detected symmetry ops were still correct even though the label was wrong. We suspect a logic bug, and want to investigate alternatives to the current labelling algorithm.

**Comment by fxcoudert** [comment]
I am seeing more trouble. I was trying to get the symmetrized molecule into a good frame of reference, since it appears that `symmetrize_molecule` does not do any orientation.

However, I am finding that the principal axes as calculated by `PointGroupAnalyzer` are not orthogonal, which I don't understand:

```
#!/usr/bin/env python3

import numpy as np
import pymatgen

mol = pymatgen.Molecule.from_file("Cluster_Zr_1H.xyz")
pg = pymatgen.symmetry.analyzer.PointGroupAnalyzer(mol, eigen_tolerance=0.000001)
print('Point group: ' + str(pg.get_pointgroup()))
print(np.dot(pg.principal_axes, pg.principal_axes.T))
```

is giving:

```
Point group: C3v
[[ 1.00000000e+00 -1.04189128e-14  3.97365516e-01]
 [-1.04189128e-14  1.00000000e+00 -7.17973577e-13]
 [ 3.97365516e-01 -7.17973577e-13  1.00000000e+00]]
```

which is not the identity matrix (see xz and zx terms).

**Comment by shyuep** [comment]
It does seem like the answer is approximately an identity. But just to clarify, the principal axes are just the eigenvectors of the inertia tensor. This is straight from a numpy.linalg.eig calculation. THis molecule is rather large, so it is rather sensitive to numerical errors.

**Comment by espottesmith** [comment]
Adding another example upon encouragement from @mkhorton. Just tried using the PointGroupAnalyzer on the following molecule:

5
Li1 C2 O2
O 1.466022 0.260061 0.857948
C 1.199389 0.074416 2.036307
C 0.920374 -0.114814 3.237086
O 0.648901 -0.305195 4.442436
Li 0.266687 -0.563754 6.096545

It didn't actually return the wrong point group. Instead, I got a ValueError from _get_smallest_set_not_on_axis:

ValueError: min() arg is an empty sequence

I guess this makes sense since it's trying to find a set of molecules not on the axis, but the molecule is linear?

This is on version '2020.12.31', by the way.

**Comment by shyuep** [comment]
I cannot reproduce the last error. 

```
from pymatgen import Molecule
 m = Molecule.from_file("test.xyz")
from pymatgen.symmetry.analyzer import PointGroupAnalyzer
a = PointGroupAnalyzer(m)
print(a.get_pointgroup())
```

spits out C*v, which is correct?

**Comment by espottesmith** [comment]
Ah, I should have mentioned in my original post. This was with eigen_tolerance=0.000001 (trying to ensure that there wouldn't be issues with tolerance as the original issue mentioned). That is interesting that by using the default tolerance you don't get an issue.

**Comment by shyuep** [comment]
@espottesmith Tolerances work both ways. Too strict and you are unable to detect certain symmetries when they exist. Too loose and certain atoms/symmetry operations get lumped together. There is no way around this unless you are always inputting an idealized molecule at perfect symmetry positions at the limits of floating point precision. The best we can do is to tweak the default settings such that it works in most cases.
