### ISSUE TITLE
Error in reading PROCAR file with SOC

### ISSUE THREAD

**Issue by rajibul645** [materialsproject/pymatgen#1778]
I got following  error in reading PROCAR file. Could you please suggest me, how should I deal with this problem?  

C:\ProgramData\Anaconda3\envs\Pymatgen\lib\site-packages\pymatgen\io\vasp\outputs.py in __init__(self, filename)
   3477                             for orb in range(len(headers)):
   3478                                 phase_factors[spin][current_kpoint, current_band,
-> 3479                                                     index, orb] = complex(num_data[2 * orb], num_data[2 * orb + 1])
   3480                         else:
   3481                             # old format of PROCAR (vasp 5.4.1 and before)

IndexError: index 10 is out of bounds for axis 0 with size 10

**Comment by Nokimann** [comment]
Same issue currently.
