### ISSUE TITLE
POTCAR with symbol Si has metadata that does not match any VASP POTCAR known to pymatgen.

### ISSUE THREAD

**Issue by hongyi-zhao** [materialsproject/pymatgen#1787]
Hi,

I try to run the examples here:

https://ma.issp.u-tokyo.ac.jp/en/app-post/1146

With the following code to generate the band-structure plot:

```
from pymatgen.io.vasp.outputs import Vasprun
from pymatgen.electronic_structure.plotter import BSPlotter

vaspout = Vasprun("./vasprun.xml")
bandstr = vaspout.get_band_structure(line_mode=True)
plt = BSPlotter(bandstr).get_plot(ylim=[-12,10])
plt.savefig("band.pdf")
```

I get the following warnings:

```
In [1]: runfile('/home/werner/Cd-Si/plotband.py', wdir='/home/werner/Cd-Si')
Reloaded modules: spyder
/home/werner/.pyenv/versions/hpc/lib/python3.8/site-packages/pymatgen/io/vasp/inputs.py:1855: BadPotcarWarning: POTCAR with symbol Si has metadata that does not match                          any VASP POTCAR known to pymatgen. The data in this                          POTCAR is known to match the following functionals:                          ['unvie_PBE_52', 'PBE_54', 'PBE_52']
  warnings.warn("POTCAR with symbol {} has metadata that does not match\
```

How to solve this issue?

Regards

**Comment by mkhorton** [comment]
Hi @hongyi-zhao, it’s just a warning. If you’re comfortable you’re using the correct POTCAR you can ignore it.

It’s basically saying that the functional is compatible with those distributed as PBE_52/54 by VASP, but a specific variation we haven’t encountered before. This doesn’t mean it’s wrong.

(Flagging @rkingsbury )

**Comment by hongyi-zhao** [comment]
Thanks, got it.

**Comment by kayahans** [comment]
Hi, 

I have and a couple people experience the same problem as I see from the open issues. In my case, POTCAR metadata (PSCTR file) never matches the PSCTR of PotcarSingle object. However, md5 sums of the POTCARs I have always matches the vasp_potcar_pymatgen_hashes.json file. 

I thought the content of the actual pseudopotential file is more important than what is inside the metadata. Why do you need to check the contents of the metadata as well?

Thanks,
Kayahan

**Comment by rkingsbury** [comment]
Hi @kayahans , you are correct. The content of the actual pseudopotential file is what affects the calculation, so as long as the hash of the potcar **data** (which is calculated by the `get_potcar_hash` method) matches the contents of `vasp_potcar_pymatgen_hashes.json`, then your POTCAR is valid. 

We track the hash of the metadata as well to provide a clearer provenance as to which POTCARs are being used, and to serve as an indicator that the contents of the POTCARs have been modified at some point. Basically, if the contents of the file (including metadata) do not match exactly what is provided by VASP, you will see a warning.

**Comment by kayahans** [comment]
Thanks!

**Comment by mkhorton** [comment]
@rkingsbury we're getting enough queries about these warnings that I think we should re-word the messages a little bit. I'll make a change
