### ISSUE TITLE
Space group symmetry operator issues

### ISSUE THREAD

**Issue by pietakio** [materialsproject/pymatgen#1789]
Hi!

Thank you for making Pymatgen -- it's a fabulously helpful and awesome program.
 
I've encountered two major issues when working with generation of Structures using Structure.from_spacegroup(). 

**First case**

In the first case (for space group 'P6_3/m', with equivalent results using the space group number 176) the generated structure is clearly not correct as it contains the incorrect number of Ca atoms (there are 14 Ca atoms instead of 10 in the unit cell). 

In this case, the structure that I'm trying to generate from lattice parameters and a list of atomic positions is based on hydroxyapatite, and there are cif files available to define hydroxyapatite ([Hydroxyapatite.txt](https://github.com/materialsproject/pymatgen/files/4302192/Hydroxyapatite.txt)). 

However, when I define the structure using Structure.from_file() and use the pre-defined cif files for hydroxyapatite, the unit cell has the correct formula.  I noticed that if I change the spacegroup symbol
or the international spacegroup number in the hydroxyapatite cif file, that there is no change to the 
structure defined by Pymatgen using Structure.from_file(). If, however, I change the space group 
symmetry operations in the hydroxyapatite cif file, then the structure generated by Pymatgen has the
incorrect unit cell formula (additional atoms appear, as happens when I attempt to generate the structure using Structure.from_spacegroup(). This leads me to believe that there is an error in Pymatgen's spacegroup symmetry operators for space group 'P6_3/m' (number 176). 

The symmetry operators from the hydroxyapatite cif file are:
  'x,y,z'
  '-x+y,-x,1/2-z'
  'x-y,x,1/2+z'
  'y,-x+y,-z'
  '-y,x-y,z'
  'x,y,1/2-z'
  '-x,-y,1/2+z'
  'x-y,x,-z'
  '-x+y,-x,z'
  '-y,x-y,1/2-z'
  'y,-x+y,1/2+z'
  '-x,-y,-z'

If you would please check and fix, this would be much appreciated! 

To reproduce:
```
# Structure generated from cif reference file:
ref_struct = Structure.from_file(os.path.join(read_path, "Hydroxyapatite.cif"))

# Structure generated from atom list, lattice info, coords, and spacegroup (slightly different coords
# and lattice constants, but results are same using exact coords of ref cif file):
siha_atoms_list =  [{'Ca':1.0},{'Ca':1.0},{'P':1.0},{'O':1.0},{'O':1.0},{'O':1.0},{'O':0.5},{'H':0.5}]
# siha_atoms_list =  ['Ca','Ca','P','O','O','O','O','H']

siha_atom_coords = [[0.33333, 0.66667, 0.00195],
                    [0.24745, 0.99214, 0.25000],
                    [0.39747, 0.36773, 0.25000],
                    [0.32481,0.48347,0.25000],
                    [0.58394,0.46300,0.25000],
                    [0.34028,0.25607,0.07052],
                    [0.00000,0.00000,0.20142],
                    [0.00000,0.00000,0.01242]]

siha_latt = Lattice.from_parameters(a=9.43144, b=9.43144, c=6.94553, 
                               alpha=90.00000, beta=90.0000, gamma=120.00000)   

siha_struct = Structure.from_spacegroup('P6_3/m', siha_latt, siha_atoms_list, siha_atom_coords)

# Compare siha_struct to ref_struct and see that siha_struct is not correct, although it should be
# same unit cell formula to the one generated by the symmetry operators of the hydroxyapatite.cif file. 

```

**Second Case**

The second case also involves generating a structure from Structure.from_spacegroup().

In this case, when attempting to generate a structure using the space group 'P 1 21/a 1', I get the correct structure, and when using xrayutilities I obtain an excellent match between the calculated and experimental xrd curve, so I believe that the structure generated by Pymatgen is correct. 

The 'P 1 21/a 1' space group corresponds to international number 14 (http://img.chem.ucl.ac.uk/sgp/large/014ay1.htm), and using get_space_group_info() on the Pymatgen generated structure says the space group is ( 'P2_1/c', 14). However, if I generate the structure using 'P2_1/c' or number 14, the structure returned is incorrect, and the match to the experimental xrd spectra is terrible, and moreover, 'P2_1/c' and number 14 results are not the same (where I definitely think these two results should be the same). Again, I feel as though there must be a mistake in the underlying symmetry operators, where in this case there are different operators for items that should be mapping to the same operator (it's possible that I'm confused here too, and if this is the case, some additional documentation would be much appreciated).  

**Expected behavior**
Expected structure read by cif and generated from_space group to be the same, and expected structures generated from equivalent space group symbols and numbers to be the same.  

**Desktop:**
 - OS: Linux
 - Ubuntu 18.04.4 LTS

Thanks so much for your help!

**Comment by mkhorton** [comment]
Hi @pietakio,

When building structure from space groups you have to be very careful with the precision of your inputs. Have you tried:

`siha_atom_coords = [[1/3, 2/3, 0.00195], ...`

instead?

When this happens, it's usually because 0.33333 != 1/3 from the point of view of applying a symmetry operation. If importing from a CIF file, pymatgen will try to find rational fractions for certain co-ordinates and correct as appropriate.

If this doesn't fix your issue, we can certainly look at the space group operations themselves. Errors in these are rare but certainly possible!

**Comment by pietakio** [comment]
Hi @mkhorton,

Thank you so much! Yes, on your above advice I re-wrote the atom coordinates in fractions 
(wherever they were obvious) as:

```
siha_atom_coords = [[1/3, 2/3, 0.00195],
                    [0.24745, 0.99214, 1/4],
                    [0.39747, 0.36773, 1/4],
                    [0.32481,0.48347,1/4],
                    [0.58394,0.46300,1/4],
                    [0.34028,0.25607,0.07052],
                    [0.00000,0.00000,0.20142],
                    [0.00000,0.00000,0.01242]]
```

And now it works to give the correct structure.

Thanks so much!! 

So nothing needs to be fixed in the space group operators for 'P6_3/m', although if it's not there already (perhaps I missed it?), it would be fantastic if a note could be made about the need to use fractions in the Structure.from_spacegroup() doc strings to save other people who might struggle with the precision issue.   

Any thoughts on my "case 2" (space group symbol and international number not generating the same structure)? 

Thanks!

**Comment by mkhorton** [comment]
For your second case, you should be aware there are multiple "settings" available for each space group. We use the standard ITA (International Tables for Crystallography, Vol. A) settings in pymatgen, as are also used in spglib.

For the specific example of space group 14, a monoclinic group, we have to choose our unique axis (this can be either **a**, **b** or **c**) along with different choices for the oblique axes (cell choices 1, 2 or 3), and this leads to 18 different possible settings. The Bilbao Crystallographic Server is an excellent resource for this. "P 1 2_1/a 1" chooses the **a** lattice vector as its unique axes, whereas the standard "P 1 2_1/c 1" is the ITA setting with **c** as its unique axes. Likely, your reference is using the former, and pymatgen is using the latter.

The important thing here is that the overall symmetry is the same in all settings (the same symmetry operations are present), but the way we're describing the cell changes. In particular, the positions of the atoms in your motif will be different. And if you use positions for one setting while using the generators for a different system then you'll get the incorrect result.

Finally, *pymatgen* does include a `JonesFaithfulTransformation` to help you convert atomic positions, lattices and symmetry operations between different settings. Good luck!

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/2976580/76156594-75335e00-60b1-11ea-971c-21849c59081c.png">
From International Tables for Crystallography, Vol. A

<img width="838" alt="image" src="https://user-images.githubusercontent.com/2976580/76156609-aa3fb080-60b1-11ea-8bbf-2fdfc0559533.png">
From Bilbao Crystallographic Server, "GENPOS"

**Comment by pietakio** [comment]
Thank you! This is extremely helpful. 

A few (hopefully simple requests) to help clarify these issues for others:
1. Please add a note to the doc strings for Structure.from_spacegroup() about the need to use fractions, where possible, when specifying atomic coordinates.  
2. Would it be possible for the space group tag (i.e. what's returned from get_space_group_info()) to return the extended symbol instead of, or in addition to, the short form, as this would greatly help confirm to the user specifically what is being done in terms of symmetry operations? 

Thank you so much!

**Comment by mkhorton** [comment]
> Please add a note to the doc strings for Structure.from_spacegroup() about the need to use fractions, where possible, when specifying atomic coordinates.

Agreed, that sounds sensible. Just a word of caution here though; there are many real cases of crystals where atomic positions are almost-but-not-quite at fractional co-ordinates and these do have physical meaning. At the end of the day, the user has to make a judgement call here.

> Would it be possible for the space group tag (i.e. what's returned from get_space_group_info()) to return the extended symbol instead of, or in addition to, the short form, as this would greatly help confirm to the user specifically what is being done in terms of symmetry operations?

We probably won't change this -- partly because we don't want to break backwards compatibility with scripts that expect a certain output from this command, and also because the short H-M symbol is sufficient to convey setting information (P2_1/c).

However, note that these are just convenience methods on `Structure`. If you want more information, pymatgen offers a lot more functionality via its `pymatgen.symmetry` module including `SpaceGroup` (which can give you the full symbol as an attribute) and also `SpaceGroupAnalyzer` (which can give you the structure in other settings, give you a way to retrieve Wyckoff labels etc.)
