### ISSUE TITLE
The list of vasp's INCAR tags supported by pymatgen currently.

### ISSUE THREAD

**Issue by hongyi-zhao** [materialsproject/pymatgen#1791]
Hi,

The complete list of vasp INCAR tags is here:
https://www.vasp.at/wiki/index.php/Category:INCAR

I want to know which of them supported by pymatgen currently?

Regards

**Comment by mkhorton** [comment]
You can use any VASP INCAR tag via pymatgen using `user_incar_settings`.

**Comment by hongyi-zhao** [comment]
I mean whether the pymatgen has already built-in all of these tags with the usage instructions when I use a appropriate python IDE, say, pycharm, to write the script.

**Comment by hongyi-zhao** [comment]
The tag list is huge to some extent, so have the build-in usage instructions for them may be more useful for writing the job scripts with the help of python IDE's auto-completion functionality.

**Comment by shyuep** [comment]
Pymatgen does not have instructions for VASP tags or any other software. Ultimately, VASP belongs to a completely different set of developers and they have to maintain their own documentation and help. It is certainly easy enough for us to implement something that obtains the help from the wiki....

**Comment by hongyi-zhao** [comment]
Good idea.  Thanks a lot.

**Comment by shyuep** [comment]
I implemented a basic version for now. It should be easy to make it nicer. See pymatgen.io.vasp.help.

**Comment by hongyi-zhao** [comment]
Wonderful, I'll see it and test it.

**Comment by shyuep** [comment]
```python
from pymatgen.io.vasp.help import VaspDoc
doc = VaspDoc()
doc.print_help("ISYM")
```

Pls review how to use Python classes. Sorry, but we cannot provide support for Python syntax.

**Comment by hongyi-zhao** [comment]
Thanks.
