### ISSUE TITLE
Some properties of the Element class not defined with decorate @property.

### ISSUE THREAD

**Issue by hongyi-zhao** [materialsproject/pymatgen#1794]
Hi,

Say for the following code snippets:
```

import pymatgen as mg
fe = mg.Element("Fe")
print(fe.atomic_mass)
print(fe.melting_point)
print(fe.boiling_point)
```

The atomic_mass is defined as a property with decorate @property, but the other two are not.  This will cause the property's name cannot be auto-completed within the python IDE, say pycharm. 

Are they designed like this intentionally or need to some touch up for add the corresponding  @property's?

Regards

**Comment by shyuep** [comment]
The @property is only used if we are using a hidden variable or it is a property that is computed on the fly. In this case, the atomic mass is important enough that we write a special decorator for it. The melting point and boiling point are much less frequently used and so we just leave it to the get_attr function to deal with it.
