### ISSUE TITLE
Want to make a PR for fixing the installation.rst

### ISSUE THREAD

**Issue by hongyi-zhao** [materialsproject/pymatgen#1795]
Hi,

I noted that the following description is outdated here:
https://github.com/materialsproject/pymatgen/blob/master/docs_rst/installation.rst

`3. Atomistic Simulation Environment or ASE 3.6+: Required for the usage of the adapters in pymatgen.io.aseio between pymatgen's core Structure object and the Atoms object used by ASE. Get it at https://wiki.fysik.dtu.dk/ase/. Note that the ASE package is incompatible with Python 3.x at the moment.`

In fact, based on the info here: https://wiki.fysik.dtu.dk/ase/install.html, at the moment, ASE package need Python 3.5+.  So, I changed the above notes into the following:

```
3. Atomistic Simulation Environment or ASE 3.6+: Required for the usage of the
   adapters in pymatgen.io.aseio between pymatgen's core Structure object and
   the Atoms object used by ASE. Get it at https://wiki.fysik.dtu.dk/ase/.
   Note that the ASE package is compatible with Python 3.5+ at the moment.
```

Then I want to make PR, but I'm not sure whether only change this file is enough?  Please instruct me for all the changes should I do before I can make the PR.

Regards

**Comment by shyuep** [comment]
Yes, submitting a PR would be fine. In fact, we prefer small PRs, even when the functionality is big, it is preferable they are broken up into simple chunks.

**Comment by hongyi-zhao** [comment]
Thanks.  Another issue also said on the installation page, see following:

```
$ pip install pymatgen[extra] 
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pymatgen[extra] in /home/werner/Public/hpc/tools/pymatgen.git (2020.3.2)
  WARNING: pymatgen 2020.3.2 does not provide the extra 'extra'
```

Is the following install option discarded for pymatgen 2020.3.2:

`pymatgen[extra] `

Regards

**Comment by shyuep** [comment]
The word extra means one of the other extras needed. E.g., pip install pymatgen[ase]. These are defined in the setup.py under extras_require.
