### ISSUE TITLE
Report a bug or issue

### ISSUE THREAD

**Issue by danpho** [materialsproject/pymatgen#1796]
**Describe the bug**
I prefer using issue report instead of bug report. I am not fully sure it is a bug. But it shows that the inconsistent results with same input, setting, and environments.

Note: My structure has partial occupation sites.
Pymatgen was updated in February.

I built a small model using PDFgui. And then use pymatgen to generate a supercell. However, under Python >3.7 environment(I tested v3.7 and 3.81), the same input cif file and settings, I receive the inconsistent outputs. I do not which one is reasonable. Then I visualize each output to see the difference using CrystalMaker. 

**To Reproduce**
Attached are my scripts, input_control file, input cif files, and output pdb files.
Please run wmake_supercell.py, and then check the number of Cs and Ba in ./pdb/*.pdb file. Rename these files and rerun the scripts. Most time, I got different numbers of Cs and Ba. 

**Expected behavior**
I hope that the output is consistent with same configurations and input.

**Screenshots**
Here, I attached part of the generated structures. I ran twice my scripts, and got different number of Ba and Cs atoms.
![image](https://user-images.githubusercontent.com/19391437/76330339-1d207580-62c4-11ea-9d22-8927d70a5093.png)
![image](https://user-images.githubusercontent.com/19391437/76330427-36c1bd00-62c4-11ea-80c3-dcfafe67fac0.png)

**Desktop (please complete the following information):**
 - OS: [CentOS 7.3, Kernel: Linux 3.10.0-514.16.1.el7.x86_64]
 - Version [pymatgen==2020.1.28

Here are all of my files which are in pdfgui.zip.
[pdfgui.zip](https://github.com/materialsproject/pymatgen/files/4313301/pdfgui.zip)]

**Additional context**

**Comment by danpho** [comment]
Sorry, I did not realize, I posted a screenshot at the bottom my post.

**Comment by shyuep** [comment]
Sorry, but there is a lot happening in your script. Pls report the issue/bug properly with a *short* script that reproduces the problem with a minimum number of lines and inputs. We cannot debug a long script where we do not even know where the bug occurred and whether it is even in a Pymatgen related method or one of the many other packages being used.
