### ISSUE TITLE
Add angle_tolerance argument to CifWriter constructor

### ISSUE THREAD

**Issue by kyledmiller** [materialsproject/pymatgen#1797]
Pymatgen is very useful for quickly converting between file types, e.g., POSCAR <--> cif, but the `CifWriter` constructor is lacking the `angle_tolerance` parameter which means the default `SpaceGroupAnalyzer` value of 5 degrees is used. This value is too large for many applications and should in principle be configurable.

This issue could be very easily solved by simply adding an `angle_tolerance=None` argument to the constructor and carrying it through to the `SpaceGroupAnalyzer` constructor call.

**Comment by mkhorton** [comment]
Please feel welcome to open a pull request if this would be useful!
