### ISSUE TITLE
SpaceGroup.from_int_number(hexagonal=False) ineffective

### ISSUE THREAD

**Issue by jacksund** [materialsproject/pymatgen#1801]
**Describe the bug**
When initiating a SpaceGroup class using the SpaceGroup.from_int_number(), the hexagonal option is ineffective for the following spacegroups: 146,148,155,160,161,166,167

NOTE: This is similar to issue #1203. The big difference is that here, it's claimed functionality that is ineffective. While a workaround exists, the functionality of hexagonal=False needs to be corrected.

**To Reproduce**
Below is an example with spacegroup 166 that illustrates the bug:

```
from pymatgen.symmetry.groups import SpaceGroup

SpaceGroup('R-3m') # correctly returns hexagonal info (per hexagonal is set as default)
SpaceGroup('R-3m:H') # correctly returns hexagonal info
SpaceGroup('R-3m:R') # correctly returns rhombohedral info

SpaceGroup.from_int_number(166, hexagonal=True) # correctly returns hexagonal info
SpaceGroup.from_int_number(166, hexagonal=False) # incorrectly returns hexagonal info
```

**Expected behavior**
```
sg = SpaceGroup.from_int_number(166, hexagonal=False) 
sg.symbol # should be 'R-3mR', but instead give 'R-3mH' which is the hexagonal form
sg.order # should be 12, but instead gives 36 which is the hexagonal form
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 2019.12.22 (though code looks to be identical in the up-to-date github version)

**Additional context**
In the from_int_number() code ([located here on github](https://github.com/materialsproject/pymatgen/blob/5a3284fd2dce70ee27e8291e6558e73beaba5164/pymatgen/symmetry/groups.py#L470)), the method really is just calling sg_symbol_from_int_number() and running that result back through SpaceGroup(). The bug exists in sg_symbol_from_int_number(). More specifically, it is a logical error in the following line:

`syms = list(filter(lambda s: not s.endswith("H"), syms))`

This line is run when hexagonal=False. The issue is that this line will return ‘R-3m’, which then calls SpaceGroup(‘R-3m’) – this still gives the hexagonal object! We need that line to return ‘R-3m:R’, not ‘R-3m’. We could add ':R' in multiple places:

OPTION 1: within SpaceGroup.from_int_number():
```
##### original code ######
return SpaceGroup(sg_symbol_from_int_number(int_number,hexagonal=hexagonal))

##### fixed code ######
sym = sg_symbol_from_int_number(int_number,hexagonal=hexagonal)
if not hexagonal and int_number in [146,148,155,160,161,166,167]:
    sym += ':R'
return SpaceGroup(sym)
```

OPTION 2: within sg_symbol_from_int_number()
This option is non-ideal because most will want the 'cleaner' symbol 'R-3m' instead of 'R-3m:R'
```
##### original code ######
if hexagonal:
    syms = list(filter(lambda s: s.endswith("H"), syms))
else:
    syms = list(filter(lambda s: not s.endswith("H"), syms))

##### fixed code ######
if hexagonal:
    syms = list(filter(lambda s: s.endswith("H"), syms))
else:
    syms = list(filter(lambda s: not s.endswith("H"), syms))
    syms = [sym + ':R' for sym in syms]
```

OPTION 3: change the default return of SpaceGroup
I haven't gone through enough to see where this fix would be. I do think this would be the cleanest/best option though. In concept, here's the change in functionality though:
```
### original ###
SpaceGroup('R-3m') # will return hexagonal info
### edit ###
SpaceGroup('R-3m') # will return rhomb info
```

The whole point of the hexagonal=False option is for the spacegroups that have the option between trigonal and hexagonal lattices that we pick the correct one. In the symm_ops.yaml file, the choice between rhombohedral/hexagonal only exists for 146,148,155,160,161,166,167.

**Comment by shyuep** [comment]
Thanks. Can you pls implement the fix and submit a PR? Pls include unittests catching the wrong behavior.

**Comment by jacksund** [comment]
Do you have a preference on whether I add the fix via option 1 or option 2 that I show above? sg_symbol_from_int_number() is the lower-level function, so it might be better there. But it could also have the biggest implications.
