### ISSUE TITLE
Structure.from_spacegroup() inaccurate for trigonal crystal systems

### ISSUE THREAD

**Issue by jacksund** [materialsproject/pymatgen#1802]
I apologize in advance for the long post, but I think this is a confusing topic. I wanted to give a full justification for the changes I'm suggesting!

**Summary:**
Structure.from_spacegroup() will inaccurately produce structures for the following spacegroups:
143, 144, 145, 147, 149, 150, 151, 152,153, 154, 156, 157, 158, 159, 162, 163,164, 165.
This occurs because SpaceGroup.is_compatible() requires these spacegroups to be hexagonal lattices, when the [symm_op.yaml](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/symmetry/symm_ops.yaml) only provides operations for the trigonal system. This is a bug that is introduced by issue #454, where discussion is misled by rhombohedral/trigonal/hexagonal confusion.

**Issue #454 inaccuracies:**
In the posted issue (to summarize), [blondegeek](https://github.com/blondegeek) argues that trigonal spacegroups (specifically spacegroup 165) should have hexagonal lattices. Also, [wenhaosun](https://github.com/wenhaosun) states that spacegroup 165 is trigonal. [blondegeek](https://github.com/blondegeek) then makes the final statement that spacegroup 165 is indeed tigonal crystal system but possesses a hexagonal lattice system. The result of this discussion is that all trigonal spacegroups (see list in summary above) are checked to be hexagonal in the [SpaceGroup.is_compatible()](https://github.com/materialsproject/pymatgen/blob/5a3284fd2dce70ee27e8291e6558e73beaba5164/pymatgen/symmetry/groups.py#L362) code. 
Their discussion comes close, but it is still incorrect -- leading to a logical error in the code. The confusion can actually be summarized with a quote from wikipedia: 

> Crystal systems, crystal families and lattice systems are similar but slightly different, and there is widespread confusion between them: in particular the trigonal crystal system is often confused with the rhombohedral lattice system, and the term "crystal system" is sometimes used to mean "lattice system" or "crystal family".

Space group 165 does NOT have the hexagonal lattice conventionally - it has a **rhombohedral** lattice. But since you can convert between the two, you can have crystal structures that have a hexagonal lattice with space group 165. Because you can have multiple forms of a lattice, this means the is_compatible() function should take that into account - but more that later. To state things clearly, spacegroups like 165 (and the others listed above) belong to the **trigonal crystal system** ([source](https://en.wikipedia.org/wiki/Space_group)) and the **hexagonal crystal family** ([source](https://en.wikipedia.org/wiki/Crystal_system)), but they possess a lattice that belongs to the **rhombohedral lattice system** ([source](https://en.wikipedia.org/wiki/Hexagonal_crystal_family)).
You'll see that in [this page](https://en.wikipedia.org/wiki/Hexagonal_crystal_family), the trigonal crystal system can have either a rhombohedral or hexagonal lattice system. The trigonal space groups (143-167) are a mixture of these lattice systems. Here is how the spacegroup lattices are assigned conventionally...
Rhombohedral lattices:

> 143, 144, 145, 147, 149, 150, 151, 152,153, 154, 156, 157, 158, 159, 162, 163,164, 165

Hexagonal lattices:

> 146,148,155,160,161,166,167

**Bugs & Errors in pymatgen**
Based on the discussion above, I believe the following errors in pymatgen exist:

In pymatgen.symmetry.groups module, the SpaceGroup.is_compatible() ([link](https://github.com/materialsproject/pymatgen/blob/5a3284fd2dce70ee27e8291e6558e73beaba5164/pymatgen/symmetry/groups.py#L362)) function is incorrect. The follow code should be changed:
```
### CURRENT CODE ###
        elif crys_system == "hexagonal" or (
                crys_system == "trigonal" and (
                self.symbol.endswith("H") or
                self.int_number in [143, 144, 145, 147, 149, 150, 151, 152,
                                    153, 154, 156, 157, 158, 159, 162, 163,
                                    164, 165])):

### FIXED CODE ###
        elif crys_system == "hexagonal" or (
                crys_system == "trigonal" and self.symbol.endswith("H")):
```
This is pretty much undoing the changes made in issue #454, so that issue would be reopened. What [blondegeek](https://github.com/blondegeek) should have been told is that her hexagonal lattice is not compatible with the **conventional** lattice of that spacegroup. She needs to first convert her crystal structure to the primitive cell (should give the rhombohedral) which is then compatible. A separate function can be made that does a thorough compatibility check, but as-is the is_compatible() function should only check via convention. Maybe we can add a warning to the doc-string of that function that warns the user of this issue.

Thus far, it's really just a matter of convention, but the really major error comes from the pymatgen.core.structure module. Specifically, the SpaceGroup.from_spacegroup() method will be inaccurate for trigonal crystal systems that are based on the rhombohedral lattice. This because the symmetry operations related to the spacegroups (located in [symm_ops.yaml](https://github.com/materialsproject/pymatgen/blob/5a3284fd2dce70ee27e8291e6558e73beaba5164/pymatgen/symmetry/symm_ops.yaml)) are based on the rhombohedral lattice. If you took a hexagonal lattice and applied the rhombohedral symmetry operations to it, you won't get the correct crystal structure!!! 
If someone wants to use the Structure.from_spacegroup() method, where they can choose between a rhombohedral and hexagonal lattice, then the hexagonal=True/False option needs to be added (note there is currently another bug with that option. see issue #1801). This option is only useful for spacegroups 146,148,155,160,161,166, and 167, because only those spacegroups have both the rhomb and hexagonal options available in symm_ops.yaml.

**Comment by mkhorton** [comment]
@blondegeek would you be willing to comment here, since this would re-open your #454 issue and possibly break some existing code/tests?

**Comment by jacksund** [comment]
I might have had the conventional assignment of spacegroups backwards. This would make the original code correct...
When looking at the AFlow library ([here](http://aflowlib.org/CrystalDatabase/trigonal_lattice.html))...
Hexagonal lattices:

> 143, 144, 145, 147, 149, 150, 151, 152,153, 154, 156, 157, 158, 159, 162, 163,164, 165

 Rhombohedral lattices:

> 146,148,155,160,161,166,167

I was led to believe the opposite when using another crystallography server, so I apologize for all of the confusion.
