### ISSUE TITLE
Unexpected structure.get_sorted_structure in structure to lammps data

### ISSUE THREAD

**Issue by chc273** [materialsproject/pymatgen#1812]
https://github.com/materialsproject/pymatgen/blob/47c8223dfe2ef4af6ebc273c950a72ccf038c5c6/pymatgen/io/lammps/data.py#L805

I found this behavior unexpected for some applications. 

If I want to calculate the site descriptors for a given site index in a structure using lammps, I can get wrong results since this line of code reordered the sites in the structure before outputting to lammps data. 

For example, if my structure has two sites ['S', 'Mo'], and I want to calculate local environment descriptors using lammps on the first site (S), I would always get the properties of the 'Mo' site due to the structure sort.

I had to sort my structures before using this code every time to avoid error and I wonder if this behavior can be changed.

**Comment by chc273** [comment]
Similar issues are with 

https://github.com/materialsproject/pymatgen/blob/561b4cfed1f74ede87074fae3903885b9d5c7868/pymatgen/io/lammps/data.py#L806-L807

Here the structures are rotated without the end users knowing.. This causes unexpected mismatch between force vectors calculated with lammps and the original structures' force vectors. It costed me sometime on this before as well.

**Comment by adengz** [comment]
Structure sorting can be definitely bypassed since it is only for the purpose of sanity, i.e., grouping atoms of the same element. 

However, rotation is inevitable when dealing with structures with non-orthogonal lattice. There are certain [alignment requirements](https://lammps.sandia.gov/doc/Howto_triclinic.html) when the simulation box is triclinic. And unfortunately it only takes care of conversion from structure and never converts the axis back to the original structure.

**Comment by chc273** [comment]
@adengz good that you are still around. 

For the lattice, I understand that lammps takes a specific representation of triclinic lattice, but do we really need to rotate all atoms in the cell? Line 807 specifically. 

We can just redefine the lattice but keep the coordinates right? This way the direction of force vector does not change.

**Comment by adengz** [comment]
@chc273 I think the fractional coordinates shall remain unchanged to keep the structure integrated. By constructing the rotated structure from fractional coordinates, there is no need to know the rotation. 

However, if (site) velocities are attached to structures, they need to be rotated accordingly under xyz axis. And I think this also applies to atomic forces as well..

**Comment by chc273** [comment]
@adengz thanks. My previous assumption of keeping coordinates but only change lattice is wrong.
