### ISSUE TITLE
Boltztrap2.py unit problem

### ISSUE THREAD

**Issue by adam5353** [materialsproject/pymatgen#1815]
I was using boltztrap2 module in pymatgen. I discoverd unit problem in electrical conductivity. When I checked the source, I have not found unit conversion of kS/m. I think the unit should be S/m.

**Comment by fraricci** [comment]
Let me check that.
I have a couple of edits done but not pushed yet.
Thank for reporting. Do not hesitate if you find something else.

**Comment by adam5353** [comment]
It is great to hear that. Looking forward to your edits. Thanks.

**Comment by fraricci** [comment]
I pushed a new version. 
Please have a look.
Any suggestion is welcome.
