### ISSUE TITLE
import error in pymatgen

### ISSUE THREAD

**Issue by srajpand87** [materialsproject/pymatgen#1816]
Hi,

I installed pymatgen from github (https://github.com/materialsproject/pymatgen.git) .
When  i was  trying to run some python file name GaAs.py i got an error which is as follows

File "/global/homes/s/srajpand/.conda/envs/myenv/lib/python3.8/site-packages/OPTpy-4.2.2-py3.8.egg/OPTpy/utils/response.py", line 205
    self.runscript.append("cp {0} {1}".format(origin,dest))
                                                         
 ImportError: cannot import name 'units' from 'pymatgen' (/global/homes/s/srajpand/.conda/envs/myenv/lib/python3.8/site-packages/pymatgen-2020.3.13-py3.8-linux-x86_64.egg/pymatgen/__init__.py)
 
Could you please let me know how to sort out this issue?
Thank you

Suman Raj Panday

**Comment by mkhorton** [comment]
Hi @srajpand87, I don't think this is a pymatgen issue -- it's likely you're trying to use an old script.

**Comment by srajpand87** [comment]
Thanks for the reply.
Actually i was trying whole day to sort out the issue but I couldn’t.
I am afraid to say do you mean old script is the pymatgen from the above link and I need to use the latest pymatgen 2020 3 13 not the one from the link?

**Comment by mkhorton** [comment]
I meant that the GaAs.py script might be old, it might help if you shared this?

**Comment by srajpand87** [comment]
from OPTpy import  OPTflow,Structure

kpt_l = [[4,4,4]]  # for optical only, bad practice ther are two places where this is defined :(


modules=''

tiniba_path='/global/u1/s/srajpand/panday_back_python2/tiniba-v3.2'

ncalc = len(kpt_l)

# Common arguments for the OPTpy flows.
kwargs = dict(
    modules=modules,
    dirname = './',

    # Executables:
    ABINIT='/global/u2/b/bmunozf2/abinit_cori_haswell/bin/abinit',
    RPMNS='/global/u1/s/srajpand/panday_back_python2/tiniba-v3.2/matrix_elements/rpmns',
    SET_INPUT_ALL='/global/u1/s/srajpand/panday_back_python2/tiniba-v3.2/latm/set_input_all',
    TETRA_METHOD_ALL='/global/u1/s/srajpand/panday_back_python2/tiniba-v3.2/latm/tetra_method_all',
    RKRAMER='/global/u1/s/srajpand/panday_back_python2/tiniba-v3.2/kk/rkramer',


#   Common variables:
    prefix = 'gaas',      # Root name for files required by Tiniba
#   Structure from file:
    structure=Structure.from_file('GaAs.json'),

#   Pseudopotentials:
    pseudo_dir = './',
    pseudos = ['Ga.psp8', 'As.psp8'], # order has to coinside with .json file, e.g.,:  SSGeGe or GeGeSS?

    ecut = 50.0,           # Wavefunctions cutoff energy, 60 Ha = 120 Ry= what I used in convergence in QE
    nspinor = 2,           # Numbers of spinorial components

#   Variables for density:
    ngkpt = [8,8,8],      # k-point grid for density
#    nstep = 120,  # it ignores this anyways
#    nshiftk=3,
    kshift = [[.5,.5,.5],[.5,0,0],[0,.5,0],[0,0,.5]],  # k-point shift for density, no shifts of kpoint for GeS,ok?

#   Variables for momentum matrix elements and responses:
    nband=70,      # Number of bands
    nbdbuf=2,      # Bands in buffer, skip these as are difficult to converge (see Abinit documentation).
    nval_total=28, # 20 valence bands (needs to set to all valence bands). 

#   Variables for responses:
    kgrid_response=[4,4,4],
#   Bands to include for transitions (can be less than for RPMNS)
    ncond=38,
    nval=28,   #Ge val=4, S val=4 total =10x2 =20 works
#   Response to calculate, see Doc. in responses.py
    response=21, #46 for sigma, 21 for SHG
    components=["xyz"],

    # These are the default parameters for the MPI runner.
    # Please adapt them to your needs.
    nproc = 32,
    nproc_per_node = '',
    mpirun = 'srun -c 2 --cpu_bind=cores',
    nproc_flag = '',
    nproc_per_node_flag = '',
    mpi_extra_vars='',
    )

dirnames = list()

for icalc in range(ncalc):

    kgrid_response = kpt_l[icalc]

    dirname = 'k{:0=2}'.format(icalc+1)
    dirnames.append(dirname)

    kwargs.update(
        dirname = dirname,
        kgrid_response=kgrid_response,
        )


    flow = OPTflow(**kwargs)
    flow.write()

This is the content of the file.
Thank you

**Comment by mkhorton** [comment]
Thanks for sharing @srajpand87, I would advise you talk to whoever develops `OPTflow`, I don't think this is a pymatgen issue.

**Comment by mkhorton** [comment]
Yes, it looks like the code was written against pymatgen around three years ago: https://github.com/trangel/OPTpy

You could try installing an old version of pymatgen (e.g. `4.0`) but I would advise against this since many bugs have been fixed since then. It would be better for the original script to be updated.

**Comment by srajpand87** [comment]
Thanks for the suggestion.
Okay I will contact Tonatiuh Rangel to update this script.

**Comment by srajpand87** [comment]
Hi mkhorton,
I made an inquiry with the one who wrote OPTpy and above file.
He suggested me to use an old version of pymatgen like you said to me.
I am wondering how can I get v2018.x pymatgen as i am using python 2.7 and this python only take into account v2018.x pymatgen.
Previously i was using git clone https://github.com/materialsproject/pymatgen.git  which only upload 2020 3 13 version of pymatgen.
I want to get something like git clone similar link above  to upload 2018 version of pymatgen.
Thank you
Suman

**Comment by shyuep** [comment]
Pls refer to standard python installation instructions using pip to get a specific version. Sorry, but we cannot be providing this kind of support for basic python installation questions.

**Comment by srajpand87** [comment]
Really apologized for such a naive question.
I used following commands to install conda and pip.
module load python/2.7-anaconda-4.4
conda create -n myenv
source activate myenv
conda uninstall numpy
pip install numpy==1.16.4
No error using above commands
But while trying to install pymatgen using command
pip install pymatgen==2018.2.13 gave me an error
Building wheel for pymatgen (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /global/homes/s/srajpand/.conda/envs/myenv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1gjmt1nc/pymatgen/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1gjmt1nc/pymatgen/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_mbrjwet
       cwd: /tmp/pip-install-1gjmt1nc/pymatgen/

Does it mean  not allowing me to install pymatgen 2018.2.13?

**Comment by mkhorton** [comment]
Hi @srajpand87, as @shyuep said we really can't help with this kind of issue -- I'd advise reading more about Python and Python packaging in general. Historical versions of pymatgen are available on [PyPI](https://pypi.org/project/pymatgen/#history) and via git using `git checkout`.

For this specific issue I couldn't say--you're using an old version of Python, `2.7`, which we don't support anymore since the Python community has almost exclusively moved to 3+.

More broadly, whatever calculation you're trying to run, you are likely to have some more success if you use a more recent version of whatever code you're trying to use, and study more closely the specifics of the calculation you're trying to run. Good luck!

**Comment by srajpand87** [comment]
Okay I will follow your directions and thank you.
