### ISSUE TITLE
Pourbaix diagrams: AqueousCorrection unexpected behavior re: hydrogen energy

### ISSUE THREAD

**Issue by rkingsbury** [materialsproject/pymatgen#1823]
**Describe the bug**
@JosephMontoya-TRI and I recently discovered a bug in the `AqueousCorrection` class (used by `MaterialsProjectAqueousCompatibility` and `MITProjectAqueousCompatibility`) that causes unexpected behavior when correcting the energy of aqueous H2. As a result, the hydrogen energy may vary depending on whether or not the `ComputedEntry` for H2 already has a correction applied (e.g., when downloading from MPRester).

**To Reproduce**
Below are three different ways of generating entries for Pourbaix diagram construction. These should all result in the same energy for H2, but they do not. Note that H2 should always be assigned an energy of -3.6019 eV/atom (the value in the `MPCompatibility.yaml` file.

**Method 1: Manually process MPRester entries**

```
compat = MaterialsProjectAqueousCompatibility()

with MPRester() as m:
    ion_ref_entries = m.get_entries_in_chemsys(["O", "H"])
    ion_ref_entries = compat.process_entries(ion_ref_entries)
```
(print statements omitted for clarity)
```
Entry ID 	 Correction 	 E_per_atom	Corrections
mp-632291	   -0.2112	   -3.6019	{'MP Gas Correction': 0.30189724724000033}
mp-1188177	   -0.2798	   -3.6019	{'MP Gas Correction': 1.3179495979200055}
mp-850274	   -0.2139	   -3.6019	{'MP Gas Correction': 0.2964079872400003}
```

**Method 2: Remove corrections, then manually reprocess MPRester entries**

```
compat = MaterialsProjectAqueousCompatibility()

with MPRester() as m:
    ion_ref_entries = m.get_entries_in_chemsys(["O", "H"])
    for e in ion_ref_entries:
        e.correction=0
    ion_ref_entries = compat.process_entries(ion_ref_entries)
```

```
Entry ID 	 Correction 	 E_per_atom	Corrections
mp-632291	   -0.0603	   -3.4509	{'MP Gas Correction': 0.30189724724000033, 'MP Aqueous Correction': -0.30189724724000033}
mp-1188177	   -0.1974	   -3.5195	{'MP Gas Correction': 1.3179495979200055, 'MP Aqueous Correction': -1.3179495979200055}
mp-850274	   -0.0657	   -3.4537	{'MP Gas Correction': 0.2964079872400003, 'MP Aqueous Correction': -0.2964079872400003}
```

**Method 3: compatible_only=False, then manually reprocess MPRester entries**

```
compat = MaterialsProjectAqueousCompatibility()

with MPRester() as m:
    ion_ref_entries = m.get_entries_in_chemsys(["O", "H"], compatible_only=False)
    for e in ion_ref_entries:
        e.correction=0
    ion_ref_entries = compat.process_entries(ion_ref_entries)
```

```
Entry ID 	 Correction 	 E_per_atom	Corrections
mp-632291	   -0.0603	   -3.4509	{'MP Gas Correction': 0.30189724724000033, 'MP Aqueous Correction': -0.30189724724000033}
mp-1188177	   -0.1974	   -3.5195	{'MP Gas Correction': 1.3179495979200055, 'MP Aqueous Correction': -1.3179495979200055}
mp-850274	   -0.0657	   -3.4537	{'MP Gas Correction': 0.2964079872400003, 'MP Aqueous Correction': -0.2964079872400003}
```

Method 1 produces the correct energy, while Method 2 and 3 fail. Method 3 (which parallels the implementation in `get_pourbaix_entries` is equivalent to Method 2. 

The reason Method 1 works is that the `ComputedEntry` returned by MPRester already has a non-zero energy correction. `AqueousCorrection` requires the energy of H2 to be already corrected in order to compute the correct final energy, but this is not guaranteed if you process entries "from scratch", as shown in Method 2 or set `compatible_only=False` as in Method 3.

Because of this bug, Pourbaix diagrams generated via `.get_pourbaix_entries` slightly understabilize hydrogen, which can result in hydrides disappearing from the diagrams. For example:

Method 2 /3: 

![image](https://user-images.githubusercontent.com/1908695/78951584-7debcb00-7a87-11ea-9634-1fbaba209c94.png)

vs. the more correct Method 1:

![image](https://user-images.githubusercontent.com/1908695/78951612-9d82f380-7a87-11ea-91f4-6562ece37d51.png)

**Additional context**
We are developing a fix to correct this and also to ensure that `MaterialsProjectAqueousCompatibility` is fully compatible with a forthcoming new set of energy corrections (See #1558 ).

**Comment by rkingsbury** [comment]
@JosephMontoya-TRI do you see any problem with just setting `compatible_only=True` as a temporary fix?

**Comment by rkingsbury** [comment]
@JosephMontoya-TRI as part of the longer-term solution, we are thinking of moving the `AqueousCompatibility` scheme to a standalone `Compatibility` class that doesn't require an underlying `Correction` class. That way we could start with already-corrected `ComputedEntry` (e.g., from `MaterialsProjectCompatibility`) and apply the aqueous adjustments directly in the `Compatibility` class, without having to go through the `process_entry` -> `get_correction` -> `get_corrections_dict` flow that causes this bug. See https://github.com/awvio/pymatgen/compare/master...rkingsbury:abstractcompat?expand=1. Do you have any thoughts on this approach?

**Comment by JosephMontoya-TRI** [comment]
That sounds reasonable to me, my understanding is that writing a custom process_entries method will allow you to implement the sequential logic in a more transparent way?

**Comment by rkingsbury** [comment]
> That sounds reasonable to me, my understanding is that writing a custom process_entries method will allow you to implement the sequential logic in a more transparent way?

Yes, exactly. Also, what do you think about the `compatible_only=True` vs. `False` setting in `get_pourbaix_entries` ?

**Comment by JosephMontoya-TRI** [comment]
Also the temporary fix sounds fine to me assuming it works.  It won't mess up O2 will it?

**Comment by rkingsbury** [comment]
> Also the temporary fix sounds fine to me assuming it works. It won't mess up O2 will it?

I will verify, but it shouldn't.

**Comment by rkingsbury** [comment]
Update: while #1826 will fix this bug by preventing double-counting of corrections, the pymatgen Pourbaix diagram for Na will in fact not show a hydride. This is a result of a more accurate way of fitting the hydrogen energy that we introduced with the new `MaterialsProjectAqueousCompatibility` class.

**Comment by mkhorton** [comment]
@rkingsbury sorry why is the hydride no longer present?

**Comment by rkingsbury** [comment]
> 
> 
> @rkingsbury sorry why is the hydride no longer present?

As part of the new `MaterialsProjectAqueousCompatibility` class, we recalculated the chemical potential of H2 (previously -3.60 eV/H and stored in a .yaml file). Due to an updated DFT energy of water in our database and correcting an error in the way the value was fitted before, the new chemical potentials is -4.05 eV/H. This more negative hydrogen chemical potential cases most hydrides not to be on the hull. The effect is similar to what was happening previously because of this double-counting bug.

I'll note that some systems like Li, Ca, Sr, and Ba do gain hydrides after fixing this bug. It's just that Na does not.
