### ISSUE TITLE
VoronoiNN._extract_nn_info() ValueError when calculating max_weight

### ISSUE THREAD

**Issue by CompRhys** [materialsproject/pymatgen#1825]
**Describe the bug**
Trying to generate a Structure Graph from the Voronoi Neighbours gives `ValueError: max() arg is an empty sequence` for some structures when trying to calculate max_weight in `VoronoiNN._extract_nn_info()` .  

**To Reproduce**
Minimal Code: 
```
from pymatgen.core.structure import Structure
from pymatgen.analysis import local_env
from pymatgen.analysis.graphs import StructureGraph

with open("breaking-oqmd-4866.txt", 'r') as file:
    str_ = file.read()
    crystal = Structure.from_str(str_, fmt="json")

print(crystal)
graph = StructureGraph.with_local_env_strategy(crystal, local_env.VoronoiNN())
``` 

breaking example: attatched 
[breaking-oqmd-4866.txt](https://github.com/materialsproject/pymatgen/files/4466354/breaking-oqmd-4866.txt)

**Expected behavior**
The code should return a structure graph where each nodes neighbours are its Voronoi neighbours

**Comment by mkhorton** [comment]
Hi @CompRhys , `VoronoiNN` takes a `cutoff` parameter as an optimization, but it does need to be increased with some structures. Try `VoronoiNN(cutoff=15)` and you should find it works.

I'm not ruling out an underlying improvement that could be made here, if you're inclined you could take a look at the behavior of `VoronoiNN().get_all_voronoi_polyhedra(crystal)[14]` for your example vs `VoronoiNN().get_voronoi_polyhedra(crystal, 14)`. The latter works, the former does not, suggesting that the former might be overly aggressive in its optimizations (I did not write this function, so this is just speculation from me). If you find a fix, please feel welcome to open a PR, thanks for reporting.

**Comment by CompRhys** [comment]
Okay great I will look at the code and see if I can resolve the issue. 

As a stop gap would a simple PR with a descriptive error message suggesting that users increase the cutoff if they get this exact error at this point be likely to be merged?

**Comment by mkhorton** [comment]
Yes, PRs always welcome even for things like improved warnings or docstrings – though actually in this case the code need not fail at all. Where the max() statement is, if this is an empty list it could just report no neighbours for that site rather than raising an error, so that change could be made too.

I haven’t made that change myself because my understanding of VoronoiNN (with tolerance 0) is that all sites should at least have some neighbors, which makes me suspect an underlying bug in the optimization when all sites are requested.

**Comment by CompRhys** [comment]
This is perhaps more complicated, in the minimal code example increasing the cutoff doesn't fix the issue. 

I will open a PR with the assertion to stop if it doesn't find neighbours but only to facilitate fixing the deeper issue

**Comment by mkhorton** [comment]
That's interesting, the increased tolerance seemed to solve the issue on my machine.

**Comment by CompRhys** [comment]
So I can call both `local_env.VoronoiNN().get_voronoi_polyhedra(crystal, 14)`
`local_env.VoronoiNN().get_all_voronoi_polyhedra(crystal)[14]` without errors but I get the error if I try `StructureGraph.with_local_env_strategy(crystal, local_env.VoronoiNN())`

**Comment by CompRhys** [comment]
@mkhorton I am currently looking for more edge cases and it appears to have something to do with the fact that I am converting the structures to primitive structures first (using pymatgen to do this). 

Maybe the best thing to do in the meantime is just merge a more helpful error message while I continue to look for edge cases?

**Comment by mtdunstan** [comment]
I think I am having a similar problem - I had older code using VoronoiNN.get_nn_info that I tried to use today, and it is giving an illegal instruction error. Minimal code is attached.

Do you know what I can try to do to fix this?

``
from pymatgen.ext.matproj import MPRester

from pymatgen.core.structure import Structure, Composition
from pymatgen.analysis.local_env import VoronoiNN

a = MPRester("ZbTstiE2olAnyU64")

entry = a.get_entry_by_material_id('mp-104',inc_structure='final')

s = entry.structure

vcf = VoronoiNN()

vs = vcf.get_nn_info(s, 0)
``
