### ISSUE TITLE
ComputedEntry repr / as_dict display uncorrected energy

### ISSUE THREAD

**Issue by rkingsbury** [materialsproject/pymatgen#1829]
**Describe the bug**
The `repr` and `as_dict` methods of `ComputedEntry` display the `uncorrected_energy` attribute under the `energy` key instead of the `energy` attribute (uncorrected energy plus corrections). Energies are still calculated correctly when reconstructing entries using `as_dict()` / `from_dict`, so this bug simply affects presentation. 

**To Reproduce**
See steps in the screenshot below.
![image](https://user-images.githubusercontent.com/1908695/79474877-d2c59f00-7fbb-11ea-8aa0-70d6d60e863c.png)

**Expected behavior**
Either display the `energy` attribute with the energy key or rename the key to `uncorrected_energy`.

**Additional context**
I have a suspicion that this bug was introduced when we refactored the `Entry` class (https://github.com/materialsproject/pymatgen/pull/1780), though I could be wrong and it may be intended behavior. If we do not already have one, I think we should add a test to enforce the intended behavior here.

**Comment by rkingsbury** [comment]
@ayushsgupta can you investigate?

**Comment by rkingsbury** [comment]
@mkhorton @shyamd intended behavior would be to show the corrected energy under the 'Energy' key at least in the `repr`, right?

**Comment by rkingsbury** [comment]
I suppose it makes sense to have uncorrected energy in `as_dict`, because that's what one would use to initialize a new entry with `from_dict`, but in the case of `ComputedEntry` we should probably explicitly call it `uncorrected_energy` for clarity. In the `repr`, I think it would be nice to list both `energy` and `uncorrected_energy` for clarity. Thoughts?

**Comment by mkhorton** [comment]
I agree that it's not obvious if it's corrected or uncorrected energy currently, `uncorrected_energy` is better, but would break backwards compatibility. Adding a `corrected_energy` key would be nice but would be including duplicate information which is not ideal.

So, verdict: keep `as_dict()` as it is, but improve `__repr__()` to make it less ambiguous (the only job of `__repr__` is to show something useful about the underlying data, it's really `__str__()` we should be concerned about, but nevertheless people do print the object in Jupyter like in your screenshot so having an unambiguous `__repr__` would be a good thing imo).

**Comment by rkingsbury** [comment]
Here is what I am thinking. This will be part of #1826 .

```
ComputedEntry mp-13 - Fe1
Uncorrected Energy = -8.4598
Correction = 0.0000
Final Energy = -8.4598
Energy Adjustments:
  None
Parameters:
  run_type = GGA
  is_hubbard = False
  pseudo_potential = {'functional': 'PBE', 'labels': ['Fe_pv'], 'pot_type': 'paw'}
  hubbards = {}
  potcar_symbols = ['PBE Fe_pv']
  oxide_type = None
Data:
  oxide_type = None
```

**Comment by rkingsbury** [comment]
and an example with corrections:

```
ComputedEntry mp-626570 - Fe16 H16 O32
Uncorrected Energy = -375.8532
Correction = -66.2013
Final Energy = -442.0545
Energy Adjustments:
  MP Anion Correction: -22.473 eV (-0.351 eV/atom)
  MP Advanced Correction: -43.728 eV (-0.683 eV/atom)
Parameters:
  run_type = GGA+U
  is_hubbard = True
  pseudo_potential = {'functional': 'PBE', 'labels': ['Fe_pv', 'H', 'O'], 'pot_type': 'paw'}
  hubbards = {'Fe': 5.3, 'H': 0.0, 'O': 0.0}
  potcar_symbols = ['PBE Fe_pv', 'PBE H', 'PBE O']
  oxide_type = hydroxide
Data:
  oxide_type = hydroxide
```

**Comment by mkhorton** [comment]
This looks a lot more legible to me :-)

**Comment by rkingsbury** [comment]
added a little extra alignment, reduced composition, and energies in both eV and eV/atom

```
ComputedEntry mp-626570  - Fe16 H16 O32 (FeHO2)
Uncorrected Energy       = -375.8532 eV (-5.8727  eV/atom)
Correction               =  -66.2013 eV (-1.0344  eV/atom)
Final Energy             = -442.0545 eV (-6.9071  eV/atom)
Energy Adjustments:
  MP Anion Correction    : -22.4733  eV (-0.3511  eV/atom)
  MP Advanced Correction : -43.7280  eV (-0.6833  eV/atom)
Parameters:
  run_type = GGA+U
  is_hubbard = True
  pseudo_potential = {'functional': 'PBE', 'labels': ['Fe_pv', 'H', 'O'], 'pot_type': 'paw'}
  hubbards = {'Fe': 5.3, 'H': 0.0, 'O': 0.0}
  potcar_symbols = ['PBE Fe_pv', 'PBE H', 'PBE O']
  oxide_type = hydroxide
Data:
  oxide_type = hydroxide
```

**Comment by shyuep** [comment]
Let me weigh in here. Having repr to return the uncorrected energy is fine. But not changing the dict representation. One has to remember that "corrections" or any concept therefore, is fundamentally an artificial construction of MP and its correction scheme. Hypothetically, one need not even store it as a correction and simply set it as PDEntry.energy = PDEntry.energy + correction with compatibility. The only reason why we store the correction within COmputedEntry is for reasons of debugging.

So the functional API of ComputedEntry is inherited from PDEntry - the most basic and fundamental concept of a Entry that does not require any correction whatsoever. The only reason why the *internal* representation uses `uncorrected_energy` is to enable the energy to be a property computed on the fly. That way, ComputedEntry and PDEntries can be mixed and transparently used. 

The above repr looks ok to me. But instead of "Uncorrected Energy' on the second line, I would suggest Energy (Uncorrected).

**Comment by rkingsbury** [comment]
Thanks for the input, @shyuep . How about this?

```
ComputedEntry mp-626570  - Fe16 H16 O32 (FeHO2)
Energy (Uncorrected)     = -375.8532 eV (-5.8727  eV/atom)
Correction               =  -66.2013 eV (-1.0344  eV/atom)
Energy (Final)           = -442.0545 eV (-6.9071  eV/atom)
Energy Adjustments:
  MP Anion Correction    : -22.4733  eV (-0.3511  eV/atom)
  MP Advanced Correction : -43.7280  eV (-0.6833  eV/atom)
Parameters:
  run_type = GGA+U
  is_hubbard = True
  pseudo_potential = {'functional': 'PBE', 'labels': ['Fe_pv', 'H', 'O'], 'pot_type': 'paw'}
  hubbards = {'Fe': 5.3, 'H': 0.0, 'O': 0.0}
  potcar_symbols = ['PBE Fe_pv', 'PBE H', 'PBE O']
  oxide_type = hydroxide
Data:
  oxide_type = hydroxide
```

**Comment by shyuep** [comment]
This is fine with me. Though you can probably dump the Parameters and Data (which are both dicts) in YAML like form to make it slightly easier to read. But this is just me nit-picking.
