### ISSUE TITLE
potcar symbol mapping not working

### ISSUE THREAD

**Issue by matk86** [materialsproject/pymatgen#183]
when symbol mapping dictionary is provided, the data attribute of Potcarsingle class does not have the raw potcar data.

**Comment by shyuep** [comment]
As far as I can tell, this works perfectly fine. Can you give an example of where it fails?

**Comment by matk86** [comment]
when 'sym_potcar_map' is provided, the method 'set_symbols' of class Potcar appends potcar singles objects with its data variable set to 'sym_potcar_map[el]'.
When  'sym_potcar_map' is not given, it actually goes to the potcar files folder and reads the corresponding potcar file into the 'data' variable

**Comment by shyuep** [comment]
If you provide sym_potcar_map, then you need to provide the actual data in the sym_potcar_map. Otherwse, you shouldn't set it. This is so taht people can arbitarily set the raw data for the POTCAR. It is not meant for general usage.

**Comment by matk86** [comment]
ok. thank you
