### ISSUE TITLE
Cif Parser improvement

### ISSUE THREAD

**Issue by ramfrey** [materialsproject/pymatgen#1830]
**Is your feature request related to a problem? Please describe.**
I'm working with text files that contain multiple cif files (always 20) and would like to parse them with the Cif Parser, see example file. [1.txt](https://github.com/materialsproject/pymatgen/files/4494649/1.txt)
However, reading them into a dict or getting the structures yields different results:
```
for_struc=mg.io.cif.CifParser(r'1.cif',)
for_dict=mg.io.cif.CifParser(r'1.cif').as_dict()
struc=for_struc.get_structures(primitive=False)
print(len(struc))
print(len(list(for_dict.values())))
```
result:
19
20

also if I get the structures directly, I lose information e.g. the keys of the dict are the identifier numbers for each cif file, which i can't correlate directly to the structure anymore because the numbers are different.

**Describe the solution you'd like**
Either more precise error messages, saying which part of the (multiple)cif file was faulty, or a function that allows to create structures from "cif-dictionaries" as obtained like so: `for_dict=mg.io.cif.CifParser(r'1.cif').as_dict() `

**Comment by shyuep** [comment]
I added an error message to detail unparseable structures. In this case, 18th structure in the file was problematic because there were essentially no atoms defined. You can check that for yourself by opening the CIF file and eyeballing it. 

Pymatgen's CIF parser is reasonably robust against a lot of errors. But it cannot guess structures when no atoms are defined.

**Comment by ramfrey** [comment]
Thanks for the quick response. This already helps. A step further, it would be nice to have an option to read in from such a "multiple" cif file and directly resave the individual cif files (even the one with errors).

**Comment by shyuep** [comment]
To split a CIF, I don’t think you need pymatgen for that. You can easily use a Unix tool to do it or a simple few liner python script.
