### ISSUE TITLE
nullability-completeness related pymatgen build errors on Mac OS X

### ISSUE THREAD

**Issue by paulfons** [materialsproject/pymatgen#1833]
**Describe the bug**
pymatgen update fails on OS X 10.15.4 and more importantly Xcode version 11.4.1 (11E503a)

**To Reproduce**
pip3 install --upgrade pymatgen

The full output is listed below:
[error.txt](https://github.com/materialsproject/pymatgen/files/4508677/error.txt)

The error seems to relate to the flag -Wnullability-completeness from what I can gather from google-based searches. 

/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:93:16: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullabl
e, or _Null_unspecified) [-Wnullability-completeness]

**Expected behavior**
An error free install update.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac (Catalina) 10.15.4 note Xcode version is 11.4.1 (11E503a)
 - Version [e.g. 2019.9.16]

**Additional context**

**Comment by shyuep** [comment]
Please use conda to install pymatgen.

**Comment by mkhorton** [comment]
Hi @paulfons, I can't reproduce -- I'm also on latest macOS (10.15.4) and Xcode (11.4), however I'll keep an eye on this.

@shyuep is correct that the conda install is more reliable, since there are many more pre-built binary wheels available across platforms.
