### ISSUE TITLE
CifParser distorts structure

### ISSUE THREAD

**Issue by peterschindler** [materialsproject/pymatgen#1839]
Recently came across a strange bug when parsing a primitive cell (cif downloaded from MP). Parsing the cif with CifParser and then immediately exporting it again as a new cif (without any other operations in between) completely changed/distorted the unit cell and atomic positions.
```Python
from pymatgen.io.cif import CifParser
file = "InI_mp-23202_primitive.cif"
structure = CifParser(file).get_structures()[0]
structure.to(filename="structure.cif")
```
See attached input and output cif files. Done with most recent Pymatgen version.

Not sure what could cause this, as the input cif looks normal to me and it's not a specifically weird structure. The lattice matrix of the imported structure seems already strange because the second-row vector `structure.lattice.matrix[1]` appears to be aligned with the z-direction (which normally should be the third-row vector).

Thank you for looking into it!

[cifs.zip](https://github.com/materialsproject/pymatgen/files/4555612/cifs.zip)

**Comment by shyuep** [comment]
In the call to get_structures, set primitive=False. When primitive is True (the default), the code performs a search for primitive lattice vectors and that can change the setting.

**Comment by peterschindler** [comment]
Oh, I wasn't aware of that tag. Thank you for the quick solution @shyuep !

**Comment by mkhorton** [comment]
Have verified this seems to be a bug in CifParser, though not in get_primitive ... potentially serious, am investigating.

**Comment by mkhorton** [comment]
Actually, I take this back, it seems fine, just unusual given the setting change. We _are_ trying to track down a potentially serious symmetrization/structure matching bug though, and thought this might have been a candidate, but evidently not.
