### ISSUE TITLE
Comment in KPOINTS generator

### ISSUE THREAD

**Issue by arosen93** [materialsproject/pymatgen#1841]
**Describe the bug**
When using [`pymatgen.io.inputs.vasp.Kpoints.automatic_density()`](https://github.com/materialsproject/pymatgen/blob/v2020.4.29/pymatgen/io/vasp/inputs.py#L1237) (and likely related functions), the [comment line](https://github.com/materialsproject/pymatgen/blob/v2020.4.29/pymatgen/io/vasp/inputs.py#L1256) is

```python
comment = "pymatgen v%s with grid density = %.0f / atom" % (__version__, kppa)
```

I am having some self-doubt on whether this is _strictly speaking_ the best way to write this, specifically the "/ atom". For instance, if I set `kppa=1000`, it writes out "... grid density = 1000 / atom". Is that better described 1000/number of atoms, as written out in the [Materials Project documentation](https://materialsproject.org/docs/calculations)? Should it instead be written as 1000 per reciprocal atom, as in [the JHU module](https://pymatgen.org/pymatgen.ext.jhu.html)? 1000/per atom always confuses me, but I see that kind of phrasing in [the VASP documentation](https://cms.mpi.univie.ac.at/vasp/vasp/Number_k_points_method_smearing.html). Regardless of the best way to do this, my question really boils down to; "is 1000/atom" the ideal way to phrase this, and is it strictly accurate? A user may see that and think "so, if I increase the number of atoms, the number of k-points goes up," which of course is the opposite.

I know this is me just being pedantic and isn't really a bug, but I thought it'd be worth bringing up here.

**Comment by mkhorton** [comment]
Hi Andrew; agreed, I think this could be better phrased. A pull request is welcome if you'd like to change it!

As a general comment, a lot of the default MP sets are kept as they are for historical, backwards compatibility reasons, including how we determine k-points. For our newer sets (e.g. SCAN) we're looking at KSPACING or one of the generalized schemes (e.g. the Mueller/JHU scheme) anyway. Regardless, the comments for the kppa scheme should be accurate and unambiguous, and I agree the current comment string is misleading.

**Comment by arosen93** [comment]
Alright, I'll make a PR. I just wanted to make sure I wasn't misunderstanding it!

Thanks for the comment about the k-point generation. That's useful to know. I had been using `automatic_density()` for a while now, mainly drawing parallels with the original MP sets but have been meaning to switch over to the Mueller/JHU scheme myself. I just have to do some convergence checks before I feel comfortable porting my workflows over, which I keep putting off...

**Comment by mkhorton** [comment]
Yes, I've also been running convergence tests on the Mueller scheme, not 100% comfortable yet – I had some surprising results in the first batch, which makes me suspect an error on my part. There's a similar code from Gus Hart et al too https://github.com/msg-byu/kgridGen, but we don't have an interface to that. Opinions on these matters definitely welcome!
