### ISSUE TITLE
Reference doesn't exist

### ISSUE THREAD

**Issue by JabinHao** [materialsproject/pymatgen#1843]
I want to know more about the Ewald  electrostatic energy, but when I try to open the reference in 
```python
pymatgen.analysis.ewald module
class EwaldSummation(structure, real_space_cut=None, recip_space_cut=None, eta=None, acc_factor=12.0, w=0.7071067811865475, compute_forces=False)
Bases: object

Calculates the electrostatic energy of a periodic array of charges using the Ewald technique. Ref: http://www.ee.duke.edu/~ayt/ewaldpaper/ewaldpaper.html

This matrix can be used to do fast calculations of Ewald sums after species removal.

E = E_recip + E_real + E_point

Atomic units used in the code, then converted to eV.
```
the URL
>Ref: http://www.ee.duke.edu/~ayt/ewaldpaper/ewaldpaper.html

doesn't exist. I guess they have changed their site to other adress, Could you please provide the correct URL?

Thanks a lot.

**Comment by mkhorton** [comment]
Hi JabinHao, there are many textbook references available on Ewald summation. The specific one linked from our documentation was:

*Ewald summation techniques in perspective: a survey* by Abdulnour Y. Toukmaji and John A. Board Jr., doi: 10.1016/0010-4655(96)00016-1

A pdf seems to be available here: https://math.la.asu.edu/~jtaylor/teaching/Fall2010/APM530/papers/Toukmaji96.pdf

I'll update the docstring to reference this paper specifically, thanks for letting us know the URL was broken!
