### ISSUE TITLE
pymatgen.analysis.interface_reactions InterfacialReactivity issue

### ISSUE THREAD

**Issue by roterojama** [materialsproject/pymatgen#1845]
**Describe the bug**
When using the newest version of pymatgen (v2020.4.29) the InterfacialReactivity() function produces an error. Two seperate errors can be generated depeding on whether the argument "include_no_mixing_energy=" is set to True or False. However this was not the case before the newest version of pymatgen. I changed the package version to e.g. pymatgen=2019.2.28 and everything works fine.

**To Reproduce**
Just run the example code from the binder hub. Its the "2019-03-11-Interface Reactions.ipynb" notebook. Here you have the code as a txt file: [Example-file.txt](https://github.com/materialsproject/pymatgen/files/4599647/Example-file.txt) (I changed it from a .py file. I hope that didnt introduce any Errors).

**Expected behavior**
Can be seen when running the notebook on the binder hub (binder hub: http://matgenb.materialsvirtuallab.org/). There it works fine.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home, OS build: 18362.778
 - Version 1903
- Im running the Spyder 4.1.2 IDE with the Anaconda Navigator for the environement.

**Comment by mkhorton** [comment]
Thanks for the report @roterojama. Can you paste in the two separate error messages you see?

**Comment by roterojama** [comment]
@mkhorton I reinstalled the newest version of pymatgen to reproduce the error messages and just couldn't. Im very sorry about this. I can't explain what changed. Thus I guess the issue is resolved. Good day to you.

**Comment by mkhorton** [comment]
No problem!
