### ISSUE TITLE
Can't instantiate numpy array of Composition objects

### ISSUE THREAD

**Issue by KirbyBroderick** [materialsproject/pymatgen#1848]
I'm on pymatgen version 2020.1.28 in JupyterLab, and I'm trying to instantiate a numpy array of Composition objects.

`import numpy as np
np.array([pymatgen.core.Composition('Ru')])` and several variants thereof result in an error 

`TypeError: Invalid key 0, <class 'int'> for Composition
ValueError exception:
No element with this atomic number 0`

I can, however, get this array by going through a pandas DataFrame:

`pd.DataFrame([[pymatgen.core.Composition('Ru')]]).values[0]`

I was hoping the direct way would work.

**Comment by shyuep** [comment]
I don't think a numpy array is a good container for a Composition object. The Composition object is in fact a dict-like object, which is iterable.
You can use lists if you wish, or pandas DataFrames, which are supposed to work with heterogenous objects works too. In general,  numpy arrays are for numeric types.
