### ISSUE TITLE
Negative electrostatic energy for charged cells

### ISSUE THREAD

**Issue by lbluque** [materialsproject/pymatgen#1849]
**Describe the bug**
I'm getting nonphysical negative values for the electrostatic energy of charged cells using `EwaldSummation`.

Seems the `_charged_cell_energy` needs to be adjusted by a minus sign?

https://github.com/materialsproject/pymatgen/blob/72d336d2d17ac140058fdcb74eb3336125bb12b7/pymatgen/analysis/ewald.py#L114

**Comment by shyuep** [comment]
I don't think that is correct. A charged cell has a background charge of the opposite charge. That results in a negative electrostatic energy.

**Comment by lbluque** [comment]
Ah, I see now. It is the energy of the structure + the compensating background. Thanks for the clarification @shyuep. 

I think the docstrings could be made more explicit then. Stating that the result for charged systems. Additionally there is a URL in there that does not work anymore, and I believe the actual paper it refers does not treat charged systems at all. I would suggest this as an additional reference:

- R. M. Martin, Ed., in Electronic Structure: Basic Theory and Practical Methods (Cambridge University Press, Cambridge, 2004; (https://www.cambridge.org/core/books/electronic-structure/coulomb-interactions-in-extended-systems/51B0E2F27A831B78BCEFA1444299E92B) pp. 499–511.

**Comment by mkhorton** [comment]
I updated the reference in the code to the original source for the old URL.

**Comment by lbluque** [comment]
Yup that's the one I also assumed the old URL referred to.
