### ISSUE TITLE
any function to get site-specific xas from MP?

### ISSUE THREAD

**Issue by davidcn21** [materialsproject/pymatgen#1851]
I've been using "get_xas_data" to read the site-average XAS for a given adsorption element. Just curious if there is a function to read the site-specific XAS data? thanks!

**Comment by mkhorton** [comment]
Hi @davidcn21, we're currently developing a new API, and intend to add a site-specific API route for this. I'll update this thread when we have a public beta available. If you send us your email address, we may be able to share private access earlier if this is important to your research. My email is mkhorton@lbl.gov, or you can contact feedback@materialsproject.org.
