### ISSUE TITLE
Option of plotter class to remove the grid lines on the background.

### ISSUE THREAD

**Issue by hongyi-zhao** [materialsproject/pymatgen#1852]
Hi,

The pymatgen plotter class uses grid lines on the background in default. I try to remove the grid lines, say, for the example below:

from matplotlib import pyplot as plt
from pymatgen.electronic_structure.plotter import BSDOSPlotter
from pymatgen.ext.matproj import MPRester

```
a = MPRester()
bs = a.get_bandstructure_by_material_id('mp-19009')
dos = a.get_dos_by_material_id('mp-19009')
bsdosplot = BSDOSPlotter(
    bs_projection="elements",
    dos_projection="elements",
    vb_energy_range=11,
    cb_energy_range=10,
    # egrid_interval=2
)
plt = bsdosplot.get_plot(bs, dos=dos)
plt.subplots_adjust(wspace=0)
fig = plt.gcf()
```

Germain Salvato Vallverdu < germain.vallverdu @ univ - pau.fr > told me the following codes to do the trick by adding them at the end of the above example:

```
all_axes = fig.get_axes()
for ax in all_axes:
    ax.grid(False)
```

But, I want to know whether there is an option of this pymatgen class for me to achieve the same aim?

Regards,
HY

**Comment by shyuep** [comment]
No there is no option. You can just adjust the grid yourself using the code given by @gVallverdu . In general, there are an infinite variety of customizations for plots. There is no way we can support all of them.

**Comment by gVallverdu** [comment]
Hi
In case somebody look for an answer, hereafter is the way to remove the grid. You need first to get back the figure object.

```py
api = MPRester(api_key="XXX")
bs = api.get_bandstructure_by_material_id('mp-XYZT')
dos = api.get_dos_by_material_id('mp-XYZT')
bsdosplot = BSDOSPlotter(
   bs_projection="elements",
   dos_projection="elements",
   vb_energy_range=11,
   cb_energy_range=10,
)
plt = bsdosplot.get_plot(bs, dos=dos)
plt.subplots_adjust(wspace = 0)
fig = plt.gcf()
all_axes = fig.get_axes()
for ax in all_axes:
    ax.grid(False)
```

From the `all_axes` array you can show/hide grids on one specific axes or do whatever you want on that axes.

![image](https://user-images.githubusercontent.com/5417018/82874888-f3780180-9f36-11ea-93bc-13e7ab170f06.png)

**Comment by hongyi-zhao** [comment]
@gVallverdu Thanks for your notes. 
Another issue: How to add the vertical lines on the plot at each high symmetry points?

Reards
