### ISSUE TITLE
Structure.get_neighbors returning reference site as neighbor (only for image sites)

### ISSUE THREAD

**Issue by santiama** [materialsproject/pymatgen#186]
Hello this is a rather small bug and it hasnt been problematic to deal with, but I figured it should be known for future releases. In structure.get_neighbors( site, rmax, index), when a site is passed in which does not belong to the unit cell and is an image, it will return the neighbors as well as the site itself. 

For example, in GaAs (tetrahedral coordination):

In [38]: struct
Out[38]:
Structure Summary
Lattice
    abc : 3.9977696087943837 3.9977696087943837 3.9977696087943837
 angles : 59.999999999999993 60.000000000000007 60.000000000000007
 volume : 45.179174211538246
      A : -1.7309464020848477e-16 2.8268499999999999 2.8268499999999999
      B : 2.8268499999999999 0.0 2.8268499999999999
      C : 2.8268499999999999 2.8268499999999999 3.4618928041696953e-16
PeriodicSite: Ga3+ (0.0000, 0.0000, 0.0000) [0.0000, 0.0000, 0.0000]
PeriodicSite: As3- (1.4134, 1.4134, 1.4134) [0.2500, 0.2500, 0.2500]

In [39]: other_site
Out[39]: PeriodicSite: As (1.4134, -1.4134, -1.4134) [-0.7500, 0.2500, 0.2500]

In [40]: struct.get_neighbors(other_site,2.5,True)
Out[40]:
[(PeriodicSite: Ga3+ (0.0000, -2.8268, -2.8268) [-1.0000, 0.0000, 0.0000],
  2.4481239126880401,
  0),
 (PeriodicSite: Ga3+ (2.8268, 0.0000, -2.8268) [-1.0000, 0.0000, 1.0000],
  2.448123912688041,
  0),
 (PeriodicSite: Ga3+ (2.8268, -2.8268, 0.0000) [-1.0000, 1.0000, 0.0000],
  2.4481239126880396,
  0),
 (PeriodicSite: Ga3+ (0.0000, 0.0000, 0.0000) [0.0000, 0.0000, 0.0000],
  2.4481239126880401,
  0),
 (PeriodicSite: As3- (1.4134, -1.4134, -1.4134) [-0.7500, 0.2500, 0.2500],
  2.2204460492503131e-16,
  1)]

So the last site returned in that list should not be there. The fact that the distance is ~0 agrees. 

Thanks

**Comment by shyuep** [comment]
This is not a bug I think. Based on your output in line 39, I think you manually created the "other_site"? That site is As, not As3-. Pymatgen distinguishes between As3- and As as different species. That will make it such that the last site with As3- is a neighbor within a radius of 2.5 from the site you entered.
