### ISSUE TITLE
Restore structures from their pymatgen __str__ representation

### ISSUE THREAD

**Issue by CompRhys** [materialsproject/pymatgen#1862]
`Structure` has a str representation defined below that can be written to a file however I can't find an easy way to restore a `Structure` from that string, is there one? it doesn't appear to be an option when using `Stucture.from_str()` 

The need for such functionality arises when restoring a dataframe of structures that has been saved in a csv format

### Example of str
> Reduced Formula: CrNi3
abc   :   3.501092   3.501092   4.348644
angles: 113.737682 113.737682  90.000000
Sites (4)
  \#  SP       a     b     c    magmom
\---  ----  ----  ----  ----  --------
  0  Cr    0     0      0       1.484
  1  Ni    0.5   0.5   -0      -0.008
  2  Ni    0.25  0.75   0.5    -0.057
  3  Ni    0.75  0.25   0.5    -0.057

https://github.com/materialsproject/pymatgen/blob/72d336d2d17ac140058fdcb74eb3336125bb12b7/pymatgen/core/structure.py#L2014

**Comment by shyuep** [comment]
While we can certainly implement a parser for the `Structure.__str__`, the general preference is to use one of the other formats for storing structures, e.g., CIF, POSCAR or json. These are well-established representations that people have been using widely. The structure string is more for the purposes of readability and a quick glance at the basic information. I am not sure that we'd want to introduce a new representation for these purposes.

@mkhorton Views?

If we are really going to introduce a new format, I'd rather it be something simple and structured. E.g., we use YAML for the `__str__` and rely on the yaml parser to get it back. This will have the added feature that we can easily transform to json if needed. I do not really want to be responsible for maintaining a new format for structures....

**Comment by CompRhys** [comment]
One issue to highlight is that the co-ordinates are truncated to 3dp in this str as opposed to 6dp in a CIF. This alone would make this a bad way to store structures but the functionality may still be helpful?

**Comment by shyuep** [comment]
Yes, the number of significant figures can be changed of course....

**Comment by mkhorton** [comment]
Note that the `str` representation is a little lossy too, it may not show site properties sufficiently etc. and will be very difficult to write a general parser for since site properties can take many compound data types.
