### ISSUE TITLE
Bug: Finding nn distances in the pymatgen_diffusion package

### ISSUE THREAD

**Issue by chemist29** [materialsproject/pymatgen#1863]
**Describe the bug**
Hello Pymatgen Dev,
There appears to be an error in the pymatgen_diffusion package. Exactly it is finding nn distances with the pymatgen_diffusion package.  That has not been updated in a long time and it appears to be broken. 
**To Reproduce**
Unzip file
1. Command is python neb_end_member_setup Na2O.cif
2. In diffusing species, enter Na
3. You should see error, attached is my output; might have to make some paths work as per your environment. 
[neb_end_member_setup.zip](https://github.com/materialsproject/pymatgen/files/4732787/neb_end_member_setup.zip)

![image](https://user-images.githubusercontent.com/45610381/83810871-75c29d00-a67e-11ea-9858-8104934c9317.png)

**Expected behavior**
The line, 
cubic=cube(min_length=10,min_atoms=50, max_atoms=150) 
Should make a cubic supercell that is at least 10 Angstrom wide with between 50 and 150 atoms

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 4.19.0-6-amd64

**Comment by shyuep** [comment]
Pls make sure ou have the latest pymatgen and pymatgen-diffusion packages. Also, for pymatgen-diffusion, pls post on the Github issues of that package.
