### ISSUE TITLE
Illegal instruction error when running VoronoiNN.get_nn_info()

### ISSUE THREAD

**Issue by mtdunstan** [materialsproject/pymatgen#1865]
I had older code using VoronoiNN.get_nn_info on structures that I tried to use today, and it is giving an illegal instruction error. Minimal code is below. Normally it should produce substructural information for each site in the structure.

Do you know what I can try to do to fix this?

```
from pymatgen.ext.matproj import MPRester

from pymatgen.core.structure import Structure, Composition
from pymatgen.analysis.local_env import VoronoiNN

a = MPRester("ZbTstiE2olAnyU64")

entry = a.get_entry_by_material_id('mp-104',inc_structure='final')

s = entry.structure

vcf = VoronoiNN()

vs = vcf.get_nn_info(s, 0)
```

Desktop:
 - OS: Mac 10.12.6 (but running on University cluster)
 - Version 2020.4.29

**Comment by shyuep** [comment]
Please install using pip install the latest version of pymatgen.

**Comment by mkhorton** [comment]
Hi @mtdunstan , I can't reproduce this -- note that VoronoiNN relies on qhull integrated into scipy, try upgrading your scipy and/or your Python version also.
