### ISSUE TITLE
How to use jimage to compute distances ?

### ISSUE THREAD

**Issue by gVallverdu** [materialsproject/pymatgen#187]
Hello,
I would like to understand the image index which is returned by get_neighbors methods doing 

    s.get_neighbors(site, 3., include_index=True)

For example, I got

    [(PeriodicSite: O (-3.0702, 1.4045, 3.7466) [0.3650, 0.1350, 0.7720],
      2.0976135752472325,
      8),
     (PeriodicSite: O (-5.7897, 2.8090, 3.7466) [0.8650, 0.1350, 0.7720],
      2.3069461858444189,
      9),
     (PeriodicSite: O (-3.0702, 4.2135, 3.7466) [0.8650, 0.6350, 0.7720],
      2.0976135752472329,
      10),
     (PeriodicSite: O (-2.0058, 2.8090, 1.1065) [0.6350, 0.3650, 0.2280],
      2.3069461858444189,
      12),
     (PeriodicSite: O (-4.7253, 4.2135, 1.1065) [1.1350, 0.3650, 0.2280],
      2.097613575247232,
      13),
      (PeriodicSite: O (-4.7253, 1.4045, 1.1065) [0.6350, -0.1350, 0.2280],
      2.0976135752472325,
      15)]

How can I use these last numbers (8, 9, 10, 12, 13, 15) ? For example, item 1 is inside the cell

    PeriodicSite: O (-3.0702, 1.4045, 3.7466) [0.3650, 0.1350, 0.7720]

Why the image_index is 8 ?

Acutally, what I would like to do exactly is to compute distances between all this O neighbors. But I need to know the periodic image of the atom which is in the list.

Thanks

**Comment by shyuep** [comment]
The jimage is not returned in get_neighbors. The index returned just simply tells you that the first NN site is O with a distance of 2.098 and corresponds to site # 8 in the structure. The distance already accounts for PBC, so you don't need to take that into account anymore.

If you really want to know what image, you do site.distance_and_image(other_site). E.g., your other site would be the O atom in this case. What is returned is then the closest distance as well as the image vector taht you need to add to the other_site's fractional coordinates to get the closest atom. 

BTW, for clarifications and questions, pls post them on the pymatgen Google Groups page. The Github issues is meant for bug reports and feature requests only. Thanks.

**Comment by gVallverdu** [comment]
Thank you and sorry for the bad place of the question.
Germain

2015-02-17 18:42 GMT+01:00 Shyue Ping Ong <notifications@github.com>:

> The jimage is not returned in get_neighbors. The index returned just
> simply tells you that the first NN site is O with a distance of 2.098 and
> corresponds to site # 8 in the structure. The distance already accounts for
> PBC, so you don't need to take that into account anymore.
>
> If you really want to know what image, you do
> site.distance_and_image(other_site). E.g., your other site would be the O
> atom in this case. What is returned is then the closest distance as well as
> the image vector taht you need to add to the other_site's fractional
> coordinates to get the closest atom.
>
> BTW, for clarifications and questions, pls post them on the pymatgen
> Google Groups page. The Github issues is meant for bug reports and feature
> requests only. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/materialsproject/pymatgen/issues/187#issuecomment-74713392>
> .
>



-- 
*Germain Salvato Vallverdu*
*PagePerso : http://gvallver.perso.univ-pau.fr
<http://gvallver.perso.univ-pau.fr>*
*Tel : 06 88 59 08 87*
