### ISSUE TITLE
Link to Bader analysis code no longer working

### ISSUE THREAD

**Issue by ayushsgupta** [materialsproject/pymatgen#1874]
**Describe the bug**
For the [Bader caller module](https://pymatgen.org/pymatgen.command_line.bader_caller.html) in the docs, the link to download the original fortran code for the Bader analysis is broken. The link should be http://theory.cm.utexas.edu/henkelman/code/bader/. Not sure how to fix (edit docs or docs_rst?).

**Comment by mkhorton** [comment]
Edit to docs_rst, thanks!
