### ISSUE TITLE
Possible Potcar hash changes in new pymatgen versions

### ISSUE THREAD

**Issue by chc273** [materialsproject/pymatgen#1884]
**Describe the bug**

I was trying to generate vasp input sets for a Na-containing system using io.vasp.sets.MPRelaxSet. However, it seems that the `Na_pv` potcar failed the potcar check. 

I then go to my vasp potcar directory, `VASP_PSP/POT_GGA_PAW_PBE`, and run the following codes

```
from pymatgen.io.vasp.inputs import PotcarSingle
from glob import glob
for pot_file in glob('*.gz'):
    p = PotcarSingle.from_file(i)
```

It gives me a long list of warnings like the following. 

```
pymatgen/pymatgen/io/vasp/inputs.py:1853: BadPotcarWarning: POTCAR data with symbol Na_pv does not match any VASP                          POTCAR known to pymatgen. We advise verifying the                          integrity of your POTCAR files.
  BadPotcarWarning)
```

If I change pymatgen version to an earlier version, for example, `pymatgen-2019.5.8`. There is no such problem. I wonder if this is expected. I cannot see why the potcar is wrong, since it is from VASP distribution..

**Comment by mkhorton** [comment]
Hi Chi. I agree that it's unlikely it's a "bad" POTCAR -- in fact, I've recently changed this warning in master to be `UnknownPotcarWarning` instead, so as not to alarm people. I suspect the database of potcar hashes distributed with pymatgen is simply incomplete, we did use the latest potcars to generate them but perhaps VASP has released an update, I'll check.

**Comment by mkhorton** [comment]
If interested, here is the current list of [file hashes (checksums of the file itself)](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/io/vasp/vasp_potcar_file_hashes.json) and ["pymatgen hashes"( hashes of the content of the potcar)](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/io/vasp/vasp_potcar_pymatgen_hashes.json), so you could check if your Na_pv hash is already included in one of those, it could be a logic bug.

**Comment by chc273** [comment]
Thanks Matt. In fact, I have never updated my potcars. I assume that for PBE functional used in MP, the potcars should not changed right? maybe i am wrong.. It leads me to think that If somehow the potcar changes slightly, for example adding extra spaces, that will also change the hashes? I wonder if there are alternative ways to test the equivalencies of pseudo potentials..

**Comment by mkhorton** [comment]
Yes, that's why there are two hashes, the "file hash" (which will change even if a title or a space changes) and a "pymatgen hash" (which is meant to be more robust against small changes). VASP have released multiple versions of the same POTCARs sometimes, because of small typos.

We have the hashing system because some people have spent many CPU hours on incompatible calculations because they accidentally use the wrong POTCAR, so the hashing is meant to prevent that, however I think it's too strict right now.

**Comment by chc273** [comment]
Thanks Matt. Yes, hash can be too sensitive to very small changes and the files that you used to generate the hashes may be slightly different from what our group is using.

It would be nice to have the option to turn off the warnings if I am certain that the POTCAR I am using is the correct one, judging from some meta information (e.g., VASP PBE) and the potcar symbol (e.g., Na_pv).

**Comment by mkhorton** [comment]
The "pymatgen hash" is intended to be robust against small changes, could you share this hash for your Na_pv in this issue so we can diagnose?

```
p = Potcar(['Na'])
p[0].file_hash  # gives me `5a81584fb022b82fbb3658e6decf92de`
p[0].hash # the "pymatgen hash" gives me `1a89e79f7e21d99e8cf5788979f6a987`
```

Note that the meta information is _not_ always correct in the file, some pseudopotentials distributed by VASP have (unfortunately) sometimes had incorrect metadata, e.g. they had a release where the title string gave PAW instead of PAW_PBE.

**Comment by chc273** [comment]
I confirm that these two hashes are the same as yours for `Na`. The one problematic is `Na_pv` (MPRelaxSet uses this one).

```
p_na_pv = Potcar(['Na_pv'])[0]
```
Will give me warning 
```BadPotcarWarning: POTCAR data with symbol Na_pv does not match any VASP                          POTCAR known to pymatgen. We advise verifying the                          integrity of your POTCAR files.
  BadPotcarWarning)
```
The hashes are

```
p_na_pv.hash  # gives me 'c71d0ed99a871c91fccae9347860d8ba'
p_na_pv.file_hash  # gives me 'c2bf3a84744e11107e8c18128fe55175'
```
pymatgen version is `2020.4.2`.

**Comment by mkhorton** [comment]
Thanks! I'll follow-up.

**Comment by chc273** [comment]
Thanks Matt!

**Comment by zbwang** [comment]
> If interested, here is the current list of [file hashes (checksums of the file itself)](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/io/vasp/vasp_potcar_file_hashes.json) and ["pymatgen hashes"( hashes of the content of the potcar)](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/io/vasp/vasp_potcar_pymatgen_hashes.json), so you could check if your Na_pv hash is already included in one of those, it could be a logic bug.

In these two hash files, it seems they only cover `"potpaw_PBE.54", "unvie_potpaw_PBE.54", "potpaw_PBE.52", "unvie_potpaw_PBE.52"`.  I think Chi used the oldest VASP PSP (`"potpaw_PBE" or "POT_GGA_PAW_PBE"`) and the MP did the same. 

 According to the VASP release notes, this oldest VASP PSP is outdated. The developers recommend  PBE54 (`potpaw_PBE.54`)
The original release of PBE52 and PBE54 are now called "unvie PBE52" and "unvie PBE54", respectively. (@chc273 I think you also used these old ones.) In VASP portal, they have the lastest PBE52 and PBE54.

**Comment by chc273** [comment]
Thanks Zhenbin @zbwang In your experience, will the calculation results change if I switch from the older PBE to PBE54? What are the differences? My concern is about the result consistency with MP if I update to the latest PBE. It may affect things like ehull calculations etc.

**Comment by zbwang** [comment]
Sorry, I am not sure. But based on these two hash files, it seems the MP is going to discard the oldest VASP PSP but use the newest ones. Matt may know how MP is going to deal with this.  (some potcar correction?)

**Comment by mkhorton** [comment]
@zbwang the hash database does include the oldest VASP pseudopotentials. Regarding the issue, no POTCAR correction is planned, we are using the oldest pseudopotentials for MP compatibility. We are switching to PBE54 for newer calculations with different functionals, but our standard PBE calcs are staying on the old pseudos for now.

**Comment by zbwang** [comment]
ah. my bad, I just realized that the hash keys for the oldest PSP are at the bottom of the files you shared. Then, it is strange that each time when generating VASP inputs, pymatgen complains the warnings.

**Comment by darnoceloc** [comment]
`pymatgen/io/vasp/inputs.py:1856: UnknownPotcarWarning: POTCAR with symbol Pr has metadata that does not match                          any VASP POTCAR known to pymatgen. The data in this POTCAR is known to match the following functionals:                          ['PBE_52', 'PBE_54', 'unvie_PBE_52']`
.
When post-processing results from a **TbO2** relaxation, I get the same UnknownPotcarWarning and pymatgen interprets the Tb ions as Ce when printing output structure data, plotting DOS, etc.

How should this behaviour be handled since the post-processing of VASP results is being affected in the case of TbO2.

Can results generated by pymatgen modules on raw VASP output data be interpreted as the same when this warning is not present?

**Comment by hhh123hhh123** [comment]
@darnoceloc I have the same problem as you.Have you solved this problem？
`/pymatgen/io/vasp/inputs.py:1820: UnknownPotcarWarning: POTCAR with symbol Zr_sv has metadata that does not match                          any VASP POTCAR known to pymatgen. The data in this                          POTCAR is known to match the following functionals:                          ['unvie_PBE_52', 'PBE_54', 'PBE_52']`

**Comment by mkhorton** [comment]
> When post-processing results from a TbO2 relaxation, I get the same UnknownPotcarWarning and pymatgen interprets the Tb ions as Ce when printing output structure data, plotting DOS, etc.

More information would be required to diagnose this issue; this sounds unusual and potentially troublesome.

The warning itself is not necessarily a problem (it is just a warning). Mis-parsing one ion as another ion, however, would be a significant bug if it could be reproduced and was not an error in usage.
