### ISSUE TITLE
Error of Critic2Caller

### ISSUE THREAD

**Issue by yuuukuma** [materialsproject/pymatgen#1890]
[test.zip](https://github.com/materialsproject/pymatgen/files/4850861/test.zip)
**Describe the bug**
When using the critic2 with Critic2Caller, the result shows 
```
%% load int.CHGCAR id chg_int zpsp Al 3 As 5 O 6

!error! id chg_int zpsp Al 3 As 5 O 6
ERROR(setfield): Unknown extra keyword
ERROR(setfield): Unknown extra keyword
```
and fails.
This result does not depend on the system.
However, when using Pymatgen ver.2020.1.28, Critic2Caller works.
So, the update between ver.2020.1.28 and ver.2020.6.8 may break the code related to Critic2Caller.

The version of critic2 is the latest stable version (+ critic2 (stable), commit (config) 3081176) downloaded last Saturday.

**To Reproduce**
1. Copy the attached files to a directory.

2. Run the following command with the attached files. First argument is the path to the directory.

```
from pymatgen.command_line.critic2_caller import Critic2Caller

def create_critic2_output(path: str):
    critic2_caller = Critic2Caller.from_path(path)

if __name__ == "__main__":
    create_critic2_output(sys.argv[1])
```

**Comment by mkhorton** [comment]
Hi @yuuukuma, you need to compile a newer version of Critic2, the zpsp version isn't in older versions of the code.

**Comment by yuuukuma** [comment]
Dear @mkhorton,
thanks for your reply. 
I can only use the stable version of critic2 due to the compiler issue, so try to use the older version of Pymatgen.

**Comment by mkhorton** [comment]
Ok, you can also check with the critic2 developer to see if you can get a newer compilation to work, it usually works quite well.

**Comment by yuuukuma** [comment]
Dear @mkhorton 

The latest version of critic2 downloaded from the GitHub page works quit well with the latest Pymatgen.
However, I think there is a bug in Critic2Caller

Please see line 300 in critic2_caller.py
"symbol" should be "element"; otherwise, it does not work for e.g. "Ca_pv" PAW potential.
--------------------------------------------------------------------------
        if not zpsp:

            potcar_path = _get_filepath(
                "POTCAR",
                "Could not find POTCAR, will not be able to calculate charge transfer.",
            )

            if potcar_path:
                potcar = Potcar.from_file(potcar_path)
                zpsp = {p.symbol: p.zval for p in potcar}
--------------------------------------------------------------------------

**Comment by mkhorton** [comment]
Yes, I agree, that looks like a bug. Would you be willing to submit a PR to fix?

**Comment by yuuukuma** [comment]
Okay, I will submit a PR.
Do you think I need to prepare a unittest for this?

**Comment by mkhorton** [comment]
No, I think this is fine for now, thanks.
