### ISSUE TITLE
One should be able to put pymatgen.core.surface.Slab.as_dict() into a MongoDB database using pymongo.

### ISSUE THREAD

**Issue by MichaelWolloch** [materialsproject/pymatgen#1892]
**Is your feature request related to a problem? Please describe.**
When I try to put a `Slab.as_dict()` into a MongoDB database within a FireWorks workflow it fails. The `as_dict()` method has to be MSON serializable according to the documentation, but apparently for pymongo this is not enough.
The problematic entries for me where:
1.  `site['properties']['bulk_equivalent']` for site in` Slab.as_dict()['sites']` and for site in `Slab.as_dict()['oriented_unit_cell']['sites']`. These are of type` numpy.int32` which pymongo can not encode.
2.  `Slab.as_dict()['scale_factor']` which has type `numpy.ndarray`

**Describe the solution you'd like**
I would appreciate if the `as_dict()` method of `pymatgen.core.surface.Slab` would result in a dictionary that has only data types encodable by pymongo. This would mean to change some types from `numpy.int32` to `int` and `numpy.ndarray` to `list`.
If needed, the `from_dict()` method should also be adapted to convert the types back.

**Describe alternatives you've considered**
I have written a small function to change the problematic types myself before database insertion, and I can confirm that I can create a Slab object again with the from_dict() method. However, I have not yet tested if there might be a problem when using the slabs (e.g. for the creation of an interface) later on, which could be true especially for the scale_factor which remains a list of lists. Of course another small function to change the types back would be sufficient to solve this problem, but overall this is not very elegant and I think to do it inside the `as_dict() `and `to_dict()` methods would be better and cleaner.

**Comment by mkhorton** [comment]
Check out `jsanitize` in `monty.json` and see if that helps. There's a subtle distinction between `to_dict()` and `to_json()` methods, to insert into Mongo it needs to be JSON-compatible, you might try JSON with MontyEncoder too. Both these methods should just work without manual code tweaks required. If this doesn't work, let me know.

**Comment by MichaelWolloch** [comment]
Thanks a lot for the quick reply and the options to solve my problem. Both `monty.json.jsanitize(Slab.as_dict(), allow_bson=True) ` and `json.dumps(Slab, cls=monty.json.MontyEncoder)` can be inserted into MongoDB without problems.

I think I will to stick to `jsanitize`, as I can use the same code to load `Structures` and `Slabs` from the DB without rewriting stuff to feature `json.dumps` and `json.loads`.
Also, while `json.loads(json_slab, cls=monty.json.MontyDecoder)` produces a valid `pymatgen.core.surface.Slab` object, I am not getting the expected results. E.g. for the `Slab` object from `json.loads` I get a `dict` for `Slab.scale_factor`:
~~~
{'@module': 'numpy',
 '@class': 'array',
 'dtype': 'int64',
 'data': [[0, 0, -1], [1, -1, 0], [0, -1, 0]]}
~~~
while I get a list of lists with the `jsanitize` option. I probably are making a mistake again, somewhere with json, but this is not too important for now and I guess a `list of lists` is closer to the original `numpy.ndarray` than a `dict`, even if the `dict` contains all the information of the original array.

Thanks again for the help!

**Comment by shyuep** [comment]
I pushed a fix for this.
