### ISSUE TITLE
SlabGenerator missed some unique surfaces

### ISSUE THREAD

**Issue by lixinyuu** [materialsproject/pymatgen#1894]
Hi Pymatgen Developers,

I am using Pymatgen to generate the (1, 0, 0) surfaces of  mp-3702 FeCuPt2 crystal, and I get confused why only one CuPt terminated surface is generated. Theoretically, there are two unique surfaces (terminated at (1, 0, 0) and (0.5, 0, 0) respectively)

```
from pymatgen.ext.matproj import MPRester
from pymatgen.core.surface import SlabGenerator
with MPRester(api_key='******') as rester:
    structure = rester.get_structure_by_material_id('mp-3702')

slab_gen = SlabGenerator(initial_structure=structure,
                             miller_index=(1, 0, 0),
                             min_slab_size=6.,
                             min_vacuum_size=12.,)
slabs = slab_gen.get_slabs()
len(slabs)
```

We can see that the geometry of the generated slab is
![Snipaste_2020-07-03_19-42-07](https://user-images.githubusercontent.com/33710988/86456421-6316b300-bd65-11ea-84ad-07e16fee3991.jpg)

**Expected behavior**
However, a slab which is terminated by FePt should be generated as well. I tried to use (2, 0, 0) as miller index, but it doesn't work as well.
![FePt-terminated](https://user-images.githubusercontent.com/33710988/86456611-a96c1200-bd65-11ea-8a20-786ff128d8b4.jpg)

Could anyone give me some suggestions here? Thanks very much.

 - OS: Linux
 - Version 2019.11.11

**Comment by shyuep** [comment]
The code is correct. In your first example, there are TWO surfaces - one is the FePt terminated and the other is CuPt terminated. In your second figure, that is not even stoichiometric FeCuPt2 anymore. If you want to make sure the surfaces are  symmetrized, you need the Tasker 2 reconstructed slabs.

**Comment by lixinyuu** [comment]
Thanks Professor. I understand it now.
