### ISSUE TITLE
Simple way to test if a structure is disordered?

### ISSUE THREAD

**Issue by mm04926412** [materialsproject/pymatgen#1898]
Apologies if github is the wrong place to ask operational questions.

I have a large list of structures and I need to quickly identify the ones with partial occupancies and parse them / clean up. Is there a quick test for if a crystal contains partial occupancies?

**Comment by shyuep** [comment]
What format are your structure files? Structure.is_ordered is the property method you are looking for.
For questions regarding usage, pls use https://matsci.org/c/pymatgen/9
