### ISSUE TITLE
enumlib error

### ISSUE THREAD

**Issue by haesunpark87** [materialsproject/pymatgen#1914]
**Describe the bug**
Error when modules from pymatgen.analysis.magnetism.analyzer are used. 

**To Reproduce**
1. execute the following python script

!/usr/bin/env python3
 -*- coding: utf-8 -*-
from pymatgen.core import Lattice, Structure
from pymatgen.analysis.magnetism.analyzer import *

latt = Lattice.cubic(4.17)
species = ["Ni", "O"]
coords = [[0.00000, 0.00000, 0.00000], [0.50000, 0.50000, 0.50000]]
NiO = Structure.from_spacegroup(225, latt, species, coords)
print(NiO)
#enumerator = CollinearMagneticStructureAnalyzer(NiO)
enumerator = MagneticStructureEnumerator(NiO,strategies='ferromagnetic')

2. Then it seems the structure is generated but magnetic analyzing module dose not work

Full Formula (Ni4 O4)
Reduced Formula: NiO
abc   :   4.170000   4.170000   4.170000
angles:  90.000000  90.000000  90.000000
Sites (8)
     SP      a    b    c
  0  Ni    0    0    0
  1  Ni    0    0.5  0.5
  2  Ni    0.5  0    0.5
  3  Ni    0.5  0.5  0
  4  O     0.5  0.5  0.5
  5  O     0.5  0    0
  6  O     0    0.5  0
  7  O     0    0    0.5
Illegal instruction (core dumped)

*Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/43765756/88584659-9a504b00-d017-11ea-808a-9c2c78e10070.png)

**Desktop (please complete the following information):**
 - The code is ran on the cluster in Argonne National Lab bebop. 
 - Linux 3.10.0-957.21.3.el7.x86_64 x86_64

**Additional context**

**Comment by mkhorton** [comment]
Hi @haesunpark87, this code works for me, a core dump is likely some serious issue with your installation -- have you tried installing `pymatgen` using conda? Does `enumlib` work outside of pymatgen? (e.g. if you call `enum.x` directly?)

**Comment by haesunpark87** [comment]
Dear Matthew, 

It seems you are right. 
I ran the following code,

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from pymatgen.core import Lattice, Structure
from pymatgen.transformations.advanced_transformations import EnumerateStructureTransformation

specie = {"Cu": 0.5, "Au": 0.5}
cuau = Structure.from_spacegroup("Fm-3m", Lattice.cubic(3.677), [specie], [[0, 0, 0]])

trans = EnumerateStructureTransformation(max_cell_size=3)
ss = trans.apply_transformation(cuau, return_ranked_list=1000)

And the error message saying "RuntimeError: EnumlibAdaptor requires the executables 'enum.x' or 'multienum.x' and 'makestr.x' or 'makeStr.py' to be in the path. Please download the library at http://enum.sourceforge.net/ and follow the instructions in the README to compile these two executables accordingly. “

I have the same error in my desktop and the question is where is the path to put the executables. 

Best,
Haesun

**Comment by mkhorton** [comment]
You can install enumlib following the instructions here: https://github.com/msg-byu/enumlib

You put it into your PATH meaning that it's available when you type a command in a terminal; the specific instructions to do this vary from Linux, Mac, Windows etc.

Will close this issue since it's not a pymatgen bug but good luck!
