### ISSUE TITLE
How to generate vacancy structure and calculate formation energy

### ISSUE THREAD

**Issue by thienbinh92** [materialsproject/pymatgen#1915]
Hello, I read this paper "Vacancy Ordering in O3-Type Layered Metal Oxide Sodium-Ion Battery Cathodes", Toumar described that pymatgen was used to generate potential structures and the formation energy vs Na concentration was plotted in figure 3. If I am right, the pymatgen's tutorial does not describe how to generate potential structures. Can anyone show me step by step how to generate vacancy structures using pymatgen? Please take O3 layered oxide as an example.
Thank you so much!
https://escholarship.org/content/qt9648d7wm/qt9648d7wm.pdf

**Comment by mkhorton** [comment]
Hi @thienbinh92, this issues page is for reporting bugs, if you have a question could you ask it over at our user forum on https://matsci.org/pymatgen ? thanks!
