### ISSUE TITLE
Something wrong with the result of DosPlotter 

### ISSUE THREAD

**Issue by Shan19961030** [materialsproject/pymatgen#1934]
**Describe the bug**
when I use the BSDosPlotter model to draw BAND and DOS figure,I got a perfect result comparing to the one drawn by P4V and Origin.But,when I use the same data to draw single DOS picture with DosPlotter ,I got a very strange result . 

**To Reproduce**
Follows are my script of DosPlotter:

 import matplotlib.pyplot as plt
from pymatgen.io.vasp.outputs import Vasprun
from pymatgen.electronic_structure.plotter import BSDOSPlotter, BSPlotter, BSPlotterProjected, DosPlotter

dos_vasprun = Vasprun("./dos/vasprun.xml")
dos_data = dos_vasprun.complete_dos
bs_vasprun = Vasprun("./band/vasprun.xml", parse_projected_eigen=True)
bs_data = bs_vasprun.get_band_structure(line_mode=True)

plt1 = DosPlotter(stack=True, sigma=0.5)
plt1.add_dos('total dos', dos=dos_data)
plt1.save_plot('DOS.png', img_format=u'png')

**Screenshots**
This is the result of BSDosPlotter
[image](http://m.qpic.cn/psc?/V11CjYqJ0aw8nE/bqQfVz5yrrGYSXMvKr.cqQyJain0wopA8.W9M02nUSSc47hSbSvgwoC*0l6UpJqNaPVGdlAFDgMr3if5O2ECX97msz5kz9M5WBM4KykTlkE!/b&bo=TARSAwAAAAADBzs!&rf=viewer_4)
This is the result of DosPlotter
[image](http://m.qpic.cn/psc?/V11CjYqJ0aw8nE/TmEUgtj9EK6.7V8ajmQrEHrPeDaGjBTlR*k.D5XsIvPoWd31h6XhVEVTwdXkil5.KVPt.nR8HIXuHbv3miCqDcy6xkqY2DhIsyyKEd36z*8!/b&bo=sAQgAwAAAAADF6U!&rf=viewer_4)

**Desktop (please complete the following information):**
 - OS: [Windows]
 -python Version [3.8]

**Additional context**
Is it a problem of the version of Python?

Thank you for your attention!

**Comment by fraricci** [comment]
I think the problem comes from stack=True. I had a similar result when trying to fill the a DOS plotted horizontally, while was ok if plotted vertically (as by BSDOSPlotter). Please, try with stack=False.
I edited the code to solve the bug but I forgot to push it. I'll do it ASAP.

**Comment by Shan19961030** [comment]
I have tried to solve this problems with stack = False,but the result also seems strange,here is the result
[image](http://m.qpic.cn/psc?/V11CjYqJ0aw8nE/bqQfVz5yrrGYSXMvKr.cqYKcrh4XcC2c7vMugZy9f3ZtSwJy5k2VezXdpGQQ3PIHu1*7g5bKnT5u.SCNKsvgHhQI9qmDgM8gDgs8isQLBiI!/b&bo=sAQgAwAAAAADB7U!&rf=viewer_4)

**Comment by Shan19961030** [comment]
> I think the problem comes from stack=True. I had a similar result when trying to fill the a DOS plotted horizontally, while was ok if plotted vertically (as by BSDOSPlotter). Please, try with stack=False.
> I edited the code to solve the bug but I forgot to push it. I'll do it ASAP.

I have tried to solve this problems with stack = False,but the result also seems strange,here is the result
[image](http://m.qpic.cn/psc?/V11CjYqJ0aw8nE/bqQfVz5yrrGYSXMvKr.cqYKcrh4XcC2c7vMugZy9f3ZtSwJy5k2VezXdpGQQ3PIHu1*7g5bKnT5u.SCNKsvgHhQI9qmDgM8gDgs8isQLBiI!/b&bo=sAQgAwAAAAADB7U!&rf=viewer_4)

**Comment by shyuep** [comment]
Can you supply the vasprun.xml so that we can debug it?

**Comment by Shan19961030** [comment]
> Can you supply the vasprun.xml so that we can debug it?

Thank you so much for your reply.Here is my vasprun.xml、POSCAR and POTCAR file. If you need more files, please feel free to contact me anytime and I will provide you with them soon.

[files](https://github.com/Shan19961030/VaspCalculationFile)

If you debug it or find the reasons,I hope you can notify me.

Sincere thanks!

**Comment by shyuep** [comment]
I need the KPOINTS file for the band structure. But I see what you did wrong. You used a HUGE sigma value. That is the value that is used to smear the DOS plot. A smearing of 0.5 eV is way too big. Try setting it to 0 or some small number. The following code works:

```
import matplotlib.pyplot as plt
from pymatgen.io.vasp.outputs import Vasprun
from pymatgen.electronic_structure.plotter import BSDOSPlotter, BSPlotter, BSPlotterProjected, DosPlotter
%matplotlib inline
dos_vasprun = Vasprun("vasprun.xml")
dos_data = dos_vasprun.complete_dos
#bs_vasprun = Vasprun("vasprun.xml", parse_projected_eigen=True)
#bs_data = bs_vasprun.get_band_structure(line_mode=True)

plt1 = DosPlotter(stack=False, sigma=0)
plt1.add_dos('total dos', dos=dos_data)
plt = plt1.get_plot()
plt.xlim(((-4, 6)))
plt.ylim((0, 1000))
```

Note that you have some strange states at low energies. Stack does not seem to work right now. This is because this is a no spin DOS I believe.

**Comment by Shan19961030** [comment]
> I need the KPOINTS file for the band structure. But I see what you did wrong. You used a HUGE sigma value. That is the value that is used to smear the DOS plot. A smearing of 0.5 eV is way too big. Try setting it to 0 or some small number. The following code works:
> 
> ```python
> import matplotlib.pyplot as plt
> from pymatgen.io.vasp.outputs import Vasprun
> from pymatgen.electronic_structure.plotter import BSDOSPlotter, BSPlotter, BSPlotterProjected, DosPlotter
> dos_vasprun = Vasprun("vasprun.xml")
> dos_data = dos_vasprun.complete_dos
> plt1 = DosPlotter(stack=False, sigma=0)
> plt1.add_dos('total dos', dos=dos_data)
> plt = plt1.get_plot()
> plt.xlim(((-4, 6)))
> plt.ylim((0, 1000))
> ```
> 
> Note that you have some strange states at low energies. So I set the xlims and ylims to a reasonable value. Stack does not seem to work for this case right now. This is because this is a no spin DOS I believe.

Thank you so much ,I will try it with you code again.
