### ISSUE TITLE
Faster analysis.local_env.VoronoiNN

### ISSUE THREAD

**Issue by googhgoo** [materialsproject/pymatgen#1950]
Hello, I have been trying to use VornoiNN at large scale and noticed it does not scale well with large data set. 
I noticed that trivial step in line 805 in pymatgen.analysis.local_env.VoronoiNN takes significant amount of time:
`sites = np.array(sites)[uniq_inds]`
The performance improves by about 10 fold over the MP data set if this is changed to:
`sites = [sites[i] for i in uniq_inds]`
I'm not sure how to make a pull request, so I just posted it here. 

Thank you very much.. I hope this helps..

**Comment by shyuep** [comment]
Thanks. I have pushed the changes this time. For future reference, the instructions for how to contribute to pymatgen are at https://pymatgen.org/contributing . For a small change such as this, one way is to directly edit within Github itself, which will create a PR.

**Comment by googhgoo** [comment]
Thank you, I will do that next time..
