### ISSUE TITLE
Problems with terminology

### ISSUE THREAD

**Issue by cajfisher** [materialsproject/pymatgen#1962]
A number of functions and their descriptions (as well as the online manual) use the incorrect term "specie" to describe a single species. The singular and plural forms are both "species". ("Specie" refers to the physical form of money, usually coins.)
See, e.g., https://brians.wsu.edu/2016/05/31/specie/
https://thetrcompany.com/en/difference-specie-species/
https://grammarist.com/usage/species/
Although the above explanations are concerned primarily with species as living organisms, the same applies for other usages:
https://www.merriam-webster.com/dictionary/species (1e)

It would be good if this error could be fixed at some stage to minimize confusion and improve readability and consistency across the various modules.

**Comment by mkhorton** [comment]
Hi @cajfisher, your comment is well-received but this is not likely to change at this point. The decision to use the term `Specie` is not made for grammatical reasons but for programmatical reasons: it is to unambiguously declare that this refers to a *single* species, vs., say, a list of multiple species. In terms of a programming language, only a single definition can be used (e.g., we could not use the term `Species` to refer to both a single `Species` object and an object that represents multiple `Species`), and it is very important that we unambiguously declare that this refers to the singular form. I appreciate this is grammatically frustrating however so my apologies for that :-)

**Comment by cajfisher** [comment]
Thanks for your quick response and explanation. I understand the need to distinguish between single and multiple species in the coding. The main problem (as I see it) is that this has bled over into the "natural" English used in the manual and module/function descriptions. For example, in the pymatgen.core.sites module under "species" it says "ii. An element / specie specified either as a string...", even though "species" is meant to contain multiple species; in the pymatgen.analysis.diffusion_analyzer module: "Specie to calculate diffusivity for as a String" (why am I calculating the diffusivity of a python variable?); and in the pymatgen.alchemy.materials module: "when the specie to replace...", but elsewhere "with a single species". In other words, there appears to be a lack of consistency. Tidying this up (although tedious!) should improve readability and reduce confusion, thereby speeding up both the uptake of pymatgen and future code development (easier bug checking, and so on). That's my (non-inflationary) two-cents worth, anyway.
Just for reference, in other codes I've worked on, variable names such as "species_type" and "atom_type" are commonly used to overcome/avoid this tricky linguistic problem (although you have probably already considered these). Cheers!

**Comment by shyuep** [comment]
I think this can be resolved easily. Let's rename it as Ion, and put Specie as a trivial subclass to maintain backwards compatibility. I do not think it is going to cause any issues?

Species_type or Atom_type is far too long a name for a very commonly used class.

**Comment by cajfisher** [comment]
Looking at the definition of the Specie class in pymatgen.core.periodic_table, this seems to be a sensible choice to me (as an outsider looking in).

**Comment by shyuep** [comment]
Ok, there is a complication (slight one). There is actually an ion class that is used defined in pymatgen.core.ion. The difference is that the current Ion is Composition(which can mean 1 or many atoms)+Oxidation State. This Ion is used just in the Pourbaix diagram construction.

There are a few potential solutions in order of effort:
1. Do nothing.
2. Rename Specie to Species and have Specie be a backwards compatible name.
3. Rename Specie to Ion and Ion to PolyIon. This will break backwards compatibility for sure for the current PourbaixDiagrams but will Specie can still be made backwards compatible by mapping to Ion.

@mkhorton I am leaning towards #2. It is ~ the first option in terms of effort. It solves the grammar issue. And for existing users, it is invisible. What do you think?

**Comment by shyuep** [comment]
I have implemented the change in https://github.com/materialsproject/pymatgen/tree/species_rename branch. Seems to be working fine. There is one slight complication in that Site.specie is used to refer to a single species in ordered sites. For that, I don't think we can do a rename since the programmatic choice that Matt mentioned (single vs plural variable names) unfortunately applies here. I have added a statement on the deliberate non-grammatical naming choice in the documentation for that property.

**Comment by mkhorton** [comment]
I don't think `Ion` is a good fit for `Specie`, because `Specie` can contain `spin` instead of `oxidation_state`, i.e. it's not always an ion, and as you say ion is already used in Pourbaix regardless

**Comment by mkhorton** [comment]
My primary motivation *against* changing it is the backwards compatibility argument, since `Specie` has been in use for a long time at this point. If we wanted to break backwards compatibility, I would have it subclass `Element` instead, and allow a more uniform interface between `Element` and `Specie`

**Comment by cajfisher** [comment]
Another alternative label is "Particle". A few more characters than "Ion" and a bit more general in meaning, but it seems to cover the properties entailed by "Specie" reasonably well, assuming it isn't used elsewhere. Also, if you did want to break backwards compatibility, Matthew's suggestion sounds good from an OOP point of view.

**Comment by mkhorton** [comment]
Thanks for the feedback, it is now `Species` 🎉
