### ISSUE TITLE
The "too close" atoms are not removed in the grain boundary structure for bcc [001] twist GB with primitive cell

### ISSUE THREAD

**Issue by goodwilling** [materialsproject/pymatgen#1970]
**Describe the bug**
In the GB structure, some atoms  are too close to each other (distance < rm_ratio*bond_length_in_bulk). 
 Similar results are also obtained for other bcc systems, with [100], [010], [001] as the  rotation axis for the 
twist GB and the primitive cell as the crystal bulk structure, together with normal = False. 

**To Reproduce**
Using the following python script with pymatgen 2020.9.4:
-----------------------------------
from pymatgen import Structure
from pymatgen.analysis.gb.grain import GrainBoundary, GrainBoundaryGenerator

angle = GrainBoundaryGenerator.get_rotation_angle_from_sigma(5, [0, 0, 1], lat_type='c')
struc = Structure.from_file("Fe_mp-13_primitive.cif")

generator = GrainBoundaryGenerator(struc)
gb = generator.gb_from_parameters([0, 0, 1], angle[0], expand_times=8)

gb.to(filename="Fe_mp-13_gb001.cif")
-----------------------------------

**Expected behavior**
 0.7*bond_length of bulk system is the criteria of bond length, 
below which the atom will be removed. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version [2004]

**Comment by shyuep** [comment]
@ucsdlxg Can you take a look?

**Comment by ucsdlxg** [comment]
Sure. I will take a look.

**Comment by ucsdlxg** [comment]
It seems to me that the problem is due to the structure.merge_sites() function. The temporary solution is to do one more merge_sites(tol = tol, mode='d') with your obtained GB object.  Or you can add a vacuum layer, e.g. set vacuum_thickness=1.0.
