### ISSUE TITLE
XSF atomic symbol as label request

### ISSUE THREAD

**Issue by seryi70** [materialsproject/pymatgen#1977]
We get frustrated that pymatgen XSF implemented only the  number as atom label, whereas most software can handle the regular atomic symbol, much easier to find elements of interest in the file.

**Describe the solution you'd like**
Please add the possibility to dump/read XSF files with  atomic symbol (H,He,O) instead of atomic number  (1,2,8) for atom label.

Thank you.
Sergiu

**Comment by mkhorton** [comment]
Can you upload a sample XSF file?

**Comment by seryi70** [comment]
Sure thing, thanks a lot.
Sergiu

[pymatgen_example.zip](https://github.com/materialsproject/pymatgen/files/5339419/pymatgen_example.zip)

**Comment by shyuep** [comment]
Done. Now the default format uses atom symbols.
