### ISSUE TITLE
Dump structure to Lammps format

### ISSUE THREAD

**Issue by seryi70** [materialsproject/pymatgen#1978]
Dear pymatgen developers, is it possible to have pymatge.core.structure.to(fmt='lammps',...) ?

**Describe the solution you'd like**
A simple format conversion described here: https://atomsk.univ-lille.fr/tutorial_lammps.php

Besr regards,
Sergiu

**Comment by shyuep** [comment]
You can use the pymatgen.io.lammps to create LAMMPS format. Not all formats are given in fmt because LAMMPS require other parameters to be specified.
