### ISSUE TITLE
Plot of neutron diffraction is broken

### ISSUE THREAD

**Issue by goodwilling** [materialsproject/pymatgen#1980]
**Describe the bug**
Neutron diffraction pattern can not be plot.  A bug fix is suggested.

**To Reproduce**
Error always comes out if using the following script:

from pymatgen import Structure
from pymatgen.analysis.diffraction.neutron import NDCalculator
import sys
 
struc = Structure.from_file("Fe_mp-13_primitive.cif");
plot=NDCalculator().get_plot(struc)
plot.show()

with the following error message
------------------
Traceback (most recent call last):
  File "calc_XRD.py", line 6, in <module>
    plot=NDCalculator().get_plot(struc)
  File "C:\ProgramData\miniconda3\lib\site-packages\pymatgen\analysis\diffraction\core.py", line 108, in get_plot
    label = ", ".join([str(hkl["hkl"]) for hkl in hkls])
  File "C:\ProgramData\miniconda3\lib\site-packages\pymatgen\analysis\diffraction\core.py", line 108, in <listcomp>
    label = ", ".join([str(hkl["hkl"]) for hkl in hkls])
TypeError: tuple indices must be integers or slices, not str
------------------

**Expected behavior**
A matplotlib plot should be shown.

**Suggested bug fix**
With the following correction, the neutron diffraction pattern can be plot as expected:

pymatgen\analysis\diffraction\neutron.py, Line 197:
                hkls.append(fam)
-->
                #hkls.append(fam)
                hkls.append([{"hkl": hkl, "multiplicity": mult}
                             for hkl, mult in fam.items()])

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version:  Pymatgen-2020.09.14

**Comment by shyuep** [comment]
Thanks. I implemented the fix with a new test to ensure this does not recur.
