### ISSUE TITLE
Confirm the equivalence of different surfaces belong to different spacegroups which are related via the change-of-basis transformation.

### ISSUE THREAD

**Issue by hongyi-zhao** [materialsproject/pymatgen#1981]
Hi,

Based on the descriptions in [this paper](https://pubs.acs.org/doi/pdf/10.1021/acs.chemmater.9b05047), see top left column on pp.3 for more info, I learned the following fact: 

`
The (010) surface in C2/c is equivalent to the (001) surface in I2/b. And these two space groups are related through a change-of-basis transformation. An I2/b cell is with tetragonal lattice while a C2/c cell is related to the conventional monoclinic cell.
`

But The above description is very abstract and difficult to understand, so I want to know whether I can have a better understanding of the problem based on the help of pymatgen?

Regards,
HY

**Comment by shyuep** [comment]
Your statement is incorrect. C2/c and I2/b are both monoclinic. They even have the same space group (No. 15). It is just a different choice of axes. All this can be found in the International Tables for Space group No. 15.
