### ISSUE TITLE
[Feature Request] Better compatibility between PDPlotter and matplotlib subplots

### ISSUE THREAD

**Issue by CompRhys** [materialsproject/pymatgen#1984]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to pass `matplotlib` axes objects to `PDPlotter` when using the `matplotlib` backend such that they can be easily incorporated into subplots.

**Describe the solution you'd like**
a `kwarg` called `axes` in PDPlotter that gives the axes to plot the phase diagram on in a subplots

**Additional context**
there is a `kwarg` called `plt` in `PDPlotter` that may have similar functionality but I haven't managed to use it for this use case successfully

**Comment by rkingsbury** [comment]
+1 . I agree this would be very useful.

**Comment by shyuep** [comment]
I don't have a problem with this. Can @utf implement and submit a PR?

**Comment by utf** [comment]
Yes I can implement this.

**Comment by janosh** [comment]
@utf I submitted a similar PR that adds an `ax` kwarg to `plot_brillouin`. Could you have a look at #2039?

**Comment by mattmcdermott** [comment]
I just updated `PDPlotter` in https://github.com/materialsproject/pymatgen/pull/3032 but this is still not addressed. I don't feel particularly good about touching some of the matplotlib code, so if anyone is interested in improving it sometime, please feel free!
