### ISSUE TITLE
If there any way to get x-y axis non-orthogonal slabs?

### ISSUE THREAD

**Issue by lixinyuu** [materialsproject/pymatgen#1988]
Hi pymatgen developers,

I have lots of x-y axis orthorhombic slabs which is constructed by SlabGenerator. However, my problem is sensitive to the slab x-y angle (gamma) thus I would like to check if these slabs could be transformed into non-orthorhombic slabs.

The following picture (get from https://wiki.fysik.dtu.dk/ase/ase/build/surface.html) shows what I want to do. So I have lots of orthorhombic slabs like the right slabs, I would like to know if they could be reshaped into non-orthorhombic ones. I have checked both SlabGenerator and SpacegroupAnalyzer, but didn't find way to do this. 

Could you please give me some suggestions? Thanks in advance. 
![Screensho![Uploading Screenshot 2020-10-25 201005.png…]()t 2020-10-25 201005](https://user-images.githubusercontent.com/33710988/97103188-fe5dda80-16fe-11eb-99bd-b387e69b84b0.png)

**Comment by shyuep** [comment]
In pymatgen's slab generator, the surface is in the x-y direction. The only question is whether the z direction is constrained to be orthogonal or not. By default the SlabGenerator makes non-orthgonal slabs that are the smallest possible for that surface. If you use Slab.get_orthogonal_c_slab, you then get the orthogonal version.

**Comment by shyuep** [comment]
In future, please use https://discuss.matsci.org/ for queries on usage. Github Issues is meant for reporting bugs and requesting new features. Thanks.

**Comment by lixinyuu** [comment]
Thanks, Prof. Ong.
