### ISSUE TITLE
ValueError when using get_decomposition_energy for computed entries in Pourbaix diagrams

### ISSUE THREAD

**Issue by CJBR-97** [materialsproject/pymatgen#1993]
Hello,

I am new to pymatgen and am trying to use the Pourbaix diagram features to obtain a decomposition energy for a computed entry.  However I keep encountering the ValueError associated with the get_decomposition_energy() method: 

_ValueError: Composition of stability entry does not match Pourbaix Diagram_

Is it possible to resolve this error?

Below is the code:

![image](https://user-images.githubusercontent.com/69945487/99027117-73704300-253a-11eb-9d50-f360d98a9bab.png)

**Comment by JosephMontoya-TRI** [comment]
The phase used in the argument of Pourbaix.get_decomposition_energy must have a matching ratio of non-OH elements in order to work.  When you generate the pourbaix diagram, add a composition dictionary to match the entry whose stability you want to determine, e.g.

```
pbx = PourbaixDiagram(entries, comp_dict={"Zn": 27/108, "V": 81/108})
```

**Comment by JosephMontoya-TRI** [comment]
@CJBR-97 does this resolve your issue?

**Comment by CJBR-97** [comment]
Yes this was great!  Thank you.

Sorry for the late reply.

**Comment by mfdresser** [comment]
Hi,

I get the same error even when I use a composition dictionary. Could you help me understand why? My code is:
`els = ['O', 'Na', 'Si', 'Al']
mp_id = "mp-560334"
comp_dict = {'Na': 0.14285714285714285, 'Al': 0.14285714285714285, 'Si': 0.14285714285714285, 'O': 0.5714285714285714}

with MPRester(api_key) as m:
            pe = m.get_pourbaix_entries(els) 
        
dia = pb.PourbaixDiagram(pe, comp_dict) 
plot = pb.PourbaixPlotter(dia)

mpid_entry = [entry for entry in pe if entry.entry_id==mp_id][0] 
decomp_e = dia.get_decomposition_energy(mpid_entry, pH, V) `

This gives the error:
`ValueError: Composition of stability entry does not match Pourbaix Diagram`
Everything works until I use dia.get_decomposition_energy

**Comment by JosephMontoya-TRI** [comment]
As an aside for dev purposes - we could probably do a better job of preprocessing this argument, I don't see any issue removing OH elements from a supplied composition, and it would probably be useful to accept a composition, as opposed to only a dictionary, and to just call the argument that.  I think the the holdover is just from legacy behavior.

**Comment by mfdresser** [comment]
Hi, thanks for your response! So, even if my solid of interest is an oxide, I should still leave the O composition out of my composition dictionary?

**Comment by mfdresser** [comment]
Thank you! This fixed the problem.

**Comment by ThamBui8896** [comment]
Dear Sir,
I try the code for make Pourbaix Diagram of (ZnMn2O4 (mp-18751-GGA+U))
However, I have the erorr " Composition of stability entry does not match Pourbaix Diagram"

This is my used code: 
```
# Import necessary tools from pymatgen
from pymatgen.analysis.pourbaix_diagram import PourbaixDiagram, PourbaixPlotter
from mp_api.client import MPRester

%matplotlib inline

# Initialize the MP Rester
mpr = MPRester("API")
# Get all pourbaix entries corresponding to the Zn-Mn-O-H chemical system.
entries = mpr.get_pourbaix_entries(["Zn", "Mn"])
# Construct the PourbaixDiagram object
pbx1 = PourbaixDiagram(
    entries,
    comp_dict={"Zn": 0.5, "Mn": 0.5},
    conc_dict={"Zn": 1e-6, "Mn": 1e-6},
    filter_solids=True,
)
plotter = PourbaixPlotter(pbx1)
plotter.get_pourbaix_plot().show()

entry = [entry for entry in entries if entry.entry_id == "mp-18751-GGA+U"][0]
plt = plotter.plot_entry_stability(entry)

)
```

ValueError                                Traceback (most recent call last)
Cell In[156], line 2
      1 entry = [entry for entry in entries if entry.entry_id == "mp-18751-GGA+U"][0]
----> 2 plt = plotter.plot_entry_stability(entry)

File ~\miniconda3\Lib\site-packages\pymatgen\analysis\pourbaix_diagram.py:1059, in PourbaixPlotter.plot_entry_stability(self, entry, pH_range, pH_resolution, V_range, V_resolution, e_hull_max, cmap, ax, **kwargs)
   1053 ax = self.get_pourbaix_plot(ax=ax, **kwargs)
   1054 pH, V = np.mgrid[
   1055     pH_range[0] : pH_range[1] : pH_resolution * 1j,
   1056     V_range[0] : V_range[1] : V_resolution * 1j,
   1057 ]
-> 1059 stability = self._pbx.get_decomposition_energy(entry, pH, V)
   1061 # Plot stability map
   1062 cax = ax.pcolor(pH, V, stability, cmap=cmap, vmin=0, vmax=e_hull_max)

File ~\miniconda3\Lib\site-packages\pymatgen\analysis\pourbaix_diagram.py:837, in PourbaixDiagram.get_decomposition_energy(self, entry, pH, V)
    833 entry_pbx_comp = Composition(
    834     {elt: coeff for elt, coeff in entry.composition.items() if elt not in ELEMENTS_HO}
    835 ).fractional_composition
    836 if entry_pbx_comp != pbx_comp:
--> 837     raise ValueError("Composition of stability entry does not match Pourbaix Diagram")
    838 entry_normalized_energy = entry.normalized_energy_at_conditions(pH, V)
    839 hull_energy = self.get_hull_energy(pH, V)

**ValueError: Composition of stability entry does not match Pourbaix Diagram**
I have the Poubaix Diagram without  ΔGpbx as bellow , 
![image|690x397](upload://1G5BNXlRCDFo0fjP5uVGgOIeykh.png)
How can I fix this erorr and the plot can show ΔGpbx,
I am really hope you can help in this case,
Thank you so much!

**Comment by ThamBui8896** [comment]
> @CJBR-97 does this resolve your issue?

Dear Sir,
I try the code for make Pourbaix Diagram of (ZnMn2O4 (mp-18751-GGA+U))
However, I have the erorr " Composition of stability entry does not match Pourbaix Diagram"

This is my used code: 
```
# Import necessary tools from pymatgen
from pymatgen.analysis.pourbaix_diagram import PourbaixDiagram, PourbaixPlotter
from mp_api.client import MPRester

%matplotlib inline

# Initialize the MP Rester
mpr = MPRester("API")
# Get all pourbaix entries corresponding to the Zn-Mn-O-H chemical system.
entries = mpr.get_pourbaix_entries(["Zn", "Mn"])
# Construct the PourbaixDiagram object
pbx1 = PourbaixDiagram(
    entries,
    comp_dict={"Zn": 0.5, "Mn": 0.5},
    conc_dict={"Zn": 1e-6, "Mn": 1e-6},
    filter_solids=True,
)
plotter = PourbaixPlotter(pbx1)
plotter.get_pourbaix_plot().show()

entry = [entry for entry in entries if entry.entry_id == "mp-18751-GGA+U"][0]
plt = plotter.plot_entry_stability(entry)

)
```

ValueError                                Traceback (most recent call last)
Cell In[156], line 2
      1 entry = [entry for entry in entries if entry.entry_id == "mp-18751-GGA+U"][0]
----> 2 plt = plotter.plot_entry_stability(entry)

File ~\miniconda3\Lib\site-packages\pymatgen\analysis\pourbaix_diagram.py:1059, in PourbaixPlotter.plot_entry_stability(self, entry, pH_range, pH_resolution, V_range, V_resolution, e_hull_max, cmap, ax, **kwargs)
   1053 ax = self.get_pourbaix_plot(ax=ax, **kwargs)
   1054 pH, V = np.mgrid[
   1055     pH_range[0] : pH_range[1] : pH_resolution * 1j,
   1056     V_range[0] : V_range[1] : V_resolution * 1j,
   1057 ]
-> 1059 stability = self._pbx.get_decomposition_energy(entry, pH, V)
   1061 # Plot stability map
   1062 cax = ax.pcolor(pH, V, stability, cmap=cmap, vmin=0, vmax=e_hull_max)

File ~\miniconda3\Lib\site-packages\pymatgen\analysis\pourbaix_diagram.py:837, in PourbaixDiagram.get_decomposition_energy(self, entry, pH, V)
    833 entry_pbx_comp = Composition(
    834     {elt: coeff for elt, coeff in entry.composition.items() if elt not in ELEMENTS_HO}
    835 ).fractional_composition
    836 if entry_pbx_comp != pbx_comp:
--> 837     raise ValueError("Composition of stability entry does not match Pourbaix Diagram")
    838 entry_normalized_energy = entry.normalized_energy_at_conditions(pH, V)
    839 hull_energy = self.get_hull_energy(pH, V)

**ValueError: Composition of stability entry does not match Pourbaix Diagram**
I have the Poubaix Diagram without  ΔGpbx as bellow , 
![image|690x397](upload://1G5BNXlRCDFo0fjP5uVGgOIeykh.png)
How can I fix this erorr and the plot can show ΔGpbx,
I am really hope you can help in this case,
Thank you so much!
