### ISSUE TITLE
Failed pymatgen import in python v3.8

### ISSUE THREAD

**Issue by DeepanshS** [materialsproject/pymatgen#1994]
**Describe the bug**
Error importing the pymatgen module. 

```
>>> import pymatgen

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-a3a39e60e980> in <module>
----> 1 import pymatgen

~/anaconda3/lib/python3.8/site-packages/pymatgen/__init__.py in <module>
     12 from fnmatch import fnmatch
     13 
---> 14 import ruamel.yaml as yaml
     15 
     16 from monty.json import MontyEncoder, MontyDecoder, MSONable

ModuleNotFoundError: No module named 'ruamel'
```

**To Reproduce**
1. Install pymatgen using pip: ``pip install pymatgen``
2. Single line code: ``import pymatgen``

**Expected behavior**
No error

**Desktop/System info**
 - OS: macOS Big Sur, v11.0.1
 - Python v3.8.5

**Other details**

1. `ruamel.yaml` is installed on python v3.8.
```
>>> pip show ruamel.yaml

Name: ruamel-yaml
Version: 0.15.87
Summary: ruamel_yaml is a YAML parser/emitter that supports roundtrip preservation of comments, seq/map flow style, and map key order
Home-page: UNKNOWN
Author: Anthon van der Neut
Author-email: a.van.der.neut@ruamel.eu
License: UNKNOWN
Location: ~/anaconda3/lib/python3.8/site-packages
Requires: 
Required-by: pymatgen, conda, anaconda-project
```

2. The `import pymatgen` is successful on python v3.7.7

**Comment by vmeschke** [comment]
I've also had this issue.

**Comment by shyuep** [comment]
I just tried on my system and I cannot reproduce this. Can you try forcing a reinstall of ruamel?

`pip install --force ruamel.yaml`

**Comment by vmeschke** [comment]
Forcing the reinstall gives me the following error messages:

ERROR: Cannot uninstall 'ruamel-yaml'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by shyuep** [comment]
Hmmm.... are you using a virtual env?

**Comment by vmeschke** [comment]
I am. I have it activated for the pip install.

**Comment by shyuep** [comment]
Honestly, I am unsure what is wrong. There are some suggestions that using the pip install --ignore-installed flag would work. Maybe you can try that.

**Comment by vmeschke** [comment]
Changing the ruamel.yaml import from:
'''
import ruamel.yaml as yaml
'''
to: 
'''
import ruamel_yaml as yaml
'''
 in the following files:
1. __init__.py" (line 14)
2. ext/matproj.py (line 27)
3. analysis/local_env.py (line 23)

Solved it for me. It looks like the naming for ruamel just changed.

**Comment by shyuep** [comment]
That's very odd then. Because I did ruamel.yaml and it works. And this is the latest ruamel.yaml version.

```
Python 3.8.5 (default, Sep  4 2020, 02:22:02)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ruamel.yaml
>>> ruamel.yaml.__version__
'0.16.12'
```

**Comment by vmeschke** [comment]
Hmm, that is weird. I just did a fresh install of Anaconda and Python. Same thing still happens.

**Comment by vmeschke** [comment]
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ruamel.yaml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ruamel.yaml'
>>> import ruamel_yaml
>>>

**Comment by shyuep** [comment]
Version of ruamel?

**Comment by vmeschke** [comment]
>>> ruamel_yaml.__version__
'0.15.87'

**Comment by shyuep** [comment]
Ok, unclear what is happening. Apparently someone on anaconda did a patched version that uses ruamel_yaml. The official pip version is ruamel.yaml for sure. Anyway, this is an easy fix.

**Comment by shyuep** [comment]
Fix pushed.
