### ISSUE TITLE
Proposed change to how electrode are defined

### ISSUE THREAD

**Issue by jmmshn** [materialsproject/pymatgen#2012]
**Is your feature request related to a problem? Please describe.**
The current implementation of the insertion and conversion electrodes are not very db friendly.
The information that users will interface with is essentially the data defined in the abstract properties of each class in addition to the `_vpair` parameter.
However, the current implementation has custom `as_dict` and `from_dict` using the input entries.

**Describe the solution you'd like**
Convert the Abstract classes to `dataclass` that subclass `MSONables`.
This automatically creates the optimal `__init__`, `as_dict`, `from_dict` functions for the electrodes and voltages pairs.
Additionally, this will make the code significantly smaller

I tested the interaction between `MSONable` and `dataclass` and it seems to behave as expected.
```
from dataclasses import dataclass
from monty.json import MSONable
@dataclass
class TestClass(MSONable):
    """Class for keeping track of an item in inventory."""
    name: str
    unit_price: float
    quantity_on_hand: int = 0

tmp = TestClass(name="J", unit_price=12)
dd = tmp.as_dict()
print(A.from_dict(dd))
```

@mkhorton  if you are ok with this I will implement ASAP.

**Comment by shyuep** [comment]
NOte that db "friendliness" is a distant consideration to actual user-friendliness.
In this case, I do agree using dataclasses is better. The only reason why it wasn't done in the past is to maintain backwards compatibility. Since most other packages have abandoned py36, there is nothing stopping us from doing dataclasses anymore.

**Comment by jmmshn** [comment]
@shyuep Thanks for the quick reply!  I will make these changes and create a PR.
