### ISSUE TITLE
Pymatgen does not support reading EIGENVAL files from VASP < 5.4

### ISSUE THREAD

**Issue by mdforti** [materialsproject/pymatgen#2021]
https://github.com/materialsproject/pymatgen/blob/f6aa22ae178f3ea1e0332e8ec2a7731d6b260548/pymatgen/io/vasp/outputs.py#L5526

the line referenced skips if the eigenvalue table for a kpoint has only two columns. an option should be added for non spin polarized calculations where only two columns are present, one for band number and another for corresponding eigenvalue.

**Comment by mkhorton** [comment]
Hi @mdforti, thanks for reporting this. Would you willing to prepare a PR to fix?

**Comment by mdforti** [comment]
yes, of course. hope I do it correctly.

**Comment by arosen93** [comment]
Note to @janosh: The correct description here should be that Pymatgen does not support reading EIGENVAL files from pre-VASP 5.4, as noted in #2403.
