### ISSUE TITLE
feff_input_generation executable is broken: No module named 'pymatgen.cli.feff_input_generation'

### ISSUE THREAD

**Issue by drew-parsons** [materialsproject/pymatgen#2024]
pymatgen generates a handful of executable files invoking various pymatgen functionality, including pmg, 
gaussian_analyzer,  feff_input_generation

feff_input_generation appears to be broken and fails on attempting to load self-referential python submodule:
```
$ feff_input_generation 
Traceback (most recent call last):
  File "/usr/bin/feff_input_generation", line 33, in <module>
    sys.exit(load_entry_point('pymatgen==2020.12.18', 'console_scripts', 'feff_input_generation')())
  File "/usr/bin/feff_input_generation", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pymatgen.cli.feff_input_generation'
```

feff_input_generation is the calling script. As far as I'm aware it should not be a submodule of pymatgen.cli as implied in this error message.

All the other executable scripts run fine.

**Desktop:**
 - OS: Debian GNU/Linux
 - Version debian/unstable
 - Python 3.9
 - cython3 0.29.21

**Comment by shyuep** [comment]
Yes, this has been deprecated and removed. Pls use the modules directly to generate the input files.

**Comment by drew-parsons** [comment]
But the executable scripts are still being generated.  They are listed in the entry_points list in setup.py.  Hence this bug is still open.

**Comment by shyuep** [comment]
Yes, I just removed them in a new commit. This will be fixed in the next release.

**Comment by drew-parsons** [comment]
I see it, thanks @shyuep .
