### ISSUE TITLE
enable installation CI testing

### ISSUE THREAD

**Issue by drew-parsons** [materialsproject/pymatgen#2025]
For Linux (and other) distributions, it would be good to be able to regularly test the pymatgen installation is working correctly (configuration integration CI testing).

pymatgen already provides an extensive amount of tests.  They can't really be used with CI testing however.  The location of input files is hardcoded to an outside directory, e.g. core/tests/test_surface.py uses `path = os.path.join(cwd, "..", "..", "..", "test_files", "surface_tests", path_str)`

If a distribution installs pymatgen into /usr/lib/python3/dist-packages/pymatgen, then it means input files would be expected in /usr/lib/python3/dist-packages/test_files, which is not the right place for this kind of data.  /usr/share/pymatgen/test_files would be more appropriate.

Even in a private user installation, it means test files would be expected in ~/.local/lib/python3.9/site-packages/test_files, which again is not a good path for such data.

The pymatgen tests should allow for a different location of the test_files dir, possibly checking a hierarchy of alternatives, possibly with an override that can be set at runtime, e.g. via environment variable PYMATGEN_TEST_FILES or via pytest_addoption in conf.py (cf. https://docs.pytest.org/en/stable/example/simple.html#dynamically-adding-command-line-options)

Alternatively, tests could be placed in a separate tests dir, separate from the actual module dirs.

I'm preparing packaging for the Debian GNU/Linux distribution, but the point applies to other distributions.

**Comment by shyuep** [comment]
Generally the tests are meant to be operated on a cloned repository of pymatgen, rather than being run on a pip install version. None of the test files are provided in the standard wheels or tar.gz distributions because they are hundreds of Mb. So these are mainly provided just in the repository for cloning by developers.

Note that pymatgen already runs CI on the repo. These can be seen from the Github Actions.

**Comment by drew-parsons** [comment]
Your response does not address the issue raised.

It needs to be possible for distributions to be able to test the module as installed.  Testing the repo does not achieve that.

**Comment by shyuep** [comment]
As I said, the test files are very large. Neither the tests nor the input files needed for testing are distributed with the installation. This is the reality with the kind of files we have. It is theoretically possible to do the tests such that those that do not require input files can be tested using some script. But that would test a minuscule fraction of what pymatgen does. If you have a good suggestion on a way to design the tests, I am all ears. As it is, pymatgen is tested on both Mac and Linux platforms.

**Comment by drew-parsons** [comment]
github CI testing does not achieve CI testing of distribution installations.  We need to confirm, for instance, if new versions of numpy or other modules updated in Debian will break client packages such as pymatgen.

The pypi source tarball does not include the test files, but the github source tarball does include them.

Currently the test files are embedded in the github source directories alongside the python module files. I recommend placing test files in a separate directory with hierarchical structure mirroring the module files which they are testing. Something like

```
pymatgen/
    __init__.py
    core/
        __init__.py
        ...
    ...
test_files/
    ATOMS
    AgO_kpath_test.cif
    ...
tests/
    __init__.py
    test_init.py
    core/
        __init__.py
        slab.cif
        test_bonds.py
        ...
    ...
```
rather than
```
pymatgen/
    __init__.py
    tests/
        __init__.py
        test_init.py
    core/
        __init__.py
        ...
        tests/
            __init__.py
            slab.cif
            test_bonds.py
            ...
    ...
test_files/
    ATOMS
    AgO_kpath_test.cif
    ...
tests/
    __init__.py
    test_init.py
    core/
        slab.cif
        test_bonds.py
        ...
 ```

In that case `cd tests; pytest` could run the tests for all types of installation, whether in-source, pypi or distribution installation.

The relationship between the tests and the input files in the `test_files` dir can also be made more robust by allowing for a different location of the test_files dir, possibly checking a hierarchy of alternatives, possibly with an override that can be set at runtime, e.g. via environment variable PYMATGEN_TEST_FILES or via pytest_addoption in conf.py

**Comment by shyuep** [comment]
Ok, I have implemented your suggestion to use an environmental variable. You can specify the root location of test files using PMG_TEST_DIR. I will not be making the rest of the changes, e.g., the structure of the tests hirerarchy since that will require too much maintenance. Note that having tests directories in the modules is standard practice (e.g., see numpy own tests).

**Comment by drew-parsons** [comment]
Thanks @shyuep , I'll give PMG_TEST_DIR a try.

**Comment by drew-parsons** [comment]
Use of PMG_TEST_FILES_DIR works well enough.  Some tests were missed in the patch. I'll prepare a PR.
