### ISSUE TITLE
Calling specie from a site gives two different object classes

### ISSUE THREAD

**Issue by mm04926412** [materialsproject/pymatgen#2026]
Depending on the source of the structure the return value for "Site.specie" is either an specie object or an element object. When I'm working with a database of pymatgen structures this seems to vary depending on the data source. This causes inconsistent behaviour with attempting to access the atomic number with .Z as specie.Z and specie.element.Z can report different values for some structures.

It seems like a very strange design choice to me that two different classes can be returned from the same method?

**Comment by shyuep** [comment]
I would need a bit more context the inconsistent behavior you are referring to. Python uses duck typing. Objects that basically implement a common subset of methods/properties can substitute for each other.

There are instances where people want to just use Element to represent the site, e.g., when they are not interested or do not know the oxidation state. For example, an alloy like CuAu. There are other instances where they want to specify a formal oxidation state. Say Li2O with Li+ and O2-. 

In all cases, specie.Z and specie.element.Z should return exactly the same number. If it doesn't, something is seriously wrong. But I would need you to provide an example code demonstrating such a problem.

**Comment by mm04926412** [comment]
Using specie.element.Z where only an element is defined results in the error

"Object of type Element has no member element" 

The specific line where I get different results is 

token_list = torch.tensor(
            [int(i.specie.Z) for i in structure], dtype=torch.long
        )

where

token_list = torch.tensor(
            [int(i.specie.element.Z) for i in structure], dtype=torch.long
        )

is stable for compounds with a defined oxidation state but gives "Object of type Element has no member element" otherwise.

the version I'm using is '2020.12.18'

**Comment by shyuep** [comment]
Well, in general, you should not be using specie.element.Z since specie.Z basically works for both Element and Specie.

**Comment by mm04926412** [comment]
Ah ok that makes sense, I'm stil confused about the strange behaviour though. For context I have structure objects for the ICSD database and every now and again some of tensors generated by the list comprehension above have arbitary huge values in them with it furthermore being arbitrary if they are positive or negative.

**Comment by shyuep** [comment]
The only way that happens is that your ICSD structure contains a specie notation that is not actually a valid element. Then a DummySpecie is generated, for which the Z is a nonsensical value.

**Comment by mm04926412** [comment]
Would it be possible to have this raise an Exception or default to nan? rather than a random int?

**Comment by shyuep** [comment]
That is not possible. There are many instances where we want the DummySpecie (e.g., to represent vacancies). You can catch this by checking whether the Z is < 100.

**Comment by mm04926412** [comment]
I understand that but you don't want DummySpecie().Z to ever be called right? It seems there is already precedent to return NaN when a request has no physical meaning?

**Comment by shyuep** [comment]
We cannot use NaN. Otherwise a DummySpecie(X) and DummySpecie(Z) will have the same Z and that can result in issues when you want to treat multiple dummy specie.
