### ISSUE TITLE
Lattice parameters are not extracted from NWChem output

### ISSUE THREAD

**Issue by merkys** [materialsproject/pymatgen#203]
It seems that the lattice parameters are not extracted from the output of NWChem, a feature that would be nice to have. I wonder whether the developers feel positive about this development. I could implement it and present in a form of pull request if there is any possibility of such an improvement to get into the packaged version of pymatgen.

**Comment by shyuep** [comment]
Thanks. That would be much appreciated.
We have not implement lattice parameters as we primarily use NWChem for molecular calculations at the moment. But I am sure this feature would be useful for many other users.

**Comment by merkys** [comment]
Very well then, I will open my fork of the code and start implementing the lattice parameter extraction there.

**Comment by merkys** [comment]
Feature implemented in pull request #205 (merged).
