### ISSUE TITLE
Test coverage for cmd line stuff

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#2030]
Right now, the unit tests are not being run for a number of those requiring certain cmd line utilities. (see recent tests).

1. mcsqs 
2. critic2
3. aconvasp
4. zeo 

I would like to address at least a number of those, esp 1-3. We do not need executables for all platforms, but at the minimum, the Ubuntu tests should aim for 100% coverage (I have managed to push it up quite significantly). @mkhorton can you make sure at least 1-3 are addressed and we will think of adding zeo? All we need is to have compiled and executable versions in the pymatgen/cmd_line directory under appropriate structures.

**Comment by mkhorton** [comment]
I can deal with `mcsqs` and `critic2` since I am familiar with both and compilations are straight-forward. I don't know who's responsible for the `aconvasp` and `zeo` interfaces?

**Comment by shyuep** [comment]
Sure, we can start with those 2. The other two are not that important for now.

**Comment by mkhorton** [comment]
Rather than committing compiled versions in the repository, I think we might instead have a custom Dockerfile with the utilities pre-installed, and launch from this Dockerfile in the test workflows. This is supported by GitHub Actions. Thoughts?

**Comment by shyuep** [comment]
Sounds good to me.
