### ISSUE TITLE
"Failed to build spglib" while installing pymatgem

### ISSUE THREAD

**Issue by pratapslair** [materialsproject/pymatgen#2045]
I tried to install 'pymatgem' using 'pip install pymatgem' command. It threw an error saying 
"ERROR: Failed building wheel for spglib
Failed to build spglib
ERROR: Could not build wheels for spglib which use PEP 517 and cannot be installed directly"

The python version i am using is, python 3.8

Can you please let me know what I should do to troubleshoot this?
![Capture](https://user-images.githubusercontent.com/41544177/106348635-9fa39080-62ed-11eb-9e1c-484156a2c3a4.JPG)

**Comment by shyuep** [comment]
Pls report your OS when reporting issues. For this, I would recommend you try using conda installation as recommended in the official pymatgen documentation first.

**Comment by pratapslair** [comment]
OS is Windows 10.

**Comment by pratapslair** [comment]
The issue was resolved after i updated Microsoft Visual C++ greater than 14.0. Thank you.
