### ISSUE TITLE
Issue with EnumlibAdaptor during doping transformation

### ISSUE THREAD

**Issue by marcoloco23** [materialsproject/pymatgen#2051]
While trying to perform a doping transformation, I get the following attribute error:

'EnumlibAdaptor' object has no attribute 'structures'.

The error occurs on line 457 of "https://github.com/materialsproject/pymatgen/blob/v2021.1.28/pymatgen/transformations/advanced_transformations.py#L1095-L1258".

It seems as though 'EnumlibAdaptor' has an attribute "structure" but not "structures" which leads to the error.

**Comment by shyuep** [comment]
This error typically occurs if the enumeration was unsuccessful. Either the cell is too large to be enumerated or the enum.x exited with error.
