### ISSUE TITLE
get_computed_entry() is failing in the Vasprun

### ISSUE THREAD

**Issue by kshumilov** [materialsproject/pymatgen#2052]
**Describe the bug**
If `io.vasp.outputs.Vasprun()` is describing a run with IVDW tag set to `int` the function `get_computed_entry()` is failing.
The bug is hiding in the line [759](https://github.com/materialsproject/pymatgen/blob/v2021.1.28/pymatgen/io/vasp/outputs.py#L759) where the output of `get()` method on the `self.incar` returns an integer, which doesn't have `strip()` method.

**To Reproduce**
1. Have a `vasprun.xml` with IVDW set to `int`
2. Get `Vasprun` object
3. Call `Vasprun.get_computed_entry()`

Unable to provide file exact IVDW file, but technically it's not needed since the `Vasprun()` can be constructed with the custom `Incar` object.

**Expected behavior**
`ComputedStructureEntry` is returned successfully with correctly identified run IVDW variant.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Version 2021.1.28 

**Additional context**
Traceback
```python
/usr/local/Caskroom/miniconda/base/envs/quantum/lib/python3.9/site-packages/pymatgen/io/vasp/outputs.py in get_computed_entry(self, inc_structure, parameters, data)
    807         if parameters:
    808             param_names.update(parameters)
--> 809         params = {p: getattr(self, p) for p in param_names}
    810         data = {p: getattr(self, p) for p in data} if data is not None else {}
    811 

/usr/local/Caskroom/miniconda/base/envs/quantum/lib/python3.9/site-packages/pymatgen/io/vasp/outputs.py in <dictcomp>(.0)
    807         if parameters:
    808             param_names.update(parameters)
--> 809         params = {p: getattr(self, p) for p in param_names}
    810         data = {p: getattr(self, p) for p in data} if data is not None else {}
    811 

/usr/local/Caskroom/miniconda/base/envs/quantum/lib/python3.9/site-packages/pymatgen/io/vasp/outputs.py in run_type(self)
    757         if self.parameters.get("LUSE_VDW", False):
    758             rt += "+rVV10"
--> 759         elif self.incar.get("IVDW", "").strip().upper() in IVDW_TYPES:
    760             rt += "vdW-" + IVDW_TYPES[self.incar.get("IVDW", "").strip().upper()]
    761         elif self.incar.get("IVDW"):

AttributeError: 'int' object has no attribute 'strip'
```

**Comment by shyuep** [comment]
Thanks for reporting this. @rkingsbury I believe this was added by you? Can you fix it pls? Thanks.

**Comment by rkingsbury** [comment]
Thanks for reporting @kshumilov . @shyuep see #2054 for a fix.
