### ISSUE TITLE
latexify_ion is broken

### ISSUE THREAD

**Issue by rkingsbury** [materialsproject/pymatgen#2056]
**Describe the bug**
The `latexify_ion` method in `analysis.pourbaix_diagram` does not work; it just returns the input formula.

**To Reproduce**
```
from pymatgen.analysis.pourbaix_diagram import latexify_ion
latexify_ion('Na+')
'Na+'
latexify_ion('SO4-2')
'SO4-2'
```

**Expected behavior**
The formula would be reformatted with appropriate LateX sub/superscripts

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: latest Github master as of Feb 3, 2021

**Comment by rkingsbury** [comment]
Proposed fix:

Changing the regex match pattern from
`
re.sub(r"()\[([^)]*)\]", r"\1$^{\2}$", formula)
`
to 
`
re.sub(r"([-+][\d\.]*)", r"$^{\1}$", )
`

Seems to work as expected. See [regex tester](https://regex101.com/).

It seems to me it might be better to integrate this with `pymatgen.util.string.latexify` and deprecate `latexify_ion` rather than have a standalone function to recognize charged formulae. Thoughts?

**Comment by shyuep** [comment]
Go ahead and integrate with pymatgen.util.string latexify. Frankly, I don't know why the heck someone implemented a separate one elsewhere.

**Comment by mkhorton** [comment]
Actually, if we're proposing changes, I think I would prefer a `.latex_string()` option on Species, Composition, etc. -- then people don't have to find or hunt for the appropriate util function.

**Comment by utf** [comment]
Please don't remove the pymatgen.util.string function though.

**Comment by shyuep** [comment]
Pls do not add a method to every single class. That would be a horrendous way to do this. I think we should use a MixIn class that implements to_latex_string that works for most use cases,eg some adaptation of current latexify.

**Comment by shyuep** [comment]
Eg MSONable is the classic example of a mixin.

**Comment by mkhorton** [comment]
Why would it be horrendous? We have `__str__` representations on a class, this is a variant of `__str__`

**Comment by mkhorton** [comment]
We're not talking about a lot of classes here, there's `Composition`, `Species`, `SpaceGroup`, `PointGroup` maybe.

**Comment by shyuep** [comment]
There are classes you haven't thought of. Ion. Defects. There are also alternative conversions that would be extremely useful. Eg to_html_string. Even if it is 3-4 classes, having ONE implementation rather than the same code replicated in multiple locations.

**Comment by mkhorton** [comment]
> Even if it is 3-4 classes, having ONE implementation rather than the same code replicated in multiple locations.

Yes, this is fair -- I was presuming that it wouldn't be a common implementation, e.g. Species has to deal with superscripts, SpaceGroup handles minus signs as overbars etc. I was indeed neglecting Ion, Defects however.

**Comment by shyuep** [comment]
I have added a basic implementation in https://github.com/materialsproject/pymatgen/commit/0d38d3f9e86ad3dfb498d2db28f3f28c253bf1c8 .
This works on both Specie and compositions.

**Comment by rkingsbury** [comment]
> I have added a basic implementation in [0d38d3f](https://github.com/materialsproject/pymatgen/commit/0d38d3f9e86ad3dfb498d2db28f3f28c253bf1c8) .
> This works on both Specie and compositions.

@shyuep thanks. This implementation requires one to choose EITHER subscripts or superscripts though, which I don't think is necessary. We can have a single method that will, for example, convert `B(OH)4-` to `B(OH)$_4^-$`. This can be accomplished with a combination of the regex pattern in the existing `latexify` and the one in my post up above.

The only caveat is that the charge of multivalent species must be written _after_ the + or - sign (e.g., `Fe+2` not `Fe2+`, which is something we can specify in the docstring. I think this is a good practice to enforce anyway as it prevents ambiguity. What do you think?

**Comment by mkhorton** [comment]
> The only caveat is that the charge of multivalent species must be written after the + or - sign (e.g., Fe+2 not Fe2+, which is something we can specify in the docstring. I think this is a good practice to enforce anyway as it prevents ambiguity. What do you think?

The problem with this is that `latexify` needs to work on, say, the output of a `str(Species)` which would do `Fe2+`, likewise `Species.from_str` has to support this. I'm not sure if this notation is strictly conventional but it's definitely common.

**Comment by rkingsbury** [comment]
> > The only caveat is that the charge of multivalent species must be written after the + or - sign (e.g., Fe+2 not Fe2+, which is something we can specify in the docstring. I think this is a good practice to enforce anyway as it prevents ambiguity. What do you think?
> 
> The problem with this is that `latexify` needs to work on, say, the output of a `str(Species)` which would do `Fe2+`, likewise `Species.from_str` has to support this. I'm not sure if this notation is strictly conventional but it's definitely common.

OK that's a good point. Can / should we consider changing the output of `str(Species)` then? I feel that notation is outdated and ambiguous but I don't know what's common practice in every field.

**Comment by shyuep** [comment]
@rkingsbury @mkhorton This is an initial attempt. Feel free to modify if you think there is a better way. The general idea with the mix-in is that you can always override one method. E.g., let's say we want to deal with space groups and it is not clear that a single regex can work for Species, Composition and Spacegroups. So for Spacegroups, we can implement a special to_latex method. It will still inherit the mix-in class because the latex->HTML is much easier and well-defined than basic string -> latex. I am sure there are other markup languages we can think of, e.g., markdown.

There is also some code for unicode versions, which are helpful. I think those can be added relatively easily though they don't work in all instances.

**Comment by shyuep** [comment]
As for from_str, I don't think there is a standard definition. I would suggest we follow the convention that the `__repr__` is usually the more complete string output and stipulate that from_str should work with the output from `repr(obj)`. `__str__` is usually the more user-friendly output that may not include all information necessary to reconstitute the class.

**Comment by shyuep** [comment]
One other option: we define in Stringify a "to_pretty_string" method that defaults to `__str__`. All other methods then works on the to_pretty_string output. That will allow us to decouple the actual output of `__str__` and a pretty output when we want to.

**Comment by shyuep** [comment]
@rkingsbury @mkhorton I have a mostly working implementation at https://github.com/materialsproject/pymatgen/commit/8455650c5a40a8a5c69f79df015ab0e9580a6429 .

Now a general method implements latex, html and unicode strings and a `to_pretty_string` is the input (defaulting to just `__str__`).

I am going to just leave this for now. You can make changes if you desire, including fixing the Ion latex string.

**Comment by mkhorton** [comment]
Great, thanks @shyuep!
