### ISSUE TITLE
pymatgen installation

### ISSUE THREAD

**Issue by frank-lin-liu** [materialsproject/pymatgen#2063]
When I install pymatgen in windows 10 using "python setup.py install", I have the following error,

error: command 'C:\\Program Files (x86)\\Microsoft Visual studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

Please, could you help me out?

**Comment by shyuep** [comment]
Pls use the installation using conda as recommended in the pymatgen documentation.
