### ISSUE TITLE
Gcc 8.3 errors when compiling Zeo++

### ISSUE THREAD

**Issue by feacluster** [materialsproject/pymatgen#2067]
I am following your instructions here for the pymatgen.io.zeopp module:

https://pymatgen.org/pymatgen.io.zeopp.html#zeo-installation-steps

I get gcc errors when attempting step 5(c). The first error is:

zeo/netstorage.cpp: In function ‘PyObject* __Pyx_PyCFunction_FastCall(PyObject*,
zeo/netstorage.cpp:8776:69: error: too many arguments to function
     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);

This is then followed by a few other errors before the compilation fails.

I suspect it is because I am using the latest gcc 8.3.1

(VOID) [hussaif1@7920 cython_wrapper]$ gcc --version
gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)

Or could it be something else?

**Comment by feacluster** [comment]
I tried on another system with older GCC 4.8.5 but got the same errors. The errors are:

zeo/netstorage.cpp: In function ‘PyObject* __Pyx_PyCFunction_FastCall(PyObject*, PyObject**, Py_ssize_t)’:
zeo/netstorage.cpp:8776:69: error: too many arguments to function
     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
                                                                     ^
zeo/netstorage.cpp:8766:15: warning: unused variable ‘result’ [-Wunused-variable]
     PyObject *result;
               ^
zeo/netstorage.cpp:8767:9: warning: unused variable ‘flags’ [-Wunused-variable]
     int flags;
         ^
zeo/netstorage.cpp: In function ‘void __Pyx__ExceptionSwap(PyThreadState*, PyObject**, PyObject**, PyObject**)’:
zeo/netstorage.cpp:10133:24: error: ‘PyThreadState’ has no member named ‘exc_type’
     tmp_type = tstate->exc_type;
                        ^
zeo/netstorage.cpp:10134:25: error: ‘PyThreadState’ has no member named ‘exc_value’
     tmp_value = tstate->exc_value;
                         ^
zeo/netstorage.cpp:10135:22: error: ‘PyThreadState’ has no member named ‘exc_traceback’
     tmp_tb = tstate->exc_traceback;
                      ^
zeo/netstorage.cpp:10136:13: error: ‘PyThreadState’ has no member named ‘exc_type’
     tstate->exc_type = *type;
             ^
zeo/netstorage.cpp:10137:13: error: ‘PyThreadState’ has no member named ‘exc_value’
     tstate->exc_value = *value;
             ^
zeo/netstorage.cpp:10138:13: error: ‘PyThreadState’ has no member named ‘exc_traceback’
     tstate->exc_traceback = *tb;
             ^

**Comment by shyuep** [comment]
We can't really help you on this since zeopp is not a pymatgen code per se. Pls contact the Zeo++ authors on its installation and usage.
