### ISSUE TITLE
Installation problem in Google colab

### ISSUE THREAD

**Issue by Amadeus-System** [materialsproject/pymatgen#2071]
Hi. I was using pymatgen in google colab. 
In google colab, pymatgen is not installed , so I was using pymatgen by installing every time when I need to use it.
"!pip3 install pymatgen" or "!pip install pymatgen" command was normally working a few days ago, but now it's not working so I can't use pymatgen in colab.
I need your help. please teach me how to install pymatgen in google colab.
I think it's because some sort of problem happend in pymatgen library.  

The following is my capture image for the error and message.

"""
Collecting pymatgen
  Downloading https://files.pythonhosted.org/packages/9b/50/a22eb063ca5ceb27c2be7e51e775ee4b5ade664525be143a2b1b77e4cc70/pymatgen-2021.2.16.tar.gz (3.0MB)
     |████████████████████████████████| 3.0MB 6.4MB/s 
  Installing build dependencies ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-u3bnrkjk/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'numpy>=1.20.1' 'setuptools>=43.0.0' Check the logs for full command output.
"""

![pymatgen error](https://user-images.githubusercontent.com/76824867/108536058-54decc80-731f-11eb-8eae-903d0735269f.PNG)

I expect your kind answer. 
Thank you.

**Comment by mkhorton** [comment]
The issue is that Google won't let you install numpy 1.20.1 (try `!pip install numpy==1.20.1` to verify), I think because it's not supported by Python 3.6 (the default interpreter). For now, I would advice you install an older version of pymatgen e.g. using `pip install pymatgen==` until Google supports this.

**Comment by shyuep** [comment]
If google collab allows you to install conda, you can do that instead.
