### ISSUE TITLE
Adding a more discriminative hash for Composition

### ISSUE THREAD

**Issue by CompRhys** [materialsproject/pymatgen#2076]
For a project I am doing I have produced a large screening library of compositions, to reduce the computation I need to do at the next stage I want only the unique compositions. Unique compositions will be determined by hashing and then within each hashbin checking the n(n-1) equality options. The current hash ends up hashing very large numbers of compositions to the same hash code

```  python  
    def __hash__(self):
        """
        Minimally effective hash function that just distinguishes between
        Compositions with different elements.
        """
        hashcode = 0
        for el, amt in self.items():
            if abs(amt) > Composition.amount_tolerance:
                hashcode += el.Z
        return hashcode
```

A more discriminative hash might be:
```python
from math import floor

    def __hash__(self):
        """
        Minimally effective hash function that just distinguishes between
        Compositions with different elements.
        """
        sym_amt = {
            el: floor(1e7*(amt + Composition.amount_tolerance * 2))
            for el, amt in self.get_el_amt_dict().items()
            if abs(amt) > Composition.amount_tolerance
        }

        syms = sorted(sym_amt.keys())
        formula = [s + formula_double_format(sym_amt[s], False) for s in syms]
        return hash(" ".join(formula))
```

### robustness

```
>>> hash(Composition(f"O{0.8}Fe{0.2}"))
-2228561952991124878
>>> hash(Composition(f"O{0.8}Fe{0.2}Na{1e-9}"))
-2228561952991124878
>>> hash(Composition(f"O{0.8}Fe{0.2+Composition.amount_tolerance}"))
-2228561952991124878
>>> hash(Composition(f"O{0.8}Fe{0.2-Composition.amount_tolerance}"))
-2228561952991124878
>>> hash(Composition(f"O{0.8}Fe{0.2-2*Composition.amount_tolerance}"))
-2228561952991124878
>>> hash(Composition(f"O{0.8}Fe{0.2-5*Composition.amount_tolerance}"))
-414002531081527414
>>> hash(Composition(f"O{0.8+Composition.amount_tolerance}Fe{0.2-2*Composition.amount_tolerance}"))
-2228561952991124878
>>> hash(Composition(f"Cl{0.8+Composition.amount_tolerance}Na{0.2-2*Composition.amount_tolerance}"))
1665041687307082964
>>> hash(Composition(f"Fe{0.2}O{0.8-Composition.amount_tolerance}"))
-2228561952991124878
```

@shyamd do you see any issues with this change to the hash? I think it maintains a greater level of robustness than `__eq__`.  

an issue might be that the current hash is not salted but the proposed hash would be 

### speed
for a set of 18,322 compositions where 14,201 are unique I timed the following `foo()` function
```python
df = pnd.read_csv("data/hash-test-small.csv", na_filter=False)
df = StrToComposition(target_col_id="composition_obj").featurize_dataframe(df, "composition")
df["frac_comp"] = df["composition_obj"].apply(lambda x: x.fractional_composition)

def foo():
    print(len(df["frac_comp"].unique()))
```

```
proposed: 1 loop, best of 5: 793 msec per loop
current: 1 loop, best of 5: 4.94 sec per loop
```

for a set of 454,484 where 317,764 are unique timing the new hash gives 
```
proposed: 1 loop, best of 5: 23.1 sec per loop
```
The current hash is still running whilst writing this post.

**Comment by shyamd** [comment]
A good hash function has two qualities:
1) It's fast
2.) It hashes very similar but different things to completely different hashes. The more granual that definition of similar is, the better the hash function.

Your 3rd example is a good test to implement IMHO. Something like:
``` python
assert hash(Composition(f"O{0.8}Fe{0.2}")) == hash(Composition(f"O{0.8}Fe{0.2}Na{1e-9}"))
assert hash(Composition(f"O{0.8}Fe{0.2}")) != hash(Composition(f"O{0.8}Fe{0.2+Composition.amount_tolerance}"))
```

Why not just do something like
```python
def __hash__(self)
    return hash(self.formula)
```

**Comment by CompRhys** [comment]
I think without the manipulations the formula alone isn't robust, as a counter-example: 

```
>>> Composition(f"O{0.2+Composition.amount_tolerance}Fe{0.8}") == Composition(f"O{0.2}Fe{0.8}")
True
>>> hash(Composition(f"O{0.2+Composition.amount_tolerance}Fe{0.8}").formula) == hash(Composition(f"O{0.2}Fe{0.8}").formula)
False
```

**Comment by shyamd** [comment]
Ah! Ok, I didn't realize that those two compositions should actually be equal. Then, this looks mostly good. The rounding logic is a bit confusing, so you might want some comments on why you chose the numbers you did. For instance, I don't understand why 1e7 is the right multiplier. It should probably something like divide by tolerance since that could change.

 You might drop the switch to a string and even the `get_el_amt_dict` and use something like:
```python

    def __hash__(self):
        """
        Minimally effective hash function that just distinguishes between
        Compositions with different elements.
        """
        sym_amt = {
            el: floor(1e7*(amt + Composition.amount_tolerance * 2))
            for el, amt in self.items()
            if abs(amt) > Composition.amount_tolerance
        }

        syms = sorted(sym_amt.keys())
        formula = [s + formula_double_format(sym_amt[s], False) for s in syms]
        return hash(frozenset(sym_amt.items()))
```

**Comment by CompRhys** [comment]
Using `frozenset` is faster and I split out the 1e7 coefficient into a divide by `tol` and multiply by 10. The 2 is to deal with the case where the delta is equal to the tol, anything larger than 1 would do so I picked 2 because it only takes one character...

```python
    def __hash__(self):
        """
        Minimally effective hash function that just distinguishes between
        Compositions with different elements.
        """
        sym_amt = {
            el: floor((amt + Composition.amount_tolerance * 2) / (Composition.amount_tolerance * 10))
            for el, amt in self.items()
            if abs(amt) > Composition.amount_tolerance
        }

        return hash(frozenset(sym_amt.items()))
```
```
1 loop, best of 5: 547 msec per loop
```

**Comment by shyamd** [comment]
Yeah! I like it. As long as this passes all existing tests, I think it's a good modification. The docstring will need an update to be clear it now distinguishes the full composition, but that can be in the PR :)

**Comment by shyuep** [comment]
I don't think something this complicated ius necessary. The problem with the earlier hash is mainly because it just sums the Z. While that is somewhat ok, there are many ways to arrive at the same Z. We just need to use something else. What if you just change `el.Z` to `el.Z * el.X`? My suspicion is that you will get most of the speed savings.

**Comment by CompRhys** [comment]
Can't use `el.X` due to noble gases but trying `int(el.Z * el.mendeleev_no)` took
```1 loop, best of 5: 1.01 sec per loop```
without wrapping in int I got an error

**Comment by shyuep** [comment]
Cool. That is already just 2x of the solution with the amounts. Will this be sufficient? I am loath to introduce things like floating point comparisons, floors, etc. It is a lot more prone to errors in edge cases.

**Comment by shyamd** [comment]
Why not just `hash({frozentset(self.elements)})` then?

**Comment by CompRhys** [comment]
on the larger set `hash(frozenset(self.elements))` gave 
```
1 loop, best of 5: 21.1 sec per loop  (365msec on small)
```

whilst the one with the amounts was
```
1 loop, best of 5: 14.9 sec per loop  (616msec on small)
```

as such `hash(frozenset(self.elements))` is performant enough to be useable at the current size of the screening set if I end up screening millions of things it might be slow but in that case I have something workable

**Comment by shyuep** [comment]
NIce. Let's implement that then.

**Comment by shyuep** [comment]
BTW, you can probably get a small bit of performance boost from using `self._data.keys()` instead of `self.elements`. The former uses a built in attribute.

**Comment by CompRhys** [comment]
okay making PR and adding a small test for robustness
