### ISSUE TITLE
Context managers for perturbing and translating lattice sites

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#2081]
**Is your feature request related to a problem? Please describe.**

[`Structure.perturb()`](https://pymatgen.org/pymatgen.core.structure.html#pymatgen.core.structure.Structure.perturb) and [`Structure.translate_sites()`](https://pymatgen.org/pymatgen.core.structure.html#pymatgen.core.structure.Structure.translate_sites) make in-place modifications to the lattice sites of a crystal. This can lead to user errors when people don't consider the implications of permanent changes for downstream tasks or simply forget to revert to the original positions manually.

**Describe the solution you'd like**

A way to avoid these pitfalls would be to provide new methods, say `Structure.perturbed()` and `Structure.translated_sites()`, as context managers which perform temporary lattice site modifications and revert back to the original positions when the context exits. The new API could look like this:

```py
from pymatgen import Structure

crystal = Structure()

print('original')
print(crystal.cart_coords)

with crystal.perturbed(0.05) as cryst:
    print('perturbed coordinates')
    print(cryst.cart_coords)

print('unchanged original')
print(crystal.cart_coords)
```

which would print:

```txt
original
[[ 3.34134688  0.94786948  1.78078667]
 [ 0.69595394  3.04452513  1.31349259]
 [ 2.26161323  2.87664712 -0.55981345]
 [ 1.34395046  1.61686791  3.70986864]
 [ 3.64365627  4.24525709 -3.22423295]]
perturbed coordinates
[[ 3.31185334  0.92091982  1.80484822]
 [ 0.64055798  3.06264923  1.26460508]
 [ 2.19797793  2.82148173 -0.50081053]
 [ 1.33806345  1.61946541  3.75244629]
 [ 3.67168166  4.20351193 -3.19816276]]
unchanged original
[[ 3.34134688  0.94786948  1.78078667]
 [ 0.69595394  3.04452513  1.31349259]
 [ 2.26161323  2.87664712 -0.55981345]
 [ 1.34395046  1.61686791  3.70986864]
 [ 3.64365627  4.24525709 -3.22423295]]
```

and be implemented like this:

```py
from contextlib import contextmanager

import numpy as np

class Structure:

    @contextmanager
    def perturbed(self, std=0.03):
        try:
            old_coords = self.cart_coords

            # loop over each site and apply Gaussian noise to its position
            for site in self:
                perturbation = np.random.normal(0, std, [3])
                site.coords += perturbation

            yield self

        finally:
            for site, coords in zip(self, old_coords):
                site.coords = coords
```

**Additional context**

Such temporary lattice perturbations are useful for on-the-fly data augmentation while training structure-based ML models, see e.g. ["Crystal Structure Search with Random Relaxations Using Graph Networks"](https://arxiv.org/abs/2012.02920).

**Comment by janosh** [comment]
Based on preliminary testing, the new API would be about twice as fast as the current one, probably due to not [creating new `Site`s to overwrite existing ones in `translate_sites`](https://github.com/materialsproject/pymatgen/blob/33ad121f3ad99ab5e61d4142d4200e7519e12d28/pymatgen/core/structure.py#L3995) but simply reusing them (as the operation is destructive anyway):

```py
from contextlib import contextmanager
from time import perf_counter
from pymatgen import MPRester

mpr = MPRester(api_key="foobar")
cystal = mpr.get_structure_by_material_id('mp-1000')

@contextmanager
def perturb_crystal(crystal, std=0.03):
    try:
        old_coords = crystal.cart_coords

        # loop over each site and apply Gaussian noice to position
        for site in crystal:
            perturbation = np.random.normal(0, std, [3])
            site.coords += perturbation

        yield crystal

    finally:
        for coords, site in zip(old_coords, crystal):
            site.coords = coords


start = perf_counter()

for _ in range(10000):
    with perturb_crystal(crystal) as cryst:
        pass

print(f"context took {perf_counter() - start:.3f} sec")


start = perf_counter()

for _ in range(10000):
    old_coords = crystal.cart_coords
    crystal.perturb(0.03)
    
    for site, coords in zip(crystal, old_coords):
        site.coords = coords

print(f"existing perturb() took {perf_counter() - start:.3f} sec")
```

This printed

```txt
Connection established to Materials Project database, version 2021_02_08.
context took 0.581 sec
perturb() took 1.032 sec
```

**Comment by shyuep** [comment]
I don't think this is a common enough use case to justify a context manager. It is rare that you want to "go back" to the original structure after you perturb it. Even when you want to keep the structure, there are simpler ways to do this.

E..g.

```python
s2 = structure.copy()
s2.perturb(0.01)
```

or if you are going to be doing it millions of times,

```
lattice = structure.lattice
species = structure.species
coords = structure.cart_coords
for _ in range(1000000):
    new_coords = coords + np.random.normal(coords.shape[0], 3)
    s2 = Structure(lattice, species, new_coords)
```

**Comment by janosh** [comment]
Thanks for the quick reply!

>  I don't think this is a common enough use case to justify a context manager.

I think it's likely that data augmentation for structure-based models will become more widely used in the future.

> Even when you want to keep the structure, there are simpler ways to do this.
> [...]
> 
> ```
> lattice = structure.lattice
> species = structure.species
> coords = structure.cart_coords
> for _ in range(1000000):
>     new_coords = coords + np.random.normal(coords.shape[0], 3)
>     s2 = Structure(lattice, species, new_coords, coords_are_cartesian=True)
> ```

I don't find that as simple as:

```py
for _ in range(10000):
    with crystal.perturbed() as cryst:
        pass
```

But it's slightly faster so good to know. :)

**Comment by shyuep** [comment]
I agree data augmentation is useful for ML. But the best way to do that isn't using the structure.perturb method (with or without context managers). The work you were referring to uses MEGNet graph models from my group. The input is a crystal graph, not a structure. Of course, in a typical case where you have unique structures, you construct a graph from a Structure object. But if you are planning to do data augmentation, a much faster way is to directly construct the graph from coordinates rather than doing Structure -> Perturbed Structure -> Graph because the species, i.e., nodes, are not actually changing.

**Comment by janosh** [comment]
Thanks for this advice! I'm aware that Megnet ultimately uses a graph representation but it still computes that from a  `Structure()` in its `get_graphs_within_cutoff()` function.

https://github.com/materialsvirtuallab/megnet/blob/0c75e9cfd0c9b949c6d5d08ef7bcd211718b2138/megnet/utils/data.py#L14-L36

So your suggestion is to modify `get_graphs_within_cutoff` to not accept a `Structure` but pass in the `lattice.matrix` and `cart_coords` as bare numpy arrays? And then turn

```py
cart_coords = np.ascontiguousarray(np.array(structure.cart_coords), dtype=float)
```

into

```py
cart_coords = np.ascontiguousarray(cart_coords + np.random.normal(...), dtype=float)
```

**Comment by shyuep** [comment]
Yeah, my advice is to go the the lower level numpy arrays to speed things up, especially if you plan to do lots of augmentation. @chc273 can probably advise you on the best way to proceed. Note that the get_graphs_within_cutoff basically uses the underlying cartesian coordinates (with PBC) anyway. If it is just augmenting a few structures, then probably the cost savings is not really worth it and you might as well use the slower methods I mentioned before.

**Comment by chc273** [comment]
@shyuep @janosh Yes I think working with the numpy arrays directly instead of going from Structure -> Perturbed Structure -> Perturbed Graph will be much faster since constructing python objects is slow. You can basically call the find_points_in_spheres method in pymatgen, which takes numpy arrays as inputs. The get_graphs_within_cutoff is just a thin wrapper of the pymatgen method.
