### ISSUE TITLE
Outdated docstrings related to PeriodicNeighbor

### ISSUE THREAD

**Issue by lan496** [materialsproject/pymatgen#2084]
**Describe the bug**
The docstrings for member functions of `IStructure` to get neighbor atoms are seemed to be outdated.
Related to `get_sites_in_sphere`, `get_neighbors`, `get_neighbors_old`, `get_all_neighbors`, `get_all_neighbors_py`, and `get_neighbors_in_shell`.

The difference between docstrings and codes are as follows:
- `include_index` and `include_image` were deprecated, but some of these functions do not mention so in the docstrings.
- Some docstrings say returned `PeriodicNeighbor`s have `distance` attribute, but `PeriodicNeighbor` has actually `nn_distance` instead.

**Comment by shyuep** [comment]
Thanks for reporting this. I have updated the doc.

**Comment by lan496** [comment]
Thank you very much for your quick reply and fix. Also, I appreciate the functions for getting neighbor atoms in pymatgen, which have helped my research a lot.
