### ISSUE TITLE
Pourbaix diagram for big supercells 

### ISSUE THREAD

**Issue by hitarth64** [materialsproject/pymatgen#2090]
**Describe the bug**
I am trying to model an alloy with three elements (Co11-Fe11-Ru10-O64) in it. I am working with a 96 atoms supercell. Calculating the Pourbaix diagram only yields that particular compound as the stable entity across the whole pH range which doesn't make sense. 

**To Reproduce**
```
from pymatgen import MPRester
mpr = MPRester()
entries = mpr.get_pourbaix_entries(['Co','Fe','Ru'])
from pymatgen.entries.computed_entries import ComputedEntry
from pymatgen.core.composition import Composition
from pymatgen.analysis.pourbaix_diagram import PourbaixEntry
from pymatgen.analysis.pourbaix_diagram import PourbaixDiagram, PourbaixPlotter

# Energy is obtained from by performing DFT in consistency with MPRelaxSet parameters
centry = ComputedEntry(Composition('Fe11 Co11 O64 Ru10'), -606.313)
entry = PourbaixEntry(centry)
entries.append(entry)
pbx = PourbaixDiagram(entries,comp_dict={'Fe':11/32,'Co':11/32,'Ru':10/32})
print('Decomposition energy: ',pbx.get_decomposition_energy(entry,pH=0,V=1.23))
plotter = PourbaixPlotter(pbx)
plotter.get_pourbaix_plot().show()
```

**Expected behavior**
Expected behavior would be to see other competing phases too. I guess there is some problem or inconsistency within pymatgen when dealing with bigger supercells. Could you help me figure out if there is a specific parameter to be taken into account?

**Screenshots**
![image](https://user-images.githubusercontent.com/26575079/111022667-24300700-83a2-11eb-8536-a9298b57d328.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 2021.2.16

**Comment by rkingsbury** [comment]
Hi @hitarth64 , make sure that the energy you use to create your extra `ComputedEntry` in this line

`centry = ComputedEntry(Composition('Fe11 Co11 O64 Ru10'), -606.313)`

is a _formation energy_ and not a raw DFT energy. All energies supplied to `PourbaixDiagram` need to be free energies of formation with respect to elements. I suspect that's what is causing this material to be overstabilized relative to the others.

**Comment by hitarth64** [comment]
Thanks. This helps!
