### ISSUE TITLE
Import problems in Google Collab

### ISSUE THREAD

**Issue by VIGNESHinZONE** [materialsproject/pymatgen#2091]
Unable to install Pymatgen properly on google collab, 
```
!pip3 install pymatgen
from pymatgen import Structure
```
Could you please share a working code for a collab,

**To Reproduce**
Please run this [collab file](https://colab.research.google.com/drive/1XAb7q78cKf1n-MA3T9LjNscVgO0SRCsw?usp=sharing) for checking

Screenshot - 
![Screenshot from 2021-03-15 02-08-57](https://user-images.githubusercontent.com/45672459/111083435-a6036a00-8533-11eb-8d16-e7978123db24.png)

**Comment by shyuep** [comment]
We removed root level imports in the recent versions of pymatgen as part of a move to a more modular structure. Pls change from pymatgen import Structure to from pymatgen.core.structure import Structure.
