### ISSUE TITLE
Construct PointGroup class failed from the result of SpaceGroup for some space groups

### ISSUE THREAD

**Issue by hitliaomq** [materialsproject/pymatgen#2092]
**Describe the bug**
Construct PointGroup class failed from the result of SpaceGroup for some space groups.
Failed space groups: 115-120, 149-154, 156-159, 162-165, 189-190

**To Reproduce**

```python
from pymatgen.symmetry.groups import SpaceGroup, PointGroup

for spacegroup in range(1, 231):
    pointgroup = SpaceGroup.from_int_number(int(spacegroup)).point_group
    try:        
        pointsym = PointGroup(pointgroup)
    except Exception as e:
        print(spacegroup)
        print(pointgroup)
```

It will give the following results

```
[115, 116, 117, 118, 119, 120, 149, 150, 151, 152, 153, 154, 156, 157, 158, 159, 162, 163, 164, 165, 189, 190]
['-4m2', '-4m2', '-4m2', '-4m2', '-4m2', '-4m2', '312', '321', '312', '321', '312', '321', '3m1', '31m', '3m1', '31m', '-31m', '-31m', '-3m1', '-3m1', '-62m', '-62m']
[Finished in 0.7s]
```

**Desktop (please complete the following information):**
 - OS: Windows,Linux
 - Version 2022.0.4

**Comment by shyuep** [comment]
Some of the point groups are just different settings of existing point groups. E.g., -4m2 is similar to -42m. Others are just more lengthy names. E.g., 321 is just 32.

**Comment by fraricci** [comment]
just as a comment, here is a way to convert them:
point_group_conv = {'321' :'32', '312': '32', '3m1' :'3m', '31m': '3m',
                    '-3m1' : '-3m', '-31m': '-3m', '-4m2': '-42m', '-62m': '-6m2' }

# Using this dictionary we can correct to the standard point group notation.
corrected_point_groups = [point_group_conv.get(pg, pg) for pg in point_groups]

This was use by @blondegeek in developing FE database.

**Comment by hitliaomq** [comment]
@shyuep @fraricci  Thank you very much.
