### ISSUE TITLE
source code links from docs seem to be broken

### ISSUE THREAD

**Issue by rkurchin** [materialsproject/pymatgen#2093]
**Describe the bug**
The links in the documentation to the source code associated with that release currently give a 404 error, at least in the cases I have tried. 

**To Reproduce**
1. Go to https://pymatgen.org/pymatgen.analysis.local_env.html
2. Click on any "source" link
4. See "not found" error

**Expected behavior**
I should have been brought to the source code...

**Desktop (please complete the following information):**
 - MacOS
 - Version 10.15.7
 - browser: Vivaldi v3.6.2165.40

**Additional context**
I was going to just make a PR to fix it but I couldn't figure out how to make the actual correct link 😆

**Comment by mkhorton** [comment]
Looks like @shyuep has fixed, thanks for reporting!
