### ISSUE TITLE
pymatgen.__version__ does not work

### ISSUE THREAD

**Issue by adelaiden** [materialsproject/pymatgen#2094]
Hi, I have installed the latest version of pymatgen (v2022.0.4) in a fresh conda environment. Previously when checking the version I could open my command line, type `import pymatgen` and then `pymatgen.__version__` and I could obtain the version number. However, with the latest version (since the backwards incompatible transition to namespaces), it doesn't work.

Here is a sample output:
Python 3.8.8 (default, Feb 24 2021, 13:46:16) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
\>>> import pymatgen
\>>> pymatgen.\_\_version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pymatgen' has no attribute '\_\_version__'
\>>> 

I can check the version of modules such as pymatgen.core by importing `import pymatgen.core` and `core.__version__`, but I would still like to be able to check the version of pymatgen, especially when designing packages that have dependencies on specific versions of pymatgen. Previous versions of pymatgen do appear to work.

Sample output for older pymatgen version, in different conda environment with Python 3.7:
Python 3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:36:57) 
[Clang 9.0.0 (tags/RELEASE_900/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
\>>> import pymatgen
\>>> pymatgen.\_\_version__
'2020.9.14'

 - OS: Mac, Catalina, 10.14.3
 - New test conda environment with python 3.8

**Comment by shyuep** [comment]
We do make 'pymatgen.core.__version__' to be the correct version number. However, it is not the best way to properly get version numbers for packages since it depends on the developer actually updating it. You should use importlib or pkgutil. See https://stackoverflow.com/questions/20180543/how-to-check-version-of-python-modules

**Comment by adelaiden** [comment]
Great, thank you! That worked for me:

Python 3.8.8 (default, Feb 24 2021, 13:46:16) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
\>>> import pymatgen
\>>> import pkg_resources
\>>> pkg_resources.get_distribution('pymatgen').version
'2022.0.4'

**Comment by shyuep** [comment]
Specifically,

```
In [1]: import pkg_resources

In [2]: pkg_resources.get_distribution('pymatgen').version
Out[2]: '2022.0.4'
```
