### ISSUE TITLE
Duplicated atoms in Structure.from_str compared to source string

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#2096]
**Describe the bug**

`Structure.from_str` duplicates atoms.

**To Reproduce**

```py
import requests
resp = requests.get("http://www.crystallography.net/cod/1510206.cif")

with open("1510206.cif", 'w') as file:
    file.write(resp.text)
```

The above writes a CIF file with contents

```cif
...
_chemical_formula_sum            'Au K Se2'
_chemical_name_systematic        'K (Au Se2)'
_space_group_IT_number           127
_symmetry_space_group_name_Hall  '-P 4 2ab'
_symmetry_space_group_name_H-M   'P 4/m b m'
_cell_angle_alpha                90
_cell_angle_beta                 90
_cell_angle_gamma                90
_cell_formula_units_Z            2
_cell_length_a                   7.699
_cell_length_b                   7.699
_cell_length_c                   3.665
_cell_volume                     217.241
_citation_journal_id_ASTM        JALCEU
_cod_data_source_file            gold_264.cif
_cod_data_source_block           Au1K1Se2
_cod_original_cell_volume        217.2414
_cod_original_formula_sum        'Au1 K1 Se2'
_cod_database_code               1510206
...
```

On the other hand,

```py
from pymatgen.ext.cod import COD

cod.get_structure_by_id('1510206')
```

returns

```sh
Structure Summary
Lattice
    abc : 7.699 7.699 3.665
 angles : 90.0 90.0 90.0
 volume : 217.24141266499998
      A : 7.699 0.0 4.714277853317737e-16
      B : -4.714277853317737e-16 7.699 4.714277853317737e-16
      C : 0.0 0.0 3.665
PeriodicSite: K (0.0000, 0.0000, 0.0000) [0.0000, 0.0000, 0.0000]
PeriodicSite: K (3.8495, 3.8495, 0.0000) [0.5000, 0.5000, 0.0000]
PeriodicSite: Au (3.8495, 0.0000, 0.0000) [0.5000, 0.0000, 0.0000]
PeriodicSite: Au (-0.0000, 3.8495, 0.0000) [0.0000, 0.5000, 0.0000]
PeriodicSite: Se (2.6716, 1.1764, 1.8325) [0.3470, 0.1528, 0.5000]
PeriodicSite: Se (6.5226, 2.6716, 1.8325) [0.8472, 0.3470, 0.5000]
PeriodicSite: Se (5.0274, 6.5226, 1.8325) [0.6530, 0.8472, 0.5000]
PeriodicSite: Se (1.1764, 5.0274, 1.8325) [0.1528, 0.6530, 0.5000]
PeriodicSite: Se (6.5211, 2.6731, 1.8325) [0.8470, 0.3472, 0.5000]
PeriodicSite: Se (5.0259, 6.5211, 1.8325) [0.6528, 0.8470, 0.5000]
PeriodicSite: Se (1.1779, 5.0259, 1.8325) [0.1530, 0.6528, 0.5000]
PeriodicSite: Se (2.6731, 1.1779, 1.8325) [0.3472, 0.1530, 0.5000]
```

i.e. double the amount of `Se`. Apparently all the `Se` are duplicated with a 0.002 A offset. If I pass `merge_tol`,

```py
cod.get_structure_by_id('1510206', merge_tol=0.003)
```

I get

```sh
ValueError: Species occupancies sum to more than 1!
```

How to proceed in this case?

Also, there should probably be a test for `Structure.from_str` that asserts the reduced compositions of the structure and the source string/file match.

**Desktop (please complete the following information):**
 - OS: Mac & Linux
 - Version: 2021.2.16

**Comment by shyuep** [comment]
You need to use mode="delete" for merging.

**Comment by janosh** [comment]
Makes sense, thanks for the detailed reply.

**Comment by mkhorton** [comment]
Yes. To add to this, COD is usually pretty good, but the amount of out-of-spec or malformed CIF files that are in the wild is staggering. The pymatgen CifParser is very forgiving in this respect (another issue is finite precision of atomic site co-ordinates which can make reconstruction via space group operations tricky), but it's impossible to get a good answer automatically in all cases.

**Comment by janosh** [comment]
Given a set of COD or ICSD IDs, is is possible to query with `MPRester` for corresponding MP IDs where they exist?

**Comment by shyuep** [comment]
@janosh Yes, we anticipated this need. The best way is to use https://pymatgen.org/pymatgen.ext.matproj.html#pymatgen.ext.matproj.MPRester.find_structure . 

```
from pymatgen.ext.cod import COD

structure = COD().get_structure_by_id('1510206')
structure.merge_sites(tol=0.003, mode="delete")
from pymatgen.ext.matproj import MPRester
mpr = MPRester()
mpr.find_structure(structure)
```

returns ['mp-29138']

This uses StructureMatcher. It is somewhat slower than actually assigning a COD id in the database, but it is completely general and works for a structure from any source.

**Comment by shyuep** [comment]
Also to add, for icsd_ids, there is a simpler way since the database does store the icsd ids.

```
from pymatgen.ext.matproj import MPRester
mpr = MPRester()
mpr.query({"icsd_ids": 1234}, ["task_ids"])
mpr.query({"icsd_ids": 1}, ["task_id"])
```
