### ISSUE TITLE
SpacegroupAnalyzer.get_conventional_standard_structure additional documentation

### ISSUE THREAD

**Issue by tom-wood** [materialsproject/pymatgen#2097]
**Is your feature request related to a problem? Please describe.**
It is a bit confusing (i.e. I spent quite a bit of time under a false impression) that the get_conventional_standard_structure method in the SpacegroupAnalyzer class does not necessarily return a Structure instance that is in the standard settting described by the International Tables of Crystallography, whereas get_refined_structure will. A pathological example would be the following, where the "conventional standard structure" is in fact 'P2_1mn':
```
from pymatgen.core import Structure, Lattice
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
latt = Lattice.orthorhombic(3, 1, 2)
struc = Structure(latt, ["H"] * 4 + ["Li"] * 4, 
                  [(0.1, 0.2, 0.3), (0.4, 0.8, 0.8), (0.6, 0.8, 0.8), (0.9, 0.2, 0.3),
                   (0.2, 0.3, 0.4), (0.3, 0.7, 0.9), (0.7, 0.7, 0.9), (0.8, 0.3, 0.4)])
s = SpacegroupAnalyzer(struc)
con = s.get_conventional_standard_structure()
ref = s.get_refined_structure()
print(con.lattice.abc) # (1.0, 2.0, 3.0)
print(con.get_space_group_info()) # ('Pmn2_1', 31)
print(ref.lattice.abc) # (3.0, 1.0, 2.0)
print(ref.get_space_group_info()) # ('Pmn2_1', 31)
```
This _is_ subtly implicit in the documentation for get_conventional_standard_structure but would be even better if it were explicitly warned about.

**Describe the solution you'd like**
An additional line in the docstring for get_conventional_standard_structure with a warning that get_refined_structure should be used if the ITC settings are required. I'm happy to submit a PR to do this if needed.

**Describe alternatives you've considered**
I don't know if there would be any appetite for this, but maybe the get_space_group_info method of the Structure class could print a warning that the current structure is in a non-standard setting if the transformation matrix to standard settings does not match the identity matrix. I'm agnostic as to whether this would be a useful feature, however.

**Comment by shyuep** [comment]
Thanks. Feel free to submit a PR to modify the doc. I don't think the alternative is needed though. There are a lot of different settings for space groups. People who work with space groups understand the differences.
