### ISSUE TITLE
get_symmetrically_distinct_miller_indices gives wrong values for primitive fcc cell

### ISSUE THREAD

**Issue by bernstei** [materialsproject/pymatgen#2103]
**Describe the bug**
When passed a primitive fcc cell and max index of 1, `get_symmetrically_distinct_miller_indices()` fails to find (1 0 0), but reports multiple equivalent copies of (110) and (111) differing by negative signs

**To Reproduce**
run the following python script
```
from ase.atoms import Atoms
from pymatgen.io.ase import AseAtomsAdaptor
from pymatgen.core.surface import get_symmetrically_distinct_miller_indices

struct = AseAtomsAdaptor.get_structure( Atoms('Al', cell=[[1,1,0],[1,0,1],[0,1,1]], pbc=[True]*3))
print(struct)

print(get_symmetrically_distinct_miller_indices(struct, 1))
```

**Expected behavior**
Last line should be some permutation of `[(1, 1, 1), (1, 1, 0), (1, 0, 0)]`

**Screenshots**
```
> python tt.py
Full Formula (Al1)
Reduced Formula: Al
abc   :   1.414214   1.414214   1.414214
angles:  60.000000  60.000000  60.000000
Sites (1)
  #  SP      a    b    c
---  ----  ---  ---  ---
  0  Al      0    0    0
[(1, 1, 1), (1, 1, 0), (1, 1, -1), (1, 0, -1)]
```

**Desktop (please complete the following information):**
OS X 10.15, using macports python3 3.8.7, pymatgen version 
```
> pip show pymatgen
Name: pymatgen
Version: 2022.0.5
```

**Comment by bernstei** [comment]
I just realized that this is probably explained by the code not magically knowing the convention that for fcc people use conventional cell Miller indices instead of ones based on the reciprocal of the primitive cell lattice (combined with the fact that conventional 211 can be expressed with max index 1 in primitive reciprocal indices, so even the count of inequivalent indices is different). 

Feel free to close this issue, although I might suggest making this point more explicit in the docs.

**Comment by shyuep** [comment]
Yes. The code works primarily for conventional cells. If you supply a conventional fcc crystal, that will yield the correct result. That is usually how people define miller indices.

**Comment by shyuep** [comment]
Also, in general, that method is not called on its own but rather used as part of SlabGenerator. In SlabGenerator, the doc says "Note that to ensure that the miller indices correspond to usual crystallographic definitions, you should supply a conventional                 unit cell structure."
