### ISSUE TITLE
Outdated BoltztrapRunner?

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#2114]
**Is your feature request related to a problem? Please describe.**

`BoltztrapRunner` requires `x_trans` to be in path (which appears to be outdated) and links to an [empty page](www.icams.de/content/research/software-development/boltztrap) to get it.

**Describe the solution you'd like**

https://github.com/materialsproject/pymatgen/blob/04beca9af8e575005a40117f1779f1d464c0a697/pymatgen/electronic_structure/boltztrap.py#L54-L66

Perhaps the best solution would be to update `BoltztrapRunner` to use BoltzTraP2 whose official page is https://www.imc.tuwien.ac.at/index.php?id=21094 and which can installed easily with `pip install BoltzTraP2`.

**Describe alternatives you've considered**

More detailed installation instructions for `x_trans`.

**Comment by shyuep** [comment]
There is already a pymatgen.electronic_structure.boltztrap2 module (https://github.com/materialsproject/pymatgen/blob/master/pymatgen/electronic_structure/boltztrap2.py).

**Comment by janosh** [comment]
Oops. But then how come `atomate` doesn't use it?

https://github.com/hackingmaterials/atomate/blob/7bd29a52e5b6f965b73ec035e65fc6c556f4164f/atomate/vasp/firetasks/run_calc.py#L20

Also, shouldn't the unhelpful link be updated regardless?

**Comment by shyuep** [comment]
Well, the link can be updated if you wish, but the likelihood is that the module will be junked soon anyway. As for atomate, you can pose that question to @computron .
