### ISSUE TITLE
semvar?

### ISSUE THREAD

**Issue by dwinston** [materialsproject/pymatgen#213]
What is this project's policy for version tagging? May I suggest using that of http://semver.org/?
There were some [deprecations](https://github.com/materialsproject/pymatgen/blob/master/CHANGES.rst#v305) introduced in v3.0.5 that are now incompatible changes as of v3.1. For example, the MP web code has a line
```
from pymatgen.symmetry.finder import SymmetryFinder
```
for the crystal toolkit app that is now broken. This is not a bad thing -- I'll change the line -- it's just that I figured "pymatgen v4.0.0rc1" would be the time to expect lots of dangling deprecated code to require replacement.

**Comment by shyuep** [comment]
Generally, pymatgen follows pretty closely to semvar, though backwards incompatible changes do occur at what is so-called the minor version.

The evolution of pymatgen is too rapid to use standard semvar. Many “patches” in fact are new functionality development. The time between minor versions tend to be fairly long. E.g., it is almost a year between 3.0.0 and 3.1.0. Lots of time was given with deprecation messages on the removal of SymmetryFinder.

If we use standard semvar, the version number of pymatgen will be something like 99.1.0. 

Shyue Ping

On July 3, 2015 at 07:40:33, Donny Winston (notifications@github.com) wrote:

What is this project's policy for version tagging? May I suggest using that of http://semver.org/?
There were some deprecations introduced in v3.0.5 that are now incompatible changes as of v3.1. For example, the MP web code has a line

from pymatgen.symmetry.finder import SymmetryFinder

for the crystal toolkit app that is now broken. This is not a bad thing -- I'll change the line -- it's just that I figured "pymatgen v4.0.0rc1" would be the time to expect lots of dangling deprecated code to require replacement.
