### ISSUE TITLE
Structure.from_str reads from str(Structure)

### ISSUE THREAD

**Issue by goodwilling** [materialsproject/pymatgen#2138]
**Is your feature request related to a problem? Please describe.**
It is necessary to convert str(Structure) to a Structure when a DataFrame contains column of structures and default_handler=str is set in DataFrame.to_json() in order to get rid of "OverflowError: Maximum recursion level reached".

**Describe the solution you'd like**
 Strcture.from_str(str(struct), fmt="str") reads from str(struct), where struct is a Structure.

**Additional context**
The following code:

from pymatgen.core.structure import Structure
struct = Structure.from_file("Si2.cif")
print(str(struct))

gives the structure information:

Full Formula (Si2)
Reduced Formula: Si
abc   :   3.839136   3.839136   3.839136
angles:  60.000000  60.000000  60.000000
Sites (2)
  #  SP        a      b      c
---  ----  -----  -----  -----
  0  Si    0.125  0.125  0.125
  1  Si    0.875  0.875  0.875

However, there is no method to convert str(struct) to a Structure, 
like 

 Structure.from_str(str(struct), fmt="str")

The feature should be necessary when a DataFrame contains column of structures 
and default_handler=str is set in DataFrame.to_json() in order to get rid of 
"OverflowError: Maximum recursion level reached".

**Comment by mkhorton** [comment]
Hi @goodwilling, we've had some requests for a Structure.from_str before, however I don't think this is in general a good approach. The string representation is lossy. It would be better if we could handle Pandas conversion natively. I know Pandas support extensions and custom data types but I'm not familiar with the details.

**Comment by goodwilling** [comment]
Thank you very much.  MontyEncoder works well for DataFrame containing Structure data.  

By the way, I have tried the following code before and it seems to work. 

   import json, numpy
   class MyEncoder(json.JSONEncoder):
     def default(self, o):
        if isinstance(o, numpy.generic):
           return o.item()
        try:
           t = o.as_dict()
           return t
        except: 
           return super().default(o) 
         
   #df.to_json(file)
   data = df.to_dict() 
   with open(file, 'w') as fp:
        json.dump(data, fp, cls=MyEncoder)
