### ISSUE TITLE
SpacegroupAnalyzer crashes with `alpha` not calculated

### ISSUE THREAD

**Issue by tschaume** [materialsproject/pymatgen#214]
In pymatgen 3.0.14, the `get_conventional_standard_structure` function crashes in line 618 with the error message: `local variable 'alpha' referenced before assignment`. For the special case with a monoclinic lattice type, a space group starting with 'C', and angle `landang[1][0] = 90`, the variable `alpha` is never calculated and constructing `new_matrix` hence fails.

@shyuep: This issue is important for the `mgcloud` project, since it causes two of the test jobs to crash (BaTiO3, LiCoO2) and we're not sure how this issue would scale when running many calculations. FYI, @computron and @kristinpersson

**Comment by tschaume** [comment]
Below the affected code. It seems that `alpha` needs to be set to 90.

```
   if new_matrix is None:
                    #this if is to treat the case
                    #where alpha==90 (but we still have a monoclinic sg
                    new_matrix = [[a, 0, 0],
                                  [0, b, 0],
                                  [0, c * cos(alpha), c * sin(alpha)]]
```

**Comment by shyuep** [comment]
Pls contact @hautierg to fix this problem, as well as ensure that unittests are written to ensure that this bug does not occur again. I don't want to fix this as I am not sure what's the right procedure.

**Comment by shyuep** [comment]
Already fixed. Closing/
