### ISSUE TITLE
black changes all quotes to double, flake8 complains about them

### ISSUE THREAD

**Issue by flaviu-gostin** [materialsproject/pymatgen#2142]
**Describe the bug**
Conflict between blake and flake8 settings.

**To Reproduce**
1. Commit changes with `git commit`
2. pre-commit is triggered
3. black (I think) changes all quotes to double " 
4. flake8 complains about the double quotes with: Q000 Remove bad quotes

Recommend adding in setup.cfg (according to [https://github.com/zheller/flake8-quotes]) 
[flake8]
inline-quotes = double

This stops the Q000 ...

**Comment by arosen93** [comment]
@janosh: This can be closed as out of scope.

**Comment by janosh** [comment]
`flake8` was replaced with `ruff`.
