### ISSUE TITLE
This looks like dead code since the class is redefined immediately after

### ISSUE THREAD

**Issue by jmmshn** [materialsproject/pymatgen#2145]
https://github.com/materialsproject/pymatgen/blob/ad5cb53f6255f8af8428bbc6fdff74c50be342e8/pymatgen/electronic_structure/dos.py#L26

**Comment by jmmshn** [comment]
nvm `Dos` not `DOS`

**Comment by mkhorton** [comment]
I think it is strange to have both though... I'm not sure that a work-in-progress replacement like this should be in the main branch since it causes confusion when a user goes to import the class. Maybe it's better to rename it `_DOS` or remove it until it's ready to be used?

**Comment by shyuep** [comment]
Yes this can be removed.
