### ISSUE TITLE
parsing of LORBIT and NELM by io.vaspio.Vasprun

### ISSUE THREAD

**Issue by terencezl** [materialsproject/pymatgen#215]
vasprun.xml does not seem to parse a numeric LORBIT correctly. When it is set in INCAR as an integer, it will be seen as a boolean tag and assigned False. The same could happen to other tags. Instead, OUTCAR has the right value, straight from INCAR.

NELM appears once in OUTCAR, but twice in vasprun.xml, one in 'electronic convergence', another in 'response functions'. The latter one has the default value 1, replacing the default value 60 of the former and causes vasprun.parameters to get the wrong value, thus vasprun.converged_electronic always return False.

**Comment by shyuep** [comment]
I just pushed a fix to the NELM issue. But I cannot do anything about LORBIT. If the vasprun.xml does not report the right value, I can only leave it be.
