### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ddopplereffekt** [materialsproject/pymatgen#2158]
**Describe the bug**
in pymatgen/entries/compatebility.py line 1031 is a type: the enclosing bracket for the formular is missing

**Expected behavior**
f"({entry.composition.reduced_formula}). Assigning anion correction to "
instead of
f"({entry.composition.reduced_formula}. Assigning anion correction to "

**Comment by mkhorton** [comment]
Hi @ddopplereffekt, thanks for reporting, I've fixed this now. In future, you can also suggest edits to files directly by clicking the "Edit" button on GitHub for small typos like this, and then we can merge the change in with one-click.
