### ISSUE TITLE
Anonymous formula is chemistry dependent

### ISSUE THREAD

**Issue by wmdrichards** [materialsproject/pymatgen#216]
The anonymous formula currently uses the list of special formulas to determine the reduced formula. For example, Li2O2 has anonymous formula A2B2 instead of AB. Is this desired functionality (and does anyone depend on it)?

As it is now, chemical substitutions applied to a structure can (sometimes) change its anonymous formula, which I think is quite counterintuitive.

**Comment by computron** [comment]
My preference is if the anonymous formula is not built off the "pretty formula" but rather the reduced formula. ie. I would want Li2O2 to have anonymous formula for AB.

**Comment by shyuep** [comment]
I am fine with this. Can someone fix this?
