### ISSUE TITLE
typing_extensions dependency

### ISSUE THREAD

**Issue by htz1992213** [materialsproject/pymatgen#2166]
**Describe the bug**
Dependency requirements for `typing-extensions` should apply for any python versions, not just python<3.8. Current version:
https://github.com/materialsproject/pymatgen/blob/dfc90b07d6362848442ce611ebe1c3a3e1ca2926/requirements.txt#L17
https://github.com/materialsproject/pymatgen/blob/dfc90b07d6362848442ce611ebe1c3a3e1ca2926/setup.py#L124-L125

**To Reproduce**

```
conda create -n test_pymatgen python=3.8
source activate test_pymatgen
conda install --channel conda-forge pymatgen
python
>>> import pymatgen.io.qchem.inputs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/homes/t/thou/.conda/envs/test_pymatgen/lib/python3.8/site-packages/pymatgen/io/qchem/inputs.py", line 10, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'
```

**Expected behavior**
The import should work.

**Additional context**
The `typing-extensions` package is not a built-in package for any python version. It should be explicitly required not only for python<3.8, but also >=3.8, even though the imported class is a built-in `typing` class for python>=3.8.

**Comment by mkhorton** [comment]
This is an issue in `pymatgen.io.qchem.inputs` not in `setup.py`, typing_extensions is not required for Python >= 3.8 since the relevant type hints are built-in. Fixed with https://github.com/materialsproject/pymatgen/commit/73783005ce1e9030f06d50125abd87e4071183f3.

Thanks @htz1992213 for reporting, fyi @espottesmith
