### ISSUE TITLE
Adding alternative symmetry finding backends to pymatgen

### ISSUE THREAD

**Issue by CompRhys** [materialsproject/pymatgen#2170]
Would a PR be welcomed adding alternative symmetry finding backends to pymatgen?

Currently pymatgen uses `spglib` which should definitely remain the default due to speed and the fact that it's a pip-installable package but alternative finders such as find-sym and aflow-sym trade can produce better results - https://doi.org/10.1107/S2053273318003066. 

I think I have a reasonable idea on how to implement this but it would require a config file somewhere to allow users to add paths to their aflow/findsym executables.

Would this be supported if I try to do it?

**Comment by mkhorton** [comment]
It depends on how it's implemented, and how easy it is to switch backends. We would not want any core code that requires installing packages outside pip, and would not want to add clutter within the existing classes. A more general coupling between pymatgen and the symmetry-finding code might result in the pymatgen code being cleaner however, and the feature in general sounds good.

> I think I have a reasonable idea on how to implement this

Could you outline this more concretely?

**Comment by mkhorton** [comment]
I'm not familiar with that paper, but from a quick skim it seems that the only major advance is that they iteratively change the symmetry-finding tolerance until a consistency criterion is satisfied. I suspect spglib could be used in a similar way too. Regardless, I think having the option to switch or try out different methods is a good thing.

**Comment by shyuep** [comment]
I am always open to better implementations. But in this case, I would suggest you define what is "better results" first. Even I am not entirely clear how to compare different symmetry finding packages.

I would rank my preference as follows:
1. Built in support in pymatgen for symmetry finding, either as a Python-only or as a Python C extension. The former would need to be nearly as fast as the latter to be worthwhile. But I can live with the latter.
2. Spglib or some other external pip installable package. 
3. External command line tools (I am aware of a few).

There is nothing preventing us from having multiple of these supported. But it needs to be worthwhile to spend the effort.

**Comment by CompRhys** [comment]
> I am always open to better implementations. But in this case, I would suggest you define what is "better results" first. Even I am not entirely clear how to compare different symmetry finding packages.

I think the better I am targeting is robustness but that robustness comes from adapting the tolerances and looking for consistency. In the testing, I've done looking at more "robust" symmetry finders `findsym` is about 10x slower than `spglib` and `aflow-sym` maybe 100x slower although both do place many fewer materials in P1 which is the proxy I was using for robustness. 

I think that probably on balance the backend idea using cli tools might end up being unsupported longer term and so maybe it's better if I look at whether it would be possible to do as @mkhorton suggests and mimic the consistency checking of `aflow-sym` using `spglib` as the backend and then if I can get that to work it could be turned on and off with a `auto_adjust_tol` kwarg or something like that.

**Comment by shyuep** [comment]
Ok, I think that is not really a definition of better. If I set tolerances to be 0, I am guaranteed to get P1 far more often than a higher symmetry. If I set tolerances really high, I tend to get cubic or other high symmetries more often. I wouldn't even know where to begin to stipulate what the ground truth symmetry is - which is what you need to say something is better.

Adaptive tolerances is generally a good idea - I have done this in the past.

**Comment by mkhorton** [comment]
>  mimic the consistency checking of aflow-sym using spglib as the backend inside pymatgen and then if I can get that to work it could be turned on and off with a auto_adjust_tol kwarg or something like that.

This would be interesting. Perhaps @atztogo would be interested in implementing directly in spglib too if the benefit is clear. However, I don't want to be too quick to form an opinion at this point since I have not had time to review the paper thoroughly.

**Comment by atztogo** [comment]
Tolerance parameter is a complicated parameter in symmetry finding. At least I don't define it mathematically well, so what I could explain was just how it is implemented in spglib, https://arxiv.org/abs/1808.01590 (maybe see Fig. 1.) We can improve spglib. But I want to balance among (1) reasonable symmetry identification (2) speed (3) portability (4) maintainability under the constraint that the fact that the main developer is only me.

What might be wanted to discuss here may be not as simple as you might think. As @shyuep wrote, the definition is unclear. What @mkhorton may expect to spglib is not clear for me. If you could define what you really want, I am happy to consider its implementation. Probably, the difficulty exists not in the implementation, but in the definition and the design.

By the way, I've never watched the aflow-sym code, but it seems it's under the GPL. So in a strict license manner, it might invoke license issue.

**Comment by mkhorton** [comment]
> By the way, I've never watched the aflow-sym code, but it seems it's under the GPL. So in a strict license manner, it might invoke license issue.

My understanding is that the code is GPL, but the algorithm described in the paper is freely available to implement.

> What @mkhorton may expect to spglib is not clear for me. If you could define what you really want, I am happy to consider its implementation.

Yes, I may have a poor understanding here. I was looking at Figure 5 of the [paper here](https://onlinelibrary.wiley.com/doi/pdf/10.1107/S2053273318003066?casa_token=dKAY7wSjt1AAAAAA:AFlijXEKJK-Rb-HqRlapIi9EARUEwLs4UwViPhXsHpbm70ja1Rxk0EISUq5SWSj8RQoBtzDO-GhlN0h96Q). My understanding is that spglib already does most of what this describes except perhaps for the consistency checks specified in §2.6 of the paper. Thank you for the response!

**Comment by atztogo** [comment]
> My understanding is that the code is GPL, but the algorithm described in the paper is freely available to implement.

Yes. I wanted to mention to the idea by @CompRhys.

> Yes, I may have a poor understanding here. I was looking at Figure 5 of the paper here. My understanding is that spglib already does most of what this describes except perhaps for the consistency checks specified in §2.6 of the paper. Thank you for the response!

In spglib, those symmetries are check to be consistent. Probably we can have more checks. I am not a specialist of crystallography. So if the materials science community wants to have a better symmetry finder, the first thing to do may be to discuss with crystallographers, such as the cctbx project. If I remember correctly (maybe wrong), sginfo was under GPL or something that I wanted to avoid to use (not now), and so I could not use it when I needed it.

The adjustment of tolerance parameter (or the way to tolerate) is done in a primitive way in spglib. Here "a primitive way" does not mean with respect to other symmetry finders (because I don't know others), but with respect to my feeling that we can implement a more clever way. We know many things to do for the improvement but this kind of work including maintenance and support is not respected and no chance to get paid.
