### ISSUE TITLE
pymatgen.io.vaspio.Incar() object copy method returns plain dict, rather than another object

### ISSUE THREAD

**Issue by terencezl** [materialsproject/pymatgen#218]
Don't know if it's intended to be. Of course, pymatgen.io.vaspio.Incar(incar_old.copy()) still works.

**Comment by shyuep** [comment]
You don't actually need to do .copy(). Just Incar(incar_old) will do.

In general, I don't want to override copy(). Incar inherits dict, which is why it returns a dict. For most purposes, an Incar is like a dict.
