### ISSUE TITLE
Inconsistency between function definition and documentation

### ISSUE THREAD

**Issue by gVallverdu** [materialsproject/pymatgen#2183]
Hi,

There is an inconsistency between the definition of the `append()` function of the `Molecule` class and the documentation.

The `validate_proximity` is set to `False` by default but in the docstring of the function it is said that the default value is `True`.

Here is the link to the `append()` method in the `pymatgen.core.structure.Molecule` class:
https://github.com/materialsproject/pymatgen/blob/b789d74639aa851d7e5ee427a765d9fd5a8d1079/pymatgen/core/structure.py#L3861-L3887

I am using the version 2022.0.5.

**Comment by mkhorton** [comment]
Thanks @gVallverdu, fixed with https://github.com/materialsproject/pymatgen/commit/8c96e7a395a2c5894d9d7d6d3094873b7e172741
