### ISSUE TITLE
Lattice object should not be hashable

### ISSUE THREAD

**Issue by Develpy** [materialsproject/pymatgen#2184]
The lattice object (pymatgen/pymatgen/core/lattice.py) implements the hash-function as follows:

```
def __hash__(self):
    return 7
```

I think that this is not a good way to implement the hash-function and that lattice should not be hashable because it is mutable.

**Comment by shyuep** [comment]
Strictly speaking, yes. Practically, this is normal practice and sometimes, there are cases where you want to hash a Lattice or some other mutable object in a dict. The default Python Object is hashable.
