### ISSUE TITLE
Tensorflow and Pymatgen incompatible

### ISSUE THREAD

**Issue by arunppsg** [materialsproject/pymatgen#2189]
The latest version of tensorflow and pymatgen are incompatible due to dependency errors. Tensorflow depends on older version of numpy (1.19.1) while pymatgen uses numpy 1.20.1.

When installing pymatgen in a new conda environment or in colab containing tensorflow, installation errors with exit status 1. Maybe it will be helpful if someone could point to the version of pymatgen using numpy 1.19.1 version.

**Comment by shyuep** [comment]
Try 2019.12.31

**Comment by arunppsg** [comment]
Thanks for your suggestion. Pymatgen 2020.12.31 worked for me. In colab, it worked fine. In anaconda, there was module not found error for ruamel.yaml. But `import ruamel_yaml` worked. It was resolved using the following steps:

1. `cd anaconda3/lib/python3.8/site-packages/pymatgen`
2. `find . -name '*.py' | xargs sed -i 's/ruamel.yaml/ruamel_yaml/g'`

**Comment by mkhorton** [comment]
Just to note that older versions of numpy are likely fine with the current pymatgen too if you're willing to manually git clone and run `python setup.py install`.

**Comment by arunppsg** [comment]
Thanks!
