### ISSUE TITLE
Read WAVEDER(F) from Vasp LOPTICS runs?

### ISSUE THREAD

**Issue by migueldiascosta** [materialsproject/pymatgen#219]
Hello all,

we've recently been uncommenting a line (CALL WRT_CDER_BETWEEN_STATES_FORMATTED..) in vasp linear_optics.F which writes WAVEDERF, a formatted version of WAVEDER, to get the optical transition matrix elements, and we were thinking this could be a nice addition to vasp_output.py, since coupled with other band structure features of pymatgen it can allow interesting analyses and/or visualizations. 

However, since the default output is unformatted, do you have a recommendation for how to read it from python or do you just avoid these files altogether? If the latter, we can easily read from WAVEDERF but that will only be present if people uncomment that line and recompile vasp...

Cheers,
Miguel

**Comment by shyuep** [comment]
Dear Miguel,

I think this would be a nice addition. I have no idea how to read the WAVEDER without delving deep into the VASP source code to find out how it is generated (something I avoid). I think providing the facility to read the WAVEDERF is fine, as long as you document in the code that this is only useful if people use a specific version of compiled vasp.

**Comment by migueldiascosta** [comment]
Dear Shyue,

thanks for the quick reply and your interest. Before submitting a pull request, maybe you can have a look at migueldiascosta/pymatgen@31f49648359acf9c041a5a53357e4b5e7415de67 and comment? 

Even being so simple, there were already a few choices to be made. For instante, on the type of data, I chose a numpy array for performance and multidimensional slicing.

I also left out the band indexes, energies and occupations as these are already available, as well as the kpoint coordinates, but one could also make a case for having this class more self-contained.

For testing, you can download a (large) WAVEDERF file here: https://db.tt/FfAOm163

Also, do let me know of any guidelines I may have missed.

**Comment by shyuep** [comment]
Hi Miguel,

The class looks great. Using numpy arrays is always a good idea. 

The only minor thing I would change is to use "with zopen() as f:" instead of f = zopen.... That guarantees that the file handler is closed (something that you did not do) and prevents a memory leak. 

After you make that minor change, can you submit the pull request pls? Thanks.

Regards,
Shyue Ping

**Comment by shyuep** [comment]
Oh, you should also add a Author: Miguel Dias Costa in the doc. I always want to make sure that the authors are recognized for their contributions.

**Comment by shaojim** [comment]
hello, could I get helps about transition dipole from you? I now can calculate dipole moment matrix, also the strength of dipole moment accurately, but I can not figure out the direction of dipole moment. Since in the WaVEDERF output, the dx, dy,dz seems not to be the direction of kpoints.

**Comment by shaojim** [comment]
I am wirting to ask helps from you for VASP calculation about optic transition dipole matrix (output by Linear_optic.F).

      I now can calculate dipole moment matrix, also the strength of dipole moment accurately, but I can not figure out the direction of dipole moment.  Since in the WAVEDERF output, the dx, dy,dz seems are in cart coordinates but not to be the coordinates of used by kpoints (kx, ky ,kz).  
  
     The dipole moment is defined as, <Psi_Val | r_i | Psi_Con> = <Psi_Val | d/dk_i | Psi_Con> but I can not figure out the "i,j,k", the CDUM(1),CDUM(2),CDUM(3) directions in linear_optic.F files. CDUM(1:3)=CDER_BETWEEN_STATES(NB1,NB2,NK,ISP,1:3) 

     My quesition is, the direction or axis for CDUM(1), CDUM(2) and CDUM(3) ; is it along kx, ky and kz, respectively?  

      For instance, I calculate Hexagonal w-ZnO along gamma_A (0,0,0.5) in rec kpoints coordinates, but dipole moment has  zero value along dz direction, but a strong Zn-O bond are along gamma_A direction seems leads to strong dipole along kz. 

     I would be very appreciated if I could I could get hleps from you. 

Best,
Tianjiao Shao

**Comment by debmalyakan** [comment]
Hi,
Can anyone share an example of WAVEDERF file with me? I want to see what exactly it writes i.e. in which format. I am still struggling to compile the VASP to generate the WAVEDERF file. 

Best,
Debmalya Ray

**Comment by migueldiascosta** [comment]
@debmalyakan see if this helps:  https://gist.github.com/migueldiascosta/aeae055c024bf26f595b3ed4dcbce341

**Comment by migueldiascosta** [comment]
@shaojim sorry for the (very) late reply, but I'm not sure if I can help you. In your example, do you mean all dipoles along z direction are zero? In general the dipole at a specific k point between a specific pair of bands depends on the orbital character of those bands at that point, and in many cases may well be zero due to selection rules...

**Comment by shaojim** [comment]
Dear Debmalya Ray, 


Please find in attach I calculate the wavederf. 


Best, 
Tianjiao Shao 






At 2018-02-22 02:45:34, "debmalyakan" <notifications@github.com> wrote:


Hi,
Can anyone share an example of WAVEDERF file with me? I want to see what exactly it writes i.e. in which format. I am still struggling to compile the VASP to generate the WAVEDERF file.

Best,
Debmalya Ray

**Comment by shaojim** [comment]
One need to modify the linear_optic.f in vasp program, to uncomment and let them output to wavederf document, the wavedef is like this 
           1          60           8
           1           1 (1.8741009E-10,2.5399544E-12)
           1           2 (0.4166370,0.1413575)
           1           3 (0.1636533,8.6130545E-02)
           1           4 (0.1836701,5.7265228E-03)
           1           5 (6.5361980E-11,1.2927599E-09)
           1           6 (1.9887898E-09,1.2232620E-09)
           1           7 (1.1974201E-02,6.9308490E-02)

**Comment by shaojim** [comment]
[modified_script_optic.zip](https://github.com/materialsproject/pymatgen/files/1855271/modified_script_optic.zip)

**Comment by shaojim** [comment]
@migueldiascosta Dear Migueldiascosta, Thank you very much for replying me. I also think dipole defined as <Psi_m |r| Psi_n> are used to describe the transition, when dipole equal to zero which indicates the forbidden for transition, and now I can get wavederf in vasp. But I want to ask a favor of you, is the vasp output the dipole in units of atomic units ? the vasp codes are written in atomic units ? I am appreciated for getting your helps

**Comment by shaojim** [comment]
@debmalyakan Dear Debmalya Ray please find my attached files and I appologize to reply later 
[modified_script_optic.zip](https://github.com/materialsproject/pymatgen/files/1855307/modified_script_optic.zip)

**Comment by priyashrv** [comment]
Hi Can you please let me know how to calculate transition probability ( if there is a script available ?) i have wavederf file with me ...Thanks

**Comment by shaojim** [comment]
I use semi-conductor bloch equation to compute probability, please find in PRL 113, 073901 (2014)

**Comment by priyashrv** [comment]
Hi, i am a newbie. I would like to calculate square of dipole transition matrix ie transition probability from vbm to cbm. i have wavederf file but i dont know how should i proceed. Any help would be great (like any script or code) Thanks.

**Comment by shyuep** [comment]
@priyashrv Pls post this at https://pymatgen.discourse.group .

**Comment by Haysun** [comment]
> Hello all,
> 
> we've recently been uncommenting a line (CALL WRT_CDER_BETWEEN_STATES_FORMATTED..) in vasp linear_optics.F which writes WAVEDERF, a formatted version of WAVEDER, to get the optical transition matrix elements, and we were thinking this could be a nice addition to vasp_output.py, since coupled with other band structure features of pymatgen it can allow interesting analyses and/or visualizations.
> 
> However, since the default output is unformatted, do you have a recommendation for how to read it from python or do you just avoid these files altogether? If the latter, we can easily read from WAVEDERF but that will only be present if people uncomment that line and recompile vasp...
> 
> Cheers,
> Miguel

Dear Miguel
 I want to plot optical transition probability from WAVEDER file,But I don't know how to run "linear_optics.F" This program, thank you very much for your help.


Haysun

**Comment by migueldiascosta** [comment]
@Haysun the routines in `linear_optics.F` are run when you run VASP with `LOPTICS`. 

So, if you simply uncomment the `!   CALL WRT_CDER_BETWEEN_STATES_FORMATTED(` line in `linear_optics.F` and recompile VASP, the WAVEDERF file will be created alongside the WAVEDER file when VASP is run with `LOPTICS`

(I haven't tested this with VASP 6, or used this at all in years, but the commented line is still there)

**Comment by Haysun** [comment]
@migueldiascosta ,Thank you very much for your reply, I will use the method you said to get WAVEDERF, but I have a doubt that how do we get the transition matrix through WAVEDERF?  
Thanks for your help and good luck.

**Comment by migueldiascosta** [comment]
@Haysun see if this helps, https://gist.github.com/migueldiascosta/aeae055c024bf26f595b3ed4dcbce341, and you can also have a look at the vasp code itself
