### ISSUE TITLE
SubstrateAnalyzer not returning the substrate matches

### ISSUE THREAD

**Issue by elw812** [materialsproject/pymatgen#2192]
**Describe the bug**
pymatgen.analysis.interfaces.substrate_analyzer returns None objects rather than SubstrateMatch objects. 

**To Reproduce**
Code to run:

from pymatgen.analysis.interfaces.substrate_analyzer import SubstrateAnalyzer 
from pymatgen.ext.matproj import MPRester
mpr = MPRester("API_KEY")
substrate = mpr.get_structure_by_material_id("mp-19009")
film = mpr.get_structure_by_material_id("mp-23")

sa = SubstrateAnalyzer()
gener = sa.calculate(film, substrate, lowest = True)
list(gener)

**Expected behavior**
Expect an equal sized list of SubstrateMatches.

**Desktop (please complete the following information):**
 - Windows 10
 - Version 2022.0.9

**Additional context**
A way to fix this would be adding a return at L69 here: https://github.com/materialsproject/pymatgen/blob/v2022.0.9/pymatgen/analysis/interfaces/substrate_analyzer.py, but I'm not certain if the list of Nones is expected behavior somehow and I might just be calling it incorrectly. 

Also, is it just the build rather than the calculations themselves that are different from Version 2020.7.3's substrate_analyzer (https://pymatgen.org/_modules/pymatgen/analysis/substrate_analyzer.html)? The reason I ask is because I find calculating the MCIA much simpler with the dict version of returning the matches. Is there something simple like in this forum post (https://matsci.org/t/how-to-find-the-substrate-for-my-own-structure/967/2) I can use without doing a cross product with the film_sl_vectors field?

**Comment by mkhorton** [comment]
Also tagging @shyamd here. A recent PR #2149 cleaned up a lot of the interface functionality and added new features.

**Comment by shyamd** [comment]
Yup. Dumb bug on my part. Already opened a PR to fix it in #2198

**Comment by mkhorton** [comment]
Thanks!
