### ISSUE TITLE
Inconsistent use of output file path in Structure.to() method

### ISSUE THREAD

**Issue by yw-choi** [materialsproject/pymatgen#2195]
**Describe the bug**
Structure.to() method ignores the parent path of filename for certain file formats, say, .xsf format.
For example, in the following scenario,
```python
struct = Structure(...)
struct.to(filename="/path/to/struct.ext") 
```
the output file is correctly written to /path/to/struct.ext when .ext is .cif, .mcif, .json, .cssr, .poscar. But, for some formats including .xsf, it is written at ./struct.ext (current directory).

This is because, in the source code of to(), fname (which only contains the basename of the given filename) is used instead of filename variable for some extensions.
For example,  in core/structure.py:2303-2310, 
```python
        elif fmt == "xsf" or fnmatch(fname.lower(), "*.xsf*"):
            from pymatgen.io.xcrysden import XSF

            s = XSF(self).to_string()
            if filename:
                with zopen(fname, "wt", encoding="utf8") as f:
                    f.write(s)
            return 
```
zopen uses fname instead of filename. It is also the case for some other extensions.

**Expected behavior**
I think to() method should always use filename as the output path.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur

**Comment by janosh** [comment]
Thanks for the report. I didn't see your issue at the time but this was fixed in 6a6056cd417f1310d6810cf3ebdd2d2126fe4d41 and released in [v2022.11.1](https://github.com/materialsproject/pymatgen/releases/tag/v2022.11.1).
