### ISSUE TITLE
Improve resource structure to work better with systems that package code and data

### ISSUE THREAD

**Issue by jdagdelen** [materialsproject/pymatgen#2197]
**Is your feature request related to a problem? Please describe.**

The current implementation of pymatgen is difficult to adapt/use in environments where data files are packaged separately from source code. In these cases, the actual file name of the resource, such as `pymatgen/analysis/op_params.yaml` won't necessarily have the same root path as the code opening it, so things like the following do not work:

```
_directory = os.path.join(os.path.dirname(__file__))

with open(os.path.join(_directory, "op_params.yaml"), "rt") as f:
    default_op_params = yaml.safe_load(f)
```

We also use monty to read data files which can introduce non-deterministic bugs. Feedback from engineer at FAANG company using pymatgen regarding monty:
"Monty loads check by filename for a mplk. Since these are packaged files, they have a lot of random identifiers early on
And if you're running 10K jobs, these often yield bugs."

**Describe the solution you'd like**
1. Create a single submodule/function for loading resources so that users on HPC systems that package data files can modify one load function instead of dozens/hundreds across entire library. 
2. Where possible, use yaml.safe_load and json.load instead of monty

Open to discussion about best way to/whether to accommodate these use cases @mkhorton @shyuep.

**Comment by shyuep** [comment]
Thanks for the feedback. but I need a bit more context about where this is causing problems. In general, data files that are packaged are meant to be defaults. If alternatives are allowed, those code should be implemented with an argument to allow other files to be supplied. So pls provide a specific scenario where these break and code changes are needed. We use pymatgen on HPC resources too and as far as I know, the code and data reside in the same paths. 
I don't remember a scenario where python will install code and data files to different paths, even though the MANIFEST specifically includes the files in the right paths.

Loading by filename is a feature, not a bug. I got tired of typing multiple lines with lots of words to load files. Of course, I can add an arg to monty to force a choice of format. That can be an additional flexibility.

Minor thing: I think we should avoid stipulating feedback sources as "from FAANG engineer". That is not a credential. A FANNG engineer can be someone like Jeff Dean or a lowly intern. The source can either come with proper name and credentials (e.g., master python programmer) or no source needs to be specified and we will objectively evaluate the feedback regardless of source.

**Comment by shyuep** [comment]
I have implemented a fmt override for monty. See https://github.com/materialsvirtuallab/monty/commit/02de6b36dd8a00519a40789bee38e66d513ac48a 

Will wait for discussion of the rest of the feedback.

**Comment by jdagdelen** [comment]
Thanks for getting back to me so quickly. I'm a student in Kriistin's group but doing an internship this summer, which is where this suggestion comes from. To clarify, I just said "FAANG" to clue in Matt/you about the kind of system this is an issue on, not as a credential, and used his quote because I'm not too familiar with monty and I didn't want to mis-translate something.

> We use pymatgen on HPC resources too and as far as I know, the code and data reside in the same paths.
That's a key difference between NERSC and our system. I'm still sort of new to this infrastructure, so I might not have a 100% accurate understanding of the details, but on our system code and data don't reside on the same path and you can't open files that are in a "code" path at runtime. I'm not sure if it's for security, performance, or something else, but I think other companies/institutions might use similar infrastructure. 

We can certainly keep all the modifications we have to do to use pymatgen in our internal version, but if it made sense for other users too maybe it makes sense to implement it in the main branch for other users to use. I'm happy to make these changes to how resources are accessed and submit a PR myself, but I just wanted to have the discussion with you and Matt first before writing any code.

**Comment by jdagdelen** [comment]
Doing a little digging, I think this is a broader topic on how resources are handled in python, not specific to pymatgen. 

For example, [importlib-resources](https://importlib-resources.readthedocs.io/en/latest/using.html) seems to be addressing this exact issue.
