### ISSUE TITLE
KeyError when accessing PDOS via sites

### ISSUE THREAD

**Issue by tawe141** [materialsproject/pymatgen#2207]
**Describe the bug**
I cannot use `vasprun.complete_dos.get_site_orbital_dos()` in the snippet below because the site I pass in cannot be matched to any of the sites despite passing it a `PeriodicSite` directly from the structure. 

My naive suspicion is that there is something going on with how the sites are compared. The hash of a Periodic site is just its atomic number, assuming no partial occupancies. For a structure that has more than one site with the same hash, Python's dict probably does an iterative comparison between the given site and all sites in its keys with the same hash. Somehow, the comparison between two of the same sites is failing. 

**To Reproduce**
```
from pymatgen.io.vasp.outputs import Vasprun
vr = Vasprun('vasprun.xml')
print(vr.structures[-1][10] in vr.complete_dos.pdos.keys())   # will print False
vr.complete_dos.get_site_dos(vr.structures[-1][10])   # will throw KeyError
```
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-666f345603d6> in <module>
----> 1 vr.complete_dos.get_site_dos(vr.structures[-1][10])

~/miniconda3/lib/python3.7/site-packages/pymatgen/electronic_structure/dos.py in get_site_dos(self, site)
    685             Dos containing summed orbital densities for site.
    686         """
--> 687         site_dos = functools.reduce(add_densities, self.pdos[site].values())
    688         return Dos(self.efermi, self.energies, site_dos)
    689 

KeyError: PeriodicSite: Cr (2.9902, 8.4576, 5.1792) [0.0000, 0.5546, 0.0000]
```

See `vasprun.xml` file here: https://www.dropbox.com/s/3qss6jus4uvgjxw/vasprun.xml?dl=0

**Expected behavior**
This should index the pdos just fine, considering the site that pdos is indexing is directly from the structure. 

**Desktop (please complete the following information):**
 - OS: Mac OSX Big Sur 11.5.1
 - Version 2021.2.8.1

**Comment by shyuep** [comment]
This is not really the way this is meant to be used. The structure associated with the complete dos object is stored in the dos.structure attribute. So all you need to do is to replace vr.structures[-1] with dos.structure. vr.structures[-1] may not be exactly the same as the final structure since that is just the structure of the final relaxation step.

**Comment by tawe141** [comment]
Got it, thanks Shyue!
