### ISSUE TITLE
import Lattice error in Anaconda

### ISSUE THREAD

**Issue by mersadkhan** [materialsproject/pymatgen#2209]
**Describe the bug**
1. Install Anaconda3-2020.11-Linux-x86_64
2. install pymatgen by :
```
conda install --yes numpy scipy matplotlib
pip install pymatgen
```
3. run python and 

`from pymatgen import Lattice `

```
Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pymatgen import Lattice
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Lattice' from 'pymatgen' (unknown location)
```

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Version [mint 20]

**Additional context**
the below command works and I check the file is all installed in the right place
import pymatgen

**Comment by shyuep** [comment]
Lattice needs to be imported from either pymatgen.core or pymatgen.core.lattice. Convenient imports have been removed from v2022.0.
