### ISSUE TITLE
get_entries_in_chemsys reports TypeError in the latest version (2022.0.11)

### ISSUE THREAD

**Issue by jf-codeplay** [materialsproject/pymatgen#2214]
**Describe the bug**
After upgrading to version 2022.0.11, I was trying to use `get_entries_in_chemsys` to obtain entries in a high dimentional chemical space. However a TypeError occurred, which pointed to the compatibility module under entries.

**To Reproduce**
The chemical system I demonstrated here is from pymatgen user manual (https://pymatgen.org/usage.html#:~:text=Finally%2C%20the%20MPRester,can%20be%20determined%3A). Below is the test code:

```
from pymatgen.ext.matproj import MPRester
with MPRester() as m:
    mp_entries = m.get_entries_in_chemsys(["Li", "Fe", "O"])
print(len(mp_entries))
```

After running this simple snippet, the error message looks like this:
```
Traceback (most recent call last):
  File "sample.py", line 4, in <module>
    mp_entries = m.get_entries_in_chemsys(["Li", "Fe", "O"])
  File "/.local/lib/python3.8/site-packages/pymatgen/ext/matproj.py", line 872, in get_entries_in_chemsys
    entries = self.get_entries(
  File "/.local/lib/python3.8/site-packages/pymatgen/ext/matproj.py", line 565, in get_entries
    entries = MaterialsProject2020Compatibility().process_entries(entries, clean=True)
  File "/.local/lib/python3.8/site-packages/pymatgen/entries/compatibility.py", line 559, in process_entries
    for entry in PBar(entries, disable=(not verbose)):
TypeError: __init__() got an unexpected keyword argument 'disable'
```

**Expected behavior**
When I tested with an older version 2022.0.5, I can get the normal output, with the size of chemical space as 362:

```
python3 sample.py
/.local/lib/python3.8/site-packages/pymatgen/ext/matproj.py:567: FutureWarning: __init__ is deprecated
MaterialsProjectCompatibility will be updated with new correction classes as well as new values of corrections and uncertainties in 2020
  entries = MaterialsProjectCompatibility().process_entries(entries)
362
```

Do you guys have any thoughts if there's any compatibility issue with the recently updated version?
Cheers

**Comment by shyuep** [comment]
I used the exact code you paste and did not get any error. I suspect your install may be out of date. Can you remove pymatgen and reinstall and try again?

**Comment by jf-codeplay** [comment]
> I used the exact code you paste and did not get any error. I suspect your install may be out of date. Can you remove pymatgen and reinstall and try again?

Hi Shyue Ping,

The error was found when running a pip-installed pymatgen on our HPC cluster:
```
python-3.8.5
pip-21.2.4
pymatgen-2022.0.11
Gadi supercomputer, NCI Australia, as you may know
```
Later on I tried to test it out on my local pc using the recommended conda-forge, the problem was gone. I feel this error might have something to do with the pip install but I don't have a clue yet. I'll just stick to the local conda version by now and thank you very much for your valuable advice. Best wishes, Jiaxin

**Comment by shyuep** [comment]
On your HPC, I would suggest you do a local conda install, followed by a conda virtual env and then a pip or conda install in that virutal env. On public systems, there is no way to verify what has actually been installed in the main system or whether it has been properly kept up to date.  pymatgen.org provides instructions on computing clusters.
