### ISSUE TITLE
Small bug of pymatgen.apps.borg.hive

### ISSUE THREAD

**Issue by Jeff-oakley** [materialsproject/pymatgen#2222]
**Describe the bug**
At the assimilate method of SimpleVaspToComputedEntryDrone, it checks for existence of multiple INCAR POTCAR and DYNMAT with the following commands:
if len(files) == 1 or filename in ("INCAR", "POTCAR", "DYNMAT"):
   files_to_parse[filename] = files[0]
If there is no DYNMAT file in the calculation directory, this will raise up an error as files list is empty so the indexing can not be done.

**To Reproduce**
This can be easily reproduce if you start a DFT calculation directory that does not have DYNMAT file

**Expected behavior**
It should continue even without DYNMAT file

**Screenshots**
N/A

**Desktop (please complete the following information):**
All platforms

**Additional context**
Can be easily fixed. Such as using try  except instead and continue even without DYNMAT file

**Comment by mkhorton** [comment]
Hi Bin, just a note that at Materials Project we mostly now use the drone in [`atomate`](https://github.com/hackingmaterials/atomate/blob/ac461f3f252fb484435e1a404d0877a36b0fdf4f/atomate/vasp/drones.py) rather than the simple drone here. This is not directly relevant to your bug report but thought I would let you know in case you were looking for this functionality.

**Comment by shyuep** [comment]
@mkhorton As I have said several times, the drone in atomate should be moved to pymatgen. It is unclear to me why the concept should be ported to atomate and there is a refusal to move it back to pymatgen proper so that people do not have to do it using atomate.

**Comment by Jeff-oakley** [comment]
> Hi Bin, just a note that at Materials Project we mostly now use the drone in [`atomate`](https://github.com/hackingmaterials/atomate/blob/main/atomate/vasp/drones.py) rather than the simple drone here. This is not directly relevant to your bug report but thought I would let you know in case you were looking for this functionality.

Got it. Thanks for the note.
