### ISSUE TITLE
ase name clash

### ISSUE THREAD

**Issue by matk86** [materialsproject/pymatgen#223]
Hi,
I just installed pymatgen version 3.1.5 and i was trying to use the aseadaptor from io/ase.py module. It seems like the module name clashes with the ase package and the statement 'from ase import Atoms' doesnt run evenafter installing ase. I was using version 3.1.0 before and didnt have any trouble using the adaptors.
-Kiran

**Comment by shyuep** [comment]
I am not sure how there can be a name conflict. The ase package is properly namespaced in pymatgen. You just do 

```
from pymatgen.io.ase import AseAtomsAdaptor
```

This works perfectly fine to me.

**Comment by matk86** [comment]
Hi shyuep,
Yes, that works fine, but when i do the following(structure is a Structure object):

>>> AseAtomsAdaptor().get_atoms(structure)

i get

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matk/Software/mpint2/lib/python2.7/site-packages/pymatgen-3.1.5-py2.7-linux-x86_64.egg/pymatgen/io/ase.py", line 48, in get_atoms
    return Atoms(symbols=symbols, positions=positions, pbc=True, cell=cell)
NameError: global name 'Atoms' is not defined

**Comment by shyuep** [comment]
Just pushed a fix.
