### ISSUE TITLE
Add defined tolerances for `Lattice.__eq__`

### ISSUE THREAD

**Issue by CompRhys** [materialsproject/pymatgen#2234]
In `Lattice.__eq__` the code uses the default tolerances for np.allclose which affects the strict equality of structures. Elsewhere the code pattern in `pymatgen` appears to be to have a `cls.blah_tol` for different objects i.e. `Site.position_atol = 1e-4`. The np.allclose defaults are quite strict for my use case and think the code pattern in other classes would be a better way for users to vary the tolerances in a consistent manner rather than me just hacking the `__eq__` function directly.

```python 
 def __eq__(self, other):
        """
        A lattice is considered to be equal to another if the internal matrix
        representation satisfies np.allclose(matrix1, matrix2) to be True.
        """
        if other is None:
            return False
        # shortcut the np.allclose if the memory addresses are the same
        # (very common in Structure.from_sites)
        return self is other or np.allclose(self.matrix, other.matrix)
```

**Comment by shyuep** [comment]
Honestly, even the current version of `__eq__` is not technically correct. There is no fixed reference direction in 3D space. E.g., if I rotate the basis vectors by a fixed angle, the lattices are technically still equivalent. The correct definition of `lattice.__eq__` should be that the lattice parameters (lengths and angles) are all within a certain tolerance.

**Comment by CompRhys** [comment]
I don't think that can be changed however because of how the sites positions are specified in terms of Cartesian co-ordinates? the use of Cartesian co-ordinates implies that a choice of axes has been made?

**Comment by shyuep** [comment]
It can. Equality of PeriodicSites is based on fractional coordinates and setting the lattice automatically changes the Cartesian coordinates. The problem areas are whether the structure matching algorithms may have issues with the redefinition.

**Comment by CompRhys** [comment]
Are you going to change `__eq__` or can I add the tolerance?
