### ISSUE TITLE
Extraneous parameter in OPTIMADE extension when using raw filters (plus a missing dependency)

### ISSUE THREAD

**Issue by ml-evs** [materialsproject/pymatgen#2243]
**Describe the bug**

Some minor bugs arising from today's OPTIMADE NOMAD tutorial:

1. The library [`retrying`](https://pypi.org/project/retrying/) is used in the [OPTIMADE extension](https://github.com/materialsproject/pymatgen/blob/f72963b038be33c058c844f93ec2392f1613fffe/pymatgen/ext/optimade.py#L13) but it is not listed as a pymatgen dependency (this was not a problem for the Colab examples as Colab already includes `retrying` in its default environment).
2. When providing a "raw" OPTIMADE filter to `OptimadeRester`, the response fields are set incorrectly, with an extraneous `fields=` prefix. I'm a bit worried that this is actually somewhere where OPTIMADE diverged from [JSON:API Fields](https://jsonapi.org/format/1.1/#document-resource-object-fields) that we could maybe address in the future (by e.g., allowing both).

    The fix is just changing:

    https://github.com/materialsproject/pymatgen/blob/f72963b038be33c058c844f93ec2392f1613fffe/pymatgen/ext/optimade.py#L282

    to

    ```diff
    +            url = join(resource, f"v1/structures?filter={optimade_filter}&fields={fields}")
    -            url = join(resource, f"v1/structures?filter={optimade_filter}&{fields}")
    ```

    (reported by Daniel Massote)

**Desktop (please complete the following information):**
 - Version 2020.0.14

I'm happy to make the PR to address no. 2,  but I assume a pymatgen maintainer will want to deal with no. 1 as they see fit.

**Comment by mkhorton** [comment]
Hi @ml-evs,

Thanks for the write-up. I will address 1. myself, but if you're willing to make a PR for the latter, that would be of course welcome!

**Comment by ml-evs** [comment]
Great!

re: `retrying`, I ran into it in a fresh binder env that I used for your tutorial: https://mybinder.org/v2/gh/Materials-Consortia/optimade-tutorial-exercises/HEAD?filepath=notebooks%2Fdemonstration-pymatgen-for-optimade-queries.ipynb

If you remove it from the first `pip install` line then the import of `OptimadeRester` fails, so not sure it is pulled in by plotly.

**Comment by ml-evs** [comment]
Looks like binder's default env is Python 3.7, if that helps, and some plotly subpackage has some kind of dependency on it... 

https://github.com/plotly/plotly.py/blob/03979d105c65dda3df3a155322eaff18f203b03f/packages/python/chart-studio/setup.py#L44

**Comment by mkhorton** [comment]
Yes, I think I mis-remembered, or maybe it changed. I disabled it for now at least pending a re-evaluation.
