### ISSUE TITLE
cannot import name 'coord_cython' from 'pymatgen.util'

### ISSUE THREAD

**Issue by courage0412** [materialsproject/pymatgen#2246]
Hello everyone,

When I run 'from pymatgen.core.structure import Molecule' to check whether it works well, something wrong happens like this:
![Screen Shot 2021-09-10 at 11 28 45 PM](https://user-images.githubusercontent.com/90034730/132847231-0439d4b8-9d45-4029-a858-b124e511abca.png)

Is there any reason or solution for this issue?

**Comment by shyuep** [comment]
Pls reinstall pymatgen. Try pip install --update pymatgen.

**Comment by courage0412** [comment]
> Pls reinstall pymatgen. Try pip install --update pymatgen.

It works, thank you so much for your help!

**Comment by Ocean-JH** [comment]
I've tried upgrade it but it didn't work. There is no coord_cython.py but a coord_cython.cp39-win_amd64.pyd in pymatgen/util/.
And seems the error just happen with jupyter notebook (it runs well on pycharm...).

**Comment by shyuep** [comment]
This just means that your Jupyter is in a different environment from your pymatgen install. Use a dedicated environment.
