### ISSUE TITLE
A bug in pointgroupanalyzer?

### ISSUE THREAD

**Issue by qzhu2017** [materialsproject/pymatgen#2250]
**Describe the bug**
I am trying to use the `PointGroupAnalyzer` to perform some symmetry analysis on some cluster. However, it does not work as I expected for some cases.

**To Reproduce**
```python
from pymatgen.core import Molecule
from pymatgen.symmetry.analyzer import PointGroupAnalyzer

xyz = """15
C7 N8
C -0.000000 -0.000002  1.048832
C  1.008447  0.765201  0.191851
C -1.008448 -0.765196  0.191849
C  2.019657  1.482290  1.088066
C -2.019653 -1.482295  1.088058
N  2.932883  2.279851  0.284256
N -2.932877 -2.279853  0.284246
C  3.030291  3.615607  0.223535
C -3.030270 -3.615608  0.223507
N  3.994395  3.952771 -0.650098
N -3.994383 -3.952767 -0.650120
N  4.468392  2.802027 -1.112496
N -4.468410 -2.802025 -1.112481
N  3.829808  1.789427 -0.549517
N -3.829830 -1.789428 -0.549487
"""

m = Molecule.from_str(xyz, fmt='xyz')
for tol in [0.01, 0.1, 0.5]:
    pga = PointGroupAnalyzer(m, 0.01); 
    print(tol, pga.sch_symbol)
```

```
$ python bug.py 
0.01 C1
0.1 C1
0.5 C1
```
**Expected behavior**
The above example clearly has a C2 symmetry along z-axis, i.e., (x, y, z) -> (-x, -y, z),
However, I tried to used different tolerance, it always returns `C1` symmetry.

**Desktop (please complete the following information):**
I am using pymatgen-2022.0.12 on Mac-os.

**Comment by shyuep** [comment]
The relevant tolerance in this case is the `eigen_tolerance`, which determines whether it is classified as a symmetric top or not. Setting `eigen_tolerance=1e-3` gives C2 as expected.
