### ISSUE TITLE
convert from pymatgen Molecule/Structure into SMILES/SELFIES and vice versa

### ISSUE THREAD

**Issue by turmeric-blend** [materialsproject/pymatgen#2252]
**Is your feature request related to a problem? Please describe.**
It would be a useful feature to have, especially if this could be done for [SELFIES](https://github.com/aspuru-guzik-group/selfies). SELFIES is a new more robust version of SMILES. It is useful because it might be good to explore machine learning on string-based structures as they have different ease of computation or might learn different compared to structure-based molecules such as pymatgen.

**Describe the solution you'd like**
convert from pymatgen's `Structure`/`Molecule` to SELFIES (ideally)
otherwise
convert from pymatgen's `Structure`/`Molecule` to SMILES

**Additional context**
note the SELFIES github page has a feature to convert SMILES TO SELFIES and vice versa

**Comment by shyuep** [comment]
Converting to SMILES is already possible. That can be done via the babel interface in pymatgen.io.babel. As for SELFIES, I am happy for it to be included if someone implements it.

**Comment by turmeric-blend** [comment]
Hi, could you give a small example of how to use pymatgen.io.babel to convert `pymatgen` Structure/Molecule to SMILES?

I am trying to initiate `BabelMolAdaptor()`, but I am getting this error:

> RuntimeError: BabelMolAdaptor requires openbabel to be installed with Python bindings. Please get it at http://openbabel.org (version >=3.0.0).

I am not sure how to properly install this.

**Comment by shyuep** [comment]
openbabel is available on the conda-forge channel via `conda install -c conda-forge openbabel`. This is documented in pymatgen.org. Pls refer to that if you have other questions.

**Comment by shyuep** [comment]
Once openbabel is installed, the smiles is as easy as 

```python
from pymatgen.core import Molecule
m = Molecule.from_file("molecules/Carbon_Disulfide.xyz")
print(m.to(fmt="SMILES"))
```

**Comment by turmeric-blend** [comment]
I see, I guess that SMILES string can then be converted into SELFIES using:

```
import selfies
selfies_string = selfies.encoder(smiles_string)
print(selfies_string)
```

Thanks for your help!
