### ISSUE TITLE
Update AFLOW prototype library

### ISSUE THREAD

**Issue by jacksund** [materialsproject/pymatgen#2254]
Would someone be able to update the `aflow_prototypes.json` in the `pymatgen.analysis` module?

Currently it only includes 288 prototypes (so Part 1 of their library), but they are now at 1,100 prototypes (thanks to Parts 2 and 3).

I don't use the aflow software, so I'm not sure how to download these structures and update them myself. I was hoping someone here could update it with a quick script!

**Comment by jacksund** [comment]
I reached out to the AFLOW team, and they don't want archives of the full library unless you purchase through them ([here's the thread](https://groups.io/g/aflow/topic/85959008)). 

I'll close this request because these prototypes cannot be updated to the full library😢

**Comment by shyuep** [comment]
Hahahaha
