### ISSUE TITLE
Pymatgen Zeo++ installation help

### ISSUE THREAD

**Issue by cwaitt** [materialsproject/pymatgen#2255]
I am following the directions on the pymatgen documentation site on installing and setting up Zeo++ and Voro++ (https://pymatgen.org/pymatgen.io.zeopp.html#zeo-installation-steps). When I do the svn chackout command I get an "Access denied" error. I found an older Bug back from 2016 that offered a solution but when I tried that it still did not work. any guidance will be much appreciated!

**Comment by arosen93** [comment]
Zeo++ and its related tools have moved around a bit over time. The current version of Zeo++ can be found [here](http://www.zeoplusplus.org/download.html) and Voro++ [here](https://github.com/chr1shr/voro.git).

**Comment by arosen93** [comment]
@mkhorton -- looks like I closed this one in https://github.com/materialsproject/pymatgen/pull/2400.

**Comment by arosen93** [comment]
@janosh: This can be closed based on my prior PR.
