### ISSUE TITLE
BasePhaseDiagram should be renamed

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#2270]
I am not sure when this class was introduced. But whatever it is, the naming is not good. A new user coming to pymatgen will be wondering what the heck is a BasePhaseDiagram. It has the connotations of an abstract base class but is actually not one. Then the original PhaseDiagram class inherits from BasePhaseDiagram but calls a PRIVATE method in the init. That is all kinds of ludicrous in design.

Pls revert such that PhaseDiagram is the actual base class and if you want something to just store the computed PD results, write a dataclass or a "CalculatedPhaseDiagram" (similar to "BalancedReaction") that stores the results.

**Comment by shyuep** [comment]
I understand that point. Just that this is not the right way to do this. Let me suggest another approach:

```python
class PhaseDiagram(MSONAble):

    def __init__(entries, *, computed_data:dict=None):
        if computed_data is None:
            <same old code>
        else:
            <load computed data and skip computation>
```

`as_dict` and `from_dict` will store and get the computed data.

**Comment by mkhorton** [comment]
That seems reasonable, I'm fine with that change (with the caveat that it would break backwards compatibility, but I think that would affect a small number of people, probably mostly ourselves).

**Comment by mkhorton** [comment]
Interesting, I'll let the person know who implemented it. I imagine they only added tests for as_dict/from_dict rather than checking the full round trip to JSON string.
