### ISSUE TITLE
Logger calls that appear to be historic and could potentially be removed in `ReactionDiagram`

### ISSUE THREAD

**Issue by CompRhys** [materialsproject/pymatgen#2271]
https://github.com/materialsproject/pymatgen/blob/b40ae2d962936a2ad8c2a024a3c0b2efc503e8e8/pymatgen/analysis/phase_diagram.py#L1487-L1489

@shyuep are these logging calls still needed in the code? I can't trace anywhere where they might be used and was wondering if I should clean them up?

**Comment by mkhorton** [comment]
They're debug calls anyway, presumably were useful to whoever was writing that class.
