### ISSUE TITLE
Lattice.find_all_mappings change handedness

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#230]
The Lattice.find_all_mappings can return aligned lattices that change the handedness of the coordinate system. E.g., try

[[  4.71115317  -0.32497418  -2.99516511]
 [ -3.51444478   5.01683676  -0.34400454]
 [  0.1531054   -0.85080479  18.69400637]]

mapping with itself.

Is this really the desired behavior?

@wmdrichards @sdacek - pls check

**Comment by cedergroupclusters** [comment]
Yeah, this is desired. If you want to to map a non-centrosymmetric
structure to its mirror image, you need the rotoinversions. Unless I'm
missing something....

**Comment by shyuep** [comment]
Ok. But the consequence is that the reduction algorithms can swap handedness of lattices. I don't think that's the right behavior.

**Comment by wmdrichards** [comment]
I don't really understand why the reduction algorithms need to use the find_mapping at all, but if its really an issue then find_mapping (rather than find_all_mappings) could be changed to always return proper rotations. 

This wont cause any backwards incompatibility since lattices all have an inversion center, and if a mapping exists there must also be one without inversion.

**Comment by shyuep** [comment]
It is not needed for LLL,but niggli reduction only determines the reduced lattice parameters, not the actual lattice matrix.

**Comment by terencezl** [comment]
pmg.analysis.structure_matcher.StructureMatcher has get_supercell_matrix(), and get_transformation(), sometimes return transformations that will change the handedness.

Try:

```python
st = m.get_structure_by_material_id('mp-542189')
spga = mg.symmetry.analyzer.SpacegroupAnalyzer(st, 0.01)
st_Cc = spga.get_conventional_standard_structure()
stm = mg.analysis.structure_matcher.StructureMatcher(primitive_cell=False, attempt_supercell=True)
stm.get_transformation(st_Cc, st_Cc) # returns matrix with diagnals [1, -1, 1]

# stm.get_transformation(st, st) is good
```

Is this the intended behavior?

According to the docs, StructureMatcher uses niggli reduction scheme too.

**Comment by shyuep** [comment]
I wouldn't worry too much about this. The handedness has no impact in normal crystals, except that the convention is right-handed. VASP will fail if you give it a left-handed crystal, but the VASP output sets already automatically correct for handedness.
