### ISSUE TITLE
Mistakes of argument type on the documentation

### ISSUE THREAD

**Issue by marinebox** [materialsproject/pymatgen#2306]
The example of the argument of `gamma_automatic`([here](https://pymatgen.org/pymatgen.io.vasp.inputs.html#pymatgen.io.vasp.inputs.Kpoints.gamma_automatic)) is strange.
According to the source code, the type of `kpts` and `shift` should be tuple, but these are not tuple in the documentation.

In the other function([here](https://pymatgen.org/pymatgen.io.vasp.inputs.html#pymatgen.io.vasp.inputs.Kpoints)), Sphinx understands that the arguments are tuple. However, Sphinx does not understand the arguments of `gamma_automatic` are tuple.
From these points, it seems that Sphinx doesn't interpret the source code of gamma_automatic well.

I have no idea to fix this mistake, so I submit a new issue.

I found the same mistakes on `monkhorst_automatic`([here](https://pymatgen.org/pymatgen.io.vasp.inputs.html#pymatgen.io.vasp.inputs.Kpoints.monkhorst_automatic)) too.

**Comment by arosen93** [comment]
@mkhorton -- I think this can be closed.

**Comment by mkhorton** [comment]
Thanks for reporting @marinebox, this was fixed in https://github.com/materialsproject/pymatgen/commit/e1cbe781be6651fe9df08190e3620f97adadf22a

**Comment by mkhorton** [comment]
Also thanks @arosen93 for the reminder
