### ISSUE TITLE
Pourbaix diagram is missing compounds

### ISSUE THREAD

**Issue by CFRP-07** [materialsproject/pymatgen#2321]
Hello,

I am new to pymatgen and am trying to reproduce the Pourbaix diagram from the website in python. However, the plot seems to be missing some compounds and I can not figure out why. 
Is it possible to resolve this?

Thanks!

My code:

`# Import necessary tools from pymatgen`
`from pymatgen import MPRester`
`from pymatgen.analysis.pourbaix_diagram import PourbaixDiagram, PourbaixPlotter`

`# Initialize the MP Rester`
`mpr = MPRester('MY-API-KEY')`

`# Get all pourbaix entries corresponding to the Fe-O-H chemical system.`
`entries = mpr.get_pourbaix_entries(["Fe", "Cu"])`
`# Construct the PourbaixDiagram object`
`pbx = PourbaixDiagram(entries, comp_dict={"Fe": 0.5, "Cu": 0.5},
                      conc_dict={"Fe": 1e-8, "Cu": 1e-8}, filter_solids=True)`

`# Construct the pourbaix analyzer`
`plotter = PourbaixPlotter(pbx)`
`plt =  plotter.get_pourbaix_plot()`
`plt.show()`

Generated plot:
![matplotlib](https://user-images.githubusercontent.com/95743637/145177390-b2dc09d1-2038-49c0-bc13-3164f1ae1611.png)

Plot from materials project website:
![website](https://user-images.githubusercontent.com/95743637/145179160-891b27d6-be42-4783-a844-a11c4fd05d84.png)

**Comment by CFRP-07** [comment]
https://matsci.org/t/materials-project-database-release-log/1609/18

Upgrading the pymatgen version from 2020.1.10 to 2022.0.16 worked.

**Comment by mkhorton** [comment]
Thanks for sharing your resolution @CFRP-07 !
