### ISSUE TITLE
VASP Input Sets: Investigate LMAXTAU

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/pymatgen#2325]
Thanks @arosen93:

> If the PAW one-center expansion of the density has component up to L, then the one-center expansion of the kinetic energy density has components up to L+2. This means that as a rule of thumb, for s-elements: LMAXTAU=2, for p: LMAXTAU=4, and for d: LMAXTAU=6. If you are willing to live with the computational costs, the default for LMAXTAU ***should be safe in all cases, except those involving f-elements.*** [emphasis mine]

via https://www.vasp.at/wiki/index.php/LMAXTAU

Will likely add appropriate logic to appropriate VASP input sets.

**Comment by mkhorton** [comment]
Notifying @rkingsbury too as likely relevant for SCAN input sets.

**Comment by arosen93** [comment]
Just to clarify for my own notes too: This is really only relevant if `LAPSH = True`.

**Comment by rkingsbury** [comment]
Thanks @mkhorton ; if you change the SCAN sets just please make sure to check if any validation rules in the validation builder need to change (I don't think they do).

**Comment by arosen93** [comment]
@munrojm, @janosh: We should probably update this in the Atomate2 workflow......

**Comment by arosen93** [comment]
The fix for this can ultimately be copied from the relevant part in the Atomate2 PR: https://github.com/materialsproject/atomate2/pull/362

**Comment by arosen93** [comment]
Apparently there is plenty of ambiguity about this... https://www.vasp.at/forum/viewtopic.php?p=23038

**Comment by janosh** [comment]
We removed the the `_set_lmaxtau` helper entirely in https://github.com/materialsproject/atomate2/pull/362/commits/75c43baab2a3d3caa680da0892fcf7733b7c1bd9 in an attempt to fix this VASP error

```txt
 -----------------------------------------------------------------------------
|                     _     ____    _    _    _____     _                     |
|                    | |   |  _ \  | |  | |  / ____|   | |                    |
|                    | |   | |_) | | |  | | | |  __    | |                    |
|                    |_|   |  _ <  | |  | | | | |_ |   |_|                    |
|                     _    | |_) | | |__| | | |__| |    _                     |
|                    (_)   |____/   \____/   \_____|   (_)                    |
|                                                                             |
|     internal error in: asa.F  at line: 479                                  |
|                                                                             |
|     internal error in YLM3LOOKUP: L or LP > LMAXCG                          |
|      L, LP, LMAXCG 7 1 6                                                    |
|                                                                             |
|     If you are not a developer, you should not encounter this problem.      |
|     Please submit a bug report.                                             |
|                                                                             |
 -----------------------------------------------------------------------------
```

**Comment by arosen93** [comment]
@janosh: Let's close this as being not needed.
