### ISSUE TITLE
Battery Analyzer for Anion Batteries

### ISSUE THREAD

**Issue by sthartman** [materialsproject/pymatgen#2328]
Hello,
Currently, the pymatgen.apps.battery.analyzer module only can handle cation batteries, but there are several emerging battery chemistries with a negatively charged working ion, such as fluoride or chloride. I have some spare time in the next week, so I'll try to update the module to work for anion batteries in the same way as it currently does for cations. I think it will be pretty straight-forward, but please let me know if there are any special considerations to be aware of before I get the pull request ready.

Thanks

**Comment by shyuep** [comment]
This sounds great.
