### ISSUE TITLE
problem for "pymatgen.io.vasp.Poscar"

### ISSUE THREAD

**Issue by Amadeus-System** [materialsproject/pymatgen#2331]
Hi. I have found (probably) **Parsing Error** in the conversion process from "POSCAR" to "structure"
I wanted to convert my POSCAR file to structure object in pymatgen. 
but there's something wrong in the library or my code.

Here is my situation

![캡처](https://user-images.githubusercontent.com/76824867/148499265-2693c85a-7ff3-4563-9236-f0ddc7906b6f.PNG)

As you see, there is a vasp calculation directory containing **POSCAR** file which is standard format of the VASP.
and this code was available in january 5, 2020. in the **Googlecolab** environment.
But today, when I rerun the same code, the error that I did not see occurs. 
I think there's something wrong in the  **sre_parse.py** code.

I would really appreciate if you help me.

**Comment by shyuep** [comment]
Pls provide the actual text POSCAR in the issue report. Giving an image is very difficult for me to try to reproduce the error.

**Comment by Amadeus-System** [comment]
Here is my actual POSCAR file example.

"
Cs1 Pb1 Br3
1.0
6.022257 -0.003742 -0.008211
-0.024789 6.018620 0.014154
0.008111 0.018091 6.002165
Cs Pb Br
1 1 3
direct
0.515001 0.498256 0.486467 Cs
0.021258 -0.001505 -0.000947 Pb
0.004667 0.002804 0.492459 Br
-0.002320 0.516228 0.008898 Br
0.497373 -0.006585 0.008383 Br
"

**Comment by Amadeus-System** [comment]
> Pls provide the actual text POSCAR in the issue report. Giving an image is very difficult for me to try to reproduce the error.

Here is my POSCAR file.

"
Cs1 Pb1 Br3
1.0
6.022257 -0.003742 -0.008211
-0.024789 6.018620 0.014154
0.008111 0.018091 6.002165
Cs Pb Br
1 1 3
direct
0.515001 0.498256 0.486467 Cs
0.021258 -0.001505 -0.000947 Pb
0.004667 0.002804 0.492459 Br
-0.002320 0.516228 0.008898 Br
0.497373 -0.006585 0.008383 Br
"

**Comment by shyuep** [comment]
I can't reproduce this error. It actually works on my end. As for googlecolab, since I don't use that platform, I can't really test it out on there. As far as I can see, all the unittests indicate the code is functioning as it should and on my end, running your code works.

**Comment by Amadeus-System** [comment]
> I can't reproduce this error. It actually works on my end. As for googlecolab, since I don't use that platform, I can't really test it out on there. As far as I can see, all the unittests indicate the code is functioning as it should and on my end, running your code works.

Really??. Oh. Thank you. maybe it is about the problem in googlecolab.
I appreciate for your kind answer
