### ISSUE TITLE
Build broken on Python 3.8

### ISSUE THREAD

**Issue by sphuber** [materialsproject/pymatgen#2333]
Building `pymatgen` on Python 3.8 currently seems broken, see for example [this recent action](https://github.com/materialsproject/pymatgen/runs/4733023541?check_suite_focus=true) on the `master` branch. The problem seems to be the well-known incompatibility of the `numpy` package used for building and the one used when running the tests, resulting in the exception:
```
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
I expect this has to do with the release of `numpy==1.22` about a week ago.

Recent comments [in this issue on `numpy`](https://github.com/numpy/numpy/issues/18709) suggest that the requirement of `numpy>=1.20.1` in `pymatgen`'s `pyproject.toml` have something to do with it and changing this to `numpy>=1.20.3` seems to alleviate the problem.

That being said, maybe using the [`oldest-supported-numpy`](https://pypi.org/project/oldest-supported-numpy/) meta-package in the `pyproject.toml` may be preferable and more robust a solution to prevent these problems from occurring in the future.

**Comment by shyuep** [comment]
Thanks. Indeed there are some really annoying crap happening with numpy binary compatibility between versions.  For now, I have followed your recommendation to increment the numpy version.

**Comment by shyuep** [comment]
Quick update that a new version of pymatgen was released which should fix these problems for now.

**Comment by sphuber** [comment]
Thanks for the release and the update.

**Comment by sphuber** [comment]
Thanks again for the quick action on this @shyuep but I am afraid this fix won't help. The real problem is when `pymatgen` is compiled with a more recent version of `numpy` and then is used with an older version. Since `pymatgen` doesn't specify an explicit version to build with in its `pyproject.toml`, it will automatically pick the latest. This is why things started failing when `numpy=1.22.0` was released on December 31. This now means that `pymatgen` builds can _only_ be run with `numpy==1.22.0` even though it is compatible with older versions as well.

This is a common problem and a common solution exists. One merely has to specify the minimum supported `numpy` version in the `[build]` section of the `pyproject.toml`. This works because `numpy` does guarantee forwards compatibility, so if you compile with an older version of `numpy` you _can_ run with a newer one, but not vice versa. The only problem of this approach that it puts a bit of a burden to keep these versions up to date in the `pyproject.toml`, however, there is a solution for this as well. Simply install  the [`oldest-supported-numpy`](https://pypi.org/project/oldest-supported-numpy/) meta-package in the `pyproject.toml` and it will be done automatically.

**Comment by shyuep** [comment]
But a minimum numpy version actually is specified in the pyproject.toml. It is not 1.22.0.

**Comment by sphuber** [comment]
Yes, but it shouldn't specify a _minimum_ version, but an _exact_ version, and ideally the lowest version that `pymatgen` supports. So if the current version of `pymatgen` is still compatible with `numpy==1.17.0` and up, you specify `numpy==1.17` in the build requirements.

You _can_ specify `numpy==1.21.4` for example, but than that would only ever be compatible with `numpy>=1.21.4` even though `pymatgen` could very well be compatible with older versions.

So to prevent all of these problems and be as loose as possible with restrictions, you should specify something like the following
```toml
[build-system]
requires = [
    "wheel",
    "setuptools",
    "numpy==1.13.3; python_version=='3.5'",
    "numpy==1.13.3; python_version=='3.6'",
    "numpy==1.14.5; python_version=='3.7'",
    # more numpy requirements...
]
```
But this can all be simplified by using the `oldest-compatible-numpy` meta-package to:
```toml
[build-system]
requires = ["wheel", "setuptools", "oldest-supported-numpy"]
```
