### ISSUE TITLE
Drift correction and framework ions in DiffusionAnalyzer

### ISSUE THREAD

**Issue by jic198** [materialsproject/pymatgen#2337]
The drift correction in `DiffusionAnalyzer` is automatically applied when calculating ionic diffusivity. 
(1) Is it always required to include the drift correction for a trajectory? 
(2) It makes sense to include it if all the ions moving in the same direction, but what if the ions are randomly moving around?
(3) If I want to calculate the diffusivities of different species in a same trajectory, should I use a same framework? For example, I have an AIMD calculated trajectory for LiAlO2. When using `DiffusionAnalyzer` to calculate Li diffusivity, Al+O will be the framework and the drift correction will be calculated based on Al+O displacements. Now, I also want to calculate the O diffusivity. Should I use the same framework (Al+O), or use Li+Al as the framework ions and recalculate the drift correction? Using the same framework makes more sense to me as the calculated Li and O diffusivities are based on the same framework.

**Comment by shyuep** [comment]
1. Yes unless you believe the framework is not moving much.
2. Again, this really depends. If the ions are randomly moving and the average motion is close to 0, then it doesn't make a difference whether you include or not.
3. I would definitely choose all ions other than the moving ions to be the famework. In this case, just Al.
