### ISSUE TITLE
TypeError in _get_potcar_symbols()

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#2363]
`class Lobsterin()._get_potcar_symbols()` causes [CI errors in `atomate`](https://github.com/hackingmaterials/atomate/runs/4871532128?check_suite_focus=true#step:8:115)

https://github.com/materialsproject/pymatgen/blob/fd553a8e80935d77df285fed1a14d7bf63669c14/pymatgen/io/lobster/inputs.py#L612-L633

```sh
        with zopen(POTCAR_input, "r") as f:
            data = f.read()
>       if "SHA256" in data or "COPYR" in data:
E       TypeError: a bytes-like object is required, not 'str'
```

Triggered by PR: https://github.com/hackingmaterials/atomate/pull/738

**Comment by JaGeo** [comment]
Will have a look at it as soon as I am back from my vacation ... 

It's just there to warn users if they use the POTCARs including these keywords. If you know how to fix it, please go ahead. Errors seem to be new, though...

**Comment by janosh** [comment]
I guess one way to fix it would be

```diff
- if "SHA256" in data or "COPYR" in data: 
+ if b"SHA256" in data or b"COPYR" in data: 
```

but I was a bit confused by this error as I didn't expect the result `f.read()` to be a `bytes` object in the first place. Since `data` is prob supposed to be `str`, turning "SHA256" into `bytes` string wouldn't be the right fix here.

**Comment by JaGeo** [comment]
Yeah, same. I hope it is not again some test data problem in atomate. 🙈

**Comment by janosh** [comment]
Don't think so. Since `zopen` is coming from `monty` maybe @shyuep can comment how to handle this.

**Comment by shyuep** [comment]
zopen does not do anything to the encoding. It merely passes through to io.open or gzip or bzip2 based on the file extension. So this is not related to zopen. In general, python has become more strict on binary vs text types. So you might have to properly handle the encoding conversions.

**Comment by janosh** [comment]
@JaGeo Thanks, yes I saw the tests pass here. The difference is prob that in `atomate` the POTCAR is gzipped so the returned IO stream comes from `gzip.open()` instead of python's `open()`.

@shyuep You mean check the type and handle the comparison accordingly?

```py
if isinstance(data, bytes):
    if b"SHA256" in data or b"COPYR" in data:
        # ...
else:
    if "SHA256" in data or "COPYR" in data:

**Comment by shyuep** [comment]
No, you should handle the encoding of "data" first. If it is supposed to be a string, it needs to be converted to unicode first. The comparison should be based on unicode, not bytes. Then everything that follows using data should treat it as a proper unicode.
