### ISSUE TITLE
Overlapping of labels when generating XRD pattern

### ISSUE THREAD

**Issue by coiby** [materialsproject/pymatgen#237]
Hi Developers,

I'm trying to use `pymatgen`'s `XRDCalculator` to calculate XRD pattern,
```python
from pymatgen.io.vaspio import Poscar
p=Poscar.from_file('POSCAR')
from pymatgen import Lattice, Structure
from pymatgen.analysis.diffraction.xrd import XRDCalculator
from IPython.display import Image, display
c = XRDCalculator()
c.show_xrd_plot(p.structure)
```
But the labels are overlapping (see the first picture, the second one is generated by [Mercury](http://www.ccdc.cam.ac.uk/Solutions/CSDSystem/Pages/Mercury.aspx) for comparison).
![figure_1](https://cloud.githubusercontent.com/assets/1511656/9565468/862a5e1c-4f03-11e5-81d8-88b263b4c590.png)
![casio3-pxrd](https://cloud.githubusercontent.com/assets/1511656/9565471/b15aa13c-4f03-11e5-95ef-7dd355e36056.jpeg)

And the `POSCAR` file is:
```
EA703   4.479  6.253  4.483 89.98 88.52 89.99 Sym.group:  140
1.0000
    4.434782    -0.333569    -0.535297
    0.604649     6.109109     1.190892
    0.574509    -0.904071     4.352654
  Ca  Si   O
   4    4   12 
Direct
    0.420441     0.172183     0.487161
    0.919817     0.672187     0.986671
    0.920353     0.172163     0.987238
    0.419788     0.672152     0.486645
    0.920094     0.922161     0.486902
    0.420073     0.422169     0.986922
    0.920092     0.422161     0.486960
    0.420120     0.922172     0.986910
    0.169153     0.884713     0.235905
    0.169748     0.459624     0.236617
    0.669827     0.422907     0.237193
    0.171091     0.922894     0.735926
    0.383425     0.172178     0.025121
    0.170364     0.421446     0.736663
    0.456774     0.672145     0.948672
    0.671102     0.959633     0.737915
    0.956984     0.172181     0.448904
    0.883232     0.672166     0.525021
    0.670406     0.384719     0.737275
    0.669141     0.921438     0.237865
```

Btw, I've also tried the examples from [Calculating XRD patterns](http://pymatgen.org/_static/Calculating%20XRD%20patterns.html). They are totally fine. No such problem.

**Comment by shyuep** [comment]
Thanks for reporting this. But this is merely a program that it is difficult ot programmatically determine the optimal positions ot place the labels. If you wish, you can turn off labels in the XRD plot, and then do the labels manually. I am also open to suggests about how to allocate label positions.

**Comment by shyuep** [comment]
I am closing this issue for now. Please feel free to re-open if the above has not solved your problem.
