### ISSUE TITLE
pmg command becomes not to work

### ISSUE THREAD

**Issue by kuwabara74** [materialsproject/pymatgen#2378]
Dear all,

I installed pymatgen through conda. Installation of pymatgen was OK.
However, after setting up the location of POTCAR files according to the instruction in the official web page, pmg command become not t work anymore. In the the setting up of the POTCAR files, I run these command.

> pmg config -p <EXTRACTED_VASP_POTCAR> <MY_PSP>
> pmg config --add PMG_VASP_PSP_DIR <MY_PSP> 
> pmg config --add PMG_DEFAULT_FUNCTIONAL PBE_52

The following error messages appear when pmg command with any option is run.

###############################
Traceback (most recent call last):
  File "/home/kuwabara/anaconda3/envs/pymatgen/bin/pmg", line 7, in <module>
    from pymatgen.cli.pmg import main
  File "/home/kuwabara/anaconda3/envs/pymatgen/lib/python3.10/site-packages/pymatgen/cli/pmg.py", line 15, in <module>
    from pymatgen.core import SETTINGS
  File "/home/kuwabara/anaconda3/envs/pymatgen/lib/python3.10/site-packages/pymatgen/core/__init__.py", line 54, in <module>
    SETTINGS = _load_pmg_settings()
  File "/home/kuwabara/anaconda3/envs/pymatgen/lib/python3.10/site-packages/pymatgen/core/__init__.py", line 44, in _load_pmg_settings
    d.update(d_yml)
TypeError: 'NoneType' object is not iterable
###############################

I uninstalled pymatgen and reinstall. The problem is not resolved.

 - OS: Ubuntu 20.04.3 LTS (on WSL2, Windows10)
 - pymatgen 2022.1.24
 -  python 3.10.2

**Comment by shyuep** [comment]
You need to replace the `<MY_PSP>`, etc. with the actual variables relevant for your system.

**Comment by kuwabara74** [comment]
Dear shyuep, 

Thank you for your comment.
I reset the locations of potcar files like
`pmg config -p ~/POT_GGA_PAW_PBE_52 ~/vasp_potentials`
`pmg config --add PMG_VASP_PSP_DIR ~/vasp_potentials`

My settings and pmg command works after that.
In my case, empty .pmgrc.yaml was created and it caused my trouble. I found that a similar situation was already reported in #2377. My pmg command recovered after deleting the .pmgrc.yaml file.

Thank you again for your help.
