### ISSUE TITLE
structure.as_dict()["charge"] is None even though structure.charge == 0

### ISSUE THREAD

**Issue by arosen93** [materialsproject/pymatgen#2384]
```python
from pymatgen.core import Structure
structure = Structure(
    lattice=[[0, 2.13, 2.13], [2.13, 0, 2.13], [2.13, 2.13, 0]],
    species=["Mg", "O"],
    coords=[[0, 0, 0], [0.5, 0.5, 0.5]],
)
print(structure.charge) # prints 0 
print(structure.as_dict()["charge"]) # prints None
assert structure.charge == structure.as_dict()["charge"]
```

As demonstrated in the above example, when `structure.charge` is left at the default value of 0, the `.as_dict()["charge"]` is returned as `None`. It would be ideal if these were consistent (i.e. the latter should be 0, in my opinion).

Is there a specific reason why `self._charge` is used below instead of `self.charge`?
https://github.com/materialsproject/pymatgen/blob/6c31f7e38268986bd23110c2fbd4f14a09042a2a/pymatgen/core/structure.py#L2205-L2211

**Comment by shyuep** [comment]
I agree. As for why it is self._charge, I think that stores the input charge given by the user. But in other cases, the charge of the structure is given by the sum of the oxidation states of the species where available. In general, charge on a structure is pretty arbitrarily defined.
