### ISSUE TITLE
In some cases pmg.symmetry.analyzer.SpacegroupAnalyzer.get_conventional_standard_structure() returns structure not matching the spacegroup it detects.

### ISSUE THREAD

**Issue by terencezl** [materialsproject/pymatgen#239]
``` python
st = m.get_structure_by_material_id('mp-542189')
spga = mg.symmetry.analyzer.SpacegroupAnalyzer(st, 0.1)
print(spga.get_spacegroup()) # C2/c

st1 = spga.get_conventional_standard_structure()
spga1 = mg.symmetry.analyzer.SpacegroupAnalyzer(st1, 0.1) # this symprec doesn't help 
print(spga1.get_spacegroup()) # P1
```

The curious thing is when either of the two symprec 0.1 above is changed to 0.15, both report C2/c. I can understand why changing the second 0.1 to 0.15 works, because it lowers the tolerance.

After setting the first 0.1 to 0.15, the returned structure has a few sites different from the structured from the 0.1 setting. This difference is very ordered, every five sites within Mo and S.

**Comment by shyuep** [comment]
The get_*_standard_structure method first uses spglib to get a refined structure. That modifies the atoms such that they are in the expected symmetry positions. 

But that really should only preserve or increase symmetry. It is odd that it actually decreases symmetry.

@hautierg Can you investigate if there is a problem with hte get_conventional_standard?

**Comment by janosh** [comment]
Looks like this was fixed sometime in the last 7 years. :)

```py
from pymatgen.ext.matproj import MPRester
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

mpr = MPRester()
st = mpr.get_structure_by_material_id("mp-542189")
spga = SpacegroupAnalyzer(st, 0.1)
print(spga.get_space_group_symbol())  # Cc

st1 = spga.get_conventional_standard_structure()
spga1 = SpacegroupAnalyzer(st1, 0.1)
print(spga1.get_space_group_symbol())  # C2/c
```
