### ISSUE TITLE
selective_dynamics not deserialized in poscar deserialization

### ISSUE THREAD

**Issue by matk86** [materialsproject/pymatgen#240]
in Poscar.from_dict, the selective dynamics is not properly deserialized and consequently the __setattr__ raises exception because it expects a numpy array

example serialized selective dynamics:
"selective_dynamics": [
                        {
                            "dtype": "float64", 
                            "data": [
                                1.0, 
                                1.0, 
                                1.0
                            ], 
                            "@class": "array", 
                            "@module": "numpy"
                        }, 
                        {
                            "dtype": "float64", 
                            "data": [
                                1.0, 
                                1.0, 
                                1.0
                            ], 
                            "@class": "array", 
                            "@module": "numpy"
                        }, 
                        {
                            "dtype": "float64", 
                            "data": [
                                0.0, 
                                0.0, 
                                0.0
                            ], 
                            "@class": "array", 
                            "@module": "numpy"
                        }, 
                        {
                            "dtype": "float64", 
                            "data": [
                                1.0, 
                                1.0, 
                                1.0
                            ], 
                            "@class": "array", 
                            "@module": "numpy"
                        }, 
                        {
                            "dtype": "float64", 
                            "data": [
                                1.0, 
                                1.0, 
                                1.0
                            ], 
                            "@class": "array", 
                            "@module": "numpy"
                        }
                    ]

**Comment by shyuep** [comment]
If we look at the VASP example, the selective dynamics are indicated as T/F, not 1 or 0. The unittests for the T/F case show that it works perfectly fine. 

To do 1/0 is easy, but is this really needed?

**Comment by matk86** [comment]
not really, i used numpy arrays to automatically set the flags for slab relaxations as it would give me finer control over relaxtion settings..
converting the nump array to list solves the issue..
thanks

**Comment by shyuep** [comment]
I see. OK, I have pushed a simple fix to the serialization routine (by down converting the numpy array to a list first). Let me know if it solves your problem?

**Comment by matk86** [comment]
it works as long as numpy array is not used to set the flags in the poscar object. Now the list value for ''selective dynamics'' key in the above example is passed directly to the numpy array. I think the  __setattr__ in the poscar already does that. i think it should be run through the monty decoder process_d, the same way you do it for deserializing vaspinputset in the vaspjob
i fixed by changing my code to use numpy arrays to do the required manupulations and then converting that to a list before creating the poscar object which is then serialized.

**Comment by shyuep** [comment]
Ok thanks. I think there might be minor issues. The conversion to list is not proper. Using list(value) for numpy arrays is bad. So instead of that, I do a np.array(value).tolist(). That forces a proper conversion to a list in the input so that it is always consistent.

**Comment by matk86** [comment]
yes, i agree, thats the fix that i did in my code.
