### ISSUE TITLE
pmg.io.cif.CifWriter with symprec option

### ISSUE THREAD

**Issue by terencezl** [materialsproject/pymatgen#241]
I tried to use the symprec optional arg, but the returned cif files show up funky (clustered) in VESTA, and when reparsed by pymatgen, the total number of atoms is a bit more.

try:
```python
st = m.get_structure_by_material_id('mp-542189')
mg.io.cif.CifWriter(st, 0.01).write_file('Cc.cif')
mg.io.cif.CifWriter(st, 0.1).write_file('C2_m.cif')

mg.Structure.from_file('Cc.cif',primitive=False)
mg.Structure.from_file('C2_m.cif',primitive=False)
```

Both volumes are 449.5, but number of atoms are different, for example.

**Comment by shyuep** [comment]
Note quite sure what is happening, but I suspect the problem is that the original structure from MP is a primitive structure.
