### ISSUE TITLE
install without internet connection

### ISSUE THREAD

**Issue by foster362** [materialsproject/pymatgen#2425]
Hi,

I'm having issues installing/running on a computer without internet connection so I can't just pip install. I believe I have installed all required dependencies. I can build and install "python setup.py build" and "python setup.py install"; I can even do "pip install pymatgen" (all: Requirement already satisfied). So it seems like I have installed it (pymatgen  2022.2.7 is listed in "pip list"); however, if I try to simply import "import pymatgen.core" I get

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/projects/pymatgen-master/pymatgen/core/__init__.py", line 15, in <module>
    from .lattice import Lattice
  File "/projects/pymatgen-master/pymatgen/core/lattice.py", line 22, in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
  File "/projects/pymatgen-master/pymatgen/util/coord.py", line 16, in <module>
    from . import coord_cython as cuc
ImportError: cannot import name 'coord_cython' from 'pymatgen.util' (/projects/pymatgen-master/pymatgen/util/__init__.py)

Within python I can "import pymatgen" then use autofill and see pymatgen.ext and pymatgen.util but that is it.

Thanks for any help

**Comment by shyuep** [comment]
There are a lot of dependency packages. Sorry, but we do expect an internet connection when installing packages.

**Comment by foster362** [comment]
go it
