### ISSUE TITLE
MPRester.get_entries returns empty data dict. 

### ISSUE THREAD

**Issue by miaoliu** [materialsproject/pymatgen#243]
mpr = MPRester(api_key=API_KEY, endpoint="https://www.materialsproject.org/rest/v2")
entry = mpr.get_entries("mp-10",inc_structure="final")[0]
print entry.data

Output gives me an empty data dictionary. Is it normal? 

MPRester.get_data work for me though.

**Comment by shyuep** [comment]
This is normal. But I added functionality to allow you to get specific data. Pull the latest changes and you should be ale to do what you want.
