### ISSUE TITLE
pmgrc.yaml not created when installing pymatgen (Python 3.8, pymatgen 2022.2.10)

### ISSUE THREAD

**Issue by CJBR-97** [materialsproject/pymatgen#2444]
Hello,

After installing pymatgen using 'pip pre-commit pymatgen' from my environment in bash and trying to import a function (OCPCalculator from the ocp module) I receive the following message from the terminal.

**warnings.warn(f"Error loading .pmgrc.yaml: {ex}. You may need to reconfigure your yaml file.")**

I checked in my home directory and found that no yaml file had been created anywhere that I could see.  I am running from the Compute Canada Niagara cluster.  Can you please tell me the likely cause of the problem and/or possible solutions?

**Expected behavior**
I would expect the module to import without this error.

**Desktop (please complete the following information):**
 - OS: [Linux CentOS 7]

Best wishes

**Comment by shyuep** [comment]
This is a warning, not an error. The pmgrc file stores certain settings that is needed if you are generating VASP input files, using the materials project, etc. This warning can be ignored if you are not planning on using those.

**Comment by mkhorton** [comment]
This warning was also updated in https://github.com/materialsproject/pymatgen/commit/cc9dabf49f553fff2700aa514f31a3d17f99b18c, and will be slightly different in the next version: if the `.pmgrc.yaml` is not present at all, the warning will not be generated.

This change was the result of a change in behavior in YAML parsers resulting in corruption of this file for some users.

**Comment by CJBR-97** [comment]
Thank you for the swift and informative replies!
