### ISSUE TITLE
`ChemicalPotentialDiagram.get_plot()` needs better default limits for cleaner plotting

### ISSUE THREAD

**Issue by mattmcdermott** [materialsproject/pymatgen#2446]
**Is your feature request related to a problem? Please describe.**
Chemical potential diagrams tend to look pretty gross with the current defaults, especially for MP data. See screenshot from the new MP website below:

![Screen Shot 2022-02-23 at 5 23 42 PM](https://user-images.githubusercontent.com/40469694/155439237-4a593547-e521-49e1-89ae-7d569d12c3f6.png)

**Describe the solution you'd like**
What is needed is some logic for automatically "deleting" extra whitespace for elemental domains. See new screenshot below:

![Screen Shot 2022-02-23 at 5 27 34 PM](https://user-images.githubusercontent.com/40469694/155439588-512a588a-53cf-4660-926f-59101ba163ec.png)

**Describe alternatives you've considered**
The only alternative is the manual setting of limits, which is tedious and not possible for the MP website.

**Working solution**
I have a working solution for this and will address in an upcoming PR.

**Comment by mkhorton** [comment]
Thanks for taking care of this @mattmcdermott, it was actually an issue in our website issue tracker :)

Part of the issue also seems to be font size related too, I wonder if we can pull the axes labels further from the plot so they don't overlap.

**Comment by mattmcdermott** [comment]
@mkhorton For sure, gonna try to address that as well in #2447. Will try to have it done by tomorrow.

**Comment by mattmcdermott** [comment]
I was not able to figure out how to add space between the axis label and the axis; as far as I can tell, this is not a Plotly feature. (I also couldn't make a hack with HTML breaks to do it either). However, I have changed the size of the ticks and tick labels to help with the visual clarity in #2447  -- I think it looks much better now!

**Comment by mattmcdermott** [comment]
Closing with c70ca529586d848134c2e0e4d9362a0e37d1fdde
