### ISSUE TITLE
Slab generator cuts strong bonds

### ISSUE THREAD

**Issue by cedenoruel** [materialsproject/pymatgen#2454]
Hi pymatgen developers. 

I am generating slab structures for an inorganic crystal containing a phosphate ion (KH2PO4).
I would like to have no broken P--O bonds so I used the  `bonds={("P", "O"): 3}`

```
from pymatgen.core.structure import Structure

KDP = Structure.from_file("input.cif")
KDP.add_oxidation_state_by_element({"K": 1, "H": 1, "P": 5, "O": -2})
all_slabs = generate_all_slabs(KDP, 1, min_slab_size=10, min_vacuum_size=10, bonds={("P", "O"): 3},
center_slab=False,symmetrize=False, lll_reduce=False,ftol=0.00001,tol=0.00001,repair=True)
```

However, when I inspect the symmetric **slab(001)**, **phosphate bond is broken.**

I attached here my input CIF file.
[KDP_Nelmes_295K.zip](https://github.com/materialsproject/pymatgen/files/8193491/KDP_Nelmes_295K.zip)

Any comments would be highly appreciated. Thank you very much for this very useful tool.

**Comment by mkhorton** [comment]
Hi @cedenoruel, I have not had chance to investigate this yet, but is it the case that this still happens even if you do not add oxidation states and skip that `add_oxidation_state_by_element` line? I'm wondering if the bond logic is oxidation-state dependent or not. e.g. is `("P", "O"): 3` different to `("P5+", "O2-": 3)`?

**Comment by cedenoruel** [comment]
Hi @mkhorton , you are right, the bond logic is indeed oxidation-state dependent. 
`` bonds={("P5+", "O2-": 3)}`` solves the issue.
