### ISSUE TITLE
Building model of adding an oxygen atom 

### ISSUE THREAD

**Issue by Guancred** [materialsproject/pymatgen#2456]
Hi pymatgen developers:
I want to add H atoms to the systems randomly, and maintain the distance between H and O , the steps are shown in the figure,

![image](https://user-images.githubusercontent.com/91767936/157224202-f1e0504a-9b38-4a69-b019-3eb5288db1c1.png)

and which function can help me to realize this process? 

Any comments would be highly appreciated. Thank you very much.

**Comment by shyuep** [comment]
Please visit matsci.org for questions of usage. Github Issues should be used for reporting Issues and Bugs only.
