### ISSUE TITLE
scipy.constants 

### ISSUE THREAD

**Issue by gVallverdu** [materialsproject/pymatgen#246]
Hello,
Is it possible to use ``scipy.constants`` module in the implementation of methods or new dependencies are not recommended ?
Are standard physical constants accessible somewhere in pymatgen ?
Thanks

**Comment by gVallverdu** [comment]
Sorry, I have just found constants in the core. Can I add several constants (h and c) ?
Germain

**Comment by shyuep** [comment]
Sure go ahead. Using scipy is fine too since we already incldue scipy as a dependency,
