### ISSUE TITLE
Add option to disable the progress bar for MPRester query

### ISSUE THREAD

**Issue by x94carbone** [materialsproject/pymatgen#2460]
https://github.com/materialsproject/pymatgen/blob/c37ba66cce99e93557b5e44d697059e2c93c0869/pymatgen/ext/matproj.py#L923-L1044

There seems to be no way to disable the progress bar for these queries. This breaks the progress bar/output stream depending on Jupyter and other things. It's a simple improvement and should be added. For example, a simple `verbose` default in the `MPRester.query` method should suffice.

I'm happy to fix and open a PR.

**Comment by shyuep** [comment]
I just pushed an option called `show_progress_bar` to allow you to disable it.

**Comment by shyuep** [comment]
Hmmm thanks. I will leave it. I don't even understand why we need to initialize tqdm if we are not bothering with the progress bar.

**Comment by shyuep** [comment]
It will be released in the next version.

**Comment by arosen93** [comment]
@munrojm, is there a way to do this in the new `mp_api`? I was just wondering this the other day,

**Comment by munrojm** [comment]
> @munrojm, is there a way to do this in the new `mp_api`? I was just wondering this the other day.

Yes, currently there is an environment variable you can set to mute all progress bars. My plan is to also implement it as a input to the generic search methods.
