### ISSUE TITLE
Broken `MagneticSpaceGroupTest.test_symmetry_ops()`?

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#2461]
`msg_1` isn't being tested unlike `msg_(2|3|4)`. Is this intentional?

https://github.com/materialsproject/pymatgen/blob/a740053063c8d0864f23d697a45bcafef3aaadf4/pymatgen/symmetry/tests/test_maggroups.py#L78-L85

**Comment by mkhorton** [comment]
Hi @janosh, I wrote that test, not intentional, I imagine it was an omission. Thanks for flagging it.
