### ISSUE TITLE
(Un?)popular opinion: pymatgen is too OOP

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#2474]
Let me preface by saying I understand `pymatgen` is a mature code base with a large user base (for a research code), hence any breaking changes to the interface will be a slow and painful process. So feel free to close this issue if it's an unwelcome discussion.

---

The point I would like to raise is that many parts of `pymatgen` are packaged into classes even though it's stateless functionality that should really be procedural. On average classes tend to be more verbose with larger surface area for bugs. It can also be harder to reason about than the equivalent procedural code, especially if the code is stateless and could be a pure function instead.

Examples that stand out include:

- [`MPRester`](https://pymatgen.org/pymatgen.ext.matproj.html#pymatgen.ext.matproj.MPRestError): could be a function that always closes the session before returning. Leaving a session open for repeated API calls should require an explicit context manager IMO rather than sth that works both ways, but where only one way of using is recommended.
- [`SpacegroupAnalyzer`](https://pymatgen.org/pymatgen.symmetry.analyzer.html?highlight=spacegroup#pymatgen.symmetry.analyzer.SpacegroupAnalyzer): There's no need to bind space group analysis to a structure. Adds overhead invoking lots of classes if you want to analyze lots of structures. If it's about binding together related functionality, that's what modules are for. No need to wrap it in another layer (i.e. a class inside a module).

  ```py
  # current
  from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

  SpacegroupAnalyzer(structure).get_crystal_system()

  # simpler
  import pymatgen.symmetry.analyzer as psa

  psa.get_crystal_system(structure)
  ```

- `SpectrumPlotter` | `VoltageProfilePlotter` | `PhononDosPlotter` | `PDPlotter` | ... : All the `XyzPlotter` classes are perhaps the most clear-cut case. Does plotting ever require persistent state? If there's no need for state, why use classes, a tool built for binding functionality to state? For stuff like `Compositions` and `Structures`, this makes perfect sense. It allows implementing comparison operators (`if struct1 == struct2`) and methods for neatly manipulating the internal state without having to pass it around. I see the appeal of classes there. But with plots, you have some finished state and now you want to see it. There's no use case for checking that 2 `PDPlotter` instances will give the same plot. Instead using classes here results in the IMO slightly awkward `get_plot()` API:

```py
from pymatgen.analysis.phase_diagram import PhaseDiagram, PDPlotter

pd = PhaseDiagram(processed_entries)
plotter = PDPlotter(pd)
fig = plotter.get_plot()
```

Wanting the plot is a given, no? A function that returns the plot always without having to ask for it would make more sense:

```py
from pymatgen.analysis.phase_diagram import PhaseDiagram, plot_pd

pd = PhaseDiagram(processed_entries)
fig = plot_pd(pd)
```

I was going to give more examples but realize now this is turning into an essay. So I'll stop here.

Happy to discuss more in comments if any changes in this direction aren't out of the question.

**Comment by shyuep** [comment]
While I agree some stateless stuff can be non-objects (e.g., pymatgen.util are mostly methods based), I should outline the basic principles. OOP can be used as either a state tool or an organizational tool. MPRester actually does have states - the session, API key and the url. Similarly, spacegroup analyzer wraps around spglib to get the spacegroup data only once. Can we rewrite such that they are all method-based? Sure. That would require every single method to replace the API key, the url and multiple calls to spglib to get back the same info for processing, even if you are doing a single structure. 

Even for the plotters, many have rather sophisticated analyses bundled into the plotting that are valuable in and of itself. There can be multiple ways of plotting the same information (e.g., PDPlotter.get_element_profile). It also enables options like plotting figures on top of each other in certain ways (e.g., DOSPlotter). Again, you can always argue we can write a plot_X method to just plot a figure in one way and add arguments or alternative methods to get a different plot. But my view is that it is more messy than the current approach.

I am open to hearing other opinions from others and where we can streamline things.

**Comment by janosh** [comment]
@shyuep Thanks for taking the time to reply! Good points!

To clarify what I'm suggesting: For `SpacegroupAnalyzer`, I was thinking of a function like

```py
analyze_spg(
  struct: Structure,
  sym_data: list[str] = None
)
```

which by default returns the full dict received from `spglib.get_symmetry_dataset(struct, symprec)` (plus potential further analysis results from pmg itself if they're cheap and often used) to avoid the need for repeated `spglib` calls. If user knows they only want a subset of keys, they pass `sym_data = ['international', 'number', 'crystal_sys', ...]`. Similar to the 2nd arg of `MPRester.query()` where you pick all the stuff you need.

> That would require every single method to replicate the API key, the url and multiple calls to spglib to get back the same info for processing, even if you are doing a single structure.

True, splitting `MPRester` into separate functions requires each function to accept an API key. Though internally, that could be handled by a decorator so you only need to implement it once (some people object to decorators changing function signature. I'm not saying this approach is without downsides). On the user-side this problem is already solved. The API key is read from `.pmgrc.yaml` if not passed explicitly, so you wouldn't have to pass it to every function.

Regarding the plots I have to admit I haven't used them to the point where I've tried to combine them or looked at any intermediate data analysis they do. So I'm talking at a very high level here. But if plotting classes can/are also used for data analysis, that sounds like insufficient separation of concerns. For the most part, I think plotting code should solely be responsible for visualizing data. Analyzing or bringing that data into the right shape should be handled by other functions, which like you said can be useful on their own.

Let me repeat, this issue is not super actionable and I was never expecting any immediate changes from it. Just wanted to voice this opinion so that perhaps it gets taken into consideration in future development.

**Comment by shyuep** [comment]
I personally think having decorators change function signatures is a very bad practice. Most people have a hard time knowing how to call something. If they have to hunt down the decorator implementation to figure it out, it is much worse.

**Comment by sgbaird** [comment]
> I am open to hearing other opinions from others and where we can streamline things.

Drive-by comment. For generative modeling I'll probably be running tens of thousands of structures (if not many more) through `SpaceGroupAnalyzer(pmg_struct).get_refined_structure()` or similar. Not sure if the overhead of class instantiation for each structure vs. a function as mentioned by @janosh is enough overhead to be noticeable, especially compared to the cost of sampling structures from a pretrained generative model (can vary by orders of magnitude depending on the choice of model).

**Comment by shyuep** [comment]
@janosh I will close this as it is not an "Issue" per se. Feel free to post a similar thing in Github Discussion. I will outline my general philosophy:
1. Stateless, unique functionality - methods
2. Things which look like objects (e.g., Structure) - OOP
3. Things which have state - OOP preferred.

As a compromise, I think we can make some of the more commonly used stuff into methods within the common objects. For example, Structure.get_space_group_info() or the Structure.to(...). We can easily add a Structure.refine(). The bigger question is how many times do people really use the method and whether it is worth adding it to a long list of Structure.X methods. For things like Structure.to, I think it is quite clear there is major usage and value. This obviates the need to call specific IO packages.  But this is not always the case.
