### ISSUE TITLE
pymatgen version: 2022.3.24 -- TransformedStructure.structures didn't work!!!

### ISSUE THREAD

**Issue by JohnnyG-uo** [materialsproject/pymatgen#2479]
**Describe the bug**
I made some transformations on a structure, output **final_structure** and **structures**. But I found these two properties are the same. It means **structures** property didn't work. And I view its source code. I found it's due to the **input_structure** key within **hdict** is removed by no reason.

**Show the phenomenon**
When you debug and stop on the 155th line, you can see the **hdict**, and the **input_structure** still exists.
![image](https://user-images.githubusercontent.com/58620704/160753485-511ccf06-fb1d-4cbd-a38a-67927cb570e2.png)
However, when you stop on the 156th line, the **input_structure** is gone. I don't know why.
![image](https://user-images.githubusercontent.com/58620704/160753682-442bf45d-adc7-43da-8496-19f8d6e5a0fb.png)

**To Reproduce**
you can try my example code, and pymatgen version is 2022.3.24 on Ubuntu.
`
from pymatgen.alchemy.transmuters import CifTransmuter
from pymatgen.transformations.standard_transformations import SubstitutionTransformation, RemoveSpeciesTransformation
trans = []
trans.append(SubstitutionTransformation({"Fe":"Mn"}))
trans.append(RemoveSpeciesTransformation(["Li"]))
transmuter = CifTransmuter.from_filenames(["test_files/LiFePO4.cif"], trans)
structures = transmuter.transformed_structures
`

**Expected behavior**
In my example, I want my **structures[0].structures**  contains each structures in history, not only the last transformed structure.

**Comment by shyuep** [comment]
Pls provide an actual series of code that I can use to reproduce the error.

**Comment by JohnnyG-uo** [comment]
**To Reproduce**
from pymatgen.alchemy.transmuters import CifTransmuter
from pymatgen.transformations.standard_transformations import SubstitutionTransformation, RemoveSpeciesTransformation
trans = []
trans.append(SubstitutionTransformation({"Fe":"Mn"}))
trans.append(RemoveSpeciesTransformation(["Li"]))
transmuter = CifTransmuter.from_filenames(["test_files/LiFePO4.cif"], trans)
structures = transmuter.transformed_structures

**Comment by JohnnyG-uo** [comment]
Have you solve this problem?

**Comment by shyuep** [comment]
The history of structures is in the history attribute. After your last line, add print(structures[0].history) and you will see both structures. The structures do not contain intermediate structures.
