### ISSUE TITLE
Vasprun fails to read in ML-based MD results

### ISSUE THREAD

**Issue by pjf295** [materialsproject/pymatgen#2480]
**Describe the bug**
Vasp 6.3.0 includes the ability to use machine learning (ML) to generate force fields (FF) based upon ab-initio results. Ths results is a large speed up in calculation speeds. The ML process mixes both ab-initio MD with ML FF results based upon a Bayesian approach. This results in the vasprun.xml file containing both ab-initio results and ML based results. The ML based XML results include positions, forces, and velocities, but ab-initio energies. The Vasprun class init reads in a vasprun.xml file generated with ML FF without error, but it ignores all of the ML results and only includes the (typically widely temporally spaced) ab-initio results.
[vasprun.xml.gz](https://github.com/materialsproject/pymatgen/files/8380576/vasprun.xml.gz)
[XDATCAR.gz](https://github.com/materialsproject/pymatgen/files/8380577/XDATCAR.gz)

**To Reproduce**
See the attached INCAR.txt file for the relevant input cards. Machine learning must be turned on to reproduce the results

Provide any example files that are needed to reproduce the error,
especially if the bug pertains to parsing of a file.

I have also attached gzipp'd versions of XDATCAR and vasprun.xml for a demonstration run with 100 integration steps. The XDATCAR contains 100 different structures for each of the MD steps. The vasprun.xml file also contains all 100 steps, but reading in the vasprun.xml file using the Vasprun init (run = Vasprun('vasprun.xml') leads to a vasprun object only containing a small fraction of the ionic steps in the MD simulation (e.g. only those in which ab-initio steps were performed) leaving out all of the FF results.

**Expected behavior**

The vasprun object should contain the ionic steps for all MD steps. Perhaps another flag should be set to indicate that the results were generated using ab-initio or ML FF processes.

**Desktop (please complete the following information):**
Pymatgen version 2022.3.7
Behavior host independent (Mac and Linux have the same symptoms)

**Comment by pjf295** [comment]
Dear Matthew,

  It is nice to hear from you. I have often read your comments on the discourse pymatgen server.   The machine-learned force field functionality in Vasp offers a significant (tens of times) speed up for MD calculations. While I have not verified it at this point, it would also appear that the scaling with system size is very favorable as well (for purely machine learned systems). As you may know, the typical option for the ML FF is to run in ML_ISTART = 1 mode.  In this scenario, a machine learning potential is used, but based upon a Bayesian approach for monitoring systematic error, the system performs occasional ab-initio calculations and update its ML FF. This means that such simulations have intermixed ab-initio and ML FF MD data. For many use cases, it is useful to carry out autocorrelation-based Green-Kubo analysis of steady state trends for tasks such as doing diffusion analysis or as I am have been exploring recently predicting friction values (by monitoring of the force data using Green-Kubo formalism). The only realistic way to handle this is to have the data as one integral object. This would also be the case for example of large systems that are undergoing crystallization. To this end, I would suggest the addition of new Boolean dictionary elements for the ionic_steps object such as is_abinitio and is_MLFF. This way one could distinguish if necessary between the two, but existing classes (such as DiffusionAnalyzer) would not experience indigestion or have to be rewritten to handle the new information. Note that some of the energy terms will be missing in a ML FF approach (an unfortunate side effect of ML). On the other hand, the scaling improvements will hopefully allow the study of nucleation and crystallization behavior which often require long simulation times and/or large system sizes.

 I am very much an amateur at Python, but I have enjoyed a large improvement in productivity in using Pymatgen and am very grateful for your (and other team member) efforts in improving Pymatgen and its associated tools. I worked for over 25 years as a senior research at a large national laboratory (AIST) in Japan and recently moved to university (Keio). I have found that the use of pymatgen and associated tools such as matminer is an expedient approach to introducing students into world of simulations. Keep up the good work. I would be happy to comment more on the ML topic, but I suspect that you are more proficient at Python and I am looking at the situation from the viewpoint of workflows.

Best wishes,
                     Paul Fons



Paul Fons
***@***.***

Professor
Keio University, Faculty of Science and Technology, Department of Electronics and Electrical Engineering

〒223-8522 3-14-1 Hiyoshi, Kohoku-ku, Yokohama, Kanagawa 223-8522, Japan
Keio University Faculty of Science and Technology Yagami Campus.

〒223-8522　横浜市港北区日吉3-14-1 慶應義塾大学理工学部電気情報工学科 23-315

**Comment by thienbinh92** [comment]
XDATCAR format does not change for vasp5.4 and vasp6.3. Can pymatgen analyze MD results from XDATCAR?

**Comment by pjf295** [comment]
While it is true that the XDATCAR format is unchanged, there is much more information in the vasprun file including velocities and forces. I would like to use the force information in particular.

**Comment by pjf295** [comment]
I realize that this change is probably not a high priority item, but I was curious if there was a rough timeline of when support for the new machine learning tags will be added.

**Comment by shyuep** [comment]
I have finished implementing an initial version of Vasprun parsing of ML-MD runs. It is now in master.

**Comment by foster362** [comment]
How do you pass md_data into DiffusionAnalyzer.from_files
e.g.
analyzer = DiffusionAnalyzer.from_files(["vasprun.xml"], specie="Li", smoothed=False)

**Comment by shyuep** [comment]
There is a DiffusionAnalyzer.from_structures. The md_data key contains all the structures. I have no idea what the timestep of the calculations are since I don't use this feature of VASP at all.

**Comment by foster362** [comment]
Ok thanks. So from_structures is updated but not from_ files. The time step is no different than a typical vasp md calculation (still based on POTIM); however, one might use NBLOCK to reduce output but this is not a new feature.

**Comment by foster362** [comment]
I'm still having trouble getting this to work.

This reads vasprun.xml but I can't seem to excess the md_data:
analyzer = DiffusionAnalyzer.from_files(["vasprun.xml"], specie="Li", smoothed=False)

If I do the following:
analyzer = DiffusionAnalyzer.from_structures(["vasprun.xml"], specie="Li", temperature=700.0, time_step=1, step_skip=1, smoothed=False)

I get 
```
    590     if i == 0:
    591         structure = s
--> 592     p.append(np.array(s.frac_coords)[:, None])
    593     l.append(s.lattice.matrix)
    594 if initial_structure is not None:

AttributeError: 'str' object has no attribute 'frac_coords'
```

**Comment by shyuep** [comment]
Sorry, but you need to read the method signatures and documentation carefully. AS the method name implies, DiffusionAnalyzer.from_structures takes in a list of structures, not a list of vasprun.xml files. I will provide a basic example here but ultimately, you have to be the one reading the documentation and figuring this out.

```python
v = Vasprun("vasprun.xml")
structures = [d["structure"] for d in v.md_data]
analyzer = DiffusionAnalyzer.from_structures(structures, ....)
```

**Comment by foster362** [comment]
Thanks, I’m not great with python but I’m trying and not just asking.

**Comment by thienbinh92** [comment]
Dear Prof. @shyuep , I ran with `ML_ISTART = 2`, no calculation was exported, but the predicted structures and velocities in the vasprun.xml file. The following error appears for my case:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/var/folders/13/76vrjtyn2kgckfh7v76ndv900000gn/T/ipykernel_6381/266408610.py in <module>
      2 #          "tem-800/out_vasprun.xml_3", "tem-800/out_vasprun.xml_4",
      3 file800 = ["tem-800/out_vasprun.xml_5"]
----> 4 analyzer800 = DiffusionAnalyzer.from_files(file800, specie="Li", smoothed=False)
      5 #analyzer3 = DiffusionAnalyzer.from_files(file3, specie="Li", smoothed="max")
      6 plt800 = analyzer800.get_msd_plot()

~/miniconda3/lib/python3.8/site-packages/pymatgen/analysis/diffusion_analyzer.py in from_files(cls, filepaths, specie, step_skip, ncores, initial_disp, initial_structure, **kwargs)
    742                 offset = (-(v.nionic_steps - offset)) % step_skip
    743 
--> 744         return cls.from_vaspruns(
    745             vr(filepaths), specie=specie, initial_disp=initial_disp, initial_structure=initial_structure, **kwargs
    746         )

~/miniconda3/lib/python3.8/site-packages/pymatgen/analysis/diffusion_analyzer.py in from_vaspruns(cls, vaspruns, specie, initial_disp, initial_structure, **kwargs)
    672 
    673         s = get_structures(vaspruns)
--> 674         step_skip, temperature, time_step = next(s)
    675 
    676         return cls.from_structures(

~/miniconda3/lib/python3.8/site-packages/pymatgen/analysis/diffusion_analyzer.py in get_structures(vaspruns)
    654 
    655         def get_structures(vaspruns):
--> 656             for i, vr in enumerate(vaspruns):
    657                 if i == 0:
    658                     step_skip = vr.ionic_step_skip or 1

~/miniconda3/lib/python3.8/site-packages/pymatgen/analysis/diffusion_analyzer.py in vr(filepaths)
    737             offset = 0
    738             for p in filepaths:
--> 739                 v = Vasprun(p, ionic_step_offset=offset, ionic_step_skip=step_skip)
    740                 yield v
    741                 # Recompute offset.

~/miniconda3/lib/python3.8/site-packages/pymatgen/io/vasp/outputs.py in __init__(self, filename, ionic_step_skip, ionic_step_offset, parse_dos, parse_eigen, parse_projected_eigen, parse_potcar_file, occu_tol, separate_spins, exception_on_bad_xml)
    357                 # add the tailing information in the last step from the run
    358                 to_parse = "<calculation>".join(new_steps)
--> 359                 if steps[-1] != new_steps[-1]:
    360                     to_parse = f"{preamble}<calculation>{to_parse}{steps[-1].split('</calculation>')[-1]}"
    361                 else:

IndexError: list index out of range
```

**Comment by pjf295** [comment]
Thank you for your note. I probably didn’t explain myself well. I realize that the XDATCAR file is available, however, I need force data which is in the vasprun.xml file. Unfortunately, the Vasprun class does not read molecular dynamics data generated using machine learning at all. For example, a 40,000 step MD simulation generated using ML, none of the ML force-field data is read in. I have parsed the velocity and force data directly from the Vasprun file using awk and related tools, but it is in the interests of the pymatgen project to be able to read in such data directly. The speed-ups associated with ML are very large and will enable carrying out simulations for much longer times and potentially larger system sizes so it is important to support such features.


Paul Fons
***@***.***

**Comment by shyuep** [comment]
@pjf295 I understand this is a new feature of VASP and there are some pymatgen users who might need it. But you must understand that pymatgen is an open source project contributed by volunteers, not a commercial software with paid software engineers. The way new features happen is if a volunteer happens to need a new function and they add support for that feature and submit a PR. Neither myself nor any other user has stepped up to rigorously implement MLFF support because none of us actually need it at the moment.

If you want to implement it properly and submit a PR, we will be happy to review it.
