### ISSUE TITLE
Can't import pymatgen.core "No module named 'pymatgen.core'"

### ISSUE THREAD

**Issue by private-observer** [materialsproject/pymatgen#2502]
I've used pip install pymatgen with Python 3.9.1 on Windows 10 to install pymatgen, but I'm getting the following error:

    Traceback (most recent call last):
      File "D:\code\pymatgen\pymatgen.py", line 1, in <module>
    import pymatgen.core as mg
      File "D:\code\pymatgen\pymatgen.py", line 1, in <module>
        import pymatgen.core as mg
    ModuleNotFoundError: No module named 'pymatgen.core'; 'pymatgen' is not a package

I have also tried to install the previous 2 versions but still getting the same error though I can already see it in the pip list

pymatgen                          2022.3.22

i am not using a virtual environment and i dont want to install conda its too big

What am I missing?

**Comment by shyuep** [comment]
I have no idea what pymatgen.py is. I suspect it is because you named your script pymatgen and by default, python uses the package in the current directory. Rename the code to some other name.

**Comment by private-observer** [comment]
of course! thanks.
