### ISSUE TITLE
Packmol IO: Address which deprecation

### ISSUE THREAD

**Issue by rkingsbury** [materialsproject/pymatgen#2511]
The `run` method of Packmol IO makes use of `monty.io.which` to detect whether packmol is installed, and this method will be deprecated soon. This should be changed to `shutil.which` from the standard library, or (perhaps a better solution), use the `monty.dev.requires` decorator as shown [here](https://github.com/materialsproject/pymatgen/blob/95352c96d7aba865d01230d5c32a5a6704c0edba/pymatgen/io/babel.py#L39).

```
/Users/ryan/miniconda3/envs/md/code/pymatgen/pymatgen/io/packmol.py:54: 
FutureWarning: which is deprecated; use which in shutil instead.
shutil.which has been available since Python 3.3. This will be removed in v2023.
  if not which("packmol"):
```

**Comment by shyuep** [comment]
Go ahead and submit a PR to change this.
