### ISSUE TITLE
how to convert many cif file to poscar format in vasp?

### ISSUE THREAD

**Issue by Amadeus-System** [materialsproject/pymatgen#2513]
Hi. I am a researcher in computational physics and I have been using pymatgen very well.

Recently, I have obtained hundreds (or even thousands of) of CIF files and I need to convert all CIF files to POSCAR format in vasp.
I already know how to convert single cif file to poscar format using VESTA, but I would like to know more convenient ways to process many cif files.

When I access to pymatgen homepage, example codes just show how to read information in poscar file and save it to cif format. 
Do you know another ways that save structure information to poscar format in vasp?
I expect your kind explanation. Thank you!

**Comment by Amadeus-System** [comment]
Sorry, I found useful way in pymatgen tutorial. Thank you very much!

**Comment by JaGeo** [comment]
You might also have a look here: https://matsci.org/c/pymatgen/9

This is the discussion forum and the place where you can ask about the usage of pymatgen 🙂.
