### ISSUE TITLE
How to parse a complete dos object from DOSCAR but not from vasprun.xml by pymatgen

### ISSUE THREAD

**Issue by wulijixxx** [materialsproject/pymatgen#2530]
Hello dear,
I have some trouble when I parse a DOS object with vasprun.xml obtained from GW calculation. The error is as follows:
“NotImplementedError: This vasprun.xml has >2 unlabelled dielectric functions”
So I want to parse it by using DOSCAR instead of the vasprun.xml. But I have not found a class that can do this in pymatgen. If anyone can help me write a new class or some advice in pymatgen, I will be super grateful to you. Thanks.

My goal is to calculate fermi levels at the given temperatures with defect formation energies, so I need to parse the total DOS via the electronic structure calculations obtained from VASP GW calculations to estimate band edges accurately. If anyone can help me to add some functionalities of parsing DOS for GW calculations either using vasprun.xml or DOSCAR obtained from GW calculations, I will be very grateful.

**Comment by shyuep** [comment]
There is only a class to parse the Doscar from LOBSTER calculations. I am not sure why there is a need to do it from the DOSCAR since the vasprun.xml contains the same information as far as I can tell. To my knowledge, parsing the GW DOS from vasprun.xml should be the same as that from regular PBE. You should make some attempt to do this yourself and if it doesn't work, then you report an Issue.

**Comment by wulijixxx** [comment]
Thanks very much for your reply. I have tried to use LOBSTER to parse the DOS but it still failed because LOBSTER can not succeed on the results of GW electronic calculations. I am sure my GW calculations were conducted correctly. My problem is just that pymatgen can not parse the vasprun.xml from GW. So I hope someone can write a certain class for GW calculations to parse DOS files either by using vasprun.xml or DOSCAR. Thanks.

**Comment by wulijixxx** [comment]
Thank you so much dear shyuep. I will send you my GW vasprun.xml and PBE vasprun.xml right now by email.

**Comment by wulijixxx** [comment]
> You will have to provide a GW vasprun.xml and show how it fails.

Hi, I found I couldn't send you my vasprun.xml files by this dialog. Thus I have sent them to your email address: notifications@github.com. Thank you.

**Comment by wulijixxx** [comment]
Okay, thank you so much. I will send the files tomorrow.

发自我的iPhone
