### ISSUE TITLE
`Composition.replace` incorrect with complex mappings

### ISSUE THREAD

**Issue by jacksund** [materialsproject/pymatgen#2553]
**Describe the bug**
If an element is present in multiple places of the `elem_map`, the `Composition.replace` will return an incorrect result.

**To Reproduce**

``` python
from pymatgen.core import Composition

c = Composition("Ca2NF")

example_sub_1 = {"Ca": "Sr", "N": "O", "F": "O"}
c_new_1 = c.replace(example_sub_1)
assert c_new_1 == Composition("Sr2O2")  # FAILS -- instead c_new_1 is Sr2O1

example_sub_2 = {"Ca": "Sr", "N": "F", "F": "Cl"}
c_new_2 = c.replace(example_sub_2)
assert c_new_2 == Composition("Sr2ClF")  # FAILS -- instead c_new_2 is Sr2Cl

example_sub_3 = {"Ca": "Sr", "N": "F", "F": "N"}  # swaps F and N sites
c_new_3 = c.replace(example_sub_3)
assert c_new_3 == Composition("Sr2NF")  # FAILS -- instead c_new_3 is Sr2N
```

**Expected behavior**

``` python
import warnings
from pymatgen.core import Composition

def replace_new(comp, elem_map):
    """ This is an updated version of the replace method, and I'll open a PR with this update """

    # drop inapplicable substitutions
    invalid_elems = [key for key in elem_map if key not in comp]
    if invalid_elems:
        warnings.warn(
            "Some elements to be substituted are not present in composition. Please check your input. "
            f"Problematic element = {invalid_elems}; {comp}"
        )
    for elem in invalid_elems:
        elem_map.pop(elem)

    # start with elements not in elem_map and remain unchanged
    new_comp = {
        elem: amount for elem, amount in comp.as_dict().items() if elem not in elem_map
    }

    for old_elem, new_elem in elem_map.items():

        amount = comp[old_elem]

        subs = {}
        if isinstance(new_elem, dict):
            for el, factor in new_elem.items():
                subs[el] = factor * amount
        else:
            subs = {new_elem: amount}

        for el, amt in subs.items():
            if el in new_comp:
                new_comp[el] += amt
            else:
                new_comp[el] = amt

    return Composition(new_comp)


c = Composition("Ca2NF")

example_sub_1 = {"Ca": "Sr", "N": "O", "F": "O"}
c_new_1 = replace_new(c, example_sub_1)
assert c_new_1 == Composition("Sr2O2")

example_sub_2 = {"Ca": "Sr", "N": "F", "F": "Cl"}
c_new_2 = replace_new(c, example_sub_2)
assert c_new_2 == Composition("Sr2ClF")

example_sub_3 = {"Ca": "Sr", "N": "F", "F": "N"}
c_new_3 = replace_new(c, example_sub_3)
assert c_new_3 == Composition("Sr2NF")

# Confirming old functionality
assert replace_new(
    Composition("Fe2O3"), {"Fe": {"Mg": 0.5, "Cu": 0.5}}
) == Composition("MgCuO3")
```

**Comment by jacksund** [comment]
fyi -- I don't have a dev env for pymatgen set up at the moment, and it's late here -- so I'll open the PR and add unittests for this tomorrow.

**Comment by shyuep** [comment]
I think there are two issues - one which I think I can fix, but the other one is a logic problem. 
The problem with a substitution like `{"Ca": "Sr", "N": "F", "F": "Cl"}` is that it is fundamentally uninterpretable. A dict is unordered. How does the code know whether the user intend to substitute F with Cl first, followed by N with F (giving Sr2FCl) or substitute N with F followed by F with Cl (giving Sr2Cl2)? There is no reason to choose one interpretation over another.

A substitution like  `{"Ca": "Sr", "N": "O", "F": "O"}` should indeed be allowed. I will do the fix for this case.

**Comment by shyuep** [comment]
We do allow substitutions where the key is not present in the original composition (because sometimes you want to mass process compositions). The code will just throw a warning.

**Comment by jacksund** [comment]
okay, gotcha.

I was also making a PR while you made your comment -- sorry about the overlap. If you prefer to close my PR in favor of your changes, go ahead 😄

**Comment by shyuep** [comment]
No problem. Please double check that the code I pushed works in all cases. The uninterpretable case should now throw a valueError.

**Comment by jacksund** [comment]
Looks like it works as intended! Thanks. 

Also, I still think it's interpretable to have an element in both keys and values -- substitutions from the `Substitutor` class even request this sometimes (that's how I stumbled onto this bug). But I'll write a workaround for this in my code.

**Comment by shyuep** [comment]
@jacksund Anyway, I changed the code to allow it but throw a warning. This should now work.

**Comment by shyuep** [comment]
I would argue that it is ambiguous though.... :-)

**Comment by jacksund** [comment]
Thank you, and sorry about the disagreement :sweat_smile:. I really appreciate you adding the fix! It makes things a lot easier on my end.

**Comment by jacksund** [comment]
@shyuep sorry to reopen this issue, but it looks like the revised version added a new bug. `replace` can't handle oxidation states anymore. It tries to call something like `Composition("Ca2+")` which fails. This breaks some functionality in the `Substitutor` class which inputs to be oxidation-state decorated. Here's an example of the bug...

``` python
from pymatgen.core import Composition
elem_map = {'Ca2+': 'Mg2+', 'N3-': 'O2-', 'F-': 'O2-'}
c = Composition("Ca2NF").add_charges_from_oxi_state_guesses()
c.replace(elem_map)
```

I've reopened my pull request #2555 to fix this and added a unittest. It's more lines of code than your solution, but hopefully that's alright. Time testing shows that both are about the same speed:
``` python
# from PR 2555
62.7 µs ± 147 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

# from commit c676b6f (currently in main)
66.1 µs ± 112 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Comment by shyuep** [comment]
No problem. Thanks for fixing.
