### ISSUE TITLE
Bandstructure __init__ variable type error

### ISSUE THREAD

**Issue by thiassaith** [materialsproject/pymatgen#257]
In line 704 and 705 of pymatgen/electronic_structure/bandstructure.py, the lines:
704                                   "name": (self._kpoints[b[0]].label + "-" +
705                                            self._kpoints[b[-1]].label)})
throw a variable compatibility error:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'unicode'

I believe the obvious fix is to update the 'NoneType' variables to strings:
704                                   "name": (str(self._kpoints[b[0]].label) + "-" +
705                                            str(self._kpoints[b[-1]].label))})

This fixes the error. However, I am not sure if something deeper needs to be changes so that these variables are 'unicode' and note 'NoneType' from the beginning.

**Comment by shyuep** [comment]
Thanks for reporting this.
