### ISSUE TITLE
Scaling of velocities in Poscar file

### ISSUE THREAD

**Issue by gVallverdu** [materialsproject/pymatgen#2583]
Hi 

I have a question about the sampling of velocities on this line. It corresponds to the `set_temperature()` method in the Poscar class.
https://github.com/materialsproject/pymatgen/blob/23421524e1ac567358144b74825be14b2b1a7af6/pymatgen/io/vasp/inputs.py#L597

I wonder why, the velocities are scaled before the center of mass velocity is removed ? To precise, I would invert line 597 and line 600. It does not change a lot the results but I think if the velocities are scaled before computing the center of mass velocities, the quantity which is subtracted is not exactly the center of mass velocity.

**Comment by shyuep** [comment]
Thanks. I agree and I have made the change.
