### ISSUE TITLE
`IStructure.__eq__` fails for integers

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#2587]
There are more edge cases like #2584 in `IStructure.__eq__`. E.g. comparing against `int`s also throws.

```py
from pymatgen.core import Lattice, Structure


coords = [[0.5, 0.5, 0.5], [0, 0, 0]]
species = ["Na", "Cl"]
lattice = Lattice.from_parameters(a=4, b=4, c=4, alpha=90, beta=90, gamma=90)
structure = Structure(lattice, species, coords)

structure == 42
```

```py
    def __eq__(self, other) -> bool:
        if other is self:
            return True
        if other is None:
            return False
>       if len(self) != len(other):
E       TypeError: object of type 'int' has no len()
```

I think a fix to handle all such edge cases would be to start with an `isinstance` check that returns `NotImplemented` if `other` is not a `(I)Structure`.

```py
def __eq__(self, other: object) -> bool:
    if not isinstance(other, IStructure):
        return NotImplemented
```

**Comment by shyuep** [comment]
I am confused. Isn't comparing Structure and a string/int/whatever that is not Structure-like supposed to fail?

**Comment by janosh** [comment]
Comparison across types is supposed to return false. E.g.

```py
'foo' == 5
>>> False
```

**Comment by shyuep** [comment]
Then the current PR implementation is not correct. I would actually do something like 

try:
   ...
except TypeError:
   return False

**Comment by janosh** [comment]
By returning `NotImplemented`, the equality check is handed over from `IStructure.__eq__()` to the other, i.e. `int.__eq__()` or `str.__eq__()`, where Python knows to return `False`.

**Comment by shyuep** [comment]
That is fine. But I would still do the try except rather than the instance check. There is no reason why we need to ban say a Structure == something very much structure like with all the features but not exactly a Structure. This is afterall the principle of ducktyping in python.

**Comment by janosh** [comment]
I was considering using `SiteCollection`.

```py
def __eq__(self, other: object) -> bool:
    if not isinstance(other, SiteCollection):
```

Happy to change to that if you think it's more appropriate. Beyond `SiteCollection`, I'm not sure what would qualify as being equal to structure. Bear in mind, we're not banning equality with other stuff here, we're just handing off to the other object's equality. If that other thing knows how to compare with structure, it can still return `True`.

**Comment by janosh** [comment]
Actually, since `SiteCollection`s don't have a lattice, using that would result in a new bug since we're making that assumption further down the function.

**Comment by janosh** [comment]
@shyuep Actually, looking at the [`functools.total_ordering` docs](https://docs.python.org/3/library/functools.html#functools.total_ordering), I think what we should really do is return `NotImplemented` if any of the attributes required for equality checking are missing. See this `class Student` example:

```py
@total_ordering
class Student:
    def _is_valid_operand(self, other):
        return (hasattr(other, "lastname") and
                hasattr(other, "firstname"))
    def __eq__(self, other):
        if not self._is_valid_operand(other):
            return NotImplemented
        # ...
```
