### ISSUE TITLE
Process for verifying a pull request is correct?

### ISSUE THREAD

**Issue by mm04926412** [materialsproject/pymatgen#2597]
Hello

As part of my research I created a unit cell transformation algorithm that I thought might be useful to others. I'm not used to working on collaberative open source projects like this. I'd like to ask if there is anywhere / anyone I should send my code to for the purposes of getting external confirmation my code does what I say it does. Any advice on this matter would be appreciated.

**Comment by shyuep** [comment]
Thanks for the contribution. You can simply create a pull request and we will provide feedback on it. The steps are in the pymatgen documentation under the "contributing" section.

**Comment by mm04926412** [comment]
Thanks, would that be under the master branch?

**Comment by shyuep** [comment]
Doesn't matter what branch. Whatever you prefer on your fork. The master branch at the origin is only accessible to only two people in any case. So whatever you do on your fork does not affect it unti we merge it.
