### ISSUE TITLE
Allow the user to set SpacegroupAnalyzer parameters when writing FEFF input files

### ISSUE THREAD

**Issue by x94carbone** [materialsproject/pymatgen#2599]
**Is your feature request related to a problem? Please describe.**

Currently when writing FEFF input files, if [SpacegroupAnalyzer](https://github.com/materialsproject/pymatgen/blob/baf62b77788fc43387e15b1e0b60094132815c47/pymatgen/io/feff/inputs.py#L177) fails at any point, it prevents the user from writing anything. I've encountered a few cases where relaxing `symprec` slightly allows everything proceed. It would be great to have a few extra arguments added to the [FEFFDictSet](https://github.com/materialsproject/pymatgen/blob/738b52a17426eff3b8fb5c4dcf8c8e363284794b/pymatgen/io/feff/sets.py#L120) (which then propagate through to the other FEFF objects) which would let the user set these parameters.

**Describe the solution you'd like**

Described above. I'm happy to do it in a PR.

**Describe alternatives you've considered**

This seems like a straightforward request without another reasonable alternative. The user should be able to control the keywords to `SpacegroupAnalyzer` when writing FEFF input files.

**Additional context**

None.

**Comment by shyuep** [comment]
Since it is a relatively quick fix, I have implemented it. Pls see latest commits.

**Comment by x94carbone** [comment]
@shyuep Perfect thank you. Quick followup question: are you open to using the FEFF writers to handle amorphous materials and clusters (i.e. very low symmetry systems)? I think that would be quite useful for people (though perhaps out of scope). Curious to know what you think.

**Comment by shyuep** [comment]
Yes, that would be great. I personally think the tools themselves (FEFF input generation etc.) should be general to any structure and treat crystalline structures as a special case. I think all that is needed is an option to turn off symmetry checking completely.

**Comment by x94carbone** [comment]
@shyuep I'm happy to take a shot at this if you'd like. Give me the green light and I'll open an issue (which you can assign me to if possible). I can then work on this a bit and open a PR down the road.
