### ISSUE TITLE
Lattice.find_all_mappings test fails with latest numpy.

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#261]
Pls investigate. Error message below:

AssertionError: 
Arrays are not almost equal to 5 decimals

(mismatch 100.0%)
 x: array([[ 0.54756, -0.03654, -0.14159],
       [ 0.06854, -0.38895, -0.89413],
       [-1.78544, -0.24974, -0.0563 ]])
 y: array([[ 0.2, -0.4, -1.4],
       [ 0. , -0.4, -1. ],
       [-0.6, -0.9, -0.2]])

only seems to be a problem with latest numpy.

**Comment by wmdrichards** [comment]
The new numpy version has a very bad bug with non contiguous data in np.inner calls:
https://github.com/numpy/numpy/issues/6532

**Comment by charris** [comment]
@shyuep Could you try with the 1.10.2rc1 release?

**Comment by wmdrichards** [comment]
numpy 1.10.2rc1 seems to have fixed it

**Comment by shyuep** [comment]
Yes, I confirm that too. Thanks !
