### ISSUE TITLE
Cannot understand Vasprun parser error in reading a vasprun.xml file - please advise 

### ISSUE THREAD

**Issue by joshgabriel** [materialsproject/pymatgen#265]
I get the error: 

ParseError: mismatched tag: line 773, column 4

when using the Vasprun parser in pymatgen.io.vasp.outputs on a perfectly written out and converged vasprun.xml .. Any reason for this ? 

The OUTCAR file yields a perfectly converged energy. 

The line flagged in the vasprun.xml is one of the closing lines of an ionic step appears to have a misprinted angle bracket. The issue seems to be a random occurrence at random points in a high throughput run through different structures .. Can the parser somehow ignore the misprint mismatch in the vasprun.xml and recover the still useful information, for example the calculation is converged ?

**Comment by shyuep** [comment]
We use the python ElementTree XML parser for vasprun. While I think there is a way to change the error handling, it is generally not a good idea to ignore errors in XML. There is no way to ensure that the parsing gives reasonable results. 

I would say that if you know that there is a misprint, you can preprocess the XML file itself to fix those misprint and try parsing again.

But you should really check your VASP compilation. Such errors are usually the result of a bad compile, which is not good in a first principles code.
