### ISSUE TITLE
Old API key raises unknown format error

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#2652]
```py
from pymatgen.ext.matproj import MPRester

elemental_reference_energies = MPRester().query(
    {"nelements": 1}, ["material_id", "pretty_formula", "energy_per_atom"]
)
```
raises

```py
ValueError: API key ****************** is in an unknown format. Please check your API key at https://materialsproject.org/api
```

My key has length 17 and hence doesn't trigger either of these cases

https://github.com/materialsproject/pymatgen/blob/8670716641bd643545874aca972d79afd654e711/pymatgen/ext/matproj.py#L1779-L1786

Maybe we should change to this @munrojm?

```py
elif len(api_key) in (16, 17):
```

**Comment by shyuep** [comment]
I would just change it to else rather than elif.
