### ISSUE TITLE
A question about BSplotter()

### ISSUE THREAD

**Issue by 91bsjun** [materialsproject/pymatgen#266]
Hi, I have a new question.

I want to know one of the operation in the bs_plot_data() 

(In the class of BSplotter() )

why do this operation when non metalic band structure ?

>>> zero_energy = self._bs.get_vbm()['energy']

--- script ---

        if self._bs.is_metal():
            zero_energy = self._bs.efermi
        else:
            zero_energy = self._bs.get_vbm()['energy']

---------------------
I want to know why adjust zero_energy to vbm.

**Comment by shyuep** [comment]
Hi,

Github issues is for reporting bugs and feature requests. For such questions, please keep it in the pymatgen Google groups.

**Comment by hautierg** [comment]
It is a common convention/practice in insulators and semiconductors to set the zero of energy at the VBM.

Geoffroy
