### ISSUE TITLE
use SlabGenerator.get_slab to generate a surface has a bug for ZnO(010)

### ISSUE THREAD

**Issue by wangnumber14** [materialsproject/pymatgen#267]
hello, I use SlabGenerator.get_slab to generate ZnO(010) surface, while I got more atoms and wrong POSCAR format。 why?
My code is following: 

ZnO=Structure.from_file("ZnO.cif",primitive=False)
Al55=SlabGenerator(ZnO,[0,1,0],5.3,5.0,lll_reduce=False,center_slab=False).get_slab()
IStructure.to(Al55,"poscar",filename="POSCAR")

Two layers I get, the POSCAR is:

Zn4 O4
1.0
-3.249300 0.000000 -0.000000
0.000000 0.000000 -5.205400
6.498600 -11.255905 -0.000000
Zn O Zn O
2 2 2 2
direct
0.666670 0.000000 0.083333 Zn
0.333330 0.500000 0.166667 Zn
0.666670 0.617400 0.083333 O
0.333330 0.117400 0.166667 O
0.666670 0.000000 0.333333 Zn
0.333330 0.500000 0.416667 Zn
0.666670 0.617400 0.333333 O
0.333330 0.117400 0.416667 O

The format is wrong for POSCAR, why ?

In additions, I want to know the two arguments: "min_slab_size", "min_vacuum_size", min_vacuum_size means the vacuum I wanted to use between layers?or sums of the vacuum sizes in all the layers, I think the latter is right. While the min_slab_size, I really do not understand your mean? Can you tell me ?  Thanks a lot!

**Comment by wangnumber14** [comment]
Although I use get_sorted_structure() and get the right POSCAR format, I still want to know the reason.

**Comment by shyuep** [comment]
Hi,

Pls post your technical questions to the pymatgen Google groups. Github issues are for reporting bugs and problems.

As for your specific problem, the structures returned by get_slab() is not sorted. The format for the POSCAR is not wrong at all. In fact, that POSCAR can run perfectly if you do the POTCAR right.

But if you want to make sure the POSCAR is sorted properly, do

Al55.get_sorted_structure().to(….)


Shyue Ping

On November 11, 2015 at 6:45:33 PM, wangnumber14 (notifications@github.com) wrote:

hello, I use SlabGenerator.get_slab to generate ZnO(010) surface, while I got more atoms and wrong POSCAR format。 why?
My code is following:

ZnO=Structure.from_file("ZnO.cif",primitive=False)
Al55=SlabGenerator(ZnO,[0,1,0],5.3,5.0,lll_reduce=False,center_slab=False).get_slab()
IStructure.to(Al55,"poscar",filename="POSCAR")

Two layers I get, the POSCAR is:

Zn4 O4
1.0
-3.249300 0.000000 -0.000000
0.000000 0.000000 -5.205400
6.498600 -11.255905 -0.000000
Zn O Zn O
2 2 2 2
direct
0.666670 0.000000 0.083333 Zn
0.333330 0.500000 0.166667 Zn
0.666670 0.617400 0.083333 O
0.333330 0.117400 0.166667 O
0.666670 0.000000 0.333333 Zn
0.333330 0.500000 0.416667 Zn
0.666670 0.617400 0.333333 O
0.333330 0.117400 0.416667 O

The format is wrong for POSCAR, why ?

In additions, I want to know the two arguments: "min_slab_size", "min_vacuum_size", min_vacuum_size means the vacuum I wanted to use between layers?or sums of the vacuum sizes in all the layers, I think the latter is right. While the min_slab_size, I really do not understand your mean? Can you tell me ? Thanks a lot!

**Comment by shyuep** [comment]
The reason why you need to use get_sorted_structure is because by default, the slab orders the atoms in terms of increasing c coordinate. This is useful when you want to know what are the atoms near the surface in order to do further manipulations, e.g., adding an adsorbate atom. 

The Poscar class does not assume whether your structure is sorted or not. This is because there are sometimes very good reasons to not sort the structure, eg. when you want to treat certain atoms differently even though they are the same structure.

If you want to avoid this, one way is to use one of the sets in pymatgen.io.vasp.sets to generate the entire set of input files.

**Comment by wangnumber14** [comment]
Thanks a lot. I want to known two arguments: "min_slab_size", "min_vacuum_size", min_vacuum_size means the vacuum I wanted to use between layers?or sums of the vacuum sizes in all the layers, I think the latter is right. While the min_slab_size, I really do not understand your mean? Can you tell me ? Thanks a lot!  (I can not attach the pymatgen Google groups), And another question is slab generation can not support that the surface go through one specified atom. I am not sure.

**Comment by shyuep** [comment]
As the doc says, it is simply the normal distance for the Slab and the vacuum respectively. The actual # of layers will be determined based on what you specify. To take a simple example, if you have a 3A cubic cell and you are generating a (100) slab. You set min_slab_size and min_vac_size to 4A. The code will determine that you need at least 2 layers to generate the structure. You will end up with a slab taht is 6A thick with a vacuum of 6A. Both slab and vacuum are defined in term of multiples of the oriented unit cell. 

SlabGenerator can generate all slabs with all distinct terminations via the get_all_slabs() method. One of them should have the atom you want at the surface.

**Comment by wangnumber14** [comment]
Thanks a lot, I do not know if I understand your mean. Your mean is that min_slab_size determines the layers(I thinks so), one question is one crystal has different lattice parameters, for example, a=2A, b=3A, c=4A, I want to generate (001) slab, I set min_slab_size=6A, the layers is at least 2 or 3? The layers is determined by the smallest values? I think it should be 2 layers, while use the crystal POSCAR as flows:
Li1
1.0
2.000000 0.000000 0.000000
0.000000 4.000000 0.000000
0.000000 0.000000 2.000000
Li
1
direct
0.500000 0.500000 0.500000 Li
I get the c from follows:
Li=Structure.from_file("POSCAR")
A5=SlabGenerator(Li,[0,1,1],7.0,2.0,lll_reduce=False,center_slab=False).get_slab()
a,b,c=A5.oriented_unit_cell.lattice.matrix
I get c=[ 0.  0. -2.] and nlayers=9,
while the slab POSCAR is:
Li4
1.0
-2.000000 0.000000 0.000000
0.000000 4.000000 -2.000000
0.000000 0.000000 -12.000000
Li
4
direct
0.500000 0.500000 0.000000 Li
0.500000 0.500000 0.166667 Li
0.500000 0.500000 0.333333 Li
0.500000 0.500000 0.500000 Li

Obviously, there are 4 layers, and why the c is not (0,0,-18)?
 Thanks a lot for your reply!

**Comment by shyuep** [comment]
It is based on normal distance. In your case, the c vector is not perpendicular to a and b. If you take the surface normal, you see why. Alternatively, set the max_normal_search.
