### ISSUE TITLE
SlabGenerator.get_slab can not make sure the specific atom on the surface?

### ISSUE THREAD

**Issue by wangnumber14** [materialsproject/pymatgen#269]
I want to use slabgenerator.get_slab to get (111)Fe.cif (2x2x2supercell) with one Cu dopant, and make sure that the Cu atom lies on the surface, or the atom sites the mesh origin(i.e., (0,0,0) site), how should I do? Whether Pymatgen.surface module supply this function? 
I try use shift to adjust the surface, but the result is not what I expected.  Thanks for your help!

**Comment by shyuep** [comment]
You can create the Slab first and then replace one of the surface atoms. The surface atoms is always the lowest or higher c fractional coordinate.

**Comment by wangnumber14** [comment]
Thanks for your advice, I want to dope first and then create the slab, Pymatgen now can not satify this? 
Thanks for your reply.

**Comment by shyuep** [comment]
Not quite sure what you are trying to achieve. But like I said in my previous replies, the get_all_slabs should return all distinct terminations, which should include one with Cu on the surface. If you want to use the get_slab method, the shift should work with some value and testing.

**Comment by wangnumber14** [comment]
My demand is that creating a slab from a doping structure, and the specific slab(e.g., 001) contains the specific doping atoms. 
My demand can be achieved by this method: first create a slab, and then dope some atoms on the surface;
while if I want to dope some atoms in the structure first, and then create a slab from the doping structure, and make sure the doped atoms exposed on the specific surface of the slab. (I mean that this demand can not be achieved)

**Comment by shyuep** [comment]
Try with get_all_slabs. If that can't be done, dope the surface.

**Comment by wangnumber14** [comment]
Thanks a lot !  I will think about other methods !
