### ISSUE TITLE
Add PMG_LEGACY_API_KEY to `.pmgrc.yaml`

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#2699]
Is the `PMG_MAPI_KEY` used in [GH action](https://github.com/materialsproject/pymatgen/settings/secrets/actions) one of length 32 for the new API?

I think that's the reason we're getting [this error in CI](https://github.com/materialsproject/pymatgen/actions/runs/3294713178/jobs/5432504709#step:5:97):

> pymatgen.ext.matproj.MPRestError: REST query returned with error status code 403. Content: b'{"valid_response": false, "error": "API_KEY is not a valid key.", "version": {"db": "2020_09_08", "pymatgen": "2022.0.8", "rest": "2.0"}, "created_at": "2022-10-20T21:17:27.506782"}'

Would be nice to have the ability to co-operate old and new `MPRester` and would also allow us to fix CI. That would require adding a new key like `PMG_LEGACY_API_KEY` to `.pmgrc.yaml`. Old MPRester looks for that first and falls back on PMG_API_KEY else. Any thoughts?

**Comment by mkhorton** [comment]
Tagging @munrojm here. The new MPRester adaptor should choose either the legacy or new API based on the length of the API key. Is this not working?

**Comment by janosh** [comment]
> The new MPRester adaptor should choose either the legacy or new API based on the length of the API key. Is this not working?

@mkhorton It is working for pymatgen users but doesn't help with the tests (unless I'm missing sth). There, we explicitly import the old Rester since that's the one we want to test.

https://github.com/materialsproject/pymatgen/blob/41abff0b5f8eceb99af2d4d8492694f701096d12/pymatgen/ext/tests/test_matproj.py#L26

And it's trying to use the new API since that's the only passed to the GH action as a secret:

https://github.com/materialsproject/pymatgen/blob/fe42ce1fa2f471e256debb240e57e08415b6dd79/.github/workflows/test-linux.yml#L37

This assumes the answer to my above question is yes, i.e. the Gh secret is a new API key which I suspect is true since it was updated on Sep 13.

**Comment by mkhorton** [comment]
Hm, well the new MPRester tests are inside the [api repo](https://github.com/materialsproject/api) anyway; perhaps it's better we only test legacy inside pymatgen itself? It could keep the pymatgen tests cleaner since when the legacy API is removed, we could remove the API tests from pymatgen altogether, and remove a common failure mode (ideally, pymatgen tests do not fail because of a server outage). In this case, we just change the secrets API key back to the legacy API key.

**Comment by janosh** [comment]
That sounds sensible. I set my own old API key as PMG_LEGACY_API_KEY secret on this repo to test this. Will remove it again. Will you set `PMG_MAPI_KEY` to an old one?

**Comment by mkhorton** [comment]
> Will you set PMG_MAPI_KEY to an old one?

Done!

**Comment by DanielYang59** [comment]
> Generally, our recommendation is not to develop any tools against the legacy API and to move existing tools away from the legacy API. The underlying data is years outdated and the code behind it is not maintained. It will soon be retired / taken down entirely. HTH

That absolutely makes sense, I personally don't have a use case for the legacy API, just some examples in `matgenb` explicitly require the legacy API https://github.com/materialsvirtuallab/matgenb/pull/61, I would see if I could migrate them to the new API, if not I guess the best thing to do is to skip the test for now (or remove it if the data is super outdated).

Thanks again and sorry for digging up the ancient thread
