### ISSUE TITLE
Regular release schedule and TestPyPI or PyPI option

### ISSUE THREAD

**Issue by jmmshn** [materialsproject/pymatgen#2701]
@shyuep @mkhorton @janosh I think it would be super helpful to have:
1. A regular (bi-weekly) release schedule, because downloading the repo from github is still too "technologically advanced" for some people.
2. A version of the code on TestPyPI (or just a PyPI option for the current master branch) that is always pointed to master so that CI and/or releases of downstream code is smoother, currently if I'm point a dependency at the github repo it really slows down the CI.

**Comment by shyuep** [comment]
I am unclear what a regular release schedule means. We release when there are a significant number of changes that warrant a release. For many people, they could be using 2019 versions of pymatgen and not notice a difference with the 2022 version.

**Comment by janosh** [comment]
> just a PyPI option for the current master branch

Maybe this helps `pip install -U git+https://github.com/materialsproject/pymatgen`? This is basically what an automated release the PyPI after every commit to `master` would give you.

**Comment by jmmshn** [comment]
@shyuep I guess it's more important that the changes happen at predictable intervals so people can plan accordingly.
It's hard telling people that something will be fixed in the next release and have no timeline for when that will happen.

**Comment by jmmshn** [comment]
@janosh 

pip install -U git+https://github.com/materialsproject/pymatgen
That doesn't fix the issue of extremely slow install from the GitHub in the CI.  Also releasing any downstream code is not possible if any of the dependencies is from github

**Comment by shyuep** [comment]
Changes do not happen at regular intervals. That is the reality of all software codes. If I deem a bug fix important enough, I usually issue a release immediately. If there are no changes between today and a month from now, I see no reason to do a release. Most changes in pymatgen are in the form of new functionality.

**Comment by jmmshn** [comment]
So say I have feature A in `pymatgen` that fixes allow feature B in `pymatgen-analysis-diffusion` and is needed to merge a PR on atomate2.  The problem is completely fixed but there is a `pymatgen` release all those other things are completely on hold.

If the releases are mostly meant to deal with bug fixes, then we should have some mechanism that allows people to use the newest master branch (that is not just downloading the GitHub repo because I have ran into situations where the user's internet and computer speed made that really difficult, in addition to the slow CI workflow problem stated above)

**Comment by shyuep** [comment]
When such situations occur, by all means let us know and request to do a release. To date, I have never denied any such requests. There is a way to use master for the downstream codes that is stipulated by @janosh. For CI purposes, that is not a problem.

**Comment by jmmshn** [comment]
OK, then can I get a release?  😄

**Comment by janosh** [comment]
@shyuep I fixed [a small bug](https://github.com/materialsproject/pymatgen/pull/2702/files#diff-9931b710fdada44a5468d08079cf19a3e8f1825cfd3eaff24ae2bf1ed3784cc0R43) in #2702. Maybe wait for that to merge.

**Comment by shyuep** [comment]
@jmmshn done.
