### ISSUE TITLE
pymatgen.core.periodic_table: block property

### ISSUE THREAD

**Issue by rnotestine** [materialsproject/pymatgen#272]
Not being a materials scientist, perhaps I am simply naive, but I find some of the current block assignments to be surprising.  The relevant code is:

>     @property
>     def block(self):
>         """
>         Return the block character "s,p,d,f"
>         """
>         block = ""
>         if self.group in [1, 2]:
>             block = "s"
>         elif self.group in range(13, 19):
>             block = "p"
>         elif self.is_actinoid or self.is_lanthanoid:
>             block = "f"
>         elif self.group in range(3, 13):
>             block = "d"
>         else:
>             print("unable to determine block")
>         return block

Which results in lan­thanides with periodic number 67-70 and actinides with periodic number 99-102 being assigned to "p"-block, whereas I expected them to be assigned to "f"-block.  Perhaps the two lines of "p"-block code were placed above the "f"-block code to prevent Lu and Lr from being assigned to "f"-block (and the full consequences were not immediately obvious)?  Or perhaps my notion of "f"-block is simply inaccurate.

**Comment by rnotestine** [comment]
Your change appears to assign Lu and Lr to the "f"-block (rather than 
the "d"-block).  But perhaps that was intentional?

- Randy

**Comment by shyuep** [comment]
Just pushed a fix.
