### ISSUE TITLE
SpacegroupAnalyzer returns duplicate symmetry operations 

### ISSUE THREAD

**Issue by lbluque** [materialsproject/pymatgen#2725]
**Describe the bug**
The `SpacegroupAnalyzer` class returns a list of symmetry operations, where each unique symop appears twice.

This seems to be related to the upgrade of spglib, since the issue occurs with spglib >= 2, but not with earlier versions.

**To Reproduce**

```python
from pymatgen.core import Structure, Lattice
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

lattice = Lattice([[3, 3, 0], [0, 3, 3], [3, 0, 3]])
species = 3 * ["A"] + ["D"]
coords = (
    (0.25, 0.25, 0.25), (0.75, 0.75, 0.75), (0.5, 0.5, 0.5),  (0, 0, 0)
)
structure = Structure(lattice, species, coords)
sga = SpacegroupAnalyzer(structure)
symops = sga.get_symmetry_operations()

# each symop appears twice!
for i in range(0, len(symops) - 1, 2):
    assert symops[i] == symops[i + 1]
```

**Expected behavior**
The list of symmetry operations should not contain duplicates.

**Desktop (please complete the following information):**

- OS: Linux
- Version: 2022.11.1

**Comment by lan496** [comment]
`SpacegroupAnalyzer.get_symmetry_operations` calls `spglib.get_symmetry` with cell `self._cell`. The current implementation seems to attach magmoms in `self._cell` even when magmoms are not specified in `Structure`:
https://github.com/materialsproject/pymatgen/blob/ffbebceafc3482e1a63008974a6da64e522e78c9/pymatgen/symmetry/analyzer.py#L79-L80

From spglib v2, the behavior of `spglib.get_symmetry` with zero magmoms is changed. Now `spglib.get_symmetry` returns the same spatial symmetry with time_reversal=True and time-reversal=False. So the size doubles.
(c.f. https://github.com/spglib/spglib/issues/150#issuecomment-1180158502)

I am not sure a reason to attach magmoms in this case. But removing the above line will solve this issue.

**Comment by lbluque** [comment]
Thanks a lot @lan496 !

As for pymatgen, I think removing the line you suggest is the way forward.

Otherwise, adding a `unique` keyword parameter to `get_symmetry_operations`  and following your suggestion in the comment linked (https://github.com/spglib/spglib/issues/150#issuecomment-1180158502) is an option too.
