### ISSUE TITLE
Loose endpoints in NEB string_relax()

### ISSUE THREAD

**Issue by fucaline** [materialsproject/pymatgen#2732]
I found a bug in the method `string_relax()`, in `class NEBPathfinder`:
The endpoints are not kept fixed as expected due to numpy array operation the line 234: ` s0 = s` wich does not effectively save the state of `s`. https://github.com/materialsproject/pymatgen/blob/6b520e307fea25d890261b3916ecfc6fe802ae94/pymatgen/analysis/path_finder.py#L234
Later, line 258,
```
# Fix endpoints
s[0] = s0[0]
s[-1] = s0[-1]
```
does not recover the inital and final points.

**Solution**
I changed to `s0 = np.copy(s)` and it resolved the issue in my code.

**Comment by janosh** [comment]
@fucaline Good catch! Thanks for reporting.

**Comment by janosh** [comment]
Do you have a minimal example that failed before and works with your fix so we can add a test for this?

**Comment by fucaline** [comment]
I don't have a clean minimal example unfortunately. Only my project data, that I can provide but it's not a very clean and comprehensive example.

**Comment by janosh** [comment]
I see. I'll merge as-is then.
