### ISSUE TITLE
Help me using VASP input sets.

### ISSUE THREAD

**Issue by 91bsjun** [materialsproject/pymatgen#275]
from pymatgen.core import *
from pymatgen.io.vasp.sets import *

s1 = IStructure.from_file("tst.cif")
AbstractVaspInputSet.get_all_vasp_input(s1)

Here is the error.

File "<stdin>", line 1, in <module>
TypeError: unbound method get_all_vasp_input() must be called with AbstractVaspInputSet instance as first argument (got IStructure instance instead)

**Comment by shyuep** [comment]
AbstractVaspINputSet is an abstract base class. You need to use one of the concrete implementations. E.g., MPVaspInputSet().get_all_vasp_input(s1).

This is not a bug.
