### ISSUE TITLE
Interactive convex hull plot not refreshing when dragged/rotated

### ISSUE THREAD

**Issue by deecadance** [materialsproject/pymatgen#2768]
I'm encountering an issue while using `pymatgen` to visualize convex hulls in a Jupyter notebook, particularly when using Plotly as a backend (`matplotlib` works fine). After an initial successful render of the convex hull, using any interactive tool (zoom, rotation, etc.) doesn't clear the previous image, and it fails to re-render unstable points and convex hull lines (`show_unstable`).

This issue occurred spontaneously, potentially after a software update, and persists even after updating to the latest versions. The problem is not data-specific and occurs with any dataset.

Here's a screenshot for reference:
![Issue Screenshot](https://user-images.githubusercontent.com/25180487/205903943-658e8473-fe45-4a14-9ab2-ab35070f801a.png)

To replicate the issue, I use the following code to plot data from a pandas dataframe:

```python
hull=pg.CompoundPhaseDiagram(entry_list,terminal_list,normalize_terminal_compositions=True)
hull.transform_entries(entry_list,terminal_list)
plot_hull=pg.PDPlotter(hull,show_unstable=False,markersize=20.5,linewidth=1.5, markerfacecolor=(200/255,80/255,30/255),markeredgecolor=(200/255,80/255,30/255), alpha = 1.0, color = 'gray')
handle=plot_hull.get_plot(label_stable=True, label_unstable=False, energy_colormap=None)
```

System Info:
- OS: Mac OSX Monterey 12.3.1 (13-inches MacBook pro, M1 2020)
- pymatgen version: 7.11.2022
- plotly version: 5.11.0

**Comment by mattmcdermott** [comment]
Hi @deecadance, are you still having this issue? If so, what browser are you using? I wrote most of the Plotly phase diagram code and have never seen an issue like this before.

**Comment by deecadance** [comment]
Hi! I just tried, and yes I am still having it. I am using Safari (15.4) on a M1 Macbook pro (OS 12.3.1)

I hadn't thought of the obvious "try a different browser" check. I just tried and I do **not** have this problem on google chrome. This kind of fixes the problem for me.

**Comment by mattmcdermott** [comment]
Hi @deecadance That is great to hear (also a little problematic for other Safari users). I will look into it more...

**Comment by mattmcdermott** [comment]
@deecadance is this still a common problem for you?

**Comment by deecadance** [comment]
Hi! I just tried, the problem is gone! Thanks :)

**Comment by janosh** [comment]
Fixed in https://github.com/materialsproject/pymatgen/pull/3032.
