### ISSUE TITLE
Many failing tests

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/pymatgen#2788]
**Describe the bug**
Hi all, 

there are currently many, many failing tests connected to evaluations of structures.  Once the new year vacations are over, it would be great to resolve it so that contributing gets easier again.

**Comment by janosh** [comment]
Hey @JaGeo, some tests started failing when we went from `numpy` 1.23.0 to 1.24.0 in CI. @mkhorton and me fixed some of those. I think there's just 1 of those remaining that requires updating 2 test files.

For other test failures I'm not sure how they arose. There's one in `ReadWriteChemenvTest.test_read_write_structure_environments()` which i discussed with @shyuep here
https://github.com/materialsproject/pymatgen/commit/0eb1e3d72fd894b7ba39a5129fbd8b18aedf4b46#commitcomment-92101479. Tried to fix it a while back but gave up.

Another in `pymatgen/analysis/tests/test_piezo_sensitivity.py`. I hope that's all of them but not sure.

Anyway, plan is to fix them asap but haven't had time recently. PRs welcome of course.

**Comment by JaGeo** [comment]
@janosh Thanks for looking into it.

**Comment by janosh** [comment]
I fixed 7 failing tests. There's just 1 left (I think) that's not straightforward to debug (the one in `ReadWriteChemenvTest.test_read_write_structure_environments` I mentioned). Maybe someone else has better luck than me with that one.

**Comment by munrojm** [comment]
Came here to post about this. Thanks for looking at it @janosh!

**Comment by JaGeo** [comment]
I think it is related to PeriodicNeigbors and as_dict and from_dict for this one. Species is still a dict after from_dict. I am trying to work on it but I am somehow stuck. 

I think it's this line: https://github.com/materialsproject/pymatgen/blob/e3bcad781fb83978fd7394ffc16d880e9ba9ab8d/pymatgen/analysis/chemenv/coordination_environments/structure_environments.py#L2096 
and this line:
https://github.com/materialsproject/pymatgen/blob/e3bcad781fb83978fd7394ffc16d880e9ba9ab8d/pymatgen/analysis/chemenv/coordination_environments/structure_environments.py#L2125

**Comment by JaGeo** [comment]
Thank you very much for looking into this @janosh and thank you for the work.

**Comment by JaGeo** [comment]
I think one problem might be the following:
`from pymatgen.core.composition import Composition

comp=Composition({'O2-': 1.0})

print(comp == comp.as_dict())`

This leads to False. I do not think that it should lead to False, right? But there seems to be more than this.

**Comment by JaGeo** [comment]
Well, other can be a dict: https://github.com/materialsproject/pymatgen/blob/6b520e307fea25d890261b3916ecfc6fe802ae94/pymatgen/core/composition.py#L163

**Comment by shyuep** [comment]
I don't see this as a hole at all. Composition subclasses dict. So comparison with another dict is fine. But it stands to reason that the keys must be valid composition keys (Element or Species). You can of course try to convert the dict keys using get_el_sp, but that will slow down equality comparisons considerably. It is the same that {"1": 2} is not going to be equals to {1: 2}. One has a string key and the other has a int key.

We should not be changing the core classes to fix a problem with chemenv. If there is anything to be fixed, it has to be chemenv that needs to be changed.

**Comment by JaGeo** [comment]
Agreed. 

I think the error is related to PeriodicNeighbors and the from_dict and as_dict there... but I did not see an easy way to fix it...

**Comment by shyuep** [comment]
One potential expensive way of fixing it is to convert the PeriodicNeighbors to a standard PeriodicSite object. Or the from_dict will have to reconsitute the actual Species in ChemEnv.

**Comment by JaGeo** [comment]
I have implemented the conversion to PeriodicSites and could start a pull request. I just don't know how expensive it would be. 
With the other option, I was a bit lost as I also saw problems with the coordinates.
