### ISSUE TITLE
Issue with get_point_group() in SpacegroupAnalyzer

### ISSUE THREAD

**Issue by gcheon** [materialsproject/pymatgen#280]
Hello,

I'm trying to analyze a structure with no screw axes(I intentionally modified the structure to break that symmetry- the screw axis was the z axis, so I copied the unit cell in a random position along the z axis. Structure on the bottom), but get_point_group() keeps saying that it has a screw axis(point group 32) no matter what I do. Could you explain how exactly get_point_group() works? Also, I ran get_symmetry_operations() to see what was  happening, and I got:
[Rot:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
tau
[ 0.  0.  0.], Rot:
[[ 0. -1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
tau
[ 0.  0.  0.], Rot:
[[-1.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
tau
[ 0.  0.  0.], Rot:
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0. -1.]]
tau
[ 0.          0.          0.36890909], Rot:
[[-1.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
tau
[ 0.          0.          0.36890909], Rot:
[[ 1.  0.  0.]
 [ 1. -1.  0.]
 [ 0.  0. -1.]]
tau
[ 0.          0.          0.36890909]]
 
and the value of tau does not look like 1/3 or 2/3, which also seems strange. 

Thanks for your help!
Gowoon Cheon

Structure Summary
Lattice
    abc : 6.2220912549552922 6.2220912549552922 55.459783010650753
 angles : 90.0 90.0 119.99999999999999
 volume : 1859.4373503805373
      A : 3.1110456274776461 -5.3884890914562815 0.0
      B : 3.1110456274776461 5.3884890914562815 0.0
      C : 0.0 0.0 55.459783010650753
PeriodicSite: Sc (0.0000, 0.0000, 30.2508) [0.0000, 0.0000, 0.5455]
PeriodicSite: Ag (3.1110, -1.7962, 30.2508) [0.6667, 0.3333, 0.5455]
PeriodicSite: P (3.1110, 1.7962, 29.1383) [0.3333, 0.6667, 0.5254]
PeriodicSite: P (3.1110, 1.7962, 31.3633) [0.3333, 0.6667, 0.5655]
PeriodicSite: S (3.9499, 3.5671, 31.9314) [0.3038, 0.9658, 0.5758]
PeriodicSite: S (4.2252, 0.1842, 31.9314) [0.6620, 0.6962, 0.5758]
PeriodicSite: S (1.1579, 1.6372, 31.9314) [0.0342, 0.3380, 0.5758]
PeriodicSite: S (5.0641, 1.6372, 28.5702) [0.6620, 0.9658, 0.5152]
PeriodicSite: S (2.2721, 3.5671, 28.5702) [0.0342, 0.6962, 0.5152]
PeriodicSite: S (1.9968, 0.1842, 28.5702) [0.3038, 0.3380, 0.5152]
PeriodicSite: Sc (0.0000, 0.0000, 45.6686) [0.0000, 0.0000, 0.8235]
PeriodicSite: Ag (3.1110, -1.7962, 45.6686) [0.6667, 0.3333, 0.8235]
PeriodicSite: P (3.1110, 1.7962, 44.5561) [0.3333, 0.6667, 0.8034]
PeriodicSite: P (3.1110, 1.7962, 46.7811) [0.3333, 0.6667, 0.8435]
PeriodicSite: S (3.9499, 3.5671, 47.3492) [0.3038, 0.9658, 0.8538]
PeriodicSite: S (4.2252, 0.1842, 47.3492) [0.6620, 0.6962, 0.8538]
PeriodicSite: S (1.1579, 1.6372, 47.3492) [0.0342, 0.3380, 0.8538]
PeriodicSite: S (5.0641, 1.6372, 43.9880) [0.6620, 0.9658, 0.7932]
PeriodicSite: S (2.2721, 3.5671, 43.9880) [0.0342, 0.6962, 0.7932]
PeriodicSite: S (1.9968, 0.1842, 43.9880) [0.3038, 0.3380, 0.7932]

**Comment by shyuep** [comment]
Try modifying the symprec. The default is pretty high. 


Shyue Ping






On Thu, Dec 3, 2015 at 5:57 PM -0800, "gcheon" <notifications@github.com> wrote:












Hello,



I'm trying to analyze a structure with no screw axes(I intentionally modified the structure to break that symmetry- the screw axis was the z axis, so I copied the unit cell in a random position along the z axis. Structure on the bottom), but get_point_group() keeps saying that it has a screw axis(point group 32) no matter what I do. Could you explain how exactly get_point_group() works? Also, I ran get_symmetry_operations() to see what was  happening, and I got:

[Rot:

[[ 1.  0.  0.]

 [ 0.  1.  0.]

 [ 0.  0.  1.]]

tau

[ 0.  0.  0.], Rot:

[[ 0. -1.  0.]

 [ 1. -1.  0.]

 [ 0.  0.  1.]]

tau

[ 0.  0.  0.], Rot:

[[-1.  1.  0.]

 [-1.  0.  0.]

 [ 0.  0.  1.]]

tau

[ 0.  0.  0.], Rot:

[[ 0. -1.  0.]

 [-1.  0.  0.]

 [ 0.  0. -1.]]

tau

[ 0.          0.          0.36890909], Rot:

[[-1.  1.  0.]

 [ 0.  1.  0.]

 [ 0.  0. -1.]]

tau

[ 0.          0.          0.36890909], Rot:

[[ 1.  0.  0.]

 [ 1. -1.  0.]

 [ 0.  0. -1.]]

tau

[ 0.          0.          0.36890909]]



and the value of tau does not look like 1/3 or 2/3, which also seems strange. 



Thanks for your help!

Gowoon Cheon



Structure Summary

Lattice

    abc : 6.2220912549552922 6.2220912549552922 55.459783010650753

 angles : 90.0 90.0 119.99999999999999

 volume : 1859.4373503805373

      A : 3.1110456274776461 -5.3884890914562815 0.0

      B : 3.1110456274776461 5.3884890914562815 0.0

      C : 0.0 0.0 55.459783010650753

PeriodicSite: Sc (0.0000, 0.0000, 30.2508) [0.0000, 0.0000, 0.5455]

PeriodicSite: Ag (3.1110, -1.7962, 30.2508) [0.6667, 0.3333, 0.5455]

PeriodicSite: P (3.1110, 1.7962, 29.1383) [0.3333, 0.6667, 0.5254]

PeriodicSite: P (3.1110, 1.7962, 31.3633) [0.3333, 0.6667, 0.5655]

PeriodicSite: S (3.9499, 3.5671, 31.9314) [0.3038, 0.9658, 0.5758]

PeriodicSite: S (4.2252, 0.1842, 31.9314) [0.6620, 0.6962, 0.5758]

PeriodicSite: S (1.1579, 1.6372, 31.9314) [0.0342, 0.3380, 0.5758]

PeriodicSite: S (5.0641, 1.6372, 28.5702) [0.6620, 0.9658, 0.5152]

PeriodicSite: S (2.2721, 3.5671, 28.5702) [0.0342, 0.6962, 0.5152]

PeriodicSite: S (1.9968, 0.1842, 28.5702) [0.3038, 0.3380, 0.5152]

PeriodicSite: Sc (0.0000, 0.0000, 45.6686) [0.0000, 0.0000, 0.8235]

PeriodicSite: Ag (3.1110, -1.7962, 45.6686) [0.6667, 0.3333, 0.8235]

PeriodicSite: P (3.1110, 1.7962, 44.5561) [0.3333, 0.6667, 0.8034]

PeriodicSite: P (3.1110, 1.7962, 46.7811) [0.3333, 0.6667, 0.8435]

PeriodicSite: S (3.9499, 3.5671, 47.3492) [0.3038, 0.9658, 0.8538]

PeriodicSite: S (4.2252, 0.1842, 47.3492) [0.6620, 0.6962, 0.8538]

PeriodicSite: S (1.1579, 1.6372, 47.3492) [0.0342, 0.3380, 0.8538]

PeriodicSite: S (5.0641, 1.6372, 43.9880) [0.6620, 0.9658, 0.7932]

PeriodicSite: S (2.2721, 3.5671, 43.9880) [0.0342, 0.6962, 0.7932]

PeriodicSite: S (1.9968, 0.1842, 43.9880) [0.3038, 0.3380, 0.7932]

**Comment by shyuep** [comment]
Closing this issue. Pls reopen if issue persists.
