### ISSUE TITLE
Any chance using scipy's hull implementation instead of pyhull

### ISSUE THREAD

**Issue by Luindil** [materialsproject/pymatgen#281]
Hi all,

the main problem I have with using pymatgen is that is uninstallable right now under a windows in 64 bit (32 bit seems to work though). The reason for this is the installation of pyhull. Is there any chance that pyhull could just be replaced by the scipy implementation?

As a side note, even the maintainer of pyhull states that the scipy implementation is actually 50% faster:
(from the pyhull Readme.md - https://github.com/materialsvirtuallab/pyhull)

"At the time of development of pyhull, the scipy.spatial package was the only other package that supports the computation of higher dimensional convex hulls. However, the version of scipy at that time (scipy 0.11.0) only supported the computation of Delaunay triangulation and the convex hull was computed from the Delaunay triangulation, which is slower and less reliable than directly computing the convex hull. As of version 0.12.0, scipy now supports the direct computation of convex hulls and is in fact ~50% faster than pyhull for larger hulls. I will still make pyhull available for the simple reason that the scipy package is fairly large and not everyone wants to install such a large package for computing hulls."

As scipy is anyway a requirement for pymatgen, it would make sense to reduce the dependencies.

Clemens

**Comment by shyuep** [comment]
We cannot abandon pyhull completely for two undocumented reasons. Pymatgen is used in the Materials Project to generate phase diagrams. To make sure we can do it in a reasonably fast fashion, we use multiprocessing. The problem we had was that scipy's implementation of the convex hull does not work in multiprocessing and leads to crashes or worse, bad data. That was several versions of scipy ago. So I don't know if that holds true today. Second, some functions of pymatgen still rely on pyhull and has no fall back on

The best I can do is to make it an optional dependency. That would enable you to install pymatgen, with perhaps a slight loss in functionality.

**Comment by Luindil** [comment]
That would be great!

**Comment by shyuep** [comment]
Try the latest beta: https://github.com/materialsproject/pymatgen/releases/tag/v3.2.8b and let me know if it works.

**Comment by shyuep** [comment]
I am closing this issue and adding two other issues specific to the dependency of electronic structure and Pourbaix packages on pyhull. Otherwise, pymatgen should install without needing pyhull with the latest 3.2.8 release.
