### ISSUE TITLE
to_cube function has a bug

### ISSUE THREAD

**Issue by giovannipizzi** [materialsproject/pymatgen#2817]
**Describe the bug**
The [`to_cube` function](https://github.com/materialsproject/pymatgen/blob/e513400b77dc3810b45a6529437971e7762a250e/pymatgen/io/common.py#L334-L378) of VolumetricData has a bug: it stores in lines 4-6 the real-space vectors instead of the size of a voxel.

**To Reproduce**
1. Get any cube file
2. run the following code, that should return the same file (apart from cosmetics):
     ```python
     from pymatgen.io.common import VolumetricData
     cubefile = VolumetricData.from_cube(IN_FNAME)
     cubefile.to_cube(OUT_FNAME)
     ```
3. check the content of the two files. You will see that lines 4-6 are wrong. 

E.g. in my case, original file (lines 4-6):
```
   72    0.170589    0.000000    0.000000
   80    0.000000    0.163473    0.000000
  108   -0.114105    0.000000    0.125017
```
Output file:
```
	 72 12.282408 0.000000 0.000000 
	 80 0.000000 13.077840 0.000000 
	 108 -12.323340 0.000000 13.501836 
```

**Expected behavior**
The correct values are written in the cube file.

It should be as simple as changing the following lines:
https://github.com/materialsproject/pymatgen/blob/e513400b77dc3810b45a6529437971e7762a250e/pymatgen/io/common.py#L349-L365
to something like (untested, but should work)
```
            file.write(
                f"\t {self.dim[0]} "
                f"{self.structure.lattice.matrix[0][0] / self.dim[0] * ang_to_bohr :.6f} "
                f"{self.structure.lattice.matrix[0][1] / self.dim[0] * ang_to_bohr :.6f} "
                f"{self.structure.lattice.matrix[0][2] / self.dim[0] * ang_to_bohr :.6f} \n"
            )
```
and analogously for the following two lines.

**Comment by janosh** [comment]
Thanks for reporting! 👍
