### ISSUE TITLE
Make electronic structure classes independent of Pyhull

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#282]
Pyhull is still used in the BSPlotter. Can these be switched over to scipy's implementation? It does not seem too difficult for the electronic structure classes. The plan is to move to a Pyhull-free pymatgen for easier support on more platforms.

**Comment by janosh** [comment]
Looks like this was fixed in [v2017.12.8](https://github.com/materialsproject/pymatgen/releases/tag/v2017.12.8).
