### ISSUE TITLE
Search Bar not working on site

### ISSUE THREAD

**Issue by JPBergsma** [materialsproject/pymatgen#2828]
When I go to the pymatgen website(https://pymatgen.org/) and type a search term in the search bar, the search never finishes.

This occurs under firefox version:  Mozilla Firefox version mint-001 - 1.0    109.0.1(64-bit)
as well as under Chromium version: 109.0.5414.119 (Official Build) for Linux Mint (64-bit)

**Comment by shyuep** [comment]
Thanks for reporting this. I just pushed a fix. For some reason, jQuery disappeared from current pymatgen docs. @janosh is this related to the update of the docs you did recently?

**Comment by janosh** [comment]
@shyuep Don't think so but maybe I missed something? Last time I updated the docs was for the [v2023.1.9 release](https://github.com/materialsproject/pymatgen/releases/tag/v2023.1.9) (https://github.com/materialsproject/pymatgen/pull/2798). Lots of changed lines but I didn't spot a `jquery` removal in there.

**Comment by JPBergsma** [comment]
Thank you for the quick fix. For me, the search bar is working again!
