### ISSUE TITLE
Avoid adjusting input entries in mixing schemes.

### ISSUE THREAD

**Issue by peikai** [materialsproject/pymatgen#2832]
The usage of process_entries() method needs attention.

In the case that running **processed_entryList = compatibility.process_entries(entryList, clean=True),** entryList will be changed as well. The method not only returns adjusted entries, but also change input entries in place. Is it necessary? I think this may cause bugs in programming and affect subsequent usage of input entries.

In the case that running **processed_entryList = compatibility.process_entries(entryList, clean=False)**, it only returns the entries that have been processed, not always the complete set of adjusted entries. If input entries have contained energy adjustments, they would not be processed again, and even would not be shown in the results that are returned, which might cause missing entries in phase diagrams, when using them to create phase diagrams.

I've ever created a PR, but then closed it to avoid changing the usage style.

https://github.com/materialsproject/pymatgen/pull/2830

**Comment by janosh** [comment]
I've run into the same problem. I definitely agree that API could be improved. But it would be a substantial change, so not something to do on a whim. I think any modifications would need the green light from @shyuep, @mkhorton and @rkingsbury.

**Comment by peikai** [comment]
I agree, the process_entries() still works if people use with awareness, i.e., keeping clean=True and aware of entries change in place when building phase diagrams. I've noticed there is a warning on it in up-to-date documents.

**Comment by rkingsbury** [comment]
I agree the API can be improved. I believe the current behavior of `process_entries` was intended to emulate the historical behavior (see #1826 when we updated the Compatibility API) - i.e., it both processes entries in place and returns the processed entries. This is partly due to the fact that the energy corrections are carried as attributes to the entries, so in some sense it makes sense to process them in-place.  Note, however, that any entry which raises a `CompatibilityError` is _not_ returned by `process_entries`. This was again trying to emulate historical behavior, where any "incompatible" entries would be excluded from the returned list.

> In the case that running processed_entryList = compatibility.process_entries(entryList, clean=False), it only returns the entries that have been processed, not always the complete set of adjusted entries.

I was not aware that this was the case, and it's not intended behavior. The only thing `clean` is supposed to do is to control whether or not the `energy_adjustment` attribute of an entry is cleared before processing or not.

In any case, I'm not opposed to changes that reduce potential for confusion or errors, and I think they could be made with relatively little effort (although we'd need to coordinate them with Builder logic in `emmet` `ThermoBuilder` to make sure). I'd be happy to comment on PR with proposed changes.

**Comment by janosh** [comment]
>  In any case, I'm not opposed to changes that reduce potential for confusion or errors, and I think they could be made with relatively little effort

Perfect! @peikai If you want to submit a PR, I think you'll get plenty of feedback. Maybe a good first step would be to always return the full list of passed entries, regardless of whether they were corrected or not. And might be good to have an `inplace` flag. Should it default to `False` to keep with current behavior or to `True` meaning always return copies and leave originals untouched? I'm leaning towards the former for speed.

**Comment by rkingsbury** [comment]
> Maybe a good first step would be to always return the full list of passed entries, regardless of whether they were corrected or not. 

So this change would likely cause a lot of problems. Part of the core idea behind `process_entries` is that it _only_ returns entries that are "valid" within a particular `Compatibility` scheme. This is essential for properly constructing phase diagrams and things. For example, if you pass a collection of LDA, GGA, and GGA+U entries to `MaterialsProjectCompatibility2020` and run `process_entries` on it, the class needs to make sure the LDA entries are discarded. So I think its important, as a design principle, that `process_entries` only return the right entries. Technically speaking, this means entries that don't raise a `CompatibilityError` when passed to `get_adjustments` .

That said, to extend the above example, _any GGA or GGA+U_ entry should be returned, even if its correction is zero. That should be the current behavior, but if its not we should investigate.

> And might be good to have an `inplace` flag. Should it default to `False` to keep with current behavior or to `True` meaning always return copies and leave originals untouched? I'm leaning towards the former for speed.

I like this idea

**Comment by shyuep** [comment]
@peikai In general, there should be only one valid entry list during use. I am fine if the code is changed to avoid changing the original entry list. But the general idea is that you should not be using the original entry list after processing in the first place. I am not clear of the use case where both the original and processed entry list are both used in an analysis.

**Comment by janosh** [comment]
> So this change would likely cause a lot of problems. Part of the core idea behind process_entries is that it only returns entries that are "valid" within a particular Compatibility scheme.

Ah, I was not aware of this. I thought that is left to the user to handle correctly. Good to know.

**Comment by peikai** [comment]
> > In the case that running processed_entryList = compatibility.process_entries(entryList, clean=False), it only returns the entries that have been processed, not always the complete set of adjusted entries.
> 
> I was not aware that this was the case, and it's not intended behavior. The only thing `clean` is supposed to do is to control whether or not the `energy_adjustment` attribute of an entry is cleared before processing or not.

@rkingsbury, because some entries might have already contained adjusted energy. If clean=False, these entries with correct adjustment would not be processed again by the method, thereby missing in processed_entryList, then missing in subsequent phase diagrams built with them. This may happen in both of compatibility.process_entries() and MaterialsProjectDFTMixingScheme().process_entries().

@shyuep, I intended to generate and compare the phase diagrams built with GGA/GGA+U (Mixed) scheme and GGA/GGA+U/R2SCAN (Mixed) scheme in one file. Then I found the input entries are changed in place that could not be reused, and processed entries could possibly not a complete set of entries that have adjusted energy.

Thanks all.

**Comment by rkingsbury** [comment]
> @rkingsbury, because some entries might have already contained adjusted energy. If `clean=False`, these entries with correct adjustment would not be processed again by the method, thereby missing in processed_entryList, then missing in subsequent phase diagrams built with them. This may happen in both of `compatibility.process_entries()` and `MaterialsProjectDFTMixingScheme().process_entries()`.

Hmm, I see. I agree those entries would not be processed again, but they really should be passed through to the returned list. If not, I think that is a bug that we should fix. Thanks for investigating; can you provide a minimal example?

> @shyuep, I intended to generate and compare the phase diagrams built with GGA/GGA+U (Mixed) scheme and GGA/GGA+U/R2SCAN (Mixed) scheme in one file. Then I found the input entries are changed in place that could not be reused, and processed entries could possibly not a complete set of entries having adjusted energy.

Yes, for this use case you should maintain two separate copies, because the GGA/GGA+U entries will require different corrections in the regular vs. the R2SCAN mixing scheme. Note that you may have to use `.deepcopy` to ensure your two lists aren't actually pointing to the same underlying entries.

**Comment by peikai** [comment]
@rkingsbury, I read source codes again. The `process_entries()` method returns all entries having (correct) adjusted energy indeed. I misinterpreted the effect of `pass` command of it.

Ignore the second fixing request below.

> In the case that running **processed_entryList = compatibility.process_entries(entryList, clean=False)**, it only returns the entries that have been processed, not always the complete set of adjusted entries. If input entries have contained energy adjustments, they would not be processed again, and even would not be shown in the results that are returned, which might cause missing entries in phase diagrams, when using them to create phase diagrams.

**Comment by peikai** [comment]
> > And might be good to have an `inplace` flag. Should it default to `False` to keep with current behavior or to `True` meaning always return copies and leave originals untouched? I'm leaning towards the former for speed.
> 
> I like this idea

Thanks, @janosh @rkingsbury. A PR #2841 has been opened to add the inplace flag.

**Comment by peikai** [comment]
The PR has been merged.
