### ISSUE TITLE
Primitive matrix for trigonal structure has negative determinant

### ISSUE THREAD

**Issue by dgaines2** [materialsproject/pymatgen#2838]
For certain structures, pymatgen's `SpacegroupAnalyzer.get_conventional_to_primitive_transformation_matrix()` is returning a matrix with a negative determinant, which is causing issues when trying to use this transformation matrix in codes like `phonopy`. I know that the symmetry elements for trigonal space groups are especially tricky, and I see that there have been multiple issues in the past with trigonal or hexagonal rhombohedral cells.

For example, As in the R-3m spacegroup (166) with mpid mp-11.

```
import numpy as np
from pymatgen.core import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

# conventional poscar downloaded directly from MP
structure = Structure.from_file("POSCAR")
sga = SpacegroupAnalyzer(structure)
conv_to_prim_trans_matrix = sga.get_conventional_to_primitive_transformation_matrix()
print(conv_to_prim_trans_matrix)
    array([[-0.33333333,  0.33333333,  0.33333333],
           [ 0.66666667,  0.33333333,  0.33333333],
           [-0.33333333, -0.66666667,  0.33333333]])
         
trans_matrix_det = np.linalg.det(conv_to_prim_trans_matrix)
print(trans_matrix_det)
     -0.3333333333333333
```

`Phonopy/spglib` are able to find a primitive matrix with a positive determinant.

Any ideas how to fix this?

**Comment by shyuep** [comment]
I think a simple solution would be to multiply the lattice matrix and vectors by -1?
