### ISSUE TITLE
It should be possible to use a setter for coords on a neighbor object

### ISSUE THREAD

**Issue by lnaglecocco** [materialsproject/pymatgen#2843]
**The problem**
If I get all the ligands around a central cation using the structure method `get_neighbors`:

```
ligands = structure.get_neighbors(core_site,3.0)
```
and I then want to change the position of one of these ligands, i.e.:

```
ligand = ligands[0]
new_coords = ligand.coords
new_coords[2] = new_coords[2] + 0.001
ligand.coords = new_coords 
```

An attribute error occurs. I may be mistaken, but I think this is because this is a neighbor object, not a PeriodicSite object, and the setter for `coords` doesn't apply to the PeriodicSite object which the neighbor object relates to.

**Describe the solution you'd like**
Neighbor objects should have a setter for coords which will update both themselves, and the coords for the PeriodicSite object they relate to.

Note that some thought will need to be given to periodicity. I.e., if a neighbor of the core_site occurs in a neighbouring unit cell, the new code needs to make sure that the new site coordinates are corrected to make sure the change occurs within the main unit cell, but in a way that will mean the version of the PeriodicSite occurring in the unit cell where the neighbor object occurs, will be in the location the user intends when setting the coords of the neighbor object.

**Describe alternatives you've considered**
End user could write more complex code than is necessary

**Comment by shyuep** [comment]
Well, Neighbors are essentially container objects that bypass some of the checks that PeriodicSite runs by default. It is meant to be a unchangeable storage. If you prefer sites that are modifiable, I suggest you convert the neighbor objects to site objects (the information are all the same, you just need to run PeriodicSite(...) with the correct parameters. After that, you can make as many changes as you wish. It is just a single line of code.
