### ISSUE TITLE
OPTIMADE client generates malformed queries

### ISSUE THREAD

**Issue by ml-evs** [materialsproject/pymatgen#2852]
**Describe the bug**
At some point, the OPTIMADE client in this repo was linted (presumably) and `f'?response_fields="{response_fields}"...'`  was replaced with `f'?response_fields={response_fields!r}'`, which generates query parameters with the wrong (according to the OPTIMADE spec, at least) kind of quotes:

https://github.com/materialsproject/pymatgen/blob/ebec8497c05055db3b78fec4c4bba75aaefb7839/pymatgen/ext/optimade.py#L316

This renders the client useless, as every request has such malformed queries.

I'm happy to fix this (will make a PR straightaway), but please let me know if this could be released before the end of the week --- if not I will have to adjust the pymatgen OPTIMADE tutorials that are being delivered at a conference on the 28th Feb.

**Comment by ml-evs** [comment]
(same thing also applies to string queries within the `filter` query parameter)

**Comment by janosh** [comment]
@ml-evs Sorry! That was my fault. We can definitely make a release before week's end. Thanks for #2853! 🙏

**Comment by ml-evs** [comment]
No problem, and thanks! Also found another bug where `chemical_formula_hill` was being passed incorrectly in queries (instead duplicating `chemical_formula_anonymous`).

My own client at https://www.optimade.org/optimade-python-tools/latest/getting_started/client/ is getting pretty mature and could probably integrated here... (already supports pymatgen Structure output, obeys all the standardized metadata we have for delaying requests, async queries over providers, custom callbacks for e.g., saving/storing in databases) Extra deps would be `httpx` and `rich`, could split it into a namespace package of `optimade-python-tools` if there is any interest.

**Comment by janosh** [comment]
> My own client at https://www.optimade.org/optimade-python-tools/latest/getting_started/client/ is getting pretty mature and could probably integrated here... (already supports pymatgen Structure output, obeys all the standardized metadata we have for delaying requests, async queries over providers, custom callbacks for e.g., saving/storing in databases)

That sounds great! 👍

**Comment by janosh** [comment]
> Extra deps would be `httpx` and `rich`, could split it into a namespace package of `optimade-python-tools` if there is any interest.

I recommend coordinating with @munrojm on that but I'd be happy to help/act as reviewer if we go ahead.
