### ISSUE TITLE
AttributeError in LinearAssignment.__init__(), pymatgen v. 2022.11.7, python 3.11.0

### ISSUE THREAD

**Issue by KMdraijer** [materialsproject/pymatgen#2855]
Novice at pymatgen and using the matgenb notebooks [(http://matgenb.materialsvirtuallab.org/)](url) to get familiar with the workflow.
When trying to use the function pymatgen.core.surface.generate_all_slabs, the following AttributeError is raise:
![image](https://user-images.githubusercontent.com/124170375/220292334-42171d03-fc3a-4349-a0b6-bc38eab49367.png)

I tried to find the bug in linear_assignment, the AttributeError refers to line 72:
```
# initialize solution vectors
  self._x = np.zeros(self.n, dtype=int) - 1
  self._y = self._x.copy()
```
However, I have not been able to resolve the bug.
Numpy is version 1.24.2

**Comment by shyuep** [comment]
Typically you will use the C version of linear assignment. This suggests that your pymatgen is not properly installed.
