### ISSUE TITLE
pymatgen units and math.sqrt

### ISSUE THREAD

**Issue by computron** [materialsproject/pymatgen#286]
I am playing with the pymatgen units class, which on the whole I find to be really nice.

I am having a problem with applying math.sqrt() on FloatWithUnit and am wondering why it is not supported.

i.e., this does not work:
```
from pymatgen.core.units import FloatWithUnit
import math
x = FloatWithUnit(9, "m^2 s^-2")
math.sqrt(x).unit
```

with the error
```
Traceback (most recent call last):
  File "/Users/ajain/PycharmProjects/scratch_work/scratch/scratch2.py", line 6, in <module>
    math.sqrt(x).unit
AttributeError: 'float' object has no attribute 'unit'
```

but this is fine:
```
from pymatgen.core.units import FloatWithUnit
x = FloatWithUnit(9, "m^2 s^-2")
(x**0.5).unit
```

**Comment by shyuep** [comment]
I don't think this is actually doable. With ** 0.5, the behavior is specified by the __pow__ magic function, which we can specify a behavior for the units. I have no idea what the math.sqrt function internally does to compute the sqrt. The same goes for math.pow and the functions.

**Comment by shyuep** [comment]
If you read the official docs for math.pow, it is explicitly stated that args and return values are converted to float for pow. Sqrt is probably the same. So I don't think there is a way beyond using ** for everything with units.
