### ISSUE TITLE
Add structure_property attribute to `Structure`

### ISSUE THREAD

**Issue by utf** [materialsproject/pymatgen#2884]
I'd like to add a `structure_property` attribute to the `Structure` class. Sometimes it is useful to have structure-wide properties that can be stored alongside the structure. One example is the `Poscar.predictor_corrector_preamble` which is necessary to write structures to continue MD simulations. Currently, only site-specific properties can be stored (e.g., the velocities and predictor-corrector coordinates).

With the present `Structure` class, it is not possible to store structures that can be used to continue MD simulations without storing this data separately which is quite unwieldy. I'm sure there are other instances where I've wanted to do this.

@shyuep would you support me adding this feature? The API would be the same as for adding site properties. E.g., 

```python
structure.add_structure_property("property_name", property_value)
```

This is related to https://github.com/materialsproject/atomate2/issues/185

**Comment by shyuep** [comment]
I don't see a big issue with it, but what is the difference with `structure.hello = "world"`?

**Comment by utf** [comment]
The only issue with setting properties like that is they won't be serialised through `structure.as_dict()`. I'd like the information to be serialised so that it could be stored in a database along side the structure and then used in future MD jobs.

**Comment by janosh** [comment]
Cool, just discovered this issue. I was also considering proposing this feature. The ability to store metadata on structures like DFT params used is one thing I like about `AseAtoms` that `pymatgen` is currently lacking. I think it could also really help with provenance which seems to be @utf's use case.

**Comment by arosen93** [comment]
@utf/@janosh, I would also really love this if it could be added eventually. I'm expecting something like `Structure.structure_properties` with a type `dict`.

**Comment by janosh** [comment]
Big open question is serialization. I think it would be straightforward to read and write `structure_properties` from/to JSON. Don't know enough about other formats like CIF, POSCAR, etc. whether they support this.

**Comment by arosen93** [comment]
I don't think it really has any relevance to the CIF or POSCAR. It should only be read/written out to JSON (or perhaps, pandas Dataframe as well but nobody really uses that I imagine).

**Comment by shyuep** [comment]
I would say this:
1. There are already structure properties (e.g., charge).
2. In effect, the Structure.properties dict would essentially be for "second class" properties that are deemed not important enough to be a first class Structure.charge like property.
3. I also think that using inspection, there would be a way to serialize a structure.hello = "world" property. Might be hard to do in a super robust way, but might solve all these problems once and for all.

In any case, I have no real objection to adding properties to Structure. (But pls do not call it `Structure.structure_properties`).

**Comment by janosh** [comment]
> But pls do not call it Structure.structure_properties).

Agreed. 😄
