### ISSUE TITLE
PDPlotter fails when there is no unstable entry

### ISSUE THREAD

**Issue by zhuyizhou** [materialsproject/pymatgen#2885]
**Describe the bug**
PDPlotter fails when there is no unstable entry.
This issue only occurs when using "plotly" as the backend. 'matplotlib' backend would work.

**To Reproduce**

```
from pymatgen.core import Composition
from pymatgen.analysis.phase_diagram import PhaseDiagram,PDEntry,PDPlotter

pd_entries = []
for name in ['Li','Co','O']:
    pde = PDEntry(Composition(name),0)
    pd_entries.append(pde)
pd = PhaseDiagram(pd_entries)   
plotter = PDPlotter(pd,backend='plotly',show_unstable=False)
plotter.get_plot().show()
```

**Comment by shyuep** [comment]
What is the error message?

**Comment by mattmcdermott** [comment]
This is definitely a bug that I noticed recently as well, and I am sorry -- I think it might be related to code I wrote a few years back. 

I have been meaning to fix and will try to address soon!

**Comment by janosh** [comment]
@mattmcdermott There's a strange swapping in the order of keys and values in the plot_data dicts here:

https://github.com/materialsproject/pymatgen/blob/c8f99910ce7dec0d1a47d4678becd7f942d0c6f7/pymatgen/analysis/phase_diagram.py#L3026-L3027

Coords as keys, entries as values, followed by entries as keys, coords as values. Is this by accident?
