### ISSUE TITLE
find_points_in_sphere() throws error regarding data type

### ISSUE THREAD

**Issue by jake-vikoren** [materialsproject/pymatgen#2887]
**Describe the bug**
"TypeError: a bytes-like object is required, not 'list'" is thrown when passing the appropriate types.
The doc string reads: "pbc: (list of bool) whether to set periodic boundaries" and I am passing a list of bools.
All other dtypes align with the requested types. 

**To Reproduce**

call pymatgen.core.neighbors.find_points_in_sphere() with the correct types ('pbc' as a list of bools).

Provide any example files that are needed to reproduce the error,
especially if the bug pertains to parsing of a file.

**Expected behavior**
The function should return:
index1 (n, ), index2 (n, ), offset_vectors (n, 3), distances (n, ). index1 of center_coords, and index2 of all_coords that form the neighbor pair
            offset_vectors are the periodic image offsets for the all_coords.

**Screenshots**

![Screen Shot 2023-03-10 at 15 56 27](https://user-images.githubusercontent.com/99913405/224426878-874453f6-f091-4471-90c6-82296a26a77f.png)
![Screen Shot 2023-03-10 at 15 57 03](https://user-images.githubusercontent.com/99913405/224426825-c547865a-144e-4169-8bde-8e929fca0976.png)

**Environment (please supply relevant versions and platform info):**

- OS: Mac
- Version: tested with (2022.3.7) and (2023.2.28)

**Comment by jake-vikoren** [comment]
Issue is resolved when defining pbc like:
pbc = np.array([1, 1, 1], dtype=int)

Recommend revising docstring to specify this required typing

**Comment by janosh** [comment]
I'm no Cython expert but I think #2907 should fix this error.
