### ISSUE TITLE
Lots of false energy messages in the entries returned through the new Materials project API

### ISSUE THREAD

**Issue by zifengdexiatian** [materialsproject/pymatgen#2888]
**Describe the bug**
When I use
from pymatgen.ext.matproj import MPRester
with MPRester('new_API_KEY') as mpr:
entries=mpr.get_entries_in_chemsys('Cs-Pb-I') 
to return all the entries, it contains obviously incorrect energy information, e.g. mp-540839-R2SCAN ComputedStructureEntry - Cs4 Pb4 I12 (CsPbI3)  Energy (Uncorrected) = -644.3128 eV (-32.2156 eV/atom), which does not match the search results directly on the MP website by a huge margin. This leads to a huge error in the calculation of e above hull. When I use the API_KEY of the old version of Materials project, the returned entries are accurate and the error disappears.

**screenshots**
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/83349433/224548778-0c72728c-6ebf-41ac-a48a-cf06ca95b0a8.png">
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/83349433/224548805-4bd61b85-fab0-4625-ab43-5000aa86f310.png">

**Environment (please supply relevant versions and platform info):**

- OS: both Mac M1 and windows11
- Version (Latest 2023.3.10)

**Comment by shyuep** [comment]
@munrojm I think this is for you.

**Comment by munrojm** [comment]
@zifengdexiatian which version of `mp-api` are you running with? I don't see this issue on my end with the most up to date client. Try updating with `pip install mp-api --upgrade` and see if the problem persists.

**Comment by zifengdexiatian** [comment]
> @zifengdexiatian which version of `mp-api` are you running with? I don't see this issue on my end with the most up to date client. Try updating with `pip install mp-api --upgrade` and see if the problem persists.

It worked, I upgraded mp-api from 0.29.8 to 0.30.1, thanks a lot !
