### ISSUE TITLE
Compilation on Windows with MSVC 2008.

### ISSUE THREAD

**Issue by madsipsen** [materialsproject/pymatgen#289]
[patches.zip](https://github.com/materialsproject/pymatgen/files/62412/patches.zip)
Hi,

I had some issues building pymatgen-3.2.8.tar.gz on windows using Python 2.7.2 and MSVC 2008.

1. The spglib C files do not have topmost variable declarations. Trick used to was to rename all .c files to .cpp files:

   find -name '*.c' | xargs -i mv {} {}pp

in the /dependencies/spglib-1.7.4 directory.

2. The spglib file refinements.cpp need sqrt(3) changed to sqrt(3.0) to work with MSVC 2008.

3. setup.py must be patched to use .cpp instead of .c (diff attached).

4. The SOURCES.txt contains src file entries that are not in the src tree (diff attached).

5. Updating to newer version works fine on Ubuntu 14.04. But on Windows it fails:

python -measy_install -U pymatgen

Searching for pymatgen
Reading https://pypi.python.org/simple/pymatgen/
Best match: pymatgen 3.2.9
Downloading https://pypi.python.org/packages/source/p/pymatgen/pymatgen-3.2.9.tar.gz#md5=9373a9943a956c4a4d910b90b42bc5e7
Processing pymatgen-3.2.9.tar.gz
Writing c:\cygwin64\tmp\easy_install-vnhubw\pymatgen-3.2.9\setup.cfg
Running pymatgen-3.2.9\setup.py -q bdist_egg --dist-dir c:\cygwin64\tmp\easy_install-vnhubw\pymatgen-3.2.9\egg-dist-tmp-kfqswp
error: c:\cygwin64\tmp\easy_install-vnhubw\pymatgen-3.2.9\pymatgen.egg-info\SOURCES.txt: The process cannot access the file because it is being used by another process

**Comment by shyuep** [comment]
Hi, unfortunately we cannot support all the different compilers. I have discussed with the spglib author and we think it's best if you use standard gcc to compile this.
