### ISSUE TITLE
str.join() error

### ISSUE THREAD

**Issue by jchelle** [materialsproject/pymatgen#2893]
Error that occurs:
"TypeError: str.join() takes eactly one argument (2 given)"

I am gettting this error while trying to run "Gaussian_input.write_file(paramset=paramset, mol=mol)" where both the paramset and mol are correct inputs. Paramset includes the route parameters, and none otherwise, and the mol is an xyz string.

I believe there may be an issue where in pymatgen.io.gaussian.py on line 423,
" ".join(site.species_string, " ".join([to_s(j) for j in site.coords])),
everything within the external join function needs to be in brackets.

**Comment by janosh** [comment]
I believe this was already fixed in https://github.com/materialsproject/pymatgen/pull/2891.

But the code could still be improved. There's no reason to use join in the first place if it's just 2 items.

**Comment by gVallverdu** [comment]
@janosh yes , it could be just a string concatenation.
