### ISSUE TITLE
Wulff plot not working

### ISSUE THREAD

**Issue by cedenoruel** [materialsproject/pymatgen#2900]
**The Bug**

The wulff.show() function which normally gives a static plot no longer works. 
Instead, it returns `<Figure size 576x576 with 0 Axes> `
However,  wulff.get_plotly() works (which gives an interactive plot).

**To Reproduce**
```
!pip install pymatgen
# Import the neccesary tools to generate surfaces
from pymatgen.core.surface import SlabGenerator, generate_all_slabs, Structure, Lattice
# Import the neccesary tools for making a Wulff shape
from pymatgen.analysis.wulff import WulffShape

lattice = Lattice.cubic(3.508)
Ni = Structure(
    lattice,
    ["Ni", "Ni", "Ni", "Ni"],
    [[0, 0, 0], [0, 0.5, 0], [0.5, 0, 0], [0, 0, 0.5]],)
surface_energies_Ni = {
    (3, 2, 0): 2.3869,
    (1, 1, 0): 2.2862,
    (3, 1, 0): 2.3964,
    (2, 1, 0): 2.3969,
    (3, 3, 2): 2.0944,
    (1, 0, 0): 2.2084,
    (2, 1, 1): 2.2353,
    (3, 2, 2): 2.1242,
    (3, 2, 1): 2.3183,
    (2, 2, 1): 2.1732,
    (3, 3, 1): 2.2288,
    (3, 1, 1): 2.3039,
    (1, 1, 1): 1.9235,
}
miller_list = surface_energies_Ni.keys()
e_surf_list = surface_energies_Ni.values()

# We can now construct a Wulff shape with an accuracy up to a max Miller index of 3
wulffshape = WulffShape(Ni.lattice, miller_list, e_surf_list)

# Let's get some useful information from our wulffshape object
print(
    "shape factor: %.3f, anisotropy: \
%.3f, weighted surface energy: %.3f J/m^2"
    % (
        wulffshape.shape_factor,
        wulffshape.anisotropy,
        wulffshape.weighted_surface_energy,
    )
)


# If we want to see what our Wulff shape looks like
wulffshape.show()

```

- OS: (Windows 10)
- Platform: Google Colab

**Comment by janosh** [comment]
Bug confirmed.

@CifLord Are you familiar with this code? If you have time, maybe you could take look?

**Comment by CifLord** [comment]
Yeah I can take a look, that's for letting me know!

**Comment by CifLord** [comment]
Made a pull request to fix this. @cedenoruel do you know what version of matplotlib you're using? If its 3.6.0 or higher, its not compatible with the Wulffshape plotter. In any case, the pull request should fix the compatibility issue now

**Comment by cedenoruel** [comment]
> Made a pull request to fix this. @cedenoruel do you know what version of matplotlib you're using? If its 3.6.0 or higher, its not compatible with the Wulffshape plotter. In any case, the pull request should fix the compatibility issue now

Now, it's working again.  Thank you very much.
