### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'vasprun.xml'

### ISSUE THREAD

**Issue by yerdna23** [materialsproject/pymatgen#2911]
I can't get past the line:
run = BSVasprun("vasprun.xml", parse_projected_eigen=True)

 of  notebook 2013-01-01-Bandstructure of NiO

**Comment by shyuep** [comment]
I think the error message is quite clear that you do not have vasprun.xml file?

**Comment by yerdna23** [comment]
But if I have it, what happens is that I don't know where to put it. A Now that file is in a subfolder of pymatgen, test_files

**Comment by yerdna23** [comment]
> I think the error message is quite clear that you do not have vasprun.xml file?
But if I have it, what happens is that I don't know where to put it. A Now that file is in a subfolder of pymatgen, test_files

**Comment by yerdna23** [comment]
> I think the error message is quite clear that you do not have vasprun.xml file?

Ok, thanks i think that  was a problem of installation.
