### ISSUE TITLE
Molecule.from_file cannot read .xyz file from stk

### ISSUE THREAD

**Issue by KP-303** [materialsproject/pymatgen#2917]
I have a .xyz file generated by stk and when I try and create a molecule from it I get the following error:

IndexError: list index out of range

Maybe stk writes .xyz files in a format that isn't quite standard? 

Input code:
test_mof=Molecule.from_file("test.xyz")

Full error messages:

File "test.py", line 54, in <module>
    test_mof=Molecule.from_file("test.xyz")
  File ".../pymatgen/core/structure.py", line 3314, in from_file
    return cls.from_str(contents, fmt="xyz")
  File ".../pymatgen/core/structure.py", line 3276, in from_str
    m = XYZ.from_string(input_string).molecule
  File ".../site-packages/pymatgen/io/xyz.py", line 46, in molecule
    return self._mols[-1]
IndexError: list index out of range

The .xyz file is as follows (I renamed it as test.txt rather than test.xyz so I could attach it):
[test.txt](https://github.com/materialsproject/pymatgen/files/11092277/test.txt)

Thanks

**Comment by fraricci** [comment]
here you can see an example of what the Molecule.from_file() can read
https://github.com/materialsproject/pymatgen/blob/master/test_files/multiple_frame_xyz.xyz

**Comment by KP-303** [comment]
It works now thanks!
