### ISSUE TITLE
Pourbaix digram entry with a wrong composition

### ISSUE THREAD

**Issue by johanzhuohan** [materialsproject/pymatgen#2943]
**Describe the bug**
[Related matsci post](https://matsci.org/t/47247)

The Pourbaix diagram sometimes includes the multientry with a different composition than the one initially used to generate the pourbaix diagram. This only occurs for some initial compositions. What could be the reason for this?

Also, in the example shown in the attached screenshot, the multientry includes both Fe(s) and Fe[+2] at the same time. It looks unphysical, but could this be a bug in the code?

**To Reproduce**
```py
ELEMENTS_HO = {Element("H"), Element("O")}
chem_sys = 'Fe-Ir-Li-Si-V'
pourbaix_entries = mpr.get_pourbaix_entries(chemsys=chem_sys)
pourbaix_elem = [Element(elem) for elem in chem_sys.split('-')]

conc_dict = {}
for elem in pourbaix_elem:
    conc_dict[elem.symbol] = 1e-6

comp_dict = Composition({Element('Fe'): 1, Element('Ir'): 1, 
             Element('Li'): 2, Element('Si'): 1, Element('V'): 2, }).fractional_composition
print(comp_dict)

pbx = PourbaixDiagram(pourbaix_entries, comp_dict=comp_dict, conc_dict = conc_dict)
pbx_comp = Composition(pbx._elt_comp).fractional_composition
print(pbx_comp)
for multientry in pbx.all_entries:
    entry_pbx_comp = Composition(
        {elt: coeff for elt, coeff in multientry.composition.items() if elt not in ELEMENTS_HO}
    ).fractional_composition
    if entry_pbx_comp != pbx_comp:
        print(multientry)
        print(entry_pbx_comp)
        exit()
```

**Screenshots**

![2849e376d2129a2a03474c1f8361d7f27ed28640_2_690x423](https://user-images.githubusercontent.com/25890520/232914506-c3fb2b57-46b2-429a-bd0f-c891849b1ff8.png)

**Comment by janosh** [comment]
@rkingsbury Could you take a look? Not familiar with the `PourbaixDiagram` myself.

@johanzhuohan Please post code snippets in the future. They are much more usable than screenshots.

**Comment by johanzhuohan** [comment]
Sure! I was not quite sure how to insert the code, but I will do that next time!

**Comment by rkingsbury** [comment]
Hi @johanzhuohan , thanks for reporting this. To be honest I'm not entirely sure, but I agree with you that it does seem odd to get a MultiEntry whose composition is so different from the specified `comp_dict`.

If there is a bug, I think it probably resides in [this section of code](https://github.com/materialsproject/pymatgen/blob/713740f5b8bf27990d9d0c92ca154fae4164ec59/pymatgen/analysis/pourbaix_diagram.py#L709). Maybe you can scrutinize that and see if you can find anything? 

This code contains the following comment
```
# Get balanced reaction coeffs, ensuring all < 0 or conc thresh
            # Note that we get reduced compositions for solids and non-reduced
            # compositions for ions because ions aren't normalized due to
            # their charge state.
```

But I don't see where/how this actually happens, i.e., it seems like all entries (ion or solid) simply use their `.composition` attribute. So maybe there is some issue there?

@montoyjh do you have any insight into this?

**Comment by rkingsbury** [comment]
Thanks for investigating @montoyjh . Pinging @mattmcdermott as I think he's quite familiar with the `Reaction` class.

**Comment by mattmcdermott** [comment]
I am not an avid user of pymatgen's Pourbaix diagrams, but my first take is that this might be a misuse of the functionality of the `Reaction` class (at least from a programming point of view). If we wanted to be very proper, we should probably make a new reaction class that takes in `Species` objects instead of `Composition` objects.

That being said, there has always been a sort of a gray area with using the `Reaction` class when you have duplicated compositions anyway, such as this one:
```python
rxn = Reaction([Composition("Fe2O3"), Composition("Fe"), Composition("O")], [Composition("Fe"), Composition("O")])
print(rxn)
```
```
Fe2O3 + Fe + 0.5 O2 -> 3 Fe + 2 O2
```
So this is more of a general problem anyway with using the `Reaction.get_coeff` method.

@montoyjh, if your fix is working fine for the Pourbaix functionality, I don't see any problems with it.

**Comment by montoyjh** [comment]
> I am not an avid user of pymatgen's Pourbaix diagrams, but my first take is that this might be a misuse of the functionality of the `Reaction` class (at least from a programming point of view). If we wanted to be very proper, we should probably make a new reaction class that takes in `Species` objects instead of `Composition` objects.

Agreed - an ion-compatible reaction class would more accurately model our use-case, and we're abusing the current one here in order to avoid duplicating code for stoichiometry solvers.
