### ISSUE TITLE
Entry sets use wrong Yb pseudo-potential

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#2968]
[The docs](https://docs.materialsproject.org/methodology/mof-methodology/calculation-parameters/psuedopotentials) are incorrect on what pseudo-potential the `EntrySet`s use for `Yb`. Docs say `Yb_3`, actual is `Yb_2`. Just to list a few:

https://github.com/materialsproject/pymatgen/blob/a7ee5adf02e0ac8c0b9e150d10f631bd61f6b5de/pymatgen/io/vasp/MPRelaxSet.yaml#L171

https://github.com/materialsproject/pymatgen/blob/a7ee5adf02e0ac8c0b9e150d10f631bd61f6b5de/pymatgen/io/vasp/MPSCANRelaxSet.yaml#L123

https://github.com/materialsproject/pymatgen/blob/a7ee5adf02e0ac8c0b9e150d10f631bd61f6b5de/pymatgen/io/vasp/MVLRelax52Set.yaml#L177

https://github.com/materialsproject/pymatgen/blob/a7ee5adf02e0ac8c0b9e150d10f631bd61f6b5de/pymatgen/io/vasp/MPAbsorptionSet.yaml#L113

The A-lab revealed that as a result of using `Yb_2` the energy on Yb compounds is off by a lot, resulting in supposedly stable things being unsynthesizable. While an unfortunate mistake, it's also great to see how experiment can help surface simulation errors. (@rekumar) (Although if tales are correct, @arosen93 originally brought this up with @mkhorton in Oct 2021?)

Planned solution is to update all input sets to actually use Yb_3. Why not `Yb` so as not to force an oxidation state? Apparently `Yb` has stability issues. Additional context in
- https://github.com/materialsproject/atomate2/pull/27#issuecomment-986306566 
- https://www.vasp.at/forum/viewtopic.php?t=18367

@shyuep Any concerns on your end? We plan to highlight this change in the pymatgen release notes and in the next MP database release. Any additional venues?

Unfortunately, this comes too late for the large data set Google generated which used the current `MPRelaxSet` and `MPSCANRelaxSet` but better fix this now before another large effort gets this wrong.

**Comment by janosh** [comment]
[This docs page](https://docs.materialsproject.org/methodology/materials-methodology/calculation-details/gga+u-calculations/pseudopotentials) needs updating. It incorrectly states we use `Yb`. It even lists "thermo data off with Yb_2" as the reason not to use `Yb_2` even though VASP recommends. 🤦

**Comment by shyuep** [comment]
The docs page need to be updated for sure. But the docs seem to be based on the old HT framework at MIT. When we did MP, there was a deliberate change in PSP used. Anyway, like I said, no issue with switching to Yb3+.

**Comment by janosh** [comment]
@munrojm Change request [for docs page](https://docs.materialsproject.org/methodology/materials-methodology/calculation-details/gga+u-calculations/pseudopotentials) submitted on gitbooks.

**Comment by munrojm** [comment]
@janosh merging now

**Comment by mkhorton** [comment]
> Although if tales are correct, @arosen93 originally brought this up with @mkhorton in Oct 2021?

I don’t recall, but I believe it. The consequence of changing the MP Input Set is that current data on MP will the  be inconsistent with the MP Input Set; since a lot of people generate data intentionally to be compatible with MP, this can cause a lot of downstream problems (even in this case, where the change is sensible and necessary).

Around that time we were also talking about reviewing other pseudopotential choices in MP, eg some pseudopotentials we’re not used because of ghost states (perhaps Na? I forget), but these issues were later fixed in the newer 54 pseudopotentials that the MP SCAN Input Set uses. The SCAN Input Set presented an opportunity to cleanly make this change. However this was not pursued, I think more out of conservativeness than anything.

All this to say, I’m glad this change was made, but if I could offer a viewpoint to the MP team, it’s that a new data release to replace the Yb data should also be done promptly (although I realise this may not be possible!), as well as a louder mention of this change in the relevant places (eg docs changelog, or a banner on the linked docs page) might be a good idea too, to let people know this change is coming.

**Comment by munrojm** [comment]
Just an FYI for everyone here that I am moving to re-calculate all the Yb compounds right now. The plan is to stop working on the current MP build to get these done and incorporated.

**Comment by janosh** [comment]
> as well as a louder mention of this change in the relevant places (eg docs changelog, or a banner on the linked docs page) might be a good idea too, to let people know this change is coming.

Yes this is definitely planned! 👍 

> new data release to replace the Yb data should also be done promptly (although I realise this may not be possible!)

This is also planned but the timeline is less firm.

**Comment by janosh** [comment]
Lol, simultaneous posts. 😄 

I stand corrected. Timeline for updating Yb compounds is _very_ firm. 🚀

**Comment by janosh** [comment]
@mkhorton Any suggestions for this banner on the [PSP docs page](https://docs.materialsproject.org/methodology/materials-methodology/calculation-details/gga+u-calculations/pseudopotentials)?

![Screenshot 2023-05-02 at 15 14 49](https://user-images.githubusercontent.com/30958850/235797654-5d9138d7-72fe-401f-9ea5-f1b65ecee2f1.png)

**Comment by mkhorton** [comment]
Looks perfect :)

**Comment by mkhorton** [comment]
Perhaps additional information to add somewhere might simply be some screenshots or descriptions of the two relevant chemical systems to demonstrate the difference. It might help justify the change, rather than "because we say so", as well as point(s)-of-contact for who investigated the issue. I say this as someone who's wished this information was available with previous decisions, but where I was unable to track down additional context.

**Comment by janosh** [comment]
> ...well as point(s)-of-contact for who investigated the issue. I say this as someone who's wished this information was available with previous decisions, but where I was unable to track down additional context.

Definitely! That's the reason I tried to @-mention all people I know have knowledge of this matter in the original issue above. I made sure all places documenting this change link back to this issue so hopefully people in the future can follow the trail to determine who to contact with questions. What I wrote above is most of the context I have. Of course, others are welcome to add.

Another tidbit I learned later is that prompted by A-lab results, @mattmcdermott very recently tried to re-run a bunch of `Yb` compounds (< 10?) using `Yb` instead of `Yb_2`. All of them failed, corroborating the claim that the `Yb` PSP is not usable in high throughput.

**Comment by mattmcdermott** [comment]
@janosh yep, I ran 20ish compounds with the `Yb` pseudopotential that all failed (including Yb2O3, Yb, Yb2MoO6..) I am not a great VASP debugger but i was getting `PotimErrorHandler` and `PositiveEnergyErrorHandler` in custodian. Eventually every job fizzled after reaching a maximum of 5 errors

**Comment by mattmcdermott** [comment]
Also I meant to send this earlier -- this is not the most rigorous comparison, but here is a look at the Yb-Mo-O phase diagram (GGA/GGA+U) before and after I recomputed the Yb entries with the `Yb_3` pseudopotential and applied previously fitted corrections (i.e., oxide, +U corrections). 

Big differences -- notably, the very common Yb2O3 moves to be stable after previously being >200 meV/atom above the hull. Also stabilizes two ternary phases and destabilizes YbMoO4 greatly

![Screenshot 2023-05-03 at 4 52 34 PM](https://user-images.githubusercontent.com/40469694/236075391-6230e3e6-f723-4d5f-a71b-4ffd6175cb1b.png)
![Screenshot 2023-05-03 at 4 49 16 PM](https://user-images.githubusercontent.com/40469694/236075419-702c6f6c-f54c-4fd0-be5d-44a15064c8f4.png)

**Comment by chiang-yuan** [comment]
I don't know if I am experienced enough for this conversation, but I was able to get YbCl3 relaxation converged using `Yb_3` recently. But it is difficult to get YbCl2 converged and the formation energy is quite off from the experimental value. One possible reason our lab found might be the nonmagnetic state the system gets converged to but they should be converged to magnetic state.

**Comment by janosh** [comment]
> I don't know if I am experienced enough for this conversation

Any and all relevant anecdotes are welcome! The more data we have, the better our decisions.
