### ISSUE TITLE
Bug in `DictSet.kpoints` due to operator precedence

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#2970]
@shyuep I think there's a subtle operator precedence bug here:

https://github.com/materialsproject/pymatgen/blob/ed66c977d8c2c1168a9945d64f5d043d9263fc43/pymatgen/io/vasp/sets.py#L633-L638

`and` has higher precedence than `or` but unless I'm mistaken we actually want to evaluate the `or` first. The thing that throws me off is why this wasn't caught before.

```py
if (
    self.user_incar_settings.get("KSPACING") or self._config_dict["INCAR"].get("KSPACING")
) and self.user_kpoints_settings == {}:
```

**Comment by shyuep** [comment]
I agree. I did not write this though. I think the switch to KSPACING is relatively recent.
