### ISSUE TITLE
CompleteCohp.cohp and CompleteCohp.icohp produce the same output

### ISSUE THREAD

**Issue by QuantumChemist** [materialsproject/pymatgen#2985]
When trying to access the cohp and the icohp feature of CompleteCohp for a COHPCAR.lobster file, one gets the same output. In the following minimal code, the sum is 0 (and also the individual entries for each energy point is 0).

## Minimal code to reproduce the issue

cohp_test = CompleteCohp.from_file(filename="path_to_files/COHPCAR.lobster", fmt = 'LOBSTER', structure_file="path_to_files/POSCAR")

cohp = cohp_test.cohp[Spin.up]
icohp = cohp_test.icohp[Spin.up]

print(sum(icohp-cohp))

**Comment by QuantumChemist** [comment]
Totally forgot to tag @JaGeo  :D

**Comment by JaGeo** [comment]
Thanks for writing it down! I will work on a fix as soon as I get to it. I never use the average COHP/ICOHP. 😅

**Comment by JaGeo** [comment]
Can be closed then, @janosh or @QuantumChemist

**Comment by janosh** [comment]
@JaGeo Thanks. Btw, if you include "closes #issue-number" or "fixes #issue-number" in the PR description or any commit message, the issue will be auto-closed on merge.

**Comment by JaGeo** [comment]
@janosh I think I actually did this but it did not auto-close. Do you see what I did wrong?

**Comment by janosh** [comment]
I edited the PR description. 😄

**Comment by JaGeo** [comment]
> I edited the PR description. 😄

🙃 I see.

**Comment by YuanbinLiu** [comment]
> 

Brilliant! Thanks!
