### ISSUE TITLE
 `AseAtomsAdaptor.get_atoms(structure, **kwargs)` compares numpy boolean array wtith python nested list.

### ISSUE THREAD

**Issue by chiang-yuan** [materialsproject/pymatgen#3011]
**Describe the bug**

`AseAtomsAdaptor.get_atoms(structure, **kwargs)` checks numpy boolean array against python nested list. This is a bug similar to my previous PR (#2951). 

https://github.com/materialsproject/pymatgen/blob/233070151070c0d839ebb23d93afc6f17540e760/pymatgen/io/ase.py#L107-L111

The `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()` can be reproduced by reading `CONTCAR` with `selective_dynamics`. 

This can be bypassed temporarily by converting `poscar.selective_dynamics` back to nested list `poscar.selective_dynamics = [list(x) for x in poscar.selective_dynamics] ` Will look into this and submit pr later.

**Comment by janosh** [comment]
Thanks for reporting! Minimal code to trigger the error:

```py
import numpy as np

from pymatgen.core import Lattice, Structure
from pymatgen.io.ase import AseAtomsAdaptor

structure = Structure(
    lattice=Lattice.cubic(5),
    species=("Fe", "O"),
    coords=((0, 0, 0), (0.5, 0.5, 0.5)),
    site_properties={"selective_dynamics": np.array([True, True, True])},
)

ase_atoms = AseAtomsAdaptor.get_atoms(structure)
>>> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

Should be easy to fix using `np.all and not np.any` instead of list comparisons.
