### ISSUE TITLE
InputSet looks for wrong W POTCAR when using PBE_54

### ISSUE THREAD

**Issue by kyledmiller** [materialsproject/pymatgen#3016]
**Describe the bug**
When creating an input set using the PBE_54 POTCAR setting, the code looks for the non-existent W_pv POTCAR. [This has been replaced by W_sv in the 5.4 version.](https://www.vasp.at/wiki/index.php/Available_PAW_potentials#Recommended_potentials_for_DFT_calculations)

**To Reproduce**
1. Establish PBE_54 POTCAR directory
2. Set `PMG_DEFAULT_FUNCTIONAL: 'PBE_54'` in `~/.pmgrc.yaml`
3. Run the following
```
from pymatgen.core.structure import Structure
from pymatgen.io.vasp.sets import MPStaticSet

struc = Structure.from_str(
"""
# generated using pymatgen
data_Sb2WO6
_symmetry_space_group_name_H-M   'P 1'
_cell_length_a   4.97452257
_cell_length_b   5.55751792
_cell_length_c   9.25434909
_cell_angle_alpha   83.52945128
_cell_angle_beta   90.00000000
_cell_angle_gamma   90.00000000
_symmetry_Int_Tables_number   1
_chemical_formula_structural   Sb2WO6
_chemical_formula_sum   'Sb4 W2 O12'
_cell_volume   254.21595972
_cell_formula_units_Z   2
loop_
 _symmetry_equiv_pos_site_id
 _symmetry_equiv_pos_as_xyz
  1  'x, y, z'
loop_
 _atom_site_type_symbol
 _atom_site_label
 _atom_site_symmetry_multiplicity
 _atom_site_fract_x
 _atom_site_fract_y
 _atom_site_fract_z
 _atom_site_occupancy
  Sb  Sb0  1  0.44927320  0.38866033  0.16812494  1
  Sb  Sb1  1  0.04965522  0.88677808  0.16648034  1
  Sb  Sb2  1  0.94927320  0.61133967  0.83187506  1
  Sb  Sb3  1  0.54965522  0.11322192  0.83351966  1
  W  W4  1  0.03740281  0.24401928  0.50864705  1
  W  W5  1  0.53740281  0.75598072  0.49135295  1
  O  O6  1  0.77952180  0.53470618  0.44201347  1
  O  O7  1  0.72535535  0.03497081  0.44056689  1
  O  O8  1  0.22535535  0.96502919  0.55943311  1
  O  O9  1  0.27952180  0.46529382  0.55798653  1
  O  O10  1  0.84957778  0.23617072  0.68715870  1
  O  O11  1  0.14248836  0.26735019  0.31118039  1
  O  O12  1  0.64248836  0.73264981  0.68881961  1
  O  O13  1  0.34957778  0.76382928  0.31284130  1
  O  O14  1  0.18624167  0.61241876  0.06049465  1
  O  O15  1  0.31939681  0.11002430  0.06444027  1
  O  O16  1  0.68624167  0.38758124  0.93950535  1
  O  O17  1  0.81939681  0.88997570  0.93555973  1
  """, fmt='cif')

inputs = MPStaticSet(struc, user_potcar_functional = 'PBE_54')
inputs.write_input('W_bugtest')
```

**Expected behavior**
Look for W_sv POTCAR

**Environment (please supply relevant versions and platform info):**
- OS: Ubuntu 18
- 2023.3.23 via pip

**Comment by JaGeo** [comment]
Yes, this is definitely true. I fixed it within the LobsterSet by replacing the standard value.

**Comment by janosh** [comment]
I'm open to changing to `W_sv`. It would need adequate highlighting in the change logs and GH release language similar to #2969. Plus we'd need to [update the docs](https://docs.materialsproject.org/methodology/materials-methodology/calculation-details/gga+u-calculations/pseudopotentials) which correctly state we're using `W_pv` on pre-5.4 input sets.

@mkhorton What's your take?

**Comment by JaGeo** [comment]
`W_sv` does not exist in pre-5.4 postcars. `W_pv` not in 5.4 potcars. There is no real alternative.

**Comment by JaGeo** [comment]
Mh. I see. This would lead to errors with the pre-5.4 potcars. Also, it would not be consistent with all previous computations.

**Comment by arosen93** [comment]
I agree with @JaGeo. Basically, `MPRelaxSet` can _only_ be used with the original (no v.54) PAW PBE potentials, as that's part of its definition.

Assuming the question is independent of the MP sets, which it sounds like it is, then I think it's just a matter of making sure `W_sv` isn't selected when a .54 PAW PBE potential set is requested.

**Comment by JaGeo** [comment]
Is it possible to add a warning when switching to newer potcars. It could describe the compatibility issues and the required potcar updates (e.g., for W)

**Comment by janosh** [comment]
I'm happy to help implement what everyone thinks it's best. But I'm wary of warnings. In my opinion, pymatgen already issues too many warnings. If there's a sensible default where Pymatgen just does the right thing given the context, I think we should implement that.

**Comment by kyledmiller** [comment]
> I agree with @JaGeo. Basically, `MPRelaxSet` can _only_ be used with the original (not v.54) PAW PBE potentials, as that's part of its definition.
> 
> Assuming the question is independent of the MP sets, which it sounds like it is, then I think it's just a matter of making sure `W_sv` isn't selected when a .54 PAW PBE potential set is requested. This wouldn't involve changing any MP input sets (you can see that [MPSCANRelaxSet](https://github.com/materialsproject/pymatgen/blob/32436a6c18332021de4238b6c76e627e7965fbaf/pymatgen/io/vasp/MPSCANRelaxSet.yaml#L120) already has `W: W_sv`).

I understand that for compatibility/consistency the original PBE potentials are necessary, but I don't think that's the only intended use of `MPRelaxSet`, right? If you are allowed to specify `user_potcar_functional='PBE_54'` when instantiating an MPRelaxSet, it seems like the code should automatically search for W_sv since it's the only W potential in 5.4. The user is already asking explicitly for 5.4 POTCARs so they know that they are deviating from the MP standard.

**Comment by kyledmiller** [comment]
Oh, yes, I misinterpreted that first sentence. You were stating the status quo (which we are hoping to change), not the expected behavior. Yes, this fix should definitely not affect any of the default input settings. Thanks for the rapid response!

**Comment by JaGeo** [comment]
Then, I think simply implementing the correct W POTCAR for the 5.4 Potcars sounds like the best option.

**Comment by JaGeo** [comment]
@janosh we can then also close this one here: https://github.com/materialsproject/pymatgen/issues/1707 😅

**Comment by janosh** [comment]
If y'all could take a very _careful_ look at #3022 to make sure, I didn't miss or break anything, I'd be much obliged! I'm always nervous when changing VASP input settings.

**Comment by arosen93** [comment]
If I forget to respond by tomorrow, please ping me with a reminder!
