### ISSUE TITLE
`if self.bandgap == 0` is probably not the best in `MPScanRelaxSet`

### ISSUE THREAD

**Issue by arosen93** [materialsproject/pymatgen#3023]
https://github.com/materialsproject/pymatgen/blob/3c91e69838500120cf62032037324f88defcb1a4/pymatgen/io/vasp/sets.py#L949-L952

This checks if `bandgap` is strictly equal to zero, but there are likely going to be edge cases where `bandgap` is some very small value (say, 1e-6 eV) that should also be flagged as metallic. It'd probably be better to do `if self.bandgap < tol` where `tol` is something like `1e-4`.

CC @janosh, @rkingsbury

**Comment by rkingsbury** [comment]
Makes sense to me @arosen93 . I didn't know much about the robustness of bandgap detection when I wrote this.
