### ISSUE TITLE
`site.specie` in `Structure.species` should be changed to `site.species`

### ISSUE THREAD

**Issue by exenGT** [materialsproject/pymatgen#3033]
The code below
```
print(struct.species)
```
yields the error
```
  File ~/miniconda3/envs/chem/lib/python3.9/site-packages/pymatgen/core/structure.py:248 in <listcomp>
    return [site.specie for site in self]
  File ~/miniconda3/envs/chem/lib/python3.9/site-packages/pymatgen/core/sites.py:75 in __getattr__
    raise AttributeError(attr)
AttributeError: specie
```
The pymatgen version is 2023.5.10.

**Comment by exenGT** [comment]
```
Traceback (most recent call last):
  File ~/miniconda3/envs/chem/lib/python3.9/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)
  File ~/Rafael_project/codes/test.py:18
    Structure.to("gh-3033.json")
  File ~/miniconda3/envs/chem/lib/python3.9/site-packages/pymatgen/core/structure.py:2549 in to
    raise ValueError(f"Invalid format: `{str(fmt)}`")
ValueError: Invalid format: ``
```

**Comment by janosh** [comment]
Sorry, should have been more clear. The `to` method needs to be called on the `struct` instance, not the class itself.

**Comment by janosh** [comment]
So there's no `AttributeError `?

**Comment by exenGT** [comment]
Sorry, I need to clarify, there is still `AttributeError` with the original code. After I changed the code in core/structure.py the error disappeared.

**Comment by janosh** [comment]
Again, please post the structure so I can reproduce.

**Comment by exenGT** [comment]
After some testing I now know why. My IDE somehow messed up the python interpreter it uses. Running your code on the command line yields no error. (#3034 as well)

**Comment by exenGT** [comment]
This issue occurs again with the following test code:
```
from pymatgen.core import Lattice, Structure

structure = Structure(
    lattice=Lattice.cubic(3),
    species=[{"Fe": 0.5, "Mn": 0.5}, {"Fe": 0.5, "Mn": 0.5}],
    coords=((0, 0, 0), (0.5, 0.5, 0.5)),
)
print(structure.species)
```

**Comment by exenGT** [comment]
I found that the property `species_and_occu` in class `Structure` does what I thought `species` should do. Therefore, it seems this is not a bug but a feature.
