### ISSUE TITLE
Add a `Structure.calculate()` feature analagous to `Structure.relax`

### ISSUE THREAD

**Issue by arosen93** [materialsproject/pymatgen#3043]
Currently, there is a method to do `Structure.relax` which calls an ASE calculation with the ASE Optimizer class. There should be a similar method called `Structure.run` which calls ASE to run `atoms.get_potential_energy()`. This will allow for the use of the calculator's internal optimizers if the user wishes.

I can add this.

**Comment by janosh** [comment]
That sounds great! Let me know if I can help with tests or reviewing.

**Comment by arosen93** [comment]
I'll definitely be adding plenty of tests, but would love help with reviewing when I'm done! And probably fixing mypy issues...
