### ISSUE TITLE
breaking change since v3.3.2

### ISSUE THREAD

**Issue by dwinston** [materialsproject/pymatgen#305]
This is perhaps only of interest to those using serialized pymatgen structures in database/web applications, but 170a2b0c9dab863ff6f715ddf33f460f600ef5ef introduced a breaking change where two keys ("xyz", "label") usually included in the output of `pymatgen.core.sites.PeriodicSite.as_dict` are now elided in favor of requiring the caller to pass in a non-default `verbosity` kwarg value.

I'm filing this issue so that anyone who needs to make changes to their code downstream (as I did) has the above information for reference.

**Comment by shyuep** [comment]
Hmm... but in general, sites are serialized from Structure. So this shouldn't have affected the output at all?

**Comment by dwinston** [comment]
In general, yes, but I was using a `pymatgen.alchemy.materials.TransformedStructure`. :)

**Comment by dwinston** [comment]
Ah, I see. I think my recent commit f0395cce5fe3e1ba9da76f014c42ced10b5a02f3 may have been a bug-fix and not just cosmetic. Pushing a release with that may fix the regression. Structure passes verbosity=1 by default to the site serializer, but as currently released, the site serializer needs verbosity=2 or higher to do it's thing.

**Comment by shyuep** [comment]
ok, thanks.
