### ISSUE TITLE
Replace `m3gnet` optional dependency with `matgl`

### ISSUE THREAD

**Issue by arosen93** [materialsproject/pymatgen#3051]
This is just a tracker to keep tabs on it. It is my understanding that `matgl` is the new standard repo to use if you want a pre-trained m3gnet model.

~Note: From looking at the `matgl` `setup.py` file, there might be a file path or two that might cause issues on Windows. Also, the pinned versions in the `setup.py` probably aren't ideal. Might be better to propose a change such that `requirements.txt` has pinned versions but `setup.py` has minimal pins.~

**Comment by shyuep** [comment]
This is done (I hope).
