### ISSUE TITLE
Ase in optional requirement vs. ase import in pymatgen.core.structure

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/pymatgen#3061]
#### Description

I installed pymatgen today and tried to use `pymatgen.io.structure.Structure`. It failed because of this import https://github.com/materialsproject/pymatgen/blob/82f108a3cba5f12b88b95fecb4e3b775ca9de6c6/pymatgen/core/structure.py#L27

`ase` is currently an optional requirement. After installing `ase`, everything was fine.

**Comment by shyuep** [comment]
@arosen93 Pls fix....

**Comment by arosen93** [comment]
Will fix it ASAP right after this meeting. There's no need for it to be required. Something must have been missed.
