### ISSUE TITLE
Z-matrix representation

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/pymatgen#3090]
I am currently using some pymatgen parts that I hadn't used before. As far as I see, we currently have an option for a z-matrix representation as part of the Gaussian output generation: https://github.com/materialsproject/pymatgen/blob/f90929f75b27fe1d06faa4e2a5f44654009b98b0/pymatgen/io/gaussian.py#L383-L413

I wonder if this wouldn't be a good convenience method for molecule as this is also used in other quantum-chemical codes. 
I am leaving this here as a suggestion for refactoring and in case pymatgen plans to support more molecular qm codes.

**Comment by janosh** [comment]
> I wonder if this wouldn't be a good convenience method for molecule.

Good idea! Would you like to submit a PR that moves this method to the `Molecule` class and also adds a unit test for it?

**Comment by JaGeo** [comment]
Moving the method, yes. Just wandering of this is the best representation as you can use site number, elemwntname with site numer etc in the z matrix for input files.

Any ideas? Otherwise, I just move the method.

**Comment by janosh** [comment]
I'm probably not the right person to ask this since I don't work with molecules/z-matrices.

**Comment by JaGeo** [comment]
> I'm probably not the right person to ask this since I don't work with molecules/z-matrices.

Yeah, no worries. I also usally don't but it's a typical part of the compchem curriculum to learn about z-matrices and use them in qc codes.
