### ISSUE TITLE
"import openbabel" is deprecated, instead use "from openbabel import openbabel"

### ISSUE THREAD

**Issue by drew-parsons** [materialsproject/pymatgen#3105]
#### Description

[pymatgen/analysis/tests/test_molecule_matcher.py](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/analysis/tests/test_molecule_matcher.py) conditionally uses OBAlign from openbabel.  openbabel is accessed by 
```
import openbabel
```
and availability of OBAlign registered with
```
ob_align_missing = openbabel is None or "OBAlign" not in dir(openbabel)
```
But the special handling for OBAlign is redundant in this sense: openbabel has moved itself into its own submodule. The source for openbabel [`__init__.py`](https://github.com/openbabel/openbabel/blob/master/scripts/python/openbabel/__init__.py.in) 
warns
```
"import openbabel" is deprecated, instead use "from openbabel import openbabel"
```
and the openbabel [documentation](https://open-babel.readthedocs.io/en/latest/UseTheLibrary/PythonDoc.html) corroborates this usage. Indeed, with openbabel 3.1.1 this works, indicating that OBAlign is located at openbabel.openbabel.OBAlign, not openbabel.OBAlign

Hence MoleculeMatcherTest gets skipped unnecessarily, due to a missing `openbabel.OBAlign` when `openbabel.openbabel.OBAlign` is available.

So https://github.com/materialsproject/pymatgen/blob/6871dae21f245db8dafdf3767182ec7dc64f094a/pymatgen/analysis/tests/test_molecule_matcher.py#L24C21-L24C21 should be updated to replace
```
    import openbabel

```
with 
```
    from openbabel import openbabel
```
A more complex variant with a double try block could be used if older versions of openbabel need to be supported. But probably best to just require a "recent" openbabel ("recent" means openbabel 3, since [March 2019](https://github.com/openbabel/openbabel/pull/1946))

#### Repro

1. Install openbabel 3
2. Go to pymatgen source
3. `pytest-3 -v -k MoleculeMatcherTest  pymatgen/analysis/tests/test_molecule_matcher.py`
4. See if tests are skipped with `OBAlign is missing, Skipping`

#### Expected behavior

MoleculeMatcherTest (OBAlign) tests should be able to run on "modern" openbabel installations (as openbabel.openbabel.OBAlign)

#### Environment

Relevant versions and platform info:

- OS: Linux (debian unstable)
- pymatgen 2023.06.23
- openbabel 3.1.1

**Comment by janosh** [comment]
@drew-parsons Thanks for pointing this out! Note that this is not the only reason `MoleculeMatcherTest` isn't being run in CI. We're also not installing `openbabel`. IIRC we had serious installation issues in the past causing us to drop it. Just tried again on macOS and couldn't install. But happy to give it a try in Linux CI.
