### ISSUE TITLE
dangerous serialization behavior of many PMG input sets

### ISSUE THREAD

**Issue by computron** [materialsproject/pymatgen#313]
## System

Latest pymatgen, Mac

## Summary

* Many VaspInputSet objects subclass DictVaspInputSet. For example, MPStaticVaspInputSet is one of many such classes.
* These subclassed VaspInputSet objects also take in constructor parameters. However, I have found that if the first two parameters are not "name" and "config_dict", then there can be deserialization problems.
* The subclassed objects serialize fine to a dict. But on deserialization, the first two parameters given to the object are "name" and "config_dict" (e.g., in DictVaspInputSet). So these must also be the first two parameters given to the objects...
* See example code for more details

## Example code

```python
import os
from monty.serialization import loadfn
from pymatgen.io.vasp.sets import DictVaspInputSet, MODULE_DIR

class TestVaspInputSet(DictVaspInputSet):
    def __init__(self, reciprocal_density=50, **kwargs):
        super(TestVaspInputSet, self).__init__("Test",
            loadfn(os.path.join(MODULE_DIR, "MPVaspInputSet.yaml")), **kwargs)

        self.test_var = reciprocal_density


class TestVaspInputSetRevised(DictVaspInputSet):
    def __init__(self, name="Test", config_dict=None, reciprocal_density=50, **kwargs):
        super(TestVaspInputSetRevised, self).__init__(name,
            loadfn(os.path.join(MODULE_DIR, "MPVaspInputSet.yaml")), **kwargs)

        self.test_var = reciprocal_density

if __name__ == "__main__":
    x = TestVaspInputSetRevised()
    x2 = TestVaspInputSetRevised.from_dict(x.as_dict())  # OK!
    print x.as_dict() == x2.as_dict()  # True = proper serialization and deserialization

    y = TestVaspInputSet()
    y2 = TestVaspInputSet.from_dict(y.as_dict())  # raises error!
```

## Error message

The "normal" TestVaspInputSet should give an error at the indicated line.

## Suggested solution (if any)

Possible solutions are:
* subclasses of DictVaspInputSet should make sure the first two parameters are name and config_dict.
* subclasses of DictVaspInputSet should overload the from_dict() function.

There might be other solutions. My main goal here is to raise a flag.

**Comment by shyuep** [comment]
This is not really a bug, but basically a well-known problem with OOP. We have the same problem when subclassing anything else, e.g., Structure -> Slab. You *have to* overload the from_dict and preferably as_dict methods as long as your constructor no longer have the exact same signature as the parent class. But this can be mitigated by being explicit about using kwargs in DictVaspInputSet.from_dict. Just pushed a change. See if your code now works. It should.

**Comment by computron** [comment]
The test code now fails for a different reason. What happens is that in the from_dict, the "name" is passed as a **kwarg. But it also needs to be the first non-optional argument. i.e., try running the following. It fails in the "super.__init__()" call because name is both the first argument ("Test") and also passed through **kwargs.

```
import os
from monty.serialization import loadfn
from pymatgen.io.vasp.sets import DictVaspInputSet, MODULE_DIR

class TestVaspInputSet(DictVaspInputSet):
    def __init__(self, reciprocal_density=50, **kwargs):
        super(TestVaspInputSet, self).__init__("Test",
            loadfn(os.path.join(MODULE_DIR, "MPVaspInputSet.yaml")), **kwargs)

        self.test_var = reciprocal_density

if __name__ == "__main__":
    y = TestVaspInputSet()
    y2 = TestVaspInputSet.from_dict(y.as_dict())  # raises error!
```

**Comment by shyuep** [comment]
I think this should be solved on the subclass side of things? E.g., if you write

```python
d = kwargs
d["name"] = "Test"
d["config_dict"] = loadfn(os.path.join(MODULE_DIR, "MPVaspInputSet.yaml"))
super(TestVaspInputSet, self).__init__(**kwargs)
```

I am pretty sure this works.

**Comment by computron** [comment]
Works - I will use that for now. I am still thinking in Java where the super() call must be the first line.

**Comment by shyuep** [comment]
BTW, I point out that subclass in general needs to have the same arg signature as the parent for OOP to work properly.  

For example, let's say we have

```
class Rectangle:
    def __init__(self, a, b):
        ...

class Square(Rectangle):
    def __init__(self, a):
        ...
```

You will also see that there is no way to code as_dict and from_dict in Shape in a general way that works magically for Square. Square has to override those functions.

For this particular problem, if you want something simpler, we can create an intermediate subclass of DictVaspInputSet say FileVaspInputSet that takes in a config file as a variable, rather than a config dict. That might make it a bit easier.
