### ISSUE TITLE
Importing pymatgen messes up sys.path

### ISSUE THREAD

**Issue by pmrv** [materialsproject/pymatgen#3156]
Since [v2023.06.23](https://github.com/materialsproject/pymatgen/releases/tag/v2023.06.23) importing `pymatgen` manipulates [sys.path](https://github.com/materialsproject/pymatgen/blame/63bbd23b57ca2c68eaca07e4915a70ef66e13405/pymatgen/io/ase.py#L26).  This is somewhat annoying if you have a more complicated site setup.

I would suggest as a fix to move that hack either to the file with the affected tests or remove the path of `sys.path` again after you have checked that ase is installed in the file linked above (it seems `ase_loaded` that was previously checked is not used elsewhere in the code).  I'm happy to make a PR to either effect if you're a bit strapped for time right now.

Some background as to why this breaks for us:  We are in a setup where users and developers of our package share a conda environment.  For users releases of our package are installed via conda.  Developers shadow the installed package by manipulating their `sys.path` to import their development version of the software rather than the releases from conda.  The hack above then manipulates our manipulation so that the package is imported from conda again.  So it's just that the hack works a little bit too well. 😅

**Comment by shyuep** [comment]
Thanks for reporting this. @arosen93 The only sys.path that I noticed is in the io.ase. Did you add that? I am not sure of the purpose of it. Can you reverse it? @janosh

**Comment by arosen93** [comment]
Nope, don't think that was me. @janosh, was that one you? Feel free to reverse. Otherwise, I'll take a look later today.

**Comment by shyuep** [comment]
Ah yes, it was @janosh . This needs to be reversed. We shouldn't be doing this kind of thing for test running. I am not sure why this is even a problem. But if it is for testing, I am sure there are other solutions that don't involve doing things like modifying sys.path.

**Comment by shyuep** [comment]
I found a solution that works: `--import-mode=importlib` for pytest. This solution does nothing to the actual code. See https://docs.pytest.org/en/7.1.x/explanation/pythonpath.html

**Comment by shyuep** [comment]
A 2023.7.14 release has been made that removed the sys.path. This version should now work. Thanks for reporting this.

**Comment by janosh** [comment]
`--import-mode=importlib` sounds great! Except for the caveat:

> test modules are non-importable by each other. Also, utility modules in the tests directories are not automatically importable because the tests directory is no longer added to [sys.path](https://docs.python.org/3/library/sys.html#sys.path).

I'm very surprised if we don't make use of that anywhere in the `pymatgen` test suite.

**Comment by janosh** [comment]
Cool, looks I have reason to be surprised; all tests still passing. `--import-mode=importlib` is clearly the better solution, sorry for the path issues.

**Comment by shyuep** [comment]
I would be very surprised if tests import from each other. All tests are written on a per file testing basis.

**Comment by janosh** [comment]
I was referring to utility modules in the tests directories. I have those in several of my projects that are much smaller than `pymatgen`.

**Comment by pmrv** [comment]
Thanks everyone for quickly resolving this!

@janosh re utility modules: We have this case in multiple of our pyiron packages and there we just stick those in a `_test` module in the main package and haven't had problems so far. It doesn't impact the main package as well because it never imports that module.

**Comment by janosh** [comment]
Sounds like `_test` would end up in the source distribution (unless you explicitly exclude it)?

**Comment by pmrv** [comment]
Correct, it does end up in the source distribution.  It's a bit unaesthetic, but no issues otherwise.
