### ISSUE TITLE
error about "%matplotlib inline"

### ISSUE THREAD

**Issue by QiWen0110** [materialsproject/pymatgen#316]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System

* Pymatgen version: <Write "branch_name" if it is development version.>:3.3.5
* Python version: <Only 2.7.* and 3.* supported.>:python2.7.11
* OS version: <If you are writing Windows here, you are on your own.> OS EI Capitan 10.11.4

## Summary

* <Short 1-2 bullet points stating the problem.>The command "%matplotlib" can`t run

## Example code
from pymatgen.matproj.rest import MPRester
from pymatgen.electronic_structure.core import Spin
#This initiliazes the Rest connection to the Materials Project db. Put your own API key.
a=MPRester("YOUR_API_KEY")
#load the band structure from mp-3748, CuAlO2 from the MP db
bs=a.get_bandstructure_by_material_id("mp-3748")
%matplotlib inline
from pymatgen.electronic_structure.plotter import BSPlotter
plotter=BSPlotter(bs)
plotter.get_plot().show()
```python
<Example code generating error>

```

## Error message
File "<stdin>", line 1
    %matplotlib inline
    ^
SyntaxError: invalid syntax
[Basic functionality.pdf](https://github.com/materialsproject/pymatgen/files/189082/Basic.functionality.pdf)
[Analyze and plot band structures.pdf](https://github.com/materialsproject/pymatgen/files/189087/Analyze.and.plot.band.structures.pdf)

```
<Error message>
```

## Suggested solution (if any)

* <If you have a suggestion on how to solve the issue, you may write it
  here.>

## Files (if any)

<If input files are needed to reproduce the error, please provide 
either links (e.g., Dropbox or GDrive) for large files or simply paste
the file below for small files.>

```
<contents of file 1>
```

**Comment by shyuep** [comment]
This is not a bug. %matplotlib inline is only used in the ipython notebook. Take out the line and it should be fine.

**Comment by QiWen0110** [comment]
Hi,Shyue Ping Ong,I tried on ipython,but  it still doesn`t work!
thank you for your help!

**Comment by shyuep** [comment]
Ipython Notebook. Just remove that line.

Shyue Ping
