### ISSUE TITLE
Migrate to cython v3

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#3161]
[`cython` just released v3](https://cython.readthedocs.io/en/latest/src/changes.html#unified-release-notes) with a bunch of breaking changes that affect `pymatgen` installation.

This issue tracks migrating to `cython` v3 so we can remove the pin added in [e8d4917](https://github.com/materialsproject/pymatgen/commit/e8d4917b030ac9de94d0291b7ce410acd1a14d10).

**Comment by shyuep** [comment]
It is a one-line fix. `cdef int n_pbc_im = 3 ** n_pbc` -> `cdef int n_pbc_im = int(round(3 ** n_pbc))`
