### ISSUE TITLE
`label` in `Structure.as_dict()` is `None` in the latest version

### ISSUE THREAD

**Issue by njzjz** [materialsproject/pymatgen#3166]
#### Description

The latest version gives the `'label': None` in `Structure.as_dict()`. I want to confirm if it is expected, as it breaks the tests in our downstream package.

#### Repro

```py
from pymatgen.core import Structure
import numpy as np
s = Structure(np.eye(3), ["H"], np.zeros((1, 3)), coords_are_cartesian=True)
print(s.as_dict())
```

```
{'@module': 'pymatgen.core.structure', '@class': 'Structure', 'charge': 0, 'lattice': {'matrix': [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]], 'pbc': (True, True, True), 'a': 1.0, 'b': 1.0, 'c': 1.0, 'alpha': 90.0, 'beta': 90.0, 'gamma': 90.0, 'volume': 1.0}, 'sites': [{'species': [{'element': 'H', 'occu': 1}], 'abc': [0.0, 0.0, 0.0], 'xyz': [0.0, 0.0, 0.0], 'label': None, 'properties': {}}]}
```

#### Expected behavior

In previous versions, `label` is `H`.

#### Environment

Relevant versions and platform info:

- OS: Linux
- Version  2023.7.17

**Comment by janosh** [comment]
@njzjz Thanks for reporting. This is not intended.

This was caused by #3135. @stefsmeets Could you take a look? `label` should still be `H` here.

**Comment by stefsmeets** [comment]
I added `Site.label` is a new attribute (default None), so it was never 'H' to begin with unless explicitly set by the user or any code that uses it.

I can submit a PR to set the default to the species name if that is more sensible.

**Comment by stefsmeets** [comment]
Ah, I found the culprit:

https://github.com/materialsproject/pymatgen/blob/80aa7813c0c74a7e9ab60d5d76af496ba3e195a5/pymatgen/core/sites.py#L591

`Structure.as_dict()` writes with `verbosity=1`, which adds "label" to the dict. This causes a name collision with the `.label` property.
