### ISSUE TITLE
Structure object inefficiency

### ISSUE THREAD

**Issue by wmdrichards** [materialsproject/pymatgen#318]
Structure objects take a long time to copy (long here is relative, but at this point even StructureMatcher spends almost 90% of its time copying structures in the cython_utils branch). They are essentially just lists of periodic sites (which are immutable), so the copy should be able to just copy the list without copying the underlying Site objects. Unfortunately, since Structure.__init__ takes lists of species and coords, this is not currently possible.
## Suggested solution (if any)
- Refactor Structure and Molecule objects, switching Structure.__init__ and Structure.from_sites. I think it's possible to have a temporarily overloaded Structure.__init__ to avoid breaking any code and properly show deprecation warnings.

**Comment by shyuep** [comment]
Before you refactor, look at the solution I did. I think overloading is difficult. But we can cheat by simply initializing an empty structure (no site creation) and assigning self._sites. This works and doesn't break anything.

**Comment by shyuep** [comment]
In general, I am not a fan of *args, **kwargs. It makes it very difficult to know what parameters to supply. The solution I wrote basically speeds up basic structure copying by ~100x. I tested that fast_copy takes 2.7 us per loop, while normal copy or santize takes 200 us per loop.

**Comment by wmdrichards** [comment]
Ew. Looks like it could work though.

I think long-term it would be cleaner to refactor to have \__init__ take arguments closer to the internal representation. A bunch of weird bugs cropped up with these commits since there's still no way to quickly make a Structure from an IStructure. There would be some side-benefits including speeding up from_dict slightly as well. The args, kwargs would just be a temporary hack to avoid breaking peoples code before they refactor.

**Comment by shyuep** [comment]
Yep. I agree. Let's think about it a little. I will reopen this issue so that it is on our radar. But otherwise, the solution basically now works. In general, IStructure is an anachronism. Structure should be the default for most things. I have half a mind to remove IStructure completely in pmg 4.0. Though that might break a lot of stuff.

**Comment by janosh** [comment]
> IStructure is an anachronism. Structure should be the default for most things. I have half a mind to remove IStructure completely in pmg 4.0.

@shyuep What's your current thinking on `IStructure`? Should we drop it in `v2024.*.*`?

**Comment by shyuep** [comment]
Closing this issue.
