### ISSUE TITLE
How to improve `Composition.__repr__`

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#3181]
There's a problem with `Composition.__repr__`.

```py
from pymatgen.core import Composition
from pymatgen.core.periodic_table import Species

comp1 = Composition({Species("Fe2+"): 2})
comp2 = Composition({"Fe2+": 2})
comp3 = Composition({"Fe": 2})
```

These 3 compositions all print 

```
Comp: Fe2
```

which isn't ideal given only the first 2 are equal.

```
comp1 == comp2
>>> True
comp1 == comp3
>>> False
```

Ideally, the output of `Composition.__repr__` should allow to recreate the `Composition` by pasting that string into the Python interpreter. Current `__repr__` is lacking `oxi_state` information and also doesn't produce valid Python code.

**Suggestion**

How about we change to:

```
print(f"{Composition('Fe2+:2')!r}")
>>> Composition('Fe2+:2')
```

This would strictly speaking be a breaking change since people might have written code that depends on how `Composition` stringifies. Curious to hear opinion @mkhorton @shyuep.

**Comment by chiang-yuan** [comment]
This is a good proposal, but what if in the future we consider even more detailed information like partial charge, would it be more complicated? I guess we can just round the partial charge to formal charge and use formal charge as species tag?

**Comment by arosen93** [comment]
I'm definitely torn on this one. I can see the point, but at the same time, the composition is a chemically meaningful thing and typically refers to the elements without any further information. I could see arguments for both directions here.

**Comment by janosh** [comment]
@arosen93 That's what we still have the `__str__` method for. In Python `str` and `repr` serve 2 different purposes:

- __repr__ goal is to be unambiguous
- __str__ goal is to be readable

**Comment by shyuep** [comment]
I think changing repr is fine. No one should be using repr for any purposes.

**Comment by janosh** [comment]
Cool. @tschaume @yang-ruoxi any downstream implications for `mp-web` / `crystaltoolkit` here?
