### ISSUE TITLE
get_entries_in_chemsys does not seem to work any more

### ISSUE THREAD

**Issue by hyllios** [materialsproject/pymatgen#319]
## System

* Pymatgen version: 3.0.10
* Python version: 2.7.6
* OS version: Ubuntu 12.04 LTS

## Summary

* get_entries_in_chemsys does not seem to work any more

I have been using pymatgen to calculate the distance to the convex hull for several months now. A couple of weeks ago, the script stop working, complaining that it did not find come terminal compounds. The same happened in several machines at the same time. Digging a bit I found that get_entries_in_chemsys is only returning a couple of entries from the database, and not all available structures.

## Example code

from pymatgen.matproj.rest import MPRester
a = MPRester('AxxMD49p6cCDmcy9')
e = a.get_entries_in_chemsys(['Ca','Cs','O'])
for i in e:
  print i.composition

## Output

Cs2
Cs1
Cs8
Cs4
Cs8
Cs8
Cs2
O8
O2
O2
O24
O2
O8
Cs1 Ca3
Cs2 O1
Cs1 O2
Cs4 O2
Cs21 O3
Cs2 O2
Cs2 O4
Cs6 O2
Cs44 O12
Cs8 O4
Cs1 Ca1 O3
Cs8 Ca4 O8

(No Ca, for example).

**Comment by shyuep** [comment]
Your pymatgen version is rather out-dated. There have been some recent changes on the Materials Project side of things to clean up some urls. Pls upgrade your pymatgen to the latest version and it should work. I just tested it.

**Comment by hyllios** [comment]
Hi,

  It works. Thanks a lot!

   cheers,
   Miguel
