### ISSUE TITLE
New release of pymatgen required

### ISSUE THREAD

**Issue by naik-aakash** [materialsproject/pymatgen#3194]
# Issue

The recent feature added to `pymatgen.io.lobster.lobsterenv.LobsterNeighbors` class to handle cobis and coops via PR #3050 is necessary for our Lobsterpy package to extend its functionality. 

It would be great if a new release is made available soon.

**Comment by janosh** [comment]
@naik-aakash [v2023.8.10](https://github.com/materialsproject/pymatgen/releases/tag/v2023.8.10) will be on PyPI in ~1h.

**Comment by JaGeo** [comment]
Thank you both!

**Comment by naik-aakash** [comment]
@shyuep and @janosh , Thank you 😃
