### ISSUE TITLE
Redundant lines in `Kpoints.automatic_density_by_lengths`

### ISSUE THREAD

**Issue by matthewkuner** [materialsproject/pymatgen#3217]
https://github.com/materialsproject/pymatgen/blob/13e46fdf65ecdb60ddd491dd640f236ed3c5ce7a/pymatgen/io/vasp/inputs.py#L1330

What is the point of this when you always set the style to gamma a few lines later?

**Comment by janosh** [comment]
Looks like a simple oversight in https://github.com/materialsproject/pymatgen/commit/8648d50f746486e194c2355d3c12e6dce8f6dea1. @arosen93 Could you confirm that line 1334 should be deleted?

https://github.com/materialsproject/pymatgen/blob/13e46fdf65ecdb60ddd491dd640f236ed3c5ce7a/pymatgen/io/vasp/inputs.py#L1334

@matthewkuner Best to put the question in the body. 3 line titles are hard to read.

**Comment by arosen93** [comment]
```python
if has_odd or is_hexagonal or force_gamma:
    style = Kpoints.supported_modes.Gamma
else:
    style = Kpoints.supported_modes.Monkhorst
style = Kpoints.supported_modes.Gamma
```

I'm guessing that the bottom `style = Kpoints.supported_modes.Gamma` should be deleted. That seems to be an oversight.
