### ISSUE TITLE
API inconsistency in pymatgen.core.io

### ISSUE THREAD

**Issue by orionarcher** [materialsproject/pymatgen#3230]
#### Problem

The `from_string` method in `pymatgen.io.core.InputFile` was recently changed to `from_str`. I am fine with either convention (though it did break pymatgen.io.openmm downstream) but there is now internal inconsistency between the [InputFile.from_str](https://github.com/materialsproject/pymatgen/blob/1fa96f8535f86d2ee609c906d333f417c8a260e0/pymatgen/io/core.py#L73) and [InputFile.get_string](https://github.com/materialsproject/pymatgen/blob/1fa96f8535f86d2ee609c906d333f417c8a260e0/pymatgen/io/core.py#L57) methods. 

#### Proposed Solution

We should either stick to `from_string` and `get_string` or `from_str` and `get_str`. Whichever is more consistent with the rest of pymatgen makes sense to me.

**Comment by janosh** [comment]
I've moving everything `from_string -> from_str`. But it shouldn't have broken anything during the ongoing deprecation period. I made that change in #3158 but looks like I forgot to add the fallback `from_string` on `InputFile`. Fix incoming.

Good catch on the `from_str` vs `get_string` inconsistency. Let's go with `get_str` there as well. `get_string` will still be around but deprecated (for ~6 months).
