### ISSUE TITLE
Read wavefunction from WAVRCAR for some specific purposes.

### ISSUE THREAD

**Issue by hongyi-zhao** [materialsproject/pymatgen#3233]
Suppose I would like to achieve the following purposes based on the wavefunction analysis from WAVRCAR:

1. Calculate the topological number based on the exact form of wavefunction, aka, an n*1 array under plane wave basis. 
2. Compute the traces of matrix presentations and determines the corresponding irreducible representations for all energy bands and all the k-points in the three-dimensional Brillouin zone.

I would like to know whether [the method implemented in this package](https://github.com/materialsproject/pymatgen/blob/7c70c1ad5a1c489bfb5e4fbd53804630ac48d248/pymatgen/io/vasp/outputs.py#L4409) meets the above requirements.

See below for the related discussions:

https://www.vasp.at/forum/viewtopic.php?t=18177
https://github.com/QijingZheng/VaspBandUnfolding/issues/23

Regards,
Zhao

**Comment by shyuep** [comment]
I think this is something you have to experiment with the Wavecar class and see if it meets your needs.
