### ISSUE TITLE
Dependency issue of boto3 missed with pymatgen>=v2023.7.20

### ISSUE THREAD

**Issue by ZLI-afk** [materialsproject/pymatgen#3241]
#### Description

Error of **ModuleNotFoundError: No module named 'boto3'** with latest version (pymatgen>=v2023.7.20). BTW the __version__ isn't updated for those versions.

#### Fixed by

`pip install boto3`

#### Environment

Relevant versions and platform info:

- OS: Mac, Linux
- Version>=v2023.07.20)

**Comment by shyuep** [comment]
@munrojm

**Comment by shyuep** [comment]
Please report all mp-api related issues on the MP API Github repo. https://github.com/materialsproject/api

**Comment by munrojm** [comment]
I am fixing this issue now.
