### ISSUE TITLE
Construct supercells based on partial occupancy or Wyckoff position

### ISSUE THREAD

**Issue by Asif-Iqbal-Bhatti** [materialsproject/pymatgen#3247]
Hello All,

Is there a module in Pymatgen that can construct supercells based on partial occupancy or Wyckoff position? 

A supercell with partial occupancy would be a great feature. If that is already implemented, that would be great.

Asif

**Comment by shyuep** [comment]
I have no idea what you mean by partial occupancy. Does it mean that some Wyckoff sites are occupied or do you mean all sites are occupied by a partial occupied composition. Either case, this is already implemented in pymatgen. You can refer to the matgenb examples.

**Comment by Asif-Iqbal-Bhatti** [comment]
So what I meant is:
As an example, Li6PS5Cl in the literature has different experimental structure, and they have shown the coordinates, partial occupancy, and Wyckoff position. (From Vesta)

x y z Occ. U Site Sym.
1 Li Li1 0.31610 0.31610 -0.02290 0.440 0.088 48h …m
2 P P 0.50000 0.50000 0.50000 1.000 0.046 4b -43m
3 Cl Cl1 0.00000 0.00000 0.00000 0.370 0.016 4a -43m
4 Cl Cl2 0.75000 0.75000 0.75000 0.630 0.041 4d -43m
5 S S1 0.00000 0.00000 0.00000 0.630 0.016 4a -43m
6 S S2 0.75000 0.75000 0.75000 0.370 0.041 4d -43m
7 S S3 0.12110 -0.01211 0.62110 1.000 0.058 48h …m

SOmetimes S2 has 4d or 4c site. Well what I mean by is the 4th column ""Occ""

However I will check matgenb. Thanks.
