### ISSUE TITLE
 from pymatgen.analysis.graphs import MoleculeGraph gives ImportError: cannot import name 'which'

### ISSUE THREAD

**Issue by feacluster** [materialsproject/pymatgen#3262]
#### Description

When running  `from pymatgen.analysis.graphs import MoleculeGraph` , I get the error `ImportError: cannot import name 'which'`. Some googling suggests it is perhaps related to Python 2 compatibility? This system does not have Python 2 . I am using Python 3.6.8 from miniconda

#### Repro
```
[hussaif1@delltower48 VOID]$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pymatgen.analysis.graphs import MoleculeGraph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hussaif1/miniconda3/envs/VOID/lib/python3.6/site-packages/pymatgen/analysis/graphs.py", line 22, in <module>
    from monty.os.path import which
ImportError: cannot import name 'which'
```

#### Expected behavior

No error on import

#### Environment

RedHat 8. Miniconda 3.8 ( also tried with Miniconda 3.11 ).

**Comment by janosh** [comment]
`which` was removed from `monty` in favor of std lib `shutil.which` a while ago. Please update your `pymatgen` version or downgrade your `monty`.

**Comment by feacluster** [comment]
Many thanks! I was able to resolve the issue by downgrading my monty package as follows:

 pip install 'monty==2022.4.26' --force-reinstall

Now it seems to work as expected!
