### ISSUE TITLE
404 code for using the new MPRester

### ISSUE THREAD

**Issue by Jeff-oakley** [materialsproject/pymatgen#3279]
#### Description

When I run the following code under home internet
```
from mp_api.client import MPRester
USER_API_KEY='XXXX' 
mpr = MPRester(USER_API_KEY) 
mp_entries = mpr.get_entries_in_chemsys(['Li','Mn','O'])
```

The following message shows up:
```
MPRestError: REST query returned with error status code 404 on URL https://api.materialsproject.org/thermo/?_fields=entries&chemsys=Li-O&_limit=143 with message:
Response {"message":"no Route matched with those values"}
```

#### Environment

Relevant versions and platform info:

- Python: 3.9.13
- OS: Mac OS 12.6
- Version: pymatgen 2023.7.20, mp_api 0.29.7

**Comment by shyuep** [comment]
Pls report this to the mpapi repo.  Pymatgen maintainers are not responsible for mpapi.
