### ISSUE TITLE
`InputSet` optional structure refactor introduced missing warning and `W_sv` PSP default

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#3296]
@shyuep The recent [Allow structure=None in inputsets](https://github.com/materialsproject/pymatgen/commit/fabdd276497493f87f72348a3573bbe8a6c38f26#diff-e59a3ba79a120caa18efeceef5f857faf5a1d798c9efd1345746079941a2b471R433-R440) commit introduced an issue. Putting all structure-dependent logic inside the new `InputSet.structure` `@setter` means it no longer runs if people pass in the structure immediately on `InputSet` creation. So e.g. the warning about using `Yb_2` PSPs won't be issued if people use the old way of passing structure immediately.

Same with [defaulting the tungsten PSP to `W_sv`](https://github.com/materialsproject/pymatgen/blob/4b705801a3128ddf95ae5b4c79218ad735ef7d39/pymatgen/io/vasp/sets.py#L401).

**Comment by shyuep** [comment]
The warning still comes when the incar and POTCARs are generated. I think it is fine.

**Comment by janosh** [comment]
Actually, I'm wrong. This line

https://github.com/materialsproject/pymatgen/blob/49083cc93f5d2bb5633aabab094f025b047d591c/pymatgen/io/vasp/sets.py#L376-L377

calls the structure `@setter` and so all that logic runs even on `InputSet.__init__`. As it must have since this test was still passing:

https://github.com/materialsproject/pymatgen/blob/49083cc93f5d2bb5633aabab094f025b047d591c/tests/io/vasp/test_sets.py#L73-L91
