### ISSUE TITLE
Any thoughts on how to handle non-serializable `Structure.properties`?

### ISSUE THREAD

**Issue by arosen93** [materialsproject/pymatgen#3297]
Recently, a `.properties` attribute was added to the `Structure`/`Molecule` objects in #3264. However, since the user can provide any data they want here, it has the potential to break serialization (same thing with the pre-existing `.site_properties`, technically, but `.properties` is more open-ended).

We should think about how we best want to handle this (e.g. do we raise a warning to the user, do nothing at all, sanitize the data, something else?). It's possible that "do nothing at all" is the best approach, as the user will get an error when they try to dump the object if there is something non-serializable in it, but I wanted to open this up for broader discussion anyway.

---------------

On a related note, in the `ASEAtomsAdapter`, I have the following line:
https://github.com/materialsproject/pymatgen/blob/a5b82b5a2c6dd66fef6bfea87f39d3b6656770cb/pymatgen/io/ase.py#L221

The `jsanitize` part was added because oftentimes the `atoms.info` dictionary contains an entry that is not serializable, like the [ASE `Spacegroup` object](https://gitlab.com/ase/ase/-/blob/master/ase/atoms.py?ref_type=heads#L88-94) when you read in a CIF. By using `jsanitize`, it ensures that things are always clean. However, it makes me slightly uncomfortable because if someone converts back and forth between `Atoms` and `Structure`/`Molecule`, it's possible that the starting object is not the same due to `jsanitize` being called on some aspect of the data. Given how often there is non-serializable data in `atoms.info`, I felt it necessary to not simply ignore it, but I am not convinced that the current approach is ideal and am open to suggestions.

**Comment by shyuep** [comment]
I would assume properties must be something that can be handled by MontyEncoder. This can be made explicit in the doc.
