### ISSUE TITLE
BSPlotter.plot_brillouin() returns empty window

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#3328]
```python
from pymatgen.ext.matproj import MPRester
mpr = MPRester("32-digit key")
bs = mpr.get_bandstructure_by_material_id("mp-3748")
plotter = BSPlotter(bs)
plotter.plot_brillouin()
```

Result: an empty window comes out.

_Originally posted by @goodwilling in https://github.com/materialsproject/pymatgen/issues/3138#issuecomment-1721020134_

**Comment by goodwilling** [comment]
According to the following URL, it seems to be solved by the replacement of 
   ax = axes3d.Axes3D(fig) 
with
   ax = fig.add_subplot(projection='3d')

in pymatgen/utils/plotting.py.

matplotlib and Axes3D give a blank picture
https://stackoverflow.com/questions/76069849/matplotlib-and-axes3d-give-a-blank-picture
