### ISSUE TITLE
Coherent interface builder: too strict tolerance in assert_allclose

### ISSUE THREAD

**Issue by goodwilling** [materialsproject/pymatgen#3334]
##### Description

When building Si(100)/Au(100) interfaces using `coherent_interface_builder` on Windows 10, we encounter an `AssertionError` in pymatgen version 2023.9.10. The issue didn't exist in previous versions. We're using `mp-149` for Si bulk and `mp-81` for Au bulk structures.

##### Error Details

Here's the relevant stack trace:

```python
pymatgen\analysis\interfaces\coherent_interfaces.py", line 217, in get_interfaces
    assert_allclose(
File numpy\testing\_private\utils.py, line 1504, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
File contextlib.py, line 81, in inner
    return func(*args, **kwds)
    ^^^^^^^^^^^^^^^^^^^
File numpy\testing\_private\utils.py, line 797, in assert_array_compare
    raise AssertionError(msg)
```

**AssertionError Details:**

- **Tolerance**: rtol=1e-07, atol=0
- **Mismatched Elements**: 3/6 (50%)
- **Max Absolute Difference**: \(4.4408921 \times 10^{-16}\)

##### Current Workaround

Explicitly setting `atol` to a small non-zero value in `assert_allclose` within `pymatgen/analysis/interfaces/coherent_interface.py` bypasses the error.

---

Please investigate why this issue has appeared in the latest version. Thank you.

**Comment by janosh** [comment]
This is due to #3253. Should be easy to fix by reinstating explicit `atol=1e-08`. Thanks for reporting!
