### ISSUE TITLE
SPGlib segfault

### ISSUE THREAD

**Issue by sdacek** [materialsproject/pymatgen#334]
SPGlib 1.9.1 segaults on nosetests when compiled with GCC (4.8.4, 4.4.6)

SPGlib 1.7.4 also segfaults on nosetests when compiled with GCC ( 4.8.4 )

It could be that some spglib outputs (e.g. empty lists of rotations) that we use as new inputs aren't always valid

**Comment by shyuep** [comment]
I posted to spglib. In future, you might want to directly post to spglib's Github Issues so that Togo can help take a look.

**Comment by shyuep** [comment]
@wmdrichards @sdacek You might want to note the different answers with different tolerances at https://github.com/atztogo/spglib/issues/9#issuecomment-210404808.
