### ISSUE TITLE
Support VASP 64 pseudopotentials

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/pymatgen#3342]
### Problem

VASP has now released v64 pseudopotentials (PBE and LDA). This is an issue tracker to monitor progress related to ensuring that Pymatgen plays nicely with them.

### Proposed Solution

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by janosh** [comment]
Besides adding new POTCAR hashes (or whatever future validation technique we migrate to), are we expecting additional TODOs?

**Comment by Andrew-S-Rosen** [comment]
Here are a few questions:

- Everything works as-expected with the `pmg config` command-line utility? 
- Parsing of the POTCAR spec in the `Potcar` class fetches all the metadata appropriately?

It's very possible that there are no changes needed. Part of this issue was also to decide if that's the case :)

**Comment by mkhorton** [comment]
Is there a link to release notes from VASP on these pseudopotentials? I was hoping to find a news item or a wiki page or similar.

**Comment by janosh** [comment]
If you find one, let me know. This is all i could find. The `README.UPDATES` file they mention offers no further details either.

![Screenshot 2023-09-26 at 10 37 33 AM](https://github.com/materialsproject/pymatgen/assets/30958850/47162a6c-d2d4-4ed4-b301-acefabba7e61)

**Comment by mkhorton** [comment]
Thanks @janosh, I haven't found any mention myself but if I do I'll make sure to share.

**Comment by mkhorton** [comment]
Seems the most recent update of https://www.vasp.at/wiki/index.php?title=Available_PAW_potentials&type=revision&diff=14415&oldid=12650 was the addition of the Yb_3 line in Jan 2022.

**Comment by JaGeo** [comment]
Are the changes from the new "Cs_sv" on structural optimizations drastic? I guess we would expect the largest impact here.

**Comment by mkhorton** [comment]
Why would you expect Cs_sv specifically to be largest impact @JaGeo? (I have no intuition here.)

**Comment by JaGeo** [comment]
@mkhorton should have phrased it more carefully. "Cs_pv" and potentially all lanthanides but I assume that the "Cs_pv" potential is used more frequently.

**Comment by esoteric-ephemera** [comment]
Is this closed by [PR #3370](https://github.com/materialsproject/pymatgen/pull/3370)?

**Comment by Andrew-S-Rosen** [comment]
Sounds like it. Thanks!

**Comment by janosh** [comment]
We haven't really run anything with the new 6.4 POTCARs yet so I left this open in case we encounter issues. We can re-open if that's the case.
