### ISSUE TITLE
Wrong name of Pourbaix Entry

### ISSUE THREAD

**Issue by yuxin-chang** [materialsproject/pymatgen#3349]
The ion entry of Sn was in a wrong name:
the ion entry with composition Sn1 O2 H1 has name SnOH2[+1]
the ion entry with composition H1 Sn1 O2 has name SnOH2[-1]
As printed out, the number of O and H are opposite

```
mpr = MPRester()
entries = mpr.get_pourbaix_entries([ "Sn"])
for entry in entries:
    print(entry.name,entry.composition )
```
The output is:
Sn[+2] Sn1
SnOH[+1] Sn1 O1 H1
SnOH2[+1] Sn1 O2 H1
SnO3[-2] Sn1 O3
SnOH2[-1] H1 Sn1 O2
Sn[+4] Sn1
…

**Comment by shyuep** [comment]
What is your MPRester version? Also, this should be reported to the mp-api package since it has nothing to do with pymatgen.

**Comment by rkingsbury** [comment]
@yuxin-chang I thought this was an issue in `Ion.reduced_formula`, but I'm not able to reproduce:

```
>>> from pymatgen.core.ion import Ion
>>> i=Ion.from_formula('SnHO2+')
>>> print(i.reduced_formula, i.composition)
SnHO2[+1] Sn1 H1 O2
>>> i=Ion.from_formula('SnHO2-')
>>> print(i.reduced_formula, i.composition)
SnHO2[-1] Sn1 H1 O2
```

Please update your `pymatgen` and `mp-api` clients to the latest versions and let us know if this is still a problem.
