### ISSUE TITLE
parse floats and units from Element attributes

### ISSUE THREAD

**Issue by saurabh02** [materialsproject/pymatgen#335]
## System

* Pymatgen version: 3.4
* Python version: 2.7.10
* OS version: Mac OS X

## Requested feature

- Change the return type for some attribute properties of Element from strings (currently) to perhaps a float/unit or a FloatWithUnit object

## Example code

```python
from pymatgen import Element, FloatWithUnit

el = Element('Al')
print el.thermal_conductivity
print FloatWithUnit.from_string(el.thermal_conductivity)
print FloatWithUnit.from_string(el.thermal_conductivity).real
print FloatWithUnit.from_string(el.thermal_conductivity).unit

print el.electrical_resistivity
print FloatWithUnit.from_string(el.electrical_resistivity)
print FloatWithUnit.from_string(el.electrical_resistivity).real
print FloatWithUnit.from_string(el.electrical_resistivity).unit
```
gives the following unit,

235 W m<sup>-1</sup> K<sup>-1</sup>
235.0 sup^4 K W m
235.0
sup^4 K W m
2.7 10<sup>-8</sup> &Omega; m
2.7 sup^2 Omega m
2.7
sup^2 Omega m

## Suggested solution

*Replacing all "\<sup>"with "^" and removing all "\</sup>" gives the following output,

235 W m^-1 K^-1
235.0 W K^-1 m^-1
235.0
W K^-1 m^-1
2.7 10^-8 &Omega; m
2.7 Omega m
2.7
Omega m

The electrical resistivity is still missing 10^-8, so perhaps further suggested parsing?

**Comment by shyuep** [comment]
This is now implemented. But there are some properties where parsing is more complicated. Use with care.

**Comment by saurabh02** [comment]
Thanks Shyue! 

It still leaves out "10^-8" (and similar exponentials) in the electrical_resistivity, which may be important. Let me see if I can deal with this.
