### ISSUE TITLE
`jsanitize` has downstream issue when converting ase `Atoms` to pymatgen `Structure` in `multiprocessing`

### ISSUE THREAD

**Issue by chiang-yuan** [materialsproject/pymatgen#3358]
I just merged this branch to my local and found that `jsanitize` breaks my code where I have `torch.multiprocessing` to convert `ase.Atoms` into `pymatgen.core.Strucuture`.

```
  File "/global/homes/c/cyrusyc/.conda/envs/chace/lib/python3.9/site-packages/monty/json.py", line 585, in jsanitize
    return [jsanitize(i, strict=strict, allow_bson=allow_bson, enum_values=enum_values) for i in obj.tolist()]
TypeError: 'float' object is not iterable
```

The info in my ase.Atoms is empty so it might be a general problem.

The detailed information below

              @janosh: Just wanted to point out one subtlety to you. Currently, we have the mapping: `Atoms.info <--> Structure.properties`, since they serve the same purpose between ASE and Pymtatgen, respectively. However, I `jsanitize`-d the `atoms.info` before assigning it to `.properties` to ensure the `Structure`/`Molecule` object can be (de)serialized since this is often an implicit assumption of `Structure`/`Molecule` objects but is not necessarily one for ASE `Atoms` objects. In practice, this means that there could be some scenarios where a user interconverts between ASE `Atoms` and Pymatgen `Structure`/`Molecule` with some loss of information; namely, if the `atoms.info` is modified by `jsanitize()` then it can't be restored in its original form. There might be a better solution than this, but I implemented it because oftentimes ASE will dump un-serializable class objects (namely, a `Spacegroup` class) into `atoms.info`, such as when reading in a CIF with symmetry flags.

_Originally posted by @Andrew-S-Rosen in https://github.com/materialsproject/pymatgen/pull/3270#discussion_r1312508843_

**Comment by Andrew-S-Rosen** [comment]
@chiang-yuan: Thanks for highlighting. My opinion is that we should retain back-and-forth interconversion as much as possible, without any loss of information. This breaks that principle. Happy to review alternatives.

**Comment by Andrew-S-Rosen** [comment]
Also see slightly related comment: https://github.com/materialsproject/pymatgen/issues/3297

**Comment by chiang-yuan** [comment]
I 100% support we should keep as much information as possible. I guess the problem is `jsanitize` so perhaps we could use other interconversion method instead?

**Comment by Andrew-S-Rosen** [comment]
@chiang-yuan: Could you share a bit more about how you are getting this error? Perhaps some details about your Atoms object and how you are doing the interconversion? A minimum example would be helpful.

If your info dictionary is empty, I don't think it's due to the issue you linked, as the test suite would fail.

**Comment by chiang-yuan** [comment]
They are typical ase atoms. The original structures are MP computed entry structures. I am doing backward conversion to use pymatgen ewaldsum. 

The code breaks exactly where it calls jsanitize (see following error message). 

```
structure = AseAtomsAdaptor().get_structure(data.to_ase())
  File "/pscratch/sd/c/cyrusyc/pymatgen/pymatgen/io/ase.py", line 221, in get_structure
    properties = jsanitize(getattr(atoms, "info", {}))
  File "/global/homes/c/cyrusyc/.conda/envs/chace/lib/python3.9/site-packages/monty/json.py", line 591, in jsanitize
    return {
  File "/global/homes/c/cyrusyc/.conda/envs/chace/lib/python3.9/site-packages/monty/json.py", line 592, in <dictcomp>
    str(k): jsanitize(
  File "/global/homes/c/cyrusyc/.conda/envs/chace/lib/python3.9/site-packages/monty/json.py", line 585, in jsanitize
    return [jsanitize(i, strict=strict, allow_bson=allow_bson, enum_values=enum_values) for i in obj.tolist()]
TypeError: 'float' object is not iterable
```

I assume we didn't test if it passes within multiprocessing so the test suite won't break for sure. I already had a minimal test and it basically will fail (but it didn't before this change) like following scenario:

```python
from ase import Atoms
import torch.multiprocessing as mp
from pymatgen.io.ase import AseAtomsAdaptor
def convert(data: Atoms):
    structure = AseAtomsAdaptor().get_structure(data)
    return {
        "structure": structure
    }

for batch in loader:
    atoms_batch = decollate_fn(batch)
    njobs = min(mp.cpu_count() - 1, len(atoms_batch))
    with mp.Pool(processes=njobs) as pool:
        results = pool.map(compute, atoms_batch)
```

**Comment by Andrew-S-Rosen** [comment]
Thanks! That will help me debug.

If you are starting from an MP entry, that doesn't necessarily mean the info dictionary is empty. Are you confident that `atoms.info` is empty? Hope you don't mind me double-checking.

**Comment by chiang-yuan** [comment]
To be very very precise and honest, I have a derived class based on ASE Atoms but stored all the data in pytorch tensors..... I think this information is misleading so was reluctant to say. In my version of generated "derived" ASE Atoms, there is nothing inside info  and I saved all the tensors under `atoms._arrays`

**Comment by Andrew-S-Rosen** [comment]
Thanks! All info is helpful.

I'm currently on PTO but working about an hour a day. Can't guarantee I'll open a PR immediately but when I do, I'll tag you. Otherwise, feel free to propose something and I'll review.

**Comment by chiang-yuan** [comment]
Not a problem at all! I will remove `jsanitize` and `properties` temporarily as hotfix and will see if I can fix this too

**Comment by shyuep** [comment]
I just want to note that it is impossible to ensure conversion of all info, mainly because there is no telling what additional attributes a person can add to Atoms or Structure. We can do some mappings to preserve the most common use cases.

**Comment by Andrew-S-Rosen** [comment]
@shyuep: Yup, totally agree. In this case, there is a "standard" object that ASE `Atoms` objects support that is a `Spacegroup` object. It is the common culprit. In my WIP PR, I have (de)serialized that.

**Comment by shyuep** [comment]
One other thing, I am toying with removing ASEAdaptor. Why don't we simply add to_ase_atoms and from_ase_atoms to Structure? We can even map some ASE type functions. E.g., setting calculators and if someone calls an attribute that is ASE related (e.g., get_potential_energy), pymatgen automatically converts the structure to an internal Atoms representation and run the ASE call.

**Comment by Andrew-S-Rosen** [comment]
@shyuep: I wouldn't be opposed (provided the existing suite of tests remain largely intact aside from the relevant syntax changes). In fact, I find the existing adapter a bit silly because there's no reason for it to be a class at all. It has no state or inheritance. Also, many people simply don't know it exists. Having it be a class method of `Structure` would perhaps be worthwhile to consider.

**Comment by mkhorton** [comment]
> One other thing, I am toying with removing ASEAdaptor. Why don't we simply add to_ase_atoms and from_ase_atoms to Structure? 

100% agree

**Comment by shyuep** [comment]
The ASEAdaptor was written a long time ago. The class is purely for organizational purposes. How about we do this - go ahead and move all relevant code to the Structure, Molecule or SiteCollection class as methods from_ase_atoms and to_ase_atoms. We will keep ASEAdaptor and it will be modified simply to be `return structure.to_ase_atoms()` for example. This is just for backwards compatibility since there are codes that already use ASEAdaptor (many ML codes being one example).

**Comment by Andrew-S-Rosen** [comment]
@shyuep: Sounds wise to me. I can take care of that, although in a separate PR to keep things straightforward (likely when I'm back from PTO though... even though I'm on GitHub right now......)
