### ISSUE TITLE
AttributeError: module 'pymatgen' has no attribute 'symmetry'

### ISSUE THREAD

**Issue by YKQ98** [materialsproject/pymatgen#3378]
cannot access symmetry module

**Comment by janosh** [comment]
Can you give some more details about your OS, pmg + Python version and code you're trying to run?

I just confirmed [the symmetry package _is in_ the latest release](https://inspector.pypi.io/project/pymatgen/2023.10.4/packages/41/44/707494da35be2061dfb30d6b8b8cf179c558b35f09857fe6552921309a45/pymatgen-2023.10.4-cp310-cp310-macosx_10_9_x86_64.whl).

**Comment by YKQ98** [comment]
Thank you for your response. I checked again and this error disappears. I am closing this issue.
