### ISSUE TITLE
Visualize `Kpoints` in 3d Brillouin zone

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#3380]
### Problem

Would be cool to visualize `Kpoints` as a 3d scatter plot in the Brillouin zone.

### Proposed Solution

Something similar to https://materialscloud.org/work/tools/seekpath.

![Screenshot 2023-10-01 at 12 00 08 PM](https://github.com/materialsproject/pymatgen/assets/30958850/e972bfad-a80f-46b5-afa1-d8ff0de5a46f)

**Comment by shyuep** [comment]
Cool yes. But practical purpose?

**Comment by janosh** [comment]
Sanity checking, seeing how the different Kpoint styles differ on your system of interest, that sort of thing.

https://github.com/materialsproject/pymatgen/blob/cf0be37137ea0c588b6558a2188f3f919d08e50a/pymatgen/io/vasp/inputs.py#L970-L979

**Comment by shyuep** [comment]
Erm, really? If someone else wants to implement, sure. But I don't see the purpose vs say just printing out the actual point coordinates.

**Comment by mkhorton** [comment]
Already been implemented in Crystal Toolkit / MP website. Practical purpose is for education for students who are not familiar with band structure diagrams, but also to allow visualization of Fermi surface (also implemented via IFermi code). Poorly documented however so easy to miss.

**Comment by Andrew-S-Rosen** [comment]
@janosh: Perhaps we can close this one as out of scope based on the above comments.

**Comment by janosh** [comment]
Certainly.
