### ISSUE TITLE
Make a `structure.to_ase_atoms()` method

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/pymatgen#3385]
> The ASEAdaptor was written a long time ago. The class is purely for organizational purposes. How about we do this - go ahead and move all relevant code to the Structure, Molecule or SiteCollection class as methods from_ase_atoms and to_ase_atoms. We will keep ASEAdaptor and it will be modified simply to be `return structure.to_ase_atoms()` for example. This is just for backwards compatibility since there are codes that already use ASEAdaptor (many ML codes being one example). 
It is a purely copy and paste operation, with some minor refactoring.

_Originally posted by @shyuep in https://github.com/materialsproject/pymatgen/issues/3358#issuecomment-1738393284_

**Comment by janosh** [comment]
Funny, I was planning the same thing. 😄 Similar to #3384.

**Comment by Andrew-S-Rosen** [comment]
@janosh: feel free to take a stab at it. This is admittedly a low priority item in my end.
