### ISSUE TITLE
Test files for chemenv and lammps need to be in root test_files folder.

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#340]
## System
- Pymatgen version: master
## Summary
- All test data files should be in the root test_files in subfolders. E.g., test_files/lammps or test_files/chemenv. This makes it easier to exclude such files from the distributed version of pymatgen.

@matk86 Pls do it for lammps.
@hautierg Pls ask David to do it for Chemenv. FOr some reason, he is not searchable within my Github account.

Pls do this quick. I can't actually release a new version of pymatgen otherwise.

**Comment by matk86** [comment]
@shyuep done
