### ISSUE TITLE
` AttributeError`: `attr='label'` not found on `PeriodicSite`

### ISSUE THREAD

**Issue by lnaglecocco** [materialsproject/pymatgen#3404]
Hi all,

I have some pymatgen code which worked previously. Essentially I have something like:
```
if str(site1) in [str(i) for i in list_of_sites]:
```

where `site1` is an instance of the `PeriodicSite` class and `list_of_sites` is a list of `PeriodicSite` objects.

However I recently upgraded my pymatgen and this code doesn't work. It seems a bug has been introduced in pymatgen which comes up here:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[12], line 1
----> 1 str([PDF_293K[0]])

File C:\ProgramData\anaconda3\envs\materials-analysis\lib\site-packages\pymatgen\core\sites.py:552, in PeriodicSite.__repr__(self)
    549 def __repr__(self):
    550     name = self.species_string
--> 552     if self.label != name:
    553         name = f"{self.label} ({name})"
    555     x, y, z = self.coords

File C:\ProgramData\anaconda3\envs\materials-analysis\lib\site-packages\pymatgen\core\sites.py:79, in Site.__getattr__(self, attr)
     77 if attr in props:
     78     return props[attr]
---> 79 raise AttributeError(f"{attr=} not found on {type(self).__name__}")

AttributeError: attr='label' not found on PeriodicSite
```

A PeriodicSite method calls "self.label" but simultaneously this attribute seems to have been deprecated.

**Comment by lnaglecocco** [comment]
FYI for developers, I have found it useful to be able to run `str()` on a PeriodicSite object, just as a way to compare sites to see if their species and coordinates are identical or not, and would prefer it not to be deprecated (if this was the intention)

**Comment by janosh** [comment]
Please post a minimal repro, i.e. the smallest piece of code that raises this error. This helps us debug.

**Comment by lnaglecocco** [comment]
Hi Janosh,

I no longer get this error, I suspect somehow the problem was with the code setup on my end though I am not totally sure. Sorry for wasting your time and thanks for getting back to me.
