### ISSUE TITLE
Error in the battery explorer using the legacy MPRester

### ISSUE THREAD

**Issue by goodwilling** [materialsproject/pymatgen#3415]
The follow codes work well previously, but now error comes out in something like "/var/www/python/matgen_prod/materials_django/battery_explorer/rest.py". Using mp_api 
seems to bypass the problem in this case, however, it would be appreciated that the legacy MPRester still works for a while.

    mpr = MPRester("16-digit API key")
    keyword = "mp-1003549_Li"
    results = mpr._make_request('/battery/%s' % keyword)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pymatgen.ext.matproj_legacy.MPRestError: Path collision at framework. Content: b'{"valid_response": false, "error": "Path collision at framework", "version": {"db": "2020_09_08", "pymatgen": "2022.0.8", "rest": "2.0"}, "created_at": "2023-10-22T23:59:15.280222", "traceback": "Traceback (most recent call last):\\n  File \\"/var/www/python/matgen_prod/materials_django/rest/rest.py\\", line 95, in wrapped\\n    d = func(*args, **kwargs)\\n  File \\"/var/www/python/matgen_prod/materials_django/battery_explorer/rest.py\\", line 81, in get_battery\\n    for r in qe.query(properties=props, criteria=crit):\\n  File \\"/opt/miniconda3/envs/mpprod3/lib/python3.8/site-packages/matgendb/query_engine.py\\", line 654, in _result_generator\\n    for r in self._results:\\n  File \\"/opt/miniconda3/envs/mpprod3/lib/python3.8/site-packages/pymongo/cursor.py\\", line 1189, in next\\n    if len(self.__data) or self._refresh():\\n  File \\"/opt/miniconda3/envs/mpprod3/lib/python3.8/site-packages/pymongo/cursor.py\\", line 1104, in _refresh\\n    self.__send_message(q)\\n  File \\"/opt/miniconda3/envs/mpprod3/lib/python3.8/site-packages/pymongo/cursor.py\\", line 982, in __send_message\\n    helpers._check_command_response(first)\\n  File \\"/opt/miniconda3/envs/mpprod3/lib/python3.8/site-packages/pymongo/helpers.py\\", line 155, in _check_command_response\\n    raise OperationFailure(msg % errmsg, code, response)\\npymongo.errors.OperationFailure: Path collision at framework\\n"}'

**Comment by shyuep** [comment]
Please report this to the materialsproject.org people, specifically @munrojm . Pymatgen maintainers have no control over the front end or the API end points, especially the legacy end points.
