### ISSUE TITLE
py4vasp for VASP output parsing

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/pymatgen#3416]
I wanted to open up a point of (potentially contentious!) discussion here. It has now been quite some time since the VASP company released [py4vasp](https://github.com/vasp-dev/py4vasp) for VASP output parsing. I was initially skeptical about if it would be well-maintained or not, but things seem to be promising in that regard.

This begs the question: when, if at all, should Pymatgen consider adopting py4vasp for VASP output parsing?

One potential factor to consider is that py4vasp is reliant on the HDF5 output, which means it is only functional for VASP 6.2+ (with the HDF5 feature enabled). So, this suggests that nothing should be done anytime soon...

Of course, there is also the aspect of time. Someone has to spend the time to port the output parsing over to py4vasp and ensure that there are no breaking changes. A big effort! Over the long-term, there would potentially be some time-saving from a maintenance standpoint by outsourcing parsing changes/updates to the VASP company, although the core VASP I/O in pymatgen seems to be pretty stable (so long as VASP doesn't change things drastically).

There's also the fact that it adds a dependency and several subdependencies for a feature we already have largely covered. 

Anyone have any other thoughts beyond my late-night rambling here? I suppose in writing this out it's pretty clear what my conclusion is.

**Comment by JaGeo** [comment]
Agreed. Some people might still use VASP 5.4. Hdf5 support requires extra efforts to compile, if I am not mistaken. I think we should wait.

**Comment by Andrew-S-Rosen** [comment]
>  Some people might still use VASP 5.4. Hdf5 support requires extra efforts to compile, if I am not mistaken. 

This is correct. Certainly, one should not even consider _replacing_ the existing I/O suite until VASP 7+. But that said, I imagine that if a switch is ever made, both will co-exist for some period of time. After all, MP/emmet relies on the existing I/O in pymatgen, and most of the calculations don't have HDF5 files associated with them. Having two I/O suites at the same time does not do very much about reducing the maintenance burden though, rather increasing it 2x. 😅 

I am also in agreement that nothing should be done for quite some time. That said, I wanted to kick off some public conversation anyway!

**Comment by shyuep** [comment]
I would say unless (1) py4vasp offers some compelling benefits over existing pymatgen parsing and (2) porting over is made dead simple, I am not in favor of switching. 

I prioritize things in order of importance/impact and long-term benefits. Pymatgen devs (and MP devs in general) have a long list of high priority things that take months/years to move even an inch. Until those things get done in a timely manner, these lower priority stuff that do not affect existing functionality would have to take a back seat.
