### ISSUE TITLE
`QCInput` has a few undocumented kwargs

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/pymatgen#3432]
### Problem

https://github.com/materialsproject/pymatgen/blob/2709068a2b01cfbbfda4e2dcd62361678c30c10f/pymatgen/io/qchem/inputs.py#L55-L56

The `svp` and `pcm_nonels` kwargs in the Q-Chem `QCInput` class are currently undocumented. I was looking to know a bit more about them. The input type is `dict | None`, but that can be anything really.

Tagging @samblau.

### Proposed Solution

Add docstrings 😄

**Comment by Andrew-S-Rosen** [comment]
@espottesmith: Do you have any insight on this one?

**Comment by Andrew-S-Rosen** [comment]
Actually, I have been told that this is @rkingsbury's area perhaps.

**Comment by espottesmith** [comment]
Yeah, those are related to the ISOSVP/CMIRS solvent models, I believe. Hopefully @rkingsbury can address, but if not, I'm sure I could add docstrings.

**Comment by rkingsbury** [comment]
> Yeah, those are related to the ISOSVP/CMIRS solvent models, I believe. Hopefully @rkingsbury can address, but if not, I'm sure I could add docstrings.

Just a quick ping to say that yes, this is in my purview and I will follow up to add docstrings soon. (Apologies - you know I'm normally a stickler for super thorough docstrings 🤦🏻‍♂️ ). I think I left these out because they are not directly set by the user when creating an input set.

**Comment by Andrew-S-Rosen** [comment]
@rkingsbury: No worries! I appreciate your hard work as always :)
