### ISSUE TITLE
[Feature Request]: loading .STR files 

### ISSUE THREAD

**Issue by osunrinde** [materialsproject/pymatgen#3436]
### Problem

My XRD files are in .STR and I'm trying to convert all to cif but having issues loading the files

### Proposed Solution

A library that can load str directly or a library that can help convert it to cif for use in pymatgen

**Comment by janosh** [comment]
Is this a proprietary file format?

**Comment by osunrinde** [comment]
Do you mean if it's not from ithe ICCD database?
If that is what you meant by proprietary file format, then yes.

**Comment by osunrinde** [comment]
If I use structure.from_file or from_str, it keep throwing unknown file extension as error

**Comment by osunrinde** [comment]
The file opens in topaz and diffrac.eva if this information helps

**Comment by janosh** [comment]
You're getting that error because we don't support the STR file format. Whether we want to support it depends on whether it's an open and widely used standard.

There might be other OSS tools that serve your needs. This one looks like it does the reverse of what you need: https://github.com/rowlesmr/ciftostr.

**Comment by osunrinde** [comment]
Alright. This does the reverse of what I want thou

**Comment by Andrew-S-Rosen** [comment]
@osunrinde: Perhaps it will help if I clarify.

Pymatgen is a community project maintained by group of individuals doing so out of a passion for open-source software. Pymatgen, like any code, should not and cannot be expected to support all features. Whether the Pymatgen chooses to add a feature depends on if it fits within the scope of the project and is of broad use to the community.

Your request and follow-up comments are not providing substantial insight for the developers:

- Janosh's question was about if it is a proprietary file format. If you don't know what that means, a quick Google search clarifies that for you. See [this Wikipedia page](https://en.wikipedia.org/wiki/Proprietary_file_format).
- If it's openly accessible, then you should be motivating why you think this is relevant for Pymatgen. The maintainers aren't aware of every single file format in existence. You should explain what the file is, what produces the file, and why it is important. Importantly, you should share some details on the specification for what the format entails if it is niche.

At the end of the day though, Pymatgen can't support everything. At this time, I agree with @janosh: this is out of scope barring further justification.

**Comment by JaGeo** [comment]
Beyond this: I would have also assumed that TOPAS can handle cif files as this is the standard format in the field of crystallography. 

Maybe, this helps? https://topas.awh.durham.ac.uk/doku.php?id=out_pdcif

**Comment by osunrinde** [comment]
It is not a proprietary data. They are structure files that can be loaded into Topas or EVA software
