### ISSUE TITLE
It seems that there is a bug to write the lobsterin file

### ISSUE THREAD

**Issue by RedStar-Iron** [materialsproject/pymatgen#3437]
https://github.com/materialsproject/pymatgen/blob/15dc77da508c6824a2e7cc41e983f797c64815c4/pymatgen/io/lobster/inputs.py#L271-L272

`key` in `self.get(key)` should be lower, then it can be found in Lobsterin.FLOAT_KEYWORDS.

And the cohpsteps might need to be a positive integer.

So I just revised it to:
```
if key.lower() == "cohpsteps":
    f.write(f"{key} {int(self.get(key.lower()))}\n")
else:
    f.write(f"{key} {self.get(key.lower())}\n")
```

**Comment by JaGeo** [comment]
Thanks for looking at the Lobster part of the code. @naik-aakash and I will check your suggestion carefully.

**Comment by JaGeo** [comment]
I think the bug is coming from the fact that the overwriting of the dict. We will look into it more carefully to not break other parts of the code!

**Comment by naik-aakash** [comment]
Hi @RedStar-Iron, Thanks for the suggestion. Can you also please post the steps to reproduce the issue? It would help me address it properly

**Comment by JaGeo** [comment]
Yup, I have also already reproduced the issue and have started with a fix. Will start the pull request in a WIP minute.

**Comment by JaGeo** [comment]
@RedStar-Iron we have worked on a fix for both of your issues. However, we investigated that it does not matter if cohpsteps is a float or int (see here https://github.com/materialsproject/pymatgen/pull/3439#issuecomment-1791469518)
