### ISSUE TITLE
This part might not be robust.

### ISSUE THREAD

**Issue by RedStar-Iron** [materialsproject/pymatgen#3438]
https://github.com/materialsproject/pymatgen/blob/eee88ab63b66a0b92757524975c7290838b4bf01/pymatgen/io/lobster/inputs.py#L584-L589

It will fail if there is a '\t' in my lobsterin file. 

I recommand to use the `re`.

```
raw_datum = re.findall(r'(?i)\b[a-z]+(?:\d+)?\b|\b\d+[a-z]+\b|[-]?\d*\.?\d+', datum)
```

Above code might meet the requirement.

**Comment by Andrew-S-Rosen** [comment]
Tagging @JaGeo.

**Comment by JaGeo** [comment]
We are on it as a part of https://github.com/materialsproject/pymatgen/pull/3439. Thank you, @Andrew-S-Rosen !

**Comment by JaGeo** [comment]
@janosh can also be closed. It was adressed as a part of #3439
