### ISSUE TITLE
Add GitHub issue templates

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/pymatgen#3449]
There is only one template right now, which is for a feature request. At the very least, a bug report template should be added along with some fields about necessary reporting details (e.g. pymatgen version, Python version, OS), a minimal example, etc. I thought that existed at some point but perhaps not?

**Comment by rajveer43** [comment]
May I work on this?

**Comment by janosh** [comment]
Fixed in #3528.
