### ISSUE TITLE
Outcar.get_dipole_energy method or variable

### ISSUE THREAD

**Issue by rtrottie** [materialsproject/pymatgen#345]
There should be some method of obtaining the dipole correction from IDIPOL = 1/2/3 from the VASP outputs.

**Comment by shyuep** [comment]
This is already possible. Vasprun contains almost all parameters.

```python
In [1]: from pymatgen.io.vasp import Vasprun
In [2]: v= Vasprun("vasprun.xml")
In [3]: v.parameters["IDIPOL"]
Out[3]: 0
```

**Comment by shyuep** [comment]
Sorry, if you mean you want the actual corrections from the calculations, please provide an example OUTCAR with the corrections.

**Comment by rtrottie** [comment]
Yes, I meant the numerical corrections, glad I wasn't too ambiguous.  I've attached the OUTCAR as you requested.  

For your reference:

Line 4650  :  Energy used as Vasprun.final_energy
Line 5688  :  Dipole correction
Line 5958  :  Energy with dipole correction included

[OUTCAR.txt](https://github.com/materialsproject/pymatgen/files/230408/OUTCAR.txt)

**Comment by shyuep** [comment]
This is done. However, to read the dipole corrections, you need to specifically call outcar.read_corrections() and then the data is stored in the outcar.data["dipol_quadrupol_corrections"].
