### ISSUE TITLE
[Issue]: NDCalculator does not support Deuterium?

### ISSUE THREAD

**Issue by Soontam** [materialsproject/pymatgen#3453]
Good Evening, 

I was using a cif file and I received this error when using it: 
**ValueError: Unable to calculate ND pattern as there is no scattering coefficients for D.**
Here is my code:
```
struct = parser.get_structures(primitive=False, symmetrized=True)[0]
nd_calculator = NDCalculator(wavelength=1.6)
pattern = nd_calculator.get_pattern(str_sym, scaled=True, two_theta_range=None) //This is where the error occurs
```
According to the error, it is happening in the get_pattern method of the pymatgen library:
`def get_pattern(self, structure: Structure, scaled=True, two_theta_range=(0, 90))`
And it is happening at this segment of code:
<img width="919" alt="CleanShot 2023-11-03 at 18 16 25@2x" src="https://github.com/materialsproject/pymatgen/assets/106397850/ee94fd1d-21d2-4efe-a09d-774ad97f08ca">

Is there a fix for this that I am missing?

**Comment by shyuep** [comment]
Yes D is not supported. But feel free to add the scattering factors to support it.

**Comment by Soontam** [comment]
Okay sounds good. Thank you.
