### ISSUE TITLE
Zeo++ installation

### ISSUE THREAD

**Issue by lianxiliang** [materialsproject/pymatgen#3513]
Hello,

I would like to use Zeo++ but I had some problems with the installation. The installation instruction seems to be missing from the documentation but is available from previous discussions (https://github.com/materialsproject/pymatgen/issues/290).

I had problems with this download command: svn checkout --username anonsvn https://code.lbl.gov/svn/voro/trunk  # password is 'anonsvn'. The error is the following:

`svn: E170013: Unable to connect to a repository at URL 'https://code.lbl.gov/svn/voro/trunk'
svn: E175013: Access to '/svn/voro/trunk' forbidden
`

I also tried to download Zeo++ from this page directly (https://www.zeoplusplus.org/) but I am not sure how to link it to pymatgen. When I have cython, how do I find cython_wrapper and create the binding? 

Can you please provide some instructions on this? Thanks a lot in advance.

Best regards,
Xiliang

**Comment by shyuep** [comment]
Unfortunately this is very old code that few people uses. You will need to contact the Zeo++ developers on this as we do not support Zeo++ directly.

**Comment by hongyi-zhao** [comment]
However, the corresponding relevant description of `Zeo++` still appears in the current [document](https://pymatgen.org/installation.html).
