### ISSUE TITLE
NEB label error units

### ISSUE THREAD

**Issue by Asif-Iqbal-Bhatti** [materialsproject/pymatgen#3523]
Hello,

I want to report that using the NEB analysis object to get the diffusion barrier, there is a label value error on the barrier height. I have attached one of the NEB plots. If you see the y-axis scale and barrier value, it does not make sense. It should be 20.4 meV, not 204 meV.

![Capture](https://github.com/materialsproject/pymatgen/assets/7361722/e4020751-603f-4cd9-aa3a-304173448900)

Asif

**Comment by DanielYang59** [comment]
Could you @Asif-Iqbal-Bhatti  please include a minimal code snippet so that I could identify the issue more easily? Which module was used to produce this plot (is it NEBAnalysis under pymatgen.analysis.transition_state)? Thanks.

**Comment by janosh** [comment]
i just tested `NEBAnalysis.get_plot()` locally and get the correct value in the barrier label.

@Asif-Iqbal-Bhatti does your plot involve post-processing? can you post a code snippet to repro your plot?
