### ISSUE TITLE
`pymatgen.io.vasp` docs page is very slow to load and scroll

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#3556]
### Discussed in https://github.com/materialsproject/pymatgen/discussions/3554

<div type='discussions-op-text'>

<sup>Originally posted by **kuwabara74** January 15, 2024</sup>
Hello,

The documentation web page of pymatgen.io.vasp package (https://pymatgen.org/pymatgen.io.vasp.html) is too heavy to open immediately. I suppose that the contents of the Potcar class, the description of "potcarpotcar_summary_stats", are very very long.
Could you change the contents so that they do not appear on the web page or only part of the contents are shown?</div>

Thanks a lot for reporting this @kuwabara74. It's definitely the huge string repr of `potcar_summary_stats` that's causing this problem. No idea why it's showing that value in the first place. I assume if we turn this into a private class attribute, it would not be shown in the docs? What do you think @esoteric-ephemera?

![Screenshot 2024-01-15 at 14 47 31](https://github.com/materialsproject/pymatgen/assets/30958850/05dcbc09-e6a5-4151-8b0d-87ce2071e3ab)

**Comment by esoteric-ephemera** [comment]
Oof thanks for reporting this @kuwabara74 and @janosh! Yes I've made this a private attr in #3491, which hopefully fixes the docs issue. Huge oversight on my part!

**Comment by janosh** [comment]
> Huge oversight on my part!

No worries. I didn't even know it would end up as 10k lines in the docs as a non-private attribute.

Anyway, thanks for fixing in #3491.
