### ISSUE TITLE
Error in Parsing Complex Chemical Formulas with Parentheses in pymatgen's Composition Class

### ISSUE THREAD

**Issue by t29mato** [materialsproject/pymatgen#3559]
### Python version

Python 3.10.12

### Pymatgen version

2023.12.18

### Operating system version

Ubuntu 22.04.3 LTS

### Current behavior

The `Composition` class in `pymatgen` fails to correctly parse strings containing complex chemical formulas, resulting in a `ValueError`. An example of such a formula that causes an error is as follows:

```python
pmg.Composition("(Bi2(Mg0.667Nb1.333)O7)((Bi2(Mg0.667Nb1.333)O7)0.9(SrCO3)0.1)((Bi2(Mg0.667Nb1.333)O7)0.7(SrCO3)0.3)")
```

The error seems to stem from the usage of parentheses in the expression, which is not properly interpreted by the `pymatgen` parser.

### Expected Behavior

The `Composition` class in `pymatgen` is expected to correctly parse and calculate the composition for complex chemical formulas, even those using parentheses. However, it has been observed that modifying the formula from 

`(Bi2(Mg0.667Nb1.333)O7)((Bi2(Mg0.667Nb1.333)O7)0.9(SrCO3)0.1)((Bi2(Mg0.667Nb1.333)O7)0.7(SrCO3)0.3)`

to 

`(Bi2(Mg0.667Nb1.333)O7)1((Bi2(Mg0.667Nb1.333)O7)0.9(SrCO3)0.1)((Bi2(Mg0.667Nb1.333)O7)0.7(SrCO3)0.3)`

allows for correct interpretation. However, this should be considered a workaround rather than a solution. The parser should ideally handle the original format without requiring such modifications.

### Minimal example

The following is a minimal example that reproduces the issue:
```Python

import pymatgen as pmg
# This chemical formula triggers the error
pmg.Composition("(C)((C)0.9(B)0.1)")
```
This code leads to a `ValueError: could not convert string to float: '1.00.9'`.

### Relevant files to reproduce this bug

No special files are needed to reproduce this issue. The problem can be replicated by running the above code in an environment where `pymatgen` is installed.

**Comment by janosh** [comment]
thanks for the detailed bug report! should be a straightforward fix by turning the `if match` statement in `_parse_formula()` into a `while` loop to keep unpacking nested parens

https://github.com/materialsproject/pymatgen/blob/20475b6e2ba9f7304f9cc2094b9fa4685c094c58/pymatgen/core/composition.py#L561-L571
