### ISSUE TITLE
Is it OK to use the periodic table JSON data in my own library?

### ISSUE THREAD

**Issue by nicholas-miklaucic** [materialsproject/pymatgen#3579]
Hello,

Thanks for all of your work on such an important library.

I'm currently working on a Rust project intended to be spiritually similar to pymatgen, but reimagined for a a different language and goals. (It's open-source as well.) I'd like to keep rough API compatibility where possible, though, and so if possible I'd like to use the `pymatgen/core/periodic_table.json` data in my own library to ensure that there aren't subtle numerical differences that might cause headaches for users familiar with pymatgen. To be clear, Rust is different enough that the code will be essentially a full rewrite, so the only thing I'm intending to copy wholesale is the numerical data, which is mostly found through references to begin with as far as I'm aware.

A reading of the MIT license and the attributions within the code seem to indicate that this is allowed with attribution, but I thought it'd be appropriate to ask here. Is there any issue with use of the periodic table data with proper attribution? Are there issues I should be aware of when adapting the data to my own code?

Thanks for your time.

**Comment by shyuep** [comment]
Feel free to use it. But pls acknowledge pymatgen and its development team. Also, I would just caution that we periodically update the json file to fix errors, add more properties, etc.
