### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by CharlesCardot** [materialsproject/pymatgen#3582]
### Python version

Python 3.11.0

### Pymatgen version

2023.12.18

### Operating system version

CentOS Linux 8

### Current behavior

I am attempting to visualize a crystal structure using the structure_vtk module. However, it just opens up a blank white window.

### Expected Behavior

I would like to be able to visualize a pymatgen structure object, without having to drag and drop over to a different software. I want something that works with a plain old python script and doesn't require using a jupyter notebook. I would like to avoid making my own jank, ugly visualizations with matplotlib.

### Minimal example

```Python
from pymatgen.vis.structure_vtk import StructureVis
from pymatgen.core import Structure

structure = Structure.from_file("Ca2CuO3.cif")
vis = StructureVis(structure)

vis.show()
```
```


### Relevant files to reproduce this bug

_No response_

**Comment by janosh** [comment]
when i first tried `StructureVis` 1-2 years ago i got the same behavior. not sure when it was last working. bug fix PRs welcome!

**Comment by CharlesCardot** [comment]
I've discovered that the issue is two-fold.

1) I failed to read the documentation correctly and didn't realize that I needed to use the **set_structure** function on the newly created StructureVis object to actually give it something to render. That was why it was just showing a blank white window. My script should have been written like this.

```
from pymatgen.vis.structure_vtk import StructureVis
from pymatgen.core import Structure

structure = Structure.from_file("Ca2CuO3.cif")
vis = StructureVis()
vis.set_structure(structure)

vis.show()
```

2) However, this script also errors out because of the **add_polyhedron** function which gets called because `show_polyhedron = True` by default. When trying to figure out how to color the polyhedron, the module tries to make the polyhedron the same color as the center atom, but when the occupations of the center atom are fractional it will use the color of the center atom with the highest occupation.

```
        if color == "element":
            # If partial occupations are involved, the color of the specie with
            # the highest occupation is used
            max_occu = 0.0
            for specie, occu in center.species.items():
                if occu > max_occu:
                    max_specie = specie
                    max_occu = occu
            color = [i / 255 for i in self.el_color_mapping[max_specie.symbol]]
            ac.GetProperty().SetColor(color)
        else:
            ac.GetProperty().SetColor(color)
```

The main issue here is that the "color" variable is an array of fractional rgb values (ex: [1,0,0]), and I can't seem to find where this comparison against a string "element" comes from or why that was used. This can be solved relatively easily by either setting `show_polyhedron = False` when creating the StructureVis object, or by changing the condition to `if len(center.species.items()) > 1:`.

I don't have a lot of experience contributing to open source projects on github but I can try to submit a bug fix PR in the next couple days.

**Comment by CharlesCardot** [comment]
Update, I actually may have misrepresented the issue slightly. It doesn't actually have anything to do with whether the center atom has multiple occupations or not, it all just comes down to that check of `if color == "element":` and that at no point in the code does color ever seem to be stored as a string. I don't think the proposed solution should be any different though.

**Comment by mkhorton** [comment]
Yes, I don’t know that this is actively used. I would usually point people towards Crystal Toolkit since it has native support for `Structure` visualisation in Jupyter etc., however it’s in need of some updated documentation.

**Comment by dwiddo** [comment]
This issue was never resolved. Why is it closed?
