### ISSUE TITLE
Super slow import times on `2024.1.26`

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/pymatgen#3588]
### Python version

3.11.7

### Pymatgen version

2024.1.26

### Operating system version

Windows 11, Ubuntu

### Current behavior

```
conda create --name test python=3.11
pip install pymatgen
conda activate test
```

```Python
from pymatgen.io.vasp.outputs import Vasprun
```

Running the above after a clean install in an otherwise clean conda environment takes a *super* long time. I stopped timing it after waiting 2.5 minutes.

@esoteric-ephemera has observed similar behavior.

### Expected Behavior

It to not take several minutes.

**Comment by shyuep** [comment]
A new version was released that should fix it. It is due to a bug introduced in monty.
