### ISSUE TITLE
Compare two descriptions of crystal structures to see if the have the same underlying structure.

### ISSUE THREAD

**Issue by hongyi-zhao** [materialsproject/pymatgen#3597]
I'm not sure if pymatgen can do the job as implemented in [XtalComp](https://github.com/allisonvacanti/XtalComp): Compare two descriptions of crystal structures to see if they have the same underlying structure.

See [here](https://github.com/romankempt/hetbuilder/issues/9#issuecomment-1920466398) for the related discussion. Any tips will be helpful.

Regards,
Zhao

**Comment by shyuep** [comment]
It is called the StructureMatcher. We have had this since ages ago...

**Comment by hongyi-zhao** [comment]
So, you mean that [my following code](https://github.com/romankempt/hetbuilder/issues/9#issuecomment-1920466398) is exactly for the purpose discussed here, am I right?

```python
$ cat pymatgen_compare_structures.py 
import sys
from ase.io import read
from pymatgen.io.ase import AseAtomsAdaptor
from pymatgen.analysis.structure_matcher import StructureMatcher

def compare_structures(path1, path2):
    # Read the constructure
    structure1 = read(path1)
    structure2 = read(path2)

    # Convert ASE to Pymatgen structure
    s1 = AseAtomsAdaptor.get_structure(structure1)
    s2 = AseAtomsAdaptor.get_structure(structure2)

    # Initialize the StructureMatcher
    matcher = StructureMatcher()

    # Compare the structures
    are_similar = matcher.fit(s1, s2)

    print("Do the structures have the same underlying structure?", are_similar)

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: script.py path_to_structure1 path_to_structure2")
    else:
        path1, path2 = sys.argv[1], sys.argv[2]
        compare_structures(path1, path2)

$ python pymatgen_compare_structures.py C12H14Mg7N6O14_18.00_degree_0.in C12H14Mg7N6O14_19.00_degree_0.in
Do the structures have the same underlying structure? True
```

**Comment by shyuep** [comment]
Yes

**Comment by hongyi-zhao** [comment]
I think there should be a more efficient implementation for such a job via [carat](https://github.com/lbfm-rwth/carat). The core idea here is to determine the affine isomorphic transformation augmented matrix between two space groups.

**Comment by shyuep** [comment]
The idea here is to not use spacegroups as a criteria for matching. Matching spacegroups is an easy problem. 

In any case, if you have a more efficient or more accurate implementation, we are always happy to receive a PR.

**Comment by hongyi-zhao** [comment]
>The idea here is to not use spacegroups as a criteria for matching. 

This is because the implementation method of StructureMatcher takes into account a wider range of situations.

>Matching spacegroups is an easy problem.

Agreed. Although more computational work is required to determine whether two crystal structures are symmetry equivalent, a good starting point is to determine the isomorphism of space groups.

>In any case, if you have a more efficient or more accurate implementation, we are always happy to receive a PR.

Not at the moment, but what I've described above is a general idea for such a job.
