### ISSUE TITLE
POTCAR setup instructions should be made clearer

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/pymatgen#3629]
### Python version

3.10+

### Pymatgen version

2024.2.8

### Current behavior

Currently, when Pymatgen searches for a pseudopotential, it has a default set of paths it looks in. For instance, if we look for the PBE_54 pseudos and symbol Al, Pymatgen will search as follows:

```
OSError: You do not have the right POTCAR with functional='PBE_54' and symbol='Al' in your 
PMG_VASP_PSP_DIR='/home/rosen/software/vasp/pseudos'. Paths tried: 
['/home/rosen/software/vasp/pseudos/POT_GGA_PAW_PBE_54/POTCAR.Al', 
'/home/rosen/software/vasp/pseudos/POT_GGA_PAW_PBE_54/Al/POTCAR']
```

However, for quite a while now, VASP has been using `potpaw_LDA.54` and `potpaw_PBE.54` as the folder names. We should really add these as defaults so users don't have to deal with modifying this. The same folder structure is used in the v64 pseudos as well.

To be clear, this is the expected path:

```
VASP_PSP_DIR/potpaw_PBE.54/Al/POTCAR
```

### Expected Behavior

Pymatgen should register pseudos out-of-the-box.

### Minimal example

```python
from pymatgen.io.vasp.inputs import Potcar
Potcar(["Al"],functional="PBE_54")
```

**Comment by Andrew-S-Rosen** [comment]
I imagine this is covered in the [POTCAR setup](https://pymatgen.org/installation.html#potcar-setup) section of the docs, but it is not written clearly enough for me to understand.

- What is `<MY_PSP>`? It is not defined anywhere.
- Why should there need to be reconfiguring of my POTCAR directory anyway? Shouldn't I be able to just set `PMG_VASP_PSP_DIR` to the directory of my POTCARs as-downloaded from VASP without further modification?

**Comment by shyuep** [comment]
The functional directory is specified in PotcarSingle. The setup is in cli/pmg_potcar.py. The reason why this setup was done in the past is because VASP can arbitrarily change their directory structure or names (as you have just encountered). But we configure the directories in a standard way.

**Comment by Andrew-S-Rosen** [comment]
Thanks for the reply, @shyuep. I think the [docs](https://pymatgen.org/installation.html#potcar-setup) need to be updated to be clearer for clueless people like me because I could not figure out what `pmg config -p <EXTRACTED_VASP_POTCAR> <MY_PSP>` was supposed to correspond to. I'll open a PR to clarify this.
