### ISSUE TITLE
`bader_analysis_from_path` misusing `_get_filepath` and hence not finding input VASP files

### ISSUE THREAD

**Issue by janosh** [materialsproject/pymatgen#3631]
I'm quite sure that this PR is causing the "bader_analysis_from_path" method to fail for any of its usage. I'm confused how could this PR pass the tests without failing. 

The problematic line is line 455 in this PR and now line 451 in the latest pymatgen. The method is now looking for CHGCAR in the "Could not find CHGCAR!" folder path...

I think the tests and this code should be corrected.
https://github.com/materialsproject/pymatgen/blob/5514ff5418b23da809b23056ea876c0a4c244c96/pymatgen/command_line/bader_caller.py#L438-L452

_Originally posted by @JiQi535 in https://github.com/materialsproject/pymatgen/pull/3458#pullrequestreview-1886487793_

**Comment by JiQi535** [comment]
Thanks a lot for the fast and clean fix! @janosh
