### ISSUE TITLE
Is it possible to reduce the size of `tests` directory?

### ISSUE THREAD

**Issue by DanielYang59** [materialsproject/pymatgen#3641]
### Feature Requested

During a recent clone I noticed the total repo size is pretty big at around 1.9 GB in total, where (sorted and only show the largest several)
```bash
959M    tests
868M    .git
49M     docs
16M     pymatgen
11M     cmd_line
9.4M    dev_scripts
```

While in `tests`:
```bash
898M    files
47M     analysis
13M     io
568K    electronic_structure
344K    core
```

And in `files`:
```bash
139M    molecules
59M     vasprun.xml.dfpt.ionic
55M     boltztrap
42M     vasprun.lvel.Si2H.xml
42M     cohp
38M     vasprun.xml.pbesol_vdw
38M     vasprun.xml.pbesol
36M     vasprun.xml.nonlm
33M     neb_analysis
30M     path_finder
29M     bader
20M     C_48_bandstructure.json
17M     surface_tests
15M     lifepo4.xml
14M     vasprun.xml.int_Te_SOC.gz
13M     vasprun.xml.sc_overflow
13M     vasprun.xml
13M     Zr_Vasprun
13M     CHGCAR.Fe3O4
12M     vasprun.xml.hse06
12M     chgden
11M     vasprun.xml.lobster.spin
11M     chemenv
8.7M    WAVEDERF.Si
8.3M    grid_data_files
8.2M    nmr
7.8M    nwchem
7.4M    boltztrap2
6.8M    OUTCAR.stopped
6.8M    CHGCAR.Fe3O4_ref
6.3M    absorption
6.0M    OUTCAR
```

### Proposed Solution

A simply `gzip` seems to reduce the file size by over 90%:
```bash
59M     ./vasprun.xml.dfpt.ionic
4.4M    ./vasprun.xml.dfpt.ionic.tgz
```

Or reuse some test files wherever possible?

I'm wondering if we have any plan to compress the test files a bit? Thanks.

**Comment by esoteric-ephemera** [comment]
I support the gzipping effort @DanielYang59!

**Comment by JaGeo** [comment]
I guess someone just needs to go ahead and do it. We discussed it before. I compressed some cohp files a while ago but one can surely do more.

**Comment by shyuep** [comment]
Everyone, we don't need to revisit this again. Gzipping can be done. But it is not going to help because Git already gzips prior to transmitting changes. The only people who have to deal with a large tests directory are the developers, who really need the test files anyway. Everyone else just pip installs and the wheels and a few Mb in size. Do not conflate the repo size with the install size. They are two different matters.

**Comment by DanielYang59** [comment]
Thanks a lot for everyone's helpful discussion here. I would go ahead to compress these files and see how everything goes.
