### ISSUE TITLE
My kernel keeps dying when importing CifParser

### ISSUE THREAD

**Issue by stuarthaze** [materialsproject/pymatgen#3663]
### Python version

3.9.18

### Pymatgen version

2024.2.23

### Operating system version

MacOS 14.2.1 (M2 chip)

### Current behavior

I'm new to pymatgen, but my python kernel keeps dying when I import CifParser using the following command:
`from pymatgen.io.cif import CifParser`
It happens when both in the terminal and in jupyter notebook and I tried updating all of my package managers (conda, pip, brew). I never experienced this before working with python. Any advice would be welcome.

### Expected Behavior

I expected no problems importing

### Minimal example

```Python
from pymatgen.io.cif import CifParser
```

**Comment by janosh** [comment]
could this be related to https://github.com/materialsproject/pymatgen/pull/3664?

what do you get for `os.getenv("CI")`?

**Comment by stuarthaze** [comment]
Thanks for the response. I'm unaware what CI is though. After importing `os`,  `os.getenv("CI")` returns `None`, both before and after importing pymatgen

**Comment by janosh** [comment]
Good. Just wanted to confirm. Then I don't think it can't be the issue we just fixed.
As to what's causing it instead, perhaps you can try in a new python environment or on a different machine to see if the issue persists

**Comment by stuarthaze** [comment]
Thanks for the response. I think I narrowed it down to the `spglib` library. That seems to kill my kernel when importing. I'll contact them to see what the problem is.

**Comment by janosh** [comment]
ah, in that case you might be hitting https://github.com/spglib/spglib/issues/197. what's your version?

**Comment by stuarthaze** [comment]
I have version 2.3.1
I could be wrong, but I suspect the issue is that I'm using an apple M2 chip. The C bindings need to be compiled for the osx-arm64 architecture and it seems like it's not tested yet for that yet.

**Comment by janosh** [comment]
should work. i was using it fine on an M2 Max chip last year
