### ISSUE TITLE
Robustness of `Poscar` parser should be further improved

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/pymatgen#3666]
### Python version

3.9+

### Pymatgen version

2024.3.1

### Current behavior

When using the various Pymatgen input parsing utilities on the POSCAR below, a `BadPoscarWarning` is raised even though it is seemingly valid. I've drilled down to the root cause below.

### Expected Behavior

A valid parse.

### Minimal example

```Python
from pymatgen.io.vasp.inputs import Poscar

poscar_text = """
Lu3
1.0
8.212068 -1.711729 -0.004637
8.212068 1.711729 -0.004637
7.856937 -0.000000 2.938818
Lu
3
direct
0.000000 0.000000 -0.000000 Lu
0.221900 0.221900 0.221900 Lu
0.778100 0.778100 0.778100 Lu
"""

Poscar.from_str(poscar_text)
```

Reports:

```python
ValueError: could not convert string to float: 'Lu3'
```

**Comment by DanielYang59** [comment]
It seems you started with an empty first line, which should be the comment line. And therefore the `Lu3` line is treated as the `scale` line thus the error.

This should work:
```python
from pymatgen.io.vasp.inputs import Poscar

poscar_text = """Lu3
1.0
8.212068 -1.711729 -0.004637
8.212068 1.711729 -0.004637
7.856937 -0.000000 2.938818
Lu
3
direct
0.000000 0.000000 -0.000000 Lu
0.221900 0.221900 0.221900 Lu
0.778100 0.778100 0.778100 Lu
"""

Poscar.from_str(poscar_text)
```

**Comment by Andrew-S-Rosen** [comment]
Thank you, @DanielYang59. Apologies about the false report here! I was trying to track down a `BadPoscarWarning`, and it seems like this was a false flag. I'll close this issue until I can find the actual source of the problem. In hindsight, I think the source of my issue was likely some file ending issue when transferring files between Windows/Linux.

**Comment by DanielYang59** [comment]
No worries at all. Not sure if you mean #3662 (to which I confessed...). I tried to run your code on my MacOS machine and didn't notice any `BadPoscarWarning`.

Maybe you may try `git config --global core.autocrlf input` to automatically handle file ending as described [here](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration)? Not sure if this would be helpful though.
> This setup should leave you with CRLF endings in Windows checkouts, but LF endings on macOS and Linux systems and in the repository.

**Comment by Andrew-S-Rosen** [comment]
Nah, what I mean is I transferred a POSCAR from my Linux machine to Windows (or vice versa) and imagine that this probably was potentially the root cause of my problem. In any case, it's all good!
