### ISSUE TITLE
Improper parsing of `METAGGA` flag in `Vasprun` parser

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/pymatgen#3667]
### Python version

3.9+

### Pymatgen version

2024.3.1

### Current behavior

The `Vasprun` parser is not properly parsing the METAGGA flag, which can introduce some painful downstream effects related to MP (see my original report in emmet https://github.com/materialsproject/emmet/issues/960).

```python
from pymatgen.io.vasp import Vasprun

vr = Vasprun("vasprun.xml.gz")
print(vr.parameters["METAGGA"]) # raises a KeyError
```

[vasprun.xml.gz](https://github.com/materialsproject/pymatgen/files/14470682/vasprun.xml.gz)

My guess is because that even though

```
  <i type="string" name="METAGGA"> R2scan</i>
```

is in the `<incar>` section, it's not elsewhere in the file. I can confirm the meta-GGA is applied in the `OUTCAR`.

If I recall correctly, this omission in the `vasprun.xml` was present in certain older versions of VASP, but perhaps it was fixed more recently? It'd be good to confirm this with VASP 6.4.

Maybe the solution here is to get a dictionary of parameters form the incar field and then merge the two dictionaries, with that from the incar field having lower priority.

**Comment by DanielYang59** [comment]
I just had a quick look (quite busy this week) and found this seems not specific to `METAGGA`, 
for example `print(vr.parameters["ALGO"])` would also trigger `KeyError: 'ALGO'`. Not sure about the reason though.

**Comment by Andrew-S-Rosen** [comment]
@DanielYang59 it looks like `ALGO` is also missing from the `<parameters>` section of the `vasprun.xml` file, hence why it too was not showing up. 

To summarize, it seems the there are several parameters that are strangely omitted from the `<parameters>` section of the `vasprun.xml` even though they are valid in the `<incar>` (and other) sections. This then causes the `KeyError`.

I'm not exactly sure the best way to handle this one because `vr.parameters` is indeed reporting accurate information, and populating it with flags from other fields seems perhaps unwise. My concern is mostly with codes that use this information to get the `run_type`, like to generate the MP compatibility data. But I guess that should be handled in those packages directly?

**Comment by Andrew-S-Rosen** [comment]
Closing this as a VASP bug, not a pymatgen bug.
