### ISSUE TITLE
Vasprun get ParseError

### ISSUE THREAD

**Issue by hlyang1992** [materialsproject/pymatgen#369]
When use Vasprun("vasprun.xml") with follow file, will get "ParesError: not well-defined(invaild token). 

## Files 

[vasprun.xml](https://drive.google.com/file/d/0B7DapXLbWsRKUHBVSU1iWVFwS1k/view?usp=sharing)

**Comment by shyuep** [comment]
Your file contains binary characters. It is usually either a bad vasp calculation or a bad compilation of VASP. This is not a problem with pymatgen.
