### ISSUE TITLE
[Dev] Unify all docstrings to Google-Styled

### ISSUE THREAD

**Issue by DanielYang59** [materialsproject/pymatgen#3692]
Noticed some docstrings are still formatted in `Sphinx` style here and there.

![image](https://github.com/materialsproject/pymatgen/assets/80093591/559326f3-0987-4a2c-b177-a026bd8ec9d8)

Also it seems @janosh is working on reformat them to to Google style for example #3320.

Do we have any plan to use Google style? Should I go ahead and try to reformat more? Thanks.

**Comment by janosh** [comment]
help with getting consistent Google-style doc strings everywhere would be much appreciated!

**Comment by DanielYang59** [comment]
Fixed in  #3694
