### ISSUE TITLE
'list index out of range' in PotcarCorrection.get_correction of pymatgen.entries.compatibility.py

### ISSUE THREAD

**Issue by specter119** [materialsproject/pymatgen#376]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System

* Pymatgen version:  3.5.3(pip) <Write "branch_name" if it is development version.>
* Python version: 2.7.11<Only 2.7.* and 3.* supported.>
* OS version: OSX 10.11.4<If you are writing Windows here, you are on your own.> 

## Summary
Gets an IndexError when i set `parameters["potcar_symbols"]` in the class `ComputedStructureEntry`

## Example code

```python
structure = Structure.from_dict(compound['output']['crystal'])
energy = compound['output']['final_energy']
parameters = {\
    "hubbards":compound['hubbards'],\
    "potcar_symbols":compound['pseudo_potential']['labels']\
}
data = {\
    ... : ...
}
mg_entries.append(ComputedStructureEntry(structure, energy, \
    parameters = parameters, data = data)\
)
```

## Error message

```
Traceback (most recent call last):
  File "/Users/Home/Documents/Research/YCuTe2/analyze/test.py", line 10, in <module>
    entery = muti_entery(query)
  File "/Users/Home/Documents/Research/YCuTe2/analyze/AnalyzeMongo.py", line 119, in muti_entery
    entries[key] = compat.process_entries(mg_entries + mp_entries)
  File "/usr/local/lib/python2.7/site-packages/pymatgen/entries/compatibility.py", line 437, in process_entries
    return list(filter(None, map(self.process_entry, entries)))
  File "/usr/local/lib/python2.7/site-packages/pymatgen/entries/compatibility.py", line 403, in process_entry
    corrections = self.get_corrections_dict(entry)
  File "/usr/local/lib/python2.7/site-packages/pymatgen/entries/compatibility.py", line 421, in get_corrections_dict
    val = c.get_correction(entry)
  File "/usr/local/lib/python2.7/site-packages/pymatgen/entries/compatibility.py", line 153, in get_correction
    "potcar_symbols"] if sym])
IndexError: list index out of range
```

## Suggested solution (if any)

In the [line 150~158 of pymatgen.entries.compatibility.py](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/entries/compatibility.py#L150), which is already listed below:

```python
    else:
        psp_settings = set([sym.split()[1]
                            for sym in entry.parameters[
                            "potcar_symbols"] if sym])

if {self.valid_potcars[str(el)] for el in
        entry.composition.elements} != psp_settings:
    raise CompatibilityError('Incompatible potcar')
return 0
```

　　It seems to aim to compare the equality of `entry.composition.elements` and `psp_settings`.
　　But in my dbs, the value of ['pseudo_potential']['labels'] is formated as `Cu_pv` or `H`. Therefore `sym.split()` will have no effect. Even `.split("_")` will get a list of `["Cu","pv"]` or `["H"]`, and the index `[1]` will point to `["pv"]` or IndexError.
　　I am not sure if the `psp_settings` is intended to obtain `"Cu"` from `"Cu_pv"`, maybe the line 151 shoud be:

```python
        psp_settings = set([sym.split("_")[0]
```
　　I am a novice to DFT, if there is something wrong in my words, please forgive me.

**Comment by shyuep** [comment]
This is not a problem with pymatgen. If you are using pymatgen-db to construct the database, there is a specific method to reconstruct entries from db entries.

**Comment by specter119** [comment]
In fact, i haven't used pymatgen-db. Perhaps there a better way in pymatgen-db to reconstruct entries from db entries? Then, i will go and learn it. Thank you.
