### ISSUE TITLE
CrystalNN gives incorrect result for simple aromatic ring

### ISSUE THREAD

**Issue by fxcoudert** [materialsproject/pymatgen#3762]
### Python version

Python 3.11.6

### Pymatgen version

2023.10.4

### Operating system version

macOS 14.4.1

### Current behavior

1. Take this CIF file: https://gist.github.com/fxcoudert/f13193d91eacc7e3d67cf355f805ee36

2. Run this:

```
structure = Structure.from_file("/Users/fx/Documents/structures/MOFs/MOF-71.cif")
nn = CrystalNN()
bonded_struct = nn.get_bonded_structure(structure)
for n, site in enumerate(bonded_struct.structure.sites):
    print(site.label, len(bonded_struct.get_connected_sites(n)))
```

3. The code will output the number of neighbords detected for each atom by CrystalNN. Atoms C6, C7, C12, C13 are detected to have only two neighbours.

4. This is incorrect, they are carbon atoms in benzene rings (the ones in purple) and should be detected to have 3 neighboring atoms.
 
<img width="502" alt="Capture d’écran 2024-04-16 à 22 05 46" src="https://github.com/materialsproject/pymatgen/assets/1980544/f252d0e0-bf84-4e7d-bfe9-fa0ce8dd5af4">

### Expected Behavior

No carbon atom in this structure should be two-connected.

**Comment by JaGeo** [comment]
Hi @fxcoudert ,

have you tested some of other algorithms in the same module as well? I fear CrystalNN might be optimized mostly for typical inorganic crystals.

**Comment by JaGeo** [comment]
`JMolNN()` seems to work at least for the C atoms mentioned above in that example. However, I would not trust the radii in there (they are horribly far away from the atomic radii in Li, for example). You might want to provide a list of radii and tolerances yourself (e.g., atomic radii). I would assume that it should work very efficiently for molecular crystals. I am not sure there is currently any implementation directly in pymatgen or related package optimized for molecular crystals. (cc @Andrew-S-Rosen ?)

**Comment by JaGeo** [comment]
@fxcoudert should we add more documentation to the module and the respective classes to make clear that this is likely only working for inorganic/ionic crystals? If you look at the CrystalNN benchmark, it's also clear that it has never been benchmarked against molecular crystals (see https://pubs.acs.org/doi/10.1021/acs.inorgchem.0c02996)

**Comment by Andrew-S-Rosen** [comment]
Historically, I have had to toggle some of the defaults to get CrystalNN to play nicely with MOF linkers, which I imagine was the source of the motivation for @fxcoudert's question. I can dig up the arguments, if it would be helpful. Of course, one would hope the defaults would suffice...

**Comment by JaGeo** [comment]
> Historically, I have had to toggle some of the defaults to get CrystalNN to play nicely with MOF linkers, which I imagine was the source of the motivation for @fxcoudert's question. I can dig up the arguments, if it would be helpful. Of course, one would hope the defaults would suffice...

Ah, I see! Sorry that I did not know that! At least, I figured out who to ping 😅.

**Comment by JaGeo** [comment]
I think the weird thing here is that the 2nd C isn't detected even though the bond length of both C-C bonds is nearly the same. Interestingly, the atoms lie in such a way to the border of the unit cell that it could be a unit cell bug... Maybe, we should investigate further, indeed.

**Comment by JaGeo** [comment]
After looking again: I find it still puzzling that it does not consider the second C despite the fact that the bond lengths should be extremely similar.

**Comment by Andrew-S-Rosen** [comment]
> No I didn't know (or didn't remember) that. I just wanted to play with CrystalNN and see what it gave.

Ah, I was unclear in my phrasing. I meant that you were probably asking about an organic molecule because you're interested in MOF linkers. :)

>if you know what parameters can give good results for MOFs, I'd be interested, indeed

I did some digging and noticed that for the MOF Explorer App on the Materials Project, we used the following:

```python
StructureGraph.with_local_env_strategy(structure ,CrystalNN(porous_adjustment=True, x_diff_weight=1.5, search_cutoff=4.5)).to_json()
```

So, we were playing around with `x_diff_weight` and `search_cutoff` to address some issues with the organics. That said, the behavior reported in this issue is indeed odd. I would not rule out a bug or problem in general here, although I personally do not have time to look into the issue further. Hopefully someone else can!

**Comment by Andrew-S-Rosen** [comment]
This is only tangentially related, but it also implies issues with C and `CrystalNN` (but this time on an inorganic surface): https://github.com/materialsproject/pymatgen/issues/2618

**Comment by JaGeo** [comment]
I would like to add an additional weird behaviour of one of the other algorithms from the same module which relies on the MinimumDistance.

```py
from pymatgen.core.structure import Structure
from pymatgen.analysis.local_env import JmolNN, CrystalNN, MinimumDistanceNN, VoronoiNN, MinimumOKeeffeNN
from collections import Counter

structure = Structure.from_file("MOF-71.cif")

nn = MinimumDistanceNN(0.5)
bonded_struct = nn.get_bonded_structure(structure)
len_neighbors = []
import numpy as np

for n, site in enumerate(bonded_struct.structure.sites):
    connected_sites = len(bonded_struct.get_connected_sites(n))
    if np.abs(site.coords[0] - 4.63463478) < 0.01 and np.abs(site.coords[1] - 1.18568268) < 0.01 and np.abs(
            site.coords[2] - 8.95930359) < 0.01:
        print(connected_sites)
        print(bonded_struct.get_connected_sites(n))
    len_neighbors.append(connected_sites)
counter = Counter(len_neighbors)
```
I only get the 2nd C if I add a very large tolerance criterion, which is very weird. And the weight is much lower. The weights are different for the different C atoms even so it is a purely distance-based metric.

**Comment by JaGeo** [comment]
I think I have a idea: it's due to the bonded structure. 

`from pymatgen.core.structure import Structure
from pymatgen.analysis.local_env import JmolNN, CrystalNN, MinimumDistanceNN, VoronoiNN, MinimumOKeeffeNN
from collections import Counter

structure = Structure.from_file("MOF-71.cif")

nn =MinimumDistance()
print(nn.get_cn(structure, 76))
`
As expected, this gives 1. Same for CrystalNN() btw.

**Comment by JaGeo** [comment]
I have closed this issue now with an update to the documentation. Let us know if there are still any problems.
