### ISSUE TITLE
test_dilute_solution is monstrously slow

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#378]
## System
- Pymatgen version: master
## Summary
- test_dilute_solution is way too slow. It takes at least a few minutes to complete.
## Suggested solution (if any)
- Unittests should be designed on model systems that complete reasnoably quickly.
- @mbkumar Can you pls fix this. It slows down releases and tests considerably.

**Comment by mbkumar** [comment]
One suggestion is to skip the test for the time being because the underlying function incorporates a large amount of functionality. I am in the process of rewriting the dilute solution formalism with lots of smaller functions. The new code will make it easier to write a good test suite.
