### ISSUE TITLE
import `monty.json` slowing down core import

### ISSUE THREAD

**Issue by DanielYang59** [materialsproject/pymatgen#3793]
### Summary

- `from monty.json import xxx` significantly slowly down core modules, as `torch` is eagerly imported
- [ ]  Might need to look into other commonly used modules

For example:
```bash
python -X importtime -c "from pymatgen.core.structure import Structure" 2> pmg.log && tuna pmg.log
```

With `torch` installed (required by optional `matgl`):
<img width="1505" alt="image" src="https://github.com/user-attachments/assets/7c21db99-53a8-4050-ad00-90a8d31d586f">

After removing `torch`:

<img width="1505" alt="image" src="https://github.com/user-attachments/assets/17753ba9-4e62-456c-95c8-c0daffdcf3bc">

**Comment by janosh** [comment]
this is probably import overhead from loading `pandas` and maybe other big packages. if you start an interactive python session first, wait for it to load and then run `poscar = Structure.from_file("./POSCAR")` on its own, i expect it will be faster

**Comment by DanielYang59** [comment]
Thanks for the input Janosh! I'm not quite sure as I didn't have time to do a thorough investigation (and I don't have extensive experience of import time profiling either). I would look into this later (input from people with more knowledge on this would be hugely appreciated of course).

I think for DFT calculations, input file import should usually not be the bottleneck, but almost two second to read such a simple file sound too much for me.

**Comment by janosh** [comment]
have a look at https://github.com/materialsproject/pymatgen/issues/3563 which tried to reduce startup time by lazy-importing `pandas` only in code that actually needs it. that seems to have back-fired though based on this comment https://github.com/materialsproject/pymatgen/issues/3563#issuecomment-1907031585. this takes careful testing than i did in https://github.com/materialsproject/pymatgen/pull/3568 and https://github.com/materialsvirtuallab/monty/pull/604 to make sure any changes really improve startup time

**Comment by DanielYang59** [comment]
This should also be fixed by https://github.com/materialsvirtuallab/monty/pull/713, after that I would dig deep and see what else is slowing down import
