### ISSUE TITLE
StructureMatcher might be wrong when used to check if two structures are equal.

### ISSUE THREAD

**Issue by usccolumbia** [materialsproject/pymatgen#3796]
### Python version

Python 3.9  (issue not related to this)

### Pymatgen version

2024.3.1

### Operating system version

Mac Os Sonoma 14.3. (issue not related to this)

### Current behavior

StructureMatcher has been frequently used recently to evaluate crystal structure generators such as CDVAE and crystal structure prediction (CSP) algorithm.  In CDVAE paper, the following parameters are used: ltol=0.3, stol=0.5,
angle_tol=10.    We used a more strict parameter set: ltol=0.2, stol=0.3, angle_tol=5.
However, when we tried to evaluate CSP performance, we find many cases that the StructureMatcher returns True (identical) while the space group numbers of the two structures do not even match!  This leads to spurious performance for some papers. https://arxiv.org/abs/2403.10846

ground truth:   Spacegroup 12
# generated using pymatgen
data_Ba2EuTaO6
_symmetry_space_group_name_H-M   'P 1'
_cell_length_a   6.10301173
_cell_length_b   6.10301173
_cell_length_c   6.10301173
_cell_angle_alpha   120.16496379
_cell_angle_beta   120.16496379
_cell_angle_gamma   89.71451102
_symmetry_Int_Tables_number   1
_chemical_formula_structural   Ba2EuTaO6
_chemical_formula_sum   'Ba2 Eu1 Ta1 O6'
_cell_volume   160.33470623
_cell_formula_units_Z   1
loop_
 _symmetry_equiv_pos_site_id
 _symmetry_equiv_pos_as_xyz
  1  'x, y, z'
loop_
 _atom_site_type_symbol
 _atom_site_label
 _atom_site_symmetry_multiplicity
 _atom_site_fract_x
 _atom_site_fract_y
 _atom_site_fract_z
 _atom_site_occupancy
  Ba  Ba0  1  0.25000000  0.75000000  0.50000000  1.0
  Ba  Ba1  1  0.75000000  0.25000000  0.50000000  1.0
  Eu  Eu2  1  0.00000000  0.00000000  0.00000000  1.0
  Ta  Ta3  1  0.50000000  0.50000000  0.00000000  1.0
  O  O4  1  0.24918800  0.28448400  0.53367200  1.0
  O  O5  1  0.73214700  0.73214700  0.00000000  1.0
  O  O6  1  0.28448400  0.75081200  0.03529600  1.0
  O  O7  1  0.26785300  0.26785300  0.00000000  1.0
  O  O8  1  0.75081200  0.71551600  0.46632800  1.0
  O  O9  1  0.71551600  0.24918800  0.96470400  1.0

predicted structure   Spacegroup 87.
# generated using pymatgen
data_Ba2EuTaO6
_symmetry_space_group_name_H-M   'P 1'
_cell_length_a   8.62115426
_cell_length_b   8.62115426
_cell_length_c   8.62115426
_cell_angle_alpha   90.00000000
_cell_angle_beta   90.00000000
_cell_angle_gamma   90.00000000
_symmetry_Int_Tables_number   1
_chemical_formula_structural   Ba2EuTaO6
_chemical_formula_sum   'Ba8 Eu4 Ta4 O24'
_cell_volume   640.76126225
_cell_formula_units_Z   4
loop_
 _symmetry_equiv_pos_site_id
 _symmetry_equiv_pos_as_xyz
  1  'x, y, z'
loop_
 _atom_site_type_symbol
 _atom_site_label
 _atom_site_symmetry_multiplicity
 _atom_site_fract_x
 _atom_site_fract_y
 _atom_site_fract_z
 _atom_site_occupancy
  Ba  Ba0  1  0.25000000  0.25000000  0.25000000  1.0
  Ba  Ba0  1  0.75000000  0.75000000  0.75000000  1.0
  Ba  Ba0  1  0.75000000  0.25000000  0.25000000  1.0
  Ba  Ba0  1  0.25000000  0.75000000  0.75000000  1.0
  Ba  Ba0  1  0.75000000  0.75000000  0.25000000  1.0
  Ba  Ba0  1  0.25000000  0.25000000  0.75000000  1.0
  Ba  Ba0  1  0.25000000  0.75000000  0.25000000  1.0
  Ba  Ba0  1  0.75000000  0.25000000  0.75000000  1.0
  Eu  Eu1  1  0.00000000  0.00000000  0.50000000  1.0
  Eu  Eu1  1  0.50000000  0.00000000  0.00000000  1.0
  Eu  Eu1  1  0.00000000  0.50000000  0.00000000  1.0
  Eu  Eu1  1  0.50000000  0.50000000  0.50000000  1.0
  Ta  Ta2  1  0.00000000  0.00000000  0.00000000  1.0
  Ta  Ta2  1  0.50000000  0.50000000  0.00000000  1.0
  Ta  Ta2  1  0.50000000  0.00000000  0.50000000  1.0
  Ta  Ta2  1  0.00000000  0.50000000  0.50000000  1.0
  O  O3  1  0.00000000  0.00000000  0.23278080  1.0
  O  O3  1  0.00000000  0.00000000  0.76721920  1.0
  O  O3  1  0.23278080  0.00000000  0.00000000  1.0
  O  O3  1  0.76721920  0.00000000  0.00000000  1.0
  O  O3  1  0.00000000  0.23278080  0.00000000  1.0
  O  O3  1  0.00000000  0.76721920  0.00000000  1.0
  O  O3  1  0.50000000  0.50000000  0.23278080  1.0
  O  O3  1  0.50000000  0.50000000  0.76721920  1.0
  O  O3  1  0.73278080  0.50000000  0.00000000  1.0
  O  O3  1  0.26721920  0.50000000  0.00000000  1.0
  O  O3  1  0.50000000  0.73278080  0.00000000  1.0
  O  O3  1  0.50000000  0.26721920  0.00000000  1.0
  O  O3  1  0.50000000  0.00000000  0.73278080  1.0
  O  O3  1  0.50000000  0.00000000  0.26721920  1.0
  O  O3  1  0.73278080  0.00000000  0.50000000  1.0
  O  O3  1  0.26721920  0.00000000  0.50000000  1.0
  O  O3  1  0.50000000  0.23278080  0.50000000  1.0
  O  O3  1  0.50000000  0.76721920  0.50000000  1.0
  O  O3  1  0.00000000  0.50000000  0.73278080  1.0
  O  O3  1  0.00000000  0.50000000  0.26721920  1.0
  O  O3  1  0.23278080  0.50000000  0.50000000  1.0
  O  O3  1  0.76721920  0.50000000  0.50000000  1.0
  O  O3  1  0.00000000  0.73278080  0.50000000  1.0
  O  O3  1  0.00000000  0.26721920  0.50000000  1.0

### Expected Behavior

maybe StructureMatcher should at least check Spacegroup number to make sure it matches before it returns True (two structures match)?

### Minimal example

```Python
from pymatgen.core import Structure
from pymatgen.analysis.structure_matcher import StructureMatcher
import pandas as pd 
import glob

def PMD(structure1, structure2):
    #cdvae(ltol=0.3, stol=0.5, angle_tol=10)
    #ma-condition_cond-cdvae(ltol=0.2,stol=0.3, angle_tol=5)
    sm = StructureMatcher(ltol=0.3, stol=0.5,angle_tol=10) #
    
    try:
        fit = sm.fit(structure1, structure2)
    except:
        fit = "N/A"
    return fit


path1 = f"Ba2EuTaO6.cif"
path2 = f"CSPML_Ba2EuTaO6.cif"
structure1 = Structure.from_file(path1)
structure2 = Structure.from_file(path2) 

answer=PMD(structure1, structure2)
print(answer)
```

**Comment by shyuep** [comment]
This is a feature not a bug. We have stated explicitly that StructureMatcher is based on coordinate mapping. Unless the coordinates are highly precise and the same tolerances are used, two matched structures do not need to have the same space group.

**Comment by usccolumbia** [comment]
This report is supposed to be regarded as a warning to the users or improvements needed to the documentation

It seems quite many users use this structureMatcher results for calculating success rate in crystal structure prediction, which is misleading due to Pymatgen document reads like this:
https://pymatgen.org/pymatgen.analysis.html#pymatgen.analysis.structure_matcher.StructureMatcher

fit(xxxx)
Return type:
bool
True if the structures are equivalent   

But if the space groups of the two structures are not even identical, we cannot declare they are equivalent.
so maybe you can add a warning in the documentation. (e.g. this function does not check if the space groups of two structures to be identical, for strict structure match, it is suggested).

**Comment by shyuep** [comment]
I don't think your interpretation is correct. Say you have two structures A and B that are exactly the same - say a bcc metal. You move one of the atoms in B by 0.05 A in a certain direction. That breaks symmetry and so, B has space group Pm-3m if you are using a tight tolerance for symmetry determination. Structure A still has Im-3m spacegroup. For the purposes of structure matching, the two structures are the same. In fact, for crystal structure prediciton purposes, the two structures are effectively the same - if you relax both structures properly in DFT, they end up in the same final coordinates.

If you wish to force a more stringent check, you can always use SpaceGroupAnalyzer to first compare spacegroups before doing structure matching.
