### ISSUE TITLE
Suggestion for plotter & boltztrap in pymatgen.electronic_structure

### ISSUE THREAD

**Issue by specter119** [materialsproject/pymatgen#392]
Here is your corrected markdown:

---

## System
- Pymatgen version: 3.6.0 (pip)
- Python version: 2.7.11
- OS version: OSX 10.11.5

## Summary
- Should add `kl` to [plot_zt_mu](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/electronic_structure/plotter.py#L1114)
- Have a choice to sort three eigenvalues of power factor, `zt` etc. (in [BoltztrapAnalyzer class](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/electronic_structure/boltztrap.py#L664))

## Reasons
1. Add `kl` to [plot_zt_mu](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/electronic_structure/plotter.py#L1114):  
   I think it is easy to add `kl` to `plot_zt_mu`, therefore this method could plot `zt` with `kl` other than default 0.2.
2. Choose to sort eigenvalues:  
   The plot methods like [plot_zt_mu](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/electronic_structure/plotter.py#L1114) will get a figure in which the red line is always above the other two lines, because the eigenvalues are sorted 
   according to ascending order. I think it should obtain unsorted values especially when plotting.

## Suggested solution (if any)
- Adding `kl` is very straightforward, and I've done it locally:  

In [line 1115 of plotter.py](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/electronic_structure/plotter.py#L1114)

```python
def plot_zt_mu(self, temp=600, output='eig', relaxation_time=1e-14,
               kl=0.2, xlim=None):
```

In [line 1129 of plotter.py](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/electronic_structure/plotter.py#L1129)

```python
zt = self._bz.get_zt(relaxation_time=relaxation_time, output=output,
                     kl=kl, doping_levels=False)[temp]
```
- I've tried to remove `sorted()` from [_format_to_output](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/electronic_structure/boltztrap.py#L1351), but nothing happened.

**Comment by specter119** [comment]
@shyuep @computron will someone help me to apply the Feature request label to this issue?

**Comment by computron** [comment]
@specter119 - just find the "labels" button on the right of the page, click the gear icon, and then click "Feature request"

**Comment by shyuep** [comment]
Seems like this issue has been defunct for 7 years. Closing....
