### ISSUE TITLE
Adapt pymatgen.symmetry.analyzer to new spglib (>=2.5.0) output data format

### ISSUE THREAD

**Issue by kaueltzen** [materialsproject/pymatgen#3922]
### Feature Requested

The recent spglib release v2.5.0 changed the output data types from dict to new classes like SpglibDataset.
https://spglib.readthedocs.io/en/stable/releases.html#v2-5-0-9-jul-2024

The dict-like interface is planned to be removed, so it will be necessary to adapt the pymatgen interface in the near future.

### Proposed Solution

For now, modifiying the version of spglib to <2.5.0 in pyproject.toml might be best - @DanielYang59 already confirmed that this fixes the failing `test_get_crystal_system` in tests/symmetry/test_analyzer.py (https://github.com/materialsproject/pymatgen/pull/3859#issuecomment-2228279612), so that test can be re-included @shyuep

**Comment by DanielYang59** [comment]
I'm happy to implement this change :)

**Comment by JaGeo** [comment]
Thanks @DanielYang59 !! 😀
