### ISSUE TITLE
Inputset YAML format should allow setting **kwargs

### ISSUE THREAD

**Issue by computron** [materialsproject/pymatgen#396]
The DictVaspInputSet allows setting two types of properties

1. config_dict - i.e., INCAR, KPOINTS, etc. params
2. kwargs - e.g., force_gamma, ediff_per_atom, etc.

Currently, it seems that the YAML format of DictVaspInputSet only supports the config_dict parameters. However, I would like to do things like specify in a YAML that a particular input set should be able to do something like (i) force gamma or (ii) make sure ediff_per_atom is set False, i.e. for dielectric runs. Currently, those "type 2" modifications cannot be put in the YAML file.

I would like to have the "type 2" mods also be part of the YAML file. An easy way is to just have a key called kwargs in the YAML file that gets shipped as **kwargs to the DictVaspInputSet

**Comment by shyuep** [comment]
Can you see if the new BuiltInConfig set does what you want?

**Comment by shyuep** [comment]
Also done for DictSEt.
