### ISSUE TITLE
Strain Transformation

### ISSUE THREAD

**Issue by costrouc** [materialsproject/pymatgen#397]
[Feature Request]

I would like to contribute to the pymatgen project and I found a feature that I do not believe is available for Transformations.

Is there a `StrainTransformation` like object that I am missing in the transformation module?

Best,
Chris

**Comment by shyuep** [comment]
I think the most recent code has a DeformationTransformation. That was just added two days ago.

**Comment by costrouc** [comment]
Found it `pymatgen.transformations.standard_transformations.DeformStructureTransformation`

Thanks
