### ISSUE TITLE
Problem parsing some cif files?

### ISSUE THREAD

**Issue by cajfisher** [materialsproject/pymatgen#3971]
### Python version

Python 3.11.5

### Pymatgen version

2024.2.8

### Operating system version

Windows 11

### Current behavior

The cif file below produces a "non-stoichiometric" error:
io/cif.py:1134: UserWarning: Incorrect stoichiometry:
  CIF={'O': 5.0, 'Si': 2.0}
  PMG={'Si': 12.0, 'O': 24.0}
  ratios={'Si': 6.0, 'O': 4.8}
  warnings.warn(cif_failure_reason)

### Expected Behavior

Different Wyckoff sites can have different multiplicities, so I don't think simply taking the ratio between number of total sites and number of Wyckoff sites is a good indicator of stoichiometry. Please correct me if I am wrong.

### Minimal example

```Python
parser = CifParser('MVY.cif', occupancy_tolerance=1.0, site_tolerance=0.00005)
```

### Relevant files to reproduce this bug

data_MVY

_cell_length_a                   5.0210(0)
_cell_length_b                   8.1510(0)
_cell_length_c                  13.9770(0)
_cell_angle_alpha               90.0000(0)
_cell_angle_beta                90.0000(0)
_cell_angle_gamma               90.0000(0)

_symmetry_space_group_name_H-M     'P n n m'
_symmetry_Int_Tables_number         58
_symmetry_cell_setting             orthorhombic

loop_
_symmetry_equiv_pos_as_xyz
'+x,+y,+z'
'-x,-y,+z'
'1/2-x,1/2+y,1/2-z'
'1/2+x,1/2-y,1/2-z'
'-x,-y,-z'
'+x,+y,-z'
'1/2+x,1/2-y,1/2+z'
'1/2-x,1/2+y,1/2+z'

loop_
_atom_site_label
_atom_site_type_symbol
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
    O1    O     0.1370    0.2998    0.2713
    O2    O     0.2777    0.2676    0.0952
    O3    O     0.5000    0.5000    0.1981
    O4    O     0.0000    0.0000    0.5000
    O5    O     0.5000    0.0000    0.5000
    T1    Si    0.3882    0.3151    0.2000
    T3    Si    0.2501    0.8772    0.5000

**Comment by cajfisher** [comment]
Sorry about the large font

**Comment by cajfisher** [comment]
Not so much a bug as providing misinformation or unnecessary warning. Sorry about the mislabeling.

**Comment by JaGeo** [comment]
@cajfisher Thank you for reporting this. Could you check a newer version of pymatgen and see if this error still persists? (We had this pull request recently: https://github.com/materialsproject/pymatgen/pull/3628)

**Comment by cajfisher** [comment]
Pull request #3628 appears to have dealt with this issue already. The latest version gives the following warning:
io\cif.py:1285: UserWarning: Issues encountered while parsing CIF: Skipping relative stoichiometry check because CIF does not contain formula keys.
  warnings.warn("Issues encountered while parsing CIF: " + "\n".join(self.warnings))

This makes more sense.
Sorry for the repetition. I'll make sure to run tests on the most up-to-date version next time.

**Comment by JaGeo** [comment]
@cajfisher I will close this then
