### ISSUE TITLE
Bug in NearNeighbors Class

### ISSUE THREAD

**Issue by andrewxiang25** [materialsproject/pymatgen#3975]
### Python version

3.11.2

### Pymatgen version

2024.4.13

### Operating system version

MacOS Ventura 13.5.1 (22G90)

### Current behavior

When using the NearNeighbors class functions like get_nn_info(), get_all_nn_info(), and get_nn_shell_info(), the function is unable to read all the input parameters. 

For example, when using _NearNeighbors.get_nn_shell_info(mystructure, 0, 1)_, error reports that "NearNeighbors.get_nn_shell_info() missing 1 required positional argument: 'shell'". 

A similar error occurs for other functions, instead of not being able to receive the argument for "shell", they cannot receive the argument for an integer n, which is the last argument. 

### Expected Behavior

get_nn_shell_info() should return a list of dictionaries. Each entry in the list is information about a certain neighbor in the structure.

### Minimal example

```Python
from pymatgen.core import Lattice, Structure, Element
from pymatgen.analysis.local_env import NearNeighbors 

# Define the lattice parameters for NaCl (a = 5.64 Å)
a = 5.64
lattice = Lattice.cubic(a)

# Define the atomic positions for NaCl
# Na at (0, 0, 0), Cl at (0.5, 0.5, 0.5) in fractional coordinates
structure = Structure(
    lattice,
    ["Na", "Cl"],  # Species
    [[0, 0, 0], [0.5, 0.5, 0.5]]  # Fractional coordinates
)
print(structure)
#use argument 0 for the index site: the Na site, argument 1 for the first neighbor shell
NearNeighbors.get_nn_shell_info(structure,0,1)
```

### Relevant files to reproduce this bug

<img width="307" alt="Screenshot 2024-08-05 at 4 19 59 PM" src="https://github.com/user-attachments/assets/46a3fcf8-ddce-431c-a96c-f2b62b94aceb">

<img width="677" alt="Screenshot 2024-08-05 at 4 19 44 PM" src="https://github.com/user-attachments/assets/cb074a84-58ad-4a2a-bb4e-b7bbb27d587e">

**Comment by shyuep** [comment]
This is not how you use NearestNeighbor. You are supposed to use one of the other analysis tools to get a NearestNeighbor object. This is not a bug. Please refer to the documentation and python tutorial on how such classes work.
