### ISSUE TITLE
Kpoints Sampling Saved as Float When Writing Kpoints file

### ISSUE THREAD

**Issue by yutoml** [materialsproject/pymatgen#3993]
### Python version

Python 3.10.14

### Pymatgen version

Version: 2024.7.18

### Operating system version

Red Hat Enterprise Linux Ver 8.6

### Current behavior

When using the `Kpoints` class from `pymatgen.io.vasp.inputs` to read a Gamma-centered KPOINTS file and then write it back, the fourth line of the KPOINTS file is converted to a float string. This causes VASP5.4.4 calculations to fail when using this file. Specifically, in the `from_str` method of the Kpoints class, the fourth line of the KPOINTS file is cast to `kpts` as `Sequence[tuple[float, float, float]]`. The `kpts` attribute is then handled as a sequence of floats throughout the process, and it is written back as floats.

### Expected Behavior

When writting a Gamma-centered KPOINTS file, the number of K-point divisions should  be cast to a int, or it should be explicitly cast to an integer when writing the file if the style is Gamma-centered or  Monkhorst-Pack. 
Initially, the `kpts` attribute of the Kpoints class was handled as `list[int]` in `from_str` method, but it was changed to `Sequence[tuple[float, float, float]]` in #3758. While this change itself is not problematic, it would be more convenient if `kpts` were an integer sequence for Gamma-centered or Monkhorst-Pack.

### Minimal example

```Python
#The following source code is a simplified code that reproduces this problem.
#The fourth line of the KPOINTS file resulting from the output of this code is `3.0 3.0 3.0`.

from pymatgen.io.vasp.inputs import Kpoints

Kpoints_str = """\
An example
0
Gamma
3    3    3
0.0  0.0  0.0"""

kpoints = Kpoints.from_str(Kpoints_str)
kpoints.write_file("KPOINTS")
```

**Comment by DanielYang59** [comment]
Hi thanks for reporting and sorry for the troubled caused. I could confirm the issue and would fix ASAP.
