### ISSUE TITLE
For high symmetry molecules like Carborane PointGroupAnalyzer gives value error: max() arg is an empty sequence

### ISSUE THREAD

**Issue by navnidhirajput** [materialsproject/pymatgen#400]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System
Pymatgen version: pymatgen-3.6.1
Python version: Python 2.7.9
OS version: OSX El Capitan 10.11.3

## Summary

For high symmetry molecules like Carborane PointGroupAnalyzer gives value error: max() arg is an empty sequence. It works fine for smaller anions such as TFSI.

## Example code

from monty.os.path import zpath
from pymatgen import Molecule
from pymatgen.io.qchem import QcOutput
from pymatgen.symmetry.analyzer import PointGroupAnalyzer
qcout = QcOutput(zpath("mol.qcout.gz"))
data = qcout.data
mol = data[0]["molecules"][-1]
pga = PointGroupAnalyzer(mol)

## Error message

 File "/global/u1/n/nrajput/nr_test/codes/pymatgen/pymatgen/symmetry/analyzer.py", line 743, in __init__

    self._analyze()

  File "/global/u1/n/nrajput/nr_test/codes/pymatgen/pymatgen/symmetry/analyzer.py", line 784, in _analyze

    self._proc_sph_top()

  File "/global/u1/n/nrajput/nr_test/codes/pymatgen/pymatgen/symmetry/analyzer.py", line 996, in _proc_sph_top

    main_axis, rot = max(self.rot_sym, key=lambda v: v[1])

ValueError: max() arg is an empty sequence

## Files (if any)

Dropbox link: https://www.dropbox.com/s/k2e1g1sif8tin8z/mol.qcout?dl=0

**Comment by shyuep** [comment]
Can you try to implement a fix with a unittest? This should be relatively easy?
