### ISSUE TITLE
[Question] Why do we set SIGMA in INCAR for MPRelaxSet when ISMEAR is -5? 

### ISSUE THREAD

**Issue by DanielYang59** [materialsproject/pymatgen#4004]
### Summary

Why do we set SIGMA in INCAR for MPRelaxSet when ISMEAR is -5 ([SIGMA would be ignored in this case](https://www.vasp.at/wiki/index.php/ISMEAR))? Is it going to be corrected by #3322?
> Mind: [SIGMA](https://www.vasp.at/wiki/index.php/SIGMA) is ignored for the tetrahedron method.

https://github.com/materialsproject/pymatgen/blob/6427b556ea82f364ff4b619dfbcdf7fd7169cce7/src/pymatgen/io/vasp/MPRelaxSet.yaml#L11
https://github.com/materialsproject/pymatgen/blob/6427b556ea82f364ff4b619dfbcdf7fd7169cce7/src/pymatgen/io/vasp/MPRelaxSet.yaml#L80

**Comment by shyuep** [comment]
Because it doesn't matter whether it was set if ISMEAR=-5? And if we set SIGMA to 0, then 0.05 is the default value we use.

**Comment by DanielYang59** [comment]
Thanks for the reply! 

> Because it doesn't matter whether it was set if ISMEAR=-5?

Sounds like it might be better to exclude SIGMA for tetrahedron method and include it later. But anyway, we get the same results.
