### ISSUE TITLE
New issue with `ChemicalPotentialDiagram` on Website

### ISSUE THREAD

**Issue by kavanase** [materialsproject/pymatgen#4010]
### Python version

N/A

### Pymatgen version

?

### Current behavior

Hi!
On the Materials Project website, I just noticed there seems to be an issue with parsing the input chemical system for the Chemical Potential Diagram visualisations. This was working fine before, so I guess it's related to a recent `web` client update?

e.g. when I input `"Cs-Sn-Br"` as the chemical system, it seems to only be taking the first letter of each element, and so actually gives me `"C-S-B"`:
![image](https://github.com/user-attachments/assets/12051c44-ddf6-4233-a613-d186ea4d3770)

For the phase diagram code though, it seems to be fine:
![image](https://github.com/user-attachments/assets/f760c0c6-8021-4cae-b424-c62cfee075e9)

### Expected Behavior

...

**Comment by shyuep** [comment]
Please report this to the Materials Project (feedback@materialsproject.org). Pymatgen does not handle MP website queries.
