### ISSUE TITLE
[Dev] Remove `mysql` dependency from `ext.cod` and fix S608

### ISSUE THREAD

**Issue by DanielYang59** [materialsproject/pymatgen#4016]
- Resolve following `mysql` dependency issue: https://github.com/materialsproject/pymatgen/blob/41e4c69911f2b724734e0917c436ee5a1de63091/src/pymatgen/ext/cod.py#L70
- Also need to fix two `S608` violations (SQL injection): https://github.com/materialsproject/pymatgen/blob/41e4c69911f2b724734e0917c436ee5a1de63091/src/pymatgen/ext/cod.py#L73
 https://github.com/materialsproject/pymatgen/blob/41e4c69911f2b724734e0917c436ee5a1de63091/src/pymatgen/ext/cod.py#L109

Help needed.

**Comment by janosh** [comment]
> * Resolve following `mysql` dependency issue:

i think `mysql` can be replaced with https://pypi.org/project/mysqlclient (based on [the advice here](https://pypi.org/project/mysql/))

**Comment by shyuep** [comment]
Why bother? This is a small feature within pymatgen and we probably can count on a few fingers the number of people who use it. Those who use it can install mysql. In fact, the onus should be on COD to offer a REST API rather than an SQL one. Pls focus efforts on more impactful changes.

**Comment by DanielYang59** [comment]
> This is a small feature within pymatgen and we probably can count on a few fingers the number of people who use it. Those who use it can install mysql.

That's true, I posted this in case someone who need to frequently use SQL might be interested to take over and fix this?

> Pls focus efforts on more impactful changes.

Can we reopen this? This looks like a good first issue if anyone is interested in getting involved.
