### ISSUE TITLE
[DOCS] Links to source in each function returns a 404 error

### ISSUE THREAD

**Issue by tawe141** [materialsproject/pymatgen#4030]
The main pymatgen code now falls under a src parent directory, but in the documentation (as of 2024.8.9 at least), this change caused all of the hyperlinks for each function pointing to the code in Github to fail. Pretty easy fix, just need to add "src" in the link to point to the right files.

**Comment by DanielYang59** [comment]
Thanks for reporting @tawe141.  I could confirm this and would fix soon.
