### ISSUE TITLE
noncollinear attribute of Outcar class has wrong value for VASP calculations with LNONCOLLINEAR=.TRUE.

### ISSUE THREAD

**Issue by KylinGuo** [materialsproject/pymatgen#4031]
### Python version

Python 3.11.0

### Pymatgen version

2024.7.18

### Operating system version

Ubuntu 22.04 LTS

### Current behavior

I expect that `outcar.noncollinear` is `True` for noncollinear calculations. But I got `False`.

### Expected Behavior

I expect that `outcar.noncollinear` is `True` for noncollinear calculations.

### Minimal example

```Python
from pymatgen.io.vasp.outputs import Outcar
outcar = Outcar(filename='OUTCAR')
print(outcar.noncollinear)  # 'True' for LNONCOLLINEAR=.TRUE.
```
```


### Relevant files to reproduce this bug

_No response_

**Comment by janosh** [comment]
could you share the `OUTCAR` file so we can repro?

**Comment by KylinGuo** [comment]
> ```python
> ```python
> print(outcar.noncollinear)  # 'True' for LNONCOLLINEAR=.TRUE.
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

Yes. Please check the attached file (Please remove the suffix .txt).
[OUTCAR.txt](https://github.com/user-attachments/files/16846108/OUTCAR.txt)

**Comment by DanielYang59** [comment]
Thanks. I was able to reproduce this with the OUTCAR attached. Looks like the pattern match failed:
https://github.com/materialsproject/pymatgen/blob/edcd4654cc5048d7f0f00417d82755d98b03b739/src/pymatgen/io/vasp/outputs.py#L2114-L2118

**Comment by DanielYang59** [comment]
Yep the logic should be reversed. would fix this. Thanks!
