### ISSUE TITLE
deprecated sets - EDIFF_PER_ATOM

### ISSUE THREAD

**Issue by computron** [materialsproject/pymatgen#404]
I think that MPVaspInputSet.yaml should use EDIFF_PER_ATOM (not EDIFF) to maintain the old behavior of deprecated sets. Just confirming this is true rather than pushing the change directly.

I don't think this affects any of the new input sets either way...

**Comment by computron** [comment]
(this also pertains to a few others like MITVaspInputSet, MPHSEVaspInputSet)

**Comment by shyuep** [comment]
The new input sets are called MPRelaxSet.yaml. And it retains EDIFF_PER_ATOM of the old MPVaspInputSet..

**Comment by shyuep** [comment]
The old MPVaspInputSet.yaml is only used by the old deprecated sets.

**Comment by computron** [comment]
I know ... that's also what my message says. In order to maintain the behavior of the old deprecated sets, it should be EDIFF_PER_ATOM for those. I am trying to make sure that people who are using deprecated sets (not me) don't have different behavior in their runs.

**Comment by shyuep** [comment]
It will not have that problem. The logic in the old deprecated sets is different. EDIFF is interpreted as per atom by default and you have to supply ediff_per_atom=False to cause it to be interpreted as absolute. In fact, the old input sets don't even support EDIFF_PER_ATOM. 

The new input sets (which uses a different set of YAML) interprets EDIFF_PER_ATOM and EDIFF differently.

**Comment by computron** [comment]
Ok got it
