### ISSUE TITLE
BUG: INCAR Updates not working

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/pymatgen#4051]
Currently, this line  https://github.com/materialsproject/atomate2/blob/f14586c7b29a7d5cbf7eabfe399728ab6362e0e7/src/atomate2/vasp/files.py#L195 does not have the intended effect of updating the INCAR. 

This reproduces the error: 
```py
from atomate2.vasp.sets.base import VaspInputGenerator

from mp_api.client import MPRester

mpr = MPRester()
structure = mpr.get_structure_by_material_id("mp-84")

vis = VaspInputGenerator().get_input_set(
    structure=structure, potcar_spec=True
)
print(vis.incar)
vis.incar.update({"NPAR": 4})

print(vis.incar)

```

(pymatgen version: 2024.8.9)

**Comment by esoteric-ephemera** [comment]
Thanks for finding / correcting this!
