### ISSUE TITLE
don't set ISYM=0 for NCSFVaspInputSet (?)

### ISSUE THREAD

**Issue by computron** [materialsproject/pymatgen#407]
The NCSFVaspInputSet by default forces ISYM = 0.

I am thinking to change this so that ISYM is left alone, i.e., if the scf run was done with ISYM=1, to leave that setting the same for the nscf run. It is trivial to implement but I want to make sure this procedure is correct, hence the ticket.

Any objections / comments / suggestions?

**Comment by shyuep** [comment]
I have no objection, but I will leave the rest to comment. My suspicion is that you set ISYM to 0 to avoid symmetrization of the charge density. Does it really matter? This is a one step run. I doubt the cost is very much different.

**Comment by computron** [comment]
Ok I am going to leave it as is for now. In some (static scf) HSE runs I have been finding that ISYM=0 is leading to very different (lower energy) configurations than ISYM=1. To be on the safe side I will leave it as ISYM=0.

**Comment by matk86** [comment]
in hse as well as beyond dft  calculations (gw etc that involve the calculation of the susceptibility \chi) degenerate or near degenerate eigen values are 'cleaned up'(set to same value) for ISYM>0
