### ISSUE TITLE
`pymatgen.analysis.structure_matcher.StructureMatcher.fit()` does not work properly on structures with `selective_dynamics` property

### ISSUE THREAD

**Issue by yutoml** [materialsproject/pymatgen#4085]
### Python version

Python 3.10.14

### Pymatgen version

Version: 2024.9.17

### Operating system version

Red Hat Enterprise Linux Ver 8.6

### Current behavior

A `Poscar` object created from a POSCAR string with Selective Dynamics stores `selective_dynamics` as a NumPy array of booleans. However, these arrays cannot be directly compared using the `==` operator.
This error can be easily demonstrated with the following code:
```
import numpy as np
site_prop_1 = {"selective_dynamics": np.array([True, True, False])}
site_prop_2 = {"selective_dynamics": np.array([True, True, False])}
print(site_prop_1 == site_prop_2)
# -> ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
This error can cause issues during the `pymatgen.analysis.structure_matcher.StructureMatcher.fit()` process. A simple example using `StructureMatcher.fit()` will be provided later.

Just to be clear, I'm using NumPy ver. 1.26.0.

### Expected Behavior

It is desirable that the structure variable of a Poscar object created by Poscar.from_str can be directly compared using StructureMatcher.fit() without any additional processing such as casting to a list.

### Minimal example

```Python
from pymatgen.analysis.structure_matcher import StructureMatcher
from pymatgen.io.vasp.inputs import Poscar

poscar_string = """\
H
1.0
   1.000    0.000   0.000
   0.000    1.000   0.000
   0.000    0.000   1.000
H
1
Selective dynamics
direct
0.000    0.000    0.000 F F T H
"""
poscar1 = Poscar.from_str(poscar_string)
poscar2 = Poscar.from_str(poscar_string)

structure1 = poscar1.structure
structure2 = poscar2.structure

sm = StructureMatcher()
sm.fit(struct1=structure1, struct2=structure2)
```

**Comment by DanielYang59** [comment]
Thanks for the detailed diagnosis, I could recreate this
