### ISSUE TITLE
Replace POTCAR in MPRelaxSet

### ISSUE THREAD

**Issue by TDKOLI** [materialsproject/pymatgen#4106]
### Feature Requested

When users run MPGGARelax or any other workflow requiring MPRelaxSet, and the structures contain elements like tungsten (W), they encounter a "POTCAR not found" error. This issue arises because the newer PBE 54 pseudopotential set no longer includes W_pv, which is still expected by MPRelaxSet. However, I am unsure if replacing W_pv with the newer W potential affects the compatibility of the results with those generated by the Materials Project. 

### Proposed Solution

Update MPRelaxSet

**Comment by esoteric-ephemera** [comment]
Yes this impacts compatibility with the Materials Project entries. You can use the `MPScanRelaxSet` which uses the PBE_54 pseudopotentials and will be compatible with the newer materials project r2SCAN data

**Comment by TDKOLI** [comment]
Ok, thank you. I see. Btw, if I want to use GGA data, instead of recalculate with MPScanRelaxSet, could I use MP GGA(+U)/R2SCAN mixing adjustment to do the energy adjustment?

**Comment by TDKOLI** [comment]
Ok, thank you. I see.
