### ISSUE TITLE
VaspInput setter and Incar.check_params() are inconsistent

### ISSUE THREAD

**Issue by yantar92** [materialsproject/pymatgen#4119]
### Python version

Python 3.12.4

### Pymatgen version

2024.7.18

### Current behavior

When I set INCAR parametrs via `vasp_input['INCAR']['PARAM']=value`, they do not always pass `Incar.check_params()` checks.

Using the example below, I am getting:

```
...: BadIncarWarning: ENCUT: 550 is not a float
  vasp_input.incar.check_params()
...: BadIncarWarning: GGA: Cannot find Ps in the list of values
  vasp_input.incar.check_params()
```

### Expected Behavior

Setting the parameters passes the checks.

### Minimal example

```Python
from pymatgen.io.vasp.inputs import VaspInput
vasp_input = VaspInput.from_directory('.')
vasp_input['INCAR']['GGA'] = "MK"
vasp_input['INCAR']['GGA']
```

### Relevant files to reproduce this bug

I used the following INCAR
```
ALGO = Normal
ENCUT = 550
ISMEAR = 0
NCORE = 16
SIGMA = 0.04
SYSTEM = C.hexagonal.191
```
Other requried inputs may be anything.

**Comment by DanielYang59** [comment]
Thanks for reporting this, I believe the warning on `GGA=PS` is owing to: https://github.com/materialsproject/pymatgen/blob/4f7aa35f15cb17a89209b955903c64b39e2fa922/src/pymatgen/io/vasp/inputs.py#L988

I.e. any keyword not included inside the following would be capitalized: https://github.com/materialsproject/pymatgen/blob/4f7aa35f15cb17a89209b955903c64b39e2fa922/src/pymatgen/io/vasp/inputs.py#L876-L932

---

The warning on `ENCUT=550` should be owing to the incorrect classification of it into `int_keys` instead of `float_keys`: https://github.com/materialsproject/pymatgen/blob/4f7aa35f15cb17a89209b955903c64b39e2fa922/src/pymatgen/io/vasp/inputs.py#L910-L924

I believe [it should be a float](https://www.vasp.at/wiki/index.php/ENCUT):
> ENCUT = [real]

**Comment by yantar92** [comment]
With Version: 2024.10.22, I am still getting

```
/net/home/plgrid/plgyantar92/groupdir/functional-input.py:70: BadIncarWarning: Cannot find ZAB_VDW in the list of INCAR tags
  vasp_input.incar.check_params()
/net/home/plgrid/plgyantar92/groupdir/functional-input.py:70: BadIncarWarning: GGA: Cannot find Ml in the list of values
  vasp_input.incar.check_params()
```

**Comment by DanielYang59** [comment]
Hi thanks for following up. I just have a look and I believe it's a separate issue related to #4042, i.e. we need to update the `incar_parameters.json` record.

`ZAB_VDW` is currently not in the recorded INCAR tags, and `GGA` doesn't have `ML` in the recording yet: https://github.com/materialsproject/pymatgen/blob/3ee17e2c346dea6e9248eb04c989e58880914650/src/pymatgen/io/vasp/incar_parameters.json#L191-L218

But currently I don't have a better way other than doing that manually (which would be very inefficiently) given the amount of possible INCAR tags and their values. Updating the tags should be easier with: https://github.com/materialsproject/pymatgen/blob/3ee17e2c346dea6e9248eb04c989e58880914650/src/pymatgen/io/vasp/help.py#L68-L83

But updating the values is a bit tricky so I assume we need to helper script to do this? Would you be interested? If not I'm happy to get my hands on this a bit later :)

**Comment by yantar92** [comment]
> But updating the values is a bit tricky so I assume we need to helper script to do this? Would you be interested? If not I'm happy to get my hands on this a bit later :)

```python
    @classmethod
    def get_incar_tags(cls) -> list[str]:
        """Get a list of all INCAR tags from the VASP wiki."""
        url = ("https://www.vasp.at/wiki/api.php?"
               "action=query&list=categorymembers"
               "&cmtitle=Category:INCAR_tag"
               "&cmlimit=500&format=json")
        response = requests.get(url, timeout=60)
        response_dict = json.loads(response.text)

        def extract_titles(data):
            """Extract keywords from from Wikimedia response data.
            See https://www.vasp.at/wiki/api.php?action=help&modules=query
            Returns: List of keywords as strings.
            """
            return [category_data['title'] for category_data
                    in data['query']['categorymembers']]

        tags = extract_titles(response_dict)
        while 'continue' in response_dict:
            response = requests.get(
                url + f"&cmcontinue={response_dict['continue']['cmcontinue']}",
                timeout=60
            )
            response_dict = json.loads(response.text)
            tags = tags + extract_titles(response_dict)

        return tags
```

**Comment by DanielYang59** [comment]
> I can make it into pull request if you wish.

That would be hugely appreciated! You might have misread my previous comment https://github.com/materialsproject/pymatgen/issues/4119#issuecomment-2432250673

Current we already have a method to get the (tags/keywords/parameters): https://github.com/materialsproject/pymatgen/blob/0e65d35ae0b1df964639a48067b1a525979eec84/src/pymatgen/io/vasp/help.py#L68-L70

---

What we need is something to update the values, which is a bit tricky. Currently VASP wiki doesn't seem to provide an API to get possible values of a tag directly (do they?), and the webpage format seems pretty inconsistent and probably make scraping infeasible (I'm not a web scraping expert and I wish I'm wrong here).

For example the ALGO tag page seems to list all possible values at the start:
<img width="1318" alt="image" src="https://github.com/user-attachments/assets/a65bbb83-237d-4589-9728-822dd3d3af3e">

However the GGA tag only listed a small portion and left the rest inside a table: 
<img width="775" alt="image" src="https://github.com/user-attachments/assets/883a0336-2ded-4d5e-ae3c-5d5e26dcb1ed">

**Comment by yantar92** [comment]
> What we need is something to update the values, which is a bit tricky. Currently VASP wiki doesn't seem to provide an API to get possible values of a tag directly (do they?),

I do not see anything either.

>  the webpage format seems pretty inconsistent and probably make scraping infeasible (I'm not a web scraping expert and I wish I'm wrong here).

Scaping is possible, but awkward. One will need to write the scaper specifically for this page and add a number of asserts to catch incompatible changes (those are unlikely in practice though).

I looked into the source of the page at https://www.vasp.at/wiki/index.php?title=GGA&action=edit
and it looks like they define the tag list simply within a table, not using a template (template would make scaping much easier).

It should be still possible to write a dedicated scraper, via pymediawiki + wikitexparser, but non-standard pages like the one for GGA will need to have a specially tailored handler.

I think that the most productive course of action here would be asking VASP maintainers to list all the possible keys in their TAGDEF template (the template defining GGA = PE | ... line) for this page and maybe for other pages with the same problem.

**Comment by DanielYang59** [comment]
> I think that the most productive course of action here would be asking VASP maintainers to list all the possible keys in their TAGDEF template

It sounds like the best option to me, not sure what is the best approach to reach out though, perhaps through [the VASP forum](https://www.vasp.at/forum/)?

**Comment by yantar92** [comment]
Yup, the forus. I see no better options on https://www.vasp.at/wiki/index.php/The_VASP_Manual#Support

**Comment by DanielYang59** [comment]
> I am wondering if incar_parameters.json can be used to populate proc_val key/type associations.

This absolutely makes sense, currently we have type recording in both `proc_val` method and `incar_parameters.json`, but both are not really updated/validated. But I guess currently the biggest issue is that we don't have a programmatic way to retrieve such entries from VASP wiki.

> I think that the most productive course of action here would be asking VASP maintainers to list all the possible keys in their TAGDEF template (the template defining GGA = PE | ... line) for this page and maybe for other pages with the same problem.

Did you have time to reach out to them and request such feactures maybe? I might have a closer look later and see if I could find some interface to do the job :)

**Comment by yantar92** [comment]
> Did you have time to reach out to them and request such feactures maybe?

It is on my todo list, but not a high priority. I will follow up if I post something on the forum.
