### ISSUE TITLE
Question about conventional cell standards defined by `get_conventional_standard_structure` in pymatgen.

### ISSUE THREAD

**Issue by hongyi-zhao** [materialsproject/pymatgen#4126]
Hello pymatgen developers,

I've been examining the documentation for [`get_conventional_standard_structure`](https://pymatgen.org/pymatgen.symmetry.html#pymatgen.symmetry.analyzer.SpacegroupAnalyzer.get_conventional_standard_structure) and [`HighSymmKpath`](https://pymatgen.org/pymatgen.symmetry.html#pymatgen.symmetry.bandstructure.HighSymmKpath), and I've noticed a discrepancy that I'd like to understand better.

In [`HighSymmKpath`](https://pymatgen.org/pymatgen.symmetry.html#pymatgen.symmetry.bandstructure.HighSymmKpath), there are three options for the `path_type` parameter:
- 'setyawan_curtarolo'
- 'hinuma'
- 'latimer_munro'

These different conventions allow for flexibility in generating high symmetry paths.

However, in [`get_conventional_standard_structure`](https://pymatgen.org/pymatgen.symmetry.html#pymatgen.symmetry.analyzer.SpacegroupAnalyzer.get_conventional_standard_structure), the method seems to use only one standard, defined by [Setyawan & Curtarolo (2010)](https://doi.org/10.1016/j.commatsci.2010.05.010). The documentation states:

> The standards are defined in Setyawan, W., & Curtarolo, S. (2010). High-throughput electronic band structure calculations: Challenges and tools. Computational Materials Science, 49(2), 299-312. doi:10.1016/j.commatsci.2010.05.010

My question is: Why doesn't [`get_conventional_standard_structure`](https://pymatgen.org/pymatgen.symmetry.html#pymatgen.symmetry.analyzer.SpacegroupAnalyzer.get_conventional_standard_structure) offer similar options for different conventions, as seen in [`HighSymmKpath`](https://pymatgen.org/pymatgen.symmetry.html#pymatgen.symmetry.bandstructure.HighSymmKpath)? 

Would it be beneficial to implement multiple standards for conventional cell generation, allowing users to choose between different conventions (e.g., Setyawan & Curtarolo, Hinuma et al., and Latimer & Munro) similar to how [`HighSymmKpath`](https://pymatgen.org/pymatgen.symmetry.html#pymatgen.symmetry.bandstructure.HighSymmKpath) operates?

I'm curious about the rationale behind this design decision and whether there are plans to expand the options for conventional cell standards in future versions of pymatgen.

Thank you for your time and consideration.

Best regards,
Zhao

**Comment by JaGeo** [comment]
Dear @hongyi-zhao ,

I think the different kpath scheme implementations have been made as a part of this publication: https://doi.org/10.1038/s41524-020-00383-7

Historically, MP used the scheme by 'setyawan_curtarolo first. That's why the prinitive and content cells are implemented like this. I assume implementing the different conventional cell types simply wasn't necessary for the publication above at the time.

I am not aware of any plans to extend this. Tagging @mkhorton @tschaume @munrojm to see if they might know/remember more.

**Comment by JaGeo** [comment]
Btw, https://github.com/materialsproject/pymatgen/blob/v2024.10.3/src/pymatgen/symmetry/bandstructure.py#L27-L391 also clearly says that the convention from setyawan_curtarolo is used as a starting point for the generation of all 3 schema in this class.
