### ISSUE TITLE
Kpoints.from_file sometimes override the comment

### ISSUE THREAD

**Issue by yantar92** [materialsproject/pymatgen#4130]
### Python version

Python 3.12.4

### Pymatgen version

Version: 2024.10.22

### Current behavior

Given the following example KPOINTS file
```
pymatgen with grid density = 10000 / number of atoms
0
Gamma
19 19 6
```
Upon reading it, I am getting kpt.comment value  'Automatic kpoint scheme'

### Expected Behavior

I expect Kpoints object to capture the file comment and kpt.comment have the value "pymatgen with grid density = 10000 / number of atoms".

### Minimal example

```Python
from pymatgen.io.vasp.inputs import Kpoints
pt=Kpoints.from_file('KPOINTS')
pt.comment
```

**Comment by DanielYang59** [comment]
Thanks for reporting this, yes I could confirm this. 

Meanwhile it seems comments are not passed for some other modes as well, I would fix this.

https://github.com/materialsproject/pymatgen/blob/3ee17e2c346dea6e9248eb04c989e58880914650/src/pymatgen/io/vasp/inputs.py#L1594

https://github.com/materialsproject/pymatgen/blob/3ee17e2c346dea6e9248eb04c989e58880914650/src/pymatgen/io/vasp/inputs.py#L1617
