### ISSUE TITLE
assimilate method in SimpleVaspToComputedEntryDrone is not raising ValueError

### ISSUE THREAD

**Issue by igor-s-tan** [materialsproject/pymatgen#4132]
### Python version

Python 3.12.3

### Pymatgen version

2024.10.22

### Operating system version

Ubuntu 22.04 LTS

### Current behavior

assimilate method in apps.borg.hive.SimpleVaspToComputedEntryDrone is not raising the ValueError when checking if all the necessary files are present ("INCAR", "POTCAR", "CONTCAR", "OSZICAR", "POSCAR"). Instead, the method returns None, i think it happens because the raise keyword is placed inside the try statement.

### Expected Behavior

assimilate method should correctly detect the absence of required VASP files.

### Minimal example

```Python
from pymatgen.apps.borg.hive import SimpleVaspToComputedEntryDrone
drone = SimpleVaspToComputedEntryDrone()
entry = drone.assimilate(".")
print(entry)
```

**Comment by DanielYang59** [comment]
Thanks for reporting this and your investigation. I could confirm this issue.

On top of the reason you mentioned, there's another subtle bug in: https://github.com/materialsproject/pymatgen/blob/bd9fba9ec62437b5b62fbd0b2c2c723216cc5a2c/src/pymatgen/apps/borg/hive.py#L229-L239

When `files` has no match, calling `files[0]` would trigger an IndexError, this is also suppressed by the except.
