### ISSUE TITLE
Poscar.from_file throws a cryptic error for VASP5-like POSCARs when POTCAR does not contain all the present elements

### ISSUE THREAD

**Issue by yantar92** [materialsproject/pymatgen#4140]
### Python version

Python 3.12.7

### Pymatgen version

Version: 2024.10.22

### Current behavior

Consider the following scenario:
1. We have a POSCAR file in VASP5 format with, say, C and Na sites
2. We have an obsolete POTCAR file only specifying C potentials
3. We try to read the POSCAR using Poscar.from_file

When I do try it, I get an error like:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yantar92/.venv/lib/python3.12/site-packages/pymatgen/io/vasp/inputs.py", line 282, in from_file
    return cls.from_str(file.read(), names, read_velocities=read_velocities)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yantar92/.venv/lib/python3.12/site-packages/pymatgen/io/vasp/inputs.py", line 478, in from_str
    struct = Structure(
             ^^^^^^^^^^
  File "/home/yantar92/.venv/lib/python3.12/site-packages/pymatgen/core/structure.py", line 3956, in __init__
    super().__init__(
  File "/home/yantar92/.venv/lib/python3.12/site-packages/pymatgen/core/structure.py", line 1051, in __init__
    raise StructureError(f"{len(species)=} != {len(coords)=}")
pymatgen.core.structure.StructureError: len(species)=1 != len(coords)=721
```

Such error is extremely hard to understand.

I note that the error is not exactly a bug - docstring of from_file method does say that POTCAR symbols take priority by default. However, (1) it is very hard to understand what is going on from the error thrown; (2) the existing behaviour does not make much sense for VASP5 POSCARs where the symbol names are explicitly specified.

### Expected Behavior

Ideally, I'd like Poscar.from_file fall back to using POSCAR symbols if POTCAR does not specify them all and throw a warning.

### Minimal example

```Python
from pymatgen.io.vasp.inputs import Poscar, Potcar
Poscar.from_file('POSCAR')
```

### Relevant files to reproduce this bug

[POSCAR.tar.gz](https://github.com/user-attachments/files/17531141/POSCAR.tar.gz)

I cannot share the POTCAR file because of license terms, but here is the spec:
```python
[PotcarSingle(symbol='C', functional='PBE', TITEL='PAW_PBE C 08Apr2002', VRHFIN='C: s2p2', n_valence_elec=4)]
```

**Comment by DanielYang59** [comment]
Thanks for reporting again. Yes I agree this error message is not semantic, I'm happy to have a closer look later.

For the time being, you could use `check_for_potcar=False` to turn off the default POTCAR check.

```python
poscar = Poscar.from_file("./POSCAR", check_for_potcar=False)
```

**Comment by yantar92** [comment]
> If you want to read a POSCAR with an incompatible POTCAR in the same directory, you may want to use check_for_potcar=False to turn off the POTCAR check.

Unfortunately, I have no such option.

I think I need to elaborate on the _actual_ problem I encountered.

My code is the following

```python
            # No VASP output found.  Try to ingest VASP input.
            vasp_input = VaspInput.from_directory(self.directory)
            self.structure = vasp_input['POSCAR'].structure

            super().__post_init__()

            self.prev_incar = vasp_input['INCAR']
            self.prev_kpoints = vasp_input['KPOINTS']
```

As you can see, I am not calling `Poscar.from_file` directly. I am using `VaspInput.from_directory`, which is then calling `Poscar.from_file` internally and throwing the observed error.

That's why I objected the existing behaviour and instead proposing throwing a warning and reading the POSCAR anyway (the POSCAR itself is perfectly valid).

Another option would be throwing some catchable error, so that I can at least handle this specific scenario via try/catch. For now, I cannot even do that because the observed error in indistinguishable from a real problem with POSCAR.

**Comment by DanielYang59** [comment]
Thanks for the input!

>  I am using VaspInput.from_directory, which is then calling Poscar.from_file internally and throwing the observed error.

I believe this is intended to "force" user to make a VASP runner "VASP input set" and therefore POTCAR check is mandatory, I cannot think of any reason not to use a "good" POTCAR in this regard?

I agree the error message should be clarified, but I don't have a good reason to change the default POTCAR checking behaviour of `VaspInput.from_directory`

**Comment by yantar92** [comment]
> I believe this is intended to "force" user to make a VASP runner "VASP input set" and therefore POTCAR check is mandatory, I cannot think of any reason not to use a "good" POTCAR in this regard?

In my case, there is an existing VASP input directory where the POSCAR is modified manually (well, using a custom script). Then, I wanted to re-generate the POTCAR according to the new POSCAR. I could read the files separately, but using VaspInput looked like a better option.

> I agree the error message should be clarified, but I don't have a good reason to change the default POTCAR checking behaviour of VaspInput.from_directory

Your call. Having a better error is good enough for my needs.

**Comment by DanielYang59** [comment]
> Your call. Having a better error is good enough for my needs.

I'm not a maintainer, nor the person to unilaterally say no to a possible feature and you are free to open a separate PR if you believe this is a needed

**Comment by DanielYang59** [comment]
An alternative approach to turn off POTCAR checking might be the following (set `PMG_POTCAR_CHECKS` to False in your PMG config file):

https://github.com/materialsproject/pymatgen/blob/4b10dd3fb37d8012d46dee58678ac3a695845104/src/pymatgen/io/vasp/inputs.py#L272-L276

**Comment by DanielYang59** [comment]
While I was trying to fix this, I realized the bug is actually more suitable than I thought (I confirmed the bugger behaviour on my end).

With current implementation:
https://github.com/materialsproject/pymatgen/blob/4b10dd3fb37d8012d46dee58678ac3a695845104/src/pymatgen/io/vasp/inputs.py#L421-L428

As long as the number of elements in POTCAR (`len(default_names)`) is greater or equal to elements in POSCAR, this check block would pass (and leading to the cryptic error you noticed), regardless of what element is inside because it just checked the length, not the value.

I have added test to guard against this in #4143
