### ISSUE TITLE
The inappropriate warnning info for `update_user_incar_settings`.

### ISSUE THREAD

**Issue by hongyi-zhao** [materialsproject/pymatgen#4179]
When I tested an atomate2 flow, I noticed the following information:
```shell
In [7]: flow = update_user_incar_settings(flow, { 'ALGO': 'Normal', 'EDIFF': 1e-06, 'ENCUT':700})
/home/werner/.pyenv/versions/3.11.1/envs/datasci/lib/python3.11/site-packages/pymatgen/io/vasp/sets.py:288: BadInputSetWarning: Overriding the POTCAR functional is generally not recommended  as it significantly affects the results of calculations and compatibility with other calculations done with the same input set. Note that some POTCAR symbols specified in the configuration file may not be available in the selected functional.
  warnings.warn(
```
This is an inappropriate warning message. Because I update INCAR here, the warning is indeed related to POTCAR.

Regards,
Zhao

**Comment by QuantumChemist** [comment]
Hey Zhao,
Could you elaborate a little bit why exactly this warning is inappropriate?

**Comment by hongyi-zhao** [comment]
I mean, this warning should triggered by `update_user_potcar_functional` instead of `update_user_incar_settings`.

**Comment by esoteric-ephemera** [comment]
Can you move this over to atomate2 with a complete code snippet? I don't think this is a pymatgen issue
