### ISSUE TITLE
spacegroupanalyzer returns spacegroup number as long() type

### ISSUE THREAD

**Issue by computron** [materialsproject/pymatgen#421]
Spacegroup analyzer returns spacegroup number as "*long*" type, e.g.:

```
sga = SpacegroupAnalyzer(structure)
print(type(sga.get_spacegroup_number()))
```

This is not a problem when working purely in Python, but inserting *long* types into MongoDB causes them to be cast to String - so that spacegroup numbers are strings in MongoDB.

Either you can leave things be, or you can simply cast to *int* before returning the spacegroup num - in which case you are introducing a backward incompatibility for anyone who uses both the old and new code to put spacegroup nums into MongoDB. Up to you ...

**Comment by dwinston** [comment]
Python `long` values are not cast to String values in MongoDB. They are stored as [NumberLong](https://docs.mongodb.com/manual/core/shell-types/#numberlong)s in MongoDB, i.e. 64-bit integers.

I tried to reproduce your issue, but I could not. I tried MongoDB 3.2 and 2.6, and I'm using pymongo 3.2 and pymatgen 3.7.1, although I don't think this has ever been an issue with MongoDB/pymongo. Please provide a reproduction, with pymatgen/pymongo/MongoDB versions.

**Comment by computron** [comment]
Thanks for looking into this -

I think the problem is actually in the fact that I am using jsanitize() before db insertion:
```
p = Poscar.from_file("POSCAR")
sym_finder = SpacegroupAnalyzer(p.structure, symprec=0.1)
x =  sym_finder.get_spacegroup_number()

print type(x), type(jsanitize(x, allow_bson=True))
```

prints:

```<type 'long'> <type 'str'>```

The three ways forward are:

1. Do nothing
2. Return int in spacegroupanalyzer (this is what the method signature says) instead of long
3. Update jsanitize() so that it handles long, especially with allow_bson=True

**Comment by dwinston** [comment]
I recommend both 2 and 3. I've submitted a [PR](https://github.com/materialsvirtuallab/monty/pull/29) for 3 in the monty repo. I think jsanitize() should pass through long unconditionally, as `json.dumps` supports serializing `long`s.

And yes, I can think of no reason to store an integer vale ranging from 1 to 230 in a `long`.
