### ISSUE TITLE
For band structure, how to correctly display the symbol of the \Gamma point

### ISSUE THREAD

**Issue by phyfang** [materialsproject/pymatgen#4214]
### Python version

python--3.12

### Pymatgen version

2024.11.13

### Operating system version

Win-11

### Current behavior

When I was drawing the band structure, I found some problems that the gamma points were not displayed correctly.
![？？](https://github.com/user-attachments/assets/72a2a8fa-a297-49ac-87c4-bd0af7210722)

### Expected Behavior

How should I solve this problem?

**Comment by DanielYang59** [comment]
I guess it's related to #4025 (looks like `Gamma` is not escaped properly somewhere). I might open a PR later and let's fix this together @QuantumChemist ?

**Comment by QuantumChemist** [comment]
> I guess it's related to #4025 (looks like `Gamma` is not escaped properly somewhere). I might open a PR later and let's fix this together or you would fix this @QuantumChemist ?

yeah, as you gave me access to your fork, let's fix this together. Or was that not intended? When it's just escaping the `Gamma` correctly, the PR shouldn't take long I guess.

**Comment by DanielYang59** [comment]
>  as you gave me access to your fork, let's fix this together. Or was that not intended?

It was 100% intended, free feel to commit to my future PRs as well :)

> When it's just escaping the Gamma correctly, the PR shouldn't take long I guess.

Yep, I guess it wouldn't be a hard fix, but I would need to fix some data (perhaps from current tests) to recreate this as I don't have data at hand right now.

**Comment by phyfang** [comment]
> Dear @phyfang , could you further describe how you try to plot the bandstructure? Depending on what you do, it helps to put \Gamma in backticks (``) like `\Gamma` .

Thanks for your reply, I changed the 'GAMMA' in KPOINTS to '\Gamma' and it solved.

**Comment by DanielYang59** [comment]
@phyfang If you don't mind, can you share the code you used to generate the plot?

**Comment by QuantumChemist** [comment]
> It was 100% intended, free feel to commit to my other/future PRs as well :)

Sure 🤗 let's see how and where I can help out.

> Update: I just tried the BS plotter at

I also remembered that I didn't have a problem with the BSplotter before (and there were no recent changes I guess), as you can see at the end of the following page: https://autoatml.github.io/autoplex/user/phonon/flows/flows.html

**Comment by QuantumChemist** [comment]
> @phyfang If you don't mind, can you share the code you used to generate the plot?

I'm not sure if phonopy uses the KPOINTS file atm, but probably in the KPOINTS file, instead of using the mesh, putting the kpoint path explicitly with labels for the critical points.

**Comment by phyfang** [comment]
> @phyfang If you don't mind, can you share the code you used to generate the plot?

ok
`import matplotlib.pyplot as plt
from pymatgen.io.vasp.outputs import Vasprun
from pymatgen.electronic_structure.plotter import BSDOSPlotter

# get bs
band_structure = Vasprun(r"vasprun.xml", parse_projected_eigen=True)
band_data = band_structure.get_band_structure(line_mode=True) 
# get Dos
dos_vasprun = Vasprun(r"E:\DFT\dos\vasprun.xml" )
dos_data = dos_vasprun.complete_dos
# plot
banddos_fig = BSDOSPlotter(bs_projection='elements', dos_projection='orbitals', vb_energy_range=0.5, fixed_cb_energy=False, cb_energy_range=0.5)
banddos_fig.get_plot(bs=band_data, dos=dos_data)
plt.savefig('banddos.png')`
original KPOINTS
`K-Path Generated by VASPKIT.
   40
Line-Mode
Reciprocal
   0.0000000000   0.0000000000   0.0000000000     Γ        
   0.5000000000   0.5000000000   0.0000000000     Y              
 
   0.5000000000   0.5000000000   0.0000000000     Y              
   0.5000000000   0.5000000000   0.5000000000     M              
 
   0.5000000000   0.5000000000   0.5000000000     M              
   0.0000000000   0.0000000000   0.5000000000     A              
 
   0.0000000000   0.0000000000   0.5000000000     A              
   0.0000000000   0.0000000000   0.0000000000     Γ          
 
   0.0000000000   0.5000000000   0.5000000000     L_2            
   0.0000000000   0.0000000000   0.0000000000     Γ          
 
   0.0000000000   0.0000000000   0.0000000000     Γ          
   0.0000000000   0.5000000000   0.0000000000     V_2 `

changed
`K-Path Generated by VASPKIT.
   40
Line-Mode
Reciprocal
   0.0000000000   0.0000000000   0.0000000000     \Gamma        
   0.5000000000   0.5000000000   0.0000000000     Y              
 
   0.5000000000   0.5000000000   0.0000000000     Y              
   0.5000000000   0.5000000000   0.5000000000     M              
 
   0.5000000000   0.5000000000   0.5000000000     M              
   0.0000000000   0.0000000000   0.5000000000     A              
 
   0.0000000000   0.0000000000   0.5000000000     A              
   0.0000000000   0.0000000000   0.0000000000     \Gamma          
 
   0.0000000000   0.5000000000   0.5000000000     L_2            
   0.0000000000   0.0000000000   0.0000000000     \Gamma          
 
   0.0000000000   0.0000000000   0.0000000000     \Gamma          
   0.0000000000   0.5000000000   0.0000000000     V_2`

**Comment by QuantumChemist** [comment]
Thank you a lot for sharing your code @phyfang 😃

**Comment by DanielYang59** [comment]
Hi @QuantumChemist sorry for the delay but I don't think that really resolves the issue, as VASP docs also use `Γ` for labeling Gamma point (so we cannot ask users to overwrite all `Γ` with `\Gamma`).

As far as I know, this is an encoding issue in Windows (i.e. the encoding is not explicitly set in `zopen`) when parsing KPOINTS from file (as text) (looks like @phyfang's system might be using `GB2312` which is the default encoding for Chinese): https://github.com/materialsproject/pymatgen/blob/31f1e1fb8cc1bb517d59ea8e484965bb641c42a0/src/pymatgen/io/vasp/inputs.py#L908-L909

You could check the encoding with `[System.Text.Encoding]::Default` from PowerShell on Windows.

I know you're working on Linux, and the default encoding on Windows is a bit complicated and [dependent on locale encoding](https://docs.python.org/3/library/locale.html#locale.getencoding):
> On Unix, return the encoding of the current [LC_CTYPE](https://docs.python.org/3/library/locale.html#locale.LC_CTYPE) locale. Return "utf-8" if nl_langinfo(CODESET) returns an empty string: for example, if the current LC_CTYPE locale is not supported.

> On Windows, return the ANSI code page.

So in a word, that issue is not specific to plotter but more general to KPOINTS parsing where the user's default encoding is not "UTF-8", I guess we still need to fix it.

**Comment by QuantumChemist** [comment]
Hi @DanielYang59 , oh I see where the issue arises from then.
I have never seen `Γ` in a KPOINTS file before and myself always used \Gamma, so I was not even aware that this is possible at all. 🫨
