### ISSUE TITLE
Error when parsing structure from gulp output with pymatgen.command_line.gulp_caller.GulpIO.get_relaxed_structure(gout)

### ISSUE THREAD

**Issue by bcr48** [materialsproject/pymatgen#441]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>
## System
- Pymatgen version: 3.7.1
- Python version: 2.7.8
- OS version: Linux Fedora, release 21 
- GULP version: 4.4
## Summary

The pymatgen.command_line.gulp_caller.GulpIO.get_relaxed_structure(gout) method is not parsing the structure from gulp output, even though the gulp calculation ran properly and the gulp output contains the relaxed structure.
## Here is an example script that will cause the error, along with the provided gulp input file (example.gin). It is assumed that the example.gin file is located in the current working directory, and that gulp is installed and can be called with the command "gulp", which needs to be in the path.

```
import os
from pymatgen.command_line.gulp_caller import GulpCaller, GulpIO

# make GulpCaller and GulpIO objects
gulp_caller = GulpCaller()
gulp_io = GulpIO()

# get the working directory
current_dir = os.getcwd()

# get the gulp input from the file and put it in a string
gin_file = open(current_dir + '/example.gin', 'r')
gulp_input = gin_file.read()

# run gulp via GulpCaller.run() and store the output as a string
gulp_output = gulp_caller.run(gulp_input)

# print gulp output to a file for reference 
gout_file = open(current_dir + '/example.gout', 'w')
gout_file.write(gulp_output)

# parse the relaxed structure from the gulp output using GulpIO.get_relaxed_structure
relaxed_structure = gulp_io.get_relaxed_structure(gulp_output)  # this line causes the error
```
## Error message

```
Traceback (most recent call last):
  File "gulp_io_error.py", line 23, in <module>
    relaxed_structure = gulp_io.get_relaxed_structure(gulp_output) # this line causes the error
  File "/n/srv/brevard/venv/lib/python2.7/site-packages/pymatgen/command_line/gulp_caller.py", line 468, in get_relaxed_structure
    raise IOError("No structure found")
IOError: No structure found
```
## Suggested solution

I noticed that the GulpIO.get_relaxed_structure(gout) method searches for the following string when trying to parse the positions of the atoms from the gulp output:

"Final fractional coordinates of atoms"

However, this string is not contained in the gulp output (written to example.gout by the script above). Instead, it looks like the atomic positions are given after this string:

"Final asymmetric unit coordinates"

I think modifying the GulpIO.get_relaxed_structure(gout) method to search for this string will solve the problem.
## The gulp input file (example.gin) has been pasted below.

```
opti conp conj
switch_minimiser bfgs gnorm 0.02
cell
3.14234315719 3.14993532397 3.68431921347 94.7366201574 104.887692682 74.1046376087
frac
Au core 0.431215374033 0.708509636366 0.676326109399
Au core 0.994879647339 0.196971981584 0.135903401186
space
2
lennard 12 6
Au core Au core 214180.2000 625.482 40.000 0 0
```

**Comment by mbkumar** [comment]
Is this the new behavior of GULP or is the output specific to your input file?

**Comment by bcr48** [comment]
It's specific to this input file. I have since run GULP on different systems/input files, and the output did contain the string:

"Final fractional coordinates of atoms"

**Comment by shyuep** [comment]
Seems like this issue has been defunct for 7 years. Closing....
