### ISSUE TITLE
Key Error when parsing projected band structure for spin-orbit coupling VASP runs

### ISSUE THREAD

**Issue by blondegeek** [materialsproject/pymatgen#445]
A Key Error is returned when BSVasprun(parse_projected_eigen=True).get_band_structure() is used to read spin-orbit coupling VASP runs.

## Example code

```python
# while this works:
vasp_run = BSVasprun('vasprun.xml')
bs = vasp_run.get_band_structure(line_mode=True)

# this throws a key error:
vasp_run = BSVasprun('vasprun.xml',parse_projected_eigen=True)
bs = vasp_run.get_band_structure(line_mode=True)
```

## Error message

```
Traceback (most recent call last):
  File "plot_band.py", line 6, in <module>
    bs = vasp_run.get_band_structure(line_mode=True)
  File "/usr/local/lib/python2.7/site-packages/pymatgen/io/vasp/outputs.py", line 702, in get_band_structure
    dict_eigen = self.as_dict()['output']['eigenvalues']
  File "/usr/local/lib/python2.7/site-packages/pymatgen/io/vasp/outputs.py", line 1280, in as_dict
    beigen = peigen[kpoint_index][str(spin)][band_index]
KeyError: '-1'
```

**Comment by shyuep** [comment]
Can you post an example SOC file?

**Comment by blondegeek** [comment]
Hi Shyue Ping, 

[Here are example vasprun.xml and KPOINTS files for a SOC band structure run. (The vasprun.xml is bigger than github allows for posts)](https://www.dropbox.com/sh/esiw6o6rao3w2c4/AAA0ezVqpkEMpCGAp6horVGVa?dl=0)

I made a temporary fix of the key error today that is sufficient for making BSPlotterProjected plots which effectively treats SOC runs as non spin-polarized (only looking at the projected charge density not the three component spin density). 

It's currently part of the color_band branch of my forked repository which also has some additional plot options for BSPlotterProjected (get_color_grouped and get_color_sites). See the last diff for pymatgen/io/vasp/outputs.py on [this page](https://github.com/blondegeek/pymatgen/commit/92433c059df5ae522633319ff744b70640f2ffed). 

If this fix seems good enough for now, I can clean up my color_band branch and make a pull request or I can make a pull request with just the changes that fix the key error.

Let me know what you think is best.

Thanks!
Tess

**Comment by shyuep** [comment]
ok. Though I think this is a reasonable fix, I would actual prefer proper parsing of SOC bandstructures. I just implemented a change. Pls see if it works,

**Comment by blondegeek** [comment]
This fixes the key error. Thanks!
