### ISSUE TITLE
Significant mismatch between the bandgap values computed by bandstructure class and Dos class

### ISSUE THREAD

**Issue by matk86** [materialsproject/pymatgen#449]
## System
- Pymatgen version:  master branch
- Python version: 3.5
- OS version: ubuntu 16.04
## Summary
-  difference in gap of about 0.27 for Silicon(NEDOS=601 in INCAR)
-  the value reported by Bandstructure object matches the value reported on the materialsproject(mp-149)
## Example code

``` python
from pymatgen.io.vasp.outputs import Vasprun

vrun = Vasprun("vasprun.xml.gz")

bs = vrun.get_band_structure()
print("FROM BS\nvbm:{}, cbm:{}, fermi:{}, gap:{}".format(bs.get_vbm()["energy"],
                                                bs.get_cbm()["energy"],
                                                bs.efermi,
                                                bs.get_band_gap()["energy"]))

dos = vrun.complete_dos
print("FROM DOS\nvbm:{}, cbm:{}, fermi:{}, gap:{}".format(dos.get_cbm_vbm()[1],
                                                dos.get_cbm_vbm()[0],
                                                dos.efermi,
                                                dos.get_gap()))

```
## Output

```
FROM BS
vbm:5.614, cbm:6.2243, fermi:5.63746936, gap:0.6103000000000005

FROM DOS
vbm:5.2918, cbm:6.1767, fermi:5.63746936, gap:0.8849

```
## Files (if any)

[vasprun.xml.gz](https://drive.google.com/file/d/0B3SvuOHwFoR7dXVUMTNpdzh5eUk/view?usp=sharing)

**Comment by shyuep** [comment]
Don't think this is a bug? Band gap determination is ultimately a exercise in tolerances. The DOS and BS classes use different methods of determining the gap. In general, I would argue the DOS gives a much better band gap than the BS estimate.

**Comment by matk86** [comment]
the default tolerance for dos is 0.001. also the indirect gap reported on materialsproject is 0.6

**Comment by shyuep** [comment]
Yes, but that's MP's problem. In general, the gap obtained from a much finer mesh in a DOS run is better than using the bandstructure. 

MP should in fact be using gaps from the uniform runs, not the BS runs.

**Comment by hautierg** [comment]
I agree this is a tolerance issue.

However, the gaps are in general better from the BS along symmetry lines. This is because most of CBM and VBMs are along these lines…
Our uniform meshes are not that dense. So I would not recommend switching to using them for the gap.

Ideally, a method using by default BS along symmetry lines and checking if the uniform mesh is consistent would be the best.

Best,

Geoffroy

**Comment by hautierg** [comment]
What I mean by "this is a tolerance issue" is this is not a bug.
Just different k-point sampling give different gaps.

Geoffroy

**Comment by matk86** [comment]
i understand that between calculations with different kpoint meshes there will be differences, but for the given calculation shouldnt there be one to one match between the indirect gap obtained from bandstructure along symmtery lines and the dos ?
