### ISSUE TITLE
Structure.get_distance() -- ValueError: ndarray is not C-contiguous 

### ISSUE THREAD

**Issue by blondegeek** [materialsproject/pymatgen#456]
Hello,

I get a "ValueError: ndarray is not C-contiguous" when running the following script:

```
from pymatgen.matproj.rest import MPRester
a = MPRester()
Si = a.query({'material_id':'mp-149'},['structure']).pop()['structure']
Si.get_distance(0,1)
```

Thanks!
Tess

**Comment by shyuep** [comment]
I ran this exact code nd I did not have any error. I suspect you have a problem with your numpy setup because that sounds like a compile error. Maybe your python version and numpy compile version is not compatible.

**Comment by blondegeek** [comment]
Hi Shyue Ping,

Thanks for your time. I am getting this error when switching between different branches of my forked pymatgen repo for a editable pip installation: master which is up to date with materialsproject's repo and polarization_temp which is 447 commits behind. My master branch is having the "ValueError: ndarray is not C-contiguous" error when running get_distance() but my polarization_temp branch is not. 

The problem may be that the since the C libraries pymatgen uses are not recompiled when I'm switching branches, I'm using old, incompatible libraries for the master branch. What is the easiest way to recompile these libraries after switching branches?

Thanks,
Tess

**Comment by shyuep** [comment]
You can recompile by typing python setup.py develop. But unless you believe
the new code is going to override your changes, you should pull the layers
changes. That will usually make sure you get the bug fixes. Alternatively,
you can set up different envs.

**Comment by blondegeek** [comment]
Thanks again for your help. I'm not sure I understand what you mean by "pull the layers
changes" -- could you please explain this further?

**Comment by blondegeek** [comment]
Recompiling fixed the error. I'm surprised I haven't run into problem sooner! Thanks again!

**Comment by shyuep** [comment]
Sorry, I mean latest. Autocorrect
