### ISSUE TITLE
ImportError: cannot import name optimization

### ISSUE THREAD

**Issue by jic198** [materialsproject/pymatgen#458]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System

* Pymatgen version: <Write "branch_name" if it is development version.>
* Python version: 2.7.9
* OS version: <If you are writing Windows here, you are on your own.> 

## Summary

* <Short 1-2 bullet points stating the problem.>

## Example code

```python
from pymatgen import Structure
```

## Error message

```
ImportError                               Traceback (most recent call last)
<ipython-input-2-665dff898462> in <module>()
----> 1 from pymatgen import Structure

/Users/Jianli/Documents/pymatgen/pymatgen/__init__.py in <module>()
     35 # failures when loading shared libraries.
     36 import spglib
---> 37 from . import optimization, util
     38 del(spglib, optimization, util)
     39 

ImportError: cannot import name optimization
```

## Suggested solution (if any)

* <If you have a suggestion on how to solve the issue, you may write it
  here.>

## Files (if any)

<If input files are needed to reproduce the error, please provide 
either links (e.g., Dropbox or GDrive) for large files or simply paste
the file below for small files.>

```
<contents of file 1>
```

**Comment by shyuep** [comment]
Did you run python setup.py install or develop and there were no errors? This seems like you did not install pymatgen correctly.

**Comment by jic198** [comment]
Oh, sorry. I didn't. It's working now. Thank you, Prof Ong!
