### ISSUE TITLE
BSPlotterProjected Isssue

### ISSUE THREAD

**Issue by davgumo** [materialsproject/pymatgen#460]
Until Tuesday Night the code bellow was working perfectly fine:
from pymatgen.io.vasp import Vasprun
from pymatgen.electronic_structure.plotter import BSPlotter, BSPlotterProjected
from pymatgen.electronic_structure.core import Spin, OrbitalType
emin = -2.0
emax = 2.0
v = Vasprun("./vasprun.xml", parse_projected_eigen=True)
bs = v.get_band_structure(line_mode=True)
plotter = BSPlotterProjected(bs)
plotter.get_elt_projected_plots(zero_to_fermi=True, ylim=[emin,emax]).savefig(filename="test.png", img_format="png")

However, I upgraded to the latest version of pymatgen and now I'm getting the gollowing error:

Traceback (most recent call last):
  File "bands_test.py", line 12, in <module>
    plotter = BSPlotterProjected(bs)
  File "/home/guzmand/codes_mat/Miniconda/miniconda3/lib/python3.5/site-packages/pymatgen/electronic_structure/plotter.py", line 694, in __init__
    if len(bs._projections) == 0:
AttributeError: 'BandStructureSymmLine' object has no attribute '_projections'

Where line 12 corresponds to:
plotter = BSPlotterProjected(bs)

Any help would be very much appreciated.

Regards,
David

**Comment by shyuep** [comment]
I just pushed a fix, and also released v4.2.5 which should fix this problem. THis was due to some refactoring of the bandstructure classes.

**Comment by davgumo** [comment]
Thank you so much. Is working back again!
