### ISSUE TITLE
Custom k-point density for MPRelaxSet

### ISSUE THREAD

**Issue by montoyjh** [materialsproject/pymatgen#461]
For some of the MP workflows, the initial optimization step needs a higher k-point density than what's standard in the MPRelaxSet.  I can customize the input set by modifying the config_dict, but then when it's serialized via as_dict, my changes are lost.  I'm thinking it might be worthwhile to add a parameter to customize k-points in the MPRelax set, but am not sure if it'd more appropriate as something like "reciprocal_density" as in MPStaticSet or something more general in DictSet.

**Comment by shyuep** [comment]
There is a reciprocal density arg already?

**Comment by montoyjh** [comment]
Does this work for MPRelaxSet?  I'm getting an error:
```
>>> from pymatgen.io.vasp.sets import MPRelaxSet
>>> from pymatgen.util.testing import PymatgenTest
>>> struct = PymatgenTest.get_structure("Si")
>>> mpr = MPRelaxSet(struct, reciprocal_density=1000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/u1/m/montoyjh/envs/jhm_test_edison/codes/pymatgen/pymatgen/io/vasp/sets.py", line 414, in __init__
    structure, MPRelaxSet.CONFIG, **kwargs)
```
