### ISSUE TITLE
A question about the criterion on generating high symmetry K ponits

### ISSUE THREAD

**Issue by YunxingZuo** [materialsproject/pymatgen#462]
## System
- Pymatgen version: 4.2.5
- Python version: 2.7.11
## Summary

It seems that in generating the high symmetry K points for bandstructure calculations for the definite lattice system, the developer forgot to transfer the parameters of the sine function from degree to radian, thus may leading an error in generating the right high symmetry K points for monoclinic lattice system.
## Error message

pymatgen/symmetry/bandstructure.py:127:sin(alpha) may not be compatible with cos(alpha pi  / 180) as thought

```
<Error message>
```

**Comment by shyuep** [comment]
@hautierg Can you look into this? This seems a rather huge bug?

**Comment by shyuep** [comment]
@hautierg Any updates?

**Comment by mkhorton** [comment]
Closing, non-bug (thanks @munrojm for taking a sanity check!)
