### ISSUE TITLE
Likely an issue in SpacegroupAnalyzer.get_spacegroup()

### ISSUE THREAD

**Issue by WeiJiHsiao** [materialsproject/pymatgen#463]
Hello,
Line 102 in analyzer.py reads
```python
"""
Get the Spacegroup for the Structure.
Returns:
Spacgroup object.
"""
```
however, the SpacegroupAnalyzer.get_spacegroup() method actually returns a SpacegroupOperations object as Line 109 reads
```python
return SpacegroupOperations(self.get_spacegroup_symbol(),
                                    self.get_spacegroup_number(),
                                    self.get_symmetry_operations())
```

**Comment by WeiJiHsiao** [comment]
Thanks for fix.

But it still puzzles me.

Since there's a `get_point_group()` method which claims to return a `Pointgroup` object( actually it returns a `String`, another issue) and a `get_point_group_operations()` method which returns a `PointgroupOperations` object, it's kind of weird that there's only a `get_spacegroup()` method which returns a `SpacegroupOperations` object. What if someone needs a `Spacegroup()` object?

By the way, the `PointgroupAnalyzer.get_point_group()` method turns out to return a `PointgroupOperations` object rather than a `Pointgroup` object as the doc reads.

**Comment by shyuep** [comment]
The spacegroup object is constructed from the int number. It is mean for generating structures from scratch in a particular group.

The SpacegroupOperations is generated from the detected symmetry operations for the crystal itself. 

The two are not the same thing. 

I agree there is some inconsistency in the naming of the methods. I will refactor the method names.

**Comment by WeiJiHsiao** [comment]
I see. Thanks for your time.
