### ISSUE TITLE
Problem parsing vasprun.xml affecting many jobs

### ISSUE THREAD

**Issue by computron** [materialsproject/pymatgen#476]
## System

* Pymatgen version: master
* Python version: 2.7
* OS version: both Mac + Linux

## Summary

* Type the example code below
* You will get an error in parsing the vasprun.xml file
* This error seems to affect many high-throughput jobs

## Example code

```python
from pymatgen.io.vasp.outputs import Vasprun
vr = Vasprun("vasprun.xml.gz", parse_eigen=True, parse_projected_eigen=True)
bs = vr.get_band_structure(line_mode=False)
```

## Error message

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ajain/Documents/code_matgen/pymatgen_repo/pymatgen/io/vasp/outputs.py", line 729, in get_band_structure
    for j in range(len(kpoints))]
KeyError: u'-1'
```

## Suggested solution (if any)

* None, I haven't looked into the issue in detail

## Files (if any)

https://www.dropbox.com/sh/6equ9s91ljg3xgj/AACgTOg_h5p3t2wpHDjHSEw0a?dl=0

**Comment by computron** [comment]
Note: the files in the above Dropbox link are all you need to reproduce the error. But, if you want to look at the entire run, it is available here:

https://www.dropbox.com/sh/a0j604ek0pacjml/AABVyg7xL3HAvpN8j5TLWf8Va?dl=0

**Comment by shyuep** [comment]
Fixed, but if you have a file that is much smaller that can be used for testing, it would be great. This file is so large that parsing is monstrously slow.

**Comment by computron** [comment]
I couldn't find one that was smaller that had the exact same error, but the following file has a similar error in the older pymatgen that is now fixed

https://www.dropbox.com/sh/8g89dxlwfufpazx/AADBFp6PrTbn8Q41Qs1elpApa?dl=0
