### ISSUE TITLE
Incorrect Structure from CIF after defaulting to P1

### ISSUE THREAD

**Issue by merkys** [materialsproject/pymatgen#488]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System

* Pymatgen version: 4.3.2
* Python version: 2.7.3
* OS version: Ubuntu 12.04

## Summary

* if CIF file does not contain the list of symmetry operators (``_symmetry_equiv_pos_as_xyz`` data item), P1 space group is selected by default;
* however, this results in incorrect list of symmetry operators thus leading to incorrect structure;
* bug manifests in "linear" structures (y and z coordinates of all atoms are set to ``0.000000``).

## Example code

```python
from pymatgen import Structure
Structure.from_file("2002023.cif")
Structure.from_file("2105667.cif")
```

## Error message

```
/usr/local/lib/python2.7/dist-packages/pymatgen/io/cif.py:422: UserWarning: No _symmetry_equiv_pos_as_xyz type key found. Defaulting to P1.
  warnings.warn("No _symmetry_equiv_pos_as_xyz type key found. "
```

## Suggested solution

* I suggest taking lists of symmetry operators according to the values of ``_symmetry_space_group_name_Hall``, ``_symmetry_space_group_name_H-M`` and like tags. It should fix this issue as well as incorrect assumption of space groups.

## Files (if any)

* http://www.crystallography.net/cod/2002023.cif@186821
* http://www.crystallography.net/cod/2105667.cif@186821

**Comment by shyuep** [comment]
While this can certainly be done, I do not think it is something that is useful. The problem with taking the symmetry operations from the spacegroups is that many spacegroups have different settings. Without explicit statement of the operations, it is impossible to be sure what setting the atomic positions are given in.

**Comment by merkys** [comment]
I agree that such approach would not produce correct results in 100% cases. We at the Crystallography Open Database have tabulated the list of the most prominent space groups (https://github.com/sauliusg/cod-tools/blob/master/src/lib/perl5/COD/Spacegroups/Lookup/COD.pm, could be reused) and it produces correct results as long as all extra settings are provided.

Anyway, producing correct symmetry operators for guessed P1 space group would be enough to fix the bug for now.

**Comment by shyuep** [comment]
Actually, the CIF parser code already attempts to determine the space group from the H-M symbol. However, the symbol in this case is P121/n1, which is not the standard setting. The spacegroup class in pymatgen only contains the main standard settings, e.g., P21/c.

**Comment by shyuep** [comment]
I can certainly copy the COD.pm file and use it as a backup. IS there an issue with using the CoD.pm file?

**Comment by merkys** [comment]
I see. I haven't noticed that this case is in non-standard setting. Only issue with COD.pm is licensing, since it's a part of cod-tools package (https://github.com/sauliusg/cod-tools), which is licensed under GNU GPL v2.

**Comment by shyuep** [comment]
If it is GPL v2, then I should be able to use it. I will of course indicate it is obtained from COD.

**Comment by shyuep** [comment]
OK, I have fixed this.

**Comment by merkys** [comment]
Great, thanks!
