### ISSUE TITLE
orbital key missing in bandstructure vbm and cbm 'projections'

### ISSUE THREAD

**Issue by matk86** [materialsproject/pymatgen#500]
vrun = Vasprun(vasprun.xml.gz, parse_eigen=True, parse_projected_eigen=True)
bs = vrun.get_band_structure(line_mode=True)

before version 4.4.0 bs.get_vbm()['projections'] returned:

{Spin.up: 1: {Orbital.py: 1: array([ 0.1277,  0.1277]),
  Orbital.dxy: 4: array([ 0.,  0.]),
  Orbital.dyz: 5: array([ 0.,  0.]),
  Orbital.px: 3: array([ 0.0001,  0.0001]),
  Orbital.dxz: 7: array([ 0.,  0.]),
  Orbital.dz2: 6: array([ 0.,  0.]),
  Orbital.pz: 2: array([ 0.086,  0.086]),
  Orbital.s: 0: array([ 0.,  0.]),
  Orbital.dx2: 8: array([ 0.,  0.])}}

Now it returns:

{Spin.up: 1: array([[  0.00000000e+00,   0.00000000e+00],
        [  1.27700000e-01,   1.27700000e-01],
        [  8.60000000e-02,   8.60000000e-02],
        [  1.00000000e-04,   1.00000000e-04],
        [  0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00],
        [  0.00000000e+00,   0.00000000e+00]])}

This messes up the bandstructure serialization..

vasprun.xml file attached

[vasprun.xml.gz](https://github.com/materialsproject/pymatgen/files/526513/vasprun.xml.gz)

**Comment by shyuep** [comment]
This is not a bug. In v4.4.0, the format of the projections and eigenvalues objects are changed to a ndarray. THis is much more memory and computationally efficient. All serializations has to work with the new formats.

**Comment by matk86** [comment]
but bs.as_dict() fails with "IndexError: arrays used as indices must be of integer (or boolean) type"

**Comment by matk86** [comment]
Nevermind, no error now..my mistake
