### ISSUE TITLE
A question about the symmetry operations

### ISSUE THREAD

**Issue by YunxingZuo** [materialsproject/pymatgen#503]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System

* Pymatgen version: <Write "branch_name" if it is development version.>
* Python version: <Only 2.7.* and 3.* supported.>
* OS version: <If you are writing Windows here, you are on your own.> 

## Summary

What's the difference between the symmetry operations generated by the spglib and the symmetry operations generated in the _generate_full_symmetry_ops in pymatgen.symmetry.groups using the concept in <<Structure of Materials>>? I have tried several systems, and the spglib.get_symmetry_operations give different operations from that generated by the _generate_full_symmetry. However, both group of operations are closed.

## Example code

```python
<Example code generating error>
```

## Error message

```
<Error message>
```

## Suggested solution (if any)

* <If you have a suggestion on how to solve the issue, you may write it
  here.>

## Files (if any)

<If input files are needed to reproduce the error, please provide 
either links (e.g., Dropbox or GDrive) for large files or simply paste
the file below for small files.>

```
<contents of file 1>
```

**Comment by shyuep** [comment]
spglib's symmetry operations are those that apply to that specific crystal. For example, if you have a supercell or a different setting, the actual symmetry operations are different from those in a standard conventional setting.

The pymatgen.symmetry.groups operations are those that apply the standard conventional setting, with all atoms in their ideal symmetry positions.
