### ISSUE TITLE
Help retrieving names of all elements

### ISSUE THREAD

**Issue by protik77** [materialsproject/pymatgen#504]
Hi,

I am a new user of pymatgen and I am using version 4.4.9. I need some help. 

1. I would like to create a list of all elements. I found some example code that does the job using this:
```python
from pymatgen import MPRester, periodic_table
import itertools

allBinaries = itertools.combinations(periodic_table.all_symbols(), 2) 
```
This code is supposed to create a list of all possible binaries. Unfortunately it does not work. It seems the all_symbols() function is not available anymore. 

I would like to create a list of all elements, then retrieve their corresponding atomic numbers. Any help regarding this?

2. For a given range of atomic numbers, say 1-50 I would like to create a list of corresponding elements. How can I do this?

**Comment by shyuep** [comment]
Element is now an enum. If you want all the elements with Z 1-50, you simply do

```python
from pymatgen import Element
symbols = [Element.from_Z(z).symbol for z in range(1, 51)]
```

I should point out that the code is from citrine's website. Pls contact them if you have problem with their code.

**Comment by protik77** [comment]
@shyuep, thanks! Worked nicely. Yes, the code is from citrine's site. But I was using it for a different purpose.
