### ISSUE TITLE
importing pymatgen takes a long time

### ISSUE THREAD

**Issue by computron** [materialsproject/pymatgen#506]
## System

* Pymatgen version: master
* Python version: 2.7.x
* OS version: Mac / Linux

## Summary

* Importing pymatgen objects takes a long time
* e.g., "from pymatgen import Composition" takes about 3 seconds on my machine; on NERSC it is like 10 seconds. These times vary depending on whether you run the test multiple times in a row which will affect what files are in RAM, etc., but they are always fairly long compared to other libraries like numpy which are instantaneous
* This causes a problem if I am hacking on an analysis script with pymatgen. Rather than getting instant results, I have a major (to me) delay every time I run my code. I am currently trying to avoid importing pymatgen for as long as possible to get speed

## Example code

```python
from pymatgen import Composition
```

## Error message

<slow>

## Suggested solution (if any)

don't know

**Comment by shyuep** [comment]
I sped up the import a bit by disabling the spglib loading. But ultimately, the profiling tells me that the major factor is the creation of the Element enum type. That is however required for proper functioning. There is a way to speed up by ~50% if I disable unit checking, but that may break stuff. I will need to work this out a bit more.

That said, I am very surprised if it takes 3-10 seconds for import. By my count, it takes 1s or less.

**Comment by computron** [comment]
Thanks for looking into this:

>> That said, I am very surprised if it takes 3-10 seconds for import. By my count, it takes 1s or less.

If you want to reproduce, you can try on tscc

 * ssh to tscc
* load the matmethods environment on our project account ("use_matmethods_env")
* start a python shell
* type "from pymatgen import Composition"
* count cursor blinks as a crude approximation or write code to do a more formal test

**Comment by shyuep** [comment]
I found a way to speed up. I tried the TSCC load. It now takes ~1.1 secs. I think that's about as fast as I can make it without major surgery. Still not as fast as we would like, but not too bad.

**Comment by computron** [comment]
Ok thanks, I confirmed it is much faster on my local machine
