### ISSUE TITLE
Help retrieving lattice parameter from Materials Project data

### ISSUE THREAD

**Issue by protik77** [materialsproject/pymatgen#507]
Hi,
I am using pymatgen (v4.5.0) to retrieve material data from materials project and extract the lattice parameters. When a material data is retrieved from Materials Project, it seems the lattice parameter data is buried into the cif data. It seems there are several options to write cif data, but not so much to retrieve lattice parameters. I tried to convert the cif data into a structure. But now I cannot find a way to extract the lattice parameters. I need the a, b, c, alpha, beta and gamma. The code I wrote so far looks like this:
```
from pymatgen import Element, MPRester
from pymatgen.io.cif import CifParser

API_KEY = '<api_key>'

with MPRester(API_KEY) as m:
    
    data = m.get_data("LiBeH3")

    for mat in data:
        cif_str=str(mat['cif'])
        
        tempcif='temp.cif'
        
        with open(tempcif, 'w', newline='') as cif:
            cif.write(cif_str)
            
        parser = CifParser(tempcif)
        
        structure = parser.get_structures()[0]
        
        print(structure)
```
Is there a way to extract lattice parameters or I am missing something?

**Comment by shyuep** [comment]
This approach is far too complicated. You just need to do:

```
from pymatgen import MPRester
m = MPRester()
for s in m.get_structures("LiBeH3"):
    print(s.lattice.abc)
    print(s.lattice.angles)
```

For future reference, pls submit questions to the google groups. Github Issues are meant for actual bug reports or feature requests.

**Comment by protik77** [comment]
Thanks!

I was not aware of the google group. I looked for something like that, but could not find.

**Comment by shyuep** [comment]
It is at https://groups.google.com/forum/?fromgroups#!forum/pymatgen
