### ISSUE TITLE
Adding magCIF support

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/pymatgen#508]
## Summary

magCIF is a relatively new standard (2014) for storing structures of magnetic materials. Adding magCIF functionality to pymatgen would be useful to (a) be able to incorporate existing magCIF structures into a Materials Project workflow and (b) to allow easier visualisation of magnetically ordered structures.

I've created this issue just to check to see if anybody had already started working on this, and also to ask for general feedback on the functionality.

## Suggested solution 

I was going to:

(1) Add read support, to go from the magCIF file to a Structure object + its associated MAGMOM tag, provided that the magCIF file has ` _atom_site_moment_` information included. This should hopefully be straight-forward given that pymatgen already supports CIF.

(2) Add partial write support, to visualise Structure objects with their magnetic moments. This would write a magCIF file without any magnetic symmetry information (i.e. with primitive magnetic symmetry), but including `_atom_site_moment_` information. JMol, VESTA, etc. already support magCIF, so this could be useful for visualisation.

(3) Add full write support. To do this, we'd have to add detection of magnetic symmetry groups to pymatgen, which seems like a much larger problem for a future date... (I know spglib has partial support for collinear magnetic symmetry, but adding support for detection of any arbitrary (non-collinear) magnetic ordering seems like it's going to be a bigger task, though worth doing?).

Any feedback is welcome!

All the best,

Matthew

(p.s. To introduce myself briefly: I'll be joining Prof Persson's group at LBNL in February, and will be working on magnetic materials. As such, if there's any magnetic functionality that would be useful to add to pymatgen, please get in touch! MKHorton@lbl.gov)

**Comment by shyuep** [comment]
All this sounds good. I await your pull request!

**Comment by mkhorton** [comment]
Just to update on this, I've got a `MagCifWriter` and `MagCifParser` in testing, and also a `MagSymmOp` and I'm working on a magnetic version of `SpaceGroup` too (have constructed a JSON file from a magnetic space groups data file which we have permission to use) – this will hopefully enable an equivalent `Structure.from_magnetic_spacegroup()` method. When this is all further along in development I'll submit a PR for code review.

However, there have been a few issues that might need clarifying:

* As I can see, there are currently three representations in use for magnetic moments/spin in pymatgen. There's the list of scalar magmoms, there's the vector (list of lists) magmoms used by `MPSOCSet`, and there's the individual spin attribute on a Specie.

  At present, from a magCIF file we get a Structure with a list-of-lists magmom representation. Then, if it passes a collinear test, I convert this to a scalar magmom representation. But then `Structure.get_primitive_structure()` doesn't respect the magmom tags unless I've also added the spin attribute too (which, as I understand it, is only intended for 'idealised' spins).

  This all seems internally consistent, but it's also leading to a lot of code that's changing from one representation to another.

* All real magnetically ordered materials have vector magnetic moments. Magnetic symmetry is only properly defined with *vector* moments. So if we one day we ever add a `MagneticSymmetryAnalyzer`, we will need the vector magmom representation.

* `Structure.get_space_group_info()` returns the crystallographic symmetry if you give it a Structure with magmoms, but gives something else if you give it a Structure with spins. In the latter case, this is really useful, because it gives us a symmetry group we can use to classify collinear magnetically ordered Structures. However, this symmetry group isn't technically the magnetic symmetry, nor is it really the crystallographic symmetry, and it isn't the exchange symmetry either (which I think is a symmetry group that considers *only* the relative directions of the magnetic moments). I'm not sure if we should clarify this.

None of these issues are causing problems, but I'm wondering if anyone has any thoughts? I think having multiple representations of essentially the same quantity could end up causing confusion down the road, especially if more magnetic code is added.

**Comment by shyuep** [comment]
As a high-level framework, I suggest we (i) add support for vector magmoms since that is the most general formulation, (ii) define scalar spins as special cases of vector magmoms, e.g., spin z == z * [1, 0, 0]. I suggest we can add a separate Magmom class under electronic_structure.core.

Yes, spacegroup info right now does not really support magnetic spacegroup. We should indeed clarify that.

**Comment by mkhorton** [comment]
A separate Magmom class in electronic_structure.core definitely seems like a good way to go...

I'm just running into a big problem with disordered magnetic Structures: there's no way to have a `Composition` with multiple vector magmoms, because the magmoms are stored in a `Site.property`. As a hack, if they're scalar magmoms, I could store them in a `Composition` with `Specie`s with `spin` properties, but I can't do that with the vector magmoms. So there's just no way to correctly parse a magCIF file with a disordered magnetic structure at present.

An additional complication is that a `Specie` has optional spin but mandatory oxidation state, which means that, if oxidation state is not available, it becomes necessary to invent a fictitious oxidation state. 

At the moment, I've been putting magnetic-specific functionality in a new `analysis.magnetism` module, with a `MagneticStructure` sub-classing `Structure`. I could make a `MagneticSpecie` sub-classing `Specie`, or we could change `Specie` itself to handle this better?

**Comment by mkhorton** [comment]
Okay, I'm implementing a basic `electronic_structure.core.Magmom` class that includes support for vector or scalar magmoms, and includes an internal spin axis variable (by default [0,0,1]) to correspond with VASP's 'SAXIS' tag.

This class could then be adopted as the `magmom` site property or even as the Specie `spin` property (in the case of disordered magnetic structures, which are defined by the magCIF spec).

I added a `__float__` method to it so that existing code in e.g. `vasp.io.sets` could be trivially modified so that, for example:

```
if hasattr(site, 'magmom'):
    mag.append(site.magmom)
```

could become

```
if hasattr(site, 'magmom'):
    mag.append(float(site.magmom))
```

That way, if people continue to use old-style magmoms, pymatgen would still work as expected, but if the extra functionality is required for SOC/magnetism calculations, the new-style `Magmom` class can be used, and magCIF files can be parsed using this class by default.

How does this sound? Can submit a PR for code review if this sounds like a good approach.
