### ISSUE TITLE
Missing dependency pybtex

### ISSUE THREAD

**Issue by specter119** [materialsproject/pymatgen#519]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System

* Pymatgen version: <pip>
* Python version: <2.7.12.2>
* OS version: <Linux.> 

## Summary

should add pybtex to requirement

**Comment by shyuep** [comment]
This is deliberate. Pybtex is only used in one place. There is no need to add it as a required dependency. Also, it uses a primiive 2to3 method of maintaining Py27 and Py3k compatibility, which makes it difficult of pymatgen to create condo packages using it.
