### ISSUE TITLE
A tiny problem in ewald.py file

### ISSUE THREAD

**Issue by YunxingZuo** [materialsproject/pymatgen#520]
## System

* Pymatgen version: 4.5.2
* Python version: 2.7.11

## Summary

It seems there is a tiny problem in the **compute_average_oxidation_state** function in **ewald.py** file in the directory analysis/ewald.py for two reasons.
(1) There is no attribute **oxi_state** but **oxidation_states** in the Element class.
(2) The **oxidation_states** attribute returns a tuple which can not be summed up.

**Comment by shyuep** [comment]
EwaldSummation requires oxidation state decorated structures. That means they have Specie, which has oxi_state.
