### ISSUE TITLE
Structure.make_supercell() hangs

### ISSUE THREAD

**Issue by jmhow119** [materialsproject/pymatgen#522]
## System

* Pymatgen version: 4.5.2
* Python version: 3.5.2
* OS version: OS X 10.10.5

## Summary

* structure.make_supercell() seems to hang after a certain number of iterative updates
* copying a structure also runs into the same problem

## Example code

This will not complete:
```python
wurzite_structure = Structure.from_file("project/tmp/Cd_2_Te_2_Se_0/POSCAR")
for encut in range(100, 700, 100):
    for supercell_size in range(1, 4, 1):
        wurzite_structure.make_supercell([supercell_size, supercell_size, supercell_size])
```

This will not complete:
```python
wurzite_structure = Structure.from_file("project/tmp/Cd_2_Te_2_Se_0/POSCAR")
for encut in range(100, 700, 100):
    for supercell_size in range(1, 4, 1):
        new_structure = wurzite_structure
        new_structure.make_supercell([supercell_size, supercell_size, supercell_size])
```

This will:
```python
for encut in range(100, 700, 100):
    for supercell_size in range(1, 4, 1):
        wurzite_structure = Structure.from_file("project/tmp/Cd_2_Te_2_Se_0/POSCAR")
        wurzite_structure.make_supercell([supercell_size, supercell_size, supercell_size])
```

## Suggested solution (if any)

* This may be part of the larger structure copying problem for which an issue is already open.

## Files (if any)

This file was downloaded from the materials explorer 

```
CdTe wurtzite
1.0
4.684303 0.000000 0.000000
-2.342151 4.056725 0.000000
0.000000 0.000000 7.673695
Cd Te
2 2
direct
0.333333 0.666667 0.000092 Cd
0.666667 0.333333 0.500092 Cd
0.333333 0.666667 0.374908 Te
0.666667 0.333333 0.874908 Te
```

**Comment by shyuep** [comment]
This is not a bug. make_supercell actually modifies the structure in place. For the non-working code, you are effectively iteratively building larger and larger supercells within the same structure. That is why it never completes. The second example you wrote actually recreates the structure before making a supercell, which is why it works.

**Comment by jmhow119** [comment]
thank you for the reminder on pass by reference (or call-by-object more precisely).  I haven't dealt with this specific case of passing objects by reference in awhile.
