### ISSUE TITLE
Question about LAECHG in MPStaticSet

### ISSUE THREAD

**Issue by albalu** [materialsproject/pymatgen#533]
I was wondering why LAECHG is set to True in MPStaticSet ? Is the only goal to generate AECCAR0-2 files for bader charge analysis? If yes, keeping it as False makes a big difference as these files (AECCAR0-2) are relatively large and shouldn't be printed by default if they are not generally needed.

**Comment by shyuep** [comment]
Yes. For MP, the charges are analyzed to get an estimate of the oxidation state.

**Comment by computron** [comment]
@albalu were you saying that these files are no longer needed for Bader charge analysis in the newest VASP / bader code? Please explain further...

**Comment by albalu** [comment]
I read the website more carefully again and it turns out it's still needed and I was wrong. The way it was presented at the top mislead me to believe that the files are not needed anymore (bader chargefile) see [here](http://theory.cm.utexas.edu/henkelman/code/bader/). I tried both ways (with and without AECCAR0-2) for NiP2 and the charges were almost exactly the same. However, I haven't done this for so many materials so I can't be sure. 

All in all, it might be worth to actually do this test but base on the documentation these files are needed. 

For MatMethods, I can make a pull request to run Static w/ LAECHG=False by default.

**Comment by computron** [comment]
>> For MatMethods, I can make a pull request to run Static w/ LAECHG=False by default.

Note - let's discuss this further offline or in the MatMethods thread (i.e. not here), but we probably want to make this a config option for MatMethods with default=True.
