### ISSUE TITLE
lattice_type is not complete

### ISSUE THREAD

**Issue by wangnumber14** [materialsproject/pymatgen#540]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System

* Pymatgen version: <4.5.7.>
* Python version: <Only 2.7.* and 3.* supported.>

## Summary

* In the source code, pymatgen.symmetry.bandstructure.py, it gives all the HighSymmKpath, 
while when I use this code, I find one mistake. 

When "A" or "B" in the apg_symbol, the kpath is not supplied.

Can this type of lattice type be supplied?

## Example code

```python
<Example code generating error>
```

## Error message

```
<Error message>
```

## Suggested solution (if any)

* <If you have a suggestion on how to solve the issue, you may write it
  here.>

## Files (if any)

<If input files are needed to reproduce the error, please provide 
either links (e.g., Dropbox or GDrive) for large files or simply paste
the file below for small files.>

```
<contents of file 1>
```

**Comment by hautierg** [comment]
Our approach for high symmetry k-point follows what is proposed by Setyawan et al.: Setyawan, W.; Curtarolo, S. Comput. Mater. Sci. 2010, 49 (2), 299–312. There the face centered A and B representations are not considered. This is only a representation and those are not recommended by the crystallographic community as far as I know. I would suggest that you "standardize" the cell of your material to bring it back to a standard crystallographic representation and use that cell for your band structure (using get_primitive_standard_structure).

I will try to change the code to throw a more explicit warning or exception when the setting is A or B...
