### ISSUE TITLE
get_reconstructed_band_structure method outdated

### ISSUE THREAD

**Issue by utf** [materialsproject/pymatgen#543]
## System

* Pymatgen version: master/stable
* Python version: 2.7

## Summary

* The get `get_reconstructed_band_structure` method in `pymatgen/electronic_structure/bandstructure.py` contains references to `bs._bands` and `bs._kpoints`. These are obselete as the `BandStructure` class now uses the `bs.bands` and `bs.kpoints` attributes.

**Comment by utf** [comment]
@shyuep So unfortunately this fix doesn't work as `BandStructre.bands` are now `numpy` arrays so the line `eigenvals[Spin.up][i].append(e)` errors with:

`AttributeError: 'numpy.ndarray' object has no attribute 'append'`

This is also the case I think for `BandStructure.projections`.

I'm not sure of the cleanest way to get around this.

**Comment by shyuep** [comment]
I think @hautierg, the original author of that method, should fix this and also include unittests for the method so that future refactorings will ensure it works.
