### ISSUE TITLE
CIF test failing with Python 3.6

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/pymatgen#546]
## System

* Pymatgen version: 4.5.7
* Python version: 3.6.0
* OS version: macOS 10.12.2

## Summary

* `test_specie_cifwriter` fails in `test_cif.py`
* output of CifWriter() is basically correct, but ordering of species has changed, and thus atom labels change too

Output is:

```
   _atom_site_occupancy
   X3-  X1  1  0.500000  0.500000  0.500000  1
   Si3+  Si2  1  0.750000  0.500000  0.750000  0.5
   X3-  X3  1  0.750000  0.500000  0.750000  0.5
   Si4+  Si4  1  0.000000  0.000000  0.000000  1
```

when test expects:

```
  _atom_site_occupancy
  X3-  X1  1  0.500000  0.500000  0.500000  1
  X3-  X2  1  0.750000  0.500000  0.750000  0.5
  Si3+  Si3  1  0.750000  0.500000  0.750000  0.5
  Si4+  Si4  1  0.000000  0.000000  0.000000  1
```

## Error message

```
======================================================================
FAIL: test_specie_cifwriter (pymatgen.io.tests.test_cif.CifIOTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/work/Development/git/pymatgen/pymatgen/io/tests/test_cif.py", line 800, in test_specie_cifwriter
    self.assertEqual(l1.strip(), l2.strip())
AssertionError: 'Si3+  Si2  1  0.750000  0.500000  0.750000  0.5' != 'X3-  X2  1  0.750000  0.500000  0.750000  0.5'
- Si3+  Si2  1  0.750000  0.500000  0.750000  0.5
? ^^ ^^^^^
+ X3-  X2  1  0.750000  0.500000  0.750000  0.5
? ^ ^^^^


----------------------------------------------------------------------
```

## Suggested solution

Was previously using Python 3.5.2 without problems, where this test passes. Suspect this is due to dictionaries now being ordered in Python 3.6 (see: http://stackoverflow.com/questions/39980323/dictionaries-are-ordered-in-cpython-3-6)

Test will pass if the following is changed:

`                for sp, occu in site.species_and_occu.items():` (cif.py, line 808)

to

`                for sp, occu in sorted(site.species_and_occu.items()):`

However, I'm not sure this is the best solution. Maybe it would be better to either change `Composition` either to output a consistent ordering of species (so that it's the same between Python versions), or just change the unit test?

**Comment by shyuep** [comment]
Thanks. I implemented the fix as suggested.
