### ISSUE TITLE
Pre-link script warnings with conda install

### ISSUE THREAD

**Issue by rcthomas** [materialsproject/pymatgen#555]
## System

* Pymatgen version: 4.6.0
* Python version: 2.7.13 (Anaconda Distribution)
* OS version: Linux

## Summary

* Conda advises on installation that matsci dependencies are using dangerous pre-link scripts.
* Package matsci::palettable-2.1.1-py_0 uses a pre-link script
* Package matsci::pydispatcher-2.0.5-py_0 uses a pre-link script
* Package matsci::tabulate-0.7.7-py_0 uses a pre-link script

## Example code

```wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
bash Miniconda2-latest-Linux-x86_64.sh -b -p $(pwd)/env
export PATH=$(pwd)/env/bin:$PATH
conda update --all --yes
conda install --channel matsci pymatgen
```

## Error message

For example:

```
env/lib/python2.7/site-packages/conda/core/link.py:446: UserWarning: Package matsci::palettable-2.1.1-py_0 uses a pre-link script. Pre-link scripts are potentially dangerous.
This is because pre-link scripts have the ability to change the package contents in the
package cache, and therefore modify the underlying files for already-created conda
environments.  Future versions of conda may deprecate and ignore pre-link scripts.```

**Comment by shyuep** [comment]
This can be ignored for now.

**Comment by bkornpob** [comment]
I have this pre-link issue with mpi4py. Then, the program I ran shows... ImportError: Please install mpi4py. I use Anaconda, and "conda list" shows that mpi4py is already installed. Do you know how to fix this?
