### ISSUE TITLE
Interstitial module can not handle "symmetry_flag=True" case

### ISSUE THREAD

**Issue by wangnumber14** [materialsproject/pymatgen#561]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System

* Pymatgen version: 4.6.1
* Python version:  2.7.13

## Summary

* when I use interstitial module, and set  
interstitial=Interstitial(structure,valences,radii) 
the symmetry_flag is default True, 

then there will be some errors:
"TypeError: "NoneType" Object has no attribute '__getitem__'";

while I change the symmetry_flag to False, i.e.:
interstitial=Interstitial(structure,valences,radii,symmetry_flag=False)

the code works,

why?

## Suggested solution (if any)

* <If you have a suggestion on how to solve the issue, you may write it
  here.>

## Files (if any)

<If input files are needed to reproduce the error, please provide 
either links (e.g., Dropbox or GDrive) for large files or simply paste
the file below for small files.>

```
<contents of file 1>
```

**Comment by nisse3000** [comment]
@mbkumar, can you have a look at this issue?

**Comment by mbkumar** [comment]
This escaped my attention. I will check this at the earliest.

**Comment by shyuep** [comment]
Seems like this issue has been defunct for 7 years. Closing....
