### ISSUE TITLE
Feature request for atom projected band structure

### ISSUE THREAD

**Issue by paulfons** [materialsproject/pymatgen#566]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System

Python version 2.7 tested

## Summary

The documentation for BSPlotterProjected states "Class to plot or get data to facilitate the plot of band structure objects projected along orbitals, elements or sites", however, it is not possible to project a single site onto the band structure which can be useful for plots such as band inversion in topological insulator slabs.

## Suggested solution (if any)

The addition of a new method to class BSPlotterProjected that would enable the generation of a band structure plot onto a list of atoms and Orbitals. Minimally, it would be still useful to have the projection onto a single atom with a specified orbital.

Perhaps an extension to the dictionary-like selection procedure in the get_projected_plots_dots method of BSPlotterProjected would be a simple and general solution.

**Comment by shyuep** [comment]
@hautierg Can you assign someone to implement this pls? I think this is indeed a useful feature to have.

**Comment by shyuep** [comment]
Seems like this issue has been defunct for 6 years. Closing....
