### ISSUE TITLE
unittest2 incompatible with python 3.5

### ISSUE THREAD

**Issue by vorwerkc** [materialsproject/pymatgen#569]
I am trying to run  unittest of the master branch, but unittest2 seems incompatible with python 3.5.2
## System
pymatgen version: master branch
python version: python 3.5.2
conda version: 4.2.12
OS version: linux-64
 ## Summary
Running any test file returns:
```bash
ImportError: No module named 'unittest2'
```
and when I try to install the module, I get
```bash
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.5*
  - unittest2
```
The page [https://pypi.python.org/pypi/unittest2](https://pypi.python.org/pypi/unittest2) states that the module is a backport for unittest for python <=3.4

**Comment by bocklund** [comment]
This is a unittest2 issue. Python 3.5 was still in beta when unittest2 was last released and it seems abandoned. Do you have a reason to use unittest2?

**Comment by vorwerkc** [comment]
unittest2 is used in the pymatgen code. So the solution is to use a python version < 3.5 for unit testing until there is a release of unittest2 compatible with python 3.5?

**Comment by shyuep** [comment]
I just pushed a change that removes all unittest2. This should fix these problems. Pull the latest version.
