### ISSUE TITLE
Errors in trying to back-convert old band structures

### ISSUE THREAD

**Issue by computron** [materialsproject/pymatgen#571]
Note: only @shyuep can run the code example

## System

* Pymatgen version: master
* Python version: 2.7
* OS version: Mac

## Summary

* I am trying to back-convert old BandStructure and BandStructureSymmLine objects into the new format, and subsequently re-insert them into the database.
* I am successfully able to load the dict format of the old band structure objects into the (new) pymatgen objects
* But, calling as_dict() on those objects results in an error
* The errors seems to be the format of the "projections" key returned by the get_vbm() method. The get_vbm() seems to return an object that is {"Spin": {dict of other stuff...}} - in line with its documentation. However, the as_dict seems to expect {"Spin": [np.array of other stuff]}. Note that from_dict() seems to be consistent with as_dict(), i.e., {"Spin": [np.array of other stuff]}. I believe this is also the case for get_cbm()

## Example code

Running this code requires access to a private repo.

```python
import gridfs
import zlib
import json
from monty.json import MontyEncoder

from mqm.utils import get_mmdb
from pymatgen.electronic_structure.bandstructure import BandStructure, BandStructureSymmLine

if __name__ == "__main__":
    mmdb = get_mmdb()

    fs = gridfs.GridFS(mmdb.db, 'bandstructure_fs')

    # loop through all our old band structures
    for e in mmdb.db["bandstructure_fs.files"].find():
        # load the old band structure
        bs_json = zlib.decompress(fs.get(e["_id"]).read())
        bs_dict = json.loads(bs_json)
        if bs_dict["@class"] == "BandStructure":
            bs = BandStructure.from_dict(bs_dict)
        elif bs_dict["@class"] == "BandStructureSymmLine":
            bs = BandStructureSymmLine.from_dict(bs_dict)
        else:
            raise ValueError("Invalid @class: {}".format(bs_dict["@class"]))

        # assert: bs contains either a BandStructure or BandStructureSymmLine object
        x1 = bs.as_dict()
        x2 = json.dumps(bs.as_dict(), cls=MontyEncoder)
```

## Error message

```
Traceback (most recent call last):
  File "/Users/ajain/Documents/code_matgen/mqm/mqm/eie/phase2/fix_bandstructure_format.py", line 29, in <module>
    print(bs.as_dict())
  File "/Users/ajain/Documents/code_matgen/pymatgen_repo/pymatgen/electronic_structure/bandstructure.py", line 503, in as_dict
    'projections'].items()}}
  File "/Users/ajain/Documents/code_matgen/pymatgen_repo/pymatgen/electronic_structure/bandstructure.py", line 502, in <dictcomp>
    'projections': {str(spin): v.tolist() for spin, v in vbm[
AttributeError: 'dict' object has no attribute 'tolist'
```

## Suggested solution (if any)

* Not really...either modify as_dict() or modify get_cbm()/get_vbm() to have consistent formats. Not sure the best way of doing this w/o breaking other stuff(?) or which way is the intended format.

**Comment by shyuep** [comment]
Try to use the from_old_dict rather than from_dict method to deserialize the old format.

**Comment by computron** [comment]
Did you actually try this?

1. There is no from_old_dict() in the BandStructure class (only available for symm line band structures) and the first failure I get is for regular BandStructure
2. Anyway, I had modified BandStructureSymmLine in the past to try to do a better job of automatically using from_old_dict() when needed

I tried switching the code to "from_old_dict" for BandStructureSymmLine and get the same error.

Here is an even shorter code example which will work with any MMVaspDB in atomate:

```
mmdb = get_mmdb()
bs = mmdb.get_band_structure(199)  # this is fine
x = bs.as_dict()  # gives error
```

**Comment by computron** [comment]
here is a slightly clearer version of that code:
```
from mqm.utils import get_mmdb
mmdb = get_mmdb()
bs = mmdb.get_band_structure(199)  # this is a uniform band structure : no old dict possible!
print(type(bs))  # <class 'pymatgen.electronic_structure.bandstructure.BandStructure'>
x = bs.as_dict()
```

**Comment by shyuep** [comment]
I did push a fix that implemented from_old_dict for the BandStructure (no SymmLine) object. I tested it and seems to work?

**Comment by computron** [comment]
I missed the commit, thanks!
