### ISSUE TITLE
Defining the correct usage of HighSymmKpath

### ISSUE THREAD

**Issue by gpetretto** [materialsproject/pymatgen#581]
## Summary

I would like to signal a common misunderstanding that I have seen happen to many different people with the HighSymmKpath object. 
HighSymmKpath is basically a hardcoded list of kpoints based on Setyawan-Curtarolo's paper, that uses the input structure just to get its spacegroup. On the other hand, at the first usage most of the people expect that the list of kpoints would be meaningful even if they are passing a structure which is not the standard primitive. On top of that, the symprec default value in HighSymmKpath (1e-2) is larger than the default in SpacegroupAnalyzer (1e-3), so one could have even generated the standard primitive with the analyzer and get the path for a different spacegroup, if the structure is just slightly distorted. An additional source of possible misunderstandings is the fact that in SpaceGroupAnalyzer.get_primitive_standard_structure the default for international_monoclinic is True, while a False value is needed to reproduce the structure from the paper and be used by the HighSymmKpath object (Also, the international_monoclinic option is not documented in SpaceGroupAnalyzer, making the things even more difficult to understand). The problem is quite nasty as of course the produced band structure won't show any relevant problem and only a close inspection of the result can reveal the error.

## Suggested solution (if any)

My first suggestion would be to stress the intended usage of the HighSymmKpath object in the docstring. However, I personally think that it would be better having a warning or even raising an error if the structure does not correspond to the primitive standard obtained using the given symprec and angle_tolerance.

**Comment by shyuep** [comment]
I have no objection to issuing a warning or even raise an error if the structure does not correspond to primitive standard. Can you implement pls? Thanks.
