### ISSUE TITLE
plotting fermi surface from vasp calculation

### ISSUE THREAD

**Issue by chivalry123** [materialsproject/pymatgen#582]
Hi, 

I would like to ask about whether we could obtain Fermi surface and plot it via pymatgen (or other programs) from VASP calculations? I see the class BoltztrapRunner but not sure if it could achieve this task. Thank you very much.

**Comment by fraricci** [comment]
Hi,
you can run BoltztrapRunner using FERMI mode and selecting the index of the band you want to study.
Then, you can import the output with BoltztrapAnalyzer and plot it with the function plot_fermi_surface.
here a general example:

vrun = Vasprun('vasprun.xml.gz')
bs = vrun.get_band_structure()
nelect = vrun.parameters['NELECT']
vbm = int(nelect/2 -1)
BoltztrapRunner(bs=bs,nelec=nelect,lpfac=100,run_type='FERMI',band_nb=vbm,cond_band=False).run(path_dir='vbm/')
an=BoltztrapAnalyzer.from_files("vbm/boltztrap/")
plot_fermi_surface(an.fermi_surface_data,bs.structure,cbm=False,energy_levels=[-0.01])

If you already have a CUBE file containing your band in a 3D grid of kpoints, you can read it
using the read_cube_file function (in boltztrap.py module) and plot it passing thee data you get in output.

You are welcome to try this method and report any issue you get.
Thank you

**Comment by shyuep** [comment]
@fraricci Can you copy this code and put it in an ipython notebook in the examples folder? I think it will be very useful for new users. Thanks.

**Comment by mdforti** [comment]
I know this issue is old, but the example given above does not work for me. I ave Bolztrap2 installed, and bolztrap 1.25 in path. after importing the modules needed I get a 'file not found' error  for the folder where BoltzrapRunner is supposed to put the outputs. What Am I doung wrong ? Thanks for the help!

**Comment by fraricci** [comment]
I just realized that I've never moved this script to a notebook in matgenb, sorry. 
I'll that soon together with an equivalent way using boltztrap2.

@mdforti does the folder you're giving exist?

**Comment by mdforti** [comment]
ok I kind of worked out that the folders given to the run_path argument must be there beforehand, they are not created by BoltrztrapRunner. Also, the BoltzTrap executable must be in the path, but it has to be the version 1 of boltztrap. Implementation of Bolztrap2 can not read vasprun from spin polarized vasprun.
Also, a working example for vasp in the notebooks would be helpfull !
thanks for the reply!
