### ISSUE TITLE
error in plotting fermi surface

### ISSUE THREAD

**Issue by chivalry123** [materialsproject/pymatgen#584]
After performing Spin Orbit Coupling calculation on VASP. I tried to use pymatgen to plot the fermi surface as followed: 
```

from pymatgen.io.vasp.outputs import Vasprun
from pymatgen.electronic_structure.plotter import BSPlotter, DosPlotter, BSDOSPlotter, BoltztrapPlotter
from pymatgen.electronic_structure.core import Spin, Orbital, OrbitalType
from pymatgen.electronic_structure.dos import Dos
from pymatgen.electronic_structure.boltztrap import BoltztrapRunner, BoltztrapAnalyzer

v_dos = Vasprun("./DOS/vasprun.xml")
bs = v_dos.get_band_structure()
nelect = v_dos.parameters['NELECT']
vbm = int(nelect/2 -1)
BoltztrapRunner(bs=bs,nelec=nelect,lpfac=100,run_type='FERMI',band_nb=vbm,cond_band=False,soc=True).run(path_dir='./vbm/')
an=BoltztrapAnalyzer.from_files("vbm/boltztrap/")
BoltztrapPlotter.plot_fermi_surface(an.fermi_surface_data,bs.structure,cbm=False,energy_levels=[-0.01])
```

However, I get this error. 

```
lpfac, energy_grid:  100 0.005
 ================ BoltzTraP vs 1.2.5 =============
10.775u 0.208s 0:06.19 177.2%	0+0k 0+0io 90pf+0w

STOP error in factorization

Traceback (most recent call last):
  File "plot_fermi_surface.py", line 14, in <module>
    BoltztrapRunner(bs=bs,nelec=nelect,lpfac=100,run_type='FERMI',band_nb=vbm,cond_band=False,soc=True).run(path_dir='./vbm/')
  File "/Users/me/anaconda2/lib/python2.7/site-packages/pymatgen/electronic_structure/boltztrap.py", line 593, in run
    raise BoltztrapError("STOP error in factorization")
pymatgen.electronic_structure.boltztrap.BoltztrapError: BoltztrapError : STOP error in factorization
```

Do you know what should i do to resolve this? Thank you.

**Comment by chivalry123** [comment]
I have attached a small vasprun.xml (30 MB) that reproduces the error in the dropbox.

https://www.dropbox.com/s/itz8etvh4424nwa/vasprun.xml?dl=0

Would you like to take a look and see what might go wrong? Thank you very much.

**Comment by fraricci** [comment]
If you run VASP using an automatic mesh, this is a typical error due to the disagreement between VASP and spglib (used by pymatgen) finding the symmetry of your structure.
There are different possible solutions:
1. rerun VASP using an explicit kpoint list generated by pymatgen
2. rerun VASP using a automatic mesh but turning off symmetries (so kpoints spread on the entire BZ)
3. check which symmetry group is found by VASP and play with symprec variable of SpacegroupAnalyzer (in pymatgen) until you find the same group. Then you run BoltztrapRunner with the selected symprec (only possible with the last version of pymatgen).

I hope this is useful

**Comment by chivalry123** [comment]
I attempted the 2nd procedure by setting ISYM=0. With KPoints being,

pymatgen generated KPOINTS with grid density = 1000 / atom
0
Gamma
6 6 4

However, the same error persists... I attached my vasprun.xml in the dropbox

https://www.dropbox.com/s/gif7q9sbwss3wg7/vasprun.xml?dl=0

Would you like t see what might go wrong? Thank you very much.

**Comment by fraricci** [comment]
I forgot to add that in this case you have to edit the .struct file writing "1" 
instead of the number you have in the 5th line. 
It correnspond to the number of symmetries.
After you need to run boltztrap manually.

**Comment by chivalry123** [comment]
Thank you very much for your prompt response. However, after I change boltztrap.struct (5th line: from 12 to 1) I still got the error:
```

$ cat boltztrap.struct 
La3 Ir9 R-3m
-5.14256 -8.90718 0.00000
5.14256 -8.90718 0.00000
0.00000 -5.93812 16.81815
1
1 0 0
0 1 0
0 0 1
-1 0 0
0 -1 0
0 0 -1
0 1 0
-1 -1 -1
0 0 1
0 -1 0
1 1 1
0 0 -1
-1 -1 -1
1 0 0
0 0 1
1 1 1
-1 0 0
0 0 -1
0 -1 0
-1 0 0
0 0 -1
0 1 0
1 0 0
0 0 1
1 1 1
0 -1 0
0 0 -1
-1 -1 -1
0 1 0
0 0 1
-1 0 0
1 1 1
0 0 -1
1 0 0
-1 -1 -1
0 0 1
$ x_trans BoltzTraP -so
 ================ BoltzTraP vs 1.2.5 =============
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
STOP error in factorization
0.088u 0.007s 0:00.06 133.3%	0+0k 0+1io 0pf+0w

```

Do you know what might go wrong? Thank you very much.  I have attached my BoltzTrap folder here: https://www.dropbox.com/sh/v6esf6vgcjxq51f/AAClowvGfox7UWXnzJosSEf9a?dl=0 

Thank you very much again.

**Comment by chivalry123** [comment]
After everything, I tried the 1st method to generate explicit kpoint with your help. Now the boltztrap runner is successful. However, when performing boltztrap analyzer: I get this issue.

```
$ python plot_fermi_surface.py 
lpfac, energy_grid:  10 0.005
 ================ BoltzTraP vs 1.2.5 =============
1.521u 0.094s 0:01.56 103.2%	0+0k 14+39io 121pf+0w


Traceback (most recent call last):
  File "plot_fermi_surface.py", line 18, in <module>
    an=BoltztrapAnalyzer.from_files("vbm/boltztrap/")
  File "/Users/me/anaconda2/lib/python2.7/site-packages/pymatgen/electronic_structure/boltztrap.py", line 1870, in from_files
    raise ValueError("FERMI mode parsing is currently unavailable!")
ValueError: FERMI mode parsing is currently unavailable!

```

It seems it fermi parsing is unavailable.... do you know what shall i do as next step to plot fermi surface? Thank you very much for your all the way.

**Comment by fraricci** [comment]
Which version of pymatgen are you using?
The fermi mode is available only in the last version.

**Comment by chivalry123** [comment]
great! thank you very much, I upgraded to 4.6.2 and everything starts to work.... However, there is still some issue:

running the last line:

`plot_fermi_surface(an.fermi_surface_data,bs.structure,cbm=False,energy_levels=[-0.01])
`
it has the error:

`BoltztrapError: BoltztrapError : energy level -0.01 not in the range of possible energies: [-13592.0873173, -3.60221607003]
`

So I guess I might need to specify the fermi surface level. So I do (I am running in ipython)

`e_fermi = v_dos.efermi
`

but then it is 

```
In [8]: e_fermi
Out[8]: 9.06922155

```

I am really confused in this case... Do you know what should i do? Thank you very much. You are really of great help to me.

**Comment by fraricci** [comment]
-3.60221607003 is the max value of the band you're studying.
So select a value starting from it.
If you don't specify any energy_level, it will be set to the max/min
 value of the band -/+ 0.01 eV.

**Comment by chivalry123** [comment]
Thank you very much for your prompt response. I tried playing around with the code without luck....

Ehm.... does it mean that for my computation, the fermi level is 9.06eV, but the max value of the band we have considered so far is -3.602eV? Since our purpose is to plot the fermi surface at Fermi energy level which is specified to be  9.06922155... My calculation is with spin orbit coupling, not sure if this adds another layer of complexity. 

I checked my PROCAR, we have 114 electrons and our valence band is the number 114 band as shown as below, and it seems 9.06922155 is indeed our fermi level and all necessary bands should have been computed in our calculations...:

>  k-point  257 :    0.31578947 0.00000000 0.18181818     weight = 0.00151095
> 
> band   1 # energy  -23.09042420 # occ.  1.00000000
> ....
> band 113 # energy    8.91340620 # occ.  0.99999476
>  
> ion      s     py     pz     px    dxy    dyz    dz2    dxz    dx2    f-3    f-2    f-1     f0     f1     f2     f3    tot
>   1  0.000  0.003  0.000  0.001  0.001  0.004  0.000  0.002  0.001  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.015
>  ....
> band 114 # energy    8.91342568 # occ.  0.99999475
>  
> ion      s     py     pz     px    dxy    dyz    dz2    dxz    dx2    f-3    f-2    f-1     f0     f1     f2     f3    tot
>   1  0.000  0.003  0.000  0.001  0.001  0.004  0.001  0.002  0.001  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.015
> ....
> band 115 # energy    9.12415065 # occ.  0.06013640
>  
> ion      s     py     pz     px    dxy    dyz    dz2    dxz    dx2    f-3    f-2    f-1     f0     f1     f2     f3    tot
>   1  0.000  0.000  0.000  0.000  0.001  0.002  0.001  0.001  0.001  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.008
> ....

In this case, I believe BoltztrapRunner arguments n_band should be n_elect = 114.... Therefore, I run as followed:

```
from pymatgen.io.vasp.outputs import Vasprun
from pymatgen.electronic_structure.plotter import BSPlotter, DosPlotter, BSDOSPlotter, BoltztrapPlotter, plot_fermi_surface
from pymatgen.electronic_structure.core import Spin, Orbital, OrbitalType
from pymatgen.electronic_structure.dos import Dos
from pymatgen.electronic_structure.boltztrap import BoltztrapRunner, BoltztrapAnalyzer

v_dos = Vasprun("./explicit_kpt_1/vasprun.xml")
e_fermi = v_dos.efermi
bs = v_dos.get_band_structure()
nelect = v_dos.parameters['NELECT']
vbm = int(nelect)
print ("nelect is ",nelect)
print ("vbm is ",vbm)
BoltztrapRunner(bs=bs,nelec=nelect,lpfac=100,run_type='FERMI',band_nb=vbm,cond_band=False,soc=True).run(path_dir='./vbm/')
an=BoltztrapAnalyzer.from_files("vbm/boltztrap/")
plot_fermi_surface(an.fermi_surface_data,bs.structure,cbm=False,energy_levels=[e_fermi])

```

but the output is,

```
$ python plot_fermi_surface.py 
('nelect is ', 114.0)
('vbm is ', 114)
lpfac, energy_grid:  100 0.005
 ================ BoltzTraP vs 1.2.5 =============
19.864u 0.569s 0:18.89 108.0%	0+0k 1+60io 122pf+0w


Traceback (most recent call last):
  File "plot_fermi_surface.py", line 21, in <module>
    plot_fermi_surface(an.fermi_surface_data,bs.structure,cbm=False,energy_levels=[e_fermi])
  File "/Users/me/Desktop/software/pymatgen/pymatgen/electronic_structure/plotter.py", line 1707, in plot_fermi_surface
    str(en_min) + ", " + str(en_max) + "]")
pymatgen.electronic_structure.boltztrap.BoltztrapError: BoltztrapError : energy level 9.06922155 not in the range of possible energies: [-13592.0873173, 0.483561295849]

```

I think we actually considered the correct number  114 band, but for some reason it says the possible energy rang is   [-13592.0873173, 0.483561295849] .... do you know what might happen? Thank you very much again.

**Comment by chivalry123** [comment]
Sorry for bothering. I still could not resolve this issue. I will wait for you if you could might have some insight into this problem... Thank you very much.

**Comment by fraricci** [comment]
0.483561295849 is the max value of the band considered minus the fermi energy.
play also changing the band index to under stand if you're getting the right one.

**Comment by chivalry123** [comment]
I see. In this case, the problem is fully resolved by setting 

`energy_levels=[0]
`
in

`plot_fermi_surface(an.fermi_surface_data,bs.structure,cbm=False,energy_levels=[0])
`
Thank you very much for your help along the way!
