### ISSUE TITLE
Incorrect handling of projections in Vasprun.get_band_structure 

### ISSUE THREAD

**Issue by utf** [materialsproject/pymatgen#602]
When parsing a hybrid band structure using the `Vasprun.get_band_structure()` method with `linemode=True`, the band energies for any k-points that are not zero weighted are ignored.

If the `Vasprun` object is initialised with `parse_projected_eigen=True` the projections for each band are also read from the vasp output. However, when running the `get_band_structure` method, the projections for all k-points are returned, regardless of their k-point weighting.

This means the projections for kpoint_x (e.g. `bandstructure.projections[Spin.up][band_n][kpoint_x]`) are actually referring to the projections for a different kpoint than the bands at kpoint_x (e.g. `bandstructure.bands[Spin.up][band_n][kpoint_x]`).

I presume this isn't the correct behaviour?

**Comment by shyuep** [comment]
@hautierg Can you comment?

**Comment by utf** [comment]
The fix seems pretty straightforward, I'm quite happy to implement as long as this is definitely a bug and I'm not missing something.

**Comment by shyuep** [comment]
Thanks. Yes, if you can fix it, it would be great.

**Comment by hautierg** [comment]
Sounds good to me. Thanks!
