### ISSUE TITLE
conda warning of dependency installation

### ISSUE THREAD

**Issue by specter119** [materialsproject/pymatgen#614]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System

* Pymatgen version: pip(conda)
* Python version: 2.7 and 3.6
* OS version: linux

## Summary

In the matsci channel, some dependency have name with `py_0`.
It will lead conda can't choose the right version.

## Example code

```
#~/.condarc
channels:
  - defaults
  - matsci
```

```
conda install flask-paginate
```

## Error message

```
conda install flask-paginate
Fetching package metadata ...........
Solving package specifications: .
Warning: 2 possible package resolutions (only showing differing packages):
  - matsci::flask-paginate-0.4.5-py_0
  - matsci::flask-paginate-0.4.5-py27_0

Package plan for installation in environment /lustre/home/acct-umjzhh/umjzhh-1/.conda/envs/kl_mpw:

The following NEW packages will be INSTALLED:

    flask-paginate: 0.4.5-py_0 matsci

Proceed ([y]/n)? y

/lustre/usr/anaconda/2.4.3.0/lib/python2.7/site-packages/conda/core/link.py:446: UserWarning: Package matsci::flask-paginate-0.4.5-py_0 uses a pre-link script. Pre-link scripts are potentially dangerous.
This is because pre-link scripts have the ability to change the package contents in the
package cache, and therefore modify the underlying files for already-created conda
environments.  Future versions of conda may deprecate and ignore pre-link scripts.

  """ % dist))
```

then `flask-paginate` will be installed by `pip` again, finally there are 2 `flask-paginate` in `conda list`.

## Suggested solution (if any)

* I think the dependency with name `py_0` should be removed.

**Comment by shyuep** [comment]
I fixed it for flask-paginate. Can you check if there are problems for others?

**Comment by specter119** [comment]
@shyuep Thanks, it also happened on `smoqe` by chance, but it seems alright now. Besides, does `palettable` on the matsci channel need an update?

**Comment by shyuep** [comment]
I just fixed all of them. I can update palettable.

**Comment by specter119** [comment]
@shyuep Thanks in advance!

**Comment by specter119** [comment]
@shyuep I think `tqdm` have the same issue when use python2.7, sorry to find all of them yesterday.
