### ISSUE TITLE
Set attribute to the Site  object.

### ISSUE THREAD

**Issue by gVallverdu** [materialsproject/pymatgen#621]
Hi

If you are using a Site object, as attributes are almost all properties you cannot directly set it. 
```
In [1]: site = mg.Site(3, [0, 0, 0])

In [2]: site
Out[52]: Site: Li (0.0000, 0.0000, 0.0000)

In [3]: site.x = 2
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-51-f47d04af060a> in <module>()
----> 1 site.x = 2

AttributeError: can't set attribute
````

If you try to change the value in the coords array there is not any error message, but nothing is done. Again if you try to change the whole array, as `coords` is a property you get again the error message.

```
In [4]: site.coords[2] = 3

In [5]: site.coords
Out[5]: array([0, 0, 0])

In [6]: site.coords = [0, 0, 3]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-50-37feefce5458> in <module>()
----> 1 site.coords = [0, 0, 3]

AttributeError: can't set attribute
```

I think the line `In[4]` in the example above should raise a warning. The main danger here is that it does not raise an exception AND it does not do what you want. In the Site class, all attributes (or almost all) are Properties, that is why you get an exception if you try to set the coords array. I do not know exactly how to fix it, it is may be above my OOP skills.

**Comment by shyuep** [comment]
Note that sites are supposed to be immutable. So you cannot set any properties at all. The coords are internally represented by an private array. So what [4] does is that you get a copy of the array, and then you are modifying that copy. I don't think there is an easy way to change the code such that [4] raises an error. Fundamentally, you are not changing an attribute of Site itself, but rather the copy of coords you obtain.
