### ISSUE TITLE
Gascorrection  sets the Ehull/energy_per_atom to the same value for gases

### ISSUE THREAD

**Issue by miaoliu** [materialsproject/pymatgen#636]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System

* Pymatgen version: 4.6.0+
* Python version: 2.7
* OS version: linux (nersc mendel)

## Summary

* Gascorrection collapses the energy_per_atom and E^hull to the same value, even though the total energies per atom from calculations are not the same.

## Example code

```python
from pymatgen import MPRester
from pandas import DataFrame


a = MPRester(api_key="API_KEY")

entries = a.get_entries_in_chemsys(['H'])
import collections

data = collections.defaultdict(list)
for e in entries:
    data["Materials ID"].append(e.entry_id)
    data["Composition"].append(e.composition.reduced_formula)
    data["energy_per_atom"].append(e.energy_per_atom)
    data["correction"].append(e.correction)
    data["uncorrected_energy"].append(e.uncorrected_energy)

df = DataFrame(data, columns=["Materials ID", "Composition", "energy_per_atom", "correction","uncorrected_energy"])

print(df)
```

## Error message

Please note that the energy_per_atom is the same, so does the E^hull which is always equal to *ZERO* for all the calculations. 
```
   Materials ID Composition  energy_per_atom  correction  uncorrected_energy
0     mp-570752          H2        -3.239737   -4.255533           -2.223940
1      mp-24504          H2        -3.239737    0.609450          -13.568397
2    mp-1001570          H2        -3.239737    0.303425           -6.782898
3     mp-973783          H2        -3.239737    0.572690          -13.531636
4     mp-634659          H2        -3.239737   -2.123957           -1.115780
5     mp-632250          H2        -3.239737   -2.118332           -1.121405
6     mp-632172          H2        -3.239737    0.303412           -6.782886
7     mp-632291          H2        -3.239737    0.301908           -6.781381
8     mp-754417          H2        -3.239737   -0.248806           -2.990931
9     mp-850274          H2        -3.239737    0.296408           -6.775881
10     mp-23907          H2        -3.239737   -4.244749           -2.234724
```
It can also be seen from website:

[https://materialsproject.org/#search/materials/{"reduced_cell_formula"%3A"H"}](url)

## Suggested solution (if any)

line around 188 in pymatgen/pymatgen/entries/compatibility.py is responsible for this:
```python
    def get_correction(self, entry):
        comp = entry.composition

        rform = entry.composition.reduced_formula
        if rform in self.cpd_energies:
            return self.cpd_energies[rform] * comp.num_atoms \
                - entry.uncorrected_energy

        return 0
```

* Would suggest to use similar treatment of "O2" or chose the lowest energy compound as the stable compound. 
* Should also considering the case that: when a new lower energy compound is added, the correct should able to recognized the new hull and readjust value accordingly.

## Files (if any)

<If input files are needed to reproduce the error, please provide 
either links (e.g., Dropbox or GDrive) for large files or simply paste
the file below for small files.>

```
<contents of file 1>
```

**Comment by computron** [comment]
Note: the downstream consequence of this is that all MP structures for gas phase compositions (e.g., H2, F2, N2, etc) have e_above_hull = 0. This means that even if you have some really bad H2 structure that is nothing like the real solid and doesn't contain any bonds, it will still show e_above_hull = 0. It makes filtering bad structures (e.g., to build a model such as for volume prediction) or even ranking good vs. bad structures more difficult since one cannot just use an e_above_hull filter and call it a day. Instead, you need to explicitly exclude all gas phase compositions, or do some more manual work to figure out which structures are the more reasonable ones (e.g., by examining raw energies).

**Comment by shyuep** [comment]
I don't know if there is a good solution for this. Remember that the Compatibility operate on an individual entry, not a list of entries (process_entries is merely repeatedly calling process_entry). The solutions proposed here would make the correction depend on not just the entry being corrected, but also other entries (especially, the lowest energy entry). This "non-local" behavior is generally not a good programming practice. 

Is there a practical problem that we need this for? Volume predictor is nice in theory, but surely predicting the volume of a gas is futile?

**Comment by computron** [comment]
I think it's mainly because people expect an "e above hull" filter to remove most unstable compounds, but it (unexpectedly) won't remove very bad structures for H2, F2, etc.

e.g., @montoyjh and others accidentally computed a lot of elastic tensors for these structures because they passed through the e above hull filter.

Even if we keep this in mind for ourselves, others are likely to make the same mistake.

**Comment by shyuep** [comment]
Ok. I can suggest a way out. We leave GasCorrection as is. But for Compatibility.process_entries, we can find some way to readjust the corrections for the remaining entries upwards.

In any case, accidentally running elastic constants for CO2 gas really shouldn't be a problem resolved by compatibility. In this case, the initial query criteria to select structures to do computations was wrong.

**Comment by shyuep** [comment]
After reviewing the code carefully, my conclusion is that there is no way to implement this in a clean manner in the current framework. Basically, what is required is for process_entries to specially treat entries that have formulas that have GasCorrections and adjust the corrections for affected entry to the lowest value. While the actual coding of this will take a mere few minutes, the result is that Compatibility will now have a special treatment for one of the correction schemes (GasCorrection). That is extremely bad code design. And the purpose of this is merely to treat a very strange edge case of gas atoms that have no place in a solid-state world.

For MP's purposes, if it really bothers you that multiple O2 atoms have ehull=0, I would suggest you implement the workaround in the builders in the pre-processing of entries before phase diagram construction to compute ehull. You merely need to reset the corrections to the minimum correction found for all O2, CO2, etc. molecules.

I am closing this issue unless anyone has better ideas. Reopen if you have.
