### ISSUE TITLE
Should efermi from Vasprun be rounded to the 4th decimal place?

### ISSUE THREAD

**Issue by blondegeek** [materialsproject/pymatgen#648]
In vasprun.xml, the Fermi level is reported to 8 decimal places, while the band energies are only reported to 4 decimal places (and thus rounded to 4 decimal places).

Excerpt from vasprun.xml:
```
...
   <i name="efermi">      2.71196589 </i>
   <total>
    <array>
     <dimension dim="1">gridpoints</dimension>
     <dimension dim="2">spin</dimension>
     <field>energy</field>
     <field>total</field>
     <field>integrated</field>
     <set> 
      <set comment="spin 1">
       <r>   -31.9226     0.0000     0.0000 </r>
       <r>   -31.7774     0.0000     0.0000 </r>
       <r>   -31.6322     0.0000     0.0000 </r>
...
```
However, this can cause errors in determining whether a material is metallic if the valence band maximum is close to this value. I'm attaching the vasprun.xml and EIGENVAL files for such an example (BaTiO3 in space group 160 which is known to have a PBE band gap of ~2.5 eV).

```python
from pymatgen.io.vasp.outputs import Vasprun
import numpy as np

vrun = Vasprun('bto_vasprun.xml')
bs = vrun.get_band_structure()
print bs.efermi
print bs.is_metal()
bs.efermi = np.round(bs.efermi,4)
print bs.efermi
print bs.is_metal()

>> 2.71196589
>> True
>> 2.712
>> False
```

Should the efermi property be rounded to the same number of decimal places by default to avoid this issue?

[bto_example.zip](https://github.com/materialsproject/pymatgen/files/935823/bto_example.zip)

**Comment by shyuep** [comment]
We should not be changing the precision of the data. What we should do is to edit the is_metal method to account for floating point numerical accuracy and allow for up to a 4th decimal place difference.
