### ISSUE TITLE
Adding trigonal bipyramid to OrderParameters in pymatgen.analysis.structure_analyzer?

### ISSUE THREAD

**Issue by blondegeek** [materialsproject/pymatgen#653]
@nisse3000 How difficult would it be to add the order parameter for trigonal bipyramidal coordination to OrderParameters in pymatgen.analysis.structure_analyzer?

Example of structure with trigonal bipyramid coordination: 
Hexagonal manganate YMnO3
[https://materialsproject.org/materials/mp-19385/](https://materialsproject.org/materials/mp-19385/)

**Comment by nisse3000** [comment]
Hey @blondegeek,
I can give it a shot next week and see if I can construct something quickly.  Will let you know ASAP.

**Comment by blondegeek** [comment]
@nisse3000 Thanks very much! Please let me know if there's any way I can be helpful.

**Comment by nisse3000** [comment]
@shyuep, I think that this issue can be closed because the trigonal bipyramidal order parameter was implemented several months ago.
Agreed, @blondegeek?
