### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb0

### ISSUE THREAD

**Issue by moodmo** [materialsproject/pymatgen#658]
## System

* Pymatgen version: 5.0
* Python version:  2.7 as primary,  though 3 installed
* OS version: Fedora 25

## Summary

Running a code to get density of states (that runs fine in Debian Jessie) returns the following error in Fedora 25. 
` UnicodeDecodeError: 'utf8' codec can't decode byte 0xb0`

Pymatgen was hard to install but was able to install it fine after some time with pip.

## Error message
Entire error code is:
```
Traceback (most recent call last):
  File "an.py", line 199, in <module>
 vasprun = Vasprun("/vasprun.xml")
  File "/usr/lib64/python2.7/site-packages/pymatgen/io/vasp/outputs.py", line 383, in __init__
    self.update_potcar_spec(parse_potcar_file)
  File "/usr/lib64/python2.7/site-packages/pymatgen/io/vasp/outputs.py", line 829, in update_potcar_spec
    potcar = get_potcar_in_path(os.path.split(self.filename)[0])
  File "/usr/lib64/python2.7/site-packages/pymatgen/io/vasp/outputs.py", line 813, in get_potcar_in_path
    pc = Potcar.from_file(os.path.join(p, fn))
  File "/usr/lib64/python2.7/site-packages/pymatgen/io/vasp/inputs.py", line 1704, in from_file
    fdata = reader.read()
  File "/usr/lib64/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb0 in position 37: invalid start byte

```
I am sure more errors would appear if I fix just the above one since that is the first time pymatgen is actually implemented in the code.

**Comment by shyuep** [comment]
Pymatgen is at version 4.7.4. There is no version 5.0 at the moment. 

I need the example file to know the problem. The likelihood is that there is an illegal character in the file which causes the unicode decoding (which is expected for a POTCAR file) to not work. 

Also, can you elaborate on the "hard to install" comment? I expect that it is more difficult for Windows users, but I have seldom heard complaints from Mac users and certainly not from Linux users. Also, pymatgen is already available on conda and that is the first recommended installation method in the documentation for people who have not done python packages before.

**Comment by moodmo** [comment]
if I use `pmg -h `then `Author: Shyue Ping Ong Version: 5.0 Last updated: Sep 19 2016` appears, that's the version I meant. 

It was hard because fedora didn't have the dependences needed, specifically, `redhat-rpm-config`, `python-devel`, `libxstl-devel`, `gcc-c++`, and more that I installed because they were dependencies for those that I think were the key to making it work. 

Have played around more and is just some vasprun.xml files that have the problem when importing them with Vasprun(), if they are imported fine then everything else works. Note that all the files I am trying to import were imported just fine in Debian

**Comment by shyuep** [comment]
I see. If Fedora does not come with gcc and python-devel installed by default, that is a very bad practice by Fedora. Most Linux distributions come with them properly installed. THis is especially since anything within the SCipy package definitely requires these packages and those are pretty standard.

Unfortunately I have no way to looking at a file that somehow does nto parse on Fedora but parses properly on Debian. That suggests that there is something wrong either with the python compilation itself or the system. You can check the python version with `python --version`. If it is somehow failing on Python 2 rather than Python 3 or vice versa, I can look at that. Reopen this issue if this issue persists.
