### ISSUE TITLE
DeformedStructureSet returns dict_keys object in python 3

### ISSUE THREAD

**Issue by Atraii** [materialsproject/pymatgen#662]
## System

* Pymatgen version: **master 4.7.5**
* Python version: **3.6.1**
* OS version: **Fedora 25**

## Summary

* analysis/elasticity/strain.py: DeformedStructureSet() returns a [dict_keys](https://docs.python.org/3/library/stdtypes.html#dictionary-view-objects) object in python 3 (rather than a list in python 2)
* this is harder to understand as the default argument `symmetry=False` returns a list rather than a dictionary view object (even in python 3).
* returning different objects makes it difficult to determine how to use the object

## Example code

```python
poscar = Poscar.from_file('POSCAR_orig')
structure = poscar.structure
dss = elasticity.strain.DeformedStructureSet(structure, symmetry=True)
for i, st_deformed in enumerate(dss.def_structs):
    runvasp()
    vasprun = Vasprun('vasprun.xml')
    deformation_matrix = dss.deformations[i].tolist()
    sm = elasticity.strain.IndependentStrain(deformation_matrix)
    st = elasticity.stress.Stress(vasprun.ionic_steps[-1]['stress'])
    ss_dict[sm] = st
```

## Error message

```
Traceback (most recent call last):
  File "holy-potatoes-a-bug.py", line 28, in <module>
    deformation_matrix = dss.deformations[i].tolist()
TypeError: 'dict_keys' object does not support indexing
```

## Suggested solution (if any)

* From DeformedStructureSet(), could we get the same functionality from 
```python
 self.deformations = list(self.sym_dict)
```
as opposed to 
```python
 self.deformations = self.sym_dict.keys()
```

* Alternatively, I'd be okay with returning a dict_keys object if it also returned the same type **with symmetry=False**

**Comment by montoyjh** [comment]
Let's do the first.  Thanks for finding the cause.

As an aside, I wrote DeformedStructureSet mostly to preserve some legacy functionality of an older codebase that I inherited, but I've never used it for anything practical (I mostly use atomate/MPWorks for managing calculations of ECs).  If there's any additional functionality that you think would be useful there, feel free to implement and submit a PR.
