### ISSUE TITLE
problem on installing pymatgen

### ISSUE THREAD

**Issue by gangji1992** [materialsproject/pymatgen#668]
I am learning how to use pymatgen . But I have a problem on installing pymatgen, the method I use is 'python setup.py install'. When I install pymatgen, it has a error . The error is 'error LNK2019: unresolved external symbol _round  referenced in function 
___pyx_pf_8pymatgen_4util_18coord_utils_cython_pbc_shortest_vectors ' I don't know how to solve this problem. I would like to know how to solve it, please help me.

**Comment by shyuep** [comment]
When you entered the issue, the template specifically asks for several pieces of information with regards to the type of OS and system. Pls indicate all that information. The single error message that you gave above is not enough for us to go on.

Also, the pymatgen installation instructions specifically recommends that you use conda to install pymatgen if you have no experience in installing python packages.

**Comment by gangji1992** [comment]
Thank you for your reply. I will try using conda to install pymatgen
