### ISSUE TITLE
Modifying the CONFIG dict instance of a VaspInputSet class instance changes the base class

### ISSUE THREAD

**Issue by bocklund** [materialsproject/pymatgen#685]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System

* Pymatgen version: 4.7.7
* Python version: 2.7
* OS version: macOS

## Summary

* Modifying the CONFIG dict instance of a VaspInputSet class instance changes the base class

## Example code

```python
from pymatgen.io.vasp.sets import MPRelaxSet
from pymatgen import Structure

# load your structure, e.g. from a POSCAR
struct = Structure.from_file('POSCAR')

# create a custom input set
my_custom_input_set = MPRelaxSet(struct)
print('Base class config dict before: {}\n'.format(MPRelaxSet.CONFIG))
print('Instance before change: {}'.format(my_custom_input_set.CONFIG['POTCAR']['Mg']))
my_custom_input_set.CONFIG['POTCAR']['Mg'] = 'Mg'
print('Instance after change: {}'.format(my_custom_input_set.CONFIG['POTCAR']['Mg']))
print('Base class after change: {}'.format(MPRelaxSet.CONFIG['POTCAR']['Mg']))
```

results in

```
Base class config dict before: {'INCAR': ...  *'Mg': 'Mg_pv'*, ...'Er': 'Er_3'}}

Instance before change: Mg_pv
Instance after change: Mg
Base class after change: Mg
```
## Suggested solution (if any)

* Dictionaries of instances should be copied from the one passed in the  __init__ constructor

**Comment by shyuep** [comment]
This is not the way to modify the config of an input set. The CONFIG is an internal class variable that should not be changed. It merely provides a reference. If changes are needed, you should be modifying the self.config_dict instance or supply user_incar_settings if you are modifying the INCAR.
