### ISSUE TITLE
missing electronegativities and default behavior for missing electronegativities

### ISSUE THREAD

**Issue by computron** [materialsproject/pymatgen#688]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System

* Pymatgen version: master

## Summary

* pymatgen is missing electronegativity data for the following elements:
-He
-Ne
-Ar
-Pm
-Eu
-Tb
-Yb
-Rn
-Lr

* First, the default behavior of returning zero for missing electronegativities can cause downstream problems. For example, we wrote a straightforward code to get the average electronegativity of elements in a composition for use in data mining. If the composition includes an element like "Eu", we get back an answer that is completely wrong for average electronegativity (due to Eu being assigned an electronegativity of zero) without any indication that something improper happened. I suggest throwing an error if the electronegativity can't be found. At the very least, to throw a clear warning.

* Second, some of these elements do have Pauling electronegativity reported:
https://en.wikipedia.org/wiki/Electronegativity
Eu=1.2
Tb=1.1
Yb=1.1
Lr=1.3

The above electronegativities might not be 100% consistent with your version of Pauling electronegativity table for elements common to both Wikipedia and pymatgen but at least should be in the right ballpark, e.g., maybe off by 0.1.

I can provide more information, examples, etc. if needed

**Comment by computron** [comment]
Note: returning "None" for undefined electronegativity (like He) would also work for me

**Comment by shyuep** [comment]
Returning None is an issue. That means that code that averages electronegativity needs to specially take into account None as a possible value. I can fix the values that have them. But for those without Pauling electronegativities, it is very bad for a code to expect a float and then get a None.

**Comment by computron** [comment]
@shyuep I don't understand - it looks like you disagree with returning None, but the commit now seems to return None. I am satisfied in theory but perplexed at the decision.

If you don't agree with returning None, how about throwing an error - perhaps by creating a MissingDataError or using ValueError. e.g., throwing a negative number into math.log() throws a ValueError

**Comment by shyuep** [comment]
@computron The answer is simple. BHFL changed his mind. :-)
Anyway, since the only three elements from Z=1-103 that do not have electroneg are He, Ne and Ar, we can live with it for now. There might be sorting issues though. If anything, I think we should assign a *high* X to He, Ne and Ar. Probably float("inf") or something like 4.0, which is more electroneg than even F.

**Comment by shyuep** [comment]
Anyway, I just set it to infinite in the latest commit.
