### ISSUE TITLE
CIF to POSCAR

### ISSUE THREAD

**Issue by Hemnepal** [materialsproject/pymatgen#693]
Hi,

I am able to download CIF files from material project and convert them to POSCAR. When I drag them to VESTA, original CIF file shows the structure but I cannot see the structure by using transformed POSCAR. I have attached both files. 
[NO2.zip](https://github.com/materialsproject/pymatgen/files/1066648/NO2.zip)
The following is the script I used.

import json
import re
from fnmatch import fnmatch
from pymatgen.io.cif import CifParser, CifWriter
output = open("POSCAR", "w")

def read_structure(filename, primitive = True, sort = False):
        fname = os.path.basename(filename)
        if fnmatch(fname.lower(), "*.cif*"):
                parser = CifParser(filename)
                s = parser.get_structures(primitive=primitive)[0]
                print s
                output.write(str(s))

st = read_structure('N2O3.cif')

Thank you in advance.

<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System

* Pymatgen version: <Write "branch_name" if it is development version.>
* Python version: <Only 2.7.* and 3.* supported.>
* OS version: <If you are writing Windows here, you are on your own.> 

## Summary

* <Short 1-2 bullet points stating the problem.>

## Example code

```python
<Example code generating error>
```

## Error message

```
<Error message>
```

## Suggested solution (if any)

* <If you have a suggestion on how to solve the issue, you may write it
  here.>

## Files (if any)

<If input files are needed to reproduce the error, please provide 
either links (e.g., Dropbox or GDrive) for large files or simply paste
the file below for small files.>

```
<contents of file 1>
```

**Comment by shyuep** [comment]
Both the POSCAR and CIF open just fine on my VESTA.

**Comment by Hemnepal** [comment]
Thank you so much. I will check it again.
