### ISSUE TITLE
Extraneous backslash in latex label in plotter.py from  pymatgen.electronic_structure.plotter

### ISSUE THREAD

**Issue by paulfons** [materialsproject/pymatgen#698]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System

Python version: 2.7
OS Version: CentOS Linux release 7.3.1611 (Core) 
pymatgen version: pymatgen-2017.6.8-py2.7

## Summary

The plotter.py code contains an extra backslash character that results in an error when plotting band structure with matplotlib
[error.txt](https://github.com/materialsproject/pymatgen/files/1073309/error.txt)
. I have included the output of the error in an attached file.

## Example code

The included file shows the text generated when attempting to plot a band structure, namely there is a statement "\\mathrm{Wave\ Vector}" in the plotting module which has an extra "\" that leads to an error in interpreting the latex in the matplotlib routines.

```python

```

## Error message

```
<Error message>
```

## Suggested solution (if any)

The original code in plotter.py reads

        # Main X and Y Labels
        plt.xlabel(r'$\\mathrm{Wave\ Vector}$', fontsize=30)
        ylabel = r'$\\mathrm{E\ -\ E_f\ (eV)}$' if zero_to_efermi \
            else r'$\\mathrm{Energy\ (eV)}$'
        plt.ylabel(ylabel, fontsize=30)

Changing the code (I have done it locally) to remove the extra backslash allows plotting without any latex errors.

        # Main X and Y Labels
        plt.xlabel(r'$\mathrm{Wave\ Vector}$', fontsize=30)
        ylabel = r'$\mathrm{E\ -\ E_f\ (eV)}$' if zero_to_efermi \
            else r'$\mathrm{Energy\ (eV)}$'
        plt.ylabel(ylabel, fontsize=30)

## Files (if any)

<If input files are needed to reproduce the error, please provide 
either links (e.g., Dropbox or GDrive) for large files or simply paste
the file below for small files.>

```
<contents of file 1>
```

**Comment by shyuep** [comment]
Thanks. I pushed a fix. The odd thing about matplotlib is why it is so sensitve to this kind of errors. I would have thought that the easier way is to ignore such rendering issues.
