### ISSUE TITLE
plotter.get_projected_plots_dots_patom_pmorb will not accept a single orbital

### ISSUE THREAD

**Issue by paulfons** [materialsproject/pymatgen#699]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System

* Pymatgen version: pymatgen-2017.6.8-py2.7
* Python version: 2.7
* OS version: CentOS Linux release 7.3.1611 (Core)  

## Summary

plotter.get_projected_plots_dots_patom_pmorb should accept a single orbital as a target instead it generates an error. This used to work previously.

## Example code

plot = plotter.get_projected_plots_dots_patom_pmorb({'N':['px']},{'N':range(9,17)},{'N':range(9,17)})
## Error message

```
<Error message>

You do not want to sum projection over orbitals.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-955a7dd9ef4d> in <module>()
----> 1 plot = plotter.get_projected_plots_dots_patom_pmorb({'N':['px']},{'N':range(9,17)},{'N':range(9,17)})

/usr/lib64/python2.7/site-packages/pymatgen/electronic_structure/plotter.py in get_projected_plots_dots_patom_pmorb(self, dictio, dictpa, sum_atoms, sum_morbs, zero_to_efermi, ylim, vbm_cbm_marker, selected_branches, w_h_size, num_column)
   1318             f_3 = 9 f_2 = 10 f_1 = 11 f0 = 12 f1 = 13 f2 = 14 f3 = 15
   1319         """
-> 1320         dictio, sum_morbs = self._Orbitals_SumOrbitals(dictio, sum_morbs)
   1321         dictpa, sum_atoms, number_figs = self._number_of_subfigures(dictio, dictpa, sum_atoms, sum_morbs)
   1322         print('Number of subfigures: %s' % str(number_figs))

/usr/lib64/python2.7/site-packages/pymatgen/electronic_structure/plotter.py in _Orbitals_SumOrbitals(self, dictio, sum_morbs)
   1495             if len(dictio[elt]) == 1:
   1496                 if len(dictio[elt][0]) > 1:
-> 1497                     if elt in sum_morbs.keys():
   1498                         raise ValueError("You cannot sum projection over one individual orbital '%s' of '%s'." %
   1499                                          (dictio[elt][0], elt))

AttributeError: 'NoneType' object has no attribute 'keys'
```

## Suggested solution (if any)

* <If you have a suggestion on how to solve the issue, you may write it
  here.>

## Files (if any)

<If input files are needed to reproduce the error, please provide 
either links (e.g., Dropbox or GDrive) for large files or simply paste
the file below for small files.>

```
<contents of file 1>
```

**Comment by shyuep** [comment]
I suspect this has nothing to do with the orbital, but the fact that you are passing a range into the method. Can you try putting it as list(range(9, 17))?

**Comment by paulfons** [comment]
actually the same statement without the range statements has the same problem:

plot = plotter.get_projected_plots_dots_patom_pmorb({'N':['px']},{'N':[9,10,11,12,13,14,15,16]},{'N':[9,10,11,12,13,14,15,16]},ylim=(-0.5,2))

/usr/lib64/python2.7/site-packages/pymatgen/electronic_structure/plotter.py in get_projected_plots_dots_patom_pmorb(self, dictio, dictpa, sum_atoms, sum_morbs, zero_to_efermi, ylim, vbm_cbm_marker, selected_branches, w_h_size, num_column)
   1318             f_3 = 9 f_2 = 10 f_1 = 11 f0 = 12 f1 = 13 f2 = 14 f3 = 15
   1319         """
-> 1320         dictio, sum_morbs = self._Orbitals_SumOrbitals(dictio, sum_morbs)
   1321         dictpa, sum_atoms, number_figs = self._number_of_subfigures(dictio, dictpa, sum_atoms, sum_morbs)
   1322         print('Number of subfigures: %s' % str(number_figs))

/usr/lib64/python2.7/site-packages/pymatgen/electronic_structure/plotter.py in _Orbitals_SumOrbitals(self, dictio, sum_morbs)
   1495             if len(dictio[elt]) == 1:
   1496                 if len(dictio[elt][0]) > 1:
-> 1497                     if elt in sum_morbs.keys():
   1498                         raise ValueError("You cannot sum projection over one individual orbital '%s' of '%s'." %
   1499                                          (dictio[elt][0], elt))

AttributeError: 'NoneType' object has no attribute 'keys'




On the other hand, if I specify more than one orbital, it runs as advertised:

 plot = plotter.get_projected_plots_dots_patom_pmorb({'N':['px','py','pz']},{'N':range(9,17)},{'N':range(9,17)},ylim=(-0.
   ...: 5,2))
You do not want to sum projection over orbitals.
Number of subfigures: 3
{u'name': u'F-Q', u'start_index': 0, u'end_index': 19}
{u'name': u'Q-Z', u'start_index': 20, u'end_index': 39}
{u'name': u'Z-\\Gamma', u'start_index': 40, u'end_index': 59}
{u'name': u'\\Gamma-F', u'start_index': 60, u'end_index': 79}
dictio_d: {'N': ['px', 'py', 'pz']}
dictpa_d: {'N': [u'all']}

**Comment by shyuep** [comment]
I am sorry, but I will refer you to @computron and @hautierg to solve this. The code in question (that _Orbital_SumOrbitals) method contains many nested isinstance tests of whether something is a valid list or dict, which should almost never be done in a python code. Also, the method has no unittest, so I cannot debug any changes I make.

**Comment by computron** [comment]
I don't have any experience with plotters other than BSDosPlotter (that's the only one I coded and worked with), so I'd leave it to @hautierg

**Comment by fraricci** [comment]
I think @anhhv coded that function

**Comment by anhhv** [comment]
@paulfons I updated the "get_projected_plots_dots_patom_pmorb" method. Please wait until the administrators accept my changes and you can clone the newest pymatgen and retry again. If you still get some problems, please tell me.

**Comment by shyuep** [comment]
I have accepted the pull request.

**Comment by m3lab-zzl** [comment]
> @paulfons I updated the "get_projected_plots_dots_patom_pmorb" method. Please wait until the administrators accept my changes and you can clone the newest pymatgen and retry again. If you still get some problems, please tell me.

Hi anhhv, are you sure we can select only one orbital now? I stuck at `if elt in sum_morbs:` because by default sum_morbs is None and is not iterable.

pymatgen 2023.05.10 version

Thank you

**Comment by anhhv** [comment]
@m3lab-zzl  Can you share your script? I think you should not get this error because this if condition is always constrained by condition "sum_morbs is not None"

**Comment by m3lab-zzl** [comment]
> @m3lab-zzl Can you share your script? I think you should not get this error because this if condition is always constrained by condition "sum_morbs is not None"

Sure, script:

```py
import json
from pymatgen.electronic_structure.plotter import BSPlotterProjected
from pymatgen.electronic_structure.bandstructure import BandStructureSymmLine

d = json.load(open("band_data.json", "r"))
bs = BandStructureSymmLine.from_dict(d)
print(bs)

bsp = BSPlotterProjected(bs=bs)
dict_elem_orbit = {"Mo": ["px"]}
dict_elem_index = {"Mo": [1]}

plt = bsp.get_projected_plots_dots_patom_pmorb(
    dictio=dict_elem_orbit,  
    dictpa=dict_elem_index,
    sum_atoms=None, 
    sum_morbs=None, 
    zero_to_efermi=False, 
    ylim=None,
    vbm_cbm_marker=False, 
    selected_branches=None, 
    w_h_size=(12, 8), 
    num_column=None, 
)

plt.savefig('band.png')
```
[band_data.zip](https://github.com/materialsproject/pymatgen/files/11997529/band_data.zip)

Extract band_data.zip as band_data.json, and run it, you will probably get error message:

```txt
    if elt in sum_morbs:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by m3lab-zzl** [comment]
Hi, @anhhv 

In debug mode, I found the if condition (in plotter.py 1809 line, 2023.05.10 version) may be the reason:

```py
if len(dictio[elt][0]) > 1 # length of 'px' str is 2 
```

It may be better to determine the type before considering its length:

```py
if not isinstance(dictio[elt][0], str) and len(dictio[elt][0]) > 1:
```

**Comment by m3lab-zzl** [comment]
Hi, @anhhv

It has been a week, what do you think about the issue? Should we create a PR?

**Comment by m3lab-zzl** [comment]
@anhhv Two more weeks...

**Comment by anhhv** [comment]
Hi @m3lab-zzl 

Sorry that I'm super busy and currently not working in relevant Materials Project. Your can modify the code like this

            _if len(dictio[elt]) == 1:
                if len(dictio[elt][0]) > 1:
                    if sum_morbs is None:
                        pass
                    else:
                        if elt in sum_morbs.keys():
                            raise ValueError(
                                "You cannot sum projection over one individual orbital '%s' of '%s'." %
                                (dictio[elt][0], elt))_

If you want to contribute or open a PR for Pymatgen. Don't hesitate to do it. It would be nice if you also prepare a test-suite for this part as well.

Best regards,
Viet-Anh Ha

**Comment by m3lab-zzl** [comment]
> Hi @m3lab-zzl 
> 
> 
> 
> Sorry that I'm super busy and currently not working in relevant Materials Project. Your can modify the code like this
> 
> 
> 
>             if len(dictio[elt]) == 1:
> 
>                 if len(dictio[elt][0]) > 1:
> 
>                     if sum_morbs is None:
> 
>                         pass
> 
>                     else:
> 
>                         if elt in sum_morbs.keys():
> 
>                             raise ValueError(
> 
>                                 "You cannot sum projection over one individual orbital '%s' of '%s'." %
> 
>                                 (dictio[elt][0], elt))
> 
> 
> 
> If you want to contribute or open a PR for Pymatgen, don't hesitate to do it. It would be nice if you also prepare a test-suite for this part as well.
> 
> 
> 
> Best regards,
> 
> Viet-Anh Ha

I prefer not to open a new PR because I am not familiar with the test-suite
