### ISSUE TITLE
Can't copy or pickle pymatgen.io.vasp.inputs.Potcar instance

### ISSUE THREAD

**Issue by skasamatsu** [materialsproject/pymatgen#706]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System

* Pymatgen version: 2017.6.8
* Python version: 2.7.13
* OS version: SUSE Linux Enterprise Server 11 

## Summary

* Potcar instances cannot be copied or pickled (not sure if it's a bug or feature limitation)
## Example code

```python
import copy
import cPickle

from pymatgen.io.vasp import Potcar

mypotcar = Potcar(symbols=["Mg"], functional="PBE_54")
#mypotcar_copy = copy.deepcopy(mypotcar)
cPickle.dump(mypotcar, open("mypotcar.pickle","w"))

```

## Error message

```
Traceback (most recent call last):
  File "testpotcar_pmg.py", line 8, in <module>
    cPickle.dump(mypotcar, open("mypotcar.pickle","w"))
cPickle.PicklingError: Can't pickle <class 'pymatgen.io.vasp.inputs.OrbitalDescription'>: attribute lookup pymatgen.io.vasp.inputs.OrbitalDescription failed

```
If I uncomment the copy line:
```
Traceback (most recent call last):
  File "testpotcar_pmg.py", line 7, in <module>
    mypotcar_copy = copy.deepcopy(mypotcar)
  File "/home/i0009/i000900/tool/python/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/i0009/i000900/tool/python/lib/python2.7/copy.py", line 351, in _reconstruct
    item = deepcopy(item, memo)
  File "/home/i0009/i000900/tool/python/lib/python2.7/copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/i0009/i000900/tool/python/lib/python2.7/copy.py", line 329, in _reconstruct
    y = callable(*args)
  File "/home/i0009/i000900/tool/python/lib/python2.7/copy_reg.py", line 93, in __newobj__
    return cls.__new__(cls, *args)
  File "/home/i0009/i000900/tool/python/lib/python2.7/site-packages/monty/design_patterns.py", line 80, in __new__
    inst = klass(*args, **kwargs)
TypeError: __init__() takes exactly 2 arguments (1 given)

```

## Suggested solution (if any)

* The pickling error is due to using namedtuple inside the Potcar class definition. Same issue on stackoverflow:
https://stackoverflow.com/questions/4677012/python-cant-pickle-type-x-attribute-lookup-failed
so it works if I put the namedtuple line at module level, but it isn't pretty.
* The error thrown when trying to copy the instance is due to using the cached_class decoration defined in monty.design_patterns. It seems that copy.deepcopy() at some point calls `__new__ ` without arguments. This is a problem since `__new__` in cached_class calls `__init__`, which throws the TypeError when called without arguments. The example works if I remove the `@cached_class ` decoration line above Potcar class definition, but I'm not sure if there are any side effects (I couldn't find anywhere else in pymatgen that uses the cache made by cached_class).

## Files (if any)
Diff for modified inputs.py:

```
$ diff   inputs.py inputs.py.mine
1386c1386,1392
< @cached_class
---
> Orbital = namedtuple('Orbital', ['n', 'l', 'j', 'E', 'occ'])
> Description = namedtuple('Description', ['l', 'E',
>                                          'Type', "Rcut",
>                                          "Type2", "Rcut2"])
>
>
> #@cached_class
1461,1465c1467,1469
<     Orbital = namedtuple('Orbital', ['n', 'l', 'j', 'E', 'occ'])
<     Description = namedtuple('OrbitalDescription', ['l', 'E',
<                                                     'Type', "Rcut",
<                                                     "Type2", "Rcut2"])
<
---
>     #Orbital = Orbital
>     #Description = Description
>
1499c1503
<                     orbitals.append(self.Orbital(int(orbit[0]),
---
>                     orbitals.append(Orbital(int(orbit[0]),
1514c1518
<                     descriptions.append(self.Description(int(description[0]),
---
>                     descriptions.append(Description(int(description[0]),
1658c1662
<                     elif isinstance(item, (self.Orbital, self.Description)):
---
>                     elif isinstance(item, (Orbital, Description)):

```

**Comment by shyuep** [comment]
Thanks. I fixed the class. Usually, we tend not to use pickle as it is highly prone to breakage. The preferred serialization in pymatgen is with json.

**Comment by skasamatsu** [comment]
That was quick! And thank you for recommending json. Unfortunately, the reason I need it to be pickleable is because I want to use pymatgen with multiprocess Queues, which sends objects using pickles.
