### ISSUE TITLE
anonymous fit and mapping for subsets of structures

### ISSUE THREAD

**Issue by yifeimichelle** [materialsproject/pymatgen#708]
Feature Request

## System

* Pymatgen version: 2017.6.8
* Python version: 3.6.1
* OS version: Ubuntu 14.04 LTS

## Summary

* fit_anonymous(struct1, struct2) and get_all_anonymous_mappings(struct1, struct2) in the module pymatgen.analysis.structure_matcher do not allow for fitting a subset, as the equivalent non-anonymous fit(struct1, struct2) and get_mapping(struct1, struct2) do. Instead fit_anonymous() returns False and get_all_anonymous_mappings() returns None.

## Suggested solution (if any)

* Implement the anonymous fit and mapping functions the same way as the species-specific ones do, to account for fitting and mapping a subset.

**Comment by shyuep** [comment]
@wmdrichards Can you comment on whether this can be done?

**Comment by shyuep** [comment]
Seems like this issue has been defunct for many years. Closing.... Feel free to reopen if still valid.
