### ISSUE TITLE
Error when compile docs

### ISSUE THREAD

**Issue by renpj** [materialsproject/pymatgen#711]
## System

* Pymatgen version:  v2017.6.24
* Python version: 2.7.12
* OS version: Mint Linux 18.1

## Summary

* Error when compile docs by "make html"

## Error message

```
Running Sphinx v1.5.2
Exception occurred:
  File "../pymatgen/util/coord_utils.py", line 11, in <module>
    from . import coord_utils_cython as cuc
ImportError: cannot import name coord_utils_cython
The full traceback has been saved in /tmp/sphinx-err-ENm77V.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:45: recipe for target 'html' failed
make: *** [html] Error 1
```

**Comment by shyuep** [comment]
You have to compile pymatgen first before running the docs generation. In any case, all docs are available at pymatgen.org. There is really no need to build it yourself.

**Comment by renpj** [comment]
@shyuep Is there a offline version of docs?

**Comment by shyuep** [comment]
Hmmm.... I am happy to attach it. But is there a reason you need an offline version? 
[pymatgen-doc.zip](https://github.com/materialsproject/pymatgen/files/1123423/pymatgen-doc.zip)

**Comment by renpj** [comment]
@shyuep Thanks very much. The connection is not well here, especially for visiting website abroad. So, it would be more convenient by using a offline docs.
