### ISSUE TITLE
independentstrain not defined

### ISSUE THREAD

**Issue by matk86** [materialsproject/pymatgen#716]
* @montoyjh on line https://github.com/materialsproject/pymatgen/blob/master/pymatgen/analysis/elasticity/strain.py#L162

**Comment by mkhorton** [comment]
see https://github.com/hackingmaterials/atomate/issues/133

**Comment by matk86** [comment]
That's a different issue

**Comment by mkhorton** [comment]
Sorry, my mistake :)
