### ISSUE TITLE
SpagegroupAnalyzer.get_conventional_standard_structure(). 

### ISSUE THREAD

**Issue by Djordje117** [materialsproject/pymatgen#723]
<When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.>

## System

* Pymatgen version: 2017.7.4
* Python version: 2.7.13
* OS version: Linux 

## Summary

When a Structure object of nicely layered material is passed to the SpagegroupAnalyzer.get_conventional_standard_structure(), it returns a molecular structure.  

Figure 1 shown a staring structure, while Figure 2 shows a returned structure. POSCAR of a problematic structure is:

Mo2 Cl6
1.0
0.000000 6.260814 0.007832
-5.422831 3.130407 0.003916
0.000000 0.000000 6.307389
Cl Mo
6 2
direct
0.148065 0.999913 0.277579 Cl
0.499843 0.648557 0.721695 Cl
0.851935 0.000087 0.722421 Cl
0.852063 0.648113 0.277949 Cl
0.147937 0.351887 0.722050 Cl
0.500157 0.351443 0.278308 Cl
0.166623 0.666720 0.500071 Mo
0.833377 0.333280 0.499928 Mo

![figure1](https://user-images.githubusercontent.com/13387824/28222375-3b3c7626-6895-11e7-8678-c8dea093563c.png)
           Figure 1
![figure2](https://user-images.githubusercontent.com/13387824/28222376-3b3d7f08-6895-11e7-97b4-7755b7e63445.png)
                                Figure 2

**Comment by shyuep** [comment]
I can't reproduce this error.

```
from pymatgen import Structure
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
s = Structure.from_file("POSCAR")
a = SpacegroupAnalyzer(s, 0.1)
ss = a.get_conventional_standard_structure()
ss.to(filename="conv.cif")
s.to(filename="orig.cif")
```

I opened both cifs in VESTA and they look exactly the same.

**Comment by Djordje117** [comment]
It works fine when you increase symprec by 100 times (from 0.001 to 0.1). It also works when symprec increased to 0.01. I only increased up to 3 times. Thank you for the help.

**Comment by shyuep** [comment]
Yes, symmetry detection is based on tolerances. 0.001 is fine if you have a very well defined structure. If you have a DFT relaxed structure, tolerances have to be set lower. Usually we stick to 0.1 as a default.
