### ISSUE TITLE
Bug: VASP INCAR option EINT not parsed as a list

### ISSUE THREAD

**Issue by andreaslinscheid** [materialsproject/pymatgen#724]
Dear pymatgen developers,

I am using Custodian with pymatgen to perform VASP STM runs.
Thank you for providing this well developed piece of software to the community.
The incar option "EINT" is not in the list of parameters specified in pymatgen/vasp/io/inputs.py so it gets parsed in line 817 as a signed int and in=Incar.read_file("INCAR");in.write_file("INCAR") magically resets EINT to a single integer number.
It can be a list of two or one real number so when I append this option to pymatgen/vasp/io/inputs.py line 748 the problem is solved.

A different way of interpreting the error is that you don't implement a default conversion for unknown list parameters (it is understandable that EINT is not common ...).
One could maybe solve this and similar issues with unknown list options by inserting after line 808
try:
    output = []
    toks = re.findall( r"(-?\d+\.?\d*)\*?(-?\d+\.?\d*)?\*?(-?\d+\.?\d*)?", val)
    //similar logic as above for list options
    if len(output) == 0:
        raise ValueError
    return output
except ValueError:
    pass
I have not tested that but I guess you get the idea.

Thank you very much,
Andy

P.s. an INCAR file that triggers this problem is
ALGO = Fast
ECUT = 510
EDIFF = 1e-07
EINT = -0.85 0.85
IBRION = -1
ICHARG = 11
ISIF = 3
ISMEAR = 1
ISPIN = 1
LPARD = True
NBMOD = -3
PREC = Accurate
SIGMA = 0.1

**Comment by shyuep** [comment]
I just fixed this. We do not know the comprehensive list of types. But it is strange that it is being parsed as a int type. Usually for unspecified types, the default goes to a string.

**Comment by andreaslinscheid** [comment]
Thank you for this immediate response.
Looking at the code, I guess unspecified types goes to a string unless they match ^-?\d+ in the beginning. In that case line 817 matches and return this match which in my case ("-0.85 0.85") was -0. Is that what you want? My guess is not because it alters the input parameters.

**Comment by shyuep** [comment]
Ok, I fixed this bad logic in the latest commit .
