### ISSUE TITLE
Bug in Kpoints.automatic_density creates lattice symmetry breaking k mesh

### ISSUE THREAD

**Issue by andreaslinscheid** [materialsproject/pymatgen#729]
Dear pymatgen developers,

I encountered the following problem:
For fcc Al, setting the k point density to 1000kpts/atom, I obtain the k mesh 10x10x9 which breaks the lattice symmetry. The POSCAR is from the materials project:
Al1
1.0
2.473329 0.000000 1.427977
0.824443 2.331877 1.427977
0.000000 0.000000 2.855955
Al
1
direct
0.000000 0.000000 0.000000 Al

Looking at the code, the problem appears to be that I chose by accident a density that has an integer 3rd root.
If that is the case, rounding errors in the length of each lattice vector will tip the scale to be above or below the integer value. Since 'mult' in line 1053 takes these vectors into account, I figure the respective longest of these vectors will get 10 points assigned, while the shortest 9 kpts/direction because of the integer cast 'floor' in line 1055.

The logic also applies when I choose a density of 729 (9^3) in which case the code sets a grid of 9x9x8 where it should be 9x9x9

The easiest solution I can think of is simply checking if kppa is the third power of an integer, e.g. like this, added in line 1052
        if math.fabs((math.floor(kppa**(1/3)+0.5))**3 - kppa) < 1:
            kppa = kppa + kppa*0.01
If this is the case, we simply add 1% (or subtract) to kppa. 

This solved the problem for me.

Cheers,
Andy

**Comment by andreaslinscheid** [comment]
Can anybody confirm this or is there a misunderstanding on my end?

**Comment by shyuep** [comment]
Thanks. I have implemented your fix and pushed the changes.
