### ISSUE TITLE
Design question regarding PointgroupAnalyzer

### ISSUE THREAD

**Issue by mcocdawc** [materialsproject/pymatgen#738]
## System

* Pymatgen version: '2017.7.21'
* Python version: 3.6.1
* OS version: Ubuntu 16.04 LTS

## Summary

``get_pointgroup`` returns a ``pymatgen.symmetry.analyzer.PointGroupOperations`` instance.

## Example code

I use fullerene as example molecule for the pointgroup analyzer [xyz-file here](http://www.nanotube.msu.edu/fullerene/fullerene.php?C=60):
```python
analyser = PointGroupAnalyzer(fullerene)
print(type(analyser.get_pointgroup()))
```
Gives:
```
pymatgen.symmetry.analyzer.PointGroupOperations
```
Isn't this a bit redundant, if you already have a class ``pymatgent.symmetry.groups.Pointgroup``?

## Suggested solution (if any)

* ``get_pointgroup`` should return a ``pymatgent.symmetry.groups.Pointgroup`` instance.

**Comment by shyuep** [comment]
The PointGroup in pymatgen.symmetry.groups are defined based on fractional coordinates and are for use in crystal structures. It is an idealized symmetry class.

PointGroupOperations on the other hand are a series of operations that are determined on cartesian coordinates based on the detected symmetry operations, and are the actual operations you apply on a Molecule (not a crystal). 

The two are not the same.

**Comment by mcocdawc** [comment]
Thank you very much for your answer.

If there is a slightly distorted molecule and pymatgen was able to detect the correct pointgroups (perhaps with tweaking tolerance settings), is there the possibility to obtain the symmetrised molecule?

**Comment by shyuep** [comment]
Well, I think it can be done. You simply need to get all the equivalent atoms, and then choose one of them to be the generating atom, and apply all operations of the point group to get the symmetrized molecule. This functionality is not implemented as yet.

**Comment by mcocdawc** [comment]
Is this planed to be implemented in the near future?

In the molecules, I thought of, I would average over the location of the equivalent atoms, but that is a detail question of implementation.

**Comment by shyuep** [comment]
I am not planning to do it myself. I cannot speak as to whether the ~100 contributors to pymatgen will be doing so. In general, I would recommend you do it yourself and then submit a pull request. I think it is not too difficult.

**Comment by mcocdawc** [comment]
Ok, I will write an Enhancement issue for it, to avoid double work.
