### ISSUE TITLE
Overflow errors in elastic

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#743]
## System

* Pymatgen version: master
* Python version: 3.6.2
* OS version: Linux

## Summary

* Tests are showing overflow errors. Looking at the equations, it seems that there should be some special handling if t is very small.
```
/root/pymatgen/pymatgen/analysis/elasticity/elastic.py:644: RuntimeWarning: overflow encountered in double_scalars
c *= np.exp(hbar_w / kt) / (np.exp(hbar_w / kt) - 1)**2
/root/pymatgen/pymatgen/analysis/elasticity/elastic.py:644: RuntimeWarning: overflow encountered in exp
c *= np.exp(hbar_w / kt) / (np.exp(hbar_w / kt) - 1)**2
/root/pymatgen/pymatgen/analysis/elasticity/elastic.py:644: RuntimeWarning: invalid value encountered in double_scalars
c *= np.exp(hbar_w / kt) / (np.exp(hbar_w / kt) - 1)**2
```

Though the code may actually work, it is best to explicitly handle such cases to avoid ambiguity.

@montoyjh Can you fix pls?

**Comment by montoyjh** [comment]
Fixed via 52b3c05.
