### ISSUE TITLE
Possible error reading user_incar_settings in DictSet

### ISSUE THREAD

**Issue by iicurtis** [materialsproject/pymatgen#754]
## System

* Pymatgen version: master
* Python version: 3.6.2
* OS version: Linux 4.12.4-1-ARCH

## Summary

* Passing `{'LDAU': True, 'LDAUU': {'S': 0.0, 'Sm': 1.0}} to  MPStaticSet, the run crashes with KeyError("LDAUU")
* In pymatgen/io/vasp/sets.py: line 291:
```python
                        if isinstance(v[most_electroneg], dict):
                           incar[k] = [v[most_electroneg].get(sym, 0)
                                       for sym in poscar.site_symbols]
```
* `v` is a dict in my case (`{'S': 0.0, 'Sm': 1.0}`). Testing a value to check if it is a dict does not make sense to me.
* `v[most_electroneg]` should be a float, right? (`0.0`)
* Modifying as follows allows the run to go through:
```python
                        if isinstance(v, dict):
                           incar[k] = [v.get(sym, 0)
                                       for sym in poscar.site_symbols]
```

## Example code

```python
uis_elastic = {
    "ISPIN": 2,
    "LDAU": True,
    "LDAUL": {"S": -1, "Sm": 3},
    "LDAUU": {"S": 0, "Sm": 7.1},
    "LDAUJ": {"S": 0, "Sm": 1.0},
    "LDAUTYPE": 2,
    "LMAXMIX": 6,
    "LASPH": True}

vis_input = MPStaticSet(structure,                    # Crashes
                        user_incar_settings=uis_elastic)

```

## Error message

```
    Traceback (most recent call last):
    File "../runit_default.py", line 35, in <module>
    print(vis_input.incar)
    File "/zdata/icurtis/atomate/codes/pymatgen/pymatgen/io/vasp/sets.py", line 492, in incar
    parent_incar = super(MPStaticSet, self).incar
    File "/zdata/icurtis/atomate/codes/pymatgen/pymatgen/io/vasp/sets.py", line 311, in incar
    has_u = hubbard_u and sum(incar['LDAUU']) > 0
    KeyError: 'LDAUU'
```

## Suggested solution (if any)

* Change line 291 in pymatgen/io/vasp/sets.py from:
```python
                        if isinstance(v[most_electroneg], dict):
                           incar[k] = [v[most_electroneg].get(sym, 0)
                                       for sym in poscar.site_symbols]
```
to

```python
                        if isinstance(v, dict):
                           incar[k] = [v.get(sym, 0)
                                       for sym in poscar.site_symbols]
```
(removing the `[most_electroneg]` index from our value dict)

**Comment by shyuep** [comment]
I am not quite sure what you are intending here. But the format of the LDAUU and LDAUJ is not correct. This is a dict of a dict. The right formation should be:

```
    "LDAUL": {"S": {"Sm": 3}},
    "LDAUU": {"S": {"Sm": 7.1}}, 
    "LDAUJ": {"S": {"Sm": 1.0}},
```

U values are set based on the anion (most_electroneg). Also, there should be no U value on S. There is therefore no need to set a value there.

**Comment by iicurtis** [comment]
My apologies, I misunderstood how these values are set using pymatgen. If I wanted to set multiple species, how would this be done? E.g. for SmLaS, would I apply:
```python
"LDAUL": {"S": {"Sm": 3, "La": 3}}
"LDAUU": {"S": {"Sm": 7.1, "La": 6.5}}, 
"LDAUJ": {"S": {"Sm": 1.0, "La": 1.0}},
```

**Comment by mkhorton** [comment]
I think this is actually a subtle bug ...

This [line](https://github.com/materialsproject/pymatgen/blob/7ec9509e543bd84268d21b893e8a0c879f2343e4/pymatgen/io/vasp/sets.py#L290):

```
                    elif most_electroneg in v.keys():
                        if isinstance(v[most_electroneg], dict):
```

should read

```
                    elif (most_electroneg in v.keys()) and \
                          (isinstance(v[most_electroneg], dict):
```

I'll submit a PR to fix

**Comment by mkhorton** [comment]
@iicurtis the origin of this bug is a bit complicated, but basically when running in high-throughput calculations, it's useful to define anion-specific LDAU values, which is why `user_incar_settings` has this nested dict structure (e.g. `"LDAUU": {"S": {"Sm": 7.1, "La": 6.5}}`), and it attempts to detect the anion first so that the appropriate LDAU value is used.

However, if you're just doing an individual calculation, it's often much more convenient to set your LDAU values directly (e.g. with your original example `"LDAUU": {"S": 0, "Sm": 7.1}`), and pymatgen also supports this. Since your structure contained one of these anions, but did *not* contain this nested dict structure, this bug was triggered.
