### ISSUE TITLE
Need add ruamel.yaml to matsci channel as dependency of pymatgen

### ISSUE THREAD

**Issue by specter119** [materialsproject/pymatgen#758]
## System

* Pymatgen version: v2017.8.4
* Python version:  3.6
* OS version: windows

## Summary

pymatgen add ruamel.yaml>=0.15.6 to requirement in v2017.8.4.
But ruamel.yaml is named as ruamel_yaml in conda default channel, and its current version is 0.11.14.
It's better to include ruamel.yaml to matsci channel to solve the dependency of pymatgen.

**Comment by shyuep** [comment]
Done.

**Comment by specter119** [comment]
@shyuep Thanks!
