### ISSUE TITLE
Feature request: Surface properties to MAPI

### ISSUE THREAD

**Issue by CifLord** [materialsproject/pymatgen#768]
Add recent data from:
Tran, R., Xu, Z., Radhakrishnan, B., Winston, D., Sun, W., Persson, K. A., & Ong, S. P. (2016). Data Descripter: Surface energies of elemental crystals. Scientific Data, 3(160080), 1–13. https://doi.org/10.1038/cgt.2016.38

to the Materials Project API and corresponding documentation to mapidoc

@richardtran415 will take charge

**Comment by richardtran415** [comment]
Assign to richardtran415
