### ISSUE TITLE
Periodic heatmap

### ISSUE THREAD

**Issue by richardtran415** [materialsproject/pymatgen#769]
New feature to util, a function to plot a publication quality periodic table with user input values for each table entry. The table will be a heatmap to easily discern some periodic trends  related to a specific property eg surface energy, work function, Young's modulus etc. See:

Lejaeghere, K., Van Speybroeck, V., Van Oost, G., & Cottenier, S. (2014). Error Estimates for Solid-State Density-Functional Theory Predictions: An Overview by Means of the Ground-State Elemental Crystals. Critical Reviews in Solid State and Materials Sciences, 39(1), 1–24. https://doi.org/10.1080/10408436.2013.772503

as an example.

@richardtran415 will take charge

**Comment by richardtran415** [comment]
Assign to richardtran415

**Comment by shyuep** [comment]
This is a good idea. But I am assigning this to @johnson1228 since he just implemented this for a paper.

**Comment by mkhorton** [comment]
+1 for this, almost implemented it myself ... will look forward to testing this

**Comment by shyuep** [comment]
@johnson1228 Note that the heatmap should support empty values. E.g., people can provide a dict of {"Li": value, ..}. If no value is provided, a default greyed out thing should be used. The first version does not need to support color scheme choices. The subsequent versions should allow for it.

**Comment by richardtran415** [comment]
@johnson1228 it should also have a parameter that allows the user to choose whichever color scheme they want for the heatmap, eg. 'PuBu' or 'plasma'

**Comment by mkhorton** [comment]
Regarding color scheme choices, it should be fairly easy just to use the standard matplotlib colormap objects (e.g. `from matplotlib.cm import viridis`) these objects take an int from 0-255 and return a color.

**Comment by shyuep** [comment]
I will leave @johnson1228 to do this. Don't worry about this. This will be implemented at the MAVRL weekly hackathon tomorrow.

**Comment by computron** [comment]
How about
http://bokeh.pydata.org/en/latest/docs/gallery/periodic.html

Or
https://github.com/wolverton-research-group/periodic-table-plotter/tree/master/examples

**Comment by shyuep** [comment]
Ours will be better.

**Comment by shyuep** [comment]
I have moved this to pymatgen.util.plotting as I think it is more appropriate there. This is good enough for further finetuning.
