### ISSUE TITLE
A tiny problem in class Composition

### ISSUE THREAD

**Issue by YunxingZuo** [materialsproject/pymatgen#772]
When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.

## System

* Pymatgen version: 2017.8.14
* Python version: 3.6
* OS version: OSX 10.12.5

## Summary

According to the Jupyter Notebook about getting data from Materials Projects in matgenb, if I use the chemical formula like "Li1Fe1P1O4", the getting process don't work.

## Example code
```python

from pymatgen import MPRester, Composition
import re
comp = Composition("Li1Fe1P1O4")
anon_formula = comp.anonymized_formula
anon_formula = {m.group(1): int(m.group(2)) 
                for m in re.finditer(r"([A-Z]+)(\d+)", anon_formula)}

```

## Error message

```
# Error message
```

## Suggested solution (if any)
Here the variable "anon_formula" should be a dict: {'A':1, 'B':1, 'C': 1, 'D':4}, instead it comes {'ABCD': 1}. It is because in the Composition class in pymatgen.core.composition, when it comes to 1, the property "anon_formula" automatically deletes the number 1 and gives an empty string. 

## Files (if any)

* If input files are needed to reproduce the error, please provide 
either links (e.g., Dropbox or GDrive) for large files or simply paste
the file below for small files.

```
<contents of file 1>
```

**Comment by shyuep** [comment]
The anon formula is ABCD4. Your regular expression is wrong. It should be ([A-Z][a-z]*)(\d*).
