### ISSUE TITLE
ReplaceSiteSpeciesTransform disordering map input fails

### ISSUE THREAD

**Issue by paulfons** [materialsproject/pymatgen#773]
When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.

## System

* Pymatgen version: pymatgen-2017.8.16
* Python version: Python 2.7
* OS version: CentOS 7

## Summary

* The documentation for ReplaceSiteSpeciesTransform states that it will replace site species with new sites according to a user provided dictionary. It states that operator overloading is enabled such that a mapping of the form {"Si":{"Si":0.75,"Ge":0.25}} will allow disordering of sites (in this case Si sites). It does not work as the code casts the dictionary key into an integer.

## Example code

In [79]: s1 = mg.Structure(lattice, ["Cs", "Cl"], [[0, 0, 0], [0.5, 0.5, 0.5]])

In [80]: s1

Out[80]: 

Structure Summary

Lattice

    abc : 4.2000000000000002 4.2000000000000002 4.2000000000000002

 angles : 90.0 90.0 90.0

 volume : 74.088000000000008

      A : 4.2000000000000002 0.0 0.0

      B : 0.0 4.2000000000000002 0.0

      C : 0.0 0.0 4.2000000000000002

PeriodicSite: Cs (0.0000, 0.0000, 0.0000) [0.0000, 0.0000, 0.0000]

PeriodicSite: Cl (2.1000, 2.1000, 2.1000) [0.5000, 0.5000, 0.5000]

In [85]: mymap = {"Cs":{"Si":0.75,"Ge":0.25}}

In [86]: transform = ReplaceSiteSpeciesTransformation(mymap)

In [87]: transformed = transform.apply_transformation(s1)

```python
# Example code generating error
```

## Error message

```
ValueError                                Traceback (most recent call last)

<ipython-input-87-02f99378f276> in <module>()

----> 1 transformed = transform.apply_transformation(s1)



/usr/lib64/python2.7/site-packages/pymatgen/transformations/site_transformations.pyc in apply_transformation(self, structure)

    100         s = structure.copy()

    101         for i, sp in self.indices_species_map.items():

--> 102             s[int(i)] = sp

    103         return s

    104 



ValueError: invalid literal for int() with base 10: 'Cs'

```

## Suggested solution (if any)

* If you have a suggestion on how to solve the issue, you may write it
  here.

The source code for the ReplaceSiteSpeciesTransform

def apply_transformation(self, structure):
        s = structure.copy()
        for i, sp in self.indices_species_map.items():
            s[int(i)] = sp  <----------- casts string dictionary key ("Cs" in this case) into an int and fails
        return s
## Files (if any)

* If input files are needed to reproduce the error, please provide 
either links (e.g., Dropbox or GDrive) for large files or simply paste
the file below for small files.

```
<contents of file 1>
```

**Comment by shyuep** [comment]
The documentation here is wrong. ReplaceSiteSpecies only replaces a single site. The right syntax should be 

```
trans = ReplaceSiteSpeciesTransformation({0: {"Li": 0.5, "Na":0.5}})
trans.apply_transformation(s)
```

In other words, the key needs to be a numerical index.

Unless you have a good reason to use a transformation  (e.g., you need to keep track of provenance), the easiest way is to simply directly modify the structure.

```
# Modify a single site
s[0] = {"Li": 0.5, "Na": 0.5}

# Modify all sites containing Li
s["Li"] = {"Li": 0.5, "Na": 0.5}
```

**Comment by paulfons** [comment]
Dear Shyue Ping,

  Thank you for your note.  Even for a Python amateur like myself, it was clear that the source code only took numerical indices, but I was confused by the documentation. Your alternative 

> s[0] = {"Li": 0.5, "Na": 0.5}

is a good solution for randomizing a lattice. On the same thread, if I wish to run a VASP calculation on a disordered lattice, is there a way to get pymatgen to “throw the dice” and assign a specific specie or is this something I would have to code myself?

Best wishes,
                    Paul

**Comment by mkhorton** [comment]
> On the same thread, if I wish to run a VASP calculation on a disordered lattice, is there a way to get pymatgen to “throw the dice” and assign a specific specie or is this something I would have to code myself?

`OrderDisorderedStructureTransformation` can help with this, see example notebook here: http://pymatgen.org/_static/Ordering%20Disordered%20Structures.html

This will give an ordered approximation of your disordered structure. I don't believe pymatgen has functionality for giving a random approximation, though maybe @shyuep can correct me on that.

**Comment by shyuep** [comment]
No random version. But you can get a list from the apply_transformation and set return_rank_list = whatever number and then just do a random.shuffle if you wish.
