### ISSUE TITLE
Query conventional unit cell with MPRester

### ISSUE THREAD

**Issue by richardtran415** [materialsproject/pymatgen#784]
Is there a method in in MPRester that can return the conventional standard structure from Materials Project instead of just the primitive unit cell, I know the SpacegroupAnalyzer has such a tool for getting this structure, but I think it would be more convenient to just have a way to quickly get it from MPRester instead of querying for the primitive structure and then converting it with SpacegroupAnalyzer everytime.

**Comment by shyuep** [comment]
Hmmm... I think the query method might be able to do that. You need to check the mapidoc to see if the conventional structure is stored in one of the keys.

**Comment by richardtran415** [comment]
I see, OK, thank you for the info

**Comment by mkhorton** [comment]
Just checked the mapidoc, and there's a `cifs.conventional_standard` key that can give this, but no actual Structure object I can see. You can then use `Structure.from_str(..., fmt='cif')` on the returned string to get back your Structure object. Whether it's worth using this over just using SpacegroupAnalyzer I wouldn't know.
