### ISSUE TITLE
missing imports + no unit tests?

### ISSUE THREAD

**Issue by computron** [materialsproject/pymatgen#788]
There are multiple functions in

pymatgen.analysis.defects.point_defects

that seem to be missing key imports to work.

e.g.
pymatgen.analysis.defects.point_defects.get_okeeffe_params is missing BV_PARAMS
get_okeeffe_distance_prediction is missing math

I am pretty sure these functions are not even going be runnable. Are there no unit tests at all?

**Comment by shyuep** [comment]
@nisse3000 Pls fix. I think yu and Bharat were co-authors on this class? And pls add unittests.

**Comment by nisse3000** [comment]
Sorry, I forgot to put in the unit tests for the other neighbor-finding methods (i.e., the non-min_dist ones). Will come shortly.

**Comment by shyuep** [comment]
@nisse3000 Is this resolved?

**Comment by nisse3000** [comment]
Yes, I'll issue a pull request shortly in which the last remaining unit tests are added.  I didn't add tests for solid_angle, get_okeeffe_params, get_okeeffe_distance_prediction because those are called from the class tests. Is that acceptable, @shyuep?

**Comment by shyuep** [comment]
That's fine for now.
