### ISSUE TITLE
VASP KPOINTS file with Line_mode

### ISSUE THREAD

**Issue by gVallverdu** [materialsproject/pymatgen#79]
Hi !
I am new in pymatgen and I try to use it to produce KPOINTS file for band structure calculations with VASP. I use HighSymmKpath and Kpoints classes to produces the kpoints file.

Here is the source code

``` python
import pymatgen as mg
from pymatgen.symmetry.bandstructure import HighSymmKpath
from pymatgen.io.vaspio.vasp_input import Kpoints

struct = mg.read_structure("POSCAR.vasp")

# First brillouin zone
ibz = HighSymmKpath(struct)
print("ibz type     : {0}".format(ibz.name))

# suggested path
print("paths in first brillouin zone :")
for path in ibz.kpath["path"]:
    print(path)

kpoints = list()
labels = list()
for path in ibz.kpath["path"]:
    for kpts in path:
        kpoints.append(ibz.kpath["kpoints"][kpts])
        labels.append(kpts)

# print kpoints file
Kpoints(comment = "band diagram for monoclinic cell, unique axes a",
        num_kpts = 100,
        style = Kpoints.supported_modes.Line_mode,
        coord_type = "Reciprocal",
        kpts = kpoints,
        labels = labels,
        ).write_file("KPOINTS")
```

And this is the KPOINTS file produced 

```
band diagram for monoclinic cell, unique axes a
100
Line_mode
0.0 0.0 0.0            ! \Gamma
0.0 0.0 0.5            ! Y
0.0 0.491941 0.525184  ! H
0.0 0.5 0.5            ! C
0.5 0.5 0.5            ! E
0.5 0.508059 0.474816  ! M_1
0.5 0.5 0.0            ! A
0.0 0.5 0.0            ! X
0.0 0.508059 0.474816  ! H_1
0.5 0.491941 0.525184  ! M
0.5 0.0 0.5            ! D
0.5 0.0 0.0            ! Z
0.0 0.0 0.5            ! Y
0.5 0.0 0.5            ! D
```

After the line `Line_mode` in the KPOINTS file, the `coord_type` should be written.

Looking at 

http://pymatgen.org/_modules/pymatgen/io/vaspio/vasp_input.html#Kpoints

in the `__str__` method there is these lines 

``` python
style = self.style.lower()[0]
        if style == "Line-mode":
            lines.append(self.coord_type)
```

but line_mode is not written with an underscore as in the supported mode enum and I think this is the bug (or maybe the mistake for only one character  ...)

``` python
supported_modes = Enum(("Gamma", "Monkhorst", "Automatic", "Line_mode",
                            "Cartesian", "Reciprocal"))
```

The following is maybe a request more than a bug. Using VASP, in Line_mode the KPOINTS file should be 

```
band diagram for monoclinic cell, unique axes a
100
Line_mode
Reciprocal
0.0 0.0 0.0            ! \Gamma
0.0 0.0 0.5            ! Y

0.0 0.0 0.5            ! Y
0.0 0.491941 0.525184  ! H

0.0 0.491941 0.525184  ! H
0.0 0.5 0.5            ! C

0.0 0.5 0.5            ! C
0.5 0.5 0.5            ! E

0.5 0.5 0.5            ! E
0.5 0.508059 0.474816  ! M_1

0.5 0.508059 0.474816  ! M_1
0.5 0.5 0.0            ! A

0.5 0.5 0.0            ! A
0.0 0.5 0.0            ! X

0.0 0.5 0.0            ! X
0.0 0.508059 0.474816  ! H_1

0.5 0.491941 0.525184  ! M
0.5 0.0 0.5            ! D

0.5 0.0 0.5            ! D
0.5 0.0 0.0            ! Z

0.0 0.0 0.5            ! Y
0.5 0.0 0.5            ! D
```

I have ever talk about the line with "Reciprocal". Then each line of the reciprocal space is defined by 2 k-points separated by a blank line. Is there a way to obtain this directly from pymatgen without postprocessing the KPOITNS file ? 
A solution migth be to give the kpath attribute of the HighSymmKpath to a Kpoints class constructor or directely the HighSymmKpath object. But the `__str__` method must be also slithly modified.
I cloned the git repository and did the few changes.
Here is a patch file created with `git diff > patch.txt`

www.pastebin.com/5n6aniLv

I am sorry but I am a beginner with git. I do not know how to make the development version and the stable version of pymatgen to cohabit in the same PC. Thus I did not test my changes ... If you prefer and explain I can commit and push somewhere ?

Thanks

**Comment by soved** [comment]
This will do the trick:
# First brillouin zone
ibz = HighSymmKpath(struct,symprec=prec)

#Generating labels and kpath
kpoints = []
labels = []

j,s=0,0
for path in ibz.kpath["path"]:
    s=0
    for kpts in path:
        kpoints.append(ibz.kpath["kpoints"][kpts])
        labels.append(kpts)
        s = s+1
        if j%2 != 0 and len(path) != s:
            kpoints.append(ibz.kpath["kpoints"][kpts])
            labels.append(kpts)
            j=0
        j = j+1

# print kpoints file
Kpoints(comment = "Kpath",
        num_kpts = dens,
        style = Kpoints.supported_modes.Line_mode,
        coord_type = "Reciprocal",
        kpts = kpoints,
        labels = labels,
        ).write_file("KPOINTS")
