### ISSUE TITLE
Missing unit tests for LammpsForceFieldData

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#799]
Right now, there is no test for LammpsForceFieldData in test_data.py. This caused changes to LammpsData, which is the subclass to break unittests in sets.py, but not break tests in test_data.py.

A basic test should be implemented for LammpsForceFieldData to ensure that refactoring change errors get caught in a granular level. @matk86

**Comment by matk86** [comment]
test_forcefield_data.py has LammpsForceFieldData tests

**Comment by shyuep** [comment]
Ok. Can you move these to test_data? The idea here is for test_*name* to correspond to the tests for *name*.py module. That way, people don't need to think that they need to find another test file to ensure the module works.
