### ISSUE TITLE
Pathological error in VoronoiCoordFinder for slabs

### ISSUE THREAD

**Issue by CifLord** [materialsproject/pymatgen#801]
There is an issue for some slab structures where a `RunTimeError` occurs stating the structure is pathological. I think this may be due to the code being unable to properly create a convex hull for surface sites where there are neighboring atoms in the vacuum. There is a tag called `allow_pathological` that bypasses this error with an exception, but a more robust solution tackling the source of the problem would be preferred.

## Example code

```python
from pymatgen.core.surface import SlabGenerator, Lattice, Structure

lattice = Lattice.cubic(3.149000)
Mo = Structure(lattice, ["Mo", "Mo"], [[0,0,0], [0.5,0.5,0.5]])
slabgen = SlabGenerator(Mo, (1,0,0), 10, 20)
slab = slabgen.get_slabs()[0]

from pymatgen.analysis.structure_analyzer import VoronoiCoordFinder

v = VoronoiCoordFinder(slab)
for i, site in enumerate(slab):
    cn = v.get_coordination_number(i)
```

raises

```py
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-18-ec5ec645f8df> in <module>()
      8 v = VoronoiCoordFinder(slab)
      9 for i, site in enumerate(slab):
---> 10     cn = v.get_coordination_number(i)

/repos/pymatgen/pymatgen/analysis/structure_analyzer.py in get_coordination_number(self, n)
    121             n (int): Site index
    122         """
--> 123         return sum(self.get_voronoi_polyhedra(n).values())
    124 
    125     def get_coordinated_sites(self, n, tol=0, target=None):

/repos/pymatgen/pymatgen/analysis/structure_analyzer.py in get_voronoi_polyhedra(self, n)
     91                         continue
     92                     else:
---> 93                         raise RuntimeError("This structure is pathological,"
     94                                            " infinite vertex in the voronoi "
     95                                            "construction")

RuntimeError: This structure is pathological, infinite vertex in the voronoi construction
```

**Comment by whyydsforever** [comment]
How to use the 'allow_pathological'

**Comment by shyuep** [comment]
Seems like this issue has been defunct for many years. Closing.... Feel free to reopen if still valid.

**Comment by kdeoskar** [comment]
I don't have permission to reopen the issue, but I'm getting the same error. 

I'm trying to find the local chemical environments around Kagome atoms in Kagome materials using [this code by J. George et. al.](https://github.com/JaGeo/Tutorial_ChemEnv/blob/master/Tutorial.ipynb). I have a large list of Materials Project mpids I'm parsing through my functions, and a few of them are pathological - giving this infinite vertex runtime error.

I'd like to use the allow_pathological to avoid crashing the program for these pathological mpids but I can't find any documentation on it. Is this feature still available? If not, should I just try edit the method in voronoi.py? Any advice would be appreciated. Thanks.
