### ISSUE TITLE
enumlib_caller: makestr.x deprecated

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/pymatgen#814]
An FYI: I noticed that makestr.x has been deprecated in enumlib, replaced by [makeStr.py](https://github.com/msg-byu/enumlib/tree/master/aux_src). I don't know if these are interchangeable, but we should probably update `enumlib_caller` at some point in case the code diverges more in future. (Also, I think [this test](https://github.com/materialsproject/pymatgen/blob/master/pymatgen/command_line/tests/test_enumlib_caller.py#L31) is being incorrectly skipped if `enum.x` is present, even if `multienum.x` is not.)

**Comment by shyuep** [comment]
Ok. If you can fix these, it would be great. In general, I use only latest enumlib since that has significant speed advantages with the latest symmetry handling.

**Comment by volodiag** [comment]
Hello,

The supporting files provided indeed work, thank you.
However, please update the error message in pymatgen that is misleading.

Error message gotten
RuntimeError: EnumlibAdaptor requires the executables 'enum.x' or 'multienum.x' and 'makestr.x' or 'makeStr.py' to be in the path. Please download the library at http://enum.sourceforge.net/ and follow the instructions in the README to compile these two executables accordingly.

File to be updated 
pymatgen.command_line.enumlib_caller line 71

It should instead redirect to this link.
https://github.com/materialsproject/pymatgen/tree/master/cmd_line/enum

kind regard
