### ISSUE TITLE
get_conventional_standard in pymatgen.symmetry.finder.SymmetryFinder changes symmetry

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#82]
Using https://www.materialsproject.org/materials/mp–715572/, when converting the primitive cell to conventional standard, the space group changes from C2 to P1. Given that this is just a basis transformation, this really should be the case.

**Comment by shyuep** [comment]
@hautierg Can you fix this soon pls? This is really a major issue. There is no guarantee that the band structures are right if the symmetry is not preserved.

**Comment by terencezl** [comment]
I assume the method is now pymatgen.symmetry.analyzer.SpacegroupAnalyzer? I can't reproduce this. symprec is set to 0.1, and SpacegroupAnalyzer correctly finds C2, and the get_conventional_standard method returns a structure with C2 as well. Why is this issue still here?

**Comment by hautierg** [comment]
This should not be open anymore. I am closing it.
