### ISSUE TITLE
Possible bug in local_env.py or PeriodicSite/Lattice, incorrect jimage?

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/pymatgen#827]
## System

* Pymatgen version: 2017.9.1 (development)
* Python version: 3.6.0
* OS version: macOS 10.12.6

## Summary

Would appreciate a sanity check here. I'm looking at a single layer of MoS2 from a .cif file ([attached](https://raw.githubusercontent.com/mkhorton/pymatgen/e807247f43153a71b6f3389120c623c3d7e13c25/test_files/critic2/MoS2.cif)), where site 0 is Mo, site 1 is S, site 2 is S. From a visual inspection in VESTA, I see the Mo site has the following neighbors in the periodic images specified:

0 -> 1, (0, 0, 0)
0 -> 1, (0, 1, 0)
0 -> 1, (-1, 0, 0)
0 -> 2, (0, 0, 0)
0 -> 2, (0, 1, 0)
0 -> 2, (-1, 0, 0)

However, using `MinimumDistanceNN()` (which is very straight-forward, most logic comes from `PeriodicSite`/`Lattice`), I get:

0 -> 1, (0, 0, 0)
0 -> 1, (0, 1, 0)
0 -> 1, (1, 1, 0)  # this line is different
0 -> 2, (0, 0, 0)
0 -> 2, (0, 1, 0)
0 -> 2, (1, 1, 0)  # this line is different

This seems wrong to me, but I'm having difficulty tracking down the bug, I get the same results with `MinimumOKeeffeNN` too ... @nisse3000 do you have any ideas?

## Example code

```python
from pymatgen.core import Structure
from pymatgen.analysis.local_env import MinimumDistanceNN
s = Structure.from_file('MoS2.cif')
nn = MinimumDistanceNN()
nn.get_nn_info(s, 0)  # neighbors of Mo site
```
## Files (if any)

MoS2 CIF file [here](https://raw.githubusercontent.com/mkhorton/pymatgen/e807247f43153a71b6f3389120c623c3d7e13c25/test_files/critic2/MoS2.cif).

**Comment by mkhorton** [comment]
A little bit closer to diagnosing this, but still don't understand what's going on here...

Using the same `lattice`* from the CIF file,

```
f1 = [0.3333, 0.6666, 0.21329]
f2 = [2/3., 1/3., 0.12356]
lattice.get_distance_and_image(f1, f2)  # returns (2.4169088271902091, array([0, 0, 0]))
```

Alternatively,

```
f1 = [1/3., 2/3., 0.21329]  # now using 'exact' co-ords
f2 = [2/3., 1/3., 0.12356]
lattice.get_distance_and_image(f1, f2)  # returns (2.4169088271902091, array([0, 1, 0]))
```

In the first instance, we get the correct dist and correct jimage, in the second case we do not. I can't see an obvious error in the function however. Could this be a `coord_utils_cython` issue?


* `lattice` is:
```
array([[  3.19031600e+00,   0.00000000e+00,   1.95350514e-16],
       [ -1.59515800e+00,   2.76289400e+00,   1.95350477e-16],
       [  0.00000000e+00,   0.00000000e+00,   1.74395020e+01]])
```

**Comment by nisse3000** [comment]
It's a numerical issue because the third cell angle is 120 degrees. Does that make sense?

![img_20170905_204016](https://user-images.githubusercontent.com/11105218/30093567-0a643efc-927b-11e7-9c31-c915a24ff32c.jpg)

**Comment by mkhorton** [comment]
Hi Nils -- from your attached image, the neighbor from 1 (0,0) to 2' (0,1) makes sense to me, but isn't the code suggesting a neighbor to (1,1) too? Maybe I'm not looking at it right, but the (1,1,0) image just doesn't make sense to me.

**Comment by shyuep** [comment]
I am pretty sure the PeriodicSite jimage is correct.

**Comment by mkhorton** [comment]
Okay, thanks both. I've attached a sketch to illustrate the behavior I was expecting, which might help show where I'm getting confused ...

<img width="943" alt="mos2_sketch" src="https://user-images.githubusercontent.com/2976580/30093948-91393c32-927d-11e7-88ac-6868940d6b1d.png">

**Comment by shyuep** [comment]
I think I see what's happening here. The problem is that in the MinNN code, the image is defined relative to Mo. Since there are 6 S atoms that are at degenerate distance to Mo, any of the images are likely to be returned based on slight numerical perturbations. 

Based on your supplied structure, the NN to MO are:
```
[(PeriodicSite: S (-1.5952, 0.9210, 5.2846) [-0.3333, 0.3333, 0.3030],
  2.4169302746952126,
  1),
 (PeriodicSite: S (1.5952, 0.9210, 5.2846) [0.6667, 0.3333, 0.3030],
  2.4169344853367503,
  1),
 (PeriodicSite: S (0.0000, 3.6839, 5.2846) [0.6667, 1.3333, 0.3030],
  2.4169300062989856,
  1),
 (PeriodicSite: S (-1.5952, 0.9210, 2.1549) [-0.3333, 0.3333, 0.1236],
  2.4169415662251317,
  2),
 (PeriodicSite: S (1.5952, 0.9210, 2.1549) [0.6667, 0.3333, 0.1236],
  2.4169457768469989,
  2),
 (PeriodicSite: S (0.0000, 3.6839, 2.1549) [0.6667, 1.3333, 0.1236],
  2.4169412978301592,
  2)]
```
If you look at the above, the third site has a slightly smaller distance than the first and second site. So when you do a jimage calculation, the algo maps site 1 and 2 to site 3. Site 3 is therefore the (0,0,0) image reference [the (010) site in your figure). When the algo tries to find the shortest distance for site 1 for example, it needs to move your (-1, 0, 0) site to (0, 1, 0). Hence the jimage is (110).

Makes sense?

**Comment by mkhorton** [comment]
Ah, that explains it, thank you! Do you think the behavior in local_env should be changed to account for this then? Though the returned jimages are technically correct, this seems fairly non-intuitive, especially since it's fundamentally a precision issue.

I think I'd be inclined just to get the jimages by subtracting the frac coords of the corresponding original PeriodicSite in the origin lattice from the PeriodicSite returned by the NN class. In the list you've provided this would give` [[-1, 0, 0], [0, 0, 0], [0, 1, 0], ...]`.

**Comment by shyuep** [comment]
I agree your definition is probably more intuitive. In that case, I would carefully explain what the "image" means in the context of local_env to avoid confusion with the `distance_and_image` definition of jimage. The former really tells you what mappings from an existing site within the cell gives you another neighbor. The latter really is aiming to give you the shortest distance between two points, and what image mapping needs to be added to give that.

**Comment by nisse3000** [comment]
Thank you @mkhorton and @shyuep for raising this issue.

I agree that Matt's definition is more intuitive. But I had in mind that it is important to keep track of lattice displacement vectors when you do 2nd-nearest neighbor analysis. So, I think the best course of action is to update the documentation to clearly state that these are lattice displacement vectors, not image locations.

Do you guys agree, or do you see a more important use of the image locations over the lattice displacement vectors? In that case, we should go for Matt's suggestion, I guess.

**Comment by mkhorton** [comment]
I don't have strong opinions on this -- if you think it's useful to keep the original definition for other reasons, then let's do that. I wouldn't be surprised if people might mis-use it though.

I more just wanted to understand what was going on because it was causing an issue in my graph class, obtaining incorrect topology. However, now I know, it was just a one-line fix and it works fine now, regardless of what definition ends up being used in local_env.

**Comment by shyuep** [comment]
I would think using Matt's suggestion is better. It does not make sense for the local_env to map vectors to just the absolute nearest image. The whole idea is to identify multiple NN, which have different distances to the center atom.
