### ISSUE TITLE
How to vary slab thickness when creating slab?

### ISSUE THREAD

**Issue by balabi0github** [materialsproject/pymatgen#832]
Dear developers,

I am trying to use pymatgen to create slab structure. I want to create a single and a double quintuple layer of Bi2Se3.

Bi2Se3 has spacegroup 166, and the conventional cell of hexagonal setting has 15 atom layers along c axis which is 3 quintuple layer (as show in [this picture](https://www.researchgate.net/profile/Xi_Dai/publication/232748137/figure/fig3/AS:267706196820008@1440837539369/Figure-1-Crystal-structurea-Crystal-structure-of-Bi2Se3-with-three-primitive-lattice.png) . But I want to make a single quintuple layer.

I can use SlabGenerator to easily create 3 quintuple layer Bi2Se3

```
cif_file=r'r:\Bi2Se3.cif'
structure=pymatgen.Structure.from_file(cif_file)
slabgen = SlabGenerator(structure, (0,0,1), 10, 10)
all_slabs = slabgen.get_slabs()      
cif_file_obj=pymatgen.io.cif.CifWriter(all_slabs[2],symprec=1e-4)    # all_slabs[2] gives the correct surface
cif_file_obj.write_file(r'r:\Bi2Se3_layer.cif')
```

But the problem is how to make 1 quintuple layer or double layer, or even 1.5 layer of Bi2Se3?
I didn't find an option to control this. Is this possible with pymatgen?

best regards

------------

below is Bi2Se3 cif file : 

data_Bi2Se3_zhanghaijun
_audit_creation_method         'generated by CrystalMaker 9.1.4'
_cell_length_a                   4.1380(0)
_cell_length_b                   4.1380(0)
_cell_length_c                  28.6400(0)
_cell_angle_alpha               90.0000(0)
_cell_angle_beta                90.0000(0)
_cell_angle_gamma              120.0000(0)

_symmetry_space_group_name_H-M     'R -3 m'
_symmetry_Int_Tables_number         166
_symmetry_cell_setting             trigonal
loop_
_symmetry_equiv_pos_as_xyz
'+x,+y,+z'
'2/3+x,1/3+y,1/3+z'
'1/3+x,2/3+y,2/3+z'
'-y,+x-y,+z'
'2/3-y,1/3+x-y,1/3+z'
'1/3-y,2/3+x-y,2/3+z'
'-x+y,-x,+z'
'2/3-x+y,1/3-x,1/3+z'
'1/3-x+y,2/3-x,2/3+z'
'+y,+x,-z'
'2/3+y,1/3+x,1/3-z'
'1/3+y,2/3+x,2/3-z'
'+x-y,-y,-z'
'2/3+x-y,1/3-y,1/3-z'
'1/3+x-y,2/3-y,2/3-z'
'-x,-x+y,-z'
'2/3-x,1/3-x+y,1/3-z'
'1/3-x,2/3-x+y,2/3-z'
'-x,-y,-z'
'2/3-x,1/3-y,1/3-z'
'1/3-x,2/3-y,2/3-z'
'+y,-x+y,-z'
'2/3+y,1/3-x+y,1/3-z'
'1/3+y,2/3-x+y,2/3-z'
'+x-y,+x,-z'
'2/3+x-y,1/3+x,1/3-z'
'1/3+x-y,2/3+x,2/3-z'
'-y,-x,+z'
'2/3-y,1/3-x,1/3+z'
'1/3-y,2/3-x,2/3+z'
'-x+y,+y,+z'
'2/3-x+y,1/3+y,1/3+z'
'1/3-x+y,2/3+y,2/3+z'
'+x,+x-y,+z'
'2/3+x,1/3+x-y,1/3+z'
'1/3+x,2/3+x-y,2/3+z'

loop_
_atom_site_label
_atom_site_type_symbol
_atom_site_occupancy
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
    Bi    Bi 1.0000      0.0000    0.0000    0.3990
   Se1    Se 1.0000      0.0000    0.0000    0.0000
   Se2    Se 1.0000      0.0000    0.0000    0.2060

**Comment by balabi0github** [comment]
Hi, everyone. no one help?

**Comment by shyuep** [comment]
The min_slab_thickness and min_vacuum_thickness arguments to the SlabGenerator?

BTW, for questions on usage, please us the Google groups. Github issues is meant for reporting bugs and feature requests.
