### ISSUE TITLE
extract molecules from organic crystal

### ISSUE THREAD

**Issue by liwt31** [materialsproject/pymatgen#833]
If I've got a cif file for a small organic molecule crystal, how could I convert it to a Molecule object?

I've looked through the document but my closest match is some nearest neighbor algorithm... Maybe I've missed something?

If the feature is not yet implemented, I hope I can be of help. I plan to:
1. build a supercell according to cif file
2. find all possible molecules from that supercell
3. delete invalid and redundant ones

Any suggestions? Thank you all in advance.

**Comment by mkhorton** [comment]
I don't believe this is currently implemented (perhaps others can correct me) -- but I may be able to help implement something that does this. I think you're right that the closest we currently have is a nearest neighbour algorithm.

Do you have any constraints on your inputs? Do they just contain molecules, or are they organic-inorganic hybrids? Do you have any sample files to share?

**Comment by liwt31** [comment]
Thank you, @mkhorton ! In my case they're just molecules, and a sample of my cif file could be found in [https://gist.github.com/liwt31/cecfb19145e152f96d47702c817fd4da](https://gist.github.com/liwt31/cecfb19145e152f96d47702c817fd4da) . 

The cif file was downloaded from CCDC and I think it''s illegal to publish it online. So I'll delete the gist in one day. If anyone's still interested to it maybe I can share it by email.

**Comment by mkhorton** [comment]
Great, thanks! I should have time to implement this mid-week sometime.

The thing that makes this trickier is when the molecules go across the unit cell boundaries, if your cell only contains a single molecule it'd be easy to extract (just use structure.coords), or if it had multiple molecules, but again not across the unit cell boundary, you could use a clustering approach similar to what's in the break_bonds function. Hopefully we can get a fully general solution to this however.

**Comment by mkhorton** [comment]
Hi @liwt31 ,

Some basic functionality has been added this. It should work, but might be a little slow.

```
from pymatgen.analysis.graphs import StructureGraph
from pymatgen.analysis.local_env import JMolNN # used for deciding which atoms are bonded
sg = StructureGraph.with_local_env_strategy(my_structure, JMolNN())
my_molecules = sg.get_subgraphs_as_molecules()
```

(Code above assumes you've already loaded your organic crystal CIF as `my_structure`, and you'll need to `pip install networkx` to use the StructureGraph module.)

I might wrap this up as a convenience method somewhere once it's been tested more. If you find any bugs, let me know!

**Comment by liwt31** [comment]
Thanks! I think it's working. I'll report if I found any bugs in furture usage.

**Comment by CMUShuyang** [comment]
Hi @mkhorton ,

I  have cleaved an organic surface by some miller indices but I found some broken molecules in the slab. Thus, I plan to use this method to identify the broken molecules and delete them from my slabs. Could you please give me some suggestions about how to do that? Thanks so much!

**Comment by mkhorton** [comment]
Hi @misterblonde, try `JmolNN` with a lower-case `m`

**Comment by misterblonde** [comment]
If I call "JmolNN" with lower-case m, I don't get an error anymore, but I feel there is something wrong with the function, some infinite loop or something, because I have been waiting for >6 mins and nothing happens and the function is still running.

**Comment by majordt** [comment]
[I have a similar to question to the above: I have a cif file of molecules, and I'm creating a supercell and I want to be able to access the coordinates of the molecules of the original cell (each molecule individually), so that I can calculate distance distributions to other molecules (e.g., within minimum image convention). How can I do this? 

struct = Structure.from_file("227799.cif")
print(struct)
new_molecule = Molecule.from_sites(sorted(molecules[0], key=lambda site: site.species))
sg = StructureGraph.with_local_env_strategy(struct, JmolNN())
molecules = sg.get_subgraphs_as_molecules()

This only gives a single unique molecule (I want the central molecules in their original positions in the unit cell as molecular objects that I can [manipulate).](url)
Thanks,
Dan](url)

**Comment by danielpaluku** [comment]
I am actually wondering if it is possible to get a single molecule with labels of their corresponding atoms (C1, C2, S3...) not only string of atoms (C, C, S)?

**Comment by danielpaluku** [comment]
> That definitely does seem suspicious. JmolNN is actually one of the fastest since it’s a simple cut-off distance based approach. What version of pymatgen are you running? I can confirm JmolNN definitely works so we’d need some more info to track down the issue you’re seeing.
> […](#)

I am actually wondering if it is possible to get a single molecule with labels of their corresponding atoms (C1, C2, S3...) not only string of atoms (C, C, S)?
