### ISSUE TITLE
Error: Connection must be made over secure https.

### ISSUE THREAD

**Issue by bacalfa** [materialsproject/pymatgen#861]
## System

* Pymatgen version: `pymatgen==2017.9.23`
* Python version: 3.6.3
* OS version: Mac OS X 10.12.6

## Summary

Something wrong (apparently related to secure https) is happening in the call to `requests.post`. The same script I'm running used to work a while ago.

## Example code

You may consider the one in [this](https://discuss.materialsproject.org/t/mprester-query-crashing/519) discussion.

```
m = MPRester(my_api_key)
basic_properties = ['task_id','pretty_formula','reduced_cell_formula','unit_cell_formula','spacegroup.number','energy','formation_energy_per_atom','density']
electronic_properties = ['band_gap','efermi','total_magnetization']
elasticity_properties_prefix = ['elasticity']
all_properties = basic_properties + electronic_properties + elasticity_properties_prefix

# Query options
criteria = {"nelements": {"$lte": 3}, "elasticity": {"$exists": True}, "spacegroup.number": {"$exists": True}, "band_gap": {"$exists": True}}

# All properties: query response
results = m.query(criteria=criteria, properties=all_properties)
```

## Error message

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pymatgen/ext/matproj.py", line 150, in _make_request
    .format(response.status_code))
pymatgen.ext.matproj.MPRestError: REST query returned with error status code 403

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bacalfa/Documents/test.py", line 55, in <module>
    results = m.query(criteria=criteria, properties=all_properties)
  File "/usr/local/lib/python3.6/site-packages/pymatgen/ext/matproj.py", line 581, in query
    mp_decode=mp_decode)
  File "/usr/local/lib/python3.6/site-packages/pymatgen/ext/matproj.py", line 155, in _make_request
    raise MPRestError(msg)
pymatgen.ext.matproj.MPRestError: REST query returned with error status code 403. Content: b'Connection must be made over secure https.'

Process finished with exit code 1
```

This message about secure https also occurs when I access the example link on the Materials Project API website: `https://www.materialsproject.org/rest/v1/materials/Fe2O3/vasp?API_KEY=MyKey`, where `MyKey` is my personal key.

## Suggested solution (if any)

Sorry, don't know what to suggest. The `url` variable in the method `_make_request` does have "https" in it. Same thing via the website.

## Files (if any)

None.

**Comment by shyuep** [comment]
Materials project is down right now because of maintenance. This is not an
error in the code.

**Comment by bacalfa** [comment]
Makes sense! Thanks! :)

**Comment by mkhorton** [comment]
It should be back by Wednesday 11th, this is related to the NERSC maintenance detailed at http://www.nersc.gov/users/live-status/

If you're on materialsproject.org and logged in, you should see a status message about the outage.

**Comment by setten** [comment]
Ok thanks, I saw the message, which was clear on the topics mentioned. The python error message was a bit cryptic… :-)

**Comment by bacalfa** [comment]
It's back up! :)
