### ISSUE TITLE
Is it possible to convert symmetrized cif file to discard symmetry cif file while retaining the original inequivalent labels?

### ISSUE THREAD

**Issue by balabi0github** [materialsproject/pymatgen#895]
Dear developers,
     For example, I have a symmetrized cif file called "sym.cif" with spacegroup 31 and atom info like below

  Te  Te1  2  0.0000000000000  0.2072200000000  0.6463300000000  1
  Te  Te2  2  0.0000000000000  0.2984500000000  0.1022900000000  1
  Te  Te3  2  0.0000000000000  0.6463100000000  0.3535800000000  1
  Te  Te4  2  0.0000000000000  0.8576100000000  0.8977100000000  1
  W  W5  2  0.0000000000000  0.0398000000000  0.2576800000000  1
  W  W6  2  0.0000000000000  0.6006200000000  0.7424600000000  1

So there is totally 6 inequivalent atoms labeled Te1, Te2, Te3, Te4, W5, W6

However, if I discard symmetry of this cif file with below method

```
cif_file=r'r:\sym.cif'
struct=pymatgen.Structure.from_file(cif_file)
cif_file_obj=pymatgen.io.cif.CifWriter(struct)
print(cif_file_obj)
```
then I got this atom info

Te  Te1  1  0.0000000000000  0.2072200000000  0.6463300000000  1.0
  Te  Te2  1  0.5000000000000  0.7927800000000  0.1463300000000  1.0
  Te  Te3  1  0.0000000000000  0.2984500000000  0.1022900000000  1.0
  Te  Te4  1  0.5000000000000  0.7015500000000  0.6022900000000  1.0
  Te  Te5  1  0.0000000000000  0.6463100000000  0.3535800000000  1.0
  Te  Te6  1  0.5000000000000  0.3536900000000  0.8535800000000  1.0
  Te  Te7  1  0.0000000000000  0.8576100000000  0.8977100000000  1.0
  Te  Te8  1  0.5000000000000  0.1423900000000  0.3977100000000  1.0
  W  W9  1  0.0000000000000  0.0398000000000  0.2576800000000  1.0
  W  W10  1  0.5000000000000  0.9602000000000  0.7576800000000  1.0
  W  W11  1  0.0000000000000  0.6006200000000  0.7424600000000  1.0
  W  W12  1  0.5000000000000  0.3993800000000  0.2424600000000  1.0

So all atom got relabeled, and I lost the inequvalent atom infomation

What I want is a discard cif with labels to indicate inequivalent atoms like this

Te Te1  1.0  0.0  0.20722  0.64633
Te Te1  1.0  0.5  0.79278  0.14633
Te Te2  1.0  0.0  0.29845  0.10229
Te Te2  1.0  0.5  0.70155  0.60229
Te Te3  1.0  0.0  0.64631  0.35358
Te Te3  1.0  0.5  0.35369  0.85358
Te Te4  1.0  0.0  0.85761  0.89771
Te Te4  1.0  0.5  0.14239  0.39771
W  W5  1.0  0.0  0.0398  0.25768
W  W5  1.0  0.5  0.9602  0.75768
W  W6  1.0  0.0  0.60062  0.74246
W  W6  1.0  0.5  0.39938  0.24246

How to achieve this using pymatgen? Thank you very much

best regards

**Comment by shyuep** [comment]
You can write a script to do it.

**Comment by mkhorton** [comment]
Also the `SpacegroupAnalyzer.get_symmetrized_structure()` method can help with this by grouping equivalent sites, but there's no guarantee it'll get the same grouping as the original CIF (this depends on what tolerances you use for the symmetry analysis).
