### ISSUE TITLE
/lib64/libc.so.6: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by arosen93** [materialsproject/pymatgen#907]
I'm running into the following issue. Any ideas what I need to do to resolve the issue? I'm using a remote supercomputer so can't do anything to the central OS or anything like that.

## System

* Pymatgen version: 2017.11.6
* Python version: python 2.7.14
* OS version: SUSE Linux Enterprise Server 11

## Summary

Running into gcc issue

## Example code

```python
import pymatgen as pm
```

## Error message

```
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/arosen/software/anaconda2/lib/python2.7/site-packages/pymatgen/util/coord_cython.so)```
```

**Comment by shyuep** [comment]
HOw are you installing pymatgen? Conda or pip?

**Comment by arosen93** [comment]
Standard conda instructions. I've installed on other machines without
issue. I'm just not sure where to go from here.

**Comment by shyuep** [comment]
Try pip install pymatgen.

**Comment by arosen93** [comment]
Well, that seemed to fix that issue but introduced another. The full traceback:

```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arosen/software/anaconda2/lib/python2.7/site-packages/pymatgen/__init__.py", line 54, in <module>
    from pymatgen.core import *
  File "/home/arosen/software/anaconda2/lib/python2.7/site-packages/pymatgen/core/__init__.py", line 9, in <module>
    from .structure import Structure, IStructure, Molecule, IMolecule
  File "/home/arosen/software/anaconda2/lib/python2.7/site-packages/pymatgen/core/structure.py", line 30, in <module>
    from pymatgen.core.lattice import Lattice
  File "/home/arosen/software/anaconda2/lib/python2.7/site-packages/pymatgen/core/lattice.py", line 18, in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
  File "/home/arosen/software/anaconda2/lib/python2.7/site-packages/pymatgen/util/coord.py", line 11, in <module>
    from . import coord_cython as cuc
ImportError: /home/arosen/software/anaconda2/lib/python2.7/site-packages/pymatgen/util/coord_cython.so: undefined symbol: _intel_fast_memcpy
>>>
```

**Comment by arosen93** [comment]
I was able to fix it. Here is what I did:
1) Uninstalled Anaconda2
2) Installed Anaconda3
3) pip installed Pymatgen

I don't know if it was specifically switching to Python3 that fixed it or if it was uninstall Anaconda and starting fresh.

**Comment by shyuep** [comment]
No idea. In any case, I recommend you use Py3 going forward. It has definite speed (and coding) advantages.

**Comment by arosen93** [comment]
Me either, but at least it's fixed. I'll definitely stick with Py3 going forward. It's time.
