### ISSUE TITLE
density-density and velocity-velocity dielectric functions in VASP 5.4.4

### ISSUE THREAD

**Issue by bjmorgan** [materialsproject/pymatgen#940]
VASP 5.4.4 calculates the frequency dependent dielectric response in two ways, using a "density-density" response function, and using a "velocity-velocity" response function (see the comments in `linear_optics.F`. The latter is marked in `OUTCAR` as `current-current (2nd set in vasprun.xml)`, but is not labelled in `vasprun.xml`.

These two dielectric functions can have different imaginary components (in my tests, this appears as omega → 0.)

The present XML parser for `Vasprun` objects overwrites the first set of data with the second.

If both data sets are present in `vasprun.xml`, should these both be stored in the `Vasprun` object?

**Comment by shyuep** [comment]
YEs, these should be stored in the Vasprun object.
