### ISSUE TITLE
Infinite recursion in DummySpecie::__getattr_ when applying interstitial transformation leading to unpredictable behaviour.

### ISSUE THREAD

**Issue by gvdmarck** [materialsproject/pymatgen#942]
## System

* Pymatgen version: 2017.12.8
* Python version: 2.7.
* OS version: Ubuntu 15.04LTS

## Summary

- Pymatgen returns an error when trying to apply interstitial transformation with some structure. Issue has been tracked down to the DummeSpecie::getattr function which has an undefined behaviour in this context due to it infinitely calling itself and running out of stack space. 
## Example code
(see below for cif files)

import pymatgen as pmg
s = pmg.Structure.from_file('Li10Ge(PS6)2_mp-696128_computed.cif')
from pymatgen.transformations.defect_transformations import InterstitialTransformation
transfo = InterstitialTransformation('Li+',[1,1,1])
s.add_oxidation_state_by_element({"Li":1,"Ge":4,"P":5,"S":-2})
trans_list = transfo.apply_transformation(s, return_ranked_list=200)    ----> works fine

s2 = pmg.Structure.from_file('LiFeV2O7_prim.cif')
s2.add_oxidation_state_by_element({'Li':1,'Fe':3,'O':-2,'V':5})
trans_list = transfo.apply_transformation(s2, return_ranked_list=200) ---> crash

## Error message
```
_<ipython-input-10-7b1d34264ebe> in <module>()
----> 1 trans_list = transfo.apply_transformation(s2, return_ranked_list=200)

/usr/local/lib/python2.7/dist-packages/pymatgen/transformations/defect_transformations.pyc in apply_transformation(self, structure, return_ranked_list)
    282             val = valrad_eval.valences
    283             rad = valrad_eval.radii
--> 284             inter = Interstitial(s,val,rad,oxi_state=True)
    285 
    286         scs = inter.make_supercells_with_defects(

/usr/local/lib/python2.7/dist-packages/pymatgen/analysis/defects/point_defects.pyc in __init__(self, structure, valences, radii, site_type, accuracy, symmetry_flag, oxi_state)
    639         vor_node_sites, vor_edgecenter_sites, vor_facecenter_sites = \
    640             symmetry_reduced_voronoi_nodes(self._structure, self._rad_dict,
--> 641                                            high_accuracy_flag, symmetry_flag)
    642 
    643         if site_type == 'voronoi_vertex':

/usr/local/lib/python2.7/dist-packages/pymatgen/analysis/defects/point_defects.pyc in symmetry_reduced_voronoi_nodes(structure, rad_dict, high_accuracy_flag, symm_flag)
   1463 
   1464         node_dist_sites = get_dist_sites(vor_node_struct)
-> 1465         edgecenter_dist_sites = get_dist_sites(vor_edgecenter_struct)
   1466         facecenter_dist_sites = get_dist_sites(vor_facecenter_struct)
   1467 

/usr/local/lib/python2.7/dist-packages/pymatgen/analysis/defects/point_defects.pyc in get_dist_sites(vor_struct)
   1448                 vor_struct.merge_sites(0.1, 'delete')
   1449                 symmetry_finder = SpgA(vor_struct, symprec=1e-1)
-> 1450                 symm_struct = symmetry_finder.get_symmetrized_structure()
   1451             equiv_sites_list = symm_struct.equivalent_sites
   1452 

/usr/local/lib/python2.7/dist-packages/pymatgen/symmetry/analyzer.pyc in get_symmetrized_structure(self)
    337         """
    338         ds = self.get_symmetry_dataset()
--> 339         sg = SpacegroupOperations(self.get_space_group_symbol(),
    340                                   self.get_space_group_number(),
    341                                   self.get_symmetry_operations())

/usr/local/lib/python2.7/dist-packages/pymatgen/symmetry/analyzer.pyc in get_space_group_symbol(self)
    155             (str): Spacegroup symbol for structure.
    156         """
--> 157         return self._space_group_data["international"]
    158 
    159     def get_space_group_number(self):

TypeError: 'NoneType' object has no attribute '__getitem__'_
```

## Suggested solution (if any)

The issue is coming from that fact that when reading result from Zeo++, all atoms are of Dummyspecie type 'X0+'. The code then tries to initialize the space group analyser with this structure, and tries to assign the magmom property. It then encounters this line : 

`  elif site.is_ordered and hasattr(site.specie, 'spin'):`

which calls to the __getattr function of DummySpecie with 'spin' as  argument a: 
```

 def __ getattr __(self, a):
        p = object.__getattribute__(self, '_properties')
        if a in p:
            return p[a]
        try:
            return getattr(self._el, a)
        except:
            raise AttributeError(a)
```

Since DummySpecie has no properties, p is an empty dict, we therefore enter the try  with  "spin" as argument a.  The issue then is the _getattr(self._el,a)_  . Since DummySpecie has no '_el' attribute, the self._el calls again __getattr__ and infinite recursion occurs. 

In some cases (as the example with the first file) it is not an issue and python recovers correctly (as to how, I have no idea), in others, this cause python to skip the rest of the space group analyser initialisation, which results in its  _space_groupe_data not being initialised, leading to the subsequent crash.

Note that due to the unpredictable aspect, it might be that this behaviour is machine dependent. 

An obvious fix would be to immediately raise an AttributeError after the 'return p[a]' line, but I don't know what ripple effects it can have on the rest of the code base.

## Files (if any)
Li10Ge(PS6)2_mp-696128_computed.cif :

 generated using pymatgen
data_Li10Ge(PS6)2
_symmetry_space_group_name_H-M   'P 1'
_cell_length_a   8.78764647
_cell_length_b   8.78764647
_cell_length_c   12.65754627
_cell_angle_alpha   90.00000000
_cell_angle_beta   90.00000000
_cell_angle_gamma   90.00000000
_symmetry_Int_Tables_number   1
_chemical_formula_structural   Li10Ge(PS6)2
_chemical_formula_sum   'Li20 Ge2 P4 S24'
_cell_volume   977.450284168
_cell_formula_units_Z   2
loop_
 _symmetry_equiv_pos_site_id
 _symmetry_equiv_pos_as_xyz
  1  'x, y, z'
loop_
 _atom_site_type_symbol
 _atom_site_label
 _atom_site_symmetry_multiplicity
 _atom_site_fract_x
 _atom_site_fract_y
 _atom_site_fract_z
 _atom_site_occupancy
  Li  Li1  1  0.228698  0.772950  0.294563  1
  Li  Li2  1  0.771302  0.227050  0.294563  1
  Li  Li3  1  0.272950  0.271302  0.794563  1
  Li  Li4  1  0.727050  0.728698  0.794563  1
  Li  Li5  1  0.228698  0.227050  0.294563  1
  Li  Li6  1  0.771302  0.772950  0.294563  1
  Li  Li7  1  0.272950  0.728698  0.794563  1
  Li  Li8  1  0.727050  0.271302  0.794563  1
  Li  Li9  1  0.000000  0.500000  0.939730  1
  Li  Li10  1  0.000000  0.500000  0.439730  1
  Li  Li11  1  0.500000  0.000000  0.548020  1
  Li  Li12  1  0.500000  0.000000  0.048020  1
  Li  Li13  1  0.256318  0.224772  0.036663  1
  Li  Li14  1  0.743682  0.775228  0.036663  1
  Li  Li15  1  0.275228  0.756318  0.536663  1
  Li  Li16  1  0.724772  0.243682  0.536663  1
  Li  Li17  1  0.275228  0.243682  0.536663  1
  Li  Li18  1  0.724772  0.756318  0.536663  1
  Li  Li19  1  0.256318  0.775228  0.036663  1
  Li  Li20  1  0.743682  0.224772  0.036663  1
  Ge  Ge21  1  0.500000  0.000000  0.801028  1
  Ge  Ge22  1  0.500000  0.000000  0.301028  1
  P  P23  1  0.000000  0.500000  0.686051  1
  P  P24  1  0.000000  0.500000  0.186051  1
  P  P25  1  0.000000  0.000000  0.504073  1
  P  P26  1  0.500000  0.500000  0.004073  1
  S  S27  1  0.000000  0.194431  0.412071  1
  S  S28  1  0.000000  0.805569  0.412071  1
  S  S29  1  0.305569  0.500000  0.912071  1
  S  S30  1  0.694431  0.500000  0.912071  1
  S  S31  1  0.500000  0.689848  0.097057  1
  S  S32  1  0.500000  0.310152  0.097057  1
  S  S33  1  0.189848  0.000000  0.597057  1
  S  S34  1  0.810152  0.000000  0.597057  1
  S  S35  1  0.000000  0.304708  0.094096  1
  S  S36  1  0.000000  0.695292  0.094096  1
  S  S37  1  0.195292  0.500000  0.594096  1
  S  S38  1  0.804708  0.500000  0.594096  1
  S  S39  1  0.500000  0.790002  0.403242  1
  S  S40  1  0.500000  0.209998  0.403242  1
  S  S41  1  0.290002  0.000000  0.903242  1
  S  S42  1  0.709998  0.000000  0.903242  1
  S  S43  1  0.000000  0.691950  0.777069  1
  S  S44  1  0.000000  0.308050  0.777069  1
  S  S45  1  0.808050  0.500000  0.277069  1
  S  S46  1  0.191950  0.500000  0.277069  1
  S  S47  1  0.500000  0.207378  0.698166  1
  S  S48  1  0.500000  0.792622  0.698166  1
  S  S49  1  0.707378  0.000000  0.198166  1
  S  S50  1  0.292622  0.000000  0.198166  1

LiFeV2O7_prim.cif :

generated using pymatgen
data_LiV2FeO7
_symmetry_space_group_name_H-M   'P 1'
_cell_length_a   7.87875289
_cell_length_b   7.87875289
_cell_length_c   14.38600000
_cell_angle_alpha   84.40963056
_cell_angle_beta   84.40963056
_cell_angle_gamma   62.61595511
_symmetry_Int_Tables_number   1
_chemical_formula_structural   LiV2FeO7
_chemical_formula_sum   'Li6 V12 Fe6 O42'
_cell_volume   787.769007978
_cell_formula_units_Z   6
loop_
 _symmetry_equiv_pos_site_id
 _symmetry_equiv_pos_as_xyz
  1  'x, y, z'
loop_
 _atom_site_type_symbol
 _atom_site_label
 _atom_site_symmetry_multiplicity
 _atom_site_fract_x
 _atom_site_fract_y
 _atom_site_fract_z
 _atom_site_occupancy
  Fe  Fe1  1  0.444800  0.094600  0.524500  1.0
  Fe  Fe2  1  0.094600  0.444800  0.024500  1.0
  Fe  Fe3  1  0.717400  0.116200  0.198100  1.0
  Fe  Fe4  1  0.116200  0.717400  0.698100  1.0
  Fe  Fe5  1  0.423400  0.811600  0.854500  1.0
  Fe  Fe6  1  0.811600  0.423400  0.354500  1.0
  Li  Li7  1  0.731400  0.378600  0.857200  1.0
  Li  Li8  1  0.378600  0.731400  0.357200  1.0
  Li  Li9  1  0.128500  0.753300  0.189400  1.0
  Li  Li10  1  0.753300  0.128500  0.689400  1.0
  Li  Li11  1  0.066000  0.456800  0.535100  1.0
  Li  Li12  1  0.456800  0.066000  0.035100  1.0
  O  O13  1  0.317800  0.953000  0.468700  1.0
  O  O14  1  0.953000  0.317800  0.968700  1.0
  O  O15  1  0.264700  0.577300  0.292200  1.0
  O  O16  1  0.577300  0.264700  0.792200  1.0
  O  O17  1  0.662800  0.647000  0.778300  1.0
  O  O18  1  0.647000  0.662800  0.278300  1.0
  O  O19  1  0.943400  0.215800  0.457100  1.0
  O  O20  1  0.215800  0.943400  0.957100  1.0
  O  O21  1  0.298800  0.326400  0.446000  1.0
  O  O22  1  0.326400  0.298800  0.946000  1.0
  O  O23  1  0.665300  0.980100  0.436100  1.0
  O  O24  1  0.980100  0.665300  0.936100  1.0
  O  O25  1  0.940600  0.647600  0.631800  1.0
  O  O26  1  0.647600  0.940600  0.131800  1.0
  O  O27  1  0.341900  0.080100  0.787200  1.0
  O  O28  1  0.080100  0.341900  0.287200  1.0
  O  O29  1  0.041000  0.979000  0.623500  1.0
  O  O30  1  0.979000  0.041000  0.123500  1.0
  O  O31  1  0.709900  0.473500  0.608800  1.0
  O  O32  1  0.473500  0.709900  0.108800  1.0
  O  O33  1  0.553600  0.872800  0.616600  1.0
  O  O34  1  0.872800  0.553600  0.116600  1.0
  O  O35  1  0.890600  0.592200  0.419200  1.0
  O  O36  1  0.592200  0.890600  0.919200  1.0
  O  O37  1  0.061900  0.827700  0.441900  1.0
  O  O38  1  0.827700  0.061900  0.941900  1.0
  O  O39  1  0.875300  0.869700  0.272400  1.0
  O  O40  1  0.869700  0.875300  0.772400  1.0
  O  O41  1  0.569300  0.495300  0.433500  1.0
  O  O42  1  0.495300  0.569300  0.933500  1.0
  O  O43  1  0.956600  0.230000  0.758900  1.0
  O  O44  1  0.230000  0.956600  0.258900  1.0
  O  O45  1  0.315700  0.603500  0.592000  1.0
  O  O46  1  0.603500  0.315700  0.092000  1.0
  O  O47  1  0.481100  0.199100  0.272800  1.0
  O  O48  1  0.199100  0.481100  0.772800  1.0
  O  O49  1  0.249100  0.827300  0.762500  1.0
  O  O50  1  0.827300  0.249100  0.262500  1.0
  O  O51  1  0.206300  0.207300  0.612700  1.0
  O  O52  1  0.207300  0.206300  0.112700  1.0
  O  O53  1  0.573200  0.220000  0.580600  1.0
  O  O54  1  0.220000  0.573200  0.080600  1.0
  V  V55  1  0.868600  0.815200  0.389900  1.0
  V  V56  1  0.815200  0.868600  0.889900  1.0
  V  V57  1  0.534200  0.450200  0.550900  1.0
  V  V58  1  0.450200  0.534200  0.050900  1.0
  V  V59  1  0.159100  0.085900  0.709000  1.0
  V  V60  1  0.085900  0.159100  0.209000  1.0
  V  V61  1  0.717800  0.666400  0.661700  1.0
  V  V62  1  0.666400  0.717800  0.161700  1.0
  V  V63  1  0.283700  0.364500  0.325800  1.0
  V  V64  1  0.364500  0.283700  0.825800  1.0
  V  V65  1  0.090300  0.999100  0.499100  1.0
  V  V66  1  0.999100  0.090300  0.999100  1.0

**Comment by mkhorton** [comment]
Thanks for the detailed bug report. Since `DummySpecie` doesn't have `._el` defined, I can't see why the try:

```
        try:
            return getattr(self._el, a)
```

should even be there, because it seems like this would never return anything useful for `DummySpecie`. I'll try removing it and see if any tests fail, and if not then submit a PR.

In the longer term, I think a conversation about the relationship between Element-Specie-DummySpecie and specie properties vs site properties might be useful. I think there's a historical reason why e.g. Specie doesn't inherit from Element, but overriding getattr is problematic, if only because it causes confusion with new users since it breaks autocomplete.

**Comment by shyuep** [comment]
Thanks for the bug report. I just pushed a fix. I think someone simply copied the getattr from Specie to DummySpecie. self._el is valid for Specie. 

The reason why Element, Specie and DummySpecie are not subclasses is mainly because Element is an Enum, which cannot be extended. Previously, Element is a singleton-like, which also cannot be inherited. It is actually important for efficiency reasons to keep Element as an Enum type.

So the approach pymatgen uses is to rely on duck-typing to make Specie and DummySpecie behave like Element where possible, e.g., inheriting things such as atomic numbers, masses, etc.
