### ISSUE TITLE
PDPlotter.plot_element_profile

### ISSUE THREAD

**Issue by shyuep** [materialsproject/pymatgen#945]
Right now, someone has to manually plot the element profile from pd.get_element_profile. A simple PDPlotter.plot_element_profile should be added.

@Zhuoying to implement

**Comment by Zhuoying** [comment]
Done with the implementation as a method in PDPlotter. The result of testing case (Na3PS4 under different Na chemical potential) is shown below (selected profile step products are annotated in the plot):

index= 0, -Δμ=-0.0000(eV), 2 Na3PS4 + 16 Na -> 2 Na3P + 8 Na2S
index= 1, -Δμ=0.2945(eV), 2 Na3PS4 + 12 Na -> 8 Na2S + 2 NaP
index= 2, -Δμ=0.6391(eV), 2 Na3PS4 + 10.55 Na -> 0.1818 Na3P11 + 8 Na2S
index= 3, -Δμ=1.1448(eV), 2 Na3PS4 + 10 Na -> 2 P + 8 Na2S
index= 4, -Δμ=1.1623(eV), 2 Na3PS4 -> 2 Na3PS4
index= 5, -Δμ=2.4944(eV), 2 Na3PS4 -> P2S5 + 3 S + 6 Na
![image](https://user-images.githubusercontent.com/10410019/34067523-f86674f2-e1dc-11e7-93d1-6fe721f74adc.png)
