### ISSUE TITLE
Reduced oriented_unit_cell

### ISSUE THREAD

**Issue by richardtran415** [materialsproject/pymatgen#950]
To ensure that the surface energy does not diverge wrt slab size for some systems, we need to calculate an oriented unit cell with a kpoint grid consistent with the slab to sample the Brillouin zone of the slab. So both the OUC and slab have to be calculated. 

Right now when generating an OUC and reduced slab, the lattice vectors in the a and b direction are sometimes inconsistent with the OUC and so sometimes, we are stuck with calculating a larger slab size to keep the kpoints consistent with the OUC instead of just significantly smaller reduced slab.

We can actually reduced the OUC further in order to make it consistent with the reduced slab. This will make surface calculations much faster, as long as the c lattice vector is maintained (i.e. we want to reduce the OUC along the a and b vector only).

1. Get the OUC
2. Break the symmetry along the c direction by adding a vacuum.
3. Use get_primitive cell() on the new system (because symmetry is broken along c, only the a and b vectors are reduced)
4. Remove the vacuum from this reduced system.

The resulting OUC should now have a consistent a and b lattice vector with the slab. Now not only are the slab calculations cheaper, but the OUC calculations as well.

**Comment by shyuep** [comment]
Ok. But I don't think you need to artificially add a vacuum to reduce the unit cell. That would work, but it is an inelegant approach. 

All you need to do is to modify the get_primitive of the structure method to provide an option to only search in certain directions and disallow modification of the c direction.

**Comment by richardtran415** [comment]
In that case, then perhaps an optional parameter for get_primitive_structure() to say "limit reduction to these particular directions" could be useful. And by default it would just work normally as it does now.
