### ISSUE TITLE
add absorption coefficient method

### ISSUE THREAD

**Issue by zbwang** [materialsproject/pymatgen#951]
The optical absorption coefficient can be calculated from dielectric tensors. The dielectric tensors have been well processed with pymatgen. It will be more user-friendly if pymatgen could directly produce this optical property.

**Comment by shyuep** [comment]
@zbwang to implement.

**Comment by bjmorgan** [comment]
I have code that does this, using `Vasprun.dielectric`. I’d be happy to contribute it. What would be the preferred way to access this? A `Vasprun.optical_absorption` property?

**Comment by zbwang** [comment]
Hi bjmorgan, thanks for your contribution. This is a topic I come up with for our biweekly hackathon held in MAVRL group. I have placed a PR to fix this issue. ,

Also, I have a question to seek advice from you. Do you know what is the difference btw dielectric functions calculated with "density-density" and "velocity-velocity" linear response functions?
In the VASP source code, they state these are "two equivalent ways". The values in vasprun.xml of these two methods, however, are totally different. The dielectric constants calc by "density-density" in OUTCAR is called "current-current (2nd set in vasprun.xml)", though they have the same meaning.

**Comment by bjmorgan** [comment]
Hi @zbwang. I would need to do a lot more reading to follow the difference between the two methods. In my limited tests they give the same result at high frequencies, but diverge as w goes to zero, with the “velocity-velocity” looking unphysical. From looking at the VASP source code, the “density-density” function appears to be the same as in earlier versions. The “velocity-velocity” function is called “current-current” in OUTCAR, which confuses things.
