### ISSUE TITLE
Element.name returns the symbol but not the long name of element

### ISSUE THREAD

**Issue by specter119** [materialsproject/pymatgen#963]
When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.

## System

* Pymatgen version: 2017.12.16
* Python version: python 3.6.3 (anaconda)
* OS version: macOS 10.13.2

## Summary

Element.name returns the symbol but not the long name

## Example code

```python
from pymatgen.core.periodic_table import Element
Element("H").name
Element("H").symbol
```

all return with "H"

**Comment by shyuep** [comment]
This was a bug introduced when we switched Element to a Enum type. Basically, "name" is a reserved attribute for Enums. 

Since no one else seems to be missing this feature, I have renamed Element.name to Element.long_name and added a unittest to make sure it does not disappear again.

**Comment by specter119** [comment]
@shyuep thanks.
