### ISSUE TITLE
Cannot find get_projections_on_elts_and_orbitals

### ISSUE THREAD

**Issue by xfsm1912** [materialsproject/pymatgen#967]
When reporting bugs/issues, please supply the following information. If
this is a feature request, please simply state the requested feature.

## System

* Pymatgen version:pymatgen:    2017.12.16-py36_0 
* Python version: python3.6
* OS version: 10.13.2

## Summary

I run the band plot code from https://github.com/gVallverdu/bandstructureplots/tree/master/Cu_bands. But cannot run this command:
pbands = bands.get_projections_on_elts_and_orbitals({name: ["s", "p", "d"]})

## Example code

```python
# Example code generating error
```
bands = run.get_band_structure("./Bandes/KPOINTS",
                                   line_mode=True,
                                   efermi=dosrun.efermi)

pbands = bands.get_projections_on_elts_and_orbitals({name: ["s", "p", "d"]})

```
AttributeError: 'BandStructureSymmLine' object has no attribute 'get_projections_on_elts_and_orbitals'
```

## Suggested solution (if any)

* If you have a suggestion on how to solve the issue, you may write it
  here.

## Files (if any)

* If input files are needed to reproduce the error, please provide 
either links (e.g., Dropbox or GDrive) for large files or simply paste
the file below for small files.

```
<contents of file 1>
```

**Comment by zbwang** [comment]
The tutorials you are referring to use an ancient pymatgen. This functionality has actually been implemented into pymatgen by Dr Anubhav Jain. Pls take a look at the class BSDOSPlotter in pymatgen.electronic_structure.plotter module.
```from pymatgen.electronic_structure.plotter import BSDOSPlotter```

**Comment by xfsm1912** [comment]
if I use from pymatgen.electronic_structure.plotter import BSDOSPlotter, how can I edit the detials in the plot? such as number font, line color, to plot better figures like Dr Jain did? from you example, BSDOSPlotter only can give very simple and rough plot (http://pymatgen.org/_static/Analyze%20and%20plot%20band%20structures.html)
