### ISSUE TITLE
Cann't find get_environments.py) in the pymatgen/scripts directory

### ISSUE THREAD

**Issue by AlienMarkWong** [materialsproject/pymatgen#978]
## System
* Pymatgen version: 2017.9.23
* Python version: 3.5

## Summary
* Cann't find get_environments.py and pymatgen/scripts directory
* Please provide some examples about analyzing chemical environments and coordination geometries

**Comment by shyuep** [comment]
@davidwaroquiers Pls handle.

**Comment by davidwaroquiers** [comment]
A tutorial is currently being written. Be patient it should be out in a few weeks.
The get_environments.py script has been moved to pymatgen/cli

**Comment by JaGeo** [comment]
The tutorial can now be accessed via http://matgenb.materialsvirtuallab.org/2018/01/01/ChemEnv-How-to-automatically-identify-coordination-environments-in-a-structure.html .
