### ISSUE TITLE
Surface energy predictor web app

### ISSUE THREAD

**Issue by richardtran415** [materialsproject/pymatgen#989]
A Materials Project web app that allows the user to enter in an MPID or element and a Miller index and in return, will get a surface energy. 

With the addition of the surface data into the MAPI, we can use simple broken bond rules to extrapolate a cohesive energy term and use that cohesive energy to predict surface energy of facets that are not present in the database. The app will do this every time a user enters in a Miller index not present in the MAPI and the app will also return statistical data such as how accurate the prediction is based on R2 and standard error of estimate of existing data.

**Comment by shyuep** [comment]
This is fine, but it is not a pymatgen Issue. Also, I need to be convinced of the fact that broken bond extrapolation will lead to reasonable estimates.
